DECL|enumerator|Ain
DECL|enumerator|Alaph
DECL|enumerator|Alef
DECL|enumerator|ArabicGroupsEnd
DECL|enumerator|ArabicNone
DECL|enumerator|ArabicSpace
DECL|enumerator|Beh
DECL|enumerator|Beth
DECL|enumerator|Center
DECL|enumerator|Dal
DECL|enumerator|Dalath
DECL|enumerator|Dummy
DECL|enumerator|Fe
DECL|enumerator|Feh
DECL|enumerator|FinalSemakh
DECL|enumerator|Gaf
DECL|enumerator|Gamal
DECL|enumerator|Hah
DECL|enumerator|HamzaOnHehGoal
DECL|enumerator|He
DECL|enumerator|Heh
DECL|enumerator|HehGoal
DECL|enumerator|Heth
DECL|enumerator|JCausing
DECL|enumerator|JDual
DECL|enumerator|JNone
DECL|enumerator|JRight
DECL|enumerator|JTransparent
DECL|enumerator|Kaf
DECL|enumerator|Kaph
DECL|enumerator|Kashida
DECL|enumerator|KnottedHeh
DECL|enumerator|Lam
DECL|enumerator|Lamadh
DECL|enumerator|Meem
DECL|enumerator|Mim
DECL|enumerator|Noon
DECL|enumerator|Nun
DECL|enumerator|Pe
DECL|enumerator|Qaf
DECL|enumerator|Qaph
DECL|enumerator|Reh
DECL|enumerator|ReversedPe
DECL|enumerator|Sad
DECL|enumerator|Sadhe
DECL|enumerator|Seen
DECL|enumerator|Semakh
DECL|enumerator|Shin
DECL|enumerator|SwashKaf
DECL|enumerator|SyriacE
DECL|enumerator|SyriacWaw
DECL|enumerator|Tah
DECL|enumerator|Taw
DECL|enumerator|TehMarbuta
DECL|enumerator|Teth
DECL|enumerator|Transparent
DECL|enumerator|Waw
DECL|enumerator|XCausing
DECL|enumerator|XFinal
DECL|enumerator|XInitial
DECL|enumerator|XIsolated
DECL|enumerator|XMedial
DECL|enumerator|Yeh
DECL|enumerator|YehBarre
DECL|enumerator|YehWithTail
DECL|enumerator|Yudh
DECL|enumerator|YudhHe
DECL|enumerator|Zain
DECL|enum|ArabicGroup
DECL|enum|Joining
DECL|enum|QArabicShape
DECL|function|arabicGroup
DECL|function|heuristicSetGlyphAttributes
DECL|function|qt_getArabicProperties
DECL|function|shapeTextMac
DECL|member|form1
DECL|member|form2
DECL|member|justification
DECL|member|shape
DECL|struct|JoiningPair
DECL|struct|QArabicProperties
DECL|variable|arabic_group
DECL|variable|joining_for_group
DECL|variable|joining_table
