DECL|class|AutoIgnoreInvalidParameter
DECL|class|MessageHandler
DECL|class|MyEngine
DECL|class|MyHandler
DECL|class|MyHandler2
DECL|class|MyRecursiveHandler
DECL|class|tst_QFile
DECL|enumerator|NumberOfFileTypes
DECL|enumerator|OpenFd
DECL|enumerator|OpenQFile
DECL|enumerator|OpenStream
DECL|enum|FileType
DECL|function|AutoIgnoreInvalidParameter
DECL|function|FILEReadWrite
DECL|function|MessageHandler
DECL|function|MyEngine
DECL|function|absolutePathLinkToRelativePath
DECL|function|append
DECL|function|appendAndRead
DECL|function|at
DECL|function|atEnd
DECL|function|autocloseHandle
DECL|function|bufferedRead
DECL|function|caseSensitive
DECL|function|caseSensitivity
DECL|function|chmod
DECL|function|cleanup
DECL|function|cleanupTestCase
DECL|function|close
DECL|function|closeFile
DECL|function|copy
DECL|function|copy
DECL|function|copyAfterFail
DECL|function|copyFallback
DECL|function|copyRemovesTemporaryFile
DECL|function|copyShouldntOverwrite
DECL|function|create
DECL|function|create
DECL|function|create
DECL|function|createFile
DECL|function|driveLetters
DECL|function|encodeName
DECL|function|entryList
DECL|function|exists
DECL|function|fileEngineHandler
DECL|function|fileFlags
DECL|function|fileName
DECL|function|fileTime
DECL|function|flush
DECL|function|flush
DECL|function|fullDisk
DECL|function|getCharFF
DECL|function|getLargeDataBlock
DECL|function|getWorkingDirectoryForLink
DECL|function|getch
DECL|function|handle
DECL|function|handler
DECL|function|i18nFileName
DECL|function|i18nFileName_data
DECL|function|ignore_invalid_parameter
DECL|function|init
DECL|function|initTestCase
DECL|function|invalidDriveLetter
DECL|function|invalidFile
DECL|function|invalidFile_data
DECL|function|isRelativePath
DECL|function|isSequential
DECL|function|isSequential
DECL|function|largeUncFileSupport
DECL|function|link
DECL|function|link
DECL|function|linkToDir
DECL|function|longFileName
DECL|function|longFileName_data
DECL|function|map
DECL|function|mapOpenMode
DECL|function|mapOpenMode_data
DECL|function|mapResource
DECL|function|mapResource_data
DECL|function|map_data
DECL|function|miscWithUncPathAsCurrentDir
DECL|function|missingEndOfLine
DECL|function|mkdir
DECL|function|nativeHandleLeaks
DECL|function|objectConstructors
DECL|function|open
DECL|function|open
DECL|function|openDirectory
DECL|function|openFd
DECL|function|openFile
DECL|function|openStandardStreamsBufferedStreams
DECL|function|openStandardStreamsFileDescriptors
DECL|function|openStream
DECL|function|openUnbuffered
DECL|function|open_data
DECL|function|owner
DECL|function|ownerId
DECL|function|permissions
DECL|function|permissionsNtfs
DECL|function|permissionsNtfs_data
DECL|function|permissions_data
DECL|function|posAfterFailedStat
DECL|function|read
DECL|function|readAll
DECL|function|readAllBuffer
DECL|function|readAllStdin
DECL|function|readAll_data
DECL|function|readBlock
DECL|function|readBrokenLink
DECL|function|readEof
DECL|function|readEof_data
DECL|function|readFromWriteOnlyFile
DECL|function|readLine
DECL|function|readLine2
DECL|function|readLineNullInLine
DECL|function|readLineStdin
DECL|function|readLineStdin_lineByLine
DECL|function|readTextFile
DECL|function|readTextFile2
DECL|function|readTextFile_data
DECL|function|remove
DECL|function|removeOpenFile
DECL|function|remove_and_exists
DECL|function|rename
DECL|function|rename
DECL|function|renameFallback
DECL|function|renameMultiple
DECL|function|renameWithAtEndSpecialFile
DECL|function|rename_data
DECL|function|resize
DECL|function|resize_data
DECL|function|rmdir
DECL|function|seek
DECL|function|seek
DECL|function|seekAfterEndOfFile
DECL|function|seekToPos
DECL|function|setFileName
DECL|function|setPermissions
DECL|function|setSize
DECL|function|setSize
DECL|function|setSizeSeek
DECL|function|size
DECL|function|size
DECL|function|sizeNoExist
DECL|function|size_data
DECL|function|standarderror
DECL|function|streamCurrentPosition
DECL|function|streamCurrentPosition
DECL|function|streamExpectedSize
DECL|function|testPassed
DECL|function|text
DECL|function|textFile
DECL|function|truncate
DECL|function|ungetChar
DECL|function|useQFileInAFileHandler
DECL|function|virtualFile
DECL|function|write
DECL|function|writeLargeDataBlock
DECL|function|writeLargeDataBlock_data
DECL|function|writeNothing
DECL|function|writeTextFile
DECL|function|writeTextFile_data
DECL|function|writeToReadOnlyFile
DECL|function|~AutoIgnoreInvalidParameter
DECL|function|~MessageHandler
DECL|function|~MyEngine
DECL|macro|FILESIZE
DECL|macro|QT_OPEN_BINARY
DECL|macro|STDERR_FILENO
DECL|macro|STDIN_FILENO
DECL|macro|STDOUT_FILENO
DECL|member|fd_
DECL|member|name
DECL|member|number
DECL|member|ok
DECL|member|ok
DECL|member|oldHandler
DECL|member|oldMessageHandler
DECL|member|oldMessageHandler
DECL|member|oldReportMode
DECL|member|stream_
