DECL|class|DeleteTester
DECL|class|MyGraphicsObject
DECL|class|tst_QGraphicsObject
DECL|function|DeleteTester
DECL|function|MyGraphicsObject
DECL|function|boundingRect
DECL|function|boundingRect
DECL|function|cleanup
DECL|function|cleanupTestCase
DECL|function|deleted
DECL|function|enabled
DECL|function|init
DECL|function|initTestCase
DECL|function|opacity
DECL|function|paint
DECL|function|paint
DECL|function|pos
DECL|function|visible
DECL|function|x
DECL|function|y
DECL|function|z
DECL|function|~DeleteTester
DECL|member|parentWasDeleted
DECL|member|wasDeleted
