DECL|class|QOffscreenX11GLXContextData
DECL|class|QOffscreenX11Info
DECL|function|QOffscreenX11Connection
DECL|function|QOffscreenX11GLXContext
DECL|function|QOffscreenX11Info
DECL|function|createDummyWindow
DECL|function|createDummyWindow
DECL|function|createOffscreenIntegration
DECL|function|createPlatformOpenGLContext
DECL|function|display
DECL|function|doneCurrent
DECL|function|format
DECL|function|getProcAddress
DECL|function|hasCapability
DECL|function|isSharing
DECL|function|isValid
DECL|function|makeCurrent
DECL|function|root
DECL|function|screenNumber
DECL|function|swapBuffers
DECL|function|x11Info
DECL|function|~QOffscreenX11Connection
DECL|function|~QOffscreenX11GLXContext
DECL|member|context
DECL|member|format
DECL|member|m_connection
DECL|member|shareContext
DECL|member|window
DECL|member|x11
