DECL|class|QOffscreenCursor
DECL|function|QOffscreenBackingStore
DECL|function|QOffscreenCursor
DECL|function|QOffscreenScreen
DECL|function|backingStoreForWinId
DECL|function|clearHash
DECL|function|flush
DECL|function|grabWindow
DECL|function|grabWindow
DECL|function|paintDevice
DECL|function|resize
DECL|function|scroll
DECL|function|~QOffscreenBackingStore
DECL|member|m_backingStoreForWinIdHash
DECL|member|m_pos
DECL|member|windowContainingCursor
