DECL|class|QEglFSAndroidHooks
DECL|function|createCursor
DECL|function|createNativeWindow
DECL|function|destroyNativeWindow
DECL|function|hasCapability
DECL|function|logicalDpi
DECL|function|physicalScreenSize
DECL|function|platformDestroy
DECL|function|platformDisplay
DECL|function|platformInit
DECL|function|screenDepth
DECL|function|screenSize
DECL|function|surfaceFormatFor
DECL|variable|eglFSAndroidHooks
DECL|variable|platformHooks
