DECL|class|QSocketEngineHandlerList
DECL|function|QAbstractSocketEngine
DECL|function|QAbstractSocketEngine
DECL|function|QAbstractSocketEnginePrivate
DECL|function|QSocketEngineHandler
DECL|function|connectionNotification
DECL|function|createSocketEngine
DECL|function|createSocketEngine
DECL|function|error
DECL|function|errorString
DECL|function|exceptionNotification
DECL|function|localAddress
DECL|function|localPort
DECL|function|peerAddress
DECL|function|peerPort
DECL|function|protocol
DECL|function|proxyAuthenticationRequired
DECL|function|readNotification
DECL|function|setError
DECL|function|setLocalAddress
DECL|function|setLocalPort
DECL|function|setPeerAddress
DECL|function|setPeerPort
DECL|function|setProtocol
DECL|function|setReceiver
DECL|function|setSocketType
DECL|function|setState
DECL|function|socketType
DECL|function|state
DECL|function|writeNotification
DECL|function|~QSocketEngineHandler
DECL|member|mutex
