DECL|function|QAbstractSocket
DECL|function|QAbstractSocket
DECL|function|QAbstractSocketPrivate
DECL|function|_q_abortConnectionAttempt
DECL|function|_q_connectToNextAddress
DECL|function|_q_forceDisconnect
DECL|function|_q_startConnecting
DECL|function|_q_testConnection
DECL|function|abort
DECL|function|atEnd
DECL|function|bind
DECL|function|bind
DECL|function|bytesAvailable
DECL|function|bytesToWrite
DECL|function|canReadLine
DECL|function|canReadNotification
DECL|function|canWriteNotification
DECL|function|close
DECL|function|connectToHost
DECL|function|connectToHost
DECL|function|connectionNotification
DECL|function|disconnectFromHost
DECL|function|error
DECL|function|fetchConnectionParameters
DECL|function|flush
DECL|function|flush
DECL|function|getSocketEngine
DECL|function|initSocketLayer
DECL|function|isProxyError
DECL|function|isSequential
DECL|function|isValid
DECL|function|localAddress
DECL|function|localPort
DECL|function|operator <<
DECL|function|operator <<
DECL|function|pauseSocketNotifiers
DECL|function|peerAddress
DECL|function|peerName
DECL|function|peerPort
DECL|function|proxy
DECL|function|qt_prettyDebug
DECL|function|qt_timeout_value
DECL|function|readBufferSize
DECL|function|readData
DECL|function|readFromSocket
DECL|function|readLineData
DECL|function|resetSocketLayer
DECL|function|resolveProxy
DECL|function|resumeSocketNotifiers
DECL|function|setLocalAddress
DECL|function|setLocalPort
DECL|function|setPeerAddress
DECL|function|setPeerName
DECL|function|setPeerPort
DECL|function|setProxy
DECL|function|setReadBufferSize
DECL|function|setSocketDescriptor
DECL|function|setSocketError
DECL|function|setSocketOption
DECL|function|setSocketState
DECL|function|socketDescriptor
DECL|function|socketOption
DECL|function|socketType
DECL|function|startConnectingByName
DECL|function|state
DECL|function|waitForBytesWritten
DECL|function|waitForConnected
DECL|function|waitForDisconnected
DECL|function|waitForReadyRead
DECL|function|writeData
DECL|function|~QAbstractSocket
DECL|function|~QAbstractSocketPrivate
DECL|macro|QABSTRACTSOCKET_BUFFERSIZE
DECL|macro|QT_CONNECT_TIMEOUT
DECL|macro|QT_TRANSFER_TIMEOUT
DECL|macro|Q_CHECK_SOCKETENGINE
