DECL|function|QLocalSocketPrivate
DECL|function|_q_canWrite
DECL|function|_q_pipeClosed
DECL|function|_q_winError
DECL|function|abort
DECL|function|bytesAvailable
DECL|function|bytesToWrite
DECL|function|canReadLine
DECL|function|close
DECL|function|connectToServer
DECL|function|destroyPipeHandles
DECL|function|disconnectFromServer
DECL|function|error
DECL|function|flush
DECL|function|init
DECL|function|isValid
DECL|function|readBufferSize
DECL|function|readData
DECL|function|setErrorString
DECL|function|setReadBufferSize
DECL|function|setSocketDescriptor
DECL|function|socketDescriptor
DECL|function|waitForBytesWritten
DECL|function|waitForConnected
DECL|function|waitForDisconnected
DECL|function|waitForReadyRead
DECL|function|writeData
DECL|function|~QLocalSocketPrivate
