DECL|macro|QNATIVESOCKETENGINE_P_H
DECL|macro|QT_SOCKLEN_T
DECL|macro|QT_SOCKOPTLEN_T
DECL|macro|WSAID_WSARECVMSG
DECL|macro|WSAID_WSASENDMSG
DECL|member|a
DECL|member|a4
DECL|member|a6
DECL|member|dwFlags
DECL|member|lpCompletionRoutine
DECL|member|lpMsg
DECL|member|lpNumberOfBytesSent
DECL|member|lpOverlapped
DECL|typedef|LPFN_WSARECVMSG
DECL|typedef|LPFN_WSASENDMSG
DECL|typedef|LPWSASENDMSG
DECL|typedef|WSASENDMSG
DECL|union|qt_sockaddr
DECL|variable|QNativeSocketEnginePrivate
DECL|variable|QNetworkInterface
DECL|variable|QSocketNotifier
