DECL|macro|QNATIVESOCKETENGINE_P_H
DECL|macro|QT_SOCKLEN_T
DECL|macro|QT_SOCKOPTLEN_T
DECL|macro|QT_SS_ALIGNSIZE
DECL|macro|QT_SS_MAXSIZE
DECL|macro|QT_SS_PAD1SIZE
DECL|macro|QT_SS_PAD2SIZE
DECL|member|__ss_align
DECL|member|__ss_pad1
DECL|member|__ss_pad2
DECL|member|a
DECL|member|a4
DECL|member|a6
DECL|member|qt_s6_addr
DECL|member|sin6_addr
DECL|member|sin6_family
DECL|member|sin6_flowinfo
DECL|member|sin6_port
DECL|member|sin6_scope_id
DECL|member|ss_family
DECL|member|storage
DECL|struct|qt_in6_addr
DECL|struct|qt_sockaddr_in6
DECL|struct|qt_sockaddr_storage
DECL|union|qt_sockaddr
DECL|variable|QNativeSocketEnginePrivate
DECL|variable|QNetworkInterface
DECL|variable|QSocketNotifier
