DECL|class|QExceptionNotifier
DECL|class|QReadNotifier
DECL|class|QWriteNotifier
DECL|function|QExceptionNotifier
DECL|function|QNativeSocketEngine
DECL|function|QNativeSocketEnginePrivate
DECL|function|QReadNotifier
DECL|function|QWriteNotifier
DECL|function|accept
DECL|function|bind
DECL|function|bytesAvailable
DECL|function|bytesToWrite
DECL|function|checkProxy
DECL|function|close
DECL|function|connectToHost
DECL|function|connectToHostByName
DECL|function|connectionNotification
DECL|function|event
DECL|function|event
DECL|function|event
DECL|function|hasPendingDatagrams
DECL|function|initialize
DECL|function|initialize
DECL|function|isExceptionNotificationEnabled
DECL|function|isReadNotificationEnabled
DECL|function|isValid
DECL|function|isWriteNotificationEnabled
DECL|function|joinMulticastGroup
DECL|function|leaveMulticastGroup
DECL|function|listen
DECL|function|multicastInterface
DECL|function|option
DECL|function|pendingDatagramSize
DECL|function|read
DECL|function|readDatagram
DECL|function|receiveBufferSize
DECL|function|sendBufferSize
DECL|function|setError
DECL|function|setExceptionNotificationEnabled
DECL|function|setMulticastInterface
DECL|function|setOption
DECL|function|setReadNotificationEnabled
DECL|function|setReceiveBufferSize
DECL|function|setSendBufferSize
DECL|function|setWriteNotificationEnabled
DECL|function|socketDescriptor
DECL|function|waitForRead
DECL|function|waitForReadOrWrite
DECL|function|waitForWrite
DECL|function|write
DECL|function|writeDatagram
DECL|function|~QNativeSocketEngine
DECL|function|~QNativeSocketEnginePrivate
DECL|macro|Q_CHECK_INVALID_SOCKETLAYER
DECL|macro|Q_CHECK_NOT_STATE
DECL|macro|Q_CHECK_STATE
DECL|macro|Q_CHECK_STATES
DECL|macro|Q_CHECK_TYPE
DECL|macro|Q_CHECK_VALID_SOCKETLAYER
DECL|macro|Q_TR
DECL|macro|Q_VOID
DECL|member|engine
DECL|member|engine
DECL|member|engine
