DECL|function|DoCancel
DECL|function|IssueRequest
DECL|function|QAsyncSelect
DECL|function|QSymbianSocketEngine
DECL|function|QSymbianSocketEnginePrivate
DECL|function|RunError
DECL|function|RunL
DECL|function|accept
DECL|function|bind
DECL|function|bytesAvailable
DECL|function|bytesToWrite
DECL|function|checkProxy
DECL|function|close
DECL|function|connectToHost
DECL|function|connectToHostByName
DECL|function|connectionNotification
DECL|function|createNewSocket
DECL|function|deleteLater
DECL|function|event
DECL|function|fetchConnectionParameters
DECL|function|getPortAndAddress
DECL|function|hasPendingDatagrams
DECL|function|initialize
DECL|function|initialize
DECL|function|isExceptionNotificationEnabled
DECL|function|isReadNotificationEnabled
DECL|function|isValid
DECL|function|isWriteNotificationEnabled
DECL|function|joinMulticastGroup
DECL|function|leaveMulticastGroup
DECL|function|listen
DECL|function|multicastGroupMembershipHelper
DECL|function|multicastInterface
DECL|function|nativeSelect
DECL|function|nativeSelect
DECL|function|option
DECL|function|pendingDatagramSize
DECL|function|qt_prettyDebug
DECL|function|read
DECL|function|readDatagram
DECL|function|receiveBufferSize
DECL|function|run
DECL|function|sendBufferSize
DECL|function|setError
DECL|function|setError
DECL|function|setExceptionNotificationEnabled
DECL|function|setMulticastInterface
DECL|function|setOption
DECL|function|setPortAndAddress
DECL|function|setReadNotificationEnabled
DECL|function|setReceiveBufferSize
DECL|function|setSendBufferSize
DECL|function|setWriteNotificationEnabled
DECL|function|socketDescriptor
DECL|function|startNotifications
DECL|function|translateSocketOption
DECL|function|waitForRead
DECL|function|waitForReadOrWrite
DECL|function|waitForWrite
DECL|function|write
DECL|function|writeDatagram
DECL|function|~QAsyncSelect
DECL|function|~QSymbianSocketEngine
DECL|function|~QSymbianSocketEnginePrivate
DECL|macro|Q_CHECK_INVALID_SOCKETLAYER
DECL|macro|Q_CHECK_NOT_STATE
DECL|macro|Q_CHECK_STATE
DECL|macro|Q_CHECK_STATES
DECL|macro|Q_CHECK_TYPE
DECL|macro|Q_CHECK_VALID_SOCKETLAYER
DECL|macro|Q_VOID
