DECL|class|QTcpServerPrivate
DECL|function|QTcpServer
DECL|function|QTcpServerPrivate
DECL|function|addPendingConnection
DECL|function|close
DECL|function|connectionNotification
DECL|function|errorString
DECL|function|exceptionNotification
DECL|function|hasPendingConnections
DECL|function|incomingConnection
DECL|function|isListening
DECL|function|listen
DECL|function|maxPendingConnections
DECL|function|nextPendingConnection
DECL|function|proxy
DECL|function|proxyAuthenticationRequired
DECL|function|readNotification
DECL|function|resolveProxy
DECL|function|serverAddress
DECL|function|serverError
DECL|function|serverPort
DECL|function|setMaxPendingConnections
DECL|function|setProxy
DECL|function|setSocketDescriptor
DECL|function|socketDescriptor
DECL|function|waitForNewConnection
DECL|function|writeNotification
DECL|function|~QTcpServer
DECL|function|~QTcpServerPrivate
DECL|macro|Q_CHECK_SOCKETENGINE
DECL|member|address
DECL|member|maxConnections
DECL|member|pendingConnections
DECL|member|port
DECL|member|proxy
DECL|member|serverSocketError
DECL|member|serverSocketErrorString
DECL|member|socketEngine
DECL|member|state
