DECL|class|tst_QWMatrix
DECL|function|assignments
DECL|function|cleanup
DECL|function|init
DECL|function|mapPolygon
DECL|function|mapRect
DECL|function|mapRect_data
DECL|function|mapToPolygon
DECL|function|mapToPolygon_data
DECL|function|mapping_data
DECL|function|operator_star_qrect
DECL|function|operator_star_qrect_data
DECL|function|operator_star_qwmatrix
DECL|function|scale
DECL|function|translate
DECL|function|tst_QWMatrix
DECL|function|~tst_QWMatrix
DECL|macro|M_PI
