DECL|class|MyServer
DECL|function|MyServer
DECL|function|address
DECL|function|clearValueSpy
DECL|function|emitSignal
DECL|function|emitSignal2
DECL|function|handleConnection
DECL|function|isConnected
DECL|function|main
DECL|function|newMyObject
DECL|function|registerMyObject
DECL|function|slotSpyServer
DECL|function|valueSpyServer
DECL|function|~MyServer
DECL|member|m_conn
DECL|member|obj
DECL|variable|objectPath
DECL|variable|serviceName
DECL|variable|slotSpy
DECL|variable|valueSpy
