DECL|class|MimeData
DECL|function|MimeData
DECL|function|QBBClipboard
DECL|function|addFormatToCheck
DECL|function|formats
DECL|function|hasFormat
DECL|function|mimeData
DECL|function|readClipboardBuff
DECL|function|releaseOwnership
DECL|function|retrieveData
DECL|function|setMimeData
DECL|function|setUserMimeData
DECL|function|userMimeData
DECL|function|~MimeData
DECL|function|~QBBClipboard
DECL|member|m_clipboard
DECL|member|m_formatsToCheck
DECL|member|m_userMimeData
DECL|variable|typeList
