DECL|function|QBBInputContext
DECL|function|filterEvent
DECL|function|handleKeyboardEvent
DECL|function|hasPhysicalKeyboard
DECL|function|hideInputPanel
DECL|function|inputItemChanged
DECL|function|isInputPanelVisible
DECL|function|isValid
DECL|function|keyboardLocaleChanged
DECL|function|keyboardVisibilityChanged
DECL|function|locale
DECL|function|reset
DECL|function|showInputPanel
DECL|function|~QBBInputContext
