DECL|function|QBBScreen
DECL|function|addWindow
DECL|function|availableGeometry
DECL|function|createDisplays
DECL|function|defaultDepth
DECL|function|destroyDisplays
DECL|function|isOrthogonal
DECL|function|lowerWindow
DECL|function|onWindowPost
DECL|function|raiseWindow
DECL|function|removeWindow
DECL|function|setRotation
DECL|function|updateHierarchy
DECL|function|~QBBScreen
DECL|member|ms_childWindows
DECL|member|ms_screens
