DECL|function|QWaylandReadbackCGLIntegration
DECL|function|createEglWindow
DECL|function|createGLIntegration
DECL|function|createPlatformGLContext
DECL|function|initialize
DECL|function|waylandDisplay
DECL|function|~QWaylandReadbackCGLIntegration
