DECL|function|backgroundColor
DECL|function|cast_helper
DECL|function|cleanup
DECL|function|foregroundColor
DECL|function|installFactory
DECL|function|installRootObjectHandler
DECL|function|installUpdateHandler
DECL|function|invokeMethod
DECL|function|isActive
DECL|function|platformAccessibility
DECL|function|qAccessibleCleanup
DECL|function|queryAccessibleInterface
DECL|function|relationTo
DECL|function|relations
DECL|function|removeFactory
DECL|function|setRootObject
DECL|function|updateAccessibility
DECL|function|virtual_hook
DECL|function|window
DECL|member|rootObjectHandler
DECL|member|updateHandler
DECL|variable|accessibility_active
DECL|variable|cleanupAdded
