DECL|class|Current_Thread
DECL|class|DummyEventDispatcher
DECL|class|Exit_Object
DECL|class|Exit_Thread
DECL|class|FinishedTestObject
DECL|class|Job
DECL|class|NativeThreadWrapper
DECL|class|Quit_Object
DECL|class|Quit_Thread
DECL|class|SignalRecorder
DECL|class|Simple_Thread
DECL|class|Sleep_Thread
DECL|class|SlowSlotObject
DECL|class|StopableJob
DECL|class|Syncronizer
DECL|class|Terminate_Thread
DECL|class|ThreadObj
DECL|class|Waiting_Thread
DECL|class|tst_QThread
DECL|enumerator|Microsecond
DECL|enumerator|Millisecond
DECL|enumerator|Second
DECL|enumerator|WaitTime
DECL|enumerator|five_minutes
DECL|enumerator|one_minute
DECL|enum|SleepType
DECL|function|DummyEventDispatcher
DECL|function|FinishedTestObject
DECL|function|Job
DECL|function|NativeThreadWrapper
DECL|function|SignalRecorder
DECL|function|StopableJob
DECL|function|Syncronizer
DECL|function|adoptMultipleThreads
DECL|function|adoptMultipleThreadsOverlap
DECL|function|adoptedThreadAffinity
DECL|function|adoptedThreadAffinityFunction
DECL|function|adoptedThreadExec
DECL|function|adoptedThreadExecFinished
DECL|function|adoptedThreadExecFunction
DECL|function|adoptedThreadExit
DECL|function|adoptedThreadFinished
DECL|function|adoptedThreadSetPriority
DECL|function|connectThreadFinishedSignalToObjectDeleteLaterSlot
DECL|function|currentThread
DECL|function|currentThreadId
DECL|function|customEventDispatcher
DECL|function|destroyFinishRace
DECL|function|exec
DECL|function|exit
DECL|function|exitAndExec
DECL|function|exitAndStart
DECL|function|exitThread
DECL|function|finished
DECL|function|flush
DECL|function|hasPendingEvents
DECL|function|idealThreadCount
DECL|function|interrupt
DECL|function|isFinished
DECL|function|isRunning
DECL|function|isRunningInFinished
DECL|function|join
DECL|function|msleep
DECL|function|nativeThreadAdoption
DECL|function|noop
DECL|function|processEvents
DECL|function|quit
DECL|function|quitLock
DECL|function|registerEventNotifier
DECL|function|registerSocketNotifier
DECL|function|registerTimer
DECL|function|registeredTimers
DECL|function|remainingTime
DECL|function|requestTermination
DECL|function|run
DECL|function|run
DECL|function|run
DECL|function|run
DECL|function|run
DECL|function|run
DECL|function|run
DECL|function|run
DECL|function|runUnix
DECL|function|runWin
DECL|function|setPriority
DECL|function|setProp
DECL|function|setStackSize
DECL|function|setWaitForStop
DECL|function|sleep
DECL|function|slot
DECL|function|slot
DECL|function|slot
DECL|function|slotFinished
DECL|function|slowSlot
DECL|function|start
DECL|function|start
DECL|function|startAndQuitCustomEventLoop
DECL|function|startAndWait
DECL|function|startFinishRace
DECL|function|started
DECL|function|stop
DECL|function|stressTest
DECL|function|terminate
DECL|function|terminated
DECL|function|testNativeThreadAdoption
DECL|function|unregisterEventNotifier
DECL|function|unregisterSocketNotifier
DECL|function|unregisterTimer
DECL|function|unregisterTimers
DECL|function|usleep
DECL|function|visit
DECL|function|wait2
DECL|function|wait3_slowDestructor
DECL|function|wakeUp
DECL|function|wasActivated
DECL|macro|WIN_FIX_STDCALL
DECL|macro|WIN_FIX_STDCALL
DECL|member|activationCount
DECL|member|code
DECL|member|code
DECL|member|cond
DECL|member|cond
DECL|member|cond1
DECL|member|cond2
DECL|member|data
DECL|member|elapsed
DECL|member|exitThreadCalled
DECL|member|functionPointer
DECL|member|id
DECL|member|interval
DECL|member|m_prop
DECL|member|mutex
DECL|member|mutex
DECL|member|mutex
DECL|member|mutex
DECL|member|nativeThreadHandle
DECL|member|object
DECL|member|object
DECL|member|ok
DECL|member|qthread
DECL|member|quitLocker
DECL|member|result
DECL|member|result
DECL|member|sem
DECL|member|sleepType
DECL|member|startCondition
DECL|member|stopCondition
DECL|member|thread
DECL|member|thread
DECL|member|thread
DECL|member|visited
DECL|member|waitForStop
DECL|typedef|FunctionPointer
DECL|typedef|ThreadHandle
DECL|typedef|ThreadHandle
DECL|variable|mainThread
DECL|variable|threadAdoptedOk
