DECL|enumerator|NLA_802_1X_LOCATION
DECL|enumerator|NLA_CONNECTIVITY
DECL|enumerator|NLA_ICS
DECL|enumerator|NLA_INTERFACE
DECL|enumerator|NLA_INTERNET_NO
DECL|enumerator|NLA_INTERNET_UNKNOWN
DECL|enumerator|NLA_INTERNET_YES
DECL|enumerator|NLA_NETWORK_AD_HOC
DECL|enumerator|NLA_NETWORK_MANAGED
DECL|enumerator|NLA_NETWORK_UNKNOWN
DECL|enumerator|NLA_NETWORK_UNMANAGED
DECL|enumerator|NLA_RAW_DATA
DECL|enumerator|NdisMedium802_3
DECL|enumerator|NdisPhysicalMediumBluetooth
DECL|enumerator|NdisPhysicalMediumWiMax
DECL|enumerator|NdisPhysicalMediumWirelessLan
DECL|enum|NDIS_MEDIUM
DECL|enum|NDIS_PHYSICAL_MEDIUM
DECL|enum|NLA_BLOB_DATA_TYPE
DECL|enum|NLA_CONNECTIVITY_TYPE
DECL|enum|NLA_INTERNET
DECL|macro|IOCTL_NDIS_QUERY_GLOBAL_STATS
DECL|macro|NS_NLA
DECL|macro|OID_GEN_MEDIA_SUPPORTED
DECL|macro|OID_GEN_PHYSICAL_MEDIUM
DECL|macro|QPLATFORMDEFS_WIN_H
DECL|macro|interface
DECL|member|ICS
DECL|member|adapterName
DECL|member|connectivity
DECL|member|data
DECL|member|dwSize
DECL|member|dwSpeed
DECL|member|dwType
DECL|member|header
DECL|member|information
DECL|member|interfaceData
DECL|member|internet
DECL|member|locationData
DECL|member|machineName
DECL|member|nextOffset
DECL|member|rawData
DECL|member|remote
DECL|member|sharedAdapterName
DECL|member|speed
DECL|member|state
DECL|member|type
DECL|member|type
DECL|member|type
DECL|struct|NLA_BLOB
