DECL|class|CustomLayoutStyle
DECL|class|DummyMacStyle
DECL|class|DummyQtopiaStyle
DECL|class|tst_QFormLayout
DECL|function|CustomLayoutStyle
DECL|function|addRow
DECL|function|buddies
DECL|function|cleanup
DECL|function|cleanupTestCase
DECL|function|contentsRect
DECL|function|getItemPosition
DECL|function|init
DECL|function|initTestCase
DECL|function|insertRow_QLayout
DECL|function|insertRow_QString_QLayout
DECL|function|insertRow_QString_QWidget
DECL|function|insertRow_QWidget
DECL|function|insertRow_QWidget_QLayout
DECL|function|insertRow_QWidget_QWidget
DECL|function|itemAt
DECL|function|layoutAlone
DECL|function|pixelMetric
DECL|function|rowCount
DECL|function|setFieldGrowthPolicy
DECL|function|setFormAlignment
DECL|function|setFormStyle
DECL|function|setFrameless
DECL|function|setLabelAlignment
DECL|function|setLayout
DECL|function|setRowWrapPolicy
DECL|function|setWidget
DECL|function|spacing
DECL|function|styleHint
DECL|function|styleHint
DECL|function|takeAt
DECL|function|taskQTBUG_27420_takeAtShouldUnparentLayout
DECL|function|tst_QFormLayout
DECL|function|wrapping
DECL|function|~tst_QFormLayout
DECL|member|hspacing
DECL|member|vspacing
