DECL|class|tst_QMetaProperty
DECL|enumerator|EnumType1
DECL|enum|EnumType
DECL|function|getValue
DECL|function|get_value
DECL|function|hasStdCppSet
DECL|function|isConstant
DECL|function|isFinal
DECL|function|setValue
DECL|function|set_value
DECL|function|value10
DECL|function|value8
DECL|function|value9
