DECL|function|QEvdevKeyboardHandler
DECL|function|create
DECL|function|loadKeymap
DECL|function|processKeyEvent
DECL|function|processKeycode
DECL|function|readKeycode
DECL|function|switchLed
DECL|function|unloadKeymap
DECL|function|~QEvdevKeyboardHandler
