DECL|macro|INTERFACES_H
DECL|variable|QImage
DECL|variable|QPainter
DECL|variable|QPainterPath
DECL|variable|QPoint
DECL|variable|QRect
DECL|variable|QString
DECL|variable|QStringList
DECL|variable|QWidget
