DECL|macro|QPLATFORMDEFS_H
DECL|macro|QT_SNPRINTF
DECL|macro|QT_SOCKLEN_T
DECL|macro|QT_SOCKLEN_T
DECL|macro|QT_SOCKLEN_T
DECL|macro|QT_USE_XOPEN_LFS_EXTENSIONS
DECL|macro|QT_VSNPRINTF
DECL|macro|_GNU_SOURCE
