DECL|function|NmakeMakefileGenerator
DECL|function|defaultInstall
DECL|function|findDependencies
DECL|function|getPdbTarget
DECL|function|init
DECL|function|var
DECL|function|writeBuildRulesPart
DECL|function|writeImplicitRulesPart
DECL|function|writeLinkCommand
DECL|function|writeMakefile
DECL|function|writeNmakeParts
DECL|function|writeSubMakeCall
