DECL|function|VcprojGenerator
DECL|function|collectDependencies
DECL|function|createProjectWriter
DECL|function|fixFilename
DECL|function|getProjectUUID
DECL|function|hasBuiltinCompiler
DECL|function|increaseUUID
DECL|function|init
DECL|function|initCompilerTool
DECL|function|initConfiguration
DECL|function|initCustomBuildTool
DECL|function|initDeploymentTool
DECL|function|initExtraCompilerOutputs
DECL|function|initFormFiles
DECL|function|initGeneratedFiles
DECL|function|initHeaderFiles
DECL|function|initIDLTool
DECL|function|initLexYaccFiles
DECL|function|initLibrarianTool
DECL|function|initLinkerTool
DECL|function|initManifestTool
DECL|function|initOld
DECL|function|initPostBuildEventTools
DECL|function|initPreBuildEventTools
DECL|function|initPreLinkEventTools
DECL|function|initProject
DECL|function|initResourceFiles
DECL|function|initResourceTool
DECL|function|initRootFiles
DECL|function|initSourceFiles
DECL|function|initTranslationFiles
DECL|function|mergeBuildProject
DECL|function|openOutput
DECL|function|outputVariables
DECL|function|replaceExtraCompilerVariables
DECL|function|which_dotnet_version
DECL|function|writeMakefile
DECL|function|writeProjectMakefile
DECL|function|writeSubDirs
DECL|function|~VcprojGenerator
DECL|member|dependencies
DECL|member|orig_target
DECL|member|regKey
DECL|member|target
DECL|member|targetType
DECL|member|uuid
DECL|member|vcprojFile
DECL|member|version
DECL|member|versionStr
DECL|struct|DotNetCombo
DECL|struct|VcsolutionDepend
DECL|variable|_GUIDExtraCompilerFiles
DECL|variable|_GUIDFormFiles
DECL|variable|_GUIDGeneratedFiles
DECL|variable|_GUIDHeaderFiles
DECL|variable|_GUIDLexYaccFiles
DECL|variable|_GUIDResourceFiles
DECL|variable|_GUIDSourceFiles
DECL|variable|_GUIDTranslationFiles
DECL|variable|_slnExtSections
DECL|variable|_slnGlobalBeg
DECL|variable|_slnGlobalEnd
DECL|variable|_slnHeader100
DECL|variable|_slnHeader110
DECL|variable|_slnHeader70
DECL|variable|_slnHeader71
DECL|variable|_slnHeader80
DECL|variable|_slnHeader90
DECL|variable|_slnMSVCvcprojGUID
DECL|variable|_slnProjConfBeg
DECL|variable|_slnProjConfEnd
DECL|variable|_slnProjDbgConfTag1
DECL|variable|_slnProjDbgConfTag2
DECL|variable|_slnProjDepBeg
DECL|variable|_slnProjDepEnd
DECL|variable|_slnProjRelConfTag1
DECL|variable|_slnProjRelConfTag2
DECL|variable|_slnProjectBeg
DECL|variable|_slnProjectEnd
DECL|variable|_slnProjectMid
DECL|variable|_slnSolutionConf
DECL|variable|dotNetCombo
