DECL|function|CodeEditor
DECL|function|highlightCurrentLine
DECL|function|lineNumberAreaPaintEvent
DECL|function|lineNumberAreaWidth
DECL|function|resizeEvent
DECL|function|updateLineNumberArea
DECL|function|updateLineNumberAreaWidth
