DECL|function|QFontBig5Codec
DECL|function|QFontBig5hkscsCodec
DECL|function|_aliases
DECL|function|_mibEnum
DECL|function|_mibEnum
DECL|function|_mibEnum
DECL|function|_mibEnum
DECL|function|_name
DECL|function|_name
DECL|function|_name
DECL|function|_name
DECL|function|convertFromUnicode
DECL|function|convertFromUnicode
DECL|function|convertFromUnicode
DECL|function|convertFromUnicode
DECL|function|convertToUnicode
DECL|function|convertToUnicode
DECL|function|convertToUnicode
DECL|function|convertToUnicode
DECL|function|qt_Big5ToUnicode
DECL|function|qt_Big5hkscsToUnicode
DECL|function|qt_UnicodeToBig5
DECL|function|qt_UnicodeToBig5hkscs
DECL|macro|InRange
DECL|macro|IsFirstByte
DECL|macro|IsLatin
DECL|macro|IsSecondByte
DECL|macro|IsSecondByteRange1
DECL|macro|IsSecondByteRange2
DECL|macro|QValidChar
DECL|member|index
DECL|member|table
DECL|member|tableSize
DECL|member|used
DECL|member|x
DECL|member|y
DECL|struct|B5Index
DECL|struct|B5Map
DECL|typedef|Summary16
DECL|variable|b5_8140_to_uc_map
DECL|variable|b5_8E40_to_uc_map
DECL|variable|b5_C6A1_to_uc_map
DECL|variable|b5_FA40_to_uc_map
DECL|variable|b5_map_table
DECL|variable|big5hkscs_to_charset
DECL|variable|big5hkscs_to_ucs
DECL|variable|big5hkscs_uni2index_page00
DECL|variable|big5hkscs_uni2index_page1e
DECL|variable|big5hkscs_uni2index_page20
DECL|variable|big5hkscs_uni2index_page200
DECL|variable|big5hkscs_uni2index_page294
DECL|variable|big5hkscs_uni2index_page297
DECL|variable|big5hkscs_uni2index_page2e
DECL|variable|big5hkscs_uni2index_page2f8
DECL|variable|big5hkscs_uni2index_pagee0
DECL|variable|big5hkscs_uni2index_pagefe
DECL|variable|uc_to_b5_map
