DECL|class|PaintCounter
DECL|class|QTabWidgetChild
DECL|class|RemoveTabObject
DECL|class|tst_QTabWidget
DECL|function|PaintCounter
DECL|function|QTabWidgetChild
DECL|function|RemoveTabObject
DECL|function|addPage
DECL|function|addRemoveTab
DECL|function|cleanup
DECL|function|clear
DECL|function|cornerWidget
DECL|function|currentChanged
DECL|function|currentIndex
DECL|function|currentWidget
DECL|function|getSetCheck
DECL|function|heightForWidth
DECL|function|heightForWidth_data
DECL|function|indexOf
DECL|function|init
DECL|function|keyboardNavigation
DECL|function|minimumSizeHint
DECL|function|paintEvent
DECL|function|paintEventCount
DECL|function|removePage
DECL|function|removeTab
DECL|function|tabBarClicked
DECL|function|tabEnabled
DECL|function|tabIcon
DECL|function|tabInserted
DECL|function|tabPosition
DECL|function|tabRemoved
DECL|function|tabShape
DECL|function|tabText
DECL|function|tabTooltip
DECL|function|testChild
DECL|function|tst_QTabWidget
DECL|macro|LABEL
DECL|macro|Q_CHECK_PAINTEVENTS
DECL|macro|Q_CHECK_PAINTEVENTS
DECL|macro|TIP
DECL|member|count
DECL|member|count
DECL|member|tabCount
DECL|member|tw
DECL|member|tw
