DECL|enumerator|QT_TABLET_NPACKETQSIZE
DECL|enumerator|TOTAL_XINPUT_EVENTS
DECL|function|scaleCoord
DECL|function|sign
DECL|macro|GC_PAN
DECL|macro|GC_PAN_WITH_SINGLE_FINGER_HORIZONTALLY
DECL|macro|GC_PAN_WITH_SINGLE_FINGER_VERTICALLY
DECL|macro|GC_ROTATE
DECL|macro|GC_ZOOM
DECL|macro|GID_BEGIN
DECL|macro|GID_END
DECL|macro|GID_PAN
DECL|macro|GID_ROLLOVER
DECL|macro|GID_ROLLOVER
DECL|macro|GID_ROLLOVER
DECL|macro|GID_ROTATE
DECL|macro|GID_ROTATE
DECL|macro|GID_ROTATE
DECL|macro|GID_ROTATE_ANGLE_FROM_ARGUMENT
DECL|macro|GID_TWOFINGERTAP
DECL|macro|GID_TWOFINGERTAP
DECL|macro|GID_TWOFINGERTAP
DECL|macro|GID_ZOOM
DECL|macro|GID_ZOOM
DECL|macro|GID_ZOOM
DECL|macro|QAPPLICATION_P_H
DECL|macro|WM_GESTURE
DECL|member|capabilityMask
DECL|member|cbExtraArgs
DECL|member|cbSize
DECL|member|currentDevice
DECL|member|currentPointerType
DECL|member|device
DECL|member|deviceType
DECL|member|dwBlock
DECL|member|dwFlags
DECL|member|dwID
DECL|member|dwID
DECL|member|dwInstanceID
DECL|member|dwSequenceID
DECL|member|dwWant
DECL|member|eventCount
DECL|member|eventList
DECL|member|hwndTarget
DECL|member|llId
DECL|member|maxPressure
DECL|member|maxTanPressure
DECL|member|maxX
DECL|member|maxY
DECL|member|maxZ
DECL|member|minPressure
DECL|member|minTanPressure
DECL|member|minX
DECL|member|minY
DECL|member|minZ
DECL|member|ptsLocation
DECL|member|tabletDeviceType
DECL|member|tabletPointerType
DECL|member|tabletUniqueID
DECL|member|ullArguments
DECL|member|widgetToGetPress
DECL|member|xinput_button_press
DECL|member|xinput_button_release
DECL|member|xinput_key_press
DECL|member|xinput_key_release
DECL|member|xinput_motion
DECL|member|xinput_proximity_in
DECL|member|xinput_proximity_out
DECL|struct|QTabletDeviceData
DECL|struct|QWSServerCleaner
DECL|struct|tagGESTURECONFIG
DECL|struct|tagGESTUREINFO
DECL|typedef|FontHash
DECL|typedef|GESTURECONFIG
DECL|typedef|GESTUREINFO
DECL|typedef|PaletteHash
DECL|typedef|PtrBeginPanningFeedback
DECL|typedef|PtrCloseGestureInfoHandle
DECL|typedef|PtrCloseTouchInputHandle
DECL|typedef|PtrEndPanningFeedback
DECL|typedef|PtrGetGestureConfig
DECL|typedef|PtrGetGestureExtraArgs
DECL|typedef|PtrGetGestureInfo
DECL|typedef|PtrGetTouchInputInfo
DECL|typedef|PtrRegisterTouchWindow
DECL|typedef|PtrSetGestureConfig
DECL|typedef|PtrUpdatePanningFeedback
DECL|typedef|Ptrqt_dispatchAccelEvent
DECL|typedef|Ptrqt_tryAccelEvent
DECL|typedef|Ptrqt_tryComposeUnicode
DECL|typedef|QByteArray
DECL|typedef|QByteArray
DECL|typedef|QMacTabletHash
DECL|typedef|QTabletDeviceDataList
DECL|variable|QClipboard
DECL|variable|QDirectPainter
DECL|variable|QGestureManager
DECL|variable|QGraphicsScene
DECL|variable|QGraphicsSystem
DECL|variable|QInputContext
DECL|variable|QObject
DECL|variable|QSocketNotifier
DECL|variable|QWSManager
DECL|variable|QWidget
