DECL|class|QDummyInputContext
DECL|function|QDummyInputContext
DECL|function|alert
DECL|function|appName
DECL|function|beep
DECL|function|cleanupMultitouch_sys
DECL|function|closePopup
DECL|function|createEventDispatcher
DECL|function|cursorFlashTime
DECL|function|doubleClickInterval
DECL|function|enterModal_sys
DECL|function|identifierName
DECL|function|initializeMultitouch_sys
DECL|function|initializeWidgetPaletteHash
DECL|function|isComposing
DECL|function|isEffectEnabled
DECL|function|keyboardInputInterval
DECL|function|language
DECL|function|leaveModal_sys
DECL|function|modalState
DECL|function|openPopup
DECL|function|platformNativeInterface
DECL|function|qt_cleanup
DECL|function|qt_init
DECL|function|qt_try_modal
DECL|function|reset
DECL|function|restoreOverrideCursor
DECL|function|setCursorFlashTime
DECL|function|setDoubleClickInterval
DECL|function|setEffectEnabled
DECL|function|setKeyboardInputInterval
DECL|function|setMainWidget
DECL|function|setOverrideCursor
DECL|function|setWheelScrollLines
DECL|function|topLevelAt
DECL|function|wheelScrollLines
DECL|function|~QDummyInputContext
DECL|variable|appFont
DECL|variable|appName
DECL|variable|openPopupCount
