DECL|class|QETWidget
DECL|function|Data
DECL|function|QWSDisplay
DECL|function|ReadInteger
DECL|function|addProperty
DECL|function|alert
DECL|function|appName
DECL|function|applyQWSSpecificCommandLineArguments
DECL|function|beep
DECL|function|cleanupMultitouch_sys
DECL|function|closePopup
DECL|function|connectToPipe
DECL|function|convertSelection
DECL|function|create
DECL|function|createEventDispatcher
DECL|function|cursorFlashTime
DECL|function|defineCursor
DECL|function|depth
DECL|function|dequeue
DECL|function|destroyCursor
DECL|function|destroyRegion
DECL|function|directServerConnection
DECL|function|doubleClickInterval
DECL|function|enterModal_sys
DECL|function|eventPending
DECL|function|fillQueue
DECL|function|findWidget
DECL|function|flush
DECL|function|flushCommands
DECL|function|flushCommands
DECL|function|frameBuffer
DECL|function|getClientLock
DECL|function|getEvent
DECL|function|getProperty
DECL|function|getTransformationFunction
DECL|function|grab
DECL|function|grab
DECL|function|grabKeyboard
DECL|function|grabMouse
DECL|function|grabbed
DECL|function|hasPendingRegionEvents
DECL|function|height
DECL|function|init
DECL|function|initLock
DECL|function|init_display
DECL|function|initializeMultitouch_sys
DECL|function|initializeWidgetPaletteHash
DECL|function|isEffectEnabled
DECL|function|keyboardInputInterval
DECL|function|leaveModal_sys
DECL|function|lockClient
DECL|function|modalState
DECL|function|moveRegion
DECL|function|nameRegion
DECL|function|openPopup
DECL|function|parseGeometry
DECL|function|peek
DECL|function|pixmapDepth
DECL|function|playSoundFile
DECL|function|qt_app_reinit
DECL|function|qt_cleanup
DECL|function|qt_client_enqueue
DECL|function|qt_get_server_queue
DECL|function|qt_init
DECL|function|qt_init_display
DECL|function|qt_server_enqueue
DECL|function|qt_set_qws_resources
DECL|function|qt_try_modal
DECL|function|queryKeyboardModifiers
DECL|function|queueNotEmpty
DECL|function|qwsDecoration
DECL|function|qwsEventFilter
DECL|function|qwsProcessEvent
DECL|function|qwsSetCustomColors
DECL|function|qwsSetDecoration
DECL|function|qwsSetDecoration
DECL|function|qws_apply_settings
DECL|function|qws_dataDir
DECL|function|qws_qtePipeFilename
DECL|function|raiseOnClick
DECL|function|readMore
DECL|function|read_bool_env_var
DECL|function|read_int_env_var
DECL|function|registerChannel
DECL|function|reinit
DECL|function|removeProperty
DECL|function|repaintDecoration
DECL|function|repaintRegion
DECL|function|requestFocus
DECL|function|requestRegion
DECL|function|resetIM
DECL|function|restoreOverrideCursor
DECL|function|selectCursor
DECL|function|sendCommand
DECL|function|sendFontCommand
DECL|function|sendIMMouseEvent
DECL|function|sendIMResponse
DECL|function|sendIMUpdate
DECL|function|sendMessage
DECL|function|sendSynchronousCommand
DECL|function|setAltitude
DECL|function|setArgs
DECL|function|setCursorFlashTime
DECL|function|setCursorPosition
DECL|function|setDoubleClickInterval
DECL|function|setEffectEnabled
DECL|function|setIdentity
DECL|function|setKeyboardInputInterval
DECL|function|setMainWidget
DECL|function|setMaxWindowRect
DECL|function|setMaxWindowRect
DECL|function|setMouseFilter
DECL|function|setOpacity
DECL|function|setOverrideCursor
DECL|function|setProperty
DECL|function|setProperty
DECL|function|setRawMouseEventFilter
DECL|function|setScreenTransformation
DECL|function|setScreenTransformation
DECL|function|setSelectionOwner
DECL|function|setTransformation
DECL|function|setWheelScrollLines
DECL|function|setWindowCaption
DECL|function|sharedRam
DECL|function|sharedRamSize
DECL|function|supportsDepth
DECL|function|takeId
DECL|function|takeId
DECL|function|topLevelAt
DECL|function|translateEmbedEvent
DECL|function|translateKeyEvent
DECL|function|translateMouseEvent
DECL|function|translateRegionEvent
DECL|function|translateWheelEvent
DECL|function|ungrab
DECL|function|unlockClient
DECL|function|updateRegion
DECL|function|waitClient
DECL|function|waitForConnection
DECL|function|waitForCreation
DECL|function|waitForPropertyReply
DECL|function|waitForQCopResponse
DECL|function|waitForQCopResponse
DECL|function|waitForRegionAck
DECL|function|waitForRegionEvents
DECL|function|wheelScrollLines
DECL|function|width
DECL|function|windowAt
DECL|function|windowList
DECL|function|~Data
DECL|function|~QWSDisplay
DECL|function|~QWSServerCleaner
DECL|macro|AllValues
DECL|macro|HeightValue
DECL|macro|NoValue
DECL|macro|WidthValue
DECL|macro|XNegative
DECL|macro|XValue
DECL|macro|YNegative
DECL|macro|YValue
DECL|member|clientLock
DECL|member|lock
DECL|typedef|TransformFunc
DECL|variable|AnyButton
DECL|variable|appBGCol
DECL|variable|appBTNCol
DECL|variable|appFGCol
DECL|variable|appFont
DECL|variable|appName
DECL|variable|app_do_modal
DECL|variable|incoming
DECL|variable|mouseButtonPressTime
DECL|variable|mouseButtonPressed
DECL|variable|mouseInWidget
DECL|variable|mouseXPos
DECL|variable|mouseYPos
DECL|variable|mouse_double_click_distance
DECL|variable|mouse_state
DECL|variable|mouse_x_root
DECL|variable|mouse_y_root
DECL|variable|mwGeometry
DECL|variable|mwTitle
DECL|variable|openPopupCount
DECL|variable|outgoing
DECL|variable|popupButtonFocus
DECL|variable|popupCloseDownMode
DECL|variable|popupGrabOk
DECL|variable|popupOfPopupButtonFocus
DECL|variable|qt_button_down
DECL|variable|qt_fbdpy
DECL|variable|qt_last_cursor
DECL|variable|qt_last_mouse_receiver
DECL|variable|qt_last_x
DECL|variable|qt_last_y
DECL|variable|qt_mouseGrb
DECL|variable|qt_pressGrab
DECL|variable|qt_servershmid
DECL|variable|qwsSharedRamSize
DECL|variable|qws_accel
DECL|variable|qws_client_id
DECL|variable|qws_connection_timeout
DECL|variable|qws_decoration
DECL|variable|qws_display_id
DECL|variable|qws_overrideCursor
DECL|variable|qws_savefonts
DECL|variable|qws_screen_is_interlaced
DECL|variable|qws_shared_memory
DECL|variable|qws_single_process
DECL|variable|qws_sw_cursor
DECL|variable|sm_blockUserInput
