DECL|class|QMacMimeData
DECL|class|QMacPasteboardMimeSource
DECL|function|QMacPasteboard
DECL|function|QMacPasteboard
DECL|function|QMacPasteboard
DECL|function|QMacPasteboardMimeSource
DECL|function|clear
DECL|function|clear
DECL|function|clear_helper
DECL|function|connectNotify
DECL|function|event
DECL|function|formats
DECL|function|formats
DECL|function|hasFlavor
DECL|function|hasFormat
DECL|function|hasOSType
DECL|function|mimeData
DECL|function|mimeData
DECL|function|ownerDestroyed
DECL|function|ownsMode
DECL|function|pasteBoard
DECL|function|promiseKeeper
DECL|function|qt_mac_cleanupPasteboard
DECL|function|qt_mac_pasteboard
DECL|function|qt_mac_updateScrap
DECL|function|retrieveData
DECL|function|retrieveData
DECL|function|setMimeData
DECL|function|setMimeData
DECL|function|supportsMode
DECL|function|sync
DECL|function|variantData
DECL|function|~QMacPasteboard
DECL|function|~QMacPasteboardMimeSource
DECL|member|paste
DECL|variable|qt_mac_pasteboards
