DECL|function|QClipboard
DECL|function|clear
DECL|function|emitChanged
DECL|function|image
DECL|function|mimeData
DECL|function|ownsClipboard
DECL|function|ownsFindBuffer
DECL|function|ownsMode
DECL|function|ownsSelection
DECL|function|pixmap
DECL|function|setImage
DECL|function|setMimeData
DECL|function|setPixmap
DECL|function|setText
DECL|function|supportsFindBuffer
DECL|function|supportsMode
DECL|function|supportsSelection
DECL|function|text
DECL|function|text
DECL|function|~QClipboard
