DECL|class|QClipboardData
DECL|class|QClipboardWatcher
DECL|function|QClipboardData
DECL|function|QClipboardWatcher
DECL|function|QtCeFlushClipboard
DECL|function|QtCeGetClipboard
DECL|function|QtCeSetClipboard
DECL|function|cleanupClipboardData
DECL|function|clear
DECL|function|clipboardData
DECL|function|connectNotify
DECL|function|event
DECL|function|formats_sys
DECL|function|hasFormat_sys
DECL|function|mimeData
DECL|function|ownerDestroyed
DECL|function|ownsMode
DECL|function|releaseIData
DECL|function|retrieveData_sys
DECL|function|setMimeData
DECL|function|supportsMode
DECL|function|~QClipboard
DECL|function|~QClipboardData
DECL|macro|OleFlushClipboard
DECL|macro|OleGetClipboard
DECL|macro|OleSetClipboard
DECL|member|clipBoardViewer
DECL|member|iData
DECL|member|nextClipboardViewer
DECL|member|watcher
DECL|typedef|PtrIsHungAppWindow
DECL|variable|ptrClipboardData
DECL|variable|ptrIsHungAppWindow
