DECL|class|QDesktopWidgetPrivate
DECL|class|QSingleDesktopWidget
DECL|function|QDesktopWidget
DECL|function|QDesktopWidgetPrivate
DECL|function|QSingleDesktopWidget
DECL|function|availableGeometry
DECL|function|init
DECL|function|isVirtualDesktop
DECL|function|numScreens
DECL|function|primaryScreen
DECL|function|qt_desktopwidget_update_workarea
DECL|function|resizeEvent
DECL|function|screen
DECL|function|screenGeometry
DECL|function|screenNumber
DECL|function|screenNumber
DECL|function|~QDesktopWidget
DECL|function|~QDesktopWidgetPrivate
DECL|function|~QSingleDesktopWidget
DECL|member|defaultScreen
DECL|member|rects
DECL|member|screenCount
DECL|member|screens
DECL|member|use_xinerama
DECL|member|workareas
DECL|variable|qt_desktopwidget_workarea_dirty
