DECL|class|QDesktopWidgetPrivate
DECL|class|QSingleDesktopWidget
DECL|function|QDesktopWidget
DECL|function|QDesktopWidgetPrivate
DECL|function|QSingleDesktopWidget
DECL|function|availableGeometry
DECL|function|cleanup
DECL|function|init
DECL|function|init_sys
DECL|function|isVirtualDesktop
DECL|function|newSingleDesktopWidget
DECL|function|numScreens
DECL|function|primaryScreen
DECL|function|resizeEvent
DECL|function|screen
DECL|function|screenGeometry
DECL|function|screenNumber
DECL|function|screenNumber
DECL|function|~QDesktopWidget
DECL|function|~QDesktopWidgetPrivate
DECL|function|~QSingleDesktopWidget
DECL|member|displayControl
DECL|member|displayControl
DECL|member|primaryScreen
DECL|member|primaryScreen
DECL|member|rects
DECL|member|rects
DECL|member|refcount
DECL|member|refcount
DECL|member|screenCount
DECL|member|screenCount
DECL|member|screens
DECL|member|screens
DECL|member|workrects
DECL|member|workrects
