DECL|class|QOleDropSource
DECL|function|AddRef
DECL|function|AddRef
DECL|function|AddRef
DECL|function|DAdvise
DECL|function|DUnadvise
DECL|function|DragEnter
DECL|function|DragLeave
DECL|function|DragOver
DECL|function|Drop
DECL|function|EnumDAdvise
DECL|function|EnumFormatEtc
DECL|function|GetCanonicalFormatEtc
DECL|function|GetData
DECL|function|GetDataHere
DECL|function|GiveFeedback
DECL|function|QOleDataObject
DECL|function|QOleDropSource
DECL|function|QOleDropTarget
DECL|function|QueryContinueDrag
DECL|function|QueryGetData
DECL|function|QueryInterface
DECL|function|QueryInterface
DECL|function|QueryInterface
DECL|function|Release
DECL|function|Release
DECL|function|Release
DECL|function|SetData
DECL|function|cancel
DECL|function|createCursors
DECL|function|drag
DECL|function|drop
DECL|function|eventFilter
DECL|function|formats_sys
DECL|function|hasFormat_sys
DECL|function|keystate_to_mousebutton
DECL|function|mimeData
DECL|function|move
DECL|function|releaseQt
DECL|function|releaseQt
DECL|function|reportedPerformedEffect
DECL|function|retrieveData_sys
DECL|function|sendDragEnterEvent
DECL|function|timerEvent
DECL|function|toQtKeyboardModifiers
DECL|function|toQtMouseButtons
DECL|function|translateToQDragDropAction
DECL|function|translateToQDragDropActions
DECL|function|translateToWinDragEffects
DECL|function|updatePixmap
DECL|function|~QOleDataObject
DECL|function|~QOleDropSource
DECL|macro|KEY_STATE_BUTTON_MASK
DECL|macro|MK_XBUTTON1
DECL|macro|MK_XBUTTON2
DECL|member|currentAction
DECL|member|currentButtons
DECL|member|cursors
DECL|member|m_refs
