DECL|function|KeyboardModifiersToString
DECL|function|QDragManager
DECL|function|QInternalMimeData
DECL|function|canReadData
DECL|function|cancel
DECL|function|currentTarget
DECL|function|defaultAction
DECL|function|drag
DECL|function|dragActionsToString
DECL|function|dragCursor
DECL|function|drop
DECL|function|eventFilter
DECL|function|formats
DECL|function|formatsHelper
DECL|function|hasFormat
DECL|function|hasFormatHelper
DECL|function|imageReadMimeFormats
DECL|function|imageWriteMimeFormats
DECL|function|move
DECL|function|renderDataHelper
DECL|function|retrieveData
DECL|function|self
DECL|function|setCurrentTarget
DECL|function|stopDrag
DECL|function|unmanageEvents
DECL|function|updateCursor
DECL|function|updatePixmap
DECL|function|~QDragManager
DECL|function|~QInternalMimeData
DECL|member|instance
DECL|variable|defaultPm
DECL|variable|default_pm
DECL|variable|default_pm_hotx
DECL|variable|default_pm_hoty
DECL|variable|oldstate
