DECL|class|QEventDispatcherQWSPrivate
DECL|function|QEventDispatcherQWS
DECL|function|QEventDispatcherQWSPrivate
DECL|function|closingDown
DECL|function|flush
DECL|function|hasPendingEvents
DECL|function|processEvents
DECL|function|select
DECL|function|startingUp
DECL|function|~QEventDispatcherQWS
DECL|member|queuedUserInputEvents
