DECL|class|QEventDispatcherQPAPrivate
DECL|class|Rendezvous
DECL|class|SelectWorker
DECL|function|QEventDispatcherQPA
DECL|function|QEventDispatcherQPAPrivate
DECL|function|SelectWorker
DECL|function|checkpoint
DECL|function|flush
DECL|function|hasIntegration
DECL|function|hasPendingEvents
DECL|function|isEventLoopIntegrationRunning
DECL|function|processEvents
DECL|function|registerSocketNotifier
DECL|function|retVal
DECL|function|run
DECL|function|runEventLoopIntegration
DECL|function|select
DECL|function|setSelectValues
DECL|function|unregisterSocketNotifier
DECL|function|~QEventDispatcherQPA
DECL|function|~QEventDispatcherQPAPrivate
DECL|member|barrierBeforeBlocking
DECL|member|barrierReturnValue
DECL|member|eventLoopIntegration
DECL|member|m_edPrivate
DECL|member|m_exceptfds
DECL|member|m_hasIntegration
DECL|member|m_integrationInitialised
DECL|member|m_isEventLoopIntegrationRunning
DECL|member|m_nfds
DECL|member|m_readfds
DECL|member|m_retVal
DECL|member|m_writefds
DECL|member|selectReturnMutex
DECL|member|selectWorker
DECL|member|selectWorkerHasResult
DECL|member|selectWorkerNeedsSync
DECL|member|semaphore
DECL|member|state
