DECL|macro|QGUIAPPLICATION_QPA_H
DECL|macro|qApp
DECL|macro|qApp
DECL|macro|qGuiApp
DECL|macro|qGuiApp
DECL|variable|QInputPanel
DECL|variable|QPalette
DECL|variable|QPlatformNativeInterface
DECL|variable|QScreen
DECL|variable|QStyleHints
