DECL|function|QGuiApplication
DECL|function|QGuiApplication
DECL|function|QGuiApplicationPrivate
DECL|function|activeWindow
DECL|function|changeOverrideCursor
DECL|function|clipboard
DECL|function|compressEvent
DECL|function|createEventDispatcher
DECL|function|createPlatformIntegration
DECL|function|currentKeyPlatform
DECL|function|doubleClickInterval
DECL|function|event
DECL|function|exec
DECL|function|font
DECL|function|getPixmapCursor
DECL|function|init
DECL|function|init_platform
DECL|function|init_plugins
DECL|function|keyboardInputDirection
DECL|function|keyboardInputInterval
DECL|function|keyboardInputLocale
DECL|function|keyboardModifiers
DECL|function|layoutDirection
DECL|function|mouseButtons
DECL|function|notify
DECL|function|notifyActiveWindowChange
DECL|function|notifyLayoutDirectionChange
DECL|function|overrideCursor
DECL|function|palette
DECL|function|platformNativeInterface
DECL|function|primaryScreen
DECL|function|processActivatedEvent
DECL|function|processCloseEvent
DECL|function|processDrag
DECL|function|processDrop
DECL|function|processEnterEvent
DECL|function|processExposeEvent
DECL|function|processGeometryChangeEvent
DECL|function|processKeyEvent
DECL|function|processLeaveEvent
DECL|function|processMapEvent
DECL|function|processMouseEvent
DECL|function|processTouchEvent
DECL|function|processUnmapEvent
DECL|function|processWheelEvent
DECL|function|processWindowSystemEvent
DECL|function|qt_detectRTLLanguage
DECL|function|reportAvailableGeometryChange
DECL|function|reportGeometryChange
DECL|function|reportScreenCount
DECL|function|restoreOverrideCursor
DECL|function|screens
DECL|function|setDoubleClickInterval
DECL|function|setFont
DECL|function|setKeyboardInputInterval
DECL|function|setLayoutDirection
DECL|function|setOverrideCursor
DECL|function|topLevelAt
DECL|function|topLevelWindows
DECL|function|~QGuiApplication
DECL|function|~QGuiApplicationPrivate
DECL|member|active_window
DECL|member|app_do_modal
DECL|member|app_font
DECL|member|app_pal
DECL|member|buttons
DECL|member|keyboard_input_time
DECL|member|modifier_buttons
DECL|member|mousePressButton
DECL|member|mousePressTime
DECL|member|mousePressX
DECL|member|mousePressY
DECL|member|mouse_buttons
DECL|member|mouse_double_click_distance
DECL|member|mouse_double_click_time
DECL|member|platform_integration
DECL|member|qt_clipboard
DECL|member|screen_list
DECL|member|self
DECL|member|window_list
DECL|variable|copy_xpm
DECL|variable|force_reverse
DECL|variable|ignore_xpm
DECL|variable|layout_direction
DECL|variable|link_xpm
DECL|variable|move_xpm
DECL|variable|qt_is_gui_used
DECL|variable|qt_last_x
DECL|variable|qt_last_y
