DECL|function|QGuiApplication
DECL|function|QGuiApplication
DECL|function|QGuiApplicationPrivate
DECL|function|clipboard
DECL|function|compressEvent
DECL|function|createEventDispatcher
DECL|function|doubleClickInterval
DECL|function|event
DECL|function|exec
DECL|function|font
DECL|function|init
DECL|function|init_platform
DECL|function|init_plugins
DECL|function|keyboardInputInterval
DECL|function|keyboardModifiers
DECL|function|mouseButtons
DECL|function|notify
DECL|function|platformNativeInterface
DECL|function|processActivatedEvent
DECL|function|processCloseEvent
DECL|function|processEnterEvent
DECL|function|processGeometryChangeEvent
DECL|function|processKeyEvent
DECL|function|processLeaveEvent
DECL|function|processMouseEvent
DECL|function|processTouchEvent
DECL|function|processWheelEvent
DECL|function|processWindowSystemEvent
DECL|function|reportAvailableGeometryChange
DECL|function|reportGeometryChange
DECL|function|reportScreenCount
DECL|function|setDoubleClickInterval
DECL|function|setFont
DECL|function|setKeyboardInputInterval
DECL|function|~QGuiApplication
DECL|function|~QGuiApplicationPrivate
DECL|member|app_do_modal
DECL|member|app_font
DECL|member|buttons
DECL|member|keyboard_input_time
DECL|member|modifier_buttons
DECL|member|mousePressButton
DECL|member|mousePressTime
DECL|member|mousePressX
DECL|member|mousePressY
DECL|member|mouse_buttons
DECL|member|mouse_double_click_distance
DECL|member|mouse_double_click_time
DECL|member|platform_integration
DECL|member|qt_clipboard
DECL|member|qt_last_mouse_receiver
DECL|member|qt_modal_stack
DECL|member|self
DECL|variable|qt_button_down
DECL|variable|qt_last_x
DECL|variable|qt_last_y
