DECL|macro|QGUIAPPLICATION_H
DECL|macro|qApp
DECL|macro|qApp
DECL|macro|qGuiApp
DECL|macro|qGuiApp
DECL|variable|QGuiApplicationPrivate
DECL|variable|QPalette
DECL|variable|QPlatformIntegration
DECL|variable|QPlatformNativeInterface
DECL|variable|QScreen
DECL|variable|QSessionManager
DECL|variable|QStyleHints
