DECL|class|QGuiGLContextPrivate
DECL|class|QGuiGLThreadContext
DECL|function|QGuiGLContext
DECL|function|QGuiGLContextPrivate
DECL|function|currentContext
DECL|function|deleteQGLContext
DECL|function|doneCurrent
DECL|function|format
DECL|function|getProcAddress
DECL|function|handle
DECL|function|isValid
DECL|function|makeCurrent
DECL|function|qGLContextHandle
DECL|function|setCurrentContext
DECL|function|setQGLContextHandle
DECL|function|shareContext
DECL|function|swapBuffers
DECL|function|~QGuiGLContext
DECL|function|~QGuiGLContextPrivate
DECL|function|~QGuiGLThreadContext
DECL|member|context
DECL|member|platformGLContext
DECL|member|qGLContextDeleteFunction
DECL|member|qGLContextHandle
DECL|member|shareContext
DECL|variable|qwindow_context_storage
