DECL|function|factor
DECL|function|factor
DECL|function|factor
DECL|function|initHighDpiScaling
DECL|function|initialScaleFactor
DECL|function|logicalDpi
DECL|function|mapPositionFromNative
DECL|function|mapPositionToNative
DECL|function|origin
DECL|function|origin
DECL|function|screenSubfactor
DECL|function|setGlobalFactor
DECL|function|setScreenFactor
DECL|function|updateHighDpiScaling
DECL|member|m_active
DECL|member|m_factor
DECL|member|m_globalScalingActive
DECL|member|m_logicalDpi
DECL|member|m_pixelDensityScalingActive
DECL|member|m_screenFactorSet
DECL|member|m_usePixelDensity
DECL|variable|autoScreenEnvVar
DECL|variable|legacyDevicePixelEnvVar
DECL|variable|scaleFactorEnvVar
DECL|variable|scaleFactorProperty
DECL|variable|screenFactorsEnvVar
