DECL|function|QInputMethod
DECL|function|commit
DECL|function|cursorRectangle
DECL|function|hide
DECL|function|inputDirection
DECL|function|inputItemTransform
DECL|function|invokeAction
DECL|function|isAnimating
DECL|function|isVisible
DECL|function|keyboardRectangle
DECL|function|locale
DECL|function|objectAcceptsInputMethod
DECL|function|reset
DECL|function|setInputItemTransform
DECL|function|setVisible
DECL|function|show
DECL|function|update
DECL|function|~QInputMethod
