DECL|class|QETWidget
DECL|function|GetKeyboardState
DECL|function|KeyRecord
DECL|function|KeyRecord
DECL|function|KeyRecorder
DECL|function|QKeyMapperPrivate
DECL|function|ToAscii
DECL|function|ToUnicode
DECL|function|asciiToKeycode
DECL|function|clearKeys
DECL|function|clearMappings
DECL|function|clearRecordedKeys
DECL|function|deleteLayouts
DECL|function|findKey
DECL|function|isADeadKey
DECL|function|isModifierKey
DECL|function|possibleKeys
DECL|function|qt_show_system_menu
DECL|function|qt_translateKeyCode
DECL|function|sendKeyEvent
DECL|function|sendSpontaneousEvent
DECL|function|setKbdState
DECL|function|storeKey
DECL|function|toKeyOrUnicode
DECL|function|translateKeyEvent
DECL|function|updateKeyMap
DECL|function|updatePossibleKeyCodes
DECL|function|winceKeyBend
DECL|function|~QKeyMapperPrivate
DECL|macro|LANG_DIVEHI
DECL|macro|LANG_PASHTO
DECL|macro|LANG_SYRIAC
DECL|macro|VK_OEM_3
DECL|macro|VK_OEM_PLUS
DECL|macro|disabled
DECL|macro|disabled
DECL|macro|enabled
DECL|macro|enabled
DECL|member|ascii
DECL|member|code
DECL|member|deadkeys
DECL|member|deleted_record
DECL|member|dirty
DECL|member|nrecs
DECL|member|qtKey
DECL|member|records
DECL|member|state
DECL|member|text
DECL|struct|KeyRecord
DECL|struct|KeyRecorder
DECL|struct|KeyboardLayoutItem
DECL|variable|KeyTbl
DECL|variable|ModsTbl
DECL|variable|QT_MAX_KEY_RECORDINGS
DECL|variable|key_recorder
