DECL|class|QBuiltInMimes
DECL|class|QLastResortMimes
DECL|class|QWindowsMimeHtml
DECL|class|QWindowsMimeImage
DECL|class|QWindowsMimeList
DECL|class|QWindowsMimeText
DECL|class|QWindowsMimeURI
DECL|function|QBuiltInMimes
DECL|function|QLastResortMimes
DECL|function|QWindowsMime
DECL|function|QWindowsMimeHtml
DECL|function|QWindowsMimeImage
DECL|function|QWindowsMimeList
DECL|function|QWindowsMimeURI
DECL|function|addWindowsMime
DECL|function|allFormatsForMime
DECL|function|allMimesForFormats
DECL|function|calc_shift
DECL|function|canConvertFromMime
DECL|function|canConvertFromMime
DECL|function|canConvertFromMime
DECL|function|canConvertFromMime
DECL|function|canConvertFromMime
DECL|function|canConvertFromMime
DECL|function|canConvertToMime
DECL|function|canConvertToMime
DECL|function|canConvertToMime
DECL|function|canConvertToMime
DECL|function|canConvertToMime
DECL|function|canConvertToMime
DECL|function|canGetData
DECL|function|convertFromMime
DECL|function|convertFromMime
DECL|function|convertFromMime
DECL|function|convertFromMime
DECL|function|convertFromMime
DECL|function|convertFromMime
DECL|function|convertToMime
DECL|function|convertToMime
DECL|function|convertToMime
DECL|function|convertToMime
DECL|function|convertToMime
DECL|function|convertToMime
DECL|function|converterFromMime
DECL|function|converterToMime
DECL|function|customMimeType
DECL|function|formatsForMime
DECL|function|formatsForMime
DECL|function|formatsForMime
DECL|function|formatsForMime
DECL|function|formatsForMime
DECL|function|formatsForMime
DECL|function|getCf
DECL|function|getData
DECL|function|hasOriginalDIBV5
DECL|function|init
DECL|function|isCustomMimeType
DECL|function|mimeForFormat
DECL|function|mimeForFormat
DECL|function|mimeForFormat
DECL|function|mimeForFormat
DECL|function|mimeForFormat
DECL|function|mimeForFormat
DECL|function|qt_read_dibv5
DECL|function|qt_write_dibv5
DECL|function|registerMimeType
DECL|function|removeWindowsMime
DECL|function|setCf
DECL|function|setData
DECL|function|windowsMimes
DECL|function|~QWindowsMime
DECL|function|~QWindowsMimeList
DECL|macro|BMP_LCS_GM_IMAGES
DECL|macro|BMP_LCS_sRGB
DECL|macro|CF_DIBV5
DECL|member|CF_HTML
DECL|member|CF_INETURL
DECL|member|CF_INETURL_W
DECL|member|CF_PNG
DECL|member|bV5AlphaMask
DECL|member|bV5BitCount
DECL|member|bV5BlueMask
DECL|member|bV5CSType
DECL|member|bV5ClrImportant
DECL|member|bV5ClrUsed
DECL|member|bV5Compression
DECL|member|bV5Endpoints
DECL|member|bV5GammaBlue
DECL|member|bV5GammaGreen
DECL|member|bV5GammaRed
DECL|member|bV5GreenMask
DECL|member|bV5Height
DECL|member|bV5Intent
DECL|member|bV5Planes
DECL|member|bV5ProfileData
DECL|member|bV5ProfileSize
DECL|member|bV5RedMask
DECL|member|bV5Reserved
DECL|member|bV5Size
DECL|member|bV5SizeImage
DECL|member|bV5Width
DECL|member|bV5XPelsPerMeter
DECL|member|bV5YPelsPerMeter
DECL|member|ciexyzBlue
DECL|member|ciexyzGreen
DECL|member|ciexyzRed
DECL|member|ciexyzX
DECL|member|ciexyzY
DECL|member|ciexyzZ
DECL|member|excludeList
DECL|member|excludeList
DECL|member|formats
DECL|member|ianaTypes
DECL|member|ianaTypes
DECL|member|inFormats
DECL|member|initialized
DECL|member|mimes
DECL|member|outFormats
DECL|struct|BMP_BITMAPV5HEADER
DECL|struct|_CIEXYZ
DECL|struct|_CIEXYZTRIPLE
DECL|variable|BMP_BITFIELDS
DECL|variable|x_qt_windows_mime
