DECL|macro|QOPENGLCONTEXT_H
DECL|variable|QOpenGLContextGroupPrivate
DECL|variable|QOpenGLContextPrivate
DECL|variable|QOpenGLFunctions
DECL|variable|QPlatformOpenGLContext
DECL|variable|QScreen
DECL|variable|QSurface
