DECL|class|QGuiGLThreadContext
DECL|class|QOpenGLVersionProfilePrivate
DECL|function|QGuiGLThreadContext
DECL|function|QOpenGLContext
DECL|function|QOpenGLContextGroup
DECL|function|QOpenGLMultiGroupSharedResource
DECL|function|QOpenGLSharedResource
DECL|function|QOpenGLVersionProfile
DECL|function|QOpenGLVersionProfile
DECL|function|QOpenGLVersionProfile
DECL|function|QOpenGLVersionProfilePrivate
DECL|function|addContext
DECL|function|areSharing
DECL|function|cleanup
DECL|function|cleanup
DECL|function|create
DECL|function|currentContext
DECL|function|currentContextGroup
DECL|function|defaultFramebufferObject
DECL|function|deletePendingResources
DECL|function|deleteQGLContext
DECL|function|destroy
DECL|function|doneCurrent
DECL|function|extensions
DECL|function|format
DECL|function|free
DECL|function|freeResource
DECL|function|functions
DECL|function|functionsBackend
DECL|function|getProcAddress
DECL|function|handle
DECL|function|hasExtension
DECL|function|hasProfiles
DECL|function|insert
DECL|function|insertFunctionsBackend
DECL|function|isLegacyVersion
DECL|function|isOpenGLES
DECL|function|isValid
DECL|function|isValid
DECL|function|makeCurrent
DECL|function|maxTextureSize
DECL|function|nativeHandle
DECL|function|openGLModuleHandle
DECL|function|openGLModuleType
DECL|function|operator =
DECL|function|profile
DECL|function|qGLContextHandle
DECL|function|qt_gl_global_share_context
DECL|function|qt_gl_set_global_share_context
DECL|function|removeContext
DECL|function|removeFunctionsBackend
DECL|function|resources
DECL|function|screen
DECL|function|setCurrentContext
DECL|function|setFormat
DECL|function|setNativeHandle
DECL|function|setProfile
DECL|function|setQGLContextHandle
DECL|function|setScreen
DECL|function|setShareContext
DECL|function|setTextureFunctions
DECL|function|setVersion
DECL|function|shareContext
DECL|function|shareGroup
DECL|function|shareHandle
DECL|function|shares
DECL|function|surface
DECL|function|swapBuffers
DECL|function|textureFunctions
DECL|function|value
DECL|function|version
DECL|function|versionFunctions
DECL|function|~QGuiGLThreadContext
DECL|function|~QOpenGLContext
DECL|function|~QOpenGLContextGroup
DECL|function|~QOpenGLMultiGroupSharedResource
DECL|function|~QOpenGLSharedResource
DECL|function|~QOpenGLVersionProfile
DECL|member|context
DECL|member|majorVersion
DECL|member|makeCurrentTracker
DECL|member|makeCurrentTrackerMutex
DECL|member|minorVersion
DECL|member|profile
DECL|variable|global_share_context
DECL|variable|qwindow_context_storage
