DECL|function|active
DECL|function|disabled
DECL|function|inactive
DECL|function|normal
DECL|function|setBrush
DECL|function|setColor
DECL|function|setColor
DECL|macro|QPALETTE_H
DECL|variable|QPalettePrivate
DECL|variable|QVariant
