DECL|class|QColorDialogOptionsPrivate
DECL|class|QColorDialogStaticData
DECL|class|QFileDialogOptionsPrivate
DECL|class|QFontDialogOptionsPrivate
DECL|class|QMessageDialogOptionsPrivate
DECL|enumerator|CustomColorCount
DECL|enumerator|StandardColorCount
DECL|function|QColorDialogOptions
DECL|function|QColorDialogOptions
DECL|function|QColorDialogOptionsPrivate
DECL|function|QColorDialogStaticData
DECL|function|QFileDialogOptions
DECL|function|QFileDialogOptions
DECL|function|QFileDialogOptionsPrivate
DECL|function|QFontDialogOptions
DECL|function|QFontDialogOptions
DECL|function|QFontDialogOptionsPrivate
DECL|function|QMessageDialogOptions
DECL|function|QMessageDialogOptions
DECL|function|QMessageDialogOptionsPrivate
DECL|function|QPlatformDialogHelper
DECL|function|acceptMode
DECL|function|cleanFilterList
DECL|function|customColor
DECL|function|customColorCount
DECL|function|customColors
DECL|function|defaultStyleHint
DECL|function|defaultSuffix
DECL|function|detailedText
DECL|function|fileMode
DECL|function|filter
DECL|function|history
DECL|function|icon
DECL|function|informativeText
DECL|function|initialDirectory
DECL|function|initiallySelectedFiles
DECL|function|initiallySelectedNameFilter
DECL|function|isLabelExplicitlySet
DECL|function|isSupportedUrl
DECL|function|labelText
DECL|function|mimeTypeFilters
DECL|function|nameFilters
DECL|function|operator =
DECL|function|operator =
DECL|function|operator =
DECL|function|operator =
DECL|function|options
DECL|function|options
DECL|function|options
DECL|function|options
DECL|function|options
DECL|function|options
DECL|function|options
DECL|function|readSettings
DECL|function|setAcceptMode
DECL|function|setCustomColor
DECL|function|setDefaultSuffix
DECL|function|setDetailedText
DECL|function|setFileMode
DECL|function|setFilter
DECL|function|setHistory
DECL|function|setIcon
DECL|function|setInformativeText
DECL|function|setInitialDirectory
DECL|function|setInitiallySelectedFiles
DECL|function|setInitiallySelectedNameFilter
DECL|function|setLabelText
DECL|function|setMimeTypeFilters
DECL|function|setNameFilters
DECL|function|setOption
DECL|function|setOption
DECL|function|setOption
DECL|function|setOptions
DECL|function|setOptions
DECL|function|setOptions
DECL|function|setOptions
DECL|function|setOptions
DECL|function|setOptions
DECL|function|setOptions
DECL|function|setSidebarUrls
DECL|function|setStandardButtons
DECL|function|setStandardColor
DECL|function|setText
DECL|function|setViewMode
DECL|function|setWindowTitle
DECL|function|setWindowTitle
DECL|function|setWindowTitle
DECL|function|setWindowTitle
DECL|function|sidebarUrls
DECL|function|standardButtons
DECL|function|standardColor
DECL|function|standardColors
DECL|function|styleHint
DECL|function|testOption
DECL|function|testOption
DECL|function|testOption
DECL|function|text
DECL|function|viewMode
DECL|function|windowTitle
DECL|function|windowTitle
DECL|function|windowTitle
DECL|function|windowTitle
DECL|function|writeSettings
DECL|function|~QColorDialogOptions
DECL|function|~QColorDialogOptionsPrivate
DECL|function|~QFileDialogOptions
DECL|function|~QFontDialogOptions
DECL|function|~QMessageDialogOptions
DECL|function|~QPlatformDialogHelper
DECL|member|acceptMode
DECL|member|buttons
DECL|member|customRgb
DECL|member|customSet
DECL|member|defaultSuffix
DECL|member|detailedText
DECL|member|fileMode
DECL|member|filterRegExp
DECL|member|filters
DECL|member|history
DECL|member|icon
DECL|member|informativeText
DECL|member|initialDirectory
DECL|member|initiallySelectedFiles
DECL|member|initiallySelectedNameFilter
DECL|member|labels
DECL|member|mimeTypeFilters
DECL|member|nameFilters
DECL|member|options
DECL|member|options
DECL|member|options
DECL|member|sidebarUrls
DECL|member|standardRgb
DECL|member|text
DECL|member|viewMode
DECL|member|windowTitle
DECL|member|windowTitle
DECL|member|windowTitle
DECL|member|windowTitle
