DECL|function|accessibility
DECL|function|clipboard
DECL|function|createPlatformOpenGLContext
DECL|function|createPlatformPixmap
DECL|function|createPlatformSharedGraphicsCache
DECL|function|drag
DECL|function|fontDatabase
DECL|function|hasCapability
DECL|function|inputContext
DECL|function|nativeInterface
DECL|function|platformTheme
DECL|function|screenAdded
DECL|function|styleHint
