DECL|function|QPlatformScreen
DECL|function|currentOrientation
DECL|function|grabWindow
DECL|function|logicalDpi
DECL|function|pageFlipper
DECL|function|physicalSize
DECL|function|platformScreenForWindow
DECL|function|primaryOrientation
DECL|function|screen
DECL|function|topLevelAt
DECL|function|virtualSiblings
DECL|function|~QPlatformScreen
