DECL|function|nativeResourceForBackingStore
DECL|function|nativeResourceForContext
DECL|function|nativeResourceForWindow
DECL|function|setWindowProperty
DECL|function|windowProperties
DECL|function|windowProperty
DECL|function|windowProperty
