DECL|class|QPlatformWindowPrivate
DECL|function|QPlatformWindow
DECL|function|geometry
DECL|function|glContext
DECL|function|lower
DECL|function|raise
DECL|function|requestActivateWindow
DECL|function|setGeometry
DECL|function|setOpacity
DECL|function|setParent
DECL|function|setVisible
DECL|function|setWindowFlags
DECL|function|setWindowTitle
DECL|function|winId
DECL|function|window
DECL|function|~QPlatformWindow
DECL|member|rect
DECL|member|window
