DECL|function|QPlatformInputContext
DECL|function|commit
DECL|function|emitAnimatingChanged
DECL|function|emitInputDirectionChanged
DECL|function|emitInputPanelVisibleChanged
DECL|function|emitKeyboardRectChanged
DECL|function|emitLocaleChanged
DECL|function|filterEvent
DECL|function|hasCapability
DECL|function|hideInputPanel
DECL|function|inputDirection
DECL|function|inputMethodAccepted
DECL|function|invokeAction
DECL|function|isAnimating
DECL|function|isInputPanelVisible
DECL|function|isValid
DECL|function|keyboardRect
DECL|function|locale
DECL|function|reset
DECL|function|setFocusObject
DECL|function|setInputMethodAccepted
DECL|function|showInputPanel
DECL|function|update
DECL|function|~QPlatformInputContext
DECL|member|s_inputMethodAccepted
