DECL|function|QPlatformWindow
DECL|function|constrainWindowSize
DECL|function|devicePixelRatio
DECL|function|effectiveScreen
DECL|function|format
DECL|function|formatWindowTitle
DECL|function|frameMargins
DECL|function|frameStrutEventsEnabled
DECL|function|geometry
DECL|function|handleContentOrientationChange
DECL|function|initialGeometry
DECL|function|invalidateSurface
DECL|function|isActive
DECL|function|isAlertState
DECL|function|isEmbedded
DECL|function|isExposed
DECL|function|lower
DECL|function|mapFromGlobal
DECL|function|mapToGlobal
DECL|function|normalGeometry
DECL|function|parent
DECL|function|propagateSizeHints
DECL|function|raise
DECL|function|requestActivateWindow
DECL|function|requestUpdate
DECL|function|screen
DECL|function|screenForGeometry
DECL|function|setAlertState
DECL|function|setFrameStrutEventsEnabled
DECL|function|setGeometry
DECL|function|setKeyboardGrabEnabled
DECL|function|setMask
DECL|function|setMouseGrabEnabled
DECL|function|setOpacity
DECL|function|setParent
DECL|function|setVisible
DECL|function|setWindowFilePath
DECL|function|setWindowFlags
DECL|function|setWindowIcon
DECL|function|setWindowModified
DECL|function|setWindowState
DECL|function|setWindowTitle
DECL|function|startSystemResize
DECL|function|winId
DECL|function|window
DECL|function|windowBaseSize
DECL|function|windowClosestAcceptableGeometry
DECL|function|windowEvent
DECL|function|windowGeometry
DECL|function|windowMaximumSize
DECL|function|windowMinimumSize
DECL|function|windowSizeIncrement
DECL|function|~QPlatformWindow
