DECL|class|QPlatformWindowPrivate
DECL|function|QPlatformWindow
DECL|function|createGLSurface
DECL|function|frameMargins
DECL|function|geometry
DECL|function|lower
DECL|function|parent
DECL|function|propagateSizeHints
DECL|function|raise
DECL|function|requestActivateWindow
DECL|function|setGeometry
DECL|function|setKeyboardGrabEnabled
DECL|function|setMouseGrabEnabled
DECL|function|setOpacity
DECL|function|setParent
DECL|function|setVisible
DECL|function|setWindowFlags
DECL|function|setWindowState
DECL|function|setWindowTitle
DECL|function|winId
DECL|function|window
DECL|function|~QPlatformWindow
DECL|member|rect
DECL|member|window
