DECL|class|QClipboardData
DECL|function|QClipboardData
DECL|function|emitChanged
DECL|function|mimeData
DECL|function|ownsMode
DECL|function|setMimeData
DECL|function|setSource
DECL|function|source
DECL|function|supportsMode
DECL|function|~QClipboardData
DECL|function|~QPlatformClipboard
DECL|member|src
