DECL|function|createPlatformDialogHelper
DECL|function|createPlatformMenu
DECL|function|createPlatformMenuBar
DECL|function|palette
DECL|function|themeHint
DECL|function|usePlatformNativeDialog
DECL|function|~QPlatformTheme
