DECL|function|QPlatformScreen
DECL|function|cursor
DECL|function|grabWindow
DECL|function|logicalDpi
DECL|function|orientation
DECL|function|pageFlipper
DECL|function|physicalSize
DECL|function|platformScreenForWindow
DECL|function|refreshRate
DECL|function|resizeMaximizedWindows
DECL|function|screen
DECL|function|topLevelAt
DECL|function|virtualSiblings
DECL|function|~QPlatformScreen
