DECL|class|QPlatformWindowFormatPrivate
DECL|function|QPlatformWindowFormat
DECL|function|QPlatformWindowFormat
DECL|function|QPlatformWindowFormat
DECL|function|QPlatformWindowFormatPrivate
DECL|function|QPlatformWindowFormatPrivate
DECL|function|accumBufferSize
DECL|function|alphaBufferSize
DECL|function|blueBufferSize
DECL|function|defaultFormat
DECL|function|depthBufferSize
DECL|function|detach
DECL|function|greenBufferSize
DECL|function|operator !=
DECL|function|operator <<
DECL|function|operator =
DECL|function|operator ==
DECL|function|redBufferSize
DECL|function|samples
DECL|function|setAccum
DECL|function|setAccumBufferSize
DECL|function|setAlpha
DECL|function|setAlphaBufferSize
DECL|function|setBlueBufferSize
DECL|function|setDefaultFormat
DECL|function|setDepth
DECL|function|setDepthBufferSize
DECL|function|setDirectRendering
DECL|function|setDoubleBuffer
DECL|function|setGreenBufferSize
DECL|function|setOption
DECL|function|setRedBufferSize
DECL|function|setRgba
DECL|function|setSampleBuffers
DECL|function|setSamples
DECL|function|setSharedContext
DECL|function|setStencil
DECL|function|setStencilBufferSize
DECL|function|setStereo
DECL|function|setSwapInterval
DECL|function|setWindowApi
DECL|function|setWindowSurface
DECL|function|sharedGLContext
DECL|function|stencilBufferSize
DECL|function|swapInterval
DECL|function|testOption
DECL|function|windowApi
DECL|function|~QPlatformWindowFormat
DECL|member|accumSize
DECL|member|alphaSize
DECL|member|blueSize
DECL|member|depthSize
DECL|member|greenSize
DECL|member|numSamples
DECL|member|opts
DECL|member|redSize
DECL|member|ref
DECL|member|sharedContext
DECL|member|stencilSize
DECL|member|swapInterval
DECL|member|windowApi
