DECL|function|clipboard
DECL|function|createPlatformMenu
DECL|function|createPlatformMenuBar
DECL|function|createPlatformOpenGLContext
DECL|function|createPlatformPixmap
DECL|function|drag
DECL|function|fontDatabase
DECL|function|hasCapability
DECL|function|inputContext
DECL|function|nativeInterface
DECL|function|screenAdded
DECL|function|styleHint
