DECL|class|QScreenPrivate
DECL|function|QScreen
DECL|function|QScreenPrivate
DECL|function|angleBetween
DECL|function|availableGeometry
DECL|function|availableSize
DECL|function|availableVirtualGeometry
DECL|function|availableVirtualSize
DECL|function|currentOrientation
DECL|function|depth
DECL|function|geometry
DECL|function|handle
DECL|function|log2
DECL|function|logicalDotsPerInch
DECL|function|logicalDotsPerInchX
DECL|function|logicalDotsPerInchY
DECL|function|mapBetween
DECL|function|name
DECL|function|physicalDotsPerInch
DECL|function|physicalDotsPerInchX
DECL|function|physicalDotsPerInchY
DECL|function|physicalSize
DECL|function|primaryOrientation
DECL|function|size
DECL|function|transformBetween
DECL|function|virtualGeometry
DECL|function|virtualSiblings
DECL|function|virtualSize
DECL|member|platformScreen
