DECL|class|QScreenPrivate
DECL|function|QScreen
DECL|function|QScreenPrivate
DECL|function|availableGeometry
DECL|function|availableSize
DECL|function|availableVirtualGeometry
DECL|function|availableVirtualSize
DECL|function|depth
DECL|function|geometry
DECL|function|handle
DECL|function|name
DECL|function|size
DECL|function|virtualGeometry
DECL|function|virtualSiblings
DECL|function|virtualSize
DECL|member|platformScreen
