DECL|function|QScreen
DECL|function|angleBetween
DECL|function|availableGeometry
DECL|function|availableSize
DECL|function|availableVirtualGeometry
DECL|function|availableVirtualSize
DECL|function|depth
DECL|function|devicePixelRatio
DECL|function|geometry
DECL|function|grabWindow
DECL|function|handle
DECL|function|isLandscape
DECL|function|isPortrait
DECL|function|log2
DECL|function|logicalDotsPerInch
DECL|function|logicalDotsPerInchX
DECL|function|logicalDotsPerInchY
DECL|function|mapBetween
DECL|function|name
DECL|function|nativeOrientation
DECL|function|orientation
DECL|function|orientationUpdateMask
DECL|function|physicalDotsPerInch
DECL|function|physicalDotsPerInchX
DECL|function|physicalDotsPerInchY
DECL|function|physicalSize
DECL|function|primaryOrientation
DECL|function|refreshRate
DECL|function|setOrientationUpdateMask
DECL|function|size
DECL|function|transformBetween
DECL|function|updatePrimaryOrientation
DECL|function|virtualGeometry
DECL|function|virtualSiblings
DECL|function|virtualSize
