DECL|function|QBasicDrag
DECL|function|QSimpleDrag
DECL|function|cancel
DECL|function|cancel
DECL|function|disableEventFilter
DECL|function|drag
DECL|function|drop
DECL|function|drop
DECL|function|enableEventFilter
DECL|function|endDrag
DECL|function|eventFilter
DECL|function|exitDndEventLoop
DECL|function|move
DECL|function|move
DECL|function|platformDropData
DECL|function|restoreCursor
DECL|function|startDrag
DECL|function|startDrag
DECL|function|topLevelAt
DECL|function|updateCursor
DECL|function|~QBasicDrag
