DECL|function|QStyleHints
DECL|function|cursorFlashTime
DECL|function|hint
DECL|function|keyboardInputInterval
DECL|function|mouseDoubleClickInterval
DECL|function|startDragDistance
DECL|function|startDragTime
