DECL|enumerator|Blit
DECL|enumerator|BlitWriteAlpha
DECL|enumerator|Default
DECL|enumerator|Disable
DECL|enumerator|ZeroFill
DECL|enum|NativePaintMode
DECL|function|QWidgetPaintContext
DECL|function|bypassGraphicsProxyWidget
DECL|function|extraData
DECL|function|maybeBackingStore
DECL|function|maybeTopData
DECL|function|pointInsideRectAndMask
DECL|function|setSharedPainter
DECL|function|sharedPainter
DECL|function|topData
DECL|macro|QWIDGET_P_H
DECL|member|activated
DECL|member|autoFillBackground
DECL|member|backingStore
DECL|member|backingStore
DECL|member|baseh
DECL|member|basew
DECL|member|caption
DECL|member|compress_events
DECL|member|curs
DECL|member|customDpiX
DECL|member|customDpiY
DECL|member|dnd
DECL|member|dropTarget
DECL|member|embedded
DECL|member|explicitMaxSize
DECL|member|explicitMinSize
DECL|member|filePath
DECL|member|flags
DECL|member|focus_proxy
DECL|member|frameStrut
DECL|member|fullScreenOffset
DECL|member|glContext
DECL|member|group
DECL|member|hasMask
DECL|member|hotkeyRegistered
DECL|member|icon
DECL|member|iconPixmap
DECL|member|iconText
DECL|member|imageMask
DECL|member|inExpose
DECL|member|inRenderWithPainter
DECL|member|inRepaint
DECL|member|inTopLevelResize
DECL|member|inch
DECL|member|incw
DECL|member|isMove
DECL|member|isSetGeometry
DECL|member|mask
DECL|member|maskBits
DECL|member|maxh
DECL|member|maxw
DECL|member|minh
DECL|member|minw
DECL|member|nativeChildrenForced
DECL|member|nativePaintMode
DECL|member|nativeWindowTransparencyEnabled
DECL|member|newCounterValueHi
DECL|member|newCounterValueLo
DECL|member|normalGeometry
DECL|member|offset
DECL|member|oleDropWidgets
DECL|member|opacity
DECL|member|painter
DECL|member|parentWinId
DECL|member|pdev
DECL|member|platformWindow
DECL|member|platformWindowFormat
DECL|member|posFromMove
DECL|member|proxyWidget
DECL|member|qwsManager
DECL|member|receiveNativePaintEvents
DECL|member|resizer
DECL|member|rgn
DECL|member|role
DECL|member|savedFlags
DECL|member|savedWindowAttributesFromMaximized
DECL|member|screenIndex
DECL|member|sharedPainter
DECL|member|sharedPainter
DECL|member|sizeAdjusted
DECL|member|spont_unmapped
DECL|member|staticContentsSize
DECL|member|style
DECL|member|styleSheet
DECL|member|syncRequestTimestamp
DECL|member|syncUpdateCounter
DECL|member|topextra
DECL|member|userTimeWindow
DECL|member|validWMState
DECL|member|waitingForMapNotify
DECL|member|wasMaximized
DECL|member|wattr
DECL|member|wclass
DECL|member|winIconBig
DECL|member|winIconSmall
DECL|member|windowIcon
DECL|member|windowSurface
DECL|member|xDndProxy
DECL|struct|QTLWExtra
DECL|struct|QWExtra
DECL|struct|QWidgetPaintContext
DECL|variable|CCoeControl
DECL|variable|QCoreGraphicsPaintEnginePrivate
DECL|variable|QGraphicsProxyWidget
DECL|variable|QPaintEngine
DECL|variable|QPixmap
DECL|variable|QPlatformWindow
DECL|variable|QStyle
DECL|variable|QUnifiedToolbarSurface
DECL|variable|QWSManager
DECL|variable|QWidgetBackingStore
DECL|variable|QWidgetItemV2
DECL|variable|RDrawableWindow
