DECL|class|QWindowContextPrivate
DECL|class|QWindowThreadContext
DECL|function|QWindowContext
DECL|function|QWindowContextPrivate
DECL|function|currentContext
DECL|function|deleteQGLContext
DECL|function|doneCurrent
DECL|function|getProcAddress
DECL|function|handle
DECL|function|makeCurrent
DECL|function|qGLContextHandle
DECL|function|setCurrentContext
DECL|function|setQGLContextHandle
DECL|function|swapBuffers
DECL|function|~QWindowContext
DECL|function|~QWindowContextPrivate
DECL|function|~QWindowThreadContext
DECL|member|context
DECL|member|platformGLContext
DECL|member|qGLContextDeleteFunction
DECL|member|qGLContextHandle
DECL|member|staticSharedContext
DECL|member|staticSharedContext
DECL|variable|qwindow_context_storage
