DECL|function|QWindow
DECL|function|QWindow
DECL|function|QWindow
DECL|function|accessibleRoot
DECL|function|applyCursor
DECL|function|baseSize
DECL|function|close
DECL|function|contentOrientation
DECL|function|create
DECL|function|cursor
DECL|function|destroy
DECL|function|event
DECL|function|exposeEvent
DECL|function|filePath
DECL|function|flags
DECL|function|focusInEvent
DECL|function|focusObject
DECL|function|focusOutEvent
DECL|function|format
DECL|function|frameGeometry
DECL|function|frameMargins
DECL|function|framePos
DECL|function|geometry
DECL|function|handle
DECL|function|hide
DECL|function|hideEvent
DECL|function|icon
DECL|function|isActive
DECL|function|isAncestorOf
DECL|function|isExposed
DECL|function|isModal
DECL|function|isTopLevel
DECL|function|isVisible
DECL|function|keyPressEvent
DECL|function|keyReleaseEvent
DECL|function|lower
DECL|function|mapFromGlobal
DECL|function|mapToGlobal
DECL|function|maximumSize
DECL|function|maybeQuitOnLastWindowClosed
DECL|function|minimumSize
DECL|function|modality
DECL|function|mouseDoubleClickEvent
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|moveEvent
DECL|function|nativeEvent
DECL|function|orientation
DECL|function|parent
DECL|function|qt_window_private
DECL|function|raise
DECL|function|reportContentOrientationChange
DECL|function|requestActivate
DECL|function|requestOrientation
DECL|function|requestedFormat
DECL|function|resize
DECL|function|resizeEvent
DECL|function|screen
DECL|function|screenDestroyed
DECL|function|setBaseSize
DECL|function|setCursor
DECL|function|setFilePath
DECL|function|setFlags
DECL|function|setFormat
DECL|function|setFramePos
DECL|function|setGeometry
DECL|function|setIcon
DECL|function|setKeyboardGrabEnabled
DECL|function|setMaximumHeight
DECL|function|setMaximumSize
DECL|function|setMaximumWidth
DECL|function|setMinimumHeight
DECL|function|setMinimumSize
DECL|function|setMinimumWidth
DECL|function|setModality
DECL|function|setMouseGrabEnabled
DECL|function|setOpacity
DECL|function|setParent
DECL|function|setScreen
DECL|function|setSizeIncrement
DECL|function|setSurfaceType
DECL|function|setTitle
DECL|function|setTransientParent
DECL|function|setVisible
DECL|function|setWindowState
DECL|function|show
DECL|function|showEvent
DECL|function|showFullScreen
DECL|function|showMaximized
DECL|function|showMinimized
DECL|function|showNormal
DECL|function|sizeIncrement
DECL|function|surfaceHandle
DECL|function|surfaceType
DECL|function|tabletEvent
DECL|function|title
DECL|function|touchEvent
DECL|function|transientParent
DECL|function|type
DECL|function|unsetCursor
DECL|function|wheelEvent
DECL|function|winId
DECL|function|windowState
DECL|function|~QWindow
