DECL|macro|QWINDOWDEFS_H
DECL|macro|main
DECL|typedef|QWidgetList
DECL|typedef|QWidgetMapper
DECL|typedef|QWidgetSet
DECL|typedef|QWindowList
DECL|typedef|WId
DECL|typedef|WId
DECL|variable|K
DECL|variable|QApplication
DECL|variable|QBitmap
DECL|variable|QBrush
DECL|variable|QByteArray
DECL|variable|QClipboard
DECL|variable|QColor
DECL|variable|QCursor
DECL|variable|QDialog
DECL|variable|QFont
DECL|variable|QFontInfo
DECL|variable|QFontMetrics
DECL|variable|QHash
DECL|variable|QImage
DECL|variable|QList
DECL|variable|QMatrix
DECL|variable|QMovie
DECL|variable|QPainter
DECL|variable|QPalette
DECL|variable|QPen
DECL|variable|QPicture
DECL|variable|QPixmap
DECL|variable|QPoint
DECL|variable|QPolygon
DECL|variable|QRect
DECL|variable|QRegion
DECL|variable|QSet
DECL|variable|QSize
DECL|variable|QString
DECL|variable|QTime
DECL|variable|QTimer
DECL|variable|QWidget
DECL|variable|QWindow
