DECL|function|QWindow
DECL|function|actualWindowFormat
DECL|function|baseSize
DECL|function|close
DECL|function|create
DECL|function|destroy
DECL|function|event
DECL|function|format
DECL|function|geometry
DECL|function|glContext
DECL|function|handle
DECL|function|hideEvent
DECL|function|inputMethodEvent
DECL|function|isTopLevel
DECL|function|keyPressEvent
DECL|function|keyReleaseEvent
DECL|function|lower
DECL|function|maximumSize
DECL|function|minimumSize
DECL|function|mouseDoubleClickEvent
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|parent
DECL|function|qt_window_private
DECL|function|raise
DECL|function|requestActivateWindow
DECL|function|requestedWindowFormat
DECL|function|resizeEvent
DECL|function|setBaseSize
DECL|function|setGeometry
DECL|function|setMaximumSize
DECL|function|setMinimumSize
DECL|function|setOpacity
DECL|function|setParent
DECL|function|setRequestFormat
DECL|function|setSizeIncrement
DECL|function|setSurfaceType
DECL|function|setVisible
DECL|function|setWindowFlags
DECL|function|setWindowFormat
DECL|function|setWindowIcon
DECL|function|setWindowState
DECL|function|setWindowTitle
DECL|function|showEvent
DECL|function|showFullScreen
DECL|function|showMaximized
DECL|function|showMinimized
DECL|function|showNormal
DECL|function|sizeIncrement
DECL|function|surface
DECL|function|surfaceType
DECL|function|visible
DECL|function|wheelEvent
DECL|function|winId
DECL|function|windowFlags
DECL|function|windowState
DECL|function|windowTitle
DECL|function|~QWindow
