DECL|class|AppendCommand
DECL|class|InsertCommand
DECL|class|RemoveCommand
DECL|class|tst_QUndoGroup
DECL|class|tst_QUndoGroup
DECL|function|AppendCommand
DECL|function|InsertCommand
DECL|function|RemoveCommand
DECL|function|addRemoveStack
DECL|function|addRemoveStack
DECL|function|addStackAndDie
DECL|function|addStackAndDie
DECL|function|checkSignals
DECL|function|checkSignals
DECL|function|commandTextFormat
DECL|function|deleteStack
DECL|function|deleteStack
DECL|function|glue
DECL|function|id
DECL|function|mergeWith
DECL|function|redo
DECL|function|redo
DECL|function|redo
DECL|function|setActive
DECL|function|setActive
DECL|function|tst_QUndoGroup
DECL|function|tst_QUndoGroup
DECL|function|undo
DECL|function|undo
DECL|function|undo
DECL|macro|CHECK_STATE
DECL|member|m_idx
DECL|member|m_idx
DECL|member|m_str
DECL|member|m_str
DECL|member|m_str
DECL|member|m_text
DECL|member|m_text
DECL|member|m_text
DECL|member|merged
