DECL|class|tst_QSystemSemaphore
DECL|function|basicProcesses
DECL|function|basicacquire
DECL|function|cleanup
DECL|function|complexacquire
DECL|function|helperBinary
DECL|function|init
DECL|function|initTestCase
DECL|function|initialValue
DECL|function|key
DECL|function|key_data
DECL|function|processes
DECL|function|processes_data
DECL|function|tst_QSystemSemaphore
DECL|function|undo
DECL|macro|EXISTING_SHARE
DECL|macro|HELPERWAITTIME
DECL|member|existingLock
