DECL|function|QT_MODULE
DECL|function|begin
DECL|function|begin
DECL|function|data
DECL|function|data
DECL|function|deallocate
DECL|function|end
DECL|function|end
DECL|function|fromRawData
DECL|function|sharedNull
DECL|macro|QARRAYDATA_H
DECL|macro|Q_STATIC_ARRAY_DATA_HEADER_INITIALIZER
DECL|member|data
DECL|member|header
DECL|struct|QArrayData
DECL|struct|QStaticArrayData
DECL|typedef|const_iterator
DECL|typedef|iterator
DECL|variable|T
