DECL|enumerator|CapacityReserved
DECL|enumerator|Default
DECL|enumerator|RawData
DECL|enumerator|Unsharable
DECL|enum|AllocationOption
DECL|function|Q_DECLARE_FLAGS
DECL|function|begin
DECL|function|begin
DECL|function|cloneFlags
DECL|function|data
DECL|function|data
DECL|function|data
DECL|function|data
DECL|function|deallocate
DECL|function|end
DECL|function|end
DECL|function|fromRawData
DECL|function|isMutable
DECL|function|sharedNull
DECL|macro|QARRAYDATA_H
DECL|macro|Q_ARRAY_LITERAL
DECL|macro|Q_ARRAY_LITERAL
DECL|macro|Q_ARRAY_LITERAL
DECL|macro|Q_ARRAY_LITERAL_IMPL
DECL|macro|Q_STATIC_ARRAY_DATA_HEADER_INITIALIZER
DECL|member|Q_REQUIRED_RESULT
DECL|member|alloc
DECL|member|capacityReserved
DECL|member|data
DECL|member|header
DECL|member|offset
DECL|member|ptr
DECL|member|ref
DECL|member|shared_null
DECL|member|size
DECL|struct|QArrayData
DECL|struct|QArrayData
DECL|struct|QArrayDataPointerRef
DECL|struct|QStaticArrayData
DECL|typedef|const_iterator
DECL|typedef|iterator
DECL|variable|T
