DECL|function|QByteArray
DECL|function|QByteArray
DECL|function|at
DECL|function|begin
DECL|function|begin
DECL|function|capacity
DECL|function|constBegin
DECL|function|constData
DECL|function|constEnd
DECL|function|data
DECL|function|data
DECL|function|data
DECL|function|data
DECL|function|detach
DECL|function|end
DECL|function|end
DECL|function|isDetached
DECL|function|isEmpty
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|qCompress
DECL|function|qUncompress
DECL|function|qstrcmp
DECL|function|qstrlen
DECL|function|qstrncmp
DECL|function|qstrnlen
DECL|function|reserve
DECL|function|size
DECL|function|squeeze
DECL|function|~QByteArray
DECL|macro|QBYTEARRAY_H
DECL|macro|QByteArrayLiteral
DECL|macro|QByteArrayLiteral
DECL|macro|QByteArrayLiteral
DECL|macro|QT_USE_FAST_OPERATOR_PLUS
DECL|macro|QT_USE_QSTRINGBUILDER
DECL|member|alloc
DECL|member|ba
DECL|member|capacityReserved
DECL|member|d
DECL|member|data
DECL|member|offset
DECL|member|operator
DECL|member|ptr
DECL|member|ref
DECL|member|size
DECL|struct|QByteArrayData
DECL|struct|QConstByteArrayData
DECL|struct|QConstByteArrayDataPtr
DECL|variable|QByteRef
DECL|variable|QDataStream
DECL|variable|QList
DECL|variable|QString
