DECL|function|QCache
DECL|function|QT_MODULE
DECL|function|clear
DECL|function|insert
DECL|function|object
DECL|function|operator
DECL|function|remove
DECL|function|setMaxCost
DECL|function|take
DECL|function|trim
DECL|macro|QCACHE_H
DECL|variable|Key
DECL|variable|Key
DECL|variable|Key
DECL|variable|Key
DECL|variable|Key
DECL|variable|Key
DECL|variable|Key
DECL|variable|Key
DECL|variable|Key
DECL|variable|Key
DECL|variable|Key
DECL|variable|Key
DECL|variable|Key
DECL|variable|Key
DECL|variable|Key
DECL|variable|Key
DECL|variable|Key
DECL|variable|Key
