DECL|class|QCollatorPrivate
DECL|function|QCollator
DECL|function|QCollator
DECL|function|QCollatorPrivate
DECL|function|casePreference
DECL|function|clear
DECL|function|collation
DECL|function|compare
DECL|function|compare
DECL|function|compare
DECL|function|detach
DECL|function|englishIndexCharacters
DECL|function|fromIdentifier
DECL|function|identifier
DECL|function|ignorePunctuation
DECL|function|indexCharacters
DECL|function|init
DECL|function|locale
DECL|function|numericMode
DECL|function|operator =
DECL|function|setCasePreference
DECL|function|setCollation
DECL|function|setIgnorePunctuation
DECL|function|setLocale
DECL|function|setNumericMode
DECL|function|sortKey
DECL|function|~QCollator
DECL|function|~QCollatorPrivate
DECL|member|collation
DECL|member|collator
DECL|member|collator
DECL|member|indexCharacters
DECL|member|locale
DECL|member|ref
DECL|variable|collationStrings
DECL|variable|collationStringsCount
