DECL|class|QCommandLineParserPrivate
DECL|function|QCommandLineParser
DECL|function|QCommandLineParserPrivate
DECL|function|addHelpOption
DECL|function|addOption
DECL|function|addPositionalArgument
DECL|function|addVersionOption
DECL|function|aliases
DECL|function|applicationDescription
DECL|function|checkParsed
DECL|function|clearPositionalArguments
DECL|function|errorText
DECL|function|helpText
DECL|function|helpText
DECL|function|isSet
DECL|function|isSet
DECL|function|optionNames
DECL|function|parse
DECL|function|parse
DECL|function|parseOptionValue
DECL|function|positionalArguments
DECL|function|process
DECL|function|process
DECL|function|registerFoundOption
DECL|function|setApplicationDescription
DECL|function|setSingleDashWordOptionMode
DECL|function|showHelp
DECL|function|unknownOptionNames
DECL|function|value
DECL|function|value
DECL|function|values
DECL|function|values
DECL|function|wrapText
DECL|function|~QCommandLineParser
DECL|member|builtinHelpOption
DECL|member|builtinVersionOption
DECL|member|commandLineOptionList
DECL|member|description
DECL|member|description
DECL|member|errorText
DECL|member|name
DECL|member|nameHash
DECL|member|needsParsing
DECL|member|optionNames
DECL|member|optionValuesHash
DECL|member|positionalArgumentDefinitions
DECL|member|positionalArgumentList
DECL|member|singleDashWordOptionMode
DECL|member|syntax
DECL|member|unknownOptionNames
DECL|struct|PositionalArgumentDefinition
DECL|typedef|NameHash_t
DECL|variable|optionNotFound
