DECL|function|QCLocaleT
DECL|function|qDoubleSnprintf
DECL|function|qDoubleSscanf
DECL|function|~QCLocaleT
DECL|macro|QDOUBLESCANPRINT_P_H
DECL|macro|QT_CLOCALE
DECL|macro|QT_CLOCALE_HOLDER
DECL|member|locale
DECL|struct|QCLocaleT
