DECL|function|clockType
DECL|function|do_gettime
DECL|function|elapsed
DECL|function|elapsedAndRestart
DECL|function|fractionAdjustment
DECL|function|isMonotonic
DECL|function|msecsSinceReference
DECL|function|msecsTo
DECL|function|nsecsElapsed
DECL|function|operator <
DECL|function|qt_gettime
DECL|function|restart
DECL|function|secsTo
DECL|function|start
DECL|function|unixCheckClockType
DECL|macro|_POSIX_MONOTONIC_CLOCK
DECL|macro|_POSIX_MONOTONIC_CLOCK
DECL|macro|is_likely
DECL|macro|is_likely
DECL|macro|load_acquire
DECL|macro|store_release
DECL|variable|monotonicClockAvailable
DECL|variable|monotonicClockChecked
