DECL|function|do_gettime
DECL|function|elapsedAndRestart
DECL|function|qt_clock_gettime
DECL|function|qt_nanosleep
DECL|function|unixCheckClockType
DECL|macro|INVALID_CLOCK
DECL|macro|INVALID_CLOCK
DECL|macro|IS_VALID_CLOCK
DECL|macro|IS_VALID_CLOCK
DECL|macro|_POSIX_C_SOURCE
DECL|macro|_POSIX_MONOTONIC_CLOCK
DECL|macro|_POSIX_MONOTONIC_CLOCK
