DECL|enumerator|BlockCount
DECL|enumerator|IndexMask
DECL|enumerator|InitialNextValue
DECL|enumerator|MaxIndex
DECL|enumerator|SerialCounter
DECL|enumerator|SerialMask
DECL|function|QFreeList
DECL|function|at
DECL|function|next
DECL|function|operator
DECL|function|release
DECL|function|t
DECL|function|t
DECL|function|~QFreeList
DECL|macro|QFREELIST_P_H
DECL|member|Sizes
DECL|member|_t
DECL|member|next
DECL|struct|QFreeListDefaultConstants
DECL|struct|QFreeListElement
DECL|typedef|ConstReferenceType
DECL|typedef|ReferenceType
DECL|variable|ConstantsType
DECL|variable|T
DECL|variable|T
DECL|variable|T
DECL|variable|T
DECL|variable|T
DECL|variable|T
DECL|variable|T
DECL|variable|T
DECL|variable|T
DECL|variable|T
DECL|variable|T
DECL|variable|T
DECL|variable|T
