DECL|enumerator|BlockCount
DECL|enumerator|IndexMask
DECL|enumerator|InitialNextValue
DECL|enumerator|MaxIndex
DECL|enumerator|SerialCounter
DECL|enumerator|SerialMask
DECL|function|QFreeList
DECL|function|QT_MODULE
DECL|function|at
DECL|function|next
DECL|function|operator
DECL|function|release
DECL|function|~QFreeList
DECL|macro|QFREELIST_P_H
DECL|member|Sizes
DECL|struct|QFreeListDefaultConstants
DECL|variable|ConstantsType
DECL|variable|T
DECL|variable|T
DECL|variable|T
DECL|variable|T
DECL|variable|T
DECL|variable|T
DECL|variable|T
DECL|variable|T
DECL|variable|T
DECL|variable|T
DECL|variable|T
DECL|variable|T
DECL|variable|T
