DECL|function|QLine
DECL|function|QLine
DECL|function|QLine
DECL|function|QLineF
DECL|function|QLineF
DECL|function|QLineF
DECL|function|dx
DECL|function|dx
DECL|function|dy
DECL|function|dy
DECL|function|isNull
DECL|function|isNull
DECL|function|normalVector
DECL|function|operator
DECL|function|operator
DECL|function|p1
DECL|function|p1
DECL|function|p2
DECL|function|p2
DECL|function|pointAt
DECL|function|setLength
DECL|function|setLine
DECL|function|setLine
DECL|function|setP1
DECL|function|setP1
DECL|function|setP2
DECL|function|setP2
DECL|function|setPoints
DECL|function|setPoints
DECL|function|toLine
DECL|function|translate
DECL|function|translate
DECL|function|translate
DECL|function|translate
DECL|function|translated
DECL|function|translated
DECL|function|translated
DECL|function|translated
DECL|function|x1
DECL|function|x1
DECL|function|x2
DECL|function|x2
DECL|function|y1
DECL|function|y1
DECL|function|y2
DECL|function|y2
DECL|macro|QLINE_H
