DECL|function|QLinkedListNode
DECL|function|clear
DECL|function|detach_helper
DECL|function|detach_helper2
DECL|function|freeData
DECL|function|~QLinkedList
DECL|macro|QLINKEDLIST_H
DECL|member|n
DECL|member|n
DECL|member|p
DECL|member|p
DECL|member|ref
DECL|member|sharable
DECL|member|shared_null
DECL|member|size
DECL|member|t
DECL|struct|QLinkedListData
DECL|struct|QLinkedListNode
