DECL|function|append
DECL|function|append
DECL|function|append
DECL|function|append2
DECL|function|detach
DECL|function|detach
DECL|function|detach2
DECL|function|detach3
DECL|function|detach_grow
DECL|function|erase
DECL|function|grow
DECL|function|insert
DECL|function|move
DECL|function|prepend
DECL|function|realloc
DECL|function|remove
DECL|function|remove
DECL|member|shared_null
