DECL|function|QPair
DECL|function|QPair
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|qMakePair
DECL|macro|QPAIR_H
DECL|member|T1
DECL|member|operator
DECL|member|second
DECL|struct|QPair
DECL|typedef|first_type
DECL|typedef|second_type
DECL|variable|T1
DECL|variable|T1
DECL|variable|T1
DECL|variable|T1
DECL|variable|T1
DECL|variable|T1
DECL|variable|T1
DECL|variable|T1
DECL|variable|T1
DECL|variable|T1
DECL|variable|operator
