DECL|function|getCoords
DECL|function|getCoords
DECL|function|getRect
DECL|function|getRect
DECL|function|h
DECL|function|h
DECL|function|h
DECL|function|h
DECL|function|y2
DECL|function|y2
DECL|macro|QRECT_H
DECL|member|operator
DECL|member|operator
