DECL|function|append
DECL|function|chop
DECL|function|clear
DECL|function|free
DECL|function|indexOf
DECL|function|indexOf
DECL|function|peek
DECL|function|read
DECL|function|read
DECL|function|readLine
DECL|function|readPointerAtPosition
DECL|function|reserve
DECL|function|reserveFront
