DECL|function|cleanup
DECL|function|cleanup
DECL|function|cleanup
DECL|function|operator
DECL|function|operator
DECL|function|qSwap
DECL|macro|QSCOPEDPOINTER_H
DECL|struct|QScopedPointerArrayDeleter
DECL|struct|QScopedPointerDeleter
DECL|struct|QScopedPointerPodDeleter
DECL|variable|Cleanup
DECL|variable|Cleanup
DECL|variable|T
DECL|variable|T
DECL|variable|T
DECL|variable|T
DECL|variable|T
