DECL|class|KnownPointers
DECL|function|checkQObjectShared
DECL|function|getAndRef
DECL|function|internalSafetyCheckAdd
DECL|function|internalSafetyCheckAdd2
DECL|function|internalSafetyCheckCleanCheck
DECL|function|internalSafetyCheckRemove
DECL|function|internalSafetyCheckRemove2
DECL|function|printBacktrace
DECL|function|saveBacktrace
DECL|function|setQObjectShared
DECL|macro|BACKTRACE_SUPPORTED
DECL|member|backtrace
DECL|member|dPointers
DECL|member|dataPointers
DECL|member|mutex
DECL|member|pointer
DECL|namespace|QtSharedPointer
DECL|struct|Data
