DECL|enumerator|AVX
DECL|enumerator|AVX2
DECL|enumerator|HLE
DECL|enumerator|IWMMXT
DECL|enumerator|NEON
DECL|enumerator|QSimdInitialized
DECL|enumerator|RTM
DECL|enumerator|SSE2
DECL|enumerator|SSE3
DECL|enumerator|SSE4_1
DECL|enumerator|SSE4_2
DECL|enumerator|SSSE3
DECL|enum|CPUFeatures
DECL|function|_bit_scan_reverse
DECL|function|_bit_scan_reverse
DECL|function|qCpuFeatures
DECL|macro|ALIGNMENT_PROLOGUE_16BYTES
DECL|macro|QSIMD_P_H
DECL|macro|QT_COMPILER_SUPPORTS_X86INTRIN
DECL|macro|__AVX2__
DECL|macro|__AVX__
DECL|macro|__BMI__
DECL|macro|__FMA__
DECL|macro|__SSE2__
DECL|macro|__SSE3__
DECL|macro|__SSE4_1__
DECL|macro|__SSE4_2__
DECL|macro|__SSE__
DECL|macro|__SSSE3__
DECL|macro|posix_memalign
DECL|macro|posix_memalign
DECL|macro|qCpuHasFeature
DECL|variable|qCompilerCpuFeatures
