DECL|enumerator|ARM_NEON
DECL|enumerator|AVX
DECL|enumerator|AVX2
DECL|enumerator|DSP
DECL|enumerator|DSPR2
DECL|enumerator|HLE
DECL|enumerator|IWMMXT
DECL|enumerator|NEON
DECL|enumerator|QSimdInitialized
DECL|enumerator|RTM
DECL|enumerator|SSE2
DECL|enumerator|SSE3
DECL|enumerator|SSE4_1
DECL|enumerator|SSE4_2
DECL|enumerator|SSSE3
DECL|enum|CPUFeatures
DECL|function|_bit_scan_forward
DECL|function|_bit_scan_forward
DECL|function|_bit_scan_reverse
DECL|function|_bit_scan_reverse
DECL|function|qCpuFeatures
DECL|macro|ALIGNMENT_PROLOGUE_16BYTES
DECL|macro|QSIMD_P_H
DECL|macro|QT_COMPILER_SUPPORTS
DECL|macro|QT_COMPILER_SUPPORTS_HERE
DECL|macro|QT_COMPILER_SUPPORTS_HERE
DECL|macro|QT_COMPILER_SUPPORTS_SIMD_ALWAYS
DECL|macro|QT_COMPILER_SUPPORTS_SIMD_ALWAYS
DECL|macro|QT_COMPILER_SUPPORTS_X86INTRIN
DECL|macro|QT_FUNCTION_TARGET
DECL|macro|QT_FUNCTION_TARGET
DECL|macro|QT_FUNCTION_TARGET
DECL|macro|QT_FUNCTION_TARGET_STRING_ARM_NEON
DECL|macro|QT_FUNCTION_TARGET_STRING_AVX
DECL|macro|QT_FUNCTION_TARGET_STRING_AVX2
DECL|macro|QT_FUNCTION_TARGET_STRING_SSE2
DECL|macro|QT_FUNCTION_TARGET_STRING_SSE3
DECL|macro|QT_FUNCTION_TARGET_STRING_SSE4_1
DECL|macro|QT_FUNCTION_TARGET_STRING_SSE4_2
DECL|macro|QT_FUNCTION_TARGET_STRING_SSSE3
DECL|macro|__AVX__
DECL|macro|__SSE2__
DECL|macro|__SSE3__
DECL|macro|__SSE4_1__
DECL|macro|__SSE4_2__
DECL|macro|__SSE__
DECL|macro|__SSSE3__
DECL|macro|posix_memalign
DECL|macro|posix_memalign
DECL|macro|qCpuHasFeature
DECL|variable|qCompilerCpuFeatures
