DECL|function|QSize
DECL|function|QSize
DECL|function|QSizeF
DECL|function|QSizeF
DECL|function|QSizeF
DECL|function|QT_MODULE
DECL|function|height
DECL|function|height
DECL|function|isEmpty
DECL|function|isEmpty
DECL|function|isNull
DECL|function|isNull
DECL|function|isValid
DECL|function|isValid
DECL|function|rheight
DECL|function|rheight
DECL|function|rwidth
DECL|function|rwidth
DECL|function|scale
DECL|function|scale
DECL|function|setHeight
DECL|function|setHeight
DECL|function|setWidth
DECL|function|setWidth
DECL|function|width
DECL|function|width
DECL|macro|QSIZE_H
DECL|member|operator
DECL|member|operator
