DECL|function|toLower
DECL|function|toUpper
DECL|macro|QSTRINGBUILDER_H
DECL|member|Q_DECL_NOTHROW
DECL|member|Q_DECL_NOTHROW
DECL|member|len
DECL|member|protected
DECL|member|protected
DECL|struct|QAbstractConcatenable
DECL|struct|QConcatenable
DECL|struct|QStringBuilderCommon
DECL|variable|Builder
