DECL|function|QString
DECL|function|QString
DECL|function|QStringRef
DECL|function|Q_DECLARE_SHARED
DECL|function|at
DECL|function|begin
DECL|function|begin
DECL|function|constBegin
DECL|function|constData
DECL|function|constEnd
DECL|function|contains
DECL|function|contains
DECL|function|contains
DECL|function|data
DECL|function|data
DECL|function|detach
DECL|function|end
DECL|function|end
DECL|function|isDetached
DECL|function|isEmpty
DECL|function|length
DECL|function|m_size
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|qStringComparisonHelper
DECL|function|reserve
DECL|function|setCell
DECL|function|setRow
DECL|function|setUtf16
DECL|function|unicode
DECL|function|~QString
DECL|macro|QSTRING_H
DECL|member|operator
DECL|member|operator
DECL|member|operator
DECL|typedef|QStdWString
DECL|variable|QLatin1String
DECL|variable|QRegExp
DECL|variable|QStringList
DECL|variable|QStringRef
DECL|variable|QTextCodec
DECL|variable|QVector
