DECL|function|QString
DECL|function|QString
DECL|function|QStringData
DECL|function|QStringData
DECL|function|QStringData
DECL|function|QStringRef
DECL|function|Q_DECLARE_SHARED
DECL|function|at
DECL|function|begin
DECL|function|begin
DECL|function|constBegin
DECL|function|constData
DECL|function|constEnd
DECL|function|contains
DECL|function|contains
DECL|function|contains
DECL|function|data
DECL|function|data
DECL|function|data
DECL|function|data
DECL|function|detach
DECL|function|end
DECL|function|end
DECL|function|isDetached
DECL|function|isEmpty
DECL|function|length
DECL|function|m_size
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|qStringComparisonHelper
DECL|function|reserve
DECL|function|setCell
DECL|function|setRow
DECL|function|setUtf16
DECL|function|unicode
DECL|function|~QString
DECL|macro|QSTRING_H
DECL|macro|QStringLiteral
DECL|macro|QStringLiteral
DECL|macro|QStringLiteral
DECL|macro|QT_QSTRING_UNICODE_MARKER
DECL|macro|QT_QSTRING_UNICODE_MARKER
DECL|member|alloc
DECL|member|capacityReserved
DECL|member|d
DECL|member|data
DECL|member|data
DECL|member|data
DECL|member|offset
DECL|member|operator
DECL|member|operator
DECL|member|operator
DECL|member|ptr
DECL|member|ref
DECL|member|size
DECL|member|str
DECL|member|str
DECL|member|str
DECL|struct|QConstStringData
DECL|struct|QConstStringData
DECL|struct|QConstStringData
DECL|struct|QConstStringDataPtr
DECL|struct|QStringData
DECL|typedef|QLatin1Literal
DECL|typedef|QStdWString
DECL|variable|QLatin1String
DECL|variable|QRegExp
DECL|variable|QStringList
DECL|variable|QStringRef
DECL|variable|QTextCodec
DECL|variable|QVector
