DECL|function|simplified
DECL|function|simplified
DECL|function|toCaseFolded
DECL|function|toLatin1
DECL|function|toLocal8Bit
DECL|function|toLower
DECL|function|toLower
DECL|function|toUpper
DECL|function|toUpper
DECL|function|toUtf8
DECL|function|trimmed
DECL|function|trimmed
DECL|macro|QT_COMPILING_QSTRING_COMPAT_CPP
