DECL|class|qt_section_chunk
DECL|function|QString
DECL|function|QString
DECL|function|QString
DECL|function|QString
DECL|function|append
DECL|function|append
DECL|function|append
DECL|function|append
DECL|function|append
DECL|function|appendTo
DECL|function|arg
DECL|function|arg
DECL|function|arg
DECL|function|arg
DECL|function|arg
DECL|function|arg
DECL|function|chop
DECL|function|compare
DECL|function|compare
DECL|function|compare_helper
DECL|function|compare_helper
DECL|function|compare_helper
DECL|function|contains
DECL|function|contains
DECL|function|count
DECL|function|count
DECL|function|count
DECL|function|count
DECL|function|count
DECL|function|count
DECL|function|count
DECL|function|count
DECL|function|endsWith
DECL|function|endsWith
DECL|function|endsWith
DECL|function|endsWith
DECL|function|endsWith
DECL|function|endsWith
DECL|function|endsWith
DECL|function|endsWith
DECL|function|expand
DECL|function|extractSections
DECL|function|fill
DECL|function|findArgEscapes
DECL|function|findChar
DECL|function|fromAscii_helper
DECL|function|fromLatin1_helper
DECL|function|fromLocal8Bit_helper
DECL|function|fromRawData
DECL|function|fromUcs4
DECL|function|fromUtf16
DECL|function|fromUtf8_helper
DECL|function|getEscape
DECL|function|indexOf
DECL|function|indexOf
DECL|function|indexOf
DECL|function|indexOf
DECL|function|indexOf
DECL|function|indexOf
DECL|function|indexOf
DECL|function|indexOf
DECL|function|indexOf
DECL|function|indexOf
DECL|function|indexOf
DECL|function|insert
DECL|function|insert
DECL|function|insert
DECL|function|isRightToLeft
DECL|function|isSimpleText
DECL|function|lastIndexOf
DECL|function|lastIndexOf
DECL|function|lastIndexOf
DECL|function|lastIndexOf
DECL|function|lastIndexOf
DECL|function|lastIndexOf
DECL|function|lastIndexOf
DECL|function|lastIndexOf
DECL|function|lastIndexOf
DECL|function|lastIndexOf
DECL|function|lastIndexOf
DECL|function|lastIndexOfHelper
DECL|function|left
DECL|function|leftJustified
DECL|function|leftRef
DECL|function|localeAwareCompare
DECL|function|localeAwareCompare_helper
DECL|function|mergeQuestionMarks
DECL|function|mid
DECL|function|midRef
DECL|function|multiArg
DECL|function|normalized
DECL|function|number
DECL|function|number
DECL|function|number
DECL|function|number
DECL|function|number
DECL|function|number
DECL|function|number
DECL|function|operator <
DECL|function|operator <
DECL|function|operator <
DECL|function|operator <<
DECL|function|operator =
DECL|function|operator =
DECL|function|operator ==
DECL|function|operator ==
DECL|function|operator ==
DECL|function|operator ==
DECL|function|operator ==
DECL|function|operator >
DECL|function|operator >>
DECL|function|qFindString
DECL|function|qIsDigit
DECL|function|qIsUpper
DECL|function|qMemEquals
DECL|function|qToLower
DECL|function|qt_ends_with
DECL|function|qt_ends_with
DECL|function|qt_find_latin1_string
DECL|function|qt_last_index_of
DECL|function|qt_section_chunk
DECL|function|qt_starts_with
DECL|function|qt_starts_with
DECL|function|qt_string_count
DECL|function|qt_string_count
DECL|function|qt_string_normalize
DECL|function|reallocData
DECL|function|remove
DECL|function|remove
DECL|function|remove
DECL|function|repeated
DECL|function|replace
DECL|function|replace
DECL|function|replace
DECL|function|replace
DECL|function|replace
DECL|function|replace
DECL|function|replace
DECL|function|replace
DECL|function|replace
DECL|function|replace
DECL|function|replace
DECL|function|replace
DECL|function|replace
DECL|function|replaceArgEscapes
DECL|function|replace_helper
DECL|function|resize
DECL|function|right
DECL|function|rightJustified
DECL|function|rightRef
DECL|function|section
DECL|function|section
DECL|function|section
DECL|function|setNum
DECL|function|setNum
DECL|function|setNum
DECL|function|setRawData
DECL|function|setUnicode
DECL|function|simplified
DECL|function|split
DECL|function|split
DECL|function|split
DECL|function|split
DECL|function|sprintf
DECL|function|startsWith
DECL|function|startsWith
DECL|function|startsWith
DECL|function|startsWith
DECL|function|startsWith
DECL|function|startsWith
DECL|function|startsWith
DECL|function|startsWith
DECL|function|toCaseFolded
DECL|function|toDouble
DECL|function|toFloat
DECL|function|toHtmlEscaped
DECL|function|toInt
DECL|function|toLatin1
DECL|function|toLatin1
DECL|function|toLatin1_helper
DECL|function|toLocal8Bit
DECL|function|toLocal8Bit
DECL|function|toLocal8Bit_helper
DECL|function|toLong
DECL|function|toLongLong
DECL|function|toLower
DECL|function|toShort
DECL|function|toString
DECL|function|toUInt
DECL|function|toULong
DECL|function|toULongLong
DECL|function|toUShort
DECL|function|toUcs4
DECL|function|toUcs4
DECL|function|toUcs4_helper
DECL|function|toUpper
DECL|function|toUtf8
DECL|function|toUtf8
DECL|function|trimmed
DECL|function|truncate
DECL|function|ucstrcmp
DECL|function|ucstricmp
DECL|function|ucstricmp
DECL|function|ucstrncmp
DECL|function|ucstrnicmp
DECL|function|utf16
DECL|function|vsprintf
DECL|macro|CSTR_EQUAL
DECL|macro|CSTR_GREATER_THAN
DECL|macro|CSTR_LESS_THAN
DECL|macro|IS_RAW_DATA
DECL|macro|LLONG_MAX
DECL|macro|LLONG_MIN
DECL|macro|QT_MAX_FLOAT
DECL|macro|REHASH
DECL|macro|ULLONG_MAX
DECL|macro|truncate
DECL|member|escape_len
DECL|member|len
DECL|member|length
DECL|member|locale_occurrences
DECL|member|min_escape
DECL|member|no
DECL|member|null
DECL|member|occurrences
DECL|member|pos
DECL|member|string
DECL|struct|ArgEscapeData
DECL|struct|QStringCapture
