DECL|function|QString
DECL|function|QString
DECL|function|QStringRef
DECL|function|Q_DECLARE_SHARED
DECL|function|at
DECL|function|begin
DECL|function|begin
DECL|function|cbegin
DECL|function|cend
DECL|function|constBegin
DECL|function|constData
DECL|function|constEnd
DECL|function|contains
DECL|function|contains
DECL|function|contains
DECL|function|data
DECL|function|data
DECL|function|data_ptr
DECL|function|detach
DECL|function|end
DECL|function|end
DECL|function|isDetached
DECL|function|isEmpty
DECL|function|length
DECL|function|m_size
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|reserve
DECL|function|setCell
DECL|function|setRow
DECL|function|setUtf16
DECL|function|squeeze
DECL|function|unicode
DECL|function|~QString
DECL|macro|QSTRING_H
DECL|macro|QStringLiteral
DECL|macro|QStringLiteral
DECL|macro|QT_NO_UNICODE_LITERAL
DECL|macro|QT_UNICODE_LITERAL
DECL|macro|QT_UNICODE_LITERAL_II
DECL|macro|QT_UNICODE_LITERAL_II
DECL|macro|QT_UNICODE_LITERAL_II
DECL|macro|Q_STATIC_STRING_DATA_HEADER_INITIALIZER
DECL|macro|Q_STATIC_STRING_DATA_HEADER_INITIALIZER_WITH_OFFSET
DECL|member|data
DECL|member|operator
DECL|member|operator
DECL|member|ptr
DECL|member|str
DECL|struct|QStaticStringData
DECL|struct|QStringDataPtr
DECL|typedef|QLatin1Literal
DECL|typedef|QStringData
DECL|typedef|qunicodechar
DECL|typedef|qunicodechar
DECL|typedef|qunicodechar
DECL|variable|QCharRef
DECL|variable|QRegExp
DECL|variable|QRegularExpression
DECL|variable|QRegularExpressionMatch
DECL|variable|QString
DECL|variable|QStringList
DECL|variable|QStringRef
DECL|variable|QTextCodec
DECL|variable|QVector
DECL|variable|operator
