DECL|function|QTimeZonePrivate
DECL|function|QTimeZonePrivate
DECL|function|QUtcTimeZonePrivate
DECL|function|QUtcTimeZonePrivate
DECL|function|QUtcTimeZonePrivate
DECL|function|QUtcTimeZonePrivate
DECL|function|QUtcTimeZonePrivate
DECL|function|abbreviation
DECL|function|abbreviation
DECL|function|availableTimeZoneIds
DECL|function|availableTimeZoneIds
DECL|function|availableTimeZoneIds
DECL|function|availableTimeZoneIds
DECL|function|availableTimeZoneIds
DECL|function|availableTimeZoneIds
DECL|function|clone
DECL|function|clone
DECL|function|clone
DECL|function|comment
DECL|function|comment
DECL|function|country
DECL|function|country
DECL|function|data
DECL|function|daylightTimeOffset
DECL|function|daylightTimeOffset
DECL|function|displayName
DECL|function|displayName
DECL|function|displayName
DECL|function|hasDaylightTime
DECL|function|hasTransitions
DECL|function|id
DECL|function|init
DECL|function|init
DECL|function|invalidData
DECL|function|invalidOffsetData
DECL|function|isDaylightTime
DECL|function|isValid
DECL|function|isValidId
DECL|function|isoOffsetFormat
DECL|function|nextTransition
DECL|function|offsetFromUtc
DECL|function|olsenId
DECL|function|olsenId
DECL|function|olsenIdToWindowsId
DECL|function|operator !=
DECL|function|operator ==
DECL|function|previousTransition
DECL|function|serialize
DECL|function|serialize
DECL|function|standardTimeOffset
DECL|function|standardTimeOffset
DECL|function|systemTimeZoneId
DECL|function|systemTimeZoneId
DECL|function|toOffsetData
DECL|function|toWindowsIdKey
DECL|function|toWindowsIdLiteral
DECL|function|transitions
DECL|function|utcData
DECL|function|utcId
DECL|function|windowsData
DECL|function|windowsId
DECL|function|windowsIdToDefaultOlsenId
DECL|function|windowsIdToDefaultOlsenId
DECL|function|windowsIdToOlsenIds
DECL|function|windowsIdToOlsenIds
DECL|function|zoneData
DECL|function|~QTimeZonePrivate
DECL|function|~QUtcTimeZonePrivate
DECL|variable|utcDataTableSize
DECL|variable|windowsDataTableSize
DECL|variable|zoneDataTableSize
