DECL|function|QTzTimeZonePrivate
DECL|function|QTzTimeZonePrivate
DECL|function|QTzTimeZonePrivate
DECL|function|abbreviation
DECL|function|availableTimeZoneIds
DECL|function|availableTimeZoneIds
DECL|function|calculateDowDate
DECL|function|calculatePosixDate
DECL|function|calculatePosixTransitions
DECL|function|clone
DECL|function|comment
DECL|function|country
DECL|function|data
DECL|function|dataForTzTransition
DECL|function|daylightTimeOffset
DECL|function|displayName
DECL|function|displayName
DECL|function|hasDaylightTime
DECL|function|hasTransitions
DECL|function|init
DECL|function|isDaylightTime
DECL|function|loadTzTimeZones
DECL|function|nextTransition
DECL|function|offsetFromUtc
DECL|function|parsePosixOffset
DECL|function|parsePosixTime
DECL|function|parseTzAbbreviations
DECL|function|parseTzHeader
DECL|function|parseTzIndicators
DECL|function|parseTzLeapSeconds
DECL|function|parseTzPosixRule
DECL|function|parseTzTransitions
DECL|function|parseTzTypes
DECL|function|previousTransition
DECL|function|standardTimeOffset
DECL|function|systemTimeZoneId
DECL|function|~QTzTimeZonePrivate
DECL|macro|TZ_MAGIC
DECL|macro|TZ_MAX_CHARS
DECL|macro|TZ_MAX_LEAPS
DECL|macro|TZ_MAX_TIMES
DECL|macro|TZ_MAX_TYPES
DECL|member|comment
DECL|member|country
DECL|member|tz_abbrind
DECL|member|tz_gmtoff
DECL|member|tz_isdst
DECL|member|tz_time
DECL|member|tz_ttisgmt
DECL|member|tz_ttisstd
DECL|member|tz_typeind
DECL|member|tzh_charcnt
DECL|member|tzh_leapcnt
DECL|member|tzh_magic
DECL|member|tzh_reserved
DECL|member|tzh_timecnt
DECL|member|tzh_ttisgmtcnt
DECL|member|tzh_ttisstdcnt
DECL|member|tzh_typecnt
DECL|member|tzh_version
DECL|struct|QTzHeader
DECL|struct|QTzTimeZone
DECL|struct|QTzTransition
DECL|struct|QTzType
DECL|typedef|QTzTimeZoneHash
