DECL|macro|QTIMEZONEPRIVATE_DATA_P_H
DECL|member|country
DECL|member|ianaIdIndex
DECL|member|ianaIdIndex
DECL|member|ianaIdIndex
DECL|member|offsetFromUtc
DECL|member|offsetFromUtc
DECL|member|windowsIdIndex
DECL|member|windowsIdKey
DECL|member|windowsIdKey
DECL|struct|QUtcData
DECL|struct|QWindowsData
DECL|struct|QZoneData
DECL|variable|ianaIdData
DECL|variable|utcDataTable
DECL|variable|windowsDataTable
DECL|variable|windowsIdData
DECL|variable|zoneDataTable
