DECL|enumerator|JULIAN_DAY_FOR_EPOCH
DECL|enumerator|MAX_YEAR
DECL|enumerator|MIN_YEAR
DECL|enumerator|MSECS_PER_DAY
DECL|enumerator|TIME_T_MAX
DECL|function|QWinTimeZonePrivate
DECL|function|QWinTimeZonePrivate
DECL|function|QWinTimeZonePrivate
DECL|function|abbreviation
DECL|function|availableTimeZoneIds
DECL|function|availableWindowsIds
DECL|function|calculateTransitionLocalDate
DECL|function|calculateTransitionsForYear
DECL|function|clone
DECL|function|comment
DECL|function|data
DECL|function|daylightTimeOffset
DECL|function|displayName
DECL|function|equalSystemtime
DECL|function|equalTzi
DECL|function|getRegistryTzi
DECL|function|hasDaylightTime
DECL|function|hasTransitions
DECL|function|init
DECL|function|isDaylightTime
DECL|function|msecsToDate
DECL|function|msecsToSystemtime
DECL|function|nextTransition
DECL|function|offsetFromUtc
DECL|function|openRegistryKey
DECL|function|previousTransition
DECL|function|readRegistryRule
DECL|function|readRegistryString
DECL|function|readRegistryValue
DECL|function|ruleForYear
DECL|function|ruleToData
DECL|function|standardTimeOffset
DECL|function|systemTimeZoneId
DECL|function|systemtimeToMsecs
DECL|function|timeToMSecs
DECL|function|userCountry
DECL|function|windowsSystemZoneId
DECL|function|~QWinTimeZonePrivate
DECL|macro|FILETIME_UNIX_EPOCH
DECL|macro|MAX_KEY_LENGTH
DECL|member|Bias
DECL|member|DaylightBias
DECL|member|DaylightDate
DECL|member|StandardBias
DECL|member|StandardDate
DECL|struct|_REG_TZI_FORMAT
DECL|typedef|REG_TZI_FORMAT
DECL|variable|currTzRegPath
DECL|variable|tzRegPath
