DECL|macro|QTIMEZONEPRIVATE_P_H
DECL|member|abbreviationIndex
DECL|member|atMSecsSinceEpoch
DECL|member|dstOffset
DECL|member|ruleIndex
DECL|member|stdOffset
DECL|struct|QTzTransitionRule
DECL|struct|QTzTransitionTime
DECL|variable|NSTimeZone
DECL|variable|NSTimeZone
