DECL|class|QTimeLinePrivate
DECL|function|QTimeLine
DECL|function|QTimeLinePrivate
DECL|function|currentFrame
DECL|function|currentTime
DECL|function|currentValue
DECL|function|curveShape
DECL|function|direction
DECL|function|duration
DECL|function|easingCurve
DECL|function|endFrame
DECL|function|frameForTime
DECL|function|loopCount
DECL|function|resume
DECL|function|setCurrentTime
DECL|function|setCurrentTime
DECL|function|setCurveShape
DECL|function|setDirection
DECL|function|setDuration
DECL|function|setEasingCurve
DECL|function|setEndFrame
DECL|function|setFrameRange
DECL|function|setLoopCount
DECL|function|setPaused
DECL|function|setStartFrame
DECL|function|setState
DECL|function|setUpdateInterval
DECL|function|start
DECL|function|startFrame
DECL|function|state
DECL|function|stop
DECL|function|timerEvent
DECL|function|toggleDirection
DECL|function|updateInterval
DECL|function|valueForTime
DECL|function|~QTimeLine
DECL|member|currentLoopCount
DECL|member|currentTime
DECL|member|direction
DECL|member|duration
DECL|member|easingCurve
DECL|member|endFrame
DECL|member|startFrame
DECL|member|startTime
DECL|member|state
DECL|member|timer
DECL|member|timerId
DECL|member|totalLoopCount
DECL|member|updateInterval
