DECL|enumerator|ACS
DECL|enumerator|ATerm
DECL|enumerator|ATermC
DECL|enumerator|BAfter
DECL|enumerator|BAfterC
DECL|enumerator|Break
DECL|enumerator|Break
DECL|enumerator|CI
DECL|enumerator|CP
DECL|enumerator|CombiningIndirectBreak
DECL|enumerator|CombiningProhibitedBreak
DECL|enumerator|DB
DECL|enumerator|DirectBreak
DECL|enumerator|IB
DECL|enumerator|IndirectBreak
DECL|enumerator|Initial
DECL|enumerator|Lookup
DECL|enumerator|Lookup
DECL|enumerator|NoBreak
DECL|enumerator|PB
DECL|enumerator|ProhibitedBreak
DECL|enumerator|SCS
DECL|enumerator|STerm
DECL|enumerator|STermC
DECL|enumerator|UpATerm
DECL|enumerator|Upper
DECL|enum|Action
DECL|enum|Action
DECL|enum|State
DECL|function|getGraphemeBreaks
DECL|function|getLineBreaks
DECL|function|getSentenceBreaks
DECL|function|getWhiteSpaces
DECL|function|getWordBreaks
DECL|function|initCharAttributes
DECL|macro|FLAG
DECL|member|breakTable
DECL|member|breakTable
DECL|member|breakTable
DECL|member|breakTable
DECL|namespace|GB
DECL|namespace|LB
DECL|namespace|QUnicodeTools
DECL|namespace|SB
DECL|namespace|WB
DECL|variable|qt_initcharattributes_default_algorithm_only
