DECL|enumerator|NumNormalizationCorrections
DECL|enumerator|UnicodeBlockCount
DECL|enumerator|UnicodeBlockSize
DECL|function|lineBreakClass
DECL|function|properties
DECL|function|properties
DECL|function|qGetProp
DECL|function|qGetProp
DECL|function|script
DECL|macro|GET_DECOMPOSITION_INDEX
DECL|macro|GET_LIGATURE_INDEX
DECL|macro|GET_PROP_INDEX
DECL|macro|GET_PROP_INDEX_UCS2
DECL|macro|SPECIAL_CASE_MAX_LEN
DECL|member|old_mapping
DECL|member|uc_scripts
DECL|member|ucs4
DECL|member|version
DECL|namespace|QUnicodeTables
DECL|struct|NormalizationCorrection
DECL|variable|specialCaseMap
DECL|variable|uc_decomposition_map
DECL|variable|uc_decomposition_trie
DECL|variable|uc_ligature_map
DECL|variable|uc_ligature_trie
DECL|variable|uc_normalization_corrections
DECL|variable|uc_properties
DECL|variable|uc_property_trie
