DECL|macro|QUNICODETOOLS_P_H
DECL|member|graphemeBoundary
DECL|member|lineBreak
DECL|member|sentenceBoundary
DECL|member|unused
DECL|member|whiteSpace
DECL|member|wordBreak
DECL|member|wordEnd
DECL|member|wordStart
DECL|struct|QCharAttributes
