DECL|function|at
DECL|function|clear
DECL|function|copyConstruct
DECL|function|defaultConstruct
DECL|function|destruct
DECL|function|detach
DECL|function|insert
DECL|function|insert
DECL|function|operator
DECL|function|operator
DECL|function|prepend
DECL|function|remove
DECL|function|remove
DECL|function|replace
DECL|function|reserve
DECL|function|resize
DECL|macro|QVECTOR_H
DECL|macro|Q_TEMPLATE_EXTERN
DECL|member|operator
DECL|variable|QPoint
DECL|variable|QRegion
