DECL|function|at
DECL|function|begin
DECL|function|clear
DECL|function|data
DECL|function|detach_helper
DECL|function|end
DECL|function|insert
DECL|function|insert
DECL|function|operator
DECL|function|operator
DECL|function|prepend
DECL|function|remove
DECL|function|remove
DECL|function|replace
DECL|function|reserve
DECL|function|resize
DECL|function|sharedNull
DECL|macro|QVECTOR_H
DECL|macro|Q_TEMPLATE_EXTERN
DECL|member|alloc
DECL|member|capacityReserved
DECL|member|offset
DECL|member|operator
DECL|member|ref
DECL|member|shared_null
DECL|member|size
DECL|struct|QVectorData
DECL|struct|QVectorData
DECL|variable|QPoint
DECL|variable|QRegion
