DECL|function|Screenshot
DECL|function|createButton
DECL|function|createButtonsLayout
DECL|function|createOptionsGroupBox
DECL|function|newScreenshot
DECL|function|resizeEvent
DECL|function|saveScreenshot
DECL|function|shootScreen
DECL|function|updateCheckBox
DECL|function|updateScreenshotLabel
