DECL|class|tst_Lancelot
DECL|enumerator|OpenGL
DECL|enumerator|Raster
DECL|enum|GraphicsEngine
DECL|function|cleanupTestCase
DECL|function|initTestCase
DECL|function|main
DECL|function|paint
DECL|function|render
DECL|function|runTestSuite
DECL|function|setupTestSuite
DECL|function|testOpenGL
DECL|function|testOpenGL_data
DECL|function|testRasterARGB32PM
DECL|function|testRasterARGB32PM_data
DECL|function|testRasterRGB16
DECL|function|testRasterRGB16_data
DECL|function|testRasterRGB32
DECL|function|testRasterRGB32_data
DECL|function|tst_Lancelot
DECL|macro|SRCDIR
DECL|macro|main
DECL|macro|main
DECL|member|baseList
DECL|member|dryRunMode
DECL|member|proto
DECL|member|scripts
DECL|member|scriptsDir
DECL|member|simfail
DECL|member|simfail
