DECL|function|QGraphicsBlurEffect
DECL|function|QGraphicsColorizeEffect
DECL|function|QGraphicsDropShadowEffect
DECL|function|QGraphicsEffect
DECL|function|QGraphicsEffect
DECL|function|QGraphicsEffectSource
DECL|function|QGraphicsOpacityEffect
DECL|function|blurHints
DECL|function|blurRadius
DECL|function|blurRadius
DECL|function|boundingRect
DECL|function|boundingRect
DECL|function|boundingRectFor
DECL|function|boundingRectFor
DECL|function|boundingRectFor
DECL|function|color
DECL|function|color
DECL|function|draw
DECL|function|draw
DECL|function|draw
DECL|function|draw
DECL|function|draw
DECL|function|drawSource
DECL|function|graphicsItem
DECL|function|invalidateCache
DECL|function|isEnabled
DECL|function|isPixmap
DECL|function|offset
DECL|function|opacity
DECL|function|opacityMask
DECL|function|pixmap
DECL|function|setBlurHints
DECL|function|setBlurRadius
DECL|function|setBlurRadius
DECL|function|setCachedOffset
DECL|function|setColor
DECL|function|setColor
DECL|function|setEnabled
DECL|function|setOffset
DECL|function|setOpacity
DECL|function|setOpacityMask
DECL|function|setStrength
DECL|function|source
DECL|function|sourceBoundingRect
DECL|function|sourceChanged
DECL|function|sourceIsPixmap
DECL|function|sourcePixmap
DECL|function|strength
DECL|function|styleOption
DECL|function|update
DECL|function|update
DECL|function|updateBoundingRect
DECL|function|widget
DECL|function|~QGraphicsBlurEffect
DECL|function|~QGraphicsColorizeEffect
DECL|function|~QGraphicsDropShadowEffect
DECL|function|~QGraphicsEffect
DECL|function|~QGraphicsEffectSource
DECL|function|~QGraphicsEffectSourcePrivate
DECL|function|~QGraphicsOpacityEffect
