DECL|macro|CS_PUBLIC
DECL|macro|DBNTWIN32
DECL|macro|QSQL_TDS_H
DECL|macro|Q_EXPORT_SQLDRIVER_TDS
DECL|macro|Q_EXPORT_SQLDRIVER_TDS
DECL|macro|WIN32_LEAN_AND_MEAN
DECL|variable|QTDSDriver
DECL|variable|QTDSDriverPrivate
