DECL|class|CommentTestHighlighter
DECL|class|QTestDocumentLayout
DECL|class|StateTestHighlighter
DECL|class|TestHighlighter
DECL|class|tst_QSyntaxHighlighter
DECL|function|CommentTestHighlighter
DECL|function|QTestDocumentLayout
DECL|function|StateTestHighlighter
DECL|function|TestHighlighter
DECL|function|TestHighlighter
DECL|function|avoidUnnecessaryRehighlight
DECL|function|basic
DECL|function|basicTwo
DECL|function|blockBoundingRect
DECL|function|cleanup
DECL|function|documentChanged
DECL|function|documentSize
DECL|function|draw
DECL|function|emptyBlocks
DECL|function|frameBoundingRect
DECL|function|highlightBlock
DECL|function|highlightBlock
DECL|function|highlightBlock
DECL|function|highlightOnInit
DECL|function|highlightToEndOfDocument
DECL|function|highlightToEndOfDocument2
DECL|function|hitTest
DECL|function|init
DECL|function|noContentsChangedDuringHighlight
DECL|function|operator ==
DECL|function|pageCount
DECL|function|preservePreeditArea
DECL|function|rehighlight
DECL|function|rehighlightBlock
DECL|function|removeFormatsOnDelete
DECL|function|reset
DECL|function|reset
DECL|function|setCharFormat
DECL|function|stopHighlightingWhenStateDoesNotChange
DECL|function|task108530
DECL|function|tst_QSyntaxHighlighter
DECL|function|unindent
DECL|member|callCount
DECL|member|cursor
DECL|member|doc
DECL|member|documentChangedCalled
DECL|member|formats
DECL|member|highlighted
DECL|member|highlighted
DECL|member|highlighted
DECL|member|highlightedText
DECL|member|lout
DECL|member|state
