DECL|class|DraftResolution
DECL|class|Error
DECL|function|_findEntry
DECL|function|_findEntryInFile
DECL|function|_fixedLookupChain
DECL|function|findAlias
DECL|function|findChild
DECL|function|findEntry
DECL|function|findTagsInFile
DECL|function|resolve
DECL|member|__init__
DECL|member|__init__
DECL|member|__str__
DECL|member|toInt
DECL|variable|_values
DECL|variable|approved
DECL|variable|contributed
DECL|variable|doc_cache
DECL|variable|parent_locales
DECL|variable|provisional
DECL|variable|unconfirmed
