DECL|enumerator|Adaptor
DECL|enumerator|Proxy
DECL|enum|ClassType
DECL|function|classNameForInterface
DECL|function|cleanInterfaces
DECL|function|constRefArg
DECL|function|cpp
DECL|function|header
DECL|function|main
DECL|function|makeArgNames
DECL|function|methodName
DECL|function|moc
DECL|function|nextArg
DECL|function|nonConstRefArg
DECL|function|openFile
DECL|function|parseCmdLine
DECL|function|propertyGetter
DECL|function|propertySetter
DECL|function|qtTypeName
DECL|function|readInput
DECL|function|showHelp
DECL|function|showVersion
DECL|function|stringify
DECL|function|templateArg
DECL|function|writeAdaptor
DECL|function|writeArgList
DECL|function|writeHeader
DECL|function|writeProxy
DECL|macro|ANNOTATION_NO_WAIT
DECL|macro|PROGRAMCOPYRIGHT
DECL|macro|PROGRAMNAME
DECL|macro|PROGRAMVERSION
DECL|variable|adaptorFile
DECL|variable|commandLine
DECL|variable|forwardDeclarations
DECL|variable|globalClassName
DECL|variable|help
DECL|variable|includeList
DECL|variable|includeMocs
DECL|variable|includes
DECL|variable|inputFile
DECL|variable|parentClassName
DECL|variable|proxyFile
DECL|variable|skipNamespaces
DECL|variable|verbose
DECL|variable|wantedInterfaces
