DECL|class|QGIFFormat
DECL|enumerator|ApplicationExtension
DECL|enumerator|DoNotChange
DECL|enumerator|Done
DECL|enumerator|Error
DECL|enumerator|ExtensionLabel
DECL|enumerator|GlobalColorMap
DECL|enumerator|GraphicControlExtension
DECL|enumerator|Header
DECL|enumerator|ImageDataBlock
DECL|enumerator|ImageDataBlockSize
DECL|enumerator|ImageDescriptor
DECL|enumerator|Introducer
DECL|enumerator|LocalColorMap
DECL|enumerator|LogicalScreenDescriptor
DECL|enumerator|NetscapeExtensionBlock
DECL|enumerator|NetscapeExtensionBlockSize
DECL|enumerator|NoDisposal
DECL|enumerator|RestoreBackground
DECL|enumerator|RestoreImage
DECL|enumerator|SkipBlock
DECL|enumerator|SkipBlockSize
DECL|enumerator|TableImageLZWSize
DECL|enumerator|max_lzw_bits
DECL|enum|Disposal
DECL|enum|State
DECL|function|QGIFFormat
DECL|function|QGifHandler
DECL|function|canRead
DECL|function|canRead
DECL|function|color
DECL|function|currentImageNumber
DECL|function|decode
DECL|function|disposePrevious
DECL|function|fillRect
DECL|function|imageCount
DECL|function|imageIsComing
DECL|function|loopCount
DECL|function|name
DECL|function|nextImageDelay
DECL|function|nextY
DECL|function|option
DECL|function|read
DECL|function|scan
DECL|function|setOption
DECL|function|supportsOption
DECL|function|write
DECL|function|~QGIFFormat
DECL|function|~QGifHandler
DECL|macro|FAST_SCAN_LINE
DECL|macro|LM
DECL|macro|Q_TRANSPARENT
DECL|member|accum
DECL|member|backingstore
DECL|member|bgcol
DECL|member|bitcount
DECL|member|bottom
DECL|member|ccount
DECL|member|clear_code
DECL|member|code_size
DECL|member|count
DECL|member|digress
DECL|member|disposal
DECL|member|disposed
DECL|member|end_code
DECL|member|expectcount
DECL|member|firstcode
DECL|member|frame
DECL|member|gcmap
DECL|member|gif89
DECL|member|globalcmap
DECL|member|gncols
DECL|member|height
DECL|member|hold
DECL|member|incode
DECL|member|interlace
DECL|member|lcmap
DECL|member|left
DECL|member|lncols
DECL|member|localcmap
DECL|member|lzwsize
DECL|member|max_code
DECL|member|max_code_size
DECL|member|ncols
DECL|member|needfirst
DECL|member|newFrame
DECL|member|oldcode
DECL|member|out_of_bounds
DECL|member|partialNewFrame
DECL|member|right
DECL|member|sheight
DECL|member|sp
DECL|member|stack
DECL|member|state
DECL|member|swidth
DECL|member|table
DECL|member|top
DECL|member|trans_index
DECL|member|width
DECL|member|x
DECL|member|y
