DECL|enumerator|Fixed
DECL|enumerator|Scalable
DECL|enumerator|Threshold
DECL|enum|Type
DECL|function|QIconDirInfo
DECL|macro|QICONLOADER_P_H
DECL|member|Q_DECL_OVERRIDE
DECL|member|Q_DECL_OVERRIDE
DECL|member|basePixmap
DECL|member|entries
DECL|member|iconName
DECL|member|maxSize
DECL|member|minSize
DECL|member|path
DECL|member|size
DECL|member|svgIcon
DECL|member|threshold
DECL|member|type
DECL|struct|QIconDirInfo
DECL|struct|QIconLoaderEngineEntry
DECL|struct|QIconLoaderEngineEntry
DECL|struct|QThemeIconInfo
DECL|typedef|QThemeIconEntries
DECL|variable|QIconCacheGtkReader
DECL|variable|QIconLoader
