DECL|enumerator|Fixed
DECL|enumerator|Scalable
DECL|enumerator|Threshold
DECL|enum|Type
DECL|function|QIconDirInfo
DECL|macro|QDESKTOPICON_P_H
DECL|member|basePixmap
DECL|member|maxSize
DECL|member|minSize
DECL|member|path
DECL|member|size
DECL|member|svgIcon
DECL|member|threshold
DECL|member|type
DECL|struct|QIconDirInfo
DECL|struct|QIconLoaderEngineEntry
DECL|struct|QIconLoaderEngineEntry
DECL|typedef|QThemeIconEntries
DECL|variable|QIconLoader
