DECL|function|actualSize
DECL|function|addFile
DECL|function|addPixmap
DECL|function|availableSizes
DECL|function|iconName
DECL|function|isNull
DECL|function|key
DECL|function|pixmap
DECL|function|read
DECL|function|virtual_hook
DECL|function|write
DECL|function|~QIconEngine
