DECL|class|QIconCacheGtkReader
DECL|function|QIconCacheGtkReader
DECL|function|QIconLoader
DECL|function|QIconLoaderEngine
DECL|function|QIconLoaderEngine
DECL|function|QIconTheme
DECL|function|actualSize
DECL|function|clone
DECL|function|directoryMatchesSize
DECL|function|directorySizeDistance
DECL|function|ensureInitialized
DECL|function|ensureLoaded
DECL|function|entryForSize
DECL|function|fallbackTheme
DECL|function|findIconHelper
DECL|function|hasIcon
DECL|function|icon_name_hash
DECL|function|instance
DECL|function|isValid
DECL|function|key
DECL|function|loadIcon
DECL|function|lookup
DECL|function|paint
DECL|function|pixmap
DECL|function|pixmap
DECL|function|pixmap
DECL|function|read
DECL|function|read16
DECL|function|read32
DECL|function|setThemeName
DECL|function|setThemeSearchPath
DECL|function|systemIconSearchPaths
DECL|function|systemThemeName
DECL|function|themeSearchPaths
DECL|function|updateSystemTheme
DECL|function|virtual_hook
DECL|function|write
DECL|function|~QIconLoaderEngine
DECL|member|m_data
DECL|member|m_file
DECL|member|m_isValid
DECL|member|m_size
