DECL|class|QImageIOHandlerPrivate
DECL|function|QImageIOHandler
DECL|function|QImageIOHandler
DECL|function|QImageIOHandlerPrivate
DECL|function|QImageIOPlugin
DECL|function|currentImageNumber
DECL|function|currentImageRect
DECL|function|device
DECL|function|format
DECL|function|imageCount
DECL|function|jumpToImage
DECL|function|jumpToNextImage
DECL|function|loopCount
DECL|function|name
DECL|function|nextImageDelay
DECL|function|option
DECL|function|setDevice
DECL|function|setFormat
DECL|function|setFormat
DECL|function|setOption
DECL|function|supportsOption
DECL|function|write
DECL|function|~QImageIOHandler
DECL|function|~QImageIOHandlerPrivate
DECL|function|~QImageIOPlugin
DECL|member|device
DECL|member|format
DECL|member|q_ptr
