DECL|class|QMngHandlerPrivate
DECL|function|QMngHandler
DECL|function|QMngHandlerPrivate
DECL|function|backgroundColor
DECL|function|canRead
DECL|function|canRead
DECL|function|currentImageNumber
DECL|function|currentImageNumber
DECL|function|getNextImage
DECL|function|imageCount
DECL|function|imageCount
DECL|function|jumpToImage
DECL|function|jumpToImage
DECL|function|jumpToNextImage
DECL|function|jumpToNextImage
DECL|function|loopCount
DECL|function|myalloc
DECL|function|myclosestream
DECL|function|myerror
DECL|function|myfree
DECL|function|mygetcanvasline
DECL|function|mygettickcount
DECL|function|myopenstream
DECL|function|myprocessheader
DECL|function|myprocessterm
DECL|function|myreaddata
DECL|function|myrefresh
DECL|function|mysettimer
DECL|function|mytrace
DECL|function|mywritedata
DECL|function|name
DECL|function|nextImageDelay
DECL|function|nextImageDelay
DECL|function|option
DECL|function|processHeader
DECL|function|read
DECL|function|readData
DECL|function|setBackgroundColor
DECL|function|setOption
DECL|function|supportsOption
DECL|function|write
DECL|function|writeData
DECL|function|writeImage
DECL|function|~QMngHandler
DECL|function|~QMngHandlerPrivate
DECL|macro|MNG_USE_SO
DECL|member|elapsed
DECL|member|frameCount
DECL|member|frameIndex
DECL|member|hMNG
DECL|member|haveReadAll
DECL|member|haveReadNone
DECL|member|iStyle
DECL|member|image
DECL|member|iterCount
DECL|member|nextDelay
DECL|member|nextIndex
DECL|member|q_ptr
