DECL|class|QFrameInfo
DECL|class|QMoviePrivate
DECL|function|QFrameInfo
DECL|function|QFrameInfo
DECL|function|QFrameInfo
DECL|function|QMovie
DECL|function|QMovie
DECL|function|QMovie
DECL|function|QMoviePrivate
DECL|function|_q_loadNextFrame
DECL|function|_q_loadNextFrame
DECL|function|backgroundColor
DECL|function|cacheMode
DECL|function|currentFrameNumber
DECL|function|currentImage
DECL|function|currentPixmap
DECL|function|device
DECL|function|endMarker
DECL|function|enterState
DECL|function|fileName
DECL|function|format
DECL|function|frameCount
DECL|function|frameCount
DECL|function|frameRect
DECL|function|infoForFrame
DECL|function|isDone
DECL|function|isEndMarker
DECL|function|isValid
DECL|function|isValid
DECL|function|isValid
DECL|function|jumpToFrame
DECL|function|jumpToFrame
DECL|function|jumpToNextFrame
DECL|function|jumpToNextFrame
DECL|function|loopCount
DECL|function|next
DECL|function|nextFrameDelay
DECL|function|reset
DECL|function|scaledSize
DECL|function|setBackgroundColor
DECL|function|setCacheMode
DECL|function|setDevice
DECL|function|setFileName
DECL|function|setFormat
DECL|function|setPaused
DECL|function|setScaledSize
DECL|function|setSpeed
DECL|function|speed
DECL|function|speedAdjustedDelay
DECL|function|start
DECL|function|state
DECL|function|stop
DECL|function|supportedFormats
DECL|function|~QMovie
DECL|macro|QMOVIE_INVALID_DELAY
DECL|member|absoluteFilePath
DECL|member|cacheMode
DECL|member|currentFrameNumber
DECL|member|currentPixmap
DECL|member|delay
DECL|member|endMark
DECL|member|frameMap
DECL|member|frameRect
DECL|member|greatestFrameNumber
DECL|member|haveReadAll
DECL|member|initialDevicePos
DECL|member|isFirstIteration
DECL|member|movieState
DECL|member|nextDelay
DECL|member|nextFrameNumber
DECL|member|nextImageTimer
DECL|member|pixmap
DECL|member|playCounter
DECL|member|reader
DECL|member|speed
