DECL|class|QFakeDevice
DECL|class|QPictureHandler
DECL|enumerator|TranslateIn
DECL|enumerator|TranslateInOut
DECL|enumerator|Untranslated
DECL|enum|TMode
DECL|function|QFakeDevice
DECL|function|QPicture
DECL|function|QPicture
DECL|function|QPicture
DECL|function|QPictureHandler
DECL|function|QPictureIO
DECL|function|QPictureIO
DECL|function|QPictureIO
DECL|function|QPicturePrivate
DECL|function|QPicturePrivate
DECL|function|boundingRect
DECL|function|checkFormat
DECL|function|cleanup
DECL|function|data
DECL|function|defineIOHandler
DECL|function|description
DECL|function|detach
DECL|function|detach_helper
DECL|function|devType
DECL|function|exec
DECL|function|fileName
DECL|function|format
DECL|function|gamma
DECL|function|get_picture_handler
DECL|function|init
DECL|function|inputFormatList
DECL|function|inputFormats
DECL|function|inputFormats
DECL|function|ioDevice
DECL|function|isDetached
DECL|function|isNull
DECL|function|load
DECL|function|load
DECL|function|metric
DECL|function|metric
DECL|function|operator <<
DECL|function|operator =
DECL|function|operator >>
DECL|function|outputFormatList
DECL|function|outputFormats
DECL|function|outputFormats
DECL|function|paintEngine
DECL|function|paintEngine
DECL|function|parameters
DECL|function|picture
DECL|function|pictureFormat
DECL|function|pictureFormat
DECL|function|pictureFormat
DECL|function|play
DECL|function|qToStringList
DECL|function|qt_init_picture_handlers
DECL|function|qt_init_picture_plugins
DECL|function|quality
DECL|function|read
DECL|function|resetFormat
DECL|function|save
DECL|function|save
DECL|function|setBoundingRect
DECL|function|setData
DECL|function|setDescription
DECL|function|setDpiX
DECL|function|setDpiY
DECL|function|setFileName
DECL|function|setFormat
DECL|function|setGamma
DECL|function|setIODevice
DECL|function|setParameters
DECL|function|setPicture
DECL|function|setQuality
DECL|function|setStatus
DECL|function|size
DECL|function|status
DECL|function|write
DECL|function|~QPicture
DECL|function|~QPictureIO
DECL|member|descr
DECL|member|dpi_x
DECL|member|dpi_y
DECL|member|fname
DECL|member|format
DECL|member|frmt
DECL|member|gamma
DECL|member|header
DECL|member|iodev
DECL|member|iostat
DECL|member|obsolete
DECL|member|parameters
DECL|member|pi
DECL|member|quality
DECL|member|read_picture
DECL|member|text_mode
DECL|member|write_picture
DECL|struct|QPictureIOData
DECL|typedef|QPHList
DECL|variable|mfhdr_maj
DECL|variable|mfhdr_min
DECL|variable|qt_mfhdr_tag
