DECL|function|QPixmap
DECL|function|QPixmap
DECL|function|QPixmap
DECL|function|QPixmap
DECL|function|QPixmap
DECL|function|QPixmap
DECL|function|QPixmap
DECL|function|QPixmap
DECL|function|cacheKey
DECL|function|convertFromImage
DECL|function|copy
DECL|function|createHeuristicMask
DECL|function|createMaskFromColor
DECL|function|defaultDepth
DECL|function|depth
DECL|function|detach
DECL|function|devType
DECL|function|devicePixelRatio
DECL|function|doImageIO
DECL|function|doInit
DECL|function|fill
DECL|function|fill
DECL|function|fromImage
DECL|function|fromImageReader
DECL|function|grabWidget
DECL|function|grabWindow
DECL|function|handle
DECL|function|hasAlpha
DECL|function|hasAlphaChannel
DECL|function|height
DECL|function|isDetached
DECL|function|isNull
DECL|function|isQBitmap
DECL|function|load
DECL|function|loadFromData
DECL|function|mask
DECL|function|metric
DECL|function|operator <<
DECL|function|operator <<
DECL|function|operator =
DECL|function|operator >>
DECL|function|operator QVariant
DECL|function|paintEngine
DECL|function|qt_pixmap_thread_test
DECL|function|rect
DECL|function|save
DECL|function|save
DECL|function|scaled
DECL|function|scaledToHeight
DECL|function|scaledToWidth
DECL|function|scroll
DECL|function|setDevicePixelRatio
DECL|function|setMask
DECL|function|size
DECL|function|toImage
DECL|function|transformed
DECL|function|transformed
DECL|function|trueMatrix
DECL|function|trueMatrix
DECL|function|width
DECL|function|~QPixmap
