DECL|function|QRasterPixmapData
DECL|function|buffer
DECL|function|copy
DECL|function|createCompatiblePixmapData
DECL|function|createPixmapForImage
DECL|function|fill
DECL|function|fromData
DECL|function|fromImage
DECL|function|fromImageReader
DECL|function|hasAlphaChannel
DECL|function|metric
DECL|function|paintEngine
DECL|function|qt_toRasterPixmap
DECL|function|qt_toRasterPixmap
DECL|function|resize
DECL|function|scroll
DECL|function|setAlphaChannel
DECL|function|setMask
DECL|function|toImage
DECL|function|toImage
DECL|function|~QRasterPixmapData
DECL|variable|qt_pixmap_bit_mask
