DECL|function|Q_DECLARE_SHARED
DECL|function|alphaChannel
DECL|function|loadFromData
DECL|function|scroll
DECL|function|setAlphaChannel
DECL|macro|QPIXMAP_H
DECL|variable|QColor
DECL|variable|QImageReader
DECL|variable|QPlatformPixmap
DECL|variable|QVariant
DECL|variable|QX11Info
