DECL|function|QBlittablePlatformPixmap
DECL|function|blittable
DECL|function|buffer
DECL|function|clipAndTransformRect
DECL|function|devicePixelRatio
DECL|function|fill
DECL|function|fromImage
DECL|function|hasAlphaChannel
DECL|function|markRasterOverlayImpl
DECL|function|mergeOverlay
DECL|function|metric
DECL|function|overlay
DECL|function|paintEngine
DECL|function|resize
DECL|function|setBlittable
DECL|function|setDevicePixelRatio
DECL|function|toImage
DECL|function|unmarkRasterOverlayImpl
DECL|function|unmergeOverlay
DECL|function|~QBlittablePlatformPixmap
DECL|variable|global_ser_no
DECL|variable|showRasterOverlay
