DECL|function|QPlatformPixmap
DECL|function|buffer
DECL|function|copy
DECL|function|create
DECL|function|createCompatiblePlatformPixmap
DECL|function|fromData
DECL|function|fromFile
DECL|function|fromImageReader
DECL|function|makeBitmapCompliantIfNeeded
DECL|function|scroll
DECL|function|setDetachNumber
DECL|function|setSerialNumber
DECL|function|toImage
DECL|function|transformed
DECL|function|~QPlatformPixmap
