DECL|function|QTiffHandler
DECL|function|canRead
DECL|function|canRead
DECL|function|checkGrayscale
DECL|function|convert32BitOrder
DECL|function|convert32BitOrderBigEndian
DECL|function|name
DECL|function|option
DECL|function|qtiffCloseProc
DECL|function|qtiffMapProc
DECL|function|qtiffReadProc
DECL|function|qtiffSeekProc
DECL|function|qtiffSizeProc
DECL|function|qtiffUnmapProc
DECL|function|qtiffWriteProc
DECL|function|read
DECL|function|rotate_right_mirror_horizontal
DECL|function|rotate_right_mirror_vertical
DECL|function|setOption
DECL|function|supportsOption
DECL|function|write
