DECL|function|QVolatileImageData
DECL|function|QVolatileImageData
DECL|function|QVolatileImageData
DECL|function|QVolatileImageData
DECL|function|QVolatileImageData
DECL|function|applyMask
DECL|function|beginDataAccess
DECL|function|bitmapNeedsCopy
DECL|function|cleanup
DECL|function|convertData
DECL|function|copyData
DECL|function|createBitmap
DECL|function|duplicateBitmap
DECL|function|duplicateNativeImage
DECL|function|endDataAccess
DECL|function|ensureBitmap
DECL|function|ensureCleanup
DECL|function|ensureFormat
DECL|function|ensureImage
DECL|function|format2TDisplayMode
DECL|function|imageToBitmap
DECL|function|initWithBitmap
DECL|function|rasterizeBitmap
DECL|function|registerImageData
DECL|function|release
DECL|function|unregisterImageData
DECL|function|updateImage
DECL|function|~QVolatileImageData
DECL|variable|cleanup_function_registered
DECL|variable|firstImageData
