DECL|function|QXpmHandler
DECL|function|canRead
DECL|function|canRead
DECL|function|fbname
DECL|function|is_xpm_color_spec_prefix
DECL|function|name
DECL|function|operator <
DECL|function|operator <
DECL|function|option
DECL|function|qt_get_named_xpm_rgb
DECL|function|qt_read_xpm_image_or_array
DECL|function|read
DECL|function|readHeader
DECL|function|readImage
DECL|function|read_xpm_body
DECL|function|read_xpm_header
DECL|function|read_xpm_string
DECL|function|setOption
DECL|function|supportsOption
DECL|function|write
DECL|function|write_xpm_image
DECL|function|xpmHash
DECL|function|xpmHash
DECL|function|xpm_color_name
DECL|macro|QRGB
DECL|macro|QRGB
DECL|member|name
DECL|member|value
DECL|struct|XPMRGBData
DECL|variable|xpmRgbTbl
DECL|variable|xpmRgbTblSize
