DECL|function|QAbstractItemDelegate
DECL|function|QAbstractItemDelegate
DECL|function|createEditor
DECL|function|destroyEditor
DECL|function|editorEvent
DECL|function|elidedText
DECL|function|helpEvent
DECL|function|setEditorData
DECL|function|setModelData
DECL|function|updateEditorGeometry
DECL|function|~QAbstractItemDelegate
