DECL|function|QEditorInfo
DECL|function|QEditorInfo
DECL|macro|QABSTRACTITEMVIEW_P_H
DECL|member|index
DECL|member|isStatic
DECL|member|rect
DECL|member|widget
DECL|struct|QEditorInfo
DECL|struct|QItemViewPaintPair
DECL|typedef|QEditorIndexHash
DECL|typedef|QIndexEditorHash
DECL|typedef|QItemViewPaintPairs
DECL|typedef|QPersistentModelIndex
DECL|typedef|QWidget
DECL|variable|QItemViewPaintPair
DECL|variable|QRect
