DECL|class|QFileIconProviderPrivate
DECL|function|QFileIconProvider
DECL|function|QFileIconProviderPrivate
DECL|function|getIcon
DECL|function|getIcon
DECL|function|icon
DECL|function|icon
DECL|function|type
DECL|function|~QFileIconProvider
DECL|macro|_WIN32_IE
DECL|macro|_WIN32_IE
DECL|member|cdrom
DECL|member|computer
DECL|member|desktop
DECL|member|directory
DECL|member|directoryLink
DECL|member|file
DECL|member|fileLink
DECL|member|floppy
DECL|member|generic
DECL|member|harddisk
DECL|member|home
DECL|member|homePath
DECL|member|network
DECL|member|q_ptr
DECL|member|ram
DECL|member|trashcan
