DECL|class|QFileIconEngine
DECL|function|QFileIconEngine
DECL|function|QFileIconProvider
DECL|function|QFileIconProviderPrivate
DECL|function|getIcon
DECL|function|getIcon
DECL|function|icon
DECL|function|icon
DECL|function|isCacheable
DECL|function|options
DECL|function|setOptions
DECL|function|type
DECL|function|~QFileIconProvider
DECL|member|m_fileInfo
DECL|member|m_fipOpts
