DECL|function|QHeaderView
DECL|function|QHeaderView
DECL|function|_q_layoutAboutToBeChanged
DECL|function|_q_layoutChanged
DECL|function|_q_sectionsRemoved
DECL|function|adjustedVisualIndex
DECL|function|cascadingResize
DECL|function|cascadingSectionResizes
DECL|function|clear
DECL|function|count
DECL|function|createSectionSpan
DECL|function|currentChanged
DECL|function|dataChanged
DECL|function|defaultAlignment
DECL|function|defaultSectionSize
DECL|function|doItemsLayout
DECL|function|event
DECL|function|flipSortIndicator
DECL|function|headerDataChanged
DECL|function|headerSectionPosition
DECL|function|headerSectionResizeMode
DECL|function|headerSectionSize
DECL|function|headerVisualIndexAt
DECL|function|hiddenSectionCount
DECL|function|highlightSections
DECL|function|horizontalOffset
DECL|function|indexAt
DECL|function|initStyleOption
DECL|function|initialize
DECL|function|initializeSections
DECL|function|initializeSections
DECL|function|isClickable
DECL|function|isIndexHidden
DECL|function|isMovable
DECL|function|isSectionHidden
DECL|function|isSectionSelected
DECL|function|isSortIndicatorShown
DECL|function|lastVisibleVisualIndex
DECL|function|length
DECL|function|logicalIndex
DECL|function|logicalIndexAt
DECL|function|minimumSectionSize
DECL|function|mouseDoubleClickEvent
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|moveCursor
DECL|function|moveSection
DECL|function|offset
DECL|function|operator <<
DECL|function|operator >>
DECL|function|orientation
DECL|function|paintEvent
DECL|function|paintSection
DECL|function|read
DECL|function|recalcSectionStartPos
DECL|function|removeSectionsFromSpans
DECL|function|reset
DECL|function|resizeMode
DECL|function|resizeSection
DECL|function|resizeSectionSpan
DECL|function|resizeSections
DECL|function|resizeSections
DECL|function|resizeSections
DECL|function|restoreState
DECL|function|rowsInserted
DECL|function|saveState
DECL|function|scrollContentsBy
DECL|function|scrollTo
DECL|function|sectionHandleAt
DECL|function|sectionPosition
DECL|function|sectionSize
DECL|function|sectionSizeFromContents
DECL|function|sectionSizeHint
DECL|function|sectionViewportPosition
DECL|function|sectionsAboutToBeRemoved
DECL|function|sectionsHidden
DECL|function|sectionsInserted
DECL|function|sectionsMoved
DECL|function|setCascadingSectionResizes
DECL|function|setClickable
DECL|function|setDefaultAlignment
DECL|function|setDefaultSectionSize
DECL|function|setDefaultSectionSize
DECL|function|setGlobalHeaderResizeMode
DECL|function|setHeaderSectionResizeMode
DECL|function|setHighlightSections
DECL|function|setMinimumSectionSize
DECL|function|setModel
DECL|function|setMovable
DECL|function|setOffset
DECL|function|setOffsetToLastSection
DECL|function|setOffsetToSectionPosition
DECL|function|setResizeMode
DECL|function|setResizeMode
DECL|function|setSectionHidden
DECL|function|setSelection
DECL|function|setSortIndicator
DECL|function|setSortIndicatorShown
DECL|function|setStretchLastSection
DECL|function|setupSectionIndicator
DECL|function|sizeHint
DECL|function|sortIndicatorOrder
DECL|function|sortIndicatorSection
DECL|function|stretchLastSection
DECL|function|stretchSectionCount
DECL|function|swapSections
DECL|function|updateGeometries
DECL|function|updateHiddenSections
DECL|function|updateSection
DECL|function|updateSectionIndicator
DECL|function|verticalOffset
DECL|function|viewSectionSizeHint
DECL|function|viewportEvent
DECL|function|visualIndex
DECL|function|visualIndexAt
DECL|function|visualRect
DECL|function|visualRegionForSelection
DECL|function|write
DECL|function|~QHeaderView
