DECL|class|QItemDelegatePrivate
DECL|function|QItemDelegate
DECL|function|QItemDelegatePrivate
DECL|function|_q_commitDataAndCloseEditor
DECL|function|createEditor
DECL|function|decoration
DECL|function|doCheck
DECL|function|doLayout
DECL|function|doTextLayout
DECL|function|drawBackground
DECL|function|drawCheck
DECL|function|drawDecoration
DECL|function|drawDisplay
DECL|function|drawFocus
DECL|function|editorEvent
DECL|function|editorFactory
DECL|function|eventFilter
DECL|function|hasClipping
DECL|function|iconMode
DECL|function|iconState
DECL|function|itemEditorFactory
DECL|function|paint
DECL|function|qPixmapSerial
DECL|function|rect
DECL|function|replaceNewLine
DECL|function|selected
DECL|function|setClipping
DECL|function|setEditorData
DECL|function|setItemEditorFactory
DECL|function|setModelData
DECL|function|setOptions
DECL|function|sizeHint
DECL|function|textLayoutBounds
DECL|function|textRectangle
DECL|function|tryFixup
DECL|function|updateEditorGeometry
DECL|function|valueToText
DECL|function|widget
DECL|function|~QItemDelegate
DECL|macro|DBL_DIG
DECL|member|clipPainting
DECL|member|f
DECL|member|icon
DECL|member|mode
DECL|member|state
DECL|member|textLayout
DECL|member|textOption
DECL|member|tmp
DECL|struct|Icon
