DECL|class|QStyledItemDelegatePrivate
DECL|function|QStyledItemDelegate
DECL|function|QStyledItemDelegatePrivate
DECL|function|_q_commitDataAndCloseEditor
DECL|function|createEditor
DECL|function|displayText
DECL|function|editorEvent
DECL|function|editorFactory
DECL|function|eventFilter
DECL|function|initStyleOption
DECL|function|itemEditorFactory
DECL|function|paint
DECL|function|setEditorData
DECL|function|setItemEditorFactory
DECL|function|setModelData
DECL|function|sizeHint
DECL|function|tryFixup
DECL|function|updateEditorGeometry
DECL|function|widget
DECL|function|~QStyledItemDelegate
DECL|member|factory
