DECL|function|column
DECL|function|isSelected
DECL|function|itemAt
DECL|function|removeCellWidget
DECL|function|row
DECL|function|setFont
DECL|function|setIcon
DECL|function|setSelected
DECL|function|setStatusTip
DECL|function|setText
DECL|function|setToolTip
DECL|function|setWhatsThis
DECL|macro|QTABLEWIDGET_H
DECL|variable|QTableModel
DECL|variable|QTableWidget
DECL|variable|QTableWidgetItemPrivate
DECL|variable|QTableWidgetPrivate
DECL|variable|QWidgetItemData
