DECL|class|BlockableWindow
DECL|class|DummyWindow
DECL|class|FocusChangeWindow
DECL|class|ShowCloseShowWindow
DECL|class|TestEventReceiver
DECL|class|TestPlugin
DECL|class|TestPluginFactory
DECL|class|tst_QGuiApplication
DECL|enumerator|spacing
DECL|enumerator|windowSize
DECL|function|BlockableWindow
DECL|function|DummyWindow
DECL|function|FocusChangeWindow
DECL|function|ShowCloseShowWindow
DECL|function|TestEventReceiver
DECL|function|TestPlugin
DECL|function|abortQuitOnShow
DECL|function|allWindows
DECL|function|changeFocusWindow
DECL|function|create
DECL|function|customEvent
DECL|function|displayName
DECL|function|doClose
DECL|function|event
DECL|function|event
DECL|function|exitApp
DECL|function|focusObject
DECL|function|focusObject
DECL|function|focusOutEvent
DECL|function|genericPluginsAndWindowSystemEvents
DECL|function|keyboardModifiers
DECL|function|modalWindow
DECL|function|quitOnLastWindowClosed
DECL|function|resetCounts
DECL|function|setFocusObject
DECL|function|topLevelWindows
DECL|member|blocked
DECL|member|customEvents
DECL|member|enters
DECL|member|leaves
DECL|member|m_focusObject
DECL|member|showAgain
DECL|member|windowDuringFocusAboutToChange
DECL|member|windowDuringFocusOut
DECL|variable|testOrientationToSend
