DECL|function|QSqlTableModel
DECL|function|QSqlTableModel
DECL|function|clear
DECL|function|clear
DECL|function|clearCache
DECL|function|data
DECL|function|database
DECL|function|deleteRowFromTable
DECL|function|editStrategy
DECL|function|exec
DECL|function|fieldIndex
DECL|function|filter
DECL|function|flags
DECL|function|headerData
DECL|function|indexInQuery
DECL|function|initRecordAndPrimaryIndex
DECL|function|insertCount
DECL|function|insertRecord
DECL|function|insertRowIntoTable
DECL|function|insertRows
DECL|function|isDirty
DECL|function|isDirty
DECL|function|nameToIndex
DECL|function|orderByClause
DECL|function|primaryKey
DECL|function|primaryValues
DECL|function|record
DECL|function|record
DECL|function|record
DECL|function|removeColumns
DECL|function|removeRows
DECL|function|revert
DECL|function|revertAll
DECL|function|revertCachedRow
DECL|function|revertRow
DECL|function|rowCount
DECL|function|select
DECL|function|selectRow
DECL|function|selectStatement
DECL|function|setData
DECL|function|setEditStrategy
DECL|function|setFilter
DECL|function|setPrimaryKey
DECL|function|setQuery
DECL|function|setRecord
DECL|function|setSort
DECL|function|setTable
DECL|function|sort
DECL|function|strippedFieldName
DECL|function|submit
DECL|function|submitAll
DECL|function|tableName
DECL|function|updateRowInTable
DECL|function|~QSqlTableModel
DECL|typedef|Sql
