DECL|function|QSqlQueryModel
DECL|function|QSqlQueryModel
DECL|function|canFetchMore
DECL|function|clear
DECL|function|columnCount
DECL|function|data
DECL|function|fetchMore
DECL|function|headerData
DECL|function|indexInQuery
DECL|function|initColOffsets
DECL|function|insertColumns
DECL|function|lastError
DECL|function|prefetch
DECL|function|query
DECL|function|queryChange
DECL|function|record
DECL|function|record
DECL|function|removeColumns
DECL|function|rowCount
DECL|function|setHeaderData
DECL|function|setLastError
DECL|function|setQuery
DECL|function|setQuery
DECL|function|~QSqlQueryModel
DECL|function|~QSqlQueryModelPrivate
DECL|macro|QSQL_PREFETCH
