DECL|function|Framework
DECL|function|Framework
DECL|function|basePath
DECL|function|isTestBlacklisted
DECL|function|isValid
DECL|function|load
DECL|function|outputDir
DECL|function|settings
DECL|function|suites
DECL|function|~Framework
