DECL|enumerator|Default
DECL|enumerator|Foreign
DECL|enumerator|Normal
DECL|enumerator|Reference
DECL|enum|GeneratorFlag
DECL|function|XMLData
DECL|function|XMLData
DECL|function|XMLData
DECL|function|XMLEngine
DECL|function|XMLEngine
DECL|function|XMLFile
DECL|function|XMLFile
DECL|function|XMLFile
DECL|function|XMLSuite
DECL|function|XMLSuite
DECL|macro|XMLDATA_H
DECL|member|QString
DECL|member|QString
DECL|member|data
DECL|member|date
DECL|member|defaultEngine
DECL|member|details
DECL|member|files
DECL|member|foreignEngine
DECL|member|generationDate
DECL|member|iterations
DECL|member|maxElapsed
DECL|member|minElapsed
DECL|member|name
DECL|member|name
DECL|member|name
DECL|member|output
DECL|member|referenceEngine
DECL|member|suites
DECL|member|timeToRender
DECL|struct|XMLData
DECL|struct|XMLEngine
DECL|struct|XMLFile
DECL|struct|XMLSuite
