DECL|function|DataTransferer
DECL|function|DataTransfererQHttp
DECL|function|DataTransfererQNam
DECL|function|DataTransfererQTcp
DECL|function|connected
DECL|function|dataTransferOngoing
DECL|function|done
DECL|function|error
DECL|function|readyRead
DECL|function|replyFinished
DECL|function|transferData
DECL|function|transferData
DECL|function|transferData
DECL|function|~DataTransfererQHttp
DECL|function|~DataTransfererQNam
DECL|function|~DataTransfererQTcp
