DECL|enumerator|OutputConfigCurrent
DECL|enumerator|OutputConfigMode
DECL|enumerator|OutputConfigModeline
DECL|enumerator|OutputConfigOff
DECL|enumerator|OutputConfigPreferred
DECL|enum|OutputConfiguration
DECL|function|QEglFSKmsDevice
DECL|function|connectorProperty
DECL|function|createScreen
DECL|function|createScreens
DECL|function|crtcForConnector
DECL|function|devicePath
DECL|function|fd
DECL|function|nameForConnector
DECL|function|parseModeline
DECL|function|screenForConnector
DECL|function|setFd
DECL|function|~QEglFSKmsDevice
DECL|macro|ARRAY_LENGTH
DECL|variable|connector_type_names
