DECL|function|QEglFSKmsIntegration
DECL|function|device
DECL|function|hasCapability
DECL|function|hwCursor
DECL|function|loadConfig
DECL|function|outputSettings
DECL|function|platformDestroy
DECL|function|platformDisplay
DECL|function|platformInit
DECL|function|screenInit
DECL|function|separateScreens
DECL|function|supportsPBuffers
DECL|function|surfaceFormatFor
DECL|function|usesDefaultScreen
DECL|function|waitForVSync
