DECL|class|tst_QStorageInfo
DECL|function|caching
DECL|function|currentStorage
DECL|function|defaultValues
DECL|function|operatorEqual
DECL|function|operatorNotEqual
DECL|function|root
DECL|function|storageList
DECL|function|tempFile
