DECL|class|ViewsToTest
DECL|enumerator|DisplayNone
DECL|enumerator|DisplayRoot
DECL|enum|Display
DECL|function|ViewsToTest
DECL|function|createView
DECL|function|hideIndexes
DECL|function|test
DECL|member|display
DECL|member|tests
DECL|member|viewType
DECL|struct|test
