DECL|function|QCupsJobWidget
DECL|function|endBannerPage
DECL|function|initBannerPages
DECL|function|initJobBilling
DECL|function|initJobHold
DECL|function|initJobPriority
DECL|function|jobBilling
DECL|function|jobHold
DECL|function|jobHoldTime
DECL|function|jobPriority
DECL|function|setEndBannerPage
DECL|function|setJobBilling
DECL|function|setJobHold
DECL|function|setJobPriority
DECL|function|setPrinter
DECL|function|setStartBannerPage
DECL|function|setupPrinter
DECL|function|startBannerPage
DECL|function|toggleJobHoldTime
DECL|function|~QCupsJobWidget
