DECL|macro|FFD_ATOMIC_ACQUIRE
DECL|macro|FFD_ATOMIC_INIT
DECL|macro|FFD_ATOMIC_RELAXED
DECL|macro|FFD_ATOMIC_RELEASE
DECL|macro|FFD_CONCAT
DECL|macro|FORKFD_NO_FORKFD
DECL|macro|FORKFD_NO_SPAWNFD
DECL|macro|NDEBUG
DECL|macro|ffd_atomic_add_fetch
DECL|macro|ffd_atomic_compare_exchange
DECL|macro|ffd_atomic_exchange
DECL|macro|ffd_atomic_load
DECL|macro|ffd_atomic_pointer
DECL|macro|ffd_atomic_store
DECL|macro|loadRelaxed
DECL|macro|storeRelaxed
DECL|typedef|ffd_atomic_int
