DECL|class|QAbstractFileEngineHandlerList
DECL|class|QAbstractFileEngineIteratorPrivate
DECL|function|QAbstractFileEngine
DECL|function|QAbstractFileEngine
DECL|function|QAbstractFileEngineHandler
DECL|function|QAbstractFileEngineIterator
DECL|function|atEnd
DECL|function|beginEntryList
DECL|function|caseSensitive
DECL|function|close
DECL|function|copy
DECL|function|create
DECL|function|currentFileInfo
DECL|function|currentFilePath
DECL|function|endEntryList
DECL|function|entryInfo
DECL|function|entryList
DECL|function|error
DECL|function|errorString
DECL|function|extension
DECL|function|fileFlags
DECL|function|fileName
DECL|function|fileTime
DECL|function|filters
DECL|function|flush
DECL|function|handle
DECL|function|isRelativePath
DECL|function|isSequential
DECL|function|link
DECL|function|map
DECL|function|mkdir
DECL|function|nameFilters
DECL|function|open
DECL|function|owner
DECL|function|ownerId
DECL|function|path
DECL|function|pos
DECL|function|qt_custom_file_engine_handler_create
DECL|function|read
DECL|function|readLine
DECL|function|remove
DECL|function|rename
DECL|function|renameOverwrite
DECL|function|rmdir
DECL|function|seek
DECL|function|setError
DECL|function|setFileName
DECL|function|setPath
DECL|function|setPermissions
DECL|function|setSize
DECL|function|size
DECL|function|supportsExtension
DECL|function|syncToDisk
DECL|function|unmap
DECL|function|write
DECL|function|~QAbstractFileEngine
DECL|function|~QAbstractFileEngineHandler
DECL|function|~QAbstractFileEngineHandlerList
DECL|function|~QAbstractFileEngineIterator
DECL|member|fileInfo
DECL|member|filters
DECL|member|nameFilters
DECL|member|path
DECL|variable|qt_abstractfileenginehandlerlist_shutDown
DECL|variable|qt_file_engine_handlers_in_use
