DECL|class|QBufferPrivate
DECL|function|QBuffer
DECL|function|QBuffer
DECL|function|QBuffer
DECL|function|QBuffer
DECL|function|QBufferPrivate
DECL|function|_q_emitSignals
DECL|function|atEnd
DECL|function|buffer
DECL|function|buffer
DECL|function|canReadLine
DECL|function|close
DECL|function|connectNotify
DECL|function|data
DECL|function|disconnectNotify
DECL|function|open
DECL|function|peek
DECL|function|peek
DECL|function|pos
DECL|function|readData
DECL|function|seek
DECL|function|setBuffer
DECL|function|setData
DECL|function|size
DECL|function|writeData
DECL|function|~QBuffer
DECL|function|~QBufferPrivate
DECL|member|buf
DECL|member|defaultBuf
DECL|member|signalConnectionCount
DECL|member|signalsEmitted
DECL|member|writtenSinceLastEmit
