DECL|function|byteOrder
DECL|function|device
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|setVersion
DECL|function|version
DECL|macro|QDATASTREAM_H
DECL|variable|Key
DECL|variable|Key
DECL|variable|Key
DECL|variable|Key
DECL|variable|Key
DECL|variable|Key
DECL|variable|QByteArray
DECL|variable|QDataStreamPrivate
DECL|variable|QHash
DECL|variable|QIODevice
DECL|variable|QLinkedList
DECL|variable|QList
DECL|variable|QMap
DECL|variable|QSet
DECL|variable|QVector
