DECL|class|QDebugStateSaverPrivate
DECL|function|QDebugStateSaver
DECL|function|QDebugStateSaverPrivate
DECL|function|restoreState
DECL|function|~QDebugStateSaver
DECL|macro|QT_NO_DEBUG
DECL|macro|qDebug
DECL|member|m_dbg
DECL|member|m_spaces
DECL|member|m_streamParams
