DECL|class|QDirIteratorPrivate
DECL|class|QDirIteratorPrivateIteratorStack
DECL|function|QDirIterator
DECL|function|QDirIterator
DECL|function|QDirIterator
DECL|function|QDirIterator
DECL|function|QDirIteratorPrivate
DECL|function|advance
DECL|function|checkAndPushDirectory
DECL|function|entryMatches
DECL|function|fileInfo
DECL|function|fileName
DECL|function|filePath
DECL|function|hasNext
DECL|function|matchesFilters
DECL|function|next
DECL|function|path
DECL|function|pushDirectory
DECL|function|~QDirIterator
DECL|function|~QDirIteratorPrivateIteratorStack
DECL|member|currentFileInfo
DECL|member|dirEntry
DECL|member|engine
DECL|member|fileEngineIterators
DECL|member|filters
DECL|member|iteratorFlags
DECL|member|nameFilters
DECL|member|nameRegExps
DECL|member|nativeIterators
DECL|member|nextFileInfo
DECL|member|visitedLinks
