DECL|function|_q_isMacHidden
DECL|function|absoluteName
DECL|function|bundleName
DECL|function|canonicalName
DECL|function|copyFile
DECL|function|createDirectory
DECL|function|createLink
DECL|function|currentPath
DECL|function|fillMetaData
DECL|function|getLinkTarget
DECL|function|homePath
DECL|function|id
DECL|function|removeDirectory
DECL|function|removeFile
DECL|function|renameFile
DECL|function|resolveGroupName
DECL|function|resolveUserName
DECL|function|rootPath
DECL|function|setCurrentPath
DECL|function|setPermissions
DECL|function|tempPath
DECL|macro|PATH_CHUNK_SIZE
