DECL|function|QFileSystemWatcher
DECL|function|QFileSystemWatcher
DECL|function|QFileSystemWatcherPrivate
DECL|function|_q_directoryChanged
DECL|function|_q_fileChanged
DECL|function|addPath
DECL|function|addPaths
DECL|function|createNativeEngine
DECL|function|directories
DECL|function|files
DECL|function|init
DECL|function|initPollerEngine
DECL|function|removePath
DECL|function|removePaths
DECL|function|~QFileSystemWatcher
DECL|macro|USE_INOTIFY
