DECL|class|QDnotifySignalThread
DECL|function|QDnotifyFileSystemWatcherEngine
DECL|function|QDnotifySignalThread
DECL|function|addPaths
DECL|function|create
DECL|function|event
DECL|function|qfswd_sigio_monitor
DECL|function|readFromDnotify
DECL|function|refresh
DECL|function|removePaths
DECL|function|run
DECL|function|run
DECL|function|startNotify
DECL|function|stop
DECL|function|updateInfo
DECL|function|~QDnotifyFileSystemWatcherEngine
DECL|function|~QDnotifySignalThread
DECL|macro|DN_ACCESS
DECL|macro|DN_ATTRIB
DECL|macro|DN_CREATE
DECL|macro|DN_DELETE
DECL|macro|DN_MODIFY
DECL|macro|DN_MULTISHOT
DECL|macro|DN_RENAME
DECL|macro|F_NOTIFY
DECL|member|isExecing
DECL|member|mutex
DECL|member|wait
DECL|variable|qfswd_fileChanged_pipe
DECL|variable|qfswd_old_sigio_action
DECL|variable|qfswd_old_sigio_handler
