DECL|class|SidCleanup
DECL|enumerator|Q_FileIdInfo
DECL|function|absoluteName
DECL|function|accessTime
DECL|function|canonicalName
DECL|function|clearWinStatData
DECL|function|copyFile
DECL|function|createDirectory
DECL|function|createLink
DECL|function|creationTime
DECL|function|currentPath
DECL|function|fileId
DECL|function|fileIdWin8
DECL|function|fileTimeToQDateTime
DECL|function|fillMetaData
DECL|function|fillMetaData
DECL|function|fillMetaData
DECL|function|fillPermissions
DECL|function|getFindData
DECL|function|getLinkTarget
DECL|function|homePath
DECL|function|id
DECL|function|isDirPath
DECL|function|mkDir
DECL|function|modificationTime
DECL|function|nativeAbsoluteFilePath
DECL|function|owner
DECL|function|readLink
DECL|function|readSymLink
DECL|function|removeDirectory
DECL|function|removeFile
DECL|function|renameFile
DECL|function|resolveLibs
DECL|function|resolveUNCLibs
DECL|function|rmDir
DECL|function|rootPath
DECL|function|setCurrentPath
DECL|function|setPermissions
DECL|function|tempPath
DECL|function|tryDriveUNCFallback
DECL|function|tryFindFallback
DECL|function|uncListSharesOnServer
DECL|function|uncShareExists
DECL|function|~SidCleanup
DECL|macro|FSCTL_GET_REPARSE_POINT
DECL|macro|INVALID_FILE_ATTRIBUTES
DECL|macro|IO_REPARSE_TAG_SYMLINK
DECL|macro|MAXIMUM_REPARSE_DATA_BUFFER_SIZE
DECL|macro|PATH_MAX
DECL|macro|QT_NO_LIBRARY
DECL|macro|REPARSE_DATA_BUFFER_HEADER_SIZE
DECL|macro|SECURITY_WIN32
DECL|macro|SPI_GETPLATFORMTYPE
DECL|macro|_INTPTR_T_DEFINED
DECL|member|DataBuffer
DECL|member|FileId
DECL|member|Flags
DECL|member|GenericReparseBuffer
DECL|member|Identifier
DECL|member|MountPointReparseBuffer
DECL|member|PathBuffer
DECL|member|PathBuffer
DECL|member|PrintNameLength
DECL|member|PrintNameLength
DECL|member|PrintNameOffset
DECL|member|PrintNameOffset
DECL|member|ReparseDataLength
DECL|member|ReparseTag
DECL|member|Reserved
DECL|member|SubstituteNameLength
DECL|member|SubstituteNameLength
DECL|member|SubstituteNameOffset
DECL|member|SubstituteNameOffset
DECL|member|SymbolicLinkReparseBuffer
DECL|member|VolumeSerialNumber
DECL|member|shi1_netname
DECL|member|shi1_remark
DECL|member|shi1_type
DECL|struct|_FILE_ID_128
DECL|struct|_FILE_ID_INFO
DECL|struct|_REPARSE_DATA_BUFFER
DECL|struct|_SHARE_INFO_1
DECL|typedef|FILE_ID_128
DECL|typedef|FILE_ID_INFO
DECL|typedef|PFILE_ID_128
DECL|typedef|PFILE_ID_INFO
DECL|typedef|PREPARSE_DATA_BUFFER
DECL|typedef|PtrBuildTrusteeWithSidW
DECL|typedef|PtrGetEffectiveRightsFromAclW
DECL|typedef|PtrGetNamedSecurityInfoW
DECL|typedef|PtrGetUserProfileDirectoryW
DECL|typedef|PtrGetVolumePathNamesForVolumeNameW
DECL|typedef|PtrLookupAccountSidW
DECL|typedef|PtrNetApiBufferFree
DECL|typedef|PtrNetShareEnum
DECL|typedef|Q_FILE_INFO_BY_HANDLE_CLASS
DECL|typedef|REPARSE_DATA_BUFFER
DECL|typedef|SHARE_INFO_1
DECL|typedef|intptr_t
DECL|typedef|intptr_t
DECL|typedef|intptr_t
DECL|variable|currentUserSID
DECL|variable|currentUserTrusteeW
DECL|variable|ptrBuildTrusteeWithSidW
DECL|variable|ptrGetEffectiveRightsFromAclW
DECL|variable|ptrGetNamedSecurityInfoW
DECL|variable|ptrGetUserProfileDirectoryW
DECL|variable|ptrGetVolumePathNamesForVolumeNameW
DECL|variable|ptrLookupAccountSidW
DECL|variable|ptrNetApiBufferFree
DECL|variable|ptrNetShareEnum
DECL|variable|qfsPrivateCurrentDir
DECL|variable|qt_ntfs_permission_lookup
DECL|variable|worldSID
DECL|variable|worldTrusteeW
