DECL|function|QFileInfo
DECL|function|QFileInfo
DECL|function|QFileInfo
DECL|function|QFileInfo
DECL|function|QFileInfo
DECL|function|QFileInfo
DECL|function|absoluteDir
DECL|function|absoluteFilePath
DECL|function|absolutePath
DECL|function|baseName
DECL|function|bundleName
DECL|function|caching
DECL|function|canonicalFilePath
DECL|function|canonicalPath
DECL|function|completeBaseName
DECL|function|completeSuffix
DECL|function|created
DECL|function|d_func
DECL|function|dir
DECL|function|exists
DECL|function|exists
DECL|function|fileName
DECL|function|filePath
DECL|function|getFileFlags
DECL|function|getFileName
DECL|function|getFileOwner
DECL|function|getFileTime
DECL|function|group
DECL|function|groupId
DECL|function|isBundle
DECL|function|isDir
DECL|function|isExecutable
DECL|function|isFile
DECL|function|isHidden
DECL|function|isNativePath
DECL|function|isReadable
DECL|function|isRelative
DECL|function|isRoot
DECL|function|isSymLink
DECL|function|isWritable
DECL|function|lastModified
DECL|function|lastRead
DECL|function|makeAbsolute
DECL|function|operator =
DECL|function|operator ==
DECL|function|owner
DECL|function|ownerId
DECL|function|path
DECL|function|permission
DECL|function|permissions
DECL|function|readLink
DECL|function|refresh
DECL|function|setCaching
DECL|function|setFile
DECL|function|setFile
DECL|function|setFile
DECL|function|size
DECL|function|suffix
DECL|function|~QFileInfo
