DECL|function|Handle
DECL|function|QWindowsFileSystemWatcherEngineThread
DECL|function|addPaths
DECL|function|msgFindNextFailed
DECL|function|removePaths
DECL|function|run
DECL|function|stop
DECL|function|wakeup
DECL|function|~QWindowsFileSystemWatcherEngine
DECL|function|~QWindowsFileSystemWatcherEngineThread
