DECL|function|QFileDevice
DECL|function|QFileDevice
DECL|function|QFileDevice
DECL|function|QFileDevice
DECL|function|QFileDevice
DECL|function|QFileDevicePrivate
DECL|function|_qfile_writeData
DECL|function|atEnd
DECL|function|close
DECL|function|engine
DECL|function|error
DECL|function|fileName
DECL|function|flush
DECL|function|handle
DECL|function|isSequential
DECL|function|map
DECL|function|permissions
DECL|function|pos
DECL|function|putCharHelper
DECL|function|readData
DECL|function|readLineData
DECL|function|resize
DECL|function|seek
DECL|function|setError
DECL|function|setError
DECL|function|setError
DECL|function|setPermissions
DECL|function|size
DECL|function|unmap
DECL|function|unsetError
DECL|function|writeData
DECL|function|~QFileDevice
DECL|function|~QFileDevicePrivate
DECL|macro|tr
DECL|variable|QFILE_WRITEBUFFER_SIZE
