DECL|function|QFSFileEngine
DECL|function|QFSFileEngine
DECL|function|QFSFileEngine
DECL|function|QFSFileEnginePrivate
DECL|function|beginEntryList
DECL|function|close
DECL|function|closeFdFh
DECL|function|endEntryList
DECL|function|entryList
DECL|function|extension
DECL|function|flush
DECL|function|flushFh
DECL|function|handle
DECL|function|init
DECL|function|isSequential
DECL|function|isSequentialFdFh
DECL|function|open
DECL|function|open
DECL|function|open
DECL|function|open
DECL|function|open
DECL|function|openFd
DECL|function|openFh
DECL|function|pos
DECL|function|posFdFh
DECL|function|read
DECL|function|readFdFh
DECL|function|readLine
DECL|function|readLineFdFh
DECL|function|seek
DECL|function|seekFdFh
DECL|function|setFileName
DECL|function|size
DECL|function|sizeFdFh
DECL|function|supportsExtension
DECL|function|syncToDisk
DECL|function|write
DECL|function|writeFdFh
DECL|function|~QFSFileEngine
DECL|macro|INVALID_FILE_ATTRIBUTES
DECL|macro|S_ISCHR
DECL|macro|S_ISFIFO
DECL|macro|S_ISREG
DECL|macro|S_ISSOCK
