DECL|function|state
DECL|macro|IO_Append
DECL|macro|IO_ModeMask
DECL|macro|IO_ReadOnly
DECL|macro|IO_ReadWrite
DECL|macro|IO_Translate
DECL|macro|IO_Truncate
DECL|macro|IO_WriteOnly
DECL|macro|QIODEVICE_H
DECL|variable|IO_AbortError
DECL|variable|IO_Async
DECL|variable|IO_Combined
DECL|variable|IO_ConnectError
DECL|variable|IO_Direct
DECL|variable|IO_FatalError
DECL|variable|IO_Ok
DECL|variable|IO_Open
DECL|variable|IO_OpenError
DECL|variable|IO_Raw
DECL|variable|IO_ReadError
DECL|variable|IO_ResourceError
DECL|variable|IO_Sequential
DECL|variable|IO_StateMask
DECL|variable|IO_TimeOutError
DECL|variable|IO_TypeMask
DECL|variable|IO_UnspecifiedError
DECL|variable|IO_WriteError
DECL|variable|QDebug
DECL|variable|QIODevicePrivate
