DECL|function|QIODevice
DECL|function|QIODevice
DECL|function|QIODevice
DECL|function|QIODevice
DECL|function|QIODevice
DECL|function|QIODevicePrivate
DECL|function|atEnd
DECL|function|bytesAvailable
DECL|function|bytesToWrite
DECL|function|canReadLine
DECL|function|close
DECL|function|debugBinaryString
DECL|function|debugBinaryString
DECL|function|errorString
DECL|function|getChar
DECL|function|isOpen
DECL|function|isReadable
DECL|function|isSequential
DECL|function|isTextModeEnabled
DECL|function|isWritable
DECL|function|open
DECL|function|openMode
DECL|function|operator <<
DECL|function|peek
DECL|function|peek
DECL|function|peek
DECL|function|peek
DECL|function|pos
DECL|function|putChar
DECL|function|putCharHelper
DECL|function|read
DECL|function|read
DECL|function|readAll
DECL|function|readLine
DECL|function|readLine
DECL|function|readLineData
DECL|function|reset
DECL|function|seek
DECL|function|setErrorString
DECL|function|setOpenMode
DECL|function|setTextModeEnabled
DECL|function|size
DECL|function|ungetChar
DECL|function|waitForBytesWritten
DECL|function|waitForReadyRead
DECL|function|write
DECL|function|write
DECL|function|~QIODevice
DECL|function|~QIODevicePrivate
DECL|macro|CHECK_MAXLEN
DECL|macro|CHECK_READABLE
DECL|macro|CHECK_WRITABLE
DECL|macro|Q_VOID
