DECL|macro|QLOGGINGCATEGORY_H
DECL|macro|Q_DECLARE_LOGGING_CATEGORY
DECL|macro|Q_LOGGING_CATEGORY
DECL|macro|Q_LOGGING_CATEGORY
DECL|macro|qCCritical
DECL|macro|qCCritical
DECL|macro|qCDebug
DECL|macro|qCDebug
DECL|macro|qCDebug
DECL|macro|qCDebug
DECL|macro|qCInfo
DECL|macro|qCInfo
DECL|macro|qCInfo
DECL|macro|qCInfo
DECL|macro|qCWarning
DECL|macro|qCWarning
DECL|macro|qCWarning
DECL|macro|qCWarning
