DECL|function|QLoggingCategory
DECL|function|defaultCategory
DECL|function|installFilter
DECL|function|isEnabled
DECL|function|setBoolLane
DECL|function|setEnabled
DECL|function|setFilterRules
DECL|function|~QLoggingCategory
DECL|variable|qtDefaultCategoryName
