DECL|class|QProcessManager
DECL|function|QProcessManager
DECL|function|_q_dupEnvironment
DECL|function|_q_notified
DECL|function|add
DECL|function|add_fd
DECL|function|bb_select
DECL|function|bytesAvailableFromStderr
DECL|function|bytesAvailableFromStdout
DECL|function|catchDeadChildren
DECL|function|createChannel
DECL|function|destroyChannel
DECL|function|destroyPipe
DECL|function|doSpawn
DECL|function|execChild
DECL|function|findExitCode
DECL|function|initializeProcessManager
DECL|function|killProcess
DECL|function|lock
DECL|function|processManager
DECL|function|processStarted
DECL|function|qt_create_pipe
DECL|function|qt_prettyDebug
DECL|function|qt_sa_sigchld_handler
DECL|function|qt_timeout_value
DECL|function|readFromStderr
DECL|function|readFromStdout
DECL|function|remove
DECL|function|run
DECL|function|select_msecs
DECL|function|spawnChild
DECL|function|startDetached
DECL|function|startDetached
DECL|function|startProcess
DECL|function|systemEnvironment
DECL|function|terminateProcess
DECL|function|unlock
DECL|function|waitForBytesWritten
DECL|function|waitForDeadChild
DECL|function|waitForFinished
DECL|function|waitForReadyRead
DECL|function|waitForStarted
DECL|function|waitForWrite
DECL|function|writeToStdin
DECL|function|~QProcessManager
DECL|macro|environ
DECL|member|children
DECL|member|deathPipe
DECL|member|exitResult
DECL|member|mutex
DECL|member|pid
DECL|member|process
DECL|member|serialNumber
DECL|struct|QProcessInfo
DECL|variable|errorBufferMax
DECL|variable|idCounter
DECL|variable|processManagerInstance
DECL|variable|qt_qprocess_deadChild_pipe
DECL|variable|qt_sa_old_sigchld_handler
