DECL|enumerator|n_pfds
DECL|function|QProcessPoller
DECL|function|_q_dupEnvironment
DECL|function|bytesAvailableInChannel
DECL|function|childStartedPipe
DECL|function|closeChannel
DECL|function|destroyPipe
DECL|function|execChild
DECL|function|findExitCode
DECL|function|forkfd
DECL|function|killProcess
DECL|function|openChannel
DECL|function|poll
DECL|function|processStarted
DECL|function|qt_create_pipe
DECL|function|qt_pollfd_check
DECL|function|qt_prettyDebug
DECL|function|readFromChannel
DECL|function|startDetached
DECL|function|startProcess
DECL|function|stderrPipe
DECL|function|stdinPipe
DECL|function|stdoutPipe
DECL|function|systemEnvironment
DECL|function|terminateProcess
DECL|function|waitForBytesWritten
DECL|function|waitForDeadChild
DECL|function|waitForFinished
DECL|function|waitForReadyRead
DECL|function|waitForStarted
DECL|function|writeToStdin
DECL|macro|environ
DECL|member|pfds
DECL|struct|QProcessPoller
DECL|variable|errorBufferMax
