DECL|function|QSaveFile
DECL|function|QSaveFile
DECL|function|QSaveFile
DECL|function|QSaveFilePrivate
DECL|function|cancelWriting
DECL|function|close
DECL|function|commit
DECL|function|directWriteFallback
DECL|function|fileName
DECL|function|open
DECL|function|setDirectWriteFallback
DECL|function|setFileName
DECL|function|writeData
DECL|function|~QSaveFile
DECL|function|~QSaveFilePrivate
