DECL|class|QWinRTSettingsPrivate
DECL|function|QWinRTSettingsPrivate
DECL|function|QWinRTSettingsPrivate
DECL|function|children
DECL|function|clear
DECL|function|clearContainerMaps
DECL|function|create
DECL|function|create
DECL|function|createSubContainer
DECL|function|fileName
DECL|function|flush
DECL|function|get
DECL|function|getContainer
DECL|function|init
DECL|function|isWritable
DECL|function|keyNames
DECL|function|onDataChanged
DECL|function|propertyValueToQVariant
DECL|function|remove
DECL|function|set
DECL|function|subContainer
DECL|function|subContainerNames
DECL|function|sync
DECL|function|~QWinRTSettingsPrivate
DECL|macro|PROP_CASE_TO_VARIANT
DECL|member|applicationData
DECL|member|dataChangedToken
DECL|member|readContainers
DECL|member|writeContainer
DECL|typedef|ContainerItem
DECL|typedef|ContainerIterable
DECL|typedef|ContainerIterator
DECL|typedef|DataHandler
DECL|typedef|ValueItem
DECL|typedef|ValueIterable
DECL|typedef|ValueIterator
