DECL|class|QWinSettingsPrivate
DECL|class|RegistryKey
DECL|function|QWinSettingsPrivate
DECL|function|QWinSettingsPrivate
DECL|function|RegistryKey
DECL|function|allKeys
DECL|function|childKeysOrGroups
DECL|function|children
DECL|function|clear
DECL|function|close
DECL|function|create
DECL|function|create
DECL|function|createOrOpenKey
DECL|function|createOrOpenKey
DECL|function|deleteChildGroups
DECL|function|errorCodeToString
DECL|function|escapedKey
DECL|function|fileName
DECL|function|flush
DECL|function|get
DECL|function|handle
DECL|function|isWritable
DECL|function|key
DECL|function|keyName
DECL|function|keyPath
DECL|function|mergeKeySets
DECL|function|mergeKeySets
DECL|function|openKey
DECL|function|parentHandle
DECL|function|readKey
DECL|function|readOnly
DECL|function|remove
DECL|function|set
DECL|function|stringContainsNullChar
DECL|function|sync
DECL|function|unescapedKey
DECL|function|writeHandle
DECL|function|~QWinSettingsPrivate
DECL|member|deleteWriteHandleOnExit
DECL|member|m_handle
DECL|member|m_key
DECL|member|m_parent_handle
DECL|member|m_read_only
DECL|member|regList
DECL|typedef|NameSet
DECL|typedef|RegistryKeyList
DECL|variable|registryPermissions
