DECL|class|QMacSettingsPrivate
DECL|enumerator|Macify
DECL|enumerator|Qtify
DECL|enum|RotateShift
DECL|function|QMacSettingsPrivate
DECL|function|children
DECL|function|clear
DECL|function|comify
DECL|function|create
DECL|function|fileName
DECL|function|flush
DECL|function|get
DECL|function|isWritable
DECL|function|macKey
DECL|function|macList
DECL|function|macValue
DECL|function|qtKey
DECL|function|qtValue
DECL|function|readPlistFile
DECL|function|remove
DECL|function|rotateSlashesDotsAndMiddots
DECL|function|set
DECL|function|sync
DECL|function|urlFromFileName
DECL|function|writePlistFile
DECL|function|~QMacSettingsPrivate
DECL|member|applicationId
DECL|member|applicationOrSuiteId
DECL|member|domains
DECL|member|hostName
DECL|member|numDomains
DECL|member|suiteId
DECL|member|userName
DECL|struct|SearchDomain
DECL|variable|hostNames
DECL|variable|numHostNames
