DECL|class|QSettingsIniKey
DECL|enumerator|Space
DECL|enumerator|Special
DECL|function|QConfFile
DECL|function|QConfFileSettingsPrivate
DECL|function|QConfFileSettingsPrivate
DECL|function|QSettings
DECL|function|QSettings
DECL|function|QSettings
DECL|function|QSettings
DECL|function|QSettings
DECL|function|QSettings
DECL|function|QSettings
DECL|function|QSettings
DECL|function|QSettings
DECL|function|QSettingsIniKey
DECL|function|QSettingsIniKey
DECL|function|QSettingsIniSection
DECL|function|QSettingsPrivate
DECL|function|QSettingsPrivate
DECL|function|actualKey
DECL|function|allKeys
DECL|function|applicationName
DECL|function|beginGroup
DECL|function|beginGroupOrArray
DECL|function|beginReadArray
DECL|function|beginWriteArray
DECL|function|childGroups
DECL|function|childKeys
DECL|function|children
DECL|function|clear
DECL|function|clear
DECL|function|clearCache
DECL|function|contains
DECL|function|create
DECL|function|create
DECL|function|defaultFormat
DECL|function|endArray
DECL|function|endGroup
DECL|function|ensureAllSectionsParsed
DECL|function|ensureSectionParsed
DECL|function|event
DECL|function|fallbacksEnabled
DECL|function|fileName
DECL|function|fileName
DECL|function|flush
DECL|function|format
DECL|function|fromName
DECL|function|get
DECL|function|getPath
DECL|function|group
DECL|function|iniChopTrailingSpaces
DECL|function|iniCodec
DECL|function|iniEscapedKey
DECL|function|iniEscapedString
DECL|function|iniEscapedStringList
DECL|function|iniUnescapedKey
DECL|function|iniUnescapedStringList
DECL|function|initAccess
DECL|function|initDefaultPaths
DECL|function|initFormat
DECL|function|isWritable
DECL|function|isWritable
DECL|function|isWritable
DECL|function|mergedKeyMap
DECL|function|normalizedKey
DECL|function|operator <
DECL|function|organizationName
DECL|function|pathHashKey
DECL|function|processChild
DECL|function|qIsLikelyToBeNfs
DECL|function|qIsLikelyToBeNfs
DECL|function|qIsLikelyToBeNfs
DECL|function|qIsLikelyToBeNfs
DECL|function|qt_isEvilFsTypeName
DECL|function|readIniFile
DECL|function|readIniLine
DECL|function|readIniSection
DECL|function|registerFormat
DECL|function|remove
DECL|function|remove
DECL|function|requestUpdate
DECL|function|scope
DECL|function|set
DECL|function|setArrayIndex
DECL|function|setDefaultFormat
DECL|function|setFallbacksEnabled
DECL|function|setIniCodec
DECL|function|setIniCodec
DECL|function|setPath
DECL|function|setStatus
DECL|function|setSystemIniPath
DECL|function|setUserIniPath
DECL|function|setValue
DECL|function|splitArgs
DECL|function|status
DECL|function|stringListToVariantList
DECL|function|stringToVariant
DECL|function|sync
DECL|function|sync
DECL|function|syncConfFile
DECL|function|unixLock
DECL|function|update
DECL|function|value
DECL|function|variantListToStringList
DECL|function|variantToString
DECL|function|windowsConfigPath
DECL|function|writeIniFile
DECL|function|~QConfFile
DECL|function|~QConfFileSettingsPrivate
DECL|function|~QSettings
DECL|function|~QSettingsPrivate
DECL|macro|AUTOFSNG_SUPER_MAGIC
DECL|macro|AUTOFS_SUPER_MAGIC
DECL|macro|CSIDL_APPDATA
DECL|macro|CSIDL_COMMON_APPDATA
DECL|macro|FLUSH_CURRENT_SECTION
DECL|macro|FLUSH_CURRENT_SECTION
DECL|macro|NFS_SUPER_MAGIC
DECL|macro|Q_AUTOTEST_EXPORT_HELPER
DECL|macro|Q_AUTOTEST_EXPORT_HELPER
DECL|member|caseSensitivity
DECL|member|extension
DECL|member|keyMap
DECL|member|position
DECL|member|position
DECL|member|readFunc
DECL|member|writeFunc
DECL|struct|QConfFileCustomFormat
DECL|struct|QSettingsIniSection
DECL|typedef|ConfFileCache
DECL|typedef|ConfFileHash
DECL|typedef|CustomFormatVector
DECL|typedef|IniKeyMap
DECL|typedef|IniMap
DECL|typedef|PathHash
DECL|variable|charTraits
DECL|variable|globalDefaultFormat
DECL|variable|hexDigits
DECL|variable|settingsGlobalMutex
