DECL|function|convertCharArray
DECL|function|displayName
DECL|function|resolveGetSpecialFolderPath
DECL|function|standardLocations
DECL|function|writableLocation
DECL|macro|CSIDL_MYMUSIC
DECL|macro|CSIDL_MYVIDEO
DECL|typedef|GetSpecialFolderPath
