DECL|function|appendOrganizationAndApp
DECL|function|enableTestMode
DECL|function|isTestModeEnabled
DECL|function|standardLocations
DECL|function|writableLocation
DECL|function|xdgDataDirs
DECL|variable|qsp_testMode
