DECL|function|Latin1Char
DECL|function|QTemporaryFile
DECL|function|QTemporaryFile
DECL|function|QTemporaryFile
DECL|function|QTemporaryFile
DECL|function|QTemporaryFile
DECL|function|QTemporaryFile
DECL|function|QTemporaryFilePrivate
DECL|function|autoRemove
DECL|function|close
DECL|function|createFileFromTemplate
DECL|function|createNativeFile
DECL|function|defaultTemplateName
DECL|function|engine
DECL|function|fileName
DECL|function|fileTemplate
DECL|function|isReallyOpen
DECL|function|open
DECL|function|open
DECL|function|remove
DECL|function|rename
DECL|function|renameOverwrite
DECL|function|setAutoRemove
DECL|function|setFileName
DECL|function|setFileTemplate
DECL|function|setFileTemplate
DECL|function|~QTemporaryFile
DECL|function|~QTemporaryFileEngine
DECL|function|~QTemporaryFilePrivate
DECL|typedef|Char
DECL|typedef|NativeFileHandle
