DECL|class|QTemporaryFileEngine
DECL|class|QTemporaryFilePrivate
DECL|function|QTemporaryFile
DECL|function|QTemporaryFile
DECL|function|QTemporaryFile
DECL|function|QTemporaryFile
DECL|function|QTemporaryFile
DECL|function|QTemporaryFile
DECL|function|QTemporaryFileEngine
DECL|function|QTemporaryFilePrivate
DECL|function|autoRemove
DECL|function|close
DECL|function|createFileFromTemplate
DECL|function|createLocalFile
DECL|function|fileEngine
DECL|function|fileName
DECL|function|fileTemplate
DECL|function|isReallyOpen
DECL|function|open
DECL|function|open
DECL|function|remove
DECL|function|rename
DECL|function|setAutoRemove
DECL|function|setFileName
DECL|function|setFileTemplate
DECL|function|setFileTemplate
DECL|function|~QTemporaryFile
DECL|function|~QTemporaryFileEngine
DECL|function|~QTemporaryFilePrivate
DECL|member|autoRemove
DECL|member|filePathIsTemplate
DECL|member|templateName
