DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|qSetFieldWidth
DECL|function|qSetPadChar
DECL|function|qSetRealNumberPrecision
DECL|macro|QTEXTSTREAM_H
DECL|typedef|QTS
DECL|typedef|QTSMFC
DECL|typedef|QTSMFI
DECL|typedef|QTextStreamFunction
DECL|variable|QTextDecoder
DECL|variable|QTextStreamPrivate
