DECL|function|Q_DECLARE_SHARED
DECL|function|operator
DECL|function|operator
DECL|macro|QURL_H
DECL|variable|E1
DECL|variable|E1
DECL|variable|E1
DECL|variable|E2
DECL|variable|QDataStream
DECL|variable|QUrl
DECL|variable|QUrlPrivate
DECL|variable|QUrlQuery
DECL|variable|operator
