DECL|function|adapt
DECL|function|appendEncode
DECL|function|containsProhibitedOuptut
DECL|function|encodeDigit
DECL|function|equal
DECL|function|idnWhitelist
DECL|function|isBidirectionalL
DECL|function|isBidirectionalRorAL
DECL|function|isDotDelimiter
DECL|function|isMappedToNothing
DECL|function|lessThan
DECL|function|mapToLowerCase
DECL|function|nextDotDelimiter
DECL|function|operator <
DECL|function|operator <
DECL|function|qt_ACE_do
DECL|function|qt_check_std3rules
DECL|function|qt_is_idn_enabled
DECL|function|qt_nameprep
DECL|function|qt_punycodeDecoder
DECL|function|qt_punycodeEncoder
DECL|function|setIdnWhitelist
DECL|macro|Q_MAXINT
DECL|member|mapping
DECL|member|uc
DECL|struct|NameprepCaseFoldingEntry
DECL|variable|NameprepCaseFolding
DECL|variable|base
DECL|variable|damp
DECL|variable|idn_whitelist
DECL|variable|idn_whitelist_size
DECL|variable|initial_bias
DECL|variable|initial_n
DECL|variable|skew
DECL|variable|tmax
DECL|variable|tmin
DECL|variable|user_idn_whitelist
