DECL|function|_HEXDIG
DECL|function|_IPLiteral
DECL|function|_IPv4Address
DECL|function|_IPv6Address
DECL|function|_IPvFuture
DECL|function|_authority
DECL|function|_decOctet
DECL|function|_fragment
DECL|function|_h16
DECL|function|_hierPart
DECL|function|_host
DECL|function|_ls32
DECL|function|_pathAbEmpty
DECL|function|_pathAbs
DECL|function|_pathRootless
DECL|function|_pchar
DECL|function|_pctEncoded
DECL|function|_port
DECL|function|_query
DECL|function|_regName
DECL|function|_scheme
DECL|function|_segmentNZ
DECL|function|_subDelims
DECL|function|_unreserved
DECL|function|_userInfo
DECL|function|qt_isValidUrlIP
DECL|function|qt_urlParse
