DECL|enumerator|DecodeCharacter
DECL|enumerator|EncodeCharacter
DECL|enumerator|LeaveCharacter
DECL|enum|EncodingAction
DECL|function|advanceByte
DECL|function|appendByte
DECL|function|availableBytes
DECL|function|decode
DECL|function|decodeNibble
DECL|function|decodePercentEncoding
DECL|function|encodeNibble
DECL|function|encodedUtf8ToUtf16
DECL|function|ensureDetached
DECL|function|isHex
DECL|function|isUpperHex
DECL|function|peekByte
DECL|function|qt_urlRecode
DECL|function|qt_urlRecodeByteArray
DECL|function|recode
DECL|function|toUpperHex
DECL|function|unicodeToEncodedUtf8
DECL|struct|QUrlUtf8Traits
DECL|variable|defaultActionTable
DECL|variable|reservedMask
DECL|variable|uchar
