DECL|enumerator|DecodeCharacter
DECL|enumerator|EncodeCharacter
DECL|enumerator|LeaveCharacter
DECL|enum|EncodingAction
DECL|function|decodeNibble
DECL|function|decodePercentEncoding
DECL|function|encodeNibble
DECL|function|encodedUtf8ToUtf16
DECL|function|ensureDetached
DECL|function|isHex
DECL|function|isUnicodeNonCharacter
DECL|function|isUpperHex
DECL|function|qt_urlRecode
DECL|function|recode
DECL|function|toUpperHex
DECL|function|unicodeToEncodedUtf8
DECL|variable|defaultActionTable
DECL|variable|delimsMask
DECL|variable|reservedMask
DECL|variable|uchar
