DECL|class|QUrlQueryPrivate
DECL|function|QUrlQuery
DECL|function|QUrlQuery
DECL|function|QUrlQuery
DECL|function|QUrlQuery
DECL|function|QUrlQueryPrivate
DECL|function|addQueryItem
DECL|function|addQueryItem
DECL|function|allQueryItemValues
DECL|function|clear
DECL|function|clone
DECL|function|detach
DECL|function|findKey
DECL|function|findKey
DECL|function|findRecodedKey
DECL|function|hasQueryItem
DECL|function|idempotentRecodeToUser
DECL|function|isDetached
DECL|function|isEmpty
DECL|function|operator =
DECL|function|operator ==
DECL|function|query
DECL|function|queryItemValue
DECL|function|queryItems
DECL|function|queryPairDelimiter
DECL|function|queryValueDelimiter
DECL|function|recodeAndAppend
DECL|function|recodeFromUser
DECL|function|recodeToUser
DECL|function|removeAllQueryItems
DECL|function|removeQueryItem
DECL|function|setQuery
DECL|function|setQuery
DECL|function|setQueryDelimiters
DECL|function|setQueryItems
DECL|function|~QUrlQuery
DECL|macro|decode
DECL|macro|encode
DECL|macro|leave
DECL|member|itemList
DECL|member|pairDelimiter
DECL|member|valueDelimiter
DECL|typedef|Map
