DECL|class|QUrlPrivate
DECL|enumerator|HostCanonicalized
DECL|enumerator|Normalized
DECL|enumerator|ParseAndSet
DECL|enumerator|ParseOnly
DECL|enumerator|Parsed
DECL|enumerator|Validated
DECL|enum|ParseOptions
DECL|enum|State
DECL|function|QUrl
DECL|function|QUrl
DECL|function|QUrl
DECL|function|QUrlPrivate
DECL|function|QUrlPrivate
DECL|function|authority
DECL|function|authority
DECL|function|canonicalHost
DECL|function|clear
DECL|function|clear
DECL|function|createErrorString
DECL|function|detach
DECL|function|encodedFragment
DECL|function|encodedHost
DECL|function|encodedPassword
DECL|function|encodedPath
DECL|function|encodedQuery
DECL|function|encodedUserName
DECL|function|ensureEncodedParts
DECL|function|errorString
DECL|function|fragment
DECL|function|fromAce
DECL|function|fromLocalFile
DECL|function|fromPercentEncoding
DECL|function|fromPercentEncodingHelper
DECL|function|fromPercentEncodingMutable
DECL|function|fromUserInput
DECL|function|hasFragment
DECL|function|hasQuery
DECL|function|host
DECL|function|isDetached
DECL|function|isEmpty
DECL|function|isHex
DECL|function|isLocalFile
DECL|function|isLocalFile
DECL|function|isParentOf
DECL|function|isRelative
DECL|function|isValid
DECL|function|mergePaths
DECL|function|normalized
DECL|function|operator !=
DECL|function|operator <
DECL|function|operator <<
DECL|function|operator <<
DECL|function|operator =
DECL|function|operator =
DECL|function|operator ==
DECL|function|operator >>
DECL|function|parse
DECL|function|password
DECL|function|path
DECL|function|port
DECL|function|queryItem
DECL|function|removeDotsFromPath
DECL|function|resolved
DECL|function|scheme
DECL|function|setAuthority
DECL|function|setAuthority
DECL|function|setEncodedFragment
DECL|function|setEncodedHost
DECL|function|setEncodedPassword
DECL|function|setEncodedPath
DECL|function|setEncodedQuery
DECL|function|setEncodedUrl
DECL|function|setEncodedUserInfo
DECL|function|setEncodedUserName
DECL|function|setFragment
DECL|function|setHost
DECL|function|setPassword
DECL|function|setPath
DECL|function|setPort
DECL|function|setScheme
DECL|function|setUrl
DECL|function|setUserInfo
DECL|function|setUserInfo
DECL|function|setUserName
DECL|function|toAce
DECL|function|toDisplayString
DECL|function|toEncoded
DECL|function|toEncoded
DECL|function|toHex
DECL|function|toLocalFile
DECL|function|toPercentEncoding
DECL|function|toPercentEncodingHelper
DECL|function|toPrettyPercentEncoding
DECL|function|toString
DECL|function|topLevelDomain
DECL|function|url
DECL|function|userInfo
DECL|function|userInfo
DECL|function|userName
DECL|function|validate
DECL|function|~QUrl
DECL|macro|ABNF_gen_delims
DECL|macro|ABNF_pchar
DECL|macro|ABNF_reserved
DECL|macro|ABNF_sub_delims
DECL|macro|QURL_HASFLAG
DECL|macro|QURL_SETFLAG
DECL|macro|QURL_UNSETFLAG
DECL|macro|qToLower
DECL|member|encodedFragment
DECL|member|encodedNormalized
DECL|member|encodedOriginal
DECL|member|encodedPassword
DECL|member|encodedPath
DECL|member|encodedUserName
DECL|member|errorInfo
DECL|member|fragment
DECL|member|hasFragment
DECL|member|hasQuery
DECL|member|host
DECL|member|isHostValid
DECL|member|isValid
DECL|member|pairDelimiter
DECL|member|parsingMode
DECL|member|password
DECL|member|path
DECL|member|port
DECL|member|query
DECL|member|ref
DECL|member|scheme
DECL|member|stateFlags
DECL|member|userName
DECL|member|valueDelimiter
DECL|variable|fragmentExcludeChars
DECL|variable|passwordExcludeChars
DECL|variable|pathExcludeChars
DECL|variable|queryExcludeChars
DECL|variable|userNameExcludeChars
