DECL|class|QWinIoCompletionPort
DECL|function|QWinIoCompletionPort
DECL|function|QWinOverlappedIoNotifier
DECL|function|_q_notified
DECL|function|drainQueue
DECL|function|notify
DECL|function|registerNotifier
DECL|function|run
DECL|function|setEnabled
DECL|function|setHandle
DECL|function|unregisterNotifier
DECL|function|waitForNotified
DECL|function|~QWinIoCompletionPort
DECL|function|~QWinOverlappedIoNotifier
DECL|member|drainQueueKey
DECL|member|drainQueueMutex
DECL|member|finishThreadKey
DECL|member|hPort
DECL|member|hQueueDrainedEvent
DECL|member|iocp
DECL|member|iocpInstanceLock
DECL|member|iocpInstanceRefCount
DECL|member|mutex
DECL|member|notifiers
