DECL|function|Overlapped
DECL|function|QWindowsPipeWriter
DECL|function|bytesToWrite
DECL|function|clear
DECL|function|emitPendingBytesWrittenValue
DECL|function|notified
DECL|function|stop
DECL|function|waitForNotification
DECL|function|waitForWrite
DECL|function|write
DECL|function|writeFileCompleted
DECL|function|~QWindowsPipeWriter
