DECL|class|QWinIoCompletionPort
DECL|class|QWinOverlappedIoNotifierPrivate
DECL|function|IOResult
DECL|function|QWinIoCompletionPort
DECL|function|QWinOverlappedIoNotifier
DECL|function|QWinOverlappedIoNotifierPrivate
DECL|function|_q_notified
DECL|function|drainQueue
DECL|function|handle
DECL|function|notify
DECL|function|registerNotifier
DECL|function|run
DECL|function|setEnabled
DECL|function|setHandle
DECL|function|unregisterNotifier
DECL|function|waitForNotified
DECL|function|~QWinIoCompletionPort
DECL|function|~QWinOverlappedIoNotifier
DECL|member|drainQueueKey
DECL|member|drainQueueMutex
DECL|member|errorCode
DECL|member|finishThreadKey
DECL|member|hHandle
DECL|member|hPort
DECL|member|hQueueDrainedEvent
DECL|member|hResultsMutex
DECL|member|hSemaphore
DECL|member|iocp
DECL|member|iocp
DECL|member|iocpInstanceLock
DECL|member|iocpInstanceLock
DECL|member|iocpInstanceRefCount
DECL|member|iocpInstanceRefCount
DECL|member|mutex
DECL|member|notifiers
DECL|member|numberOfBytes
DECL|member|overlapped
DECL|member|results
DECL|struct|IOResult
