DECL|function|QWindowsPipeReader
DECL|function|bytesAvailable
DECL|function|canReadLine
DECL|function|checkPipeState
DECL|function|notified
DECL|function|qt_cancelIo
DECL|function|read
DECL|function|setHandle
DECL|function|startAsyncRead
DECL|function|stop
DECL|function|waitForPipeClosed
DECL|function|waitForReadyRead
DECL|function|~QWindowsPipeReader
