DECL|class|tst_QList
DECL|function|append
DECL|function|at
DECL|function|begin
DECL|function|const_shared_null
DECL|function|contains
DECL|function|count
DECL|function|empty
DECL|function|end
DECL|function|endsWith
DECL|function|first
DECL|function|initializeList
DECL|function|last
DECL|function|lastIndexOf
DECL|function|length
DECL|function|lengthSignature
DECL|function|mid
DECL|function|move
DECL|function|prepend
DECL|function|removeAll
DECL|function|removeAt
DECL|function|removeOne
DECL|function|replace
DECL|function|startsWith
DECL|function|swap
DECL|function|takeAt
DECL|function|takeFirst
DECL|function|takeLast
DECL|function|testOperators
DECL|function|testSTLIterators
DECL|function|toSet
DECL|function|toStdList
DECL|function|toVector
DECL|function|value
