DECL|class|QAhiScreenCursor
DECL|class|QAhiScreenPrivate
DECL|function|QAhiScreen
DECL|function|QAhiScreenCursor
DECL|function|QAhiScreenPrivate
DECL|function|blit
DECL|function|configure
DECL|function|connect
DECL|function|depthForPixelFormat
DECL|function|disconnect
DECL|function|hide
DECL|function|initDevice
DECL|function|move
DECL|function|pixelFormatForImageFormat
DECL|function|set
DECL|function|setMode
DECL|function|setMode
DECL|function|show
DECL|function|shutdownDevice
DECL|function|solidFill
DECL|function|~QAhiScreen
DECL|function|~QAhiScreenPrivate
DECL|member|context
DECL|member|context
DECL|member|cursor
DECL|member|screen
DECL|member|surface
