DECL|function|Lexer
DECL|function|canInsertAutomaticSemicolon
DECL|function|code
DECL|function|convertHex
DECL|function|convertHex
DECL|function|convertUnicode
DECL|function|decodeUnicodeEscapeCharacter
DECL|function|errorCode
DECL|function|errorMessage
DECL|function|followsClosingBrace
DECL|function|isDecimalDigit
DECL|function|isHexDigit
DECL|function|isIdentLetter
DECL|function|isLineTerminator
DECL|function|isOctalDigit
DECL|function|isUnicodeEscapeSequence
DECL|function|lex
DECL|function|prevTerminator
DECL|function|qmlMode
DECL|function|regExpFlagFromChar
DECL|function|scanChar
DECL|function|scanDirectives
DECL|function|scanRegExp
DECL|function|scanToken
DECL|function|setCode
DECL|function|syncProhibitAutomaticSemicolon
DECL|function|tokenEndColumn
DECL|function|tokenEndLine
DECL|function|tokenKind
DECL|function|tokenLength
DECL|function|tokenOffset
DECL|function|tokenSpell
DECL|function|tokenStartColumn
DECL|function|tokenStartLine
DECL|function|tokenText
DECL|function|tokenValue
DECL|macro|tr
DECL|macro|tr
