DECL|function|UnixMakefileGenerator
DECL|function|init2
DECL|function|libtoolFileName
DECL|function|writeDefaultVariables
DECL|function|writeLibtoolFile
DECL|function|writeMakeParts
DECL|function|writeMakefile
DECL|function|writePrlFile
DECL|function|writeSubTargets
