DECL|function|Robot
DECL|function|RobotHead
DECL|function|RobotLimb
DECL|function|RobotPart
DECL|function|RobotTorso
DECL|function|boundingRect
DECL|function|boundingRect
DECL|function|boundingRect
DECL|function|boundingRect
DECL|function|dragEnterEvent
DECL|function|dragEnterEvent
DECL|function|dragLeaveEvent
DECL|function|dropEvent
DECL|function|dropEvent
DECL|function|paint
DECL|function|paint
DECL|function|paint
DECL|function|paint
