DECL|function|QSqlResult
DECL|function|addBindValue
DECL|function|at
DECL|function|bindValue
DECL|function|bindValue
DECL|function|bindValueType
DECL|function|bindValueType
DECL|function|bindingSyntax
DECL|function|boundValue
DECL|function|boundValue
DECL|function|boundValueCount
DECL|function|boundValueName
DECL|function|boundValues
DECL|function|clear
DECL|function|detachFromResultSet
DECL|function|driver
DECL|function|exec
DECL|function|execBatch
DECL|function|executedQuery
DECL|function|fetchNext
DECL|function|fetchPrevious
DECL|function|fieldSerial
DECL|function|handle
DECL|function|hasOutValues
DECL|function|holderAt
DECL|function|isActive
DECL|function|isForwardOnly
DECL|function|isSelect
DECL|function|isValid
DECL|function|lastError
DECL|function|lastInsertId
DECL|function|lastQuery
DECL|function|namedToPositionalBinding
DECL|function|nextResult
DECL|function|numericalPrecisionPolicy
DECL|function|positionalToNamedBinding
DECL|function|prepare
DECL|function|qIsAlnum
DECL|function|record
DECL|function|resetBindCount
DECL|function|savePrepare
DECL|function|setActive
DECL|function|setAt
DECL|function|setForwardOnly
DECL|function|setLastError
DECL|function|setNumericalPrecisionPolicy
DECL|function|setQuery
DECL|function|setSelect
DECL|function|virtual_hook
DECL|function|~QSqlResult
