DECL|macro|QSQLQUERY_H
DECL|variable|Key
DECL|variable|QMap
DECL|variable|QSqlDriver
DECL|variable|QSqlError
DECL|variable|QSqlQueryPrivate
DECL|variable|QSqlRecord
DECL|variable|QSqlResult
DECL|variable|QVariant
