DECL|macro|QSQLDRIVER_H
DECL|variable|QSqlDatabase
DECL|variable|QSqlDriverPrivate
DECL|variable|QSqlError
DECL|variable|QSqlField
DECL|variable|QSqlIndex
DECL|variable|QSqlRecord
DECL|variable|QSqlResult
DECL|variable|QVariant
