DECL|class|QConnectionDict
DECL|class|QSqlDatabasePrivate
DECL|function|QSqlDatabase
DECL|function|QSqlDatabase
DECL|function|QSqlDatabase
DECL|function|QSqlDatabase
DECL|function|QSqlDatabasePrivate
DECL|function|QSqlDatabasePrivate
DECL|function|addDatabase
DECL|function|addDatabase
DECL|function|addDatabase
DECL|function|cleanConnections
DECL|function|cleanDriverDict
DECL|function|cloneDatabase
DECL|function|close
DECL|function|commit
DECL|function|connectOptions
DECL|function|connectionName
DECL|function|connectionNames
DECL|function|contains
DECL|function|contains_ts
DECL|function|copy
DECL|function|database
DECL|function|database
DECL|function|databaseName
DECL|function|disable
DECL|function|driver
DECL|function|driverDict
DECL|function|driverName
DECL|function|drivers
DECL|function|exec
DECL|function|hostName
DECL|function|init
DECL|function|invalidateDb
DECL|function|isDriverAvailable
DECL|function|isOpen
DECL|function|isOpenError
DECL|function|isValid
DECL|function|keys_ts
DECL|function|lastError
DECL|function|numericalPrecisionPolicy
DECL|function|open
DECL|function|open
DECL|function|operator <<
DECL|function|operator =
DECL|function|password
DECL|function|port
DECL|function|primaryIndex
DECL|function|record
DECL|function|registerSqlDriver
DECL|function|removeDatabase
DECL|function|removeDatabase
DECL|function|rollback
DECL|function|setConnectOptions
DECL|function|setDatabaseName
DECL|function|setHostName
DECL|function|setNumericalPrecisionPolicy
DECL|function|setPassword
DECL|function|setPort
DECL|function|setUserName
DECL|function|shared_null
DECL|function|tables
DECL|function|transaction
DECL|function|userName
DECL|function|~QSqlDatabase
DECL|function|~QSqlDatabasePrivate
DECL|macro|RETCODE
DECL|macro|RETCODE
DECL|macro|SCHAR
DECL|macro|SCHAR
DECL|macro|SQL_DATE
DECL|macro|SQL_DOUBLE
DECL|macro|SQL_FLOAT
DECL|macro|SQL_TIMESTAMP
DECL|macro|SQL_TYPE_DATE
DECL|macro|SQL_TYPE_TIME
DECL|macro|_WINSCARD_H_
DECL|member|connName
DECL|member|connOptions
DECL|member|dbname
DECL|member|defaultConnection
DECL|member|driver
DECL|member|drvName
DECL|member|hname
DECL|member|lock
DECL|member|port
DECL|member|precisionPolicy
DECL|member|pword
DECL|member|q
DECL|member|ref
DECL|member|uname
DECL|typedef|DriverDict
DECL|variable|qDriverDictInit
