DECL|class|QSqlResultPrivate
DECL|function|QHolder
DECL|function|QSqlResult
DECL|function|QSqlResultPrivate
DECL|function|addBindValue
DECL|function|at
DECL|function|bindValue
DECL|function|bindValue
DECL|function|bindValueType
DECL|function|bindValueType
DECL|function|bindingSyntax
DECL|function|boundValue
DECL|function|boundValue
DECL|function|boundValueCount
DECL|function|boundValueName
DECL|function|boundValues
DECL|function|clear
DECL|function|clear
DECL|function|clearIndex
DECL|function|clearValues
DECL|function|detachFromResultSet
DECL|function|driver
DECL|function|exec
DECL|function|execBatch
DECL|function|executedQuery
DECL|function|fetchNext
DECL|function|fetchPrevious
DECL|function|handle
DECL|function|hasOutValues
DECL|function|holderAt
DECL|function|isActive
DECL|function|isForwardOnly
DECL|function|isSelect
DECL|function|isValid
DECL|function|lastError
DECL|function|lastInsertId
DECL|function|lastQuery
DECL|function|namedToPositionalBinding
DECL|function|nextResult
DECL|function|numericalPrecisionPolicy
DECL|function|operator !=
DECL|function|operator ==
DECL|function|positionalToNamedBinding
DECL|function|prepare
DECL|function|qFieldSerial
DECL|function|qIsAlnum
DECL|function|record
DECL|function|resetBindCount
DECL|function|resetBindCount
DECL|function|savePrepare
DECL|function|setActive
DECL|function|setAt
DECL|function|setForwardOnly
DECL|function|setLastError
DECL|function|setNumericalPrecisionPolicy
DECL|function|setQuery
DECL|function|setSelect
DECL|function|virtual_hook
DECL|function|~QSqlResult
DECL|member|active
DECL|member|bindCount
DECL|member|binds
DECL|member|error
DECL|member|executedQuery
DECL|member|forwardOnly
DECL|member|holderName
DECL|member|holderPos
DECL|member|holders
DECL|member|idx
DECL|member|indexes
DECL|member|isSel
DECL|member|precisionPolicy
DECL|member|q
DECL|member|sql
DECL|member|sqldriver
DECL|member|types
DECL|member|values
DECL|struct|QHolder
DECL|typedef|IndexMap
DECL|typedef|QHolderVector
