DECL|class|tst_QGlobalStatic
DECL|function|ThrowingType
DECL|function|ThrowingType
DECL|function|afterDestruction
DECL|function|api
DECL|function|beforeInitialization
DECL|function|constVolatile
DECL|function|exception
DECL|function|otherFunction
DECL|function|threadStressTest
DECL|function|threadedException
DECL|function|~ThrowingType
DECL|member|constructedCount
DECL|member|constructedCount
DECL|member|destructedCount
DECL|member|destructedCount
DECL|member|i
DECL|struct|ThrowingType
DECL|struct|Type
DECL|variable|exceptionControlVar
DECL|variable|threadStressTestControlVar
DECL|variable|tst_QGlobalStatic
