DECL|class|QDB2DriverPrivate
DECL|class|QDB2ResultPrivate
DECL|function|QDB2Driver
DECL|function|QDB2Driver
DECL|function|QDB2DriverPrivate
DECL|function|QDB2Result
DECL|function|QDB2ResultPrivate
DECL|function|beginTransaction
DECL|function|clearValueCache
DECL|function|close
DECL|function|commitTransaction
DECL|function|createResult
DECL|function|data
DECL|function|emptyValueCache
DECL|function|escapeIdentifier
DECL|function|exec
DECL|function|fetch
DECL|function|fetchFirst
DECL|function|fetchLast
DECL|function|fetchNext
DECL|function|formatValue
DECL|function|handle
DECL|function|handle
DECL|function|hasFeature
DECL|function|isNull
DECL|function|nextResult
DECL|function|numRowsAffected
DECL|function|open
DECL|function|prepare
DECL|function|primaryIndex
DECL|function|qDB2Warn
DECL|function|qDB2Warn
DECL|function|qDecodeDB2Type
DECL|function|qFromTChar
DECL|function|qGetBigIntData
DECL|function|qGetBinaryData
DECL|function|qGetDoubleData
DECL|function|qGetIntData
DECL|function|qGetStringData
DECL|function|qMakeError
DECL|function|qMakeError
DECL|function|qMakeFieldInfo
DECL|function|qMakeFieldInfo
DECL|function|qMakeStatement
DECL|function|qSplitTableQualifier
DECL|function|qSqlWarning
DECL|function|qSqlWarning
DECL|function|qToTChar
DECL|function|qWarnDB2Handle
DECL|function|record
DECL|function|record
DECL|function|reset
DECL|function|rollbackTransaction
DECL|function|setAutoCommit
DECL|function|size
DECL|function|tables
DECL|function|virtual_hook
DECL|function|~QDB2Driver
DECL|function|~QDB2Result
DECL|function|~QDB2ResultPrivate
DECL|macro|SQL_BIGINT_TYPE
DECL|macro|SQL_BIGUINT_TYPE
DECL|macro|UNICODE
DECL|member|dp
DECL|member|hDbc
DECL|member|hEnv
DECL|member|hStmt
DECL|member|recInf
DECL|member|user
DECL|member|valueCache
DECL|variable|COLNAMESIZE
DECL|variable|qParamType
