DECL|function|GLWidget
DECL|function|drawPbuffer
DECL|function|initCommon
DECL|function|initPbuffer
DECL|function|initializeGL
DECL|function|initializeGeometry
DECL|function|orthographicProjection
DECL|function|paintGL
DECL|function|perspectiveProjection
DECL|function|resizeGL
DECL|function|setAnimationPaused
DECL|function|~GLWidget
DECL|macro|GL_MULTISAMPLE
DECL|variable|colorArray
