DECL|class|tst_QTextBoundaryFinder
DECL|function|fastConstructor
DECL|function|graphemeBoundaries
DECL|function|init
DECL|function|init_libthai
DECL|function|isAtBoundaryLine
DECL|function|isAtWordStart
DECL|function|sentenceBoundaries
DECL|function|thaiLineBreak
DECL|function|toNextBoundary
DECL|function|toNextBoundary_data
DECL|function|toPreviousBoundary
DECL|function|toPreviousBoundary_data
DECL|function|wordBoundaries
DECL|macro|LIBTHAI_MAJOR
DECL|typedef|th_brk_def
DECL|variable|th_brk
