DECL|class|tst_QtConcurrentResultStore
DECL|function|addCanceledResult
DECL|function|addResult
DECL|function|addResults
DECL|function|construction
DECL|function|contains
DECL|function|count
DECL|function|filterMode
DECL|function|init
DECL|function|iterators
DECL|function|resultAt
DECL|function|resultIndex
DECL|member|int0
DECL|member|int1
DECL|member|int2
DECL|member|vec0
DECL|member|vec1
