DECL|function|MainWindow
DECL|function|about
DECL|function|closeEvent
DECL|function|createActions
DECL|function|createMenus
DECL|function|maybeSave
DECL|function|open
DECL|function|penColor
DECL|function|penWidth
DECL|function|save
DECL|function|saveFile
