DECL|function|QFutureWatcherBase
DECL|function|QFutureWatcherBasePrivate
DECL|function|callOutInterfaceDisconnected
DECL|function|cancel
DECL|function|connectNotify
DECL|function|connectOutputInterface
DECL|function|disconnectNotify
DECL|function|disconnectOutputInterface
DECL|function|event
DECL|function|isCanceled
DECL|function|isFinished
DECL|function|isPaused
DECL|function|isRunning
DECL|function|isStarted
DECL|function|pause
DECL|function|postCallOutEvent
DECL|function|progressMaximum
DECL|function|progressMinimum
DECL|function|progressText
DECL|function|progressValue
DECL|function|resume
DECL|function|sendCallOutEvent
DECL|function|setPaused
DECL|function|setPendingResultsLimit
DECL|function|togglePaused
DECL|function|waitForFinished
