DECL|class|MyWidget
DECL|class|tst_QAction
DECL|function|MyWidget
DECL|function|actionEvent
DECL|function|actionEvent
DECL|function|alternateShortcuts
DECL|function|cleanupTestCase
DECL|function|enabledVisibleInteraction
DECL|function|getSetCheck
DECL|function|initTestCase
DECL|function|setIconText
DECL|function|setIconText_data
DECL|function|setStandardKeys
DECL|function|setText
DECL|function|setText_data
DECL|function|task200823_tooltip
DECL|function|task229128TriggeredSignalWhenInActiongroup
DECL|function|task229128TriggeredSignalWithoutActiongroup
DECL|function|tst_QAction
DECL|function|updateState
DECL|function|~tst_QAction
DECL|member|m_lastAction
DECL|member|m_lastEventType
DECL|member|m_tstWidget
DECL|member|tst
