DECL|function|QSystemLockPrivate
DECL|function|cleanHandle
DECL|function|createUnixKeyFile
DECL|function|handle
DECL|function|modifySemaphore
DECL|function|setErrorString
DECL|macro|tr
DECL|member|array
DECL|member|buf
DECL|member|val
DECL|union|qt_semun
