DECL|class|TstDialog
DECL|class|TstWidget
DECL|class|tst_qmouseevent_modal
DECL|function|TstDialog
DECL|function|TstWidget
DECL|function|buttonPressed
DECL|function|cleanupTestCase
DECL|function|closeDialog
DECL|function|count
DECL|function|initTestCase
DECL|function|mousePressRelease
DECL|function|releaseMouse
DECL|function|showEvent
DECL|member|c
DECL|member|d
DECL|member|m
DECL|member|pb
DECL|member|w
