DECL|class|FtpCommand
DECL|class|tst_QFtp
DECL|function|FtpCommand
DECL|function|FtpCommand
DECL|function|FtpCommand
DECL|function|FtpCommand
DECL|function|abort
DECL|function|abort_data
DECL|function|activeMode
DECL|function|activeModeDone
DECL|function|addCommand
DECL|function|binaryAscii
DECL|function|bytesAvailable
DECL|function|bytesAvailable_data
DECL|function|cd
DECL|function|cdUpSlot
DECL|function|cd_data
DECL|function|cleanup
DECL|function|cleanupTestCase
DECL|function|close
DECL|function|close_data
DECL|function|commandFinished
DECL|function|commandSequence
DECL|function|commandSequence_data
DECL|function|commandStarted
DECL|function|connectToHost
DECL|function|connectToHost_data
DECL|function|connectToUnresponsiveHost
DECL|function|dataTransferProgress
DECL|function|dirExists
DECL|function|done
DECL|function|doneSignal
DECL|function|fileExists
DECL|function|get
DECL|function|get_data
DECL|function|init
DECL|function|initTestCase
DECL|function|initTestCase_data
DECL|function|list
DECL|function|listInfo
DECL|function|list_data
DECL|function|login
DECL|function|login_data
DECL|function|mkdir
DECL|function|mkdir2
DECL|function|mkdir2Slot
DECL|function|mkdir_data
DECL|function|newFtp
DECL|function|operator <<
DECL|function|operator =
DECL|function|operator >>
DECL|function|proxy
DECL|function|proxy_data
DECL|function|put
DECL|function|put_data
DECL|function|qtbug7359Crash
DECL|function|queueMoreCommandsInDoneSlot
DECL|function|readyRead
DECL|function|remove
DECL|function|rename
DECL|function|renameCleanup
DECL|function|renameInit
DECL|function|rename_data
DECL|function|rmdir
DECL|function|stateChanged
DECL|function|tst_QFtp
DECL|function|~tst_QFtp
DECL|macro|CURRENTCOMMAND_TEST
DECL|macro|SRCDIR
DECL|member|args
DECL|member|bytesAvailable_done
DECL|member|bytesAvailable_finished
DECL|member|bytesAvailable_finishedGet
DECL|member|bytesDone
DECL|member|bytesTotal
DECL|member|close_state
DECL|member|cmd
DECL|member|commandSequence_success
DECL|member|connectToHost_state
DECL|member|cur_state
DECL|member|current_id
DECL|member|done_success
DECL|member|ftp
DECL|member|id
DECL|member|ids
DECL|member|inFileDirExistsFunction
DECL|member|listInfo_i
DECL|member|login_state
DECL|member|networkSessionExplicit
DECL|member|networkSessionImplicit
DECL|member|newData_ba
DECL|member|resultMap
DECL|member|success
DECL|member|uniqueExtension
DECL|struct|CommandResult
DECL|typedef|ResMapIt
DECL|variable|bytesDone_init
DECL|variable|bytesTotal_init
