DECL|function|MainWindow
DECL|function|about
DECL|function|aboutQt
DECL|function|bold
DECL|function|center
DECL|function|contextMenuEvent
DECL|function|copy
DECL|function|createActions
DECL|function|createMenus
DECL|function|cut
DECL|function|italic
DECL|function|justify
DECL|function|leftAlign
DECL|function|newFile
DECL|function|open
DECL|function|paste
DECL|function|print
DECL|function|redo
DECL|function|rightAlign
DECL|function|save
DECL|function|setLineSpacing
DECL|function|setParagraphSpacing
DECL|function|undo
