DECL|function|createPluginStub
DECL|function|fixPathToEpocOS
DECL|function|generate_test_uid
DECL|function|generate_uid
DECL|function|initProjectDeploySymbian
DECL|function|isBinary
DECL|function|isPlugin
DECL|macro|HW_Z_DIR
DECL|macro|SUFFIX_DLL
DECL|macro|SUFFIX_EXE
DECL|macro|SUFFIX_QTPLUGIN
DECL|macro|SYSBIN_DIR
