DECL|variable|bytearray
DECL|variable|bytearray
DECL|variable|floatingPoint
DECL|variable|future
DECL|variable|future
DECL|variable|future
DECL|variable|future
DECL|variable|future
DECL|variable|future
DECL|variable|future
DECL|variable|image
DECL|variable|integer
DECL|variable|string
