DECL|enumerator|BaselineNotFound
DECL|enumerator|IgnoreItem
DECL|enumerator|Mismatch
DECL|enumerator|Ok
DECL|enum|ItemStatus
DECL|function|ImageItem
DECL|function|~ImageItem
DECL|macro|BASELINEPROTOCOL_H
DECL|macro|FileFormat
DECL|macro|QLC
DECL|macro|QLS
DECL|member|image
DECL|member|imageChecksums
DECL|member|itemChecksum
DECL|member|itemName
DECL|member|misc
DECL|member|operator
DECL|member|public
DECL|member|status
DECL|member|testFunction
DECL|struct|ImageItem
DECL|typedef|ImageItemList
DECL|variable|ImageItem
DECL|variable|QString
