DECL|function|addClientProperty
DECL|function|checkImage
DECL|function|compareItem
DECL|function|connect
DECL|function|connectToBaselineServer
DECL|function|disconnectFromBaselineServer
DECL|function|fetchCustomClientProperties
DECL|function|handleCmdLineArgs
DECL|function|modifyImage
DECL|function|newRow
DECL|function|setAutoMode
DECL|function|setSimFail
DECL|function|testImage
DECL|macro|MAXCMDLINEARGS
DECL|member|connected
DECL|member|curFunction
DECL|member|customAutoModeSet
DECL|member|customInfo
DECL|member|definedTestCase
DECL|member|definedTestProject
DECL|member|dryRunMode
DECL|member|fargv
DECL|member|gotBaselines
DECL|member|itemList
DECL|member|proto
DECL|member|simfail
DECL|member|triedConnecting
DECL|namespace|QBaselineTest
