DECL|enumerator|GapItem
DECL|enumerator|KeepSize
DECL|enumerator|NoFlags
DECL|enum|ItemFlags
DECL|macro|QDOCKAREALAYOUT_P_H
DECL|member|flags
DECL|member|operator
DECL|member|placeHolderItem
DECL|member|pos
DECL|member|size
DECL|member|subinfo
DECL|member|widgetItem
DECL|struct|QDockAreaLayoutItem
DECL|variable|QDockAreaLayoutInfo
DECL|variable|QDockWidget
DECL|variable|QLayoutItem
DECL|variable|QLayoutItem
DECL|variable|QMainWindow
DECL|variable|QMainWindowLayout
DECL|variable|QPlaceHolderItem
DECL|variable|QTabBar
DECL|variable|QWidget
DECL|variable|QWidgetAnimator
