DECL|function|QLabel
DECL|function|QLabel
DECL|function|QLabel
DECL|function|QLabel
DECL|function|QLabel
DECL|function|_q_linkHovered
DECL|function|_q_movieResized
DECL|function|_q_movieUpdated
DECL|function|alignment
DECL|function|buddy
DECL|function|changeEvent
DECL|function|clear
DECL|function|clearContents
DECL|function|contextMenuEvent
DECL|function|createStandardContextMenu
DECL|function|documentRect
DECL|function|ensureTextControl
DECL|function|ensureTextLayouted
DECL|function|ensureTextPopulated
DECL|function|event
DECL|function|focusInEvent
DECL|function|focusNextPrevChild
DECL|function|focusOutEvent
DECL|function|hasScaledContents
DECL|function|hasSelectedText
DECL|function|heightForWidth
DECL|function|indent
DECL|function|init
DECL|function|keyPressEvent
DECL|function|layoutPoint
DECL|function|layoutRect
DECL|function|margin
DECL|function|minimumSizeHint
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|movie
DECL|function|openExternalLinks
DECL|function|paintEvent
DECL|function|picture
DECL|function|pixmap
DECL|function|selectedText
DECL|function|selectionStart
DECL|function|sendControlEvent
DECL|function|setAlignment
DECL|function|setAlignment
DECL|function|setBuddy
DECL|function|setIndent
DECL|function|setMargin
DECL|function|setMovie
DECL|function|setNum
DECL|function|setNum
DECL|function|setOpenExternalLinks
DECL|function|setPicture
DECL|function|setPixmap
DECL|function|setScaledContents
DECL|function|setSelection
DECL|function|setText
DECL|function|setTextFormat
DECL|function|setTextInteractionFlags
DECL|function|setWordWrap
DECL|function|sizeForWidth
DECL|function|sizeHint
DECL|function|text
DECL|function|textDirection
DECL|function|textFormat
DECL|function|textInteractionFlags
DECL|function|updateLabel
DECL|function|updateShortcut
DECL|function|wordWrap
DECL|function|~QLabel
