DECL|function|QWceMenuBarPrivate
DECL|function|QWceMenuPrivate
DECL|function|_q_updateDefaultAction
DECL|function|addAction
DECL|function|addAction
DECL|function|addAction
DECL|function|addAction
DECL|function|qt_wce_change_command
DECL|function|qt_wce_clear_menu
DECL|function|qt_wce_create_menubar
DECL|function|qt_wce_delete_action_list
DECL|function|qt_wce_disable_soft_key
DECL|function|qt_wce_enable_soft_key
DECL|function|qt_wce_get_module_handle
DECL|function|qt_wce_get_quit_action
DECL|function|qt_wce_get_quit_action
DECL|function|qt_wce_insert_action
DECL|function|qt_wce_rename_menu_item
DECL|function|rebuild
DECL|function|rebuild
DECL|function|removeAction
DECL|function|removeAction
DECL|function|resolveAygLibs
DECL|function|syncAction
DECL|function|syncAction
DECL|function|wceCommands
DECL|function|wceCommands
DECL|function|wceCommands
DECL|function|wceCommands
DECL|function|wceCreateMenuBar
DECL|function|wceDestroyMenuBar
DECL|function|wceEmitSignals
DECL|function|wceMenu
DECL|function|wceMenu
DECL|function|wceRefresh
DECL|function|wceRefresh
DECL|function|~QWceMenuBarPrivate
DECL|function|~QWceMenuPrivate
DECL|macro|SHCMBF_EMPTYBAR
DECL|macro|SHCMBM_GETSUBMENU
DECL|macro|SHCMBM_OVERRIDEKEY
DECL|macro|SHMBOF_NODEFAULT
DECL|macro|SHMBOF_NOTIFY
DECL|member|cBmpImages
DECL|member|cbSize
DECL|member|clrBk
DECL|member|dwFlags
DECL|member|hInstRes
DECL|member|hwndMB
DECL|member|hwndParent
DECL|member|nBmpId
DECL|member|nToolBarId
DECL|struct|qt_SHMENUBARINFO
DECL|typedef|AygCreateMenuBar
DECL|typedef|AygEnableSoftKey
DECL|variable|aygResolved
DECL|variable|nativeMenuBars
DECL|variable|ptrCreateMenuBar
DECL|variable|ptrEnableSoftKey
DECL|variable|qt_wce_menu_static_cmd_id
