DECL|function|actionEvent
DECL|function|allowCornerWidgets
DECL|function|allowSetVisible
DECL|function|handleReparent
DECL|function|init
DECL|function|isNativeMenuBar
DECL|function|menuBarEventFilter
DECL|function|popupAction
DECL|function|setNativeMenuBar
DECL|function|shortcutsHandledByNativeMenuBar
DECL|function|~QMenuBarImpl
