DECL|class|QMenuBarExtension
DECL|function|QMenuBar
DECL|function|QMenuBar
DECL|function|QMenuBarExtension
DECL|function|_q_actionHovered
DECL|function|_q_actionTriggered
DECL|function|_q_internalShortcutActivated
DECL|function|_q_updateLayout
DECL|function|actionAt
DECL|function|actionAt
DECL|function|actionEvent
DECL|function|actionGeometry
DECL|function|actionRect
DECL|function|activateAction
DECL|function|activeAction
DECL|function|addAction
DECL|function|addAction
DECL|function|addMenu
DECL|function|addMenu
DECL|function|addMenu
DECL|function|addSeparator
DECL|function|autoGeometry
DECL|function|calcActionRects
DECL|function|changeEvent
DECL|function|clear
DECL|function|cornerWidget
DECL|function|defaultAction
DECL|function|event
DECL|function|eventFilter
DECL|function|findActionForId
DECL|function|findIdForAction
DECL|function|focusFirstAction
DECL|function|focusInEvent
DECL|function|focusOutEvent
DECL|function|frameWidth
DECL|function|getNextAction
DECL|function|handleReparent
DECL|function|heightForWidth
DECL|function|init
DECL|function|initStyleOption
DECL|function|insertAny
DECL|function|insertMenu
DECL|function|insertSeparator
DECL|function|insertSeparator
DECL|function|isDefaultUp
DECL|function|isNativeMenuBar
DECL|function|isVisible
DECL|function|itemParameter
DECL|function|keyPressEvent
DECL|function|leaveEvent
DECL|function|menuRect
DECL|function|minimumSizeHint
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|paintEvent
DECL|function|paintEvent
DECL|function|popupAction
DECL|function|resizeEvent
DECL|function|setActiveAction
DECL|function|setAutoGeometry
DECL|function|setCornerWidget
DECL|function|setCurrentAction
DECL|function|setDefaultAction
DECL|function|setDefaultUp
DECL|function|setItemParameter
DECL|function|setKeyboardMode
DECL|function|setNativeMenuBar
DECL|function|setVisible
DECL|function|sizeHint
DECL|function|sizeHint
DECL|function|timerEvent
DECL|function|updateGeometries
DECL|function|~QMenuBar
