DECL|function|QToolBarAreaLayout
DECL|function|QToolBarAreaLayoutInfo
DECL|function|QToolBarAreaLayoutLine
DECL|function|addToolBar
DECL|function|addToolBarBreak
DECL|function|apply
DECL|function|clear
DECL|function|clear
DECL|function|currentGapIndex
DECL|function|deleteAllLayoutItems
DECL|function|distance
DECL|function|findToolBar
DECL|function|fitLayout
DECL|function|fitLayout
DECL|function|fitLayout
DECL|function|gapIndex
DECL|function|gapIndex
DECL|function|getInt
DECL|function|getStyleOptionInfo
DECL|function|indexOf
DECL|function|insertGap
DECL|function|insertGap
DECL|function|insertItem
DECL|function|insertItem
DECL|function|insertItem
DECL|function|insertToolBar
DECL|function|insertToolBar
DECL|function|insertToolBarBreak
DECL|function|insertToolBarBreak
DECL|function|isEmpty
DECL|function|item
DECL|function|itemAt
DECL|function|itemRect
DECL|function|itemRect
DECL|function|minimumSize
DECL|function|minimumSize
DECL|function|minimumSize
DECL|function|minimumSize
DECL|function|moveToolBar
DECL|function|moveToolBar
DECL|function|packRect
DECL|function|plug
DECL|function|realSizeHint
DECL|function|rectHint
DECL|function|remove
DECL|function|remove
DECL|function|removeToolBar
DECL|function|removeToolBar
DECL|function|removeToolBarBreak
DECL|function|removeToolBarBreak
DECL|function|restoreState
DECL|function|saveState
DECL|function|sizeHint
DECL|function|sizeHint
DECL|function|sizeHint
DECL|function|sizeHint
DECL|function|skip
DECL|function|skip
DECL|function|takeAt
DECL|function|toolBarBreak
DECL|function|unpackRect
DECL|function|unplug
