DECL|class|AppendCommand
DECL|class|InsertCommand
DECL|class|RemoveCommand
DECL|class|tst_QUndoStack
DECL|function|AppendCommand
DECL|function|InsertCommand
DECL|function|RemoveCommand
DECL|function|checkState
DECL|function|childCommand
DECL|function|clear
DECL|function|compression
DECL|function|glue
DECL|function|id
DECL|function|macroBeginEnd
DECL|function|mergeWith
DECL|function|redo
DECL|function|redo
DECL|function|redo
DECL|function|setClean
DECL|function|setIndex
DECL|function|tst_QUndoStack
DECL|function|undo
DECL|function|undo
DECL|function|undo
DECL|function|undoLimit
DECL|function|undoRedo
DECL|function|~AppendCommand
DECL|member|delete_cnt
DECL|member|delete_cnt
DECL|member|fail_merge
DECL|member|m_idx
DECL|member|m_idx
DECL|member|m_str
DECL|member|m_str
DECL|member|m_str
DECL|member|m_text
DECL|member|m_text
DECL|member|m_text
DECL|member|merged
