DECL|function|QX11Info
DECL|function|QX11Info
DECL|function|appCells
DECL|function|appColormap
DECL|function|appDefaultColormap
DECL|function|appDefaultVisual
DECL|function|appDepth
DECL|function|appDpiX
DECL|function|appDpiY
DECL|function|appRootWindow
DECL|function|appScreen
DECL|function|appTime
DECL|function|appUserTime
DECL|function|appVisual
DECL|function|cells
DECL|function|cloneX11Data
DECL|function|colormap
DECL|function|copyX11Data
DECL|function|defaultColormap
DECL|function|defaultVisual
DECL|function|depth
DECL|function|display
DECL|function|getX11Data
DECL|function|isCompositingManagerRunning
DECL|function|operator =
DECL|function|screen
DECL|function|setAppDpiX
DECL|function|setAppDpiY
DECL|function|setAppTime
DECL|function|setAppUserTime
DECL|function|setX11Data
DECL|function|visual
DECL|function|~QX11Info
