DECL|class|EngineWithNoIterator
DECL|class|EngineWithNoIteratorHandler
DECL|class|tst_QDirIterator
DECL|enumerator|DoDelete
DECL|enumerator|DontDelete
DECL|enum|Cleanup
DECL|function|EngineWithNoIterator
DECL|function|absoluteFilePathsFromRelativeIteratorPath
DECL|function|beginEntryList
DECL|function|create
DECL|function|createDirectory
DECL|function|createFile
DECL|function|createLink
DECL|function|dirorder
DECL|function|engineWithNoIterator
DECL|function|hiddenDirs_hiddenFiles
DECL|function|iterateRelativeDirectory
DECL|function|iterateRelativeDirectory_data
DECL|function|iterateResource
DECL|function|iterateResource_data
DECL|function|longPath
DECL|function|recurseWithFilters
DECL|function|relativePaths
DECL|function|stopLinkLoop
DECL|function|tst_QDirIterator
DECL|function|uncPaths
DECL|function|uncPaths_data
DECL|function|~tst_QDirIterator
DECL|macro|Q_NO_SYMLINKS
DECL|member|createdDirectories
DECL|member|createdFiles
DECL|member|currentDir
