DECL|function|TableGenerator
DECL|function|composeTable
DECL|function|findComposeFile
DECL|function|findSystemComposeDir
DECL|function|fromBase16
DECL|function|fromBase8
DECL|function|initPossibleLocations
DECL|function|keysymToUtf8
DECL|function|locale
DECL|function|orderComposeTable
DECL|function|parseComposeFile
DECL|function|parseIncludeInstruction
DECL|function|parseKeySequence
DECL|function|printComposeTable
DECL|function|processFile
DECL|function|readLocaleMappings
DECL|function|systemComposeDir
DECL|function|~TableGenerator
