DECL|function|MainWindow
DECL|function|about
DECL|function|closeEvent
DECL|function|createActions
DECL|function|createMenus
DECL|function|createStatusBar
DECL|function|createToolBars
DECL|function|documentWasModified
DECL|function|loadFile
DECL|function|maybeSave
DECL|function|newFile
DECL|function|open
DECL|function|readSettings
DECL|function|save
DECL|function|saveAs
DECL|function|saveFile
DECL|function|setCurrentFile
DECL|function|strippedName
DECL|function|writeSettings
