DECL|class|ChangedListener
DECL|class|ClearTestItem
DECL|class|ContextMenuItem
DECL|class|CustomScene
DECL|class|CustomView
DECL|class|DisabledItemTester
DECL|class|DndTester
DECL|class|EventSpy
DECL|class|EventTester
DECL|class|ExposedPixmapItem
DECL|class|FocusItem
DECL|class|FocusWidget
DECL|class|HoverItem
DECL|class|InputMethodTester
DECL|class|PolishItem
DECL|class|Scene
DECL|class|tst_QGraphicsScene
DECL|function|ClearTestItem
DECL|function|ContextMenuItem
DECL|function|CustomScene
DECL|function|CustomView
DECL|function|DisabledItemTester
DECL|function|DndTester
DECL|function|EventSpy
DECL|function|EventSpy
DECL|function|EventTester
DECL|function|ExposedPixmapItem
DECL|function|FocusWidget
DECL|function|HoverItem
DECL|function|PolishItem
DECL|function|addEllipse
DECL|function|addItem
DECL|function|addLine
DECL|function|addPath
DECL|function|addPixmap
DECL|function|addRect
DECL|function|addText
DECL|function|bspTreeDepth
DECL|function|changed
DECL|function|changedSignal
DECL|function|changedSignal_data
DECL|function|cleanup
DECL|function|clear
DECL|function|construction
DECL|function|contextMenuEvent
DECL|function|contextMenuEvent
DECL|function|contextMenuEvent_ItemIgnoresTransformations
DECL|function|count
DECL|function|createItemGroup
DECL|function|dispatchHoverOnPress
DECL|function|dragAndDrop_disabledOrInvisible
DECL|function|dragAndDrop_propagate
DECL|function|dragAndDrop_simple
DECL|function|dragEnterEvent
DECL|function|dragLeaveEvent
DECL|function|dragMoveEvent
DECL|function|dropEvent
DECL|function|event
DECL|function|eventFilter
DECL|function|eventsToDisabledItems
DECL|function|exposedRect
DECL|function|focusInEvent
DECL|function|focusItem
DECL|function|focusItemChangedSignal
DECL|function|focusItemLostFocus
DECL|function|focusOutEvent
DECL|function|focusOutEvent
DECL|function|hoverEvents_parentChild
DECL|function|hoverEvents_siblings
DECL|function|initTestCase
DECL|function|initialFocus
DECL|function|initialFocus_data
DECL|function|inputMethod
DECL|function|inputMethodEvent
DECL|function|inputMethodQuery
DECL|function|inputMethod_data
DECL|function|isActive
DECL|function|itemChange
DECL|function|itemIndexMethod
DECL|function|items
DECL|function|itemsBoundingRect
DECL|function|itemsBoundingRect_data
DECL|function|items_QPainterPath
DECL|function|items_QPainterPath_2
DECL|function|items_QPointF
DECL|function|items_QPointF_data
DECL|function|items_QPolygonF
DECL|function|items_QPolygonF_2
DECL|function|items_QRectF
DECL|function|items_QRectF_2
DECL|function|items_QRectF_2_data
DECL|function|mouseEventPropagation
DECL|function|mouseEventPropagation_doubleclick
DECL|function|mouseEventPropagation_focus
DECL|function|mouseEventPropagation_ignore
DECL|function|mouseEventPropagation_mouseMove
DECL|function|mouseGrabberItem
DECL|function|mouseMoveEvent
DECL|function|paint
DECL|function|paint
DECL|function|paint
DECL|function|paintEvent
DECL|function|polishItems
DECL|function|polishItems2
DECL|function|removeFullyTransparentItem
DECL|function|removeItem
DECL|function|render
DECL|function|renderItemsWithNegativeWidthOrHeight
DECL|function|render_data
DECL|function|sceneEvent
DECL|function|sceneEvent
DECL|function|sceneEvent
DECL|function|sceneEventFilter
DECL|function|sceneEventFilter
DECL|function|sceneRect
DECL|function|selectionChanged
DECL|function|selectionChanged2
DECL|function|sendEvent
DECL|function|setFocusItem
DECL|function|setFocusItem_inactive
DECL|function|siblingIndexAlwaysValid
DECL|function|sorting
DECL|function|sorting_data
DECL|function|stickyFocus
DECL|function|stickyFocus_data
DECL|function|storeLastEvent
DECL|function|style
DECL|function|tabFocus_emptyScene
DECL|function|tabFocus_sceneWithFocusWidgets
DECL|function|tabFocus_sceneWithFocusableItems
DECL|function|tabFocus_sceneWithNestedFocusWidgets
DECL|function|task139710_bspTreeCrash
DECL|function|task139782_containsItemBoundingRect
DECL|function|task160653_selectionChanged
DECL|function|task176178_itemIndexMethodBreaksSceneRect
DECL|function|task250680_childClip
DECL|function|taskQT657_paintIntoCacheWithTransparentParts
DECL|function|taskQTBUG_15977_renderWithDeviceCoordinateCache
DECL|function|taskQTBUG_16401_focusItem
DECL|function|taskQTBUG_5904_crashWithDeviceCoordinateCache
DECL|function|taskQTBUG_7863_paintIntoCacheWithTransparentParts
DECL|function|taskQT_3674_doNotCrash
DECL|function|timerEvent
DECL|function|update
DECL|function|update2
DECL|function|views
DECL|function|zeroScale
DECL|function|~ClearTestItem
DECL|function|~DndTester
DECL|macro|Q_CHECK_PAINTEVENTS
DECL|macro|Q_CHECK_PAINTEVENTS
DECL|member|_count
DECL|member|addChildrenInPolish
DECL|member|backTabs
DECL|member|changes
DECL|member|deleteChildrenInPolish
DECL|member|eventCalls
DECL|member|eventList
DECL|member|eventTypes
DECL|member|exposed
DECL|member|gotTimerEvent
DECL|member|ignoreMouse
DECL|member|ignoresDragEnter
DECL|member|ignoresDragMove
DECL|member|isHovered
DECL|member|items
DECL|member|lastEvent
DECL|member|mouseMovePoints
DECL|member|polished
DECL|member|queryCalls
DECL|member|receivedSceneEventFilters
DECL|member|receivedSceneEvents
DECL|member|repaints
DECL|member|spied
DECL|member|tabs
DECL|variable|randomX
DECL|variable|randomY
