DECL|function|cleanupTestCase
DECL|function|doPrint
DECL|function|initTestCase
DECL|function|pathUtils
DECL|function|print
DECL|function|proString
DECL|function|proStringList
DECL|function|quoteArgUnix
DECL|function|quoteArgUnix_data
DECL|function|quoteArgWin
DECL|function|quoteArgWin_data
