DECL|class|TestEdit
DECL|class|tst_QShortcut
DECL|enumerator|Ambiguous
DECL|enumerator|ClearAll
DECL|enumerator|Defined
DECL|enumerator|Defined
DECL|enumerator|Defined
DECL|enumerator|NoResult
DECL|enumerator|NoWidget
DECL|enumerator|SetupAccel
DECL|enumerator|Slot1Triggered
DECL|enumerator|Slot2Triggered
DECL|enumerator|Slot3Triggered
DECL|enumerator|Slot4Triggered
DECL|enumerator|Slot5Triggered
DECL|enumerator|Slot6Triggered
DECL|enumerator|Slot7Triggered
DECL|enumerator|TestAccel
DECL|enumerator|TriggerSlot1
DECL|enumerator|TriggerSlot2
DECL|enumerator|TriggerSlot3
DECL|enumerator|TriggerSlot4
DECL|enumerator|TriggerSlot5
DECL|enumerator|TriggerSlot6
DECL|enumerator|TriggerSlot7
DECL|enum|Action
DECL|enum|Result
DECL|enum|Widget
DECL|function|TestEdit
DECL|function|ambigSlot1
DECL|function|ambigSlot2
DECL|function|ambigSlot3
DECL|function|ambigSlot4
DECL|function|ambigSlot5
DECL|function|ambigSlot6
DECL|function|ambigSlot7
DECL|function|ambiguousItems
DECL|function|ambiguousRotation
DECL|function|cleanupTestCase
DECL|function|clearAllShortcuts
DECL|function|context
DECL|function|defElements
DECL|function|disabledItems
DECL|function|event
DECL|function|initTestCase
DECL|function|keypressConsumption
DECL|function|number
DECL|function|number_data
DECL|function|qt_metatype_id
DECL|function|qt_metatype_id
DECL|function|qt_metatype_id
DECL|function|sendKeyEvents
DECL|function|sendKeyEvents
DECL|function|setupShortcut
DECL|function|setupShortcut
DECL|function|setupShortcut
DECL|function|setupShortcut
DECL|function|shortcutDestroyed
DECL|function|slotTrig1
DECL|function|slotTrig2
DECL|function|slotTrig3
DECL|function|slotTrig4
DECL|function|slotTrig5
DECL|function|slotTrig6
DECL|function|slotTrig7
DECL|function|statusMessage
DECL|function|testElement
DECL|function|text
DECL|function|text_data
DECL|function|toButtons
DECL|function|tst_QShortcut
DECL|function|unicodeCompare
DECL|function|~tst_QShortcut
DECL|member|ambigResult
DECL|member|currentAction
DECL|member|currentResult
DECL|member|edit
DECL|member|mainW
DECL|member|sbText
DECL|member|shortcuts
DECL|struct|QMetaTypeId
DECL|struct|QMetaTypeId
DECL|struct|QMetaTypeId
