DECL|class|CreateDockWidgetDialog
DECL|class|DockWidgetAreaCornerFunctor
DECL|function|CreateDockWidgetDialog
DECL|function|DockWidgetAreaCornerFunctor
DECL|function|MainWindow
DECL|function|actionTriggered
DECL|function|addCornerAction
DECL|function|createDockWidget
DECL|function|destroyDockWidget
DECL|function|enteredObjectName
DECL|function|loadLayout
DECL|function|location
DECL|function|operator ()
DECL|function|saveLayout
DECL|function|setDockOptions
DECL|function|setupDockWidgets
DECL|function|setupMenuBar
DECL|function|setupToolBar
DECL|function|switchLayoutDirection
DECL|member|m_area
DECL|member|m_corner
DECL|member|m_location
DECL|member|m_mainWindow
DECL|member|m_objectName
DECL|variable|message
