DECL|function|ToolBar
DECL|function|addSpinBox
DECL|function|allow
DECL|function|allowBottom
DECL|function|allowLeft
DECL|function|allowRight
DECL|function|allowTop
DECL|function|changeMovable
DECL|function|enterEvent
DECL|function|genIcon
DECL|function|genIcon
DECL|function|insertToolBarBreak
DECL|function|leaveEvent
DECL|function|order
DECL|function|place
DECL|function|placeBottom
DECL|function|placeLeft
DECL|function|placeRight
DECL|function|placeTop
DECL|function|randomize
DECL|function|removeSpinBox
DECL|function|updateMenu
