DECL|class|tst_QRect
DECL|enumerator|EmptyQRect
DECL|enumerator|InvalidQRect
DECL|enumerator|LargestCoordQPoint
DECL|enumerator|LargestCoordQRect
DECL|enumerator|LargestQRect
DECL|enumerator|MaximumInt
DECL|enumerator|MiddleCoordQRect
DECL|enumerator|MiddleNegCoordQPoint
DECL|enumerator|MiddleNegativeInt
DECL|enumerator|MiddlePosCoordQPoint
DECL|enumerator|MiddlePositiveInt
DECL|enumerator|MiddleQRect
DECL|enumerator|MinimumInt
DECL|enumerator|NegXQPoint
DECL|enumerator|NegYQPoint
DECL|enumerator|NegativePointQRect
DECL|enumerator|NegativeQPoint
DECL|enumerator|NegativeSizeQRect
DECL|enumerator|NullQPoint
DECL|enumerator|NullQRect
DECL|enumerator|RandomInt
DECL|enumerator|RandomQPoint
DECL|enumerator|RandomQRect
DECL|enumerator|SmallestCoordQPoint
DECL|enumerator|SmallestCoordQRect
DECL|enumerator|SmallestQRect
DECL|enumerator|ZeroInt
DECL|enum|IntCases
DECL|enum|QPointCases
DECL|enum|QRectCases
DECL|function|bottom
DECL|function|bottomLeft
DECL|function|bottomLeft_data
DECL|function|bottomRight
DECL|function|bottomRight_data
DECL|function|bottom_data
DECL|function|center
DECL|function|center_data
DECL|function|containsPoint
DECL|function|containsPointF
DECL|function|containsPointF_data
DECL|function|containsPoint_data
DECL|function|containsRect
DECL|function|containsRectF
DECL|function|containsRectF_data
DECL|function|containsRect_data
DECL|function|getCoords
DECL|function|getCoords_data
DECL|function|getIntCase
DECL|function|getQPointCase
DECL|function|getQRectCase
DECL|function|getRect
DECL|function|getRect_data
DECL|function|intersectedRect
DECL|function|intersectedRectF
DECL|function|intersectedRectF_data
DECL|function|intersectedRect_data
DECL|function|intersectsRect
DECL|function|intersectsRectF
DECL|function|intersectsRectF_data
DECL|function|intersectsRect_data
DECL|function|isEmpty
DECL|function|isLarge
DECL|function|isNull
DECL|function|isNull_data
DECL|function|isValid
DECL|function|left
DECL|function|left_data
DECL|function|margins
DECL|function|moveBottom
DECL|function|moveBottomLeft
DECL|function|moveBottomRight
DECL|function|moveLeft
DECL|function|moveRight
DECL|function|moveTop
DECL|function|moveTopLeft
DECL|function|moveTopRight
DECL|function|newIsEmpty
DECL|function|newIsEmpty_data
DECL|function|newIsValid
DECL|function|newIsValid_data
DECL|function|newMoveBottom
DECL|function|newMoveBottomRight
DECL|function|newMoveBottomRight_data
DECL|function|newMoveBottom_data
DECL|function|newMoveLeft
DECL|function|newMoveLeft_data
DECL|function|newMoveRight
DECL|function|newMoveRight_data
DECL|function|newMoveTop
DECL|function|newMoveTopLeft
DECL|function|newMoveTopLeft_data
DECL|function|newMoveTop_data
DECL|function|newSetBottomLeft
DECL|function|newSetBottomLeft_data
DECL|function|newSetBottomRight
DECL|function|newSetBottomRight_data
DECL|function|newSetTopLeft
DECL|function|newSetTopLeft_data
DECL|function|newSetTopRight
DECL|function|newSetTopRight_data
DECL|function|normalized
DECL|function|normalized_data
DECL|function|operator_amp
DECL|function|operator_amp_eq
DECL|function|right
DECL|function|right_data
DECL|function|setBottom
DECL|function|setBottomLeft
DECL|function|setBottomRight
DECL|function|setBottom_data
DECL|function|setLeft
DECL|function|setLeft_data
DECL|function|setRight
DECL|function|setRight_data
DECL|function|setTop
DECL|function|setTopLeft
DECL|function|setTopRight
DECL|function|setTop_data
DECL|function|setWidthHeight
DECL|function|setWidthHeight_data
DECL|function|smallRects
DECL|function|testAdjust
DECL|function|testAdjust_data
DECL|function|top
DECL|function|topLeft
DECL|function|topLeft_data
DECL|function|topRight
DECL|function|topRight_data
DECL|function|top_data
DECL|function|translate
DECL|function|translate_data
DECL|function|unitedRect
DECL|function|unitedRectF
DECL|function|unitedRectF_data
DECL|function|unitedRect_data
DECL|function|x
DECL|function|x_data
DECL|function|y
DECL|function|y_data
DECL|macro|LARGE
