DECL|class|FileSystemWatcherSpy
DECL|class|SignalReceiver
DECL|class|SomeSingleton
DECL|class|tst_QFileSystemWatcher
DECL|enumerator|SpyOnDirectoryChanged
DECL|enumerator|SpyOnFileChanged
DECL|enum|Mode
DECL|function|Entry
DECL|function|Entry
DECL|function|FileSystemWatcherSpy
DECL|function|QTBUG2331
DECL|function|QTBUG2331_data
DECL|function|SignalReceiver
DECL|function|SomeSingleton
DECL|function|addPath
DECL|function|addPaths
DECL|function|basicTest
DECL|function|basicTest_data
DECL|function|bla
DECL|function|clear
DECL|function|count
DECL|function|destroyAfterQCoreApplication
DECL|function|fileChanged
DECL|function|msgFileOperationFailed
DECL|function|nonExistingFile
DECL|function|receivedFilesMessage
DECL|function|removeFileAndUnWatch
DECL|function|removePath
DECL|function|removePaths
DECL|function|removePathsFilesInSameDirectory
DECL|function|signalsEmittedAfterFileMoved
DECL|function|spySlot
DECL|function|tst_QFileSystemWatcher
DECL|function|watchDirectory
DECL|function|watchDirectory_data
DECL|function|watchFileAndItsDirectory
DECL|function|watchFileAndItsDirectory_data
DECL|member|added
DECL|member|mFsWatcher
DECL|member|m_elapsedTimer
DECL|member|m_entries
DECL|member|m_tempDirPattern
DECL|member|moveDestination
DECL|member|moveSrcDir
DECL|member|path
DECL|member|timeStamp
DECL|member|watcher
DECL|struct|Entry
