DECL|class|PaintEngine
DECL|class|QTBUG31330_PaintDevice
DECL|class|tst_QTextTable
DECL|function|PaintEngine
DECL|function|QTBUG11282_insertBeforeMergedEnding
DECL|function|QTBUG11282_insertBeforeMergedEnding_data
DECL|function|QTBUG22011_insertBeforeRowSpan
DECL|function|QTBUG31330_PaintDevice
DECL|function|QTBUG31330_renderBackground
DECL|function|begin
DECL|function|blocksForTableShouldHaveEmptyFormat
DECL|function|cleanup
DECL|function|create2x2Table
DECL|function|create4x4Table
DECL|function|createTable
DECL|function|cursorPositioning
DECL|function|deleteInTable
DECL|function|drawPixmap
DECL|function|drawRects
DECL|function|drawRects
DECL|function|end
DECL|function|init
DECL|function|insertRows
DECL|function|mergeAndInsert
DECL|function|mergeCells
DECL|function|metric
DECL|function|multiBlockCells
DECL|function|newPage
DECL|function|paintEngine
DECL|function|removeColumns1
DECL|function|removeColumns2
DECL|function|removeColumns3
DECL|function|removeColumns4
DECL|function|removeColumns5
DECL|function|removeColumnsInTableWithMergedRows
DECL|function|removeRows1
DECL|function|removeRows2
DECL|function|removeRows3
DECL|function|removeRows4
DECL|function|removeRows5
DECL|function|removeTableByRemoveColumns
DECL|function|removeTableByRemoveRows
DECL|function|rowAt
DECL|function|rowAtWithSpans
DECL|function|setCellFormat
DECL|function|spans
DECL|function|splitCells
DECL|function|tableManager_removeCell
DECL|function|tableManager_undo
DECL|function|tableShrinking
DECL|function|tst_QTextTable
DECL|function|type
DECL|function|updateState
DECL|function|variousModifications2
DECL|function|variousTableModifications
DECL|member|cursor
DECL|member|doc
DECL|member|engine
DECL|member|pages
DECL|member|rects
DECL|typedef|IntList
