DECL|class|tst_QHostAddress
DECL|function|assignment
DECL|function|cleanup
DECL|function|compare
DECL|function|compare_data
DECL|function|constructor_QString
DECL|function|constructor_QString_data
DECL|function|hashKey
DECL|function|init
DECL|function|isInSubnet
DECL|function|isInSubnet_data
DECL|function|parseSubnet
DECL|function|parseSubnet_data
DECL|function|scopeId
DECL|function|setAddress_QString
DECL|function|setAddress_QString_data
DECL|function|specialAddresses
DECL|function|specialAddresses_data
DECL|function|streaming
DECL|function|streaming_data
DECL|function|toString
DECL|function|tst_QHostAddress
DECL|function|~tst_QHostAddress
DECL|namespace|QTest
