DECL|class|QtActivity
DECL|field|m_debuggerProcess
DECL|field|m_fullScreen
DECL|field|m_id
DECL|field|m_lastChar
DECL|field|m_metaState
DECL|field|m_quitApp
DECL|field|m_started
DECL|field|m_surface
DECL|field|m_usesGL
DECL|field|softwareKeyboardIsVisible
DECL|method|dispatchKeyEvent
DECL|method|getQtSurface
DECL|method|hideSoftwareKeyboard
DECL|method|loadQtLibs
DECL|method|onConfigurationChanged
DECL|method|onCreate
DECL|method|onDestroy
DECL|method|onKeyDown
DECL|method|onKeyUp
DECL|method|onRestoreInstanceState
DECL|method|onResume
DECL|method|onRetainNonConfigurationInstance
DECL|method|onSaveInstanceState
DECL|method|redrawWindow
DECL|method|resetSoftwareKeyboard
DECL|method|setFullScreen
DECL|method|showSoftwareKeyboard
DECL|method|startApp
DECL|package|org.qtproject.qt5.android
