DECL|function|ScribbleArea
DECL|function|clearImage
DECL|function|drawLineTo
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|openImage
DECL|function|paintEvent
DECL|function|print
DECL|function|resizeEvent
DECL|function|resizeImage
DECL|function|saveImage
DECL|function|setPenColor
DECL|function|setPenWidth
