DECL|function|_q_adjustRect
DECL|function|adjustedItemBoundingRect
DECL|function|adjustedItemEffectiveBoundingRect
DECL|macro|QGRAPHICSSCENE_P_H
DECL|variable|QGraphicsSceneIndex
DECL|variable|QGraphicsView
DECL|variable|QGraphicsWidget
