DECL|class|QGraphicsRotationPrivate
DECL|class|QGraphicsScalePrivate
DECL|function|QGraphicsRotation
DECL|function|QGraphicsRotationPrivate
DECL|function|QGraphicsScale
DECL|function|QGraphicsScalePrivate
DECL|function|QGraphicsTransform
DECL|function|QGraphicsTransform
DECL|function|angle
DECL|function|applyTo
DECL|function|applyTo
DECL|function|axis
DECL|function|origin
DECL|function|origin
DECL|function|setAngle
DECL|function|setAxis
DECL|function|setAxis
DECL|function|setItem
DECL|function|setOrigin
DECL|function|setOrigin
DECL|function|setXScale
DECL|function|setYScale
DECL|function|setZScale
DECL|function|update
DECL|function|updateItem
DECL|function|xScale
DECL|function|yScale
DECL|function|zScale
DECL|function|~QGraphicsRotation
DECL|function|~QGraphicsScale
DECL|function|~QGraphicsTransform
DECL|member|angle
DECL|member|axis
DECL|member|origin
DECL|member|origin
DECL|member|xScale
DECL|member|yScale
DECL|member|zScale
