DECL|enumerator|Independent
DECL|enumerator|Master
DECL|enumerator|Normal
DECL|enumerator|Normal
DECL|enumerator|Pair
DECL|enumerator|Parallel
DECL|enumerator|Sequential
DECL|enumerator|Slave
DECL|enum|Dependency
DECL|enum|Type
DECL|enum|Type
DECL|function|AnchorData
DECL|function|AnchorVertex
DECL|function|AnchorVertex
DECL|function|AnchorVertexPair
DECL|function|ParallelAnchorData
DECL|function|m_edges
DECL|function|secondForward
DECL|function|toString
DECL|function|toString
DECL|function|updateChildrenSizes
DECL|macro|QGRAPHICSANCHORLAYOUT_P_H
DECL|member|dependency
DECL|member|distance
DECL|member|firstEdge
DECL|member|from
DECL|member|graphicsAnchor
DECL|member|isCenterAnchor
DECL|member|isLayoutAnchor
DECL|member|item
DECL|member|m_children
DECL|member|m_edge
DECL|member|m_edges
DECL|member|m_first
DECL|member|m_firstAnchors
DECL|member|m_firstConstraints
DECL|member|m_item
DECL|member|m_removedAnchor
DECL|member|m_second
DECL|member|m_secondAnchors
DECL|member|m_secondConstraints
DECL|member|m_type
DECL|member|maxPrefSize
DECL|member|maxSize
DECL|member|minPrefSize
DECL|member|minSize
DECL|member|name
DECL|member|orientation
DECL|member|prefSize
DECL|member|secondEdge
DECL|member|sizeAtMaximum
DECL|member|sizeAtMinimum
DECL|member|sizeAtPreferred
DECL|member|to
DECL|member|type
DECL|struct|AnchorData
DECL|struct|AnchorData
DECL|struct|AnchorVertex
DECL|struct|AnchorVertex
DECL|struct|QSimplexVariable
DECL|variable|QGraphicsAnchorLayoutPrivate
