DECL|function|QGraphicsAnchor
DECL|function|QGraphicsAnchorLayout
DECL|function|addAnchor
DECL|function|addAnchors
DECL|function|addCornerAnchors
DECL|function|anchor
DECL|function|count
DECL|function|horizontalSpacing
DECL|function|invalidate
DECL|function|itemAt
DECL|function|removeAt
DECL|function|setGeometry
DECL|function|setHorizontalSpacing
DECL|function|setSizePolicy
DECL|function|setSpacing
DECL|function|setSpacing
DECL|function|setVerticalSpacing
DECL|function|sizeHint
DECL|function|sizePolicy
DECL|function|spacing
DECL|function|unsetSpacing
DECL|function|verticalSpacing
DECL|function|~QGraphicsAnchor
DECL|function|~QGraphicsAnchorLayout
