DECL|enumerator|Equal
DECL|enumerator|LessOrEqual
DECL|enumerator|MoreOrEqual
DECL|enum|Ratio
DECL|function|QSimplexConstraint
DECL|function|QSimplexVariable
DECL|function|isSatisfied
DECL|function|setValueAt
DECL|function|toString
DECL|function|valueAt
DECL|macro|QSIMPLEX_P_H
DECL|member|QSimplexVariable
DECL|member|QSimplexVariable
DECL|member|artificial
DECL|member|constant
DECL|member|helper
DECL|member|index
DECL|member|ratio
DECL|member|result
DECL|member|variables
DECL|struct|QSimplexConstraint
DECL|struct|QSimplexVariable
