DECL|class|tst_QImageWriter
DECL|function|cleanup
DECL|function|equalImageContents
DECL|function|getSetCheck
DECL|function|init
DECL|function|initTestCase
DECL|function|initializePadding
DECL|function|largeTiff
DECL|function|readWriteNonDestructive
DECL|function|readWriteNonDestructive_data
DECL|function|resolution
DECL|function|resolution_data
DECL|function|saveToTemporaryFile
DECL|function|saveWithNoFormat
DECL|function|saveWithNoFormat_data
DECL|function|supportedFormats
DECL|function|supportsOption
DECL|function|supportsOption_data
DECL|function|tst_QImageWriter
DECL|function|writeImage
DECL|function|writeImage2
DECL|function|writeImage2_data
DECL|function|writeImage_data
DECL|function|writeToInvalidDevice
DECL|function|~tst_QImageWriter
DECL|member|prefix
DECL|typedef|QIntList
DECL|typedef|QStringMap
