DECL|function|QGraphicsItemPaintInfo
DECL|function|TransformData
DECL|function|computedFullTransform
DECL|function|ensureSortedChildren
DECL|function|insertionOrder
DECL|function|markParentDirty
DECL|function|qt_closestItemFirst
DECL|function|qt_closestItemLast
DECL|function|qt_closestLeaf
DECL|function|qt_notclosestLeaf
DECL|function|transformToParent
DECL|macro|QDECLARATIVELISTPROPERTY
DECL|macro|QGRAPHICSITEM_P_H
DECL|member|drawItem
DECL|member|effectTransform
DECL|member|exposedRegion
DECL|member|graphicsTransforms
DECL|member|onlyTransform
DECL|member|opacity
DECL|member|option
DECL|member|painter
DECL|member|rotation
DECL|member|scale
DECL|member|transform
DECL|member|transformPtr
DECL|member|viewTransform
DECL|member|wasDirtySceneTransform
DECL|member|widget
DECL|member|xOrigin
DECL|member|yOrigin
DECL|struct|QGraphicsItemPaintInfo
DECL|struct|TransformData
DECL|variable|QGraphicsItemPrivate
