DECL|enumerator|Bottom
DECL|enumerator|Hor
DECL|enumerator|HorizontalConstraint
DECL|enumerator|Left
DECL|enumerator|MaximumSize
DECL|enumerator|MinimumSize
DECL|enumerator|NOrientations
DECL|enumerator|NSizes
DECL|enumerator|NoConstraint
DECL|enumerator|PreferredSize
DECL|enumerator|Right
DECL|enumerator|Top
DECL|enumerator|UnfeasibleConstraint
DECL|enumerator|UnknownConstraint
DECL|enumerator|Ver
DECL|enumerator|VerticalConstraint
DECL|enum|LayoutSide
DECL|function|operator
DECL|macro|QGRIDLAYOUTENGINE_P_H
DECL|typedef|MultiCellMap
DECL|variable|QGraphicsLayoutItem
DECL|variable|QGridLayoutEngine
DECL|variable|QGridLayoutRowInfo
DECL|variable|QStyle
DECL|variable|QWidget
