DECL|function|QRfbHextileEncoder
DECL|function|QVNCClientCursor
DECL|function|QVNCCursor
DECL|function|QVNCDirtyMap
DECL|function|QVNCScreen
DECL|function|QVNCScreenPrivate
DECL|function|QVNCServer
DECL|function|QVNCServer
DECL|function|beginRect
DECL|function|blendCursor
DECL|function|checkUpdate
DECL|function|clientCutText
DECL|function|configure
DECL|function|connect
DECL|function|convertPixels
DECL|function|dirty
DECL|function|discardClient
DECL|function|disconnect
DECL|function|endRect
DECL|function|frameBufferUpdateRequest
DECL|function|getDisplayId
DECL|function|hide
DECL|function|init
DECL|function|initDevice
DECL|function|keyEvent
DECL|function|move
DECL|function|newConnection
DECL|function|next
DECL|function|pixelConversionNeeded
DECL|function|pointerEvent
DECL|function|read
DECL|function|read
DECL|function|read
DECL|function|read
DECL|function|read
DECL|function|read
DECL|function|read
DECL|function|read
DECL|function|read
DECL|function|read
DECL|function|read
DECL|function|readClient
DECL|function|reset
DECL|function|screenImage
DECL|function|set
DECL|function|set
DECL|function|setClean
DECL|function|setColor
DECL|function|setDirty
DECL|function|setDirty
DECL|function|setDirty
DECL|function|setDirty
DECL|function|setDirty
DECL|function|setEncodings
DECL|function|setName
DECL|function|setPixelFormat
DECL|function|show
DECL|function|shutdownDevice
DECL|function|swapBytes
DECL|function|write
DECL|function|write
DECL|function|write
DECL|function|write
DECL|function|write
DECL|function|write
DECL|function|write
DECL|function|write
DECL|function|write
DECL|function|~QVNCClientCursor
DECL|function|~QVNCCursor
DECL|function|~QVNCDirtyMap
DECL|function|~QVNCScreen
DECL|function|~QVNCScreenPrivate
DECL|function|~QVNCServer
DECL|member|keycode
DECL|member|keysym
DECL|variable|keyMap
