DECL|class|EventReportWidget
DECL|enumerator|TabletButtonPress
DECL|enumerator|TabletButtonRelease
DECL|enumerator|TabletMove
DECL|enum|TabletPointType
DECL|function|EventReportWidget
DECL|function|TabletPoint
DECL|function|clearPoints
DECL|function|main
DECL|function|mouseDoubleClickEvent
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|outputMouseEvent
DECL|function|paintEvent
DECL|function|tabletEvent
DECL|function|timerEvent
DECL|member|angle
DECL|member|button
DECL|member|m_lastButton
DECL|member|m_lastIsMouseMove
DECL|member|m_lastIsTabletMove
DECL|member|m_paintEventCount
DECL|member|m_points
DECL|member|m_tabletMoveCount
DECL|member|pos
DECL|member|pressure
DECL|member|ptype
DECL|member|type
DECL|struct|TabletPoint
