DECL|class|EventSpy
DECL|class|MyTextEdit
DECL|class|tst_QMdiSubWindow
DECL|function|EventSpy
DECL|function|MyTextEdit
DECL|function|changeFocusWithTab
DECL|function|clear
DECL|function|closeEvent
DECL|function|closeEvent
DECL|function|closeOnDoubleClick
DECL|function|count
DECL|function|defaultSizeGrip
DECL|function|emittingOfSignals
DECL|function|emittingOfSignals_data
DECL|function|eventFilter
DECL|function|explicitlyHiddenWidget
DECL|function|fixedMinMaxSize
DECL|function|hideAndShow
DECL|function|initTestCase
DECL|function|keepWindowMaximizedState
DECL|function|mainWindowSupport
DECL|function|mdiArea
DECL|function|minimumSize
DECL|function|minimumSizeHint
DECL|function|mouseDoubleClick
DECL|function|replaceMenuBarWhileMaximized
DECL|function|resizeEvents
DECL|function|resizeEvents_data
DECL|function|resizeTimer
DECL|function|restoreFocus
DECL|function|sendMouseDoubleClick
DECL|function|sendMouseMove
DECL|function|sendMousePress
DECL|function|sendMouseRelease
DECL|function|setAcceptClose
DECL|function|setFont
DECL|function|setOpaqueResizeAndMove
DECL|function|setOpaqueResizeAndMove_data
DECL|function|setSystemMenu
DECL|function|setWidget
DECL|function|setWindowFlags
DECL|function|setWindowFlags_data
DECL|function|setWindowState
DECL|function|setWindowState_data
DECL|function|setWindowTitle
DECL|function|showNormal
DECL|function|showNormal_data
DECL|function|showShaded
DECL|function|sizeHint
DECL|function|styleChange
DECL|function|tabAllWidgets
DECL|function|task_182852
DECL|function|task_188849
DECL|function|task_226929
DECL|function|task_233197
DECL|function|triggerSignal
DECL|member|_count
DECL|member|acceptClose
DECL|member|eventToSpy
DECL|variable|DialogWindowFlags
DECL|variable|StandardWindowFlags
DECL|variable|WindowFlags
DECL|variable|WindowState
DECL|variable|WindowStates
DECL|variable|WindowType
