DECL|function|MainWindow
DECL|function|about
DECL|function|activeMdiChild
DECL|function|closeEvent
DECL|function|copy
DECL|function|createActions
DECL|function|createMdiChild
DECL|function|createMenus
DECL|function|createStatusBar
DECL|function|createToolBars
DECL|function|cut
DECL|function|findMdiChild
DECL|function|newFile
DECL|function|open
DECL|function|paste
DECL|function|readSettings
DECL|function|save
DECL|function|saveAs
DECL|function|setActiveSubWindow
DECL|function|switchLayoutDirection
DECL|function|updateMenus
DECL|function|updateWindowMenu
DECL|function|writeSettings
