DECL|class|MyScrollArea
DECL|function|MyScrollArea
DECL|function|main
DECL|function|resizeEvent
DECL|function|scrollContentsBy
DECL|function|setWidget
DECL|function|updateArea
DECL|function|updateWidgetPosition
DECL|member|widget
