DECL|function|paintEvent
DECL|function|paintEvent
DECL|function|paintEvent
DECL|function|rotate
DECL|variable|GL_COLOR_BUFFER_BIT
DECL|variable|GL_SCISSOR_TEST
DECL|variable|GL_SCISSOR_TEST
DECL|variable|boundingRect
DECL|variable|font
DECL|variable|path
DECL|variable|pen
DECL|variable|picture
DECL|variable|points
DECL|variable|points
DECL|variable|points
DECL|variable|rectangle
DECL|variable|spanAngle
DECL|variable|spanAngle
DECL|variable|spanAngle
DECL|variable|startAngle
DECL|variable|startAngle
DECL|variable|startAngle
