DECL|function|QXlibShmImageInfo
DECL|function|QXlibWindowSurface
DECL|function|beginPaint
DECL|function|bufferSize
DECL|function|destroy
DECL|function|endPaint
DECL|function|flush
DECL|function|paintDevice
DECL|function|resizeBuffer
DECL|function|resizeShmImage
DECL|function|scroll
DECL|function|~QXlibShmImageInfo
DECL|function|~QXlibWindowSurface
DECL|member|display
DECL|member|image
DECL|member|shminfo
DECL|struct|QXlibShmImageInfo
