DECL|function|QXlibWindow
DECL|function|correctColorBuffers
DECL|function|createGC
DECL|function|doSizeHints
DECL|function|getMWMHints
DECL|function|getNetWmState
DECL|function|glContext
DECL|function|graphicsContext
DECL|function|handleCloseEvent
DECL|function|handleEnterEvent
DECL|function|handleFocusInEvent
DECL|function|handleFocusOutEvent
DECL|function|handleLeaveEvent
DECL|function|handleMouseEvent
DECL|function|isTransient
DECL|function|lower
DECL|function|mousePressEvent
DECL|function|paintEvent
DECL|function|raise
DECL|function|requestActivateWindow
DECL|function|resizeEvent
DECL|function|setCursor
DECL|function|setGeometry
DECL|function|setMWMHints
DECL|function|setParent
DECL|function|setVisible
DECL|function|setWindowFlags
DECL|function|setWindowTitle
DECL|function|translateMouseButtons
DECL|function|winId
DECL|function|windowFlags
DECL|function|xWindow
DECL|function|~QXlibWindow
