DECL|enumerator|XCursorShape
DECL|enumerator|XFocusIn
DECL|enumerator|XFocusOut
DECL|enumerator|XGrayScale
DECL|enumerator|XKeyPress
DECL|enumerator|XKeyRelease
DECL|enumerator|XNone
DECL|enumerator|XRevertToParent
DECL|macro|CursorShape
DECL|macro|FocusIn
DECL|macro|FocusOut
DECL|macro|FontChange
DECL|macro|GrayScale
DECL|macro|KeyPress
DECL|macro|KeyRelease
DECL|macro|None
DECL|macro|QTESTLITESTATICINFO_H
DECL|macro|RevertToParent
DECL|macro|X11R4
DECL|macro|X11R4
DECL|macro|XRegisterIMInstantiateCallback
DECL|macro|XRegisterIMInstantiateCallback
DECL|macro|XSetIMValues
DECL|macro|XSetIMValues
DECL|macro|XShapeCombineMask
DECL|macro|XShapeCombineRegion
DECL|macro|XUnregisterIMInstantiateCallback
DECL|macro|XUnregisterIMInstantiateCallback
DECL|macro|getpid
DECL|macro|index
DECL|macro|open
DECL|macro|rindex
DECL|typedef|PtrXCloseDevice
DECL|typedef|PtrXFixesQueryExtension
DECL|typedef|PtrXFixesQueryVersion
DECL|typedef|PtrXFixesSelectSelectionInput
DECL|typedef|PtrXFixesSetCursorName
DECL|typedef|PtrXFreeDeviceList
DECL|typedef|PtrXListInputDevices
DECL|typedef|PtrXOpenDevice
DECL|typedef|PtrXRRQueryExtension
DECL|typedef|PtrXRRRootToScreen
DECL|typedef|PtrXRRSelectInput
DECL|typedef|PtrXRRUpdateConfiguration
DECL|typedef|PtrXSelectExtensionEvent
DECL|typedef|PtrXcursorLibraryLoadCursor
DECL|typedef|PtrXineramaIsActive
DECL|typedef|PtrXineramaQueryExtension
DECL|typedef|PtrXineramaQueryScreens
DECL|typedef|XPointer
