DECL|class|QXlibClipboardMime
DECL|function|QXlibClipboard
DECL|function|QXlibClipboardMime
DECL|function|clipboardReadIncrementalProperty
DECL|function|clipboardReadProperty
DECL|function|empty
DECL|function|formats_sys
DECL|function|getDataInFormat
DECL|function|handleSelectionRequest
DECL|function|hasFormat_sys
DECL|function|maxSelectionIncr
DECL|function|mimeData
DECL|function|owner
DECL|function|requestor
DECL|function|retrieveData_sys
DECL|function|screen
DECL|function|sendSelection
DECL|function|sendTargetsSelection
DECL|function|setMimeData
DECL|function|setOwner
DECL|function|setRequestor
DECL|function|supportsMode
DECL|member|clipboard_timeout
DECL|member|formatList
DECL|member|format_atoms
DECL|member|m_clipboard
DECL|member|modeAtom
