DECL|class|MyClass
DECL|class|tst_QMap
DECL|function|MyClass
DECL|function|MyClass
DECL|function|MyClass
DECL|function|beginEnd
DECL|function|checkMostLeftNode
DECL|function|clear
DECL|function|constFind
DECL|function|const_
DECL|function|const_shared_null
DECL|function|contains
DECL|function|count
DECL|function|empty
DECL|function|equal_range
DECL|function|find
DECL|function|init
DECL|function|insert
DECL|function|iterators
DECL|function|key
DECL|function|keys_values_uniqueKeys
DECL|function|lowerUpperBound
DECL|function|mergeCompare
DECL|function|operator <<
DECL|function|operator =
DECL|function|operator_eq
DECL|function|qmultimap_specific
DECL|function|sanityCheckTree
DECL|function|setSharable
DECL|function|swap
DECL|function|take
DECL|function|~MyClass
DECL|macro|QT_STRICT_ITERATORS
DECL|member|count
DECL|member|count
DECL|member|str
DECL|typedef|MyMap
DECL|typedef|StringMap
