DECL|function|GLWidget
DECL|function|cleanup
DECL|function|initializeGL
DECL|function|minimumSizeHint
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|paintGL
DECL|function|qNormalizeAngle
DECL|function|resizeGL
DECL|function|setXRotation
DECL|function|setYRotation
DECL|function|setZRotation
DECL|function|setupVertexAttribs
DECL|function|sizeHint
DECL|function|~GLWidget
DECL|variable|fragmentShaderSource
DECL|variable|fragmentShaderSourceCore
DECL|variable|vertexShaderSource
DECL|variable|vertexShaderSourceCore
