DECL|class|CounterButton
DECL|class|QtTestAccessibleWidget
DECL|class|QtTestAccessibleWidgetIface
DECL|class|QtTestDelegate
DECL|class|QtTestTableModel
DECL|class|tst_QAccessibility
DECL|function|CounterButton
DECL|function|IsValidCEPlatform
DECL|function|QtTestAccessibleWidget
DECL|function|QtTestAccessibleWidgetIface
DECL|function|QtTestDelegate
DECL|function|QtTestTableModel
DECL|function|abstractScrollAreaTest
DECL|function|accelerators
DECL|function|accessibleName
DECL|function|actionTest
DECL|function|applicationTest
DECL|function|buttonTest
DECL|function|calendarWidgetTest
DECL|function|cleanup
DECL|function|cleanupTestCase
DECL|function|columnCount
DECL|function|comboBoxTest
DECL|function|createWidgets
DECL|function|customWidget
DECL|function|data
DECL|function|deletedWidget
DECL|function|dialTest
DECL|function|dialogButtonBoxTest
DECL|function|dockWidgetTest
DECL|function|doubleSpinBoxTest
DECL|function|eventName
DECL|function|eventTest
DECL|function|hideShowTest
DECL|function|ifaceFactory
DECL|function|incClickCount
DECL|function|indexOfChild
DECL|function|init
DECL|function|initTestCase
DECL|function|labelTest
DECL|function|lineEditTest
DECL|function|listViewTest
DECL|function|mainWindowTest
DECL|function|mdiAreaTest
DECL|function|mdiSubWindowTest
DECL|function|menuTest
DECL|function|navigateCovered
DECL|function|navigateGeometric
DECL|function|navigateHierarchy
DECL|function|onClicked
DECL|function|removeAllColumns
DECL|function|removeAllRows
DECL|function|removeLastColumn
DECL|function|removeLastRow
DECL|function|reset
DECL|function|rowCount
DECL|function|rubberBandTest
DECL|function|scrollAreaTest
DECL|function|scrollBarTest
DECL|function|sizeHint
DECL|function|sliderTest
DECL|function|spinBoxTest
DECL|function|state
DECL|function|tabTest
DECL|function|tabWidgetTest
DECL|function|table2ListTest
DECL|function|table2TableTest
DECL|function|table2TreeTest
DECL|function|tableViewTest
DECL|function|tableWidgetTest
DECL|function|text
DECL|function|textAttributes
DECL|function|textBrowserTest
DECL|function|textEditTest
DECL|function|treeWidgetTest
DECL|function|tst_QAccessibility
DECL|function|verifyChild
DECL|function|verifyHierarchy
DECL|function|workspaceTest
DECL|function|~tst_QAccessibility
DECL|macro|EXPECT
DECL|macro|QSETCOMPARE
DECL|macro|SPI_GETPLATFORMTYPE
DECL|macro|interface
DECL|member|clickCount
DECL|member|click_count
DECL|member|column_count
DECL|member|row_count
DECL|variable|Q_PI
