DECL|function|QAbstractTransition
DECL|function|QAbstractTransition
DECL|function|QAbstractTransitionPrivate
DECL|function|addAnimation
DECL|function|animations
DECL|function|callEventTest
DECL|function|callOnTransition
DECL|function|emitTriggered
DECL|function|event
DECL|function|machine
DECL|function|machine
DECL|function|removeAnimation
DECL|function|setTargetState
DECL|function|setTargetStates
DECL|function|setTransitionType
DECL|function|sourceState
DECL|function|sourceState
DECL|function|targetState
DECL|function|targetStates
DECL|function|transitionType
DECL|function|~QAbstractTransition
