DECL|function|QHistoryState
DECL|function|QHistoryState
DECL|function|QHistoryStatePrivate
DECL|function|defaultState
DECL|function|event
DECL|function|get
DECL|function|historyType
DECL|function|onEntry
DECL|function|onExit
DECL|function|setDefaultState
DECL|function|setHistoryType
DECL|function|~QHistoryState
