DECL|function|QAndroidBearerEngine
DECL|function|bytesReceived
DECL|function|bytesWritten
DECL|function|capabilities
DECL|function|connectToId
DECL|function|createSessionBackend
DECL|function|defaultConfiguration
DECL|function|disconnectFromId
DECL|function|getBearerType
DECL|function|getInterfaceFromId
DECL|function|hasIdentifier
DECL|function|initialize
DECL|function|isMobile
DECL|function|networkConfType
DECL|function|requestUpdate
DECL|function|requiresPolling
DECL|function|sessionStateForId
DECL|function|startTime
DECL|function|updateConfigurations
DECL|function|~QAndroidBearerEngine
