DECL|class|NativeFileCreator
DECL|class|tst_QFileInfo
DECL|function|IsUserAdmin
DECL|function|NativeFileCreator
DECL|function|absFilePath
DECL|function|absFilePath_data
DECL|function|absolutePath
DECL|function|absolutePath_data
DECL|function|baseName
DECL|function|baseName_data
DECL|function|brokenShortcut
DECL|function|bundleName
DECL|function|bundleName_data
DECL|function|canonicalFilePath
DECL|function|canonicalPath
DECL|function|cleanupTestCase
DECL|function|compare
DECL|function|compare_data
DECL|function|completeBaseName
DECL|function|completeBaseName_data
DECL|function|completeSuffix
DECL|function|completeSuffix_data
DECL|function|consistent
DECL|function|consistent_data
DECL|function|copy
DECL|function|detachingOperations
DECL|function|dir
DECL|function|dir_data
DECL|function|equalOperator
DECL|function|equalOperatorWithDifferentSlashes
DECL|function|error
DECL|function|exists
DECL|function|exists_data
DECL|function|fileName
DECL|function|fileName_data
DECL|function|fileTimes
DECL|function|fileTimes_data
DECL|function|fileTimes_oldFile
DECL|function|getPrivate
DECL|function|getSetCheck
DECL|function|group
DECL|function|initTestCase
DECL|function|invalidState
DECL|function|isBundle
DECL|function|isBundle_data
DECL|function|isDir
DECL|function|isDir_data
DECL|function|isExecutable
DECL|function|isFile
DECL|function|isFile_data
DECL|function|isHidden
DECL|function|isHiddenFromFinder
DECL|function|isHidden_data
DECL|function|isNativePath
DECL|function|isNativePath_data
DECL|function|isRoot
DECL|function|isRoot_data
DECL|function|isSymLink
DECL|function|isSymLink_data
DECL|function|isWritable
DECL|function|nonExistingFileDates
DECL|function|notEqualOperator
DECL|function|ntfsJunctionPointsAndSymlinks
DECL|function|ntfsJunctionPointsAndSymlinks_data
DECL|function|owner
DECL|function|permission
DECL|function|permission_data
DECL|function|refresh
DECL|function|size
DECL|function|size_data
DECL|function|suffix
DECL|function|suffix_data
DECL|function|systemFiles
DECL|function|testDecomposedUnicodeNames
DECL|function|testDecomposedUnicodeNames_data
DECL|function|tst_QFileInfo
DECL|function|~NativeFileCreator
DECL|member|m_currentDir
DECL|member|m_dir
DECL|member|m_error
DECL|member|m_filePath
DECL|member|m_resourcesDir
DECL|member|m_sourceFile
