DECL|class|tst_QActionGroup
DECL|function|cleanup
DECL|function|enabledPropagation
DECL|function|exclusive
DECL|function|separators
DECL|function|testActionInTwoQActionGroup
DECL|function|unCheckCurrentAction
DECL|function|visiblePropagation
