DECL|macro|QPLATFORMDEFS_H
DECL|macro|QT_AOUT_UNDERSCORE
DECL|macro|QT_OPEN_LARGEFILE
DECL|macro|QT_OPEN_LARGEFILE
DECL|macro|QT_SNPRINTF
DECL|macro|QT_VSNPRINTF
DECL|macro|_POSIX_THREAD_SAFE_FUNCTIONS
