DECL|class|QWindowsEnumerate
DECL|function|AddRef
DECL|function|AddRef
DECL|function|Clone
DECL|function|ContextSensitiveHelp
DECL|function|GetIDsOfNames
DECL|function|GetTypeInfo
DECL|function|GetTypeInfoCount
DECL|function|GetWindow
DECL|function|IIDToString
DECL|function|Invoke
DECL|function|Next
DECL|function|QWindowsEnumerate
DECL|function|QueryInterface
DECL|function|QueryInterface
DECL|function|Release
DECL|function|Release
DECL|function|Reset
DECL|function|Skip
DECL|function|accDoDefaultAction
DECL|function|accHitTest
DECL|function|accLocation
DECL|function|accNavigate
DECL|function|accSelect
DECL|function|accessibleDebugClientCalls_helper
DECL|function|debug_accessibility
DECL|function|get_accChild
DECL|function|get_accChildCount
DECL|function|get_accDefaultAction
DECL|function|get_accDescription
DECL|function|get_accFocus
DECL|function|get_accHelp
DECL|function|get_accHelpTopic
DECL|function|get_accKeyboardShortcut
DECL|function|get_accName
DECL|function|get_accParent
DECL|function|get_accRole
DECL|function|get_accSelection
DECL|function|get_accState
DECL|function|get_accValue
DECL|function|put_accName
DECL|function|put_accValue
DECL|function|relatedInterface
DECL|function|~QWindowsEnumerate
DECL|macro|IF_EQUAL_RETURN_IIDSTRING
DECL|macro|UiaRootObjectId
DECL|member|array
DECL|member|current
DECL|member|ref
