DECL|class|LookupAborter
DECL|class|LookupReceiver
DECL|class|LookupThread
DECL|class|tst_QHostInfo
DECL|function|abort
DECL|function|abortHostLookup
DECL|function|abortHostLookupInDifferentThread
DECL|function|blockingLookup
DECL|function|blockingLookup_data
DECL|function|cache
DECL|function|cleanup
DECL|function|getSetCheck
DECL|function|init
DECL|function|initTestCase
DECL|function|lookupIPv4
DECL|function|lookupIPv4_data
DECL|function|lookupIPv6
DECL|function|lookupIPv6_data
DECL|function|multipleDifferentLookups
DECL|function|multipleDifferentLookups_data
DECL|function|multipleSameLookups
DECL|function|raceCondition
DECL|function|resultsReady
DECL|function|resultsReady
DECL|function|reverseLookup
DECL|function|reverseLookup_data
DECL|function|run
DECL|function|start
DECL|function|staticInformation
DECL|function|threadSafety
DECL|function|threadSafetyAsynchronousAPI
DECL|function|tst_QHostInfo
DECL|function|~tst_QHostInfo
DECL|macro|NOMINMAX
DECL|macro|TEST_DOMAIN
DECL|member|id
DECL|member|ipv6Available
DECL|member|ipv6LookupsAvailable
DECL|member|lookupDone
DECL|member|lookupResults
DECL|member|lookupsDoneCounter
DECL|member|netConfMan
DECL|member|networkConfiguration
DECL|member|networkSession
DECL|member|numrequests
DECL|member|result
