DECL|function|ImeState
DECL|macro|QIOSINPUTCONTEXT_H
DECL|member|currentState
DECL|struct|ImeState
DECL|variable|QIOSKeyboardListener
DECL|variable|QIOSTextInputResponder
DECL|variable|kImePlatformDataInputAccessoryView
DECL|variable|kImePlatformDataInputView
