DECL|class|ChildObject
DECL|class|ChildWidget
DECL|class|DerivedChild
DECL|class|DerivedParent
DECL|class|TestRunnable
DECL|class|tst_QPointer
DECL|function|ChildObject
DECL|function|ChildWidget
DECL|function|DerivedChild
DECL|function|DerivedParent
DECL|function|assignment_operators
DECL|function|castDuringDestruction
DECL|function|constPointer
DECL|function|constructors
DECL|function|dereference_operators
DECL|function|destructor
DECL|function|disconnect
DECL|function|equality_operators
DECL|function|isNull
DECL|function|me
DECL|function|qvariantCast
DECL|function|run
DECL|function|threadSafety
DECL|function|~ChildObject
DECL|function|~ChildWidget
DECL|function|~DerivedChild
DECL|function|~DerivedParent
DECL|member|derivedChild
DECL|member|guardedParentPointer
DECL|member|guardedPointer
DECL|member|guardedPointer
DECL|member|parentPointer
