DECL|class|InvokeResult
DECL|class|QtApplication
DECL|field|QtTAG
DECL|field|dispatchGenericMotionEvent
DECL|field|dispatchKeyEvent
DECL|field|dispatchKeyShortcutEvent
DECL|field|dispatchPopulateAccessibilityEvent
DECL|field|dispatchTouchEvent
DECL|field|dispatchTrackballEvent
DECL|field|invoked
DECL|field|m_delegateMethods
DECL|field|m_delegateObject
DECL|field|methodReturns
DECL|field|onActivityResult
DECL|field|onCreate
DECL|field|onGenericMotionEvent
DECL|field|onKeyDown
DECL|field|onKeyLongPress
DECL|field|onKeyMultiple
DECL|field|onKeyShortcut
DECL|field|onKeyUp
DECL|field|onTouchEvent
DECL|field|onTrackballEvent
DECL|field|stackDeep
DECL|method|invokeDelegate
DECL|method|invokeDelegateMethod
DECL|method|onTerminate
DECL|method|setQtActivityDelegate
DECL|package|org.qtproject.qt5.android.bindings
