DECL|class|QtService
DECL|field|m_loader
DECL|method|onBind
DECL|method|onConfigurationChanged
DECL|method|onCreate
DECL|method|onDestroy
DECL|method|onLowMemory
DECL|method|onStartCommand
DECL|method|onTaskRemoved
DECL|method|onTrimMemory
DECL|method|onUnbind
DECL|method|super_onConfigurationChanged
DECL|method|super_onStartCommand
DECL|method|super_onTaskRemoved
DECL|method|super_onTrimMemory
DECL|method|super_onUnbind
DECL|package|org.qtproject.qt5.android.bindings
