DECL|class|QBasicMouseEventTransitionPrivate
DECL|function|QBasicMouseEventTransition
DECL|function|QBasicMouseEventTransition
DECL|function|QBasicMouseEventTransitionPrivate
DECL|function|button
DECL|function|eventTest
DECL|function|eventType
DECL|function|get
DECL|function|hitTestPath
DECL|function|modifierMask
DECL|function|onTransition
DECL|function|setButton
DECL|function|setEventType
DECL|function|setHitTestPath
DECL|function|setModifierMask
DECL|function|~QBasicMouseEventTransition
DECL|member|button
DECL|member|eventType
DECL|member|modifierMask
DECL|member|path
