DECL|class|DataChangedModel
DECL|class|tst_QIdentityProxyModel
DECL|function|changeData
DECL|function|cleanup
DECL|function|cleanupTestCase
DECL|function|data
DECL|function|dataChanged
DECL|function|index
DECL|function|initTestCase
DECL|function|insertRows
DECL|function|moveRows
DECL|function|removeRows
DECL|function|reset
DECL|function|rowCount
DECL|function|tst_QIdentityProxyModel
DECL|function|verifyIdentity
DECL|member|m_model
DECL|member|m_proxy
