DECL|class|QColSpinBox
DECL|class|QColorLuminancePicker
DECL|class|QColorPicker
DECL|class|QColorShowLabel
DECL|class|QColorShower
DECL|class|QColorWell
DECL|class|QWellArray
DECL|enumerator|coff
DECL|enumerator|foff
DECL|function|QColSpinBox
DECL|function|QColorDialog
DECL|function|QColorDialog
DECL|function|QColorLuminancePicker
DECL|function|QColorPicker
DECL|function|QColorShowLabel
DECL|function|QColorShower
DECL|function|QColorWell
DECL|function|QWellArray
DECL|function|_q_addCustom
DECL|function|_q_newColorTypedIn
DECL|function|_q_newCustom
DECL|function|_q_newHsv
DECL|function|_q_newStandard
DECL|function|_q_pickScreenColor
DECL|function|cellBrush
DECL|function|cellGeometry
DECL|function|cellHeight
DECL|function|cellRect
DECL|function|cellWidth
DECL|function|changeEvent
DECL|function|colPt
DECL|function|columnAt
DECL|function|columnX
DECL|function|currentAlpha
DECL|function|currentAlpha
DECL|function|currentColor
DECL|function|currentColor
DECL|function|currentColor
DECL|function|currentQColor
DECL|function|currentQColor
DECL|function|customColor
DECL|function|customCount
DECL|function|done
DECL|function|dragEnterEvent
DECL|function|dragEnterEvent
DECL|function|dragLeaveEvent
DECL|function|dragLeaveEvent
DECL|function|dragMoveEvent
DECL|function|dropEvent
DECL|function|dropEvent
DECL|function|focusInEvent
DECL|function|focusOutEvent
DECL|function|getColor
DECL|function|getRgba
DECL|function|grabScreenColor
DECL|function|gridSize
DECL|function|helperPrepareShow
DECL|function|hsvEd
DECL|function|huePt
DECL|function|init
DECL|function|initHelper
DECL|function|isAlphaVisible
DECL|function|isAlphaVisible
DECL|function|keyPressEvent
DECL|function|keyPressEvent
DECL|function|mouseMoveEvent
DECL|function|mouseMoveEvent
DECL|function|mouseMoveEvent
DECL|function|mouseMoveEvent
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mousePressEvent
DECL|function|mousePressEvent
DECL|function|mousePressEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|mouseReleaseEvent
DECL|function|mouseReleaseEvent
DECL|function|mouseReleaseEvent
DECL|function|numCols
DECL|function|numRows
DECL|function|open
DECL|function|options
DECL|function|paintCell
DECL|function|paintCellContents
DECL|function|paintCellContents
DECL|function|paintEvent
DECL|function|paintEvent
DECL|function|paintEvent
DECL|function|paintEvent
DECL|function|releaseColorPicking
DECL|function|resizeEvent
DECL|function|retranslateStrings
DECL|function|retranslateStrings
DECL|function|rgb2hsv
DECL|function|rgbEd
DECL|function|rowAt
DECL|function|rowY
DECL|function|satPt
DECL|function|selectColor
DECL|function|selectedColor
DECL|function|selectedColumn
DECL|function|selectedRow
DECL|function|setCellBrush
DECL|function|setCol
DECL|function|setCol
DECL|function|setCol
DECL|function|setCol
DECL|function|setColor
DECL|function|setCurrent
DECL|function|setCurrentAlpha
DECL|function|setCurrentAlpha
DECL|function|setCurrentColor
DECL|function|setCurrentColor
DECL|function|setCurrentQColor
DECL|function|setCustomColor
DECL|function|setHsv
DECL|function|setOption
DECL|function|setOptions
DECL|function|setRgb
DECL|function|setSelected
DECL|function|setStandardColor
DECL|function|setVal
DECL|function|setValue
DECL|function|setVisible
DECL|function|showAlpha
DECL|function|showAlpha
DECL|function|showCurrentColor
DECL|function|sizeHint
DECL|function|sizeHint
DECL|function|standardColor
DECL|function|testOption
DECL|function|updateCell
DECL|function|updateQColor
DECL|function|val2y
DECL|function|y2val
DECL|function|~QColorDialog
DECL|function|~QColorLuminancePicker
DECL|function|~QColorPicker
DECL|function|~QWellArray
DECL|member|alphaEd
DECL|member|alphaLab
DECL|member|bEd
DECL|member|brush
DECL|member|cellh
DECL|member|cellw
DECL|member|col
DECL|member|colorDialog
DECL|member|curCol
DECL|member|curCol
DECL|member|curQColor
DECL|member|curRow
DECL|member|d
DECL|member|gEd
DECL|member|hEd
DECL|member|hue
DECL|member|hue
DECL|member|hue
DECL|member|lab
DECL|member|lblBlue
DECL|member|lblGreen
DECL|member|lblHue
DECL|member|lblRed
DECL|member|lblSat
DECL|member|lblVal
DECL|member|mousePressed
DECL|member|mousePressed
DECL|member|ncols
DECL|member|nrows
DECL|member|oldCurrent
DECL|member|pix
DECL|member|pix
DECL|member|pressPos
DECL|member|pressPos
DECL|member|rEd
DECL|member|rgbOriginal
DECL|member|sEd
DECL|member|sat
DECL|member|sat
DECL|member|sat
DECL|member|selCol
DECL|member|selRow
DECL|member|sharedColorPanelAvailable
DECL|member|vEd
DECL|member|val
DECL|member|val
DECL|member|values
DECL|struct|QWellArrayData
DECL|variable|DefaultWindowFlags
DECL|variable|pHeight
DECL|variable|pWidth
