DECL|class|QColorDialog
DECL|class|QFontDialog
DECL|class|QInputDialog
DECL|enumerator|ComboBox
DECL|enumerator|DoubleSpinBox
DECL|enumerator|EditableComboBox
DECL|enumerator|LineEdit
DECL|enumerator|SpinBox
DECL|enum|Type
DECL|function|QColorDialog
DECL|function|QFontDialog
DECL|function|QInputDialog
DECL|function|QInputDialog
DECL|function|color
DECL|function|font
DECL|function|getFont
DECL|function|selectColor
DECL|function|selectedAlpha
DECL|function|setColor
DECL|function|setFont
DECL|function|setSelectedAlpha
DECL|function|updateFamilies
DECL|function|updateSizes
DECL|function|updateStyles
DECL|function|~QColorDialog
DECL|function|~QFontDialog
DECL|function|~QInputDialog
