DECL|function|setDirectory
DECL|macro|QFILEDIALOG_H
DECL|variable|QAbstractItemDelegate
DECL|variable|QAbstractProxyModel
DECL|variable|QFileDialogPrivate
DECL|variable|QFileIconProvider
DECL|variable|QItemSelection
DECL|variable|QModelIndex
