DECL|class|QFontListView
DECL|function|QFontDialog
DECL|function|QFontDialog
DECL|function|QFontListView
DECL|function|_q_familyHighlighted
DECL|function|_q_sizeChanged
DECL|function|_q_sizeHighlighted
DECL|function|_q_styleHighlighted
DECL|function|_q_updateSample
DECL|function|_q_writingSystemHighlighted
DECL|function|canBeNativeDialog
DECL|function|changeEvent
DECL|function|count
DECL|function|currentChanged
DECL|function|currentFont
DECL|function|currentItem
DECL|function|currentText
DECL|function|done
DECL|function|eventFilter
DECL|function|getFont
DECL|function|getFont
DECL|function|getFont
DECL|function|helperPrepareShow
DECL|function|init
DECL|function|initHelper
DECL|function|model
DECL|function|open
DECL|function|options
DECL|function|retranslateStrings
DECL|function|selectedFont
DECL|function|setCurrentFont
DECL|function|setCurrentItem
DECL|function|setOption
DECL|function|setOptions
DECL|function|setVisible
DECL|function|testOption
DECL|function|text
DECL|function|updateFamilies
DECL|function|updateSampleFont
DECL|function|updateSizes
DECL|function|updateStyles
DECL|function|~QFontDialog
DECL|variable|DefaultWindowFlags
