DECL|enumerator|WIZ_NAV_BACKBUTTON
DECL|enumerator|WIZ_NAV_BB_DISABLED
DECL|enumerator|WIZ_NAV_BB_HOT
DECL|enumerator|WIZ_NAV_BB_NORMAL
DECL|enumerator|WIZ_NAV_BB_PRESSED
DECL|enumerator|WIZ_NAV_FORWARDBUTTON
DECL|enumerator|WIZ_NAV_MENUBUTTON
DECL|enumerator|WIZ_WTA_NONCLIENT
DECL|enum|WIZ_NAVIGATIONPARTS
DECL|enum|WIZ_NAV_BACKBUTTONSTATES
DECL|enum|WIZ_WINDOWTHEMEATTRIBUTETYPE
DECL|function|QVistaBackButton
DECL|function|QVistaHelper
DECL|function|basicWindowFrameColor
DECL|function|drawBlackRect
DECL|function|drawTitleBar
DECL|function|drawTitleText
DECL|function|enterEvent
DECL|function|eventFilter
DECL|function|getCaptionFont
DECL|function|handleWinEvent
DECL|function|isCompositionEnabled
DECL|function|isThemeActive
DECL|function|leaveEvent
DECL|function|mouseEvent
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|paintEvent
DECL|function|paintEvent
DECL|function|resizeEvent
DECL|function|resolveSymbols
DECL|function|setDWMTitleBar
DECL|function|setMouseCursor
DECL|function|setTitleBarIconAndCaptionVisible
DECL|function|sizeHint
DECL|function|titleOffset
DECL|function|updateCustomMargins
DECL|function|vistaState
DECL|function|winEvent
DECL|function|~QVistaHelper
DECL|macro|WIZ_CS_ACTIVE
DECL|macro|WIZ_DTT_COMPOSITED
DECL|macro|WIZ_DTT_GLOWSIZE
DECL|macro|WIZ_DT_CENTER
DECL|macro|WIZ_DT_NOPREFIX
DECL|macro|WIZ_DT_SINGLELINE
DECL|macro|WIZ_DT_VCENTER
DECL|macro|WIZ_TMT_BORDERCOLORHINT
DECL|macro|WIZ_TMT_CAPTIONFONT
DECL|macro|WIZ_TMT_FILLCOLORHINT
DECL|macro|WIZ_WM_DWMCOMPOSITIONCHANGED
DECL|macro|WIZ_WM_NCMOUSELEAVE
DECL|macro|WIZ_WM_THEMECHANGED
DECL|macro|WIZ_WP_CAPTION
DECL|macro|WIZ_WTNCA_NODRAWCAPTION
DECL|macro|WIZ_WTNCA_NODRAWICON
DECL|macro|_WIN32_WINNT
DECL|macro|_WIN32_WINNT
DECL|member|cachedVistaState
DECL|member|crBorder
DECL|member|crShadow
DECL|member|crText
DECL|member|cxLeftWidth
DECL|member|cxRightWidth
DECL|member|cyBottomHeight
DECL|member|cyTopHeight
DECL|member|dwFlags
DECL|member|dwFlags
DECL|member|dwMask
DECL|member|dwSize
DECL|member|eTextShadowType
DECL|member|fApplyOverlay
DECL|member|iBorderSize
DECL|member|iColorPropId
DECL|member|iFontPropId
DECL|member|iGlowSize
DECL|member|iStateId
DECL|member|instanceCount
DECL|member|is_vista
DECL|member|ptShadowOffset
DECL|typedef|PtrCloseThemeData
DECL|typedef|PtrDrawThemeBackground
DECL|typedef|PtrDrawThemeTextEx
DECL|typedef|PtrDwmDefWindowProc
DECL|typedef|PtrDwmExtendFrameIntoClientArea
DECL|typedef|PtrDwmIsCompositionEnabled
DECL|typedef|PtrGetThemeColor
DECL|typedef|PtrGetThemePartSize
DECL|typedef|PtrGetThemeSysFont
DECL|typedef|PtrIsAppThemed
DECL|typedef|PtrIsThemeActive
DECL|typedef|PtrOpenThemeData
DECL|typedef|PtrSetWindowThemeAttribute
DECL|typedef|WIZ_DTTOPTS
DECL|typedef|WIZ_MARGINS
DECL|typedef|WIZ_WTA_OPTIONS
DECL|variable|pCloseThemeData
DECL|variable|pDrawThemeBackground
DECL|variable|pDrawThemeTextEx
DECL|variable|pDwmDefWindowProc
DECL|variable|pDwmExtendFrameIntoClientArea
DECL|variable|pDwmIsCompositionEnabled
DECL|variable|pGetThemeColor
DECL|variable|pGetThemePartSize
DECL|variable|pGetThemeSysFont
DECL|variable|pIsAppThemed
DECL|variable|pIsThemeActive
DECL|variable|pOpenThemeData
DECL|variable|pSetWindowThemeAttribute
