DECL|function|QT_MODULE
DECL|function|qBubbleSort
DECL|function|qBubbleSort
DECL|function|qBubbleSort
DECL|function|qBubbleSortHelper
DECL|function|qHeapSort
DECL|function|qHeapSort
DECL|function|qHeapSort
DECL|function|qHeapSortHelper
DECL|function|qHeapSortHelper
DECL|macro|Q3TL_H
DECL|variable|BiIterator
DECL|variable|BiIterator
DECL|variable|BiIterator
DECL|variable|BiIterator
DECL|variable|BiIterator
DECL|variable|T
