DECL|function|GLWidget
DECL|function|createBubbles
DECL|function|createGeometry
DECL|function|extrude
DECL|function|handleButtonPress
DECL|function|initializeGL
DECL|function|paintGL
DECL|function|paintQtLogo
DECL|function|paintTexturedCube
DECL|function|quad
DECL|function|resizeGL
DECL|function|setLogo
DECL|function|setScaling
DECL|function|setShowBubbles
DECL|function|setTexture
DECL|function|setTransparent
DECL|function|~GLWidget
DECL|variable|bubbleNum
