DECL|class|QPagePreview
DECL|class|QUnixPageSetupDialogPrivate
DECL|function|PaperSourceNames
DECL|function|QPagePreview
DECL|function|QPageSetupDialog
DECL|function|QPageSetupDialog
DECL|function|QPageSetupWidget
DECL|function|QUnixPageSetupDialogPrivate
DECL|function|bottomMarginChanged
DECL|function|exec
DECL|function|init
DECL|function|initPageSizes
DECL|function|initPagesPerSheet
DECL|function|initUnits
DECL|function|leftMarginChanged
DECL|function|pageOrientationChanged
DECL|function|pageSizeChanged
DECL|function|pagesPerSheetChanged
DECL|function|rightMarginChanged
DECL|function|selectPrinter
DECL|function|setPageLayout
DECL|function|setPagePreviewLayout
DECL|function|setPrinter
DECL|function|setupPrinter
DECL|function|topMarginChanged
DECL|function|unitChanged
DECL|function|updateWidget
DECL|function|~QUnixPageSetupDialogPrivate
DECL|member|m_pageLayout
DECL|member|m_pagePreviewColumns
DECL|member|m_pagePreviewRows
DECL|member|name
DECL|member|paperSource
DECL|member|widget
DECL|struct|PaperSourceNames
DECL|variable|paperSourceNames
