DECL|class|LineEdit
DECL|class|QPrintPreviewDialogPrivate
DECL|class|QPrintPreviewMainWindow
DECL|class|ZoomFactorValidator
DECL|function|LineEdit
DECL|function|QPrintPreviewDialog
DECL|function|QPrintPreviewDialog
DECL|function|QPrintPreviewDialogPrivate
DECL|function|QPrintPreviewMainWindow
DECL|function|ZoomFactorValidator
DECL|function|ZoomFactorValidator
DECL|function|_q_fit
DECL|function|_q_navigate
DECL|function|_q_pageNumEdited
DECL|function|_q_pageSetup
DECL|function|_q_previewChanged
DECL|function|_q_print
DECL|function|_q_setMode
DECL|function|_q_zoomFactorChanged
DECL|function|_q_zoomIn
DECL|function|_q_zoomOut
DECL|function|createPopupMenu
DECL|function|done
DECL|function|focusInEvent
DECL|function|focusOutEvent
DECL|function|handleReturnPressed
DECL|function|init
DECL|function|isFitting
DECL|function|open
DECL|function|printer
DECL|function|qt_setupActionIcon
DECL|function|setFitting
DECL|function|setVisible
DECL|function|setupActions
DECL|function|updateNavActions
DECL|function|updatePageNumLabel
DECL|function|updateZoomFactor
DECL|function|validate
DECL|function|~QPrintPreviewDialog
DECL|member|facingModeAction
DECL|member|firstPageAction
DECL|member|fitGroup
DECL|member|fitPageAction
DECL|member|fitWidthAction
DECL|member|initialized
DECL|member|landscapeAction
DECL|member|lastPageAction
DECL|member|memberToDisconnectOnClose
DECL|member|modeGroup
DECL|member|navGroup
DECL|member|nextPageAction
DECL|member|orientationGroup
DECL|member|origText
DECL|member|overviewModeAction
DECL|member|ownPrinter
DECL|member|pageNumEdit
DECL|member|pageNumLabel
DECL|member|pageSetupAction
DECL|member|portraitAction
DECL|member|prevPageAction
DECL|member|preview
DECL|member|printAction
DECL|member|printDialog
DECL|member|printer
DECL|member|printerGroup
DECL|member|receiverToDisconnectOnClose
DECL|member|singleModeAction
DECL|member|zoomFactor
DECL|member|zoomGroup
DECL|member|zoomInAction
DECL|member|zoomOutAction
