DECL|class|TransformTranslator
DECL|class|tst_languageChange
DECL|enumerator|ColorDialog
DECL|enumerator|FileDialog
DECL|enumerator|InputDialog
DECL|enum|DialogType
DECL|function|TransformTranslator
DECL|function|TransformTranslator
DECL|function|cleanupTestCase
DECL|function|initTestCase
DECL|function|install
DECL|function|isEmpty
DECL|function|retranslatability
DECL|function|retranslatability_data
DECL|function|translate
DECL|function|tst_languageChange
DECL|member|m_translations
DECL|typedef|TranslationSet
