DECL|class|AnotherStandardItemModelWithCustomRoleNames
DECL|class|StandardItemModelWithCustomDragAndDrop
DECL|class|StandardItemModelWithCustomRoleNames
DECL|class|SubQAbstractProxyModel
DECL|class|SwappingProxy
DECL|class|tst_QAbstractProxyModel
DECL|enumerator|AnotherCustomRole1
DECL|enumerator|AnotherCustomRole2
DECL|enumerator|CustomRole1
DECL|enumerator|CustomRole2
DECL|enum|CustomRole
DECL|enum|CustomRole
DECL|function|AnotherStandardItemModelWithCustomRoleNames
DECL|function|StandardItemModelWithCustomRoleNames
DECL|function|columnCount
DECL|function|columnCount
DECL|function|data
DECL|function|data_data
DECL|function|flags
DECL|function|flags_data
DECL|function|headerData
DECL|function|headerData_data
DECL|function|index
DECL|function|index
DECL|function|itemData
DECL|function|itemData_data
DECL|function|mapFromSource
DECL|function|mapFromSource
DECL|function|mapFromSource
DECL|function|mapFromSource_data
DECL|function|mapSelectionFromSource
DECL|function|mapSelectionFromSource_data
DECL|function|mapSelectionToSource
DECL|function|mapSelectionToSource_data
DECL|function|mapToSource
DECL|function|mapToSource
DECL|function|mapToSource
DECL|function|mapToSource_data
DECL|function|mimeTypes
DECL|function|parent
DECL|function|parent
DECL|function|qabstractproxymodel
DECL|function|revert
DECL|function|rowCount
DECL|function|rowCount
DECL|function|setSourceModel
DECL|function|submit
DECL|function|submit_data
DECL|function|supportedDragActions
DECL|function|supportedDropActions
DECL|function|swapRow
DECL|function|testDragAndDrop
DECL|function|testRoleNames
DECL|function|testSwappingRowsProxy
DECL|function|verifySubSetOf
