DECL|class|QSQLite2DriverPrivate
DECL|class|QSQLite2Result
DECL|class|QSQLite2ResultPrivate
DECL|function|QSQLite2Driver
DECL|function|QSQLite2Driver
DECL|function|QSQLite2DriverPrivate
DECL|function|QSQLite2Result
DECL|function|QSQLite2ResultPrivate
DECL|function|beginTransaction
DECL|function|cleanup
DECL|function|close
DECL|function|commitTransaction
DECL|function|createResult
DECL|function|detachFromResultSet
DECL|function|escapeIdentifier
DECL|function|fetchNext
DECL|function|finalize
DECL|function|gotoNext
DECL|function|handle
DECL|function|handle
DECL|function|hasFeature
DECL|function|init
DECL|function|nameToType
DECL|function|numRowsAffected
DECL|function|open
DECL|function|primaryIndex
DECL|function|record
DECL|function|record
DECL|function|reset
DECL|function|rollbackTransaction
DECL|function|size
DECL|function|tables
DECL|function|virtual_hook
DECL|function|~QSQLite2Driver
DECL|function|~QSQLite2Result
DECL|member|access
DECL|member|access
DECL|member|currentMachine
DECL|member|currentTail
DECL|member|d
DECL|member|firstRow
DECL|member|q
DECL|member|rInf
DECL|member|skipRow
DECL|member|skippedStatus
DECL|member|utf8
DECL|member|utf8
DECL|typedef|sqlite_vm
DECL|variable|initial_cache_size
