DECL|class|AppContainer
DECL|class|AppViewSource
DECL|function|AppContainer
DECL|function|AppViewSource
DECL|function|CreateView
DECL|function|Initialize
DECL|function|Load
DECL|function|Run
DECL|function|SetWindow
DECL|function|Uninitialize
DECL|function|onActivated
DECL|function|wmain
DECL|function|~AppContainer
DECL|macro|CoreApplicationClass
DECL|macro|qHString
DECL|member|argc
DECL|member|argv
DECL|member|m_activationToken
DECL|member|m_argc
DECL|member|m_argv
DECL|typedef|ActivatedHandler
