DECL|function|XFormView
DECL|function|XFormWidget
DECL|function|changeRotation
DECL|function|changeScale
DECL|function|changeShear
DECL|function|drawPixmapType
DECL|function|drawTextType
DECL|function|drawVectorType
DECL|function|mousePressEvent
DECL|function|paint
DECL|function|pixmap
DECL|function|reset
DECL|function|resizeEvent
DECL|function|setAnimation
DECL|function|setPixmap
DECL|function|setPixmapType
DECL|function|setRotation
DECL|function|setScale
DECL|function|setShear
DECL|function|setText
DECL|function|setTextType
DECL|function|setType
DECL|function|setVectorType
DECL|function|text
DECL|function|timerEvent
DECL|function|type
DECL|function|updateCtrlPoints
DECL|function|wheelEvent
DECL|variable|alpha
