DECL|class|tst_QTextPieceTable
DECL|function|blockInsertion
DECL|function|blockInsertion2
DECL|function|blockRemoval1
DECL|function|blockRemoval2
DECL|function|blockRemoval3
DECL|function|blockRemoval4
DECL|function|blockRemoval5
DECL|function|checkBlockSeparation
DECL|function|checkDocumentChanged
DECL|function|checkDocumentChanged2
DECL|function|checkFrames1
DECL|function|cleanup
DECL|function|clearWithFrames
DECL|function|init
DECL|function|insertion1
DECL|function|insertion2
DECL|function|insertion3
DECL|function|insertion4
DECL|function|insertion5
DECL|function|removal1
DECL|function|removal2
DECL|function|removal3
DECL|function|removal4
DECL|function|removeFrameDirect
DECL|function|removeWithChildFrame
DECL|function|setBlockFormat
DECL|function|tst_QTextPieceTable
DECL|function|undoRedo1
DECL|function|undoRedo10
DECL|function|undoRedo11
DECL|function|undoRedo2
DECL|function|undoRedo3
DECL|function|undoRedo4
DECL|function|undoRedo5
DECL|function|undoRedo6
DECL|function|undoRedo7
DECL|function|undoRedo8
DECL|function|undoRedo9
DECL|macro|protected
DECL|macro|protected
DECL|member|blockFormatIndex
DECL|member|charFormatIndex
DECL|member|doc
DECL|member|table
