DECL|class|ColorDock
DECL|function|BlueTitleBar
DECL|function|ColorDock
DECL|function|ColorSwatch
DECL|function|allow
DECL|function|allowBottom
DECL|function|allowLeft
DECL|function|allowRight
DECL|function|allowTop
DECL|function|bgColorForName
DECL|function|changeClosable
DECL|function|changeFloatable
DECL|function|changeFloating
DECL|function|changeMovable
DECL|function|changeSizeHints
DECL|function|changeVerticalTitleBar
DECL|function|contextMenuEvent
DECL|function|createSpinBox
DECL|function|fgColorForName
DECL|function|minimumSizeHint
DECL|function|minimumSizeHint
DECL|function|mousePressEvent
DECL|function|paintEvent
DECL|function|paintEvent
DECL|function|place
DECL|function|placeBottom
DECL|function|placeLeft
DECL|function|placeRight
DECL|function|placeTop
DECL|function|resizeEvent
DECL|function|setCustomSizeHint
DECL|function|setCustomSizeHint
DECL|function|sizeHint
DECL|function|splitInto
DECL|function|tabInto
DECL|function|updateContextMenu
DECL|function|updateMask
DECL|macro|DEBUG_SIZEHINTS
DECL|member|color
DECL|member|minSzHint
DECL|member|szHint
