DECL|class|tst_QCheckBox
DECL|function|autoRepeat
DECL|function|checkState
DECL|function|cleanup
DECL|function|cleanupTestCase
DECL|function|clicked
DECL|function|foregroundRole
DECL|function|init
DECL|function|initTestCase
DECL|function|isChecked
DECL|function|isDown
DECL|function|isOn
DECL|function|isToggleButton
DECL|function|isTriState
DECL|function|minimumSizeHint
DECL|function|onClicked
DECL|function|onPressed
DECL|function|onReleased
DECL|function|onStateChanged
DECL|function|onToggled
DECL|function|pressed
DECL|function|released
DECL|function|setAutoRepeat
DECL|function|setChecked
DECL|function|setDown
DECL|function|setNoChange
DECL|function|setText
DECL|function|setText_data
DECL|function|setTriState
DECL|function|stateChanged
DECL|function|text
DECL|function|toggle
DECL|function|toggled
DECL|function|tst_QCheckBox
DECL|function|~tst_QCheckBox
DECL|member|click_count
DECL|member|cur_state
DECL|member|press_count
DECL|member|release_count
DECL|member|testWidget
DECL|member|tmp
DECL|member|tmp2
DECL|member|toggle_count
