DECL|function|QDecorationDefault
DECL|function|paint
DECL|function|paintButton
DECL|function|pixmapFor
DECL|function|region
DECL|function|titleBarHeight
DECL|function|windowTitleFor
DECL|function|xpmForRegion
DECL|function|~QDecorationDefault
DECL|member|staticClosePixmap
DECL|member|staticHelpPixmap
DECL|member|staticMaximizePixmap
DECL|member|staticMenuPixmap
DECL|member|staticMinimizePixmap
DECL|member|staticNormalizePixmap
DECL|variable|default_close_xpm
DECL|variable|default_help_xpm
DECL|variable|default_maximize_xpm
DECL|variable|default_menu_xpm
DECL|variable|default_minimize_xpm
DECL|variable|default_normalize_xpm
