DECL|class|QDirectPainterPrivate
DECL|function|QDirectPainter
DECL|function|QDirectPainterPrivate
DECL|function|allocatedRegion
DECL|function|devS
DECL|function|endPainting
DECL|function|endPainting
DECL|function|flush
DECL|function|frameBuffer
DECL|function|geometry
DECL|function|getPrimaryScreen
DECL|function|linestep
DECL|function|lock
DECL|function|lower
DECL|function|qt_directpainter_embedevent
DECL|function|qt_directpainter_region
DECL|function|raise
DECL|function|regionChanged
DECL|function|requestedRegion
DECL|function|reserveRegion
DECL|function|reservedRegion
DECL|function|screenDepth
DECL|function|screenHeight
DECL|function|screenS
DECL|function|screenWidth
DECL|function|setGeometry
DECL|function|setRegion
DECL|function|startPainting
DECL|function|unlock
DECL|function|winId
DECL|function|~QDirectPainter
DECL|function|~QDirectPainterPrivate
DECL|member|requested_region
DECL|member|seenRegion
DECL|member|staticPainter
DECL|member|staticPainter
DECL|member|surface
