DECL|class|QWSKbPrivate
DECL|function|QWSKbPrivate
DECL|function|QWSKeyboardHandler
DECL|function|QWSKeyboardHandler
DECL|function|autoRepeat
DECL|function|beginAutoRepeat
DECL|function|beginAutoRepeat
DECL|function|endAutoRepeat
DECL|function|endAutoRepeat
DECL|function|loadKeymap
DECL|function|processKeyEvent
DECL|function|processKeycode
DECL|function|toQtModifiers
DECL|function|transformDirKey
DECL|function|unloadKeymap
DECL|function|~QWSKbPrivate
DECL|function|~QWSKeyboardHandler
DECL|member|m_ar_delay
DECL|member|m_ar_keycode
DECL|member|m_ar_modifier
DECL|member|m_ar_period
DECL|member|m_ar_timer
DECL|member|m_ar_unicode
DECL|member|m_composing
DECL|member|m_dead_unicode
DECL|member|m_do_compose
DECL|member|m_handler
DECL|member|m_keycompose
DECL|member|m_keycompose_size
DECL|member|m_keymap
DECL|member|m_keymap_size
DECL|member|m_locks
DECL|member|m_modifiers
DECL|member|m_no_zap
DECL|member|s_keycompose_default
DECL|member|s_keymap_default
