DECL|class|QIntKeyboardListenThread
DECL|class|QWSIntKbPrivate
DECL|function|QIntKeyboardListenThread
DECL|function|QWSIntKbPrivate
DECL|function|QWSIntKeyboardHandler
DECL|function|dataReady
DECL|function|readKeyboardData
DECL|function|run
DECL|function|stoploop
DECL|function|~QIntKeyboardListenThread
DECL|function|~QWSIntKbPrivate
DECL|function|~QWSIntKeyboardHandler
DECL|member|handler
DECL|member|imp
DECL|member|kbdthread
DECL|member|loop
DECL|member|rxack
DECL|member|rxpost
DECL|member|scancodebuf
