DECL|class|QWSTslibMouseHandlerPrivate
DECL|function|QWSTslibMouseHandler
DECL|function|QWSTslibMouseHandlerPrivate
DECL|function|calibrate
DECL|function|calibrate
DECL|function|clearCalibration
DECL|function|clearCalibration
DECL|function|close
DECL|function|get_sample
DECL|function|open
DECL|function|readMouseData
DECL|function|resume
DECL|function|resume
DECL|function|suspend
DECL|function|suspend
DECL|function|~QWSTslibMouseHandler
DECL|function|~QWSTslibMouseHandlerPrivate
DECL|member|calibrated
DECL|member|dev
DECL|member|devName
DECL|member|handler
DECL|member|jitter_limit
DECL|member|lastSample
DECL|member|lastdx
DECL|member|lastdy
DECL|member|mouseNotifier
DECL|member|wasPressed
