DECL|class|QWSPcMouseHandlerPrivate
DECL|class|QWSPcMouseSubHandler
DECL|class|QWSPcMouseSubHandler_intellimouse
DECL|class|QWSPcMouseSubHandler_mouseman
DECL|class|QWSPcMouseSubHandler_mousesystems
DECL|class|QWSPcMouseSubHandler_ms
DECL|class|QWSPcMouseSubHandler_serial
DECL|enumerator|Button
DECL|enumerator|Insufficient
DECL|enumerator|Motion
DECL|enumerator|max_buf
DECL|enumerator|max_dev
DECL|enum|UsageResult
DECL|function|QWSPcMouseHandler
DECL|function|QWSPcMouseHandlerPrivate
DECL|function|QWSPcMouseSubHandler
DECL|function|QWSPcMouseSubHandler_intellimouse
DECL|function|QWSPcMouseSubHandler_mouseman
DECL|function|QWSPcMouseSubHandler_mousesystems
DECL|function|QWSPcMouseSubHandler_ms
DECL|function|QWSPcMouseSubHandler_serial
DECL|function|appendData
DECL|function|buttonState
DECL|function|closeDevices
DECL|function|closeIfNot
DECL|function|file
DECL|function|init
DECL|function|init
DECL|function|init
DECL|function|init
DECL|function|initSerial
DECL|function|initState
DECL|function|motionPending
DECL|function|notify
DECL|function|openDevices
DECL|function|readMouseData
DECL|function|reliable
DECL|function|resume
DECL|function|resume
DECL|function|sendEvent
DECL|function|setflags
DECL|function|suspend
DECL|function|suspend
DECL|function|takeMotion
DECL|function|takeWheel
DECL|function|tryData
DECL|function|tryData
DECL|function|tryData
DECL|function|tryData
DECL|function|useData
DECL|function|worse
DECL|function|~QWSPcMouseHandler
DECL|function|~QWSPcMouseHandlerPrivate
DECL|function|~QWSPcMouseSubHandler
DECL|member|accel
DECL|member|accel_limit
DECL|member|badness
DECL|member|bstate
DECL|member|buffer
DECL|member|device
DECL|member|driver
DECL|member|fd
DECL|member|goodness
DECL|member|handler
DECL|member|mman
DECL|member|motion
DECL|member|nbuf
DECL|member|notifiers
DECL|member|nsub
DECL|member|packetsize
DECL|member|packetsize
DECL|member|retries
DECL|member|sub
DECL|member|wheel
