DECL|class|QWSLinuxTPMouseHandlerPrivate
DECL|function|QWSLinuxTPMouseHandler
DECL|function|QWSLinuxTPMouseHandlerPrivate
DECL|function|readMouseData
DECL|function|resume
DECL|function|resume
DECL|function|suspend
DECL|function|suspend
DECL|function|~QWSLinuxTPMouseHandler
DECL|function|~QWSLinuxTPMouseHandlerPrivate
DECL|macro|QT_QWS_IPAQ_RAW
DECL|macro|QT_QWS_SCREEN_COORDINATES
DECL|macro|QT_QWS_TP_JITTER_LIMIT
DECL|macro|QT_QWS_TP_MINIMUM_SAMPLES
DECL|macro|QT_QWS_TP_MOVE_LIMIT
DECL|macro|QT_QWS_TP_PRESSURE_THRESHOLD
DECL|macro|QT_QWS_TP_SAMPLE_SIZE
DECL|member|currSample
DECL|member|handler
DECL|member|lastSample
DECL|member|mouseBuf
DECL|member|mouseBufSize
DECL|member|mouseFD
DECL|member|mouseIdx
DECL|member|mouseNotifier
DECL|member|numSamples
DECL|member|oldTotalMousePos
DECL|member|oldmouse
DECL|member|pad
DECL|member|pressure
DECL|member|samples
DECL|member|skipCount
DECL|member|waspressed
DECL|member|x
DECL|member|y
DECL|typedef|TS_EVENT
