DECL|class|QIntMouseListenThread
DECL|class|QIntMousePrivate
DECL|function|MOUSE_Init
DECL|function|MOUSE_ShouldFilter
DECL|function|MOUSE_SynchronousGetPosition
DECL|function|QIntMouseHandler
DECL|function|QIntMouseListenThread
DECL|function|QIntMousePrivate
DECL|function|calibrate
DECL|function|clearCalibration
DECL|function|dataReady
DECL|function|readMouseData
DECL|function|resume
DECL|function|run
DECL|function|stoploop
DECL|function|suspend
DECL|function|~QIntMouseHandler
DECL|function|~QIntMouseListenThread
DECL|function|~QIntMousePrivate
DECL|member|buttons
DECL|member|calibrated
DECL|member|handler
DECL|member|imp
DECL|member|loop
DECL|member|mouseconn
DECL|member|mousemsg
DECL|member|mousethread
DECL|member|suspended
DECL|member|waitforread
DECL|member|x
DECL|member|x
DECL|member|y
DECL|member|y
DECL|member|z
DECL|struct|MOUSEMessageStruct
DECL|struct|USBMouseStruct
DECL|typedef|MOUSEHandler
DECL|typedef|MOUSEMessage
DECL|typedef|USBMouse
DECL|variable|mousedev
