DECL|class|QLinuxFbScreenPrivate
DECL|function|QLinuxFbScreen
DECL|function|QLinuxFbScreenPrivate
DECL|function|blank
DECL|function|cache
DECL|function|clearCache
DECL|function|closeTty
DECL|function|connect
DECL|function|createPalette
DECL|function|deleteEntry
DECL|function|delete_entry
DECL|function|disconnect
DECL|function|fixupScreenInfo
DECL|function|initDevice
DECL|function|insert_entry
DECL|function|openTty
DECL|function|restore
DECL|function|save
DECL|function|set
DECL|function|setDirty
DECL|function|setMode
DECL|function|setPixelFormat
DECL|function|setupOffScreen
DECL|function|sharedRamSize
DECL|function|shutdownDevice
DECL|function|uncache
DECL|function|useOffscreen
DECL|function|~QLinuxFbScreen
DECL|function|~QLinuxFbScreenPrivate
DECL|member|blank
DECL|member|displaySpec
DECL|member|doGenericColors
DECL|member|doGraphicsMode
DECL|member|driverType
DECL|member|fd
DECL|member|oldKdMode
DECL|member|startupd
DECL|member|startuph
DECL|member|startupw
DECL|member|ttyDevice
DECL|member|ttyfd
