DECL|class|QVFbScreenPrivate
DECL|function|QVFbScreen
DECL|function|QVFbScreenPrivate
DECL|function|blank
DECL|function|connect
DECL|function|disconnect
DECL|function|initDevice
DECL|function|restore
DECL|function|save
DECL|function|setBrightness
DECL|function|setDirty
DECL|function|setMode
DECL|function|shutdownDevice
DECL|function|~QVFbScreen
DECL|function|~QVFbScreenPrivate
DECL|macro|QTOPIA_QVFB_BRIGHTNESS
DECL|member|blank
DECL|member|brightness
DECL|member|hdr
DECL|member|keyboard
DECL|member|mouse
DECL|member|shmrgn
DECL|member|success
DECL|variable|connected
