DECL|class|QMultiScreenCursor
DECL|class|QMultiScreenPrivate
DECL|function|QMultiScreen
DECL|function|QMultiScreenCursor
DECL|function|QMultiScreenPrivate
DECL|function|addCursor
DECL|function|addSubScreen
DECL|function|blank
DECL|function|blit
DECL|function|blit
DECL|function|connect
DECL|function|createSurface
DECL|function|createSurface
DECL|function|disconnect
DECL|function|exposeRegion
DECL|function|filterDisplayOffset
DECL|function|getDisplayId
DECL|function|haltUpdates
DECL|function|hide
DECL|function|initDevice
DECL|function|isInterlaced
DECL|function|memoryNeeded
DECL|function|move
DECL|function|onCard
DECL|function|onCard
DECL|function|region
DECL|function|removeSubScreen
DECL|function|restore
DECL|function|resumeUpdates
DECL|function|save
DECL|function|set
DECL|function|setCurrentCursor
DECL|function|setDirty
DECL|function|setMode
DECL|function|sharedRamSize
DECL|function|show
DECL|function|shutdownDevice
DECL|function|solidFill
DECL|function|subScreens
DECL|function|supportsDepth
DECL|function|~QMultiScreen
DECL|function|~QMultiScreenCursor
DECL|function|~QMultiScreenPrivate
DECL|member|currentCursor
DECL|member|cursor
DECL|member|cursors
DECL|member|region
DECL|member|screens
