DECL|function|qt_conv16ToRgb
DECL|function|qt_conv16ToRgb
DECL|function|qt_convRgbTo16
DECL|function|qt_convRgbTo16
DECL|macro|QSCREEN_QWS_H
DECL|macro|QT_QWS_DEPTH16_RGB
DECL|typedef|ClearCacheFunc
DECL|variable|QBrush
DECL|variable|QGraphicsSystem
DECL|variable|QPixmapData
DECL|variable|QPixmapDataFactory
DECL|variable|QScreen
DECL|variable|QScreenCursor
DECL|variable|QScreenPrivate
DECL|variable|QWSWindow
DECL|variable|QWSWindowSurface
DECL|variable|SourcePixmap
DECL|variable|SourceSolid
DECL|variable|qt_bbits
DECL|variable|qt_blue_mask
DECL|variable|qt_blue_rounding_shift
DECL|variable|qt_gbits
DECL|variable|qt_green_mask
DECL|variable|qt_green_rounding_shift
DECL|variable|qt_green_shift
DECL|variable|qt_neg_blue_shift
DECL|variable|qt_rbits
DECL|variable|qt_red_mask
DECL|variable|qt_red_rounding_shift
DECL|variable|qt_red_shift
