DECL|class|QWSSoundServerBucket
DECL|class|QWSSoundServerClient
DECL|class|QWSSoundServerPrivate
DECL|class|QWSSoundServerProvider
DECL|class|QWSSoundServerStream
DECL|function|CompletedInfo
DECL|function|CompletedInfo
DECL|function|QWSSoundClient
DECL|function|QWSSoundServer
DECL|function|QWSSoundServerBucket
DECL|function|QWSSoundServerClient
DECL|function|QWSSoundServerPrivate
DECL|function|QWSSoundServerProvider
DECL|function|QWSSoundServerSocket
DECL|function|QWSSoundServerSocket
DECL|function|QWSSoundServerStream
DECL|function|add
DECL|function|checkPresetVolumes
DECL|function|closeDevice
DECL|function|devSamples
DECL|function|emitConnectionRefused
DECL|function|equal
DECL|function|feedDevice
DECL|function|finished
DECL|function|finished
DECL|function|getNumTok
DECL|function|getSample
DECL|function|getStringTok
DECL|function|groupId
DECL|function|muted
DECL|function|newConnection
DECL|function|nextId
DECL|function|openDevice
DECL|function|openFile
DECL|function|pause
DECL|function|pauseFile
DECL|function|pauseFile
DECL|function|play
DECL|function|play
DECL|function|playFile
DECL|function|playFile
DECL|function|playFile
DECL|function|playPriorityOnly
DECL|function|playPriorityOnly
DECL|function|playRaw
DECL|function|playRawFile
DECL|function|prepareBuffer
DECL|function|readySamples
DECL|function|readySamples
DECL|function|reconnect
DECL|function|resume
DECL|function|resumeFile
DECL|function|resumeFile
DECL|function|sendClientMessage
DECL|function|sendCompletedSignals
DECL|function|sendDeviceError
DECL|function|sendDeviceReady
DECL|function|sendServerMessage
DECL|function|sendSoundCompleted
DECL|function|setMute
DECL|function|setMute
DECL|function|setMute
DECL|function|setPlayPriorityOnly
DECL|function|setPriority
DECL|function|setSilent
DECL|function|setSilent
DECL|function|setVolume
DECL|function|setVolume
DECL|function|setVolume
DECL|function|soundId
DECL|function|startSampleRunin
DECL|function|stop
DECL|function|stopAll
DECL|function|stopFile
DECL|function|stopFile
DECL|function|timerEvent
DECL|function|translateSoundCompleted
DECL|function|tryReadCommand
DECL|function|tryReadCommand
DECL|function|updateBuffer
DECL|function|~QWSSoundClient
DECL|function|~QWSSoundServer
DECL|function|~QWSSoundServerBucket
DECL|function|~QWSSoundServerClient
DECL|function|~QWSSoundServerPrivate
DECL|function|~QWSSoundServerProvider
DECL|function|~QWSSoundServerStream
DECL|macro|QT_QWS_SOUND_16BIT
DECL|macro|QT_QWS_SOUND_STEREO
DECL|macro|WAVE_FORMAT_PCM
DECL|member|active
DECL|member|avgBytesPerSec
DECL|member|blockAlign
DECL|member|can_GETOSPACE
DECL|member|channels
DECL|member|chunk
DECL|member|chunkdata
DECL|member|completed
DECL|member|cursor
DECL|member|data
DECL|member|data
DECL|member|data
DECL|member|data1
DECL|member|data2
DECL|member|dev
DECL|member|fd
DECL|member|formatTag
DECL|member|groupId
DECL|member|id
DECL|member|inactive
DECL|member|isPriority
DECL|member|lastId
DECL|member|lastId
DECL|member|lasttime
DECL|member|left
DECL|member|left
DECL|member|leftVolume
DECL|member|mCurrentID
DECL|member|mFinishedRead
DECL|member|mInsufficientSamples
DECL|member|mMuted
DECL|member|mSid
DECL|member|mWid
DECL|member|max
DECL|member|max1
DECL|member|max2
DECL|member|mute
DECL|member|out
DECL|member|priExist
DECL|member|priorityExists
DECL|member|priorityExists
DECL|member|right
DECL|member|right
DECL|member|rightVolume
DECL|member|sampleRunin
DECL|member|samplesPerSec
DECL|member|samples_due
DECL|member|server
DECL|member|sid
DECL|member|silent
DECL|member|size
DECL|member|socket
DECL|member|soundId
DECL|member|timerId
DECL|member|unwritten
DECL|member|volumes
DECL|member|wBitsPerSample
DECL|member|wavedata_remaining
DECL|member|wid
DECL|struct|CompletedInfo
DECL|struct|PresetVolume
DECL|struct|QRiffChunk
DECL|variable|maxVolume
DECL|variable|runinLength
DECL|variable|sound_16bit
DECL|variable|sound_16bit
DECL|variable|sound_buffer_size
DECL|variable|sound_fragment_size
DECL|variable|sound_fragment_size
DECL|variable|sound_speed
DECL|variable|sound_stereo
DECL|variable|sound_stereo
DECL|variable|zeroMem
