DECL|function|FAREnforcer
DECL|function|QAuthDevice
DECL|function|QTransportAuth
DECL|function|QTransportAuthPrivate
DECL|function|RequestAnalyzer
DECL|function|SxeRegistryLocker
DECL|function|__fileOpen
DECL|function|analyze
DECL|function|authBuf
DECL|function|authFromMessage
DECL|function|authToMessage
DECL|function|authorizeMessage
DECL|function|authorizeRequest
DECL|function|bufferDestroyed
DECL|function|client
DECL|function|connectTransport
DECL|function|connection
DECL|function|errorString
DECL|function|getClientKey
DECL|function|getClientKey
DECL|function|getInstance
DECL|function|getInstance
DECL|function|getKeyFileMutex
DECL|function|guaranteed_memset
DECL|function|hexstring
DECL|function|hmac_md5
DECL|function|invalidateClientKeyCache
DECL|function|invalidateClientKeyCache
DECL|function|isDiscoveryMode
DECL|function|keyFilePath
DECL|function|logAuthAttempt
DECL|function|logFilePath
DECL|function|passThroughByClient
DECL|function|readData
DECL|function|recvBuf
DECL|function|recvReadyRead
DECL|function|registerPolicyReceiver
DECL|function|reset
DECL|function|setClient
DECL|function|setConnection
DECL|function|setKeyFilePath
DECL|function|setLogFilePath
DECL|function|setPackageRegistry
DECL|function|setProcessKey
DECL|function|setProcessKey
DECL|function|setRequestAnalyzer
DECL|function|setTrusted
DECL|function|targetBytesWritten
DECL|function|trusted
DECL|function|unregisterPolicyReceiver
DECL|function|writeData
DECL|function|~QAuthDevice
DECL|function|~QTransportAuth
DECL|function|~QTransportAuthPrivate
DECL|function|~RequestAnalyzer
DECL|function|~SxeRegistryLocker
DECL|macro|BUF_SIZE
DECL|macro|KEY_CACHE_SIZE
DECL|member|FARMessage
DECL|member|SxeTag
DECL|member|minute
DECL|member|minutelyRate
DECL|variable|errorStrings
