DECL|class|QWSClientPrivate
DECL|class|QWSWindowPrivate
DECL|function|QWSClient
DECL|function|QWSClientPrivate
DECL|function|QWSCommandStruct
DECL|function|QWSInputMethod
DECL|function|QWSServer
DECL|function|QWSServer
DECL|function|QWSWindow
DECL|function|QWSWindowPrivate
DECL|function|_q_clientClosed
DECL|function|_q_deleteWindowsLater
DECL|function|_q_doClient
DECL|function|_q_newConnection
DECL|function|_q_screenSaverSleep
DECL|function|_q_screenSaverTimeout
DECL|function|_q_screenSaverWake
DECL|function|addKeyboardFilter
DECL|function|addUnbufferedSurface
DECL|function|allocatedRegion
DECL|function|backgroundBrush
DECL|function|beginDisplayReconfigure
DECL|function|cleanupFonts
DECL|function|cleanupFontsDir
DECL|function|clientWindows
DECL|function|closeDisplay
DECL|function|closeHandler
DECL|function|closeKeyboard
DECL|function|closeMouse
DECL|function|closedown
DECL|function|createSurface
DECL|function|dereferenceFont
DECL|function|destroy_region
DECL|function|directPaintRegion
DECL|function|dirtyOnScreen
DECL|function|disconnectClient
DECL|function|doClient
DECL|function|emergency_cleanup
DECL|function|enablePainting
DECL|function|endDisplayReconfigure
DECL|function|errorHandler
DECL|function|exposeRegion
DECL|function|filter
DECL|function|filter
DECL|function|findWindow
DECL|function|focus
DECL|function|get_object_id
DECL|function|get_property
DECL|function|handleWindowClose
DECL|function|hide
DECL|function|hideCursor
DECL|function|ignoreSignal
DECL|function|im_response
DECL|function|im_update
DECL|function|initServer
DECL|function|inputResolutionShift
DECL|function|invokeAddProperty
DECL|function|invokeConvertSelection
DECL|function|invokeCreate
DECL|function|invokeDefineCursor
DECL|function|invokeEmbed
DECL|function|invokeFont
DECL|function|invokeGetProperty
DECL|function|invokeGrabKeyboard
DECL|function|invokeGrabMouse
DECL|function|invokeIMResponse
DECL|function|invokeIMUpdate
DECL|function|invokeIdentify
DECL|function|invokePlaySound
DECL|function|invokePositionCursor
DECL|function|invokeQCopSend
DECL|function|invokeRegion
DECL|function|invokeRegionDestroy
DECL|function|invokeRegionMove
DECL|function|invokeRegionName
DECL|function|invokeRegisterChannel
DECL|function|invokeRemoveProperty
DECL|function|invokeRepaintRegion
DECL|function|invokeScreenTransform
DECL|function|invokeSelectCursor
DECL|function|invokeSetAltitude
DECL|function|invokeSetFocus
DECL|function|invokeSetOpacity
DECL|function|invokeSetProperty
DECL|function|invokeSetSelectionOwner
DECL|function|isCursorVisible
DECL|function|keyUnicode
DECL|function|keyboardHandler
DECL|function|lower
DECL|function|lowerWindow
DECL|function|mouseHandler
DECL|function|mouseHandler
DECL|function|mouseHandlers
DECL|function|moveWindowRegion
DECL|function|move_region
DECL|function|name_region
DECL|function|newMouseHandler
DECL|function|newWindow
DECL|function|openDisplay
DECL|function|openKeyboard
DECL|function|openMouse
DECL|function|operation
DECL|function|paintedRegion
DECL|function|processEventQueue
DECL|function|processKeyEvent
DECL|function|queryResponse
DECL|function|raise
DECL|function|raiseWindow
DECL|function|readMoreCommand
DECL|function|referenceFont
DECL|function|refresh
DECL|function|refresh
DECL|function|releaseKeyboard
DECL|function|releaseMouse
DECL|function|removeKeyboardFilter
DECL|function|removeUnbufferedSurface
DECL|function|repaint_region
DECL|function|request_focus
DECL|function|request_region
DECL|function|reserve_region
DECL|function|reset
DECL|function|resetEngine
DECL|function|resetInputMethod
DECL|function|resumeMouse
DECL|function|screenSave
DECL|function|screenSaverActivate
DECL|function|screenSaverActive
DECL|function|screensaverblockevent
DECL|function|sendCommitString
DECL|function|sendConnectedEvent
DECL|function|sendEmbedEvent
DECL|function|sendEvent
DECL|function|sendFontRemovedEvent
DECL|function|sendIMEvent
DECL|function|sendIMQuery
DECL|function|sendKeyEvent
DECL|function|sendKeyEventUnfiltered
DECL|function|sendMaxWindowRectEvent
DECL|function|sendMaxWindowRectEvents
DECL|function|sendMouseEvent
DECL|function|sendMouseEvent
DECL|function|sendMouseEventUnfiltered
DECL|function|sendPreeditString
DECL|function|sendPropertyNotifyEvent
DECL|function|sendPropertyNotifyEvent
DECL|function|sendPropertyReplyEvent
DECL|function|sendQCopEvent
DECL|function|sendRegionEvent
DECL|function|sendSelectionClearEvent
DECL|function|sendSelectionRequestEvent
DECL|function|send_im_mouse
DECL|function|setActiveWindow
DECL|function|setAllocatedRegion
DECL|function|setBackground
DECL|function|setCaption
DECL|function|setCurrentInputMethod
DECL|function|setCursorVisible
DECL|function|setDefaultKeyboard
DECL|function|setDefaultMouse
DECL|function|setDesktopBackground
DECL|function|setDesktopBackground
DECL|function|setDirectPaintRegion
DECL|function|setFocus
DECL|function|setIdentity
DECL|function|setInputResolution
DECL|function|setKeyboardHandler
DECL|function|setLockId
DECL|function|setMaxWindowRect
DECL|function|setMouseHandler
DECL|function|setName
DECL|function|setScreenSaver
DECL|function|setScreenSaverBlockLevel
DECL|function|setScreenSaverInterval
DECL|function|setScreenSaverIntervals
DECL|function|setWindowRegion
DECL|function|set_altitude
DECL|function|set_identity
DECL|function|set_opacity
DECL|function|show
DECL|function|showCursor
DECL|function|socket
DECL|function|startEmbed
DECL|function|startup
DECL|function|state
DECL|function|stopEmbed
DECL|function|suspendMouse
DECL|function|timerEvent
DECL|function|unlockCommunication
DECL|function|updateClientCursorPos
DECL|function|updateHandler
DECL|function|updateWindowRegions
DECL|function|update_regions
DECL|function|windowAt
DECL|function|windowFlags
DECL|function|windowList
DECL|function|~QWSClient
DECL|function|~QWSClientPrivate
DECL|function|~QWSCommandStruct
DECL|function|~QWSInputMethod
DECL|function|~QWSScreenSaver
DECL|function|~QWSServer
DECL|function|~QWSWindow
DECL|macro|KEY
DECL|macro|MOUSE
DECL|member|allocatedRegion
DECL|member|bgBrush
DECL|member|client
DECL|member|clientLock
DECL|member|command
DECL|member|directPaintRegion
DECL|member|dirtyOnScreen
DECL|member|embedded
DECL|member|embedder
DECL|member|mousePosition
DECL|member|numUnbufferedSurfaces
DECL|member|painted
DECL|member|shutdown
DECL|member|state
DECL|member|usedFonts
DECL|member|windowFlags
DECL|struct|QWSCommandStruct
DECL|variable|FontCleanupInterval
DECL|variable|current_IM
DECL|variable|current_IM_composing_win
DECL|variable|current_IM_winId
DECL|variable|force_reject_strokeIM
DECL|variable|global_focus_time_counter
DECL|variable|keyFilters
DECL|variable|keyboardGrabber
DECL|variable|keyboardGrabbing
DECL|variable|prevWin
DECL|variable|qwsServer
DECL|variable|qwsServerPrivate
DECL|variable|qws_keyModifiers
