DECL|function|sendEvent
DECL|function|sendIMEvent
DECL|function|sendQuery
DECL|macro|QWINDOWSYSTEM_QWS_H
DECL|typedef|QWSCursorMap
DECL|variable|QBrush
DECL|variable|QColor
DECL|variable|QImage
DECL|variable|QInputMethodEvent
DECL|variable|QVariant
DECL|variable|QWSBackingStore
DECL|variable|QWSClient
DECL|variable|QWSClientPrivate
DECL|variable|QWSCommand
DECL|variable|QWSConvertSelectionCommand
DECL|variable|QWSCursor
DECL|variable|QWSInputMethod
DECL|variable|QWSMouseHandler
DECL|variable|QWSRegionManager
DECL|variable|QWSServer
DECL|variable|QWSServerPrivate
DECL|variable|QWSSoundServer
DECL|variable|QWSSoundServerData
DECL|variable|QWSWindowSurface
