DECL|function|cleanupSystemCursorTable
DECL|function|createDropShadow
DECL|function|createSystemCursor
DECL|function|initializeCursor
DECL|function|set
DECL|function|setCursor
DECL|function|systemCursor
DECL|variable|busy_bits
DECL|variable|busym_bits
DECL|variable|closedhand_bits
DECL|variable|closedhandm_bits
DECL|variable|cur_arrow_bits
DECL|variable|cur_bdiag_bits
DECL|variable|cur_blank_bits
DECL|variable|cur_cross_bits
DECL|variable|cur_fdiag_bits
DECL|variable|cur_hor_bits
DECL|variable|cur_ibeam_bits
DECL|variable|cur_up_arrow_bits
DECL|variable|cur_ver_bits
DECL|variable|forbidden_bits
DECL|variable|forbiddenm_bits
DECL|variable|hsplit_bits
DECL|variable|hsplitm_bits
DECL|variable|mcur_arrow_bits
DECL|variable|mcur_bdiag_bits
DECL|variable|mcur_cross_bits
DECL|variable|mcur_fdiag_bits
DECL|variable|mcur_hor_bits
DECL|variable|mcur_ibeam_bits
DECL|variable|mcur_up_arrow_bits
DECL|variable|mcur_ver_bits
DECL|variable|openhand_bits
DECL|variable|openhandm_bits
DECL|variable|phand_bits
DECL|variable|phandm_bits
DECL|variable|size_all_data_bits
DECL|variable|size_all_mask_bits
DECL|variable|systemCursorTable
DECL|variable|systemCursorTableInit
DECL|variable|vsplit_bits
DECL|variable|vsplitm_bits
DECL|variable|wait_data_bits
DECL|variable|wait_mask_bits
DECL|variable|whatsthis_bits
DECL|variable|whatsthism_bits
