DECL|enumerator|Allocation
DECL|enumerator|Close
DECL|enumerator|Connected
DECL|enumerator|Creation
DECL|enumerator|DirectPaint
DECL|enumerator|Embed
DECL|enumerator|Focus
DECL|enumerator|Font
DECL|enumerator|FontRemoved
DECL|enumerator|Hide
DECL|enumerator|IMEvent
DECL|enumerator|IMInit
DECL|enumerator|IMQuery
DECL|enumerator|Key
DECL|enumerator|MaxWindowRect
DECL|enumerator|Mouse
DECL|enumerator|NEvent
DECL|enumerator|NoEvent
DECL|enumerator|PropertyDeleted
DECL|enumerator|PropertyNewValue
DECL|enumerator|PropertyNotify
DECL|enumerator|PropertyReply
DECL|enumerator|QCopMessage
DECL|enumerator|Region
DECL|enumerator|Region
DECL|enumerator|ScreenTransformation
DECL|enumerator|SelectionClear
DECL|enumerator|SelectionNotify
DECL|enumerator|SelectionRequest
DECL|enumerator|Show
DECL|enumerator|ShowMaximized
DECL|enumerator|ShowMinimized
DECL|enumerator|ShowNormal
DECL|enumerator|StartEmbed
DECL|enumerator|StopEmbed
DECL|enumerator|WindowOperation
DECL|enum|EventType
DECL|enum|Operation
DECL|enum|State
DECL|enum|Type
DECL|enum|Type
DECL|enum|Type
DECL|function|QWSConnectedEvent
DECL|function|QWSCreationEvent
DECL|function|QWSEmbedEvent
DECL|function|QWSEvent
DECL|function|QWSFocusEvent
DECL|function|QWSFontEvent
DECL|function|QWSIMEvent
DECL|function|QWSIMInitEvent
DECL|function|QWSIMQueryEvent
DECL|function|QWSKeyEvent
DECL|function|QWSMaxWindowRectEvent
DECL|function|QWSMouseEvent
DECL|function|QWSPropertyNotifyEvent
DECL|function|QWSPropertyReplyEvent
DECL|function|QWSQCopMessageEvent
DECL|function|QWSRegionEvent
DECL|function|QWSScreenTransformationEvent
DECL|function|QWSSelectionClearEvent
DECL|function|QWSSelectionNotifyEvent
DECL|function|QWSSelectionRequestEvent
DECL|function|QWSWindowOperationEvent
DECL|function|asMouse
DECL|function|setData
DECL|function|setData
DECL|function|setData
DECL|function|setData
DECL|function|setData
DECL|function|setData
DECL|function|setData
DECL|function|setData
DECL|function|setData
DECL|function|setData
DECL|function|setDataDirect
DECL|function|window
DECL|function|window
DECL|macro|QWSEVENT_QWS_H
DECL|member|channel
DECL|member|clientId
DECL|member|count
DECL|member|data
DECL|member|data
DECL|member|delta
DECL|member|display
DECL|member|existence
DECL|member|fontName
DECL|member|get_focus
DECL|member|id
DECL|member|is_auto_repeat
DECL|member|is_press
DECL|member|is_response
DECL|member|keycode
DECL|member|lchannel
DECL|member|ldata
DECL|member|len
DECL|member|len
DECL|member|lmessage
DECL|member|message
DECL|member|mimeType
DECL|member|mimeTypes
DECL|member|modifiers
DECL|member|nrectangles
DECL|member|nrectangles
DECL|member|objectid
DECL|member|op
DECL|member|property
DECL|member|property
DECL|member|property
DECL|member|property
DECL|member|property
DECL|member|rect
DECL|member|rectangles
DECL|member|region
DECL|member|replaceFrom
DECL|member|replaceLength
DECL|member|requestor
DECL|member|requestor
DECL|member|screen
DECL|member|servershmid
DECL|member|simpleData
DECL|member|simpleData
DECL|member|simpleData
DECL|member|simpleData
DECL|member|simpleData
DECL|member|simpleData
DECL|member|simpleData
DECL|member|simpleData
DECL|member|simpleData
DECL|member|simpleData
DECL|member|simpleData
DECL|member|simpleData
DECL|member|simpleData
DECL|member|simpleData
DECL|member|simpleData
DECL|member|simpleData
DECL|member|simpleData
DECL|member|simpleData
DECL|member|simpleData
DECL|member|simpleData
DECL|member|state
DECL|member|state
DECL|member|streamingData
DECL|member|streamingData
DECL|member|time
DECL|member|transformation
DECL|member|type
DECL|member|type
DECL|member|type
DECL|member|unicode
DECL|member|window
DECL|member|window
DECL|member|window
DECL|member|window
DECL|member|window
DECL|member|window
DECL|member|window
DECL|member|window
DECL|member|window
DECL|member|window
DECL|member|window
DECL|member|window
DECL|member|window
DECL|member|window
DECL|member|window
DECL|member|window
DECL|member|x_root
DECL|member|y_root
DECL|struct|QWSEvent
DECL|struct|QWSEvent
DECL|struct|QWSEvent
DECL|struct|QWSEvent
DECL|struct|QWSEvent
DECL|struct|QWSEvent
DECL|struct|QWSEvent
DECL|struct|QWSEvent
DECL|struct|QWSEvent
DECL|struct|QWSEvent
DECL|struct|QWSEvent
DECL|struct|QWSEvent
DECL|struct|QWSEvent
DECL|struct|QWSEvent
DECL|struct|QWSEvent
DECL|struct|QWSEvent
DECL|struct|QWSEvent
DECL|struct|QWSEvent
DECL|struct|QWSEvent
DECL|struct|QWSEvent
DECL|struct|QWSProtocolItem
DECL|struct|SimpleData
DECL|struct|SimpleData
DECL|struct|SimpleData
DECL|struct|SimpleData
DECL|struct|SimpleData
DECL|struct|SimpleData
DECL|struct|SimpleData
DECL|struct|SimpleData
DECL|struct|SimpleData
DECL|struct|SimpleData
DECL|struct|SimpleData
DECL|struct|SimpleData
DECL|struct|SimpleData
DECL|struct|SimpleData
DECL|struct|SimpleData
DECL|struct|SimpleData
DECL|struct|SimpleData
DECL|struct|SimpleData
DECL|struct|SimpleData
DECL|struct|SimpleData
