DECL|function|QWSLock
DECL|function|QWSLock
DECL|function|down
DECL|function|forceLock
DECL|function|getValue
DECL|function|hasLock
DECL|function|lock
DECL|function|unlock
DECL|function|up
DECL|function|wait
DECL|function|~QWSLock
