DECL|class|tst_QColor
DECL|function|achromaticHslHue
DECL|function|allowX11ColorNames
DECL|function|alpha
DECL|function|assignmentOoperator
DECL|function|black
DECL|function|blue
DECL|function|colorNames
DECL|function|constructNamedColorWithSpace
DECL|function|convertTo
DECL|function|cyan
DECL|function|dark
DECL|function|equalityOperator
DECL|function|fromCmyk
DECL|function|fromHsl
DECL|function|fromHsv
DECL|function|fromRgb
DECL|function|getCmyk
DECL|function|getHsl
DECL|function|getHsv
DECL|function|getRgb
DECL|function|getSetCheck
DECL|function|globalColors
DECL|function|globalColors_data
DECL|function|green
DECL|function|hue
DECL|function|hueHsl
DECL|function|isValid
DECL|function|isValid_data
DECL|function|light
DECL|function|lightness
DECL|function|magenta
DECL|function|name
DECL|function|name_data
DECL|function|red
DECL|function|rgb
DECL|function|rgba
DECL|function|saturation
DECL|function|saturationHsl
DECL|function|setAlpha
DECL|function|setBlue
DECL|function|setCmyk
DECL|function|setGreen
DECL|function|setHsl
DECL|function|setHsv
DECL|function|setNamedColor
DECL|function|setRed
DECL|function|setRgb
DECL|function|setRgba
DECL|function|setallowX11ColorNames
DECL|function|spec
DECL|function|specConstructor
DECL|function|specConstructor_data
DECL|function|toCmyk
DECL|function|toCmykNonDestructive
DECL|function|toCmyk_data
DECL|function|toHsl
DECL|function|toHslNonDestructive
DECL|function|toHsl_data
DECL|function|toHsv
DECL|function|toHsvNonDestructive
DECL|function|toHsv_data
DECL|function|toRgb
DECL|function|toRgbNonDestructive
DECL|function|toRgb_data
DECL|function|tst_QColor
DECL|function|value
DECL|function|veryFuzzyCompare
DECL|function|yellow
DECL|macro|rgb
DECL|macro|rgb
DECL|macro|rgb
DECL|member|name
DECL|member|value
DECL|struct|RGBData
DECL|variable|Spec
DECL|variable|rgbTbl
DECL|variable|rgbTblSize
