DECL|function|QKdeTheme
DECL|function|ResourceHelper
DECL|function|clear
DECL|function|createKdeTheme
DECL|function|createUnixTheme
DECL|function|globalSettingsFile
DECL|function|kdeColor
DECL|function|kdeIconThemeSearchPaths
DECL|function|readKdeFontSetting
DECL|function|readKdeSystemPalette
DECL|function|refresh
DECL|function|themeHint
DECL|function|themeHint
DECL|function|themeHint
DECL|function|xdgIconThemePaths
