DECL|function|GLWidget
DECL|function|animate
DECL|function|createBubbles
DECL|function|drawInstructions
DECL|function|initializeGL
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|paintEvent
DECL|function|qNormalizeAngle
DECL|function|resizeGL
DECL|function|setXRotation
DECL|function|setYRotation
DECL|function|setZRotation
DECL|function|setupViewport
DECL|function|showEvent
DECL|function|sizeHint
DECL|function|~GLWidget
DECL|macro|GL_MULTISAMPLE
