DECL|macro|QABSTRACTANIMATION_H
DECL|variable|QAbstractAnimationPrivate
DECL|variable|QAnimationDriver
DECL|variable|QAnimationDriverPrivate
DECL|variable|QAnimationGroup
DECL|variable|QSequentialAnimationGroup
