DECL|function|QAbstractAnimation
DECL|function|QAbstractAnimation
DECL|function|QAnimationDriver
DECL|function|QAnimationDriver
DECL|function|QDefaultAnimationDriver
DECL|function|QUnifiedTimer
DECL|function|advance
DECL|function|closestPauseAnimationTimeToFinish
DECL|function|currentLoop
DECL|function|currentLoopTime
DECL|function|currentTime
DECL|function|direction
DECL|function|ensureTimerUpdate
DECL|function|event
DECL|function|group
DECL|function|install
DECL|function|installAnimationDriver
DECL|function|instance
DECL|function|instance
DECL|function|isRunning
DECL|function|loopCount
DECL|function|pause
DECL|function|registerAnimation
DECL|function|registerRunningAnimation
DECL|function|restartAnimationTimer
DECL|function|resume
DECL|function|setCurrentTime
DECL|function|setDirection
DECL|function|setLoopCount
DECL|function|setPaused
DECL|function|setState
DECL|function|setTimingInterval
DECL|function|start
DECL|function|start
DECL|function|started
DECL|function|state
DECL|function|stop
DECL|function|stop
DECL|function|stopped
DECL|function|timerEvent
DECL|function|timerEvent
DECL|function|totalDuration
DECL|function|unregisterAnimation
DECL|function|unregisterRunningAnimation
DECL|function|updateAnimationTimer
DECL|function|updateAnimationsTime
DECL|function|updateDirection
DECL|function|updateState
DECL|function|~QAbstractAnimation
DECL|macro|DEFAULT_TIMER_INTERVAL
DECL|macro|STARTSTOP_TIMER_DELAY
