DECL|function|QAnimationGroup
DECL|function|QAnimationGroup
DECL|function|addAnimation
DECL|function|animationAt
DECL|function|animationCount
DECL|function|animationRemoved
DECL|function|clear
DECL|function|event
DECL|function|indexOfAnimation
DECL|function|insertAnimation
DECL|function|removeAnimation
DECL|function|takeAnimation
DECL|function|~QAnimationGroup
