DECL|class|tst_QDBusLocalCalls
DECL|function|asyncReplySignal
DECL|function|delayed
DECL|function|doCall
DECL|function|echo
DECL|function|echo
DECL|function|echo
DECL|function|echo
DECL|function|echo2
DECL|function|initTestCase
DECL|function|makeCalls
DECL|function|makeCallsComplex
DECL|function|makeCallsTwoRets
DECL|function|makeCallsVariant
DECL|function|makeCallsVariant_data
DECL|function|makeCalls_data
DECL|function|makeDelayedCalls
DECL|function|makeInvalidCalls
DECL|function|replyReceived
DECL|function|tst_QDBusLocalCalls
DECL|member|asyncReplyArgs
DECL|member|conn
