DECL|function|QWaylandWindowManagerIntegration
DECL|function|authenticateWithToken
DECL|function|createIntegration
DECL|function|mapClientToProcess
DECL|function|windowManager
DECL|function|wlHandleListenerGlobal
DECL|function|~QWaylandWindowManagerIntegration
