DECL|class|ModelIndexIterator
DECL|class|QAccessibleTabButton
DECL|function|ModelIndexIterator
DECL|function|QAccessibleAbstractScrollArea
DECL|function|QAccessibleComboBox
DECL|function|QAccessibleHeader
DECL|function|QAccessibleItemRow
DECL|function|QAccessibleItemView
DECL|function|QAccessibleScrollArea
DECL|function|QAccessibleTabBar
DECL|function|QAccessibleTabButton
DECL|function|abstractScrollArea
DECL|function|accessibleAt
DECL|function|accessibleChildren
DECL|function|actionCount
DECL|function|actionCount
DECL|function|actionText
DECL|function|actionText
DECL|function|actionText
DECL|function|caption
DECL|function|cellAtIndex
DECL|function|child
DECL|function|child
DECL|function|child
DECL|function|child
DECL|function|childAt
DECL|function|childAt
DECL|function|childAt
DECL|function|childAt
DECL|function|childAt
DECL|function|childCount
DECL|function|childCount
DECL|function|childCount
DECL|function|childCount
DECL|function|childCount
DECL|function|childCount
DECL|function|childCount
DECL|function|childIndex
DECL|function|childIndex
DECL|function|childIndex
DECL|function|children
DECL|function|columnCount
DECL|function|columnDescription
DECL|function|columnHeader
DECL|function|columnIndex
DECL|function|columnSpan
DECL|function|comboBox
DECL|function|current
DECL|function|description
DECL|function|description
DECL|function|doAction
DECL|function|doAction
DECL|function|doAction
DECL|function|doAction
DECL|function|doAction
DECL|function|doAction
DECL|function|elementType
DECL|function|entryFromIndex
DECL|function|header
DECL|function|horizontalHeader
DECL|function|horizontalHeader
DECL|function|index
DECL|function|indexOfChild
DECL|function|indexOfChild
DECL|function|indexOfChild
DECL|function|indexOfChild
DECL|function|indexOfChild
DECL|function|indexOfChild
DECL|function|invokeMethod
DECL|function|isColumnSelected
DECL|function|isHidden
DECL|function|isLeftToRight
DECL|function|isRowSelected
DECL|function|isSelected
DECL|function|isValid
DECL|function|isValid
DECL|function|isValid
DECL|function|isValid
DECL|function|isValidChildRole
DECL|function|itemView
DECL|function|keyBindings
DECL|function|keyBindings
DECL|function|localizedName
DECL|function|localizedName
DECL|function|logicalFromChild
DECL|function|name
DECL|function|name
DECL|function|navigate
DECL|function|navigate
DECL|function|navigate
DECL|function|navigate
DECL|function|navigate
DECL|function|next
DECL|function|object
DECL|function|object
DECL|function|object
DECL|function|parent
DECL|function|parent
DECL|function|rect
DECL|function|rect
DECL|function|rect
DECL|function|rect
DECL|function|rect
DECL|function|rect
DECL|function|relationTo
DECL|function|relationTo
DECL|function|removeInvisibleWidgetsFromList
DECL|function|role
DECL|function|role
DECL|function|role
DECL|function|role
DECL|function|role
DECL|function|rowAt
DECL|function|rowCount
DECL|function|rowDescription
DECL|function|rowHeader
DECL|function|rowIndex
DECL|function|rowSpan
DECL|function|selectColumn
DECL|function|selectRow
DECL|function|selectedColumnCount
DECL|function|selectedColumns
DECL|function|selectedRowCount
DECL|function|selectedRows
DECL|function|selection
DECL|function|setSelected
DECL|function|setText
DECL|function|setText
DECL|function|setText
DECL|function|setText
DECL|function|state
DECL|function|state
DECL|function|state
DECL|function|state
DECL|function|state
DECL|function|state
DECL|function|summary
DECL|function|tabBar
DECL|function|text
DECL|function|text
DECL|function|text
DECL|function|text
DECL|function|text
DECL|function|text
DECL|function|text
DECL|function|text_helper
DECL|function|toCursorAction
DECL|function|treeLevel
DECL|function|unselectColumn
DECL|function|unselectRow
DECL|function|userActionCount
DECL|function|userActionCount
DECL|function|verticalHeader
DECL|function|verticalHeader
DECL|member|list
DECL|member|m_current
DECL|member|m_index
DECL|member|m_parent
DECL|member|m_view
DECL|member|table
DECL|member|tree
