DECL|macro|COMPLEXWIDGETS_H
DECL|variable|QAbstractButton
DECL|variable|QAbstractScrollArea
DECL|variable|QAccessibleAbstractScrollArea
DECL|variable|QAccessibleWidget
DECL|variable|QComboBox
DECL|variable|QHeaderView
DECL|variable|QScrollArea
DECL|variable|QTabBar
DECL|variable|QTitleBar
