DECL|class|QAccessibleTabButton
DECL|function|QAccessibleAbstractScrollArea
DECL|function|QAccessibleComboBox
DECL|function|QAccessibleScrollArea
DECL|function|QAccessibleTabBar
DECL|function|QAccessibleTabButton
DECL|function|abstractScrollArea
DECL|function|accessibleChildren
DECL|function|actionNames
DECL|function|actionNames
DECL|function|child
DECL|function|child
DECL|function|child
DECL|function|child
DECL|function|childAt
DECL|function|childAt
DECL|function|childAt
DECL|function|childCount
DECL|function|childCount
DECL|function|childCount
DECL|function|childCount
DECL|function|comboBox
DECL|function|doAction
DECL|function|doAction
DECL|function|elementType
DECL|function|indexOfChild
DECL|function|indexOfChild
DECL|function|indexOfChild
DECL|function|indexOfChild
DECL|function|interface_cast
DECL|function|isLeftToRight
DECL|function|isValid
DECL|function|isValid
DECL|function|keyBindingsForAction
DECL|function|keyBindingsForAction
DECL|function|localizedActionDescription
DECL|function|object
DECL|function|parent
DECL|function|rect
DECL|function|removeInvisibleWidgetsFromList
DECL|function|role
DECL|function|selection
DECL|function|setSelected
DECL|function|setText
DECL|function|state
DECL|function|tabBar
DECL|function|text
DECL|function|text
DECL|function|text
DECL|function|~QAccessibleTabBar
DECL|member|m_index
DECL|member|m_parent
