DECL|function|QAccessibleTable2
DECL|function|QAccessibleTable2Cell
DECL|function|QAccessibleTable2HeaderCell
DECL|function|caption
DECL|function|cell
DECL|function|cellAt
DECL|function|cellAt
DECL|function|child
DECL|function|child
DECL|function|child
DECL|function|childAt
DECL|function|childAt
DECL|function|childCount
DECL|function|childCount
DECL|function|childFromLogical
DECL|function|columnCount
DECL|function|columnDescription
DECL|function|columnExtent
DECL|function|columnHeaderCells
DECL|function|columnIndex
DECL|function|columnsInserted
DECL|function|columnsMoved
DECL|function|columnsRemoved
DECL|function|horizontalHeader
DECL|function|horizontalHeader
DECL|function|indexFromLogical
DECL|function|indexOfChild
DECL|function|indexOfChild
DECL|function|isColumnSelected
DECL|function|isExpandable
DECL|function|isRowSelected
DECL|function|isRowSelected
DECL|function|isSelected
DECL|function|isValid
DECL|function|isValid
DECL|function|logicalIndex
DECL|function|modelChange
DECL|function|modelReset
DECL|function|navigate
DECL|function|navigate
DECL|function|navigate
DECL|function|navigate
DECL|function|parent
DECL|function|parent
DECL|function|parent
DECL|function|rect
DECL|function|rect
DECL|function|rect
DECL|function|relationTo
DECL|function|relationTo
DECL|function|relationTo
DECL|function|relationTo
DECL|function|role
DECL|function|role
DECL|function|role
DECL|function|rowColumnExtents
DECL|function|rowCount
DECL|function|rowCount
DECL|function|rowDescription
DECL|function|rowDescription
DECL|function|rowExtent
DECL|function|rowHeaderCells
DECL|function|rowIndex
DECL|function|rowsInserted
DECL|function|rowsMoved
DECL|function|rowsRemoved
DECL|function|selectColumn
DECL|function|selectRow
DECL|function|selectRow
DECL|function|selectedCellCount
DECL|function|selectedCells
DECL|function|selectedColumnCount
DECL|function|selectedColumns
DECL|function|selectedRowCount
DECL|function|selectedRows
DECL|function|setText
DECL|function|setText
DECL|function|state
DECL|function|state
DECL|function|state
DECL|function|summary
DECL|function|table
DECL|function|text
DECL|function|text
DECL|function|text
DECL|function|unselectColumn
DECL|function|unselectRow
DECL|function|verticalHeader
DECL|function|verticalHeader
DECL|function|~QAccessibleTable2
