DECL|function|QAccessibleCalendarWidget
DECL|function|QAccessibleDialogButtonBox
DECL|function|QAccessibleDockWidget
DECL|function|QAccessibleMainWindow
DECL|function|QAccessibleMdiArea
DECL|function|QAccessibleMdiSubWindow
DECL|function|QAccessibleStackedWidget
DECL|function|QAccessibleTextBrowser
DECL|function|QAccessibleTextEdit
DECL|function|QAccessibleTitleBar
DECL|function|QAccessibleToolBox
DECL|function|QAccessibleWorkspace
DECL|function|addSelection
DECL|function|attributes
DECL|function|calendarView
DECL|function|calendarWidget
DECL|function|characterCount
DECL|function|characterRect
DECL|function|child
DECL|function|child
DECL|function|child
DECL|function|child
DECL|function|child
DECL|function|child
DECL|function|child
DECL|function|child
DECL|function|childAt
DECL|function|childAt
DECL|function|childAt
DECL|function|childCount
DECL|function|childCount
DECL|function|childCount
DECL|function|childCount
DECL|function|childCount
DECL|function|childCount
DECL|function|childCount
DECL|function|childCount
DECL|function|childWidgets
DECL|function|copyText
DECL|function|cursorForRange
DECL|function|cursorPosition
DECL|function|cutText
DECL|function|deleteText
DECL|function|distance
DECL|function|dockWidget
DECL|function|dockWidget
DECL|function|dockWidgetLayout
DECL|function|indexOfChild
DECL|function|indexOfChild
DECL|function|indexOfChild
DECL|function|indexOfChild
DECL|function|indexOfChild
DECL|function|indexOfChild
DECL|function|indexOfChild
DECL|function|indexOfChild
DECL|function|insertText
DECL|function|interface_cast
DECL|function|invokeMethod
DECL|function|invokeMethod
DECL|function|invokeMethod
DECL|function|invokeMethod
DECL|function|isValid
DECL|function|mainWindow
DECL|function|mdiArea
DECL|function|mdiAreaNavigate
DECL|function|mdiSubWindow
DECL|function|navigate
DECL|function|navigate
DECL|function|navigate
DECL|function|navigate
DECL|function|navigate
DECL|function|navigationBar
DECL|function|object
DECL|function|offsetAtPoint
DECL|function|parent
DECL|function|pasteText
DECL|function|qTextBlockAt
DECL|function|qTextBlockPosition
DECL|function|rect
DECL|function|rect
DECL|function|rect
DECL|function|relationTo
DECL|function|removeSelection
DECL|function|replaceText
DECL|function|role
DECL|function|role
DECL|function|role
DECL|function|scrollToSubstring
DECL|function|selection
DECL|function|selectionCount
DECL|function|setAttributes
DECL|function|setCursorPosition
DECL|function|setSelection
DECL|function|setText
DECL|function|setText
DECL|function|setText
DECL|function|stackedWidget
DECL|function|state
DECL|function|state
DECL|function|text
DECL|function|text
DECL|function|text
DECL|function|text
DECL|function|textAfterOffset
DECL|function|textAtOffset
DECL|function|textBeforeOffset
DECL|function|textEdit
DECL|function|toolBox
DECL|function|workspace
