DECL|function|QAccessibleMenu
DECL|function|QAccessibleMenuBar
DECL|function|QAccessibleMenuItem
DECL|function|action
DECL|function|actionNames
DECL|function|child
DECL|function|child
DECL|function|child
DECL|function|childAt
DECL|function|childAt
DECL|function|childCount
DECL|function|childCount
DECL|function|childCount
DECL|function|doAction
DECL|function|getOrCreateMenu
DECL|function|indexOfChild
DECL|function|indexOfChild
DECL|function|indexOfChild
DECL|function|interface_cast
DECL|function|isValid
DECL|function|keyBindingsForAction
DECL|function|menu
DECL|function|menuBar
DECL|function|object
DECL|function|owner
DECL|function|parent
DECL|function|parent
DECL|function|rect
DECL|function|role
DECL|function|role
DECL|function|setText
DECL|function|state
DECL|function|text
DECL|function|text
DECL|function|~QAccessibleMenuItem
