DECL|function|QAccessibleAbstractSlider
DECL|function|QAccessibleAbstractSpinBox
DECL|function|QAccessibleDial
DECL|function|QAccessibleDoubleSpinBox
DECL|function|QAccessibleScrollBar
DECL|function|QAccessibleSlider
DECL|function|QAccessibleSpinBox
DECL|function|abstractSlider
DECL|function|abstractSpinBox
DECL|function|actionText
DECL|function|childCount
DECL|function|currentValue
DECL|function|currentValue
DECL|function|defaultAction
DECL|function|dial
DECL|function|doAction
DECL|function|doAction
DECL|function|doubleSpinBox
DECL|function|invokeMethod
DECL|function|invokeMethod
DECL|function|invokeMethod
DECL|function|invokeMethod
DECL|function|maximumValue
DECL|function|maximumValue
DECL|function|minimumValue
DECL|function|minimumValue
DECL|function|rect
DECL|function|role
DECL|function|scrollBar
DECL|function|setCurrentValue
DECL|function|setCurrentValue
DECL|function|slider
DECL|function|spinBox
DECL|function|state
DECL|function|text
DECL|function|text
DECL|function|text
DECL|function|text
DECL|function|text
