DECL|function|QAccessibleButton
DECL|function|QAccessibleDisplay
DECL|function|QAccessibleGroupBox
DECL|function|QAccessibleLineEdit
DECL|function|QAccessibleProgressBar
DECL|function|QAccessibleToolButton
DECL|function|actionNames
DECL|function|actionNames
DECL|function|actionNames
DECL|function|addSelection
DECL|function|attributes
DECL|function|button
DECL|function|characterCount
DECL|function|characterRect
DECL|function|child
DECL|function|childCount
DECL|function|currentValue
DECL|function|cursorPosition
DECL|function|deleteText
DECL|function|doAction
DECL|function|doAction
DECL|function|doAction
DECL|function|groupBox
DECL|function|imageDescription
DECL|function|imagePosition
DECL|function|imageSize
DECL|function|insertText
DECL|function|interface_cast
DECL|function|interface_cast
DECL|function|interface_cast
DECL|function|isSplitButton
DECL|function|keyBindingsForAction
DECL|function|keyBindingsForAction
DECL|function|lineEdit
DECL|function|maximumValue
DECL|function|minimumStepSize
DECL|function|minimumValue
DECL|function|offsetAtPoint
DECL|function|progressBar
DECL|function|relations
DECL|function|relations
DECL|function|removeSelection
DECL|function|replaceText
DECL|function|role
DECL|function|role
DECL|function|scrollToSubstring
DECL|function|selection
DECL|function|selectionCount
DECL|function|setCursorPosition
DECL|function|setSelection
DECL|function|setText
DECL|function|state
DECL|function|state
DECL|function|state
DECL|function|state
DECL|function|text
DECL|function|text
DECL|function|text
DECL|function|text
DECL|function|text
DECL|function|text
DECL|function|textAfterOffset
DECL|function|textAtOffset
DECL|function|textBeforeOffset
DECL|function|toolButton
