DECL|function|QAccessibleButton
DECL|function|QAccessibleDisplay
DECL|function|QAccessibleLineEdit
DECL|function|QAccessibleProgressBar
DECL|function|QAccessibleToolButton
DECL|function|actionCount
DECL|function|actionCount
DECL|function|actionText
DECL|function|actionText
DECL|function|addSelection
DECL|function|attributes
DECL|function|button
DECL|function|characterCount
DECL|function|characterRect
DECL|function|childCount
DECL|function|currentValue
DECL|function|cursorPosition
DECL|function|description
DECL|function|doAction
DECL|function|doAction
DECL|function|doAction
DECL|function|imageDescription
DECL|function|imagePosition
DECL|function|imageSize
DECL|function|invokeMethodEx
DECL|function|isSplitButton
DECL|function|keyBindings
DECL|function|lineEdit
DECL|function|localizedName
DECL|function|maximumValue
DECL|function|minimumValue
DECL|function|name
DECL|function|navigate
DECL|function|offsetAtPoint
DECL|function|progressBar
DECL|function|rect
DECL|function|relationTo
DECL|function|removeSelection
DECL|function|role
DECL|function|role
DECL|function|scrollToSubstring
DECL|function|selection
DECL|function|selectionCount
DECL|function|setCursorPosition
DECL|function|setSelection
DECL|function|setText
DECL|function|state
DECL|function|state
DECL|function|state
DECL|function|text
DECL|function|text
DECL|function|text
DECL|function|text
DECL|function|text
DECL|function|textAfterOffset
DECL|function|textAtOffset
DECL|function|textBeforeOffset
DECL|function|toolButton
