DECL|class|EventListener
DECL|class|tst_QSoftKeyManager
DECL|function|EventListener
DECL|function|checkSoftkeyEnableStates
DECL|function|cleanup
DECL|function|cleanupTestCase
DECL|function|eventFilter
DECL|function|handleCommand
DECL|function|init
DECL|function|initTestCase
DECL|function|noMergingOverWindowBoundary
DECL|function|resetCounts
DECL|function|simulateSymbianCommand
DECL|function|tst_QSoftKeyManager
DECL|function|updateSoftKeysCompressed
DECL|function|~tst_QSoftKeyManager
DECL|member|numUpdateSoftKeys
DECL|variable|s60CommandStart
