DECL|class|ContextMenuWidget
DECL|class|EventLogger
DECL|class|EventSpy
DECL|class|HoverButton
DECL|class|InputMethod_LineEdit
DECL|class|MainWidget
DECL|class|MyProxyWidget
DECL|class|Scene
DECL|class|ScrollWidget
DECL|class|SubQGraphicsProxyWidget
DECL|class|View
DECL|class|WheelWidget
DECL|class|tst_QGraphicsProxyWidget
DECL|function|ContextMenuWidget
DECL|function|EventLogger
DECL|function|EventSpy
DECL|function|HoverButton
DECL|function|MainWidget
DECL|function|QTBUG_6986_sendMouseEventToAlienWidget
DECL|function|Scene
DECL|function|ScrollWidget
DECL|function|SubQGraphicsProxyWidget
DECL|function|View
DECL|function|WheelWidget
DECL|function|actionsContextMenu
DECL|function|actionsContextMenu_data
DECL|function|autoShow
DECL|function|bypassGraphicsProxyWidget
DECL|function|bypassGraphicsProxyWidget_data
DECL|function|call_eventFilter
DECL|function|call_focusInEvent
DECL|function|call_focusNextPrevChild
DECL|function|call_focusOutEvent
DECL|function|call_hideEvent
DECL|function|call_hoverEnterEvent
DECL|function|call_hoverLeaveEvent
DECL|function|call_hoverMoveEvent
DECL|function|call_keyPressEvent
DECL|function|call_keyReleaseEvent
DECL|function|call_mouseDoubleClickEvent
DECL|function|call_mouseMoveEvent
DECL|function|call_mousePressEvent
DECL|function|call_mouseReleaseEvent
DECL|function|call_resizeEvent
DECL|function|call_showEvent
DECL|function|call_sizeHint
DECL|function|changingCursor_basic
DECL|function|checkMenu
DECL|function|childPos
DECL|function|childPos_data
DECL|function|cleanup
DECL|function|cleanupTestCase
DECL|function|clickFocus
DECL|function|comboboxWindowFlags
DECL|function|contextMenuEvent
DECL|function|createProxyForChildWidget
DECL|function|deleteProxyForChildWidget
DECL|function|dontCrashWhenDie
DECL|function|dragDrop
DECL|function|enterEvent
DECL|function|event
DECL|function|event
DECL|function|event
DECL|function|eventFilter
DECL|function|eventFilter
DECL|function|eventFilter
DECL|function|eventFilter
DECL|function|eventFilter_data
DECL|function|focusInEvent
DECL|function|focusInEventNoWidget
DECL|function|focusInEvent_data
DECL|function|focusNextPrevChild
DECL|function|focusNextPrevChild_data
DECL|function|focusOutEvent
DECL|function|focusOutEvent
DECL|function|focusOutEvent_data
DECL|function|fontPropagation
DECL|function|hideButton
DECL|function|hoverEnterLeaveEvent
DECL|function|hoverEnterLeaveEvent_data
DECL|function|hoverMoveEvent
DECL|function|hoverMoveEvent_data
DECL|function|init
DECL|function|initTestCase
DECL|function|inputMethod
DECL|function|keyPressEvent
DECL|function|keyPressEvent_data
DECL|function|keyReleaseEvent
DECL|function|keyReleaseEvent_data
DECL|function|leaveEvent
DECL|function|makeDndEvent
DECL|function|maximumSize
DECL|function|minimumSize
DECL|function|mouseDoubleClickEvent
DECL|function|mouseDoubleClickEvent_data
DECL|function|mouseMoveEvent
DECL|function|mousePressReleaseEvent
DECL|function|mousePressReleaseEvent_data
DECL|function|paint
DECL|function|paint
DECL|function|paint
DECL|function|paintEvent
DECL|function|paintEvent
DECL|function|paintEvent
DECL|function|paint_2
DECL|function|palettePropagation
DECL|function|popup_basic
DECL|function|popup_subwidget
DECL|function|qgraphicsproxywidget
DECL|function|qgraphicsproxywidget_data
DECL|function|resizeEvent
DECL|function|resizeEvent_data
DECL|function|resize_simple
DECL|function|resize_simple_data
DECL|function|scrollUpdate
DECL|function|sendMouseMove
DECL|function|setFocus_complexTwoWidgets
DECL|function|setFocus_simpleTwoWidgets
DECL|function|setFocus_simpleWidget
DECL|function|setWidget
DECL|function|setWidget_data
DECL|function|setWidget_ownership
DECL|function|setWidget_simple
DECL|function|sizeHint
DECL|function|sizeHint_data
DECL|function|sizePolicy
DECL|function|stylePropagation
DECL|function|symmetricEnabled
DECL|function|symmetricMove
DECL|function|symmetricResize
DECL|function|symmetricVisible
DECL|function|tabFocus_complexTwoWidgets
DECL|function|tabFocus_complexWidget
DECL|function|tabFocus_simpleTwoWidgets
DECL|function|tabFocus_simpleWidget
DECL|function|tooltip_basic
DECL|function|updateAndDelete
DECL|function|updateScroll
DECL|function|wheelEvent
DECL|function|wheelEvent
DECL|function|windowFlags
DECL|function|windowFlags_data
DECL|function|windowFrameMargins
DECL|function|windowOpacity
DECL|member|button
DECL|member|counts
DECL|member|embeddedPopup
DECL|member|enterCount
DECL|member|focusOut
DECL|member|gotContextMenuEvent
DECL|member|hoverButton
DECL|member|hoverEnter
DECL|member|hoverLeave
DECL|member|hoverLeaveReceived
DECL|member|hoverMove
DECL|member|inputMethodEvents
DECL|member|item
DECL|member|keyPress
DECL|member|layout
DECL|member|leaveCount
DECL|member|moveCount
DECL|member|npaints
DECL|member|npaints
DECL|member|paintCount
DECL|member|paintEventRegion
DECL|member|paintEventRegion
DECL|member|scene
DECL|member|topButton
DECL|member|view
DECL|member|wheelEventCalled
DECL|member|widget
