DECL|class|QLinuxFbIntegrationPrivate
DECL|function|QLinuxFbIntegration
DECL|function|QLinuxFbIntegrationPrivate
DECL|function|QLinuxFbScreen
DECL|function|blank
DECL|function|closeTty
DECL|function|connect
DECL|function|createPalette
DECL|function|createPixmapData
DECL|function|createPlatformWindow
DECL|function|createWindowSurface
DECL|function|doRedraw
DECL|function|fontDatabase
DECL|function|hasCapability
DECL|function|initDevice
DECL|function|openTty
DECL|function|setFormat
DECL|function|setGeometry
DECL|function|setPixelFormat
DECL|function|~QLinuxFbIntegration
DECL|function|~QLinuxFbIntegrationPrivate
DECL|member|blank
DECL|member|displaySpec
DECL|member|doGenericColors
DECL|member|doGraphicsMode
DECL|member|fd
DECL|member|oldKdMode
DECL|member|startupd
DECL|member|startuph
DECL|member|startupw
DECL|member|ttyDevice
DECL|member|ttyfd
