DECL|class|Foo
DECL|class|MyProxyFactory
DECL|class|ReceiverThread
DECL|class|RemoteCloseErrorServer
DECL|class|SocketPair
DECL|class|TestThread
DECL|class|TestThread2
DECL|class|tst_QTcpSocket
DECL|enumerator|AuthBasic
DECL|enumerator|AuthMask
DECL|enumerator|AuthNtlm
DECL|enumerator|HttpProxy
DECL|enumerator|NoAuth
DECL|enumerator|NoProxy
DECL|enumerator|Socks5Proxy
DECL|enumerator|TypeMask
DECL|enum|ProxyTests
DECL|function|Foo
DECL|function|MyProxyFactory
DECL|function|ReceiverThread
DECL|function|RemoteCloseErrorServer
DECL|function|SocketPair
DECL|function|abortiveClose
DECL|function|abortiveClose_abortSlot
DECL|function|atEnd
DECL|function|bind
DECL|function|bind_data
DECL|function|blockingIMAP
DECL|function|cleanup
DECL|function|cleanup
DECL|function|clear
DECL|function|closed
DECL|function|connectDisconnectConnectDisconnect
DECL|function|connectToLocalHostNoService
DECL|function|connectToMultiIP
DECL|function|connectedToIt
DECL|function|connectionRefused
DECL|function|constructing
DECL|function|create
DECL|function|data
DECL|function|delayedClose
DECL|function|disconnectWhileConnecting
DECL|function|disconnectWhileConnectingNoEventLoop
DECL|function|disconnectWhileConnectingNoEventLoop_data
DECL|function|disconnectWhileConnecting_data
DECL|function|disconnectWhileLookingUp
DECL|function|disconnectWhileLookingUp_data
DECL|function|doIt
DECL|function|dontCloseOnTimeout
DECL|function|downloadBigFile
DECL|function|downloadBigFileSlot
DECL|function|earlySocketBytesSent
DECL|function|earlySocketReadyRead
DECL|function|enterLoop
DECL|function|enterLoopSlot
DECL|function|exitLoop
DECL|function|exitLoop
DECL|function|exitLoopSlot
DECL|function|expectedReplyIMAP
DECL|function|fetchExpectedReplyIMAP
DECL|function|flush
DECL|function|getConnection
DECL|function|getData
DECL|function|hostLookupSlot
DECL|function|hostNotFound
DECL|function|increaseReadBufferSize
DECL|function|init
DECL|function|initTestCase
DECL|function|initTestCase_data
DECL|function|invalidProxy
DECL|function|invalidProxy_data
DECL|function|linuxKernelBugLocalSocket
DECL|function|listen
DECL|function|localAddressEmptyOnBSD
DECL|function|moveToThread0
DECL|function|nestedEventLoopInErrorSlot
DECL|function|newSocket
DECL|function|nonBlockingIMAP
DECL|function|nonBlockingIMAP_bytesWritten
DECL|function|nonBlockingIMAP_closed
DECL|function|nonBlockingIMAP_connected
DECL|function|nonBlockingIMAP_hostFound
DECL|function|nonBlockingIMAP_readyRead
DECL|function|openCloseOpenClose
DECL|function|partialRead
DECL|function|proxyAuthenticationRequired
DECL|function|proxyAuthenticationRequired
DECL|function|proxyAuthenticationRequired
DECL|function|proxyFactory
DECL|function|proxyFactory_data
DECL|function|qtbug14268_peek
DECL|function|queryProxy
DECL|function|readAllAfterClose
DECL|function|readChunks
DECL|function|readLine
DECL|function|readLineString
DECL|function|readRegularFile_readyRead
DECL|function|readyReadSignalsAfterWaitForReadyRead
DECL|function|recursiveReadyRead
DECL|function|recursiveReadyReadSlot
DECL|function|remoteCloseError
DECL|function|remoteCloseErrorSlot
DECL|function|run
DECL|function|run
DECL|function|run
DECL|function|setInvalidSocketDescriptor
DECL|function|setSocketDescriptor
DECL|function|setSocketOption
DECL|function|socketDescriptor
DECL|function|socketInAThread
DECL|function|socketsConstructedBeforeEventLoop
DECL|function|socketsInThreads
DECL|function|suddenRemoteDisconnect
DECL|function|suddenRemoteDisconnect_data
DECL|function|synchronousApi
DECL|function|taskQtBug5799ConnectionErrorEventLoop
DECL|function|taskQtBug5799ConnectionErrorWaitForConnected
DECL|function|taskQtBug7054TimeoutErrorResetting
DECL|function|timeout
DECL|function|timeoutConnect
DECL|function|timeoutConnect_data
DECL|function|tst_QTcpSocket
DECL|function|unget
DECL|function|waitForBytesWritten
DECL|function|waitForBytesWrittenMinusOne
DECL|function|waitForConnectedInHostLookupSlot
DECL|function|waitForConnectedInHostLookupSlot2
DECL|function|waitForReadyRead
DECL|function|waitForReadyReadInASlot
DECL|function|waitForReadyReadInASlotSlot
DECL|function|waitForReadyReadMinusOne
DECL|function|zeroAndMinusOneReturns
DECL|function|~Foo
DECL|function|~ReceiverThread
DECL|function|~tst_QTcpSocket
DECL|macro|INVALID_SOCKET
DECL|macro|NOMINMAX
DECL|macro|SOCKET
DECL|member|attemptedToConnect
DECL|member|bytesAvailable
DECL|member|callCount
DECL|member|count
DECL|member|earlyBytesWrittenCount
DECL|member|earlyConstructedSockets
DECL|member|earlyReadyReadCount
DECL|member|endPoints
DECL|member|exitCode
DECL|member|expectedLength
DECL|member|expectedReplyIMAP_cached
DECL|member|lastQuery
DECL|member|loopLevel
DECL|member|loopLevel
DECL|member|networkTimeout
DECL|member|nonBlockingIMAP_data
DECL|member|nonBlockingIMAP_socket
DECL|member|nonBlockingIMAP_totalWritten
DECL|member|numConnections
DECL|member|ok
DECL|member|proxyAuthCalled
DECL|member|quit
DECL|member|readingBody
DECL|member|receivedData
DECL|member|server
DECL|member|serverPort
DECL|member|sock
DECL|member|socket
DECL|member|socketData
DECL|member|stressTestDir
DECL|member|timer
DECL|member|tmpSocket
DECL|member|toReturn
