DECL|class|tst_QtConcurrentFilter
DECL|function|filter
DECL|function|filtered
DECL|function|filteredReduced
DECL|function|filterfn
DECL|function|incrementalResults
DECL|function|noDetatch
DECL|function|resultAt
DECL|function|stlContainers
DECL|function|waitFilterfn
