DECL|class|MyChild
DECL|class|tst_QWorkspace
DECL|function|MyChild
DECL|function|accelActivated
DECL|function|accelPropagation
DECL|function|activeChanged
DECL|function|changeModified
DECL|function|changeWindowTitle
DECL|function|childSize
DECL|function|cleanup
DECL|function|cleanupTestCase
DECL|function|fixedSize
DECL|function|getSetCheck
DECL|function|init
DECL|function|initTestCase
DECL|function|nativeSubWindows
DECL|function|showWindows
DECL|function|sizeHint
DECL|function|task206368
DECL|function|tst_QWorkspace
DECL|function|windowActivated
DECL|function|windowActivatedWithMinimize
DECL|function|windowActivated_data
DECL|function|~tst_QWorkspace
DECL|member|accelPressed
DECL|member|activeWidget
