DECL|class|Window
DECL|class|tst_QWindow
DECL|function|Window
DECL|function|event
DECL|function|isActive
DECL|function|mapGlobal
DECL|function|positioning
DECL|function|received
DECL|function|reset
DECL|member|m_received
DECL|variable|tst_QWindow
