DECL|class|TranslatorThread
DECL|class|tst_QTranslator
DECL|function|cleanup
DECL|function|event
DECL|function|init
DECL|function|load
DECL|function|load2
DECL|function|loadDirectory
DECL|function|loadFromResource
DECL|function|plural
DECL|function|run
DECL|function|testLanguageChange
DECL|function|threadLoad
DECL|function|translate_qm_file_generated_with_msgfmt
DECL|function|tst_QTranslator
DECL|function|~tst_QTranslator
DECL|member|languageChangeEventCounter
