DECL|enumerator|QtCocoaEventSubTypePostMessage
DECL|enumerator|QtCocoaEventSubTypeWakeup
DECL|function|qt_mac_QStringListToNSMutableArray
DECL|function|qt_mac_resolveOption
DECL|function|qt_mac_resolveOption
DECL|macro|QCOCOAHELPERS_H
DECL|variable|QPixmap
DECL|variable|QString
