DECL|macro|check
DECL|macro|old_slots
DECL|macro|old_slots
DECL|macro|slots
DECL|macro|slots
DECL|macro|slots
DECL|typedef|AEDescList
DECL|typedef|AERecord
DECL|typedef|AppleEvent
DECL|typedef|CGContextRef
DECL|typedef|CGImageRef
DECL|typedef|CGRect
DECL|typedef|EventHandlerCallRef
DECL|typedef|EventRef
DECL|typedef|GDHandle
DECL|typedef|GDPtr
DECL|typedef|HIMutableShapeRef
DECL|typedef|HIShapeRef
DECL|typedef|IconRef
DECL|typedef|MenuRef
DECL|typedef|OSEventRef
DECL|typedef|OSEventRef
DECL|typedef|OSMenuRef
DECL|typedef|OSMenuRef
DECL|typedef|OSPasteboardRef
DECL|typedef|OSStatus
DECL|typedef|OSStatus
DECL|typedef|OSViewRef
DECL|typedef|OSViewRef
DECL|typedef|OSWindowRef
DECL|typedef|OSWindowRef
DECL|typedef|PasteboardRef
DECL|typedef|RgnHandle
