DECL|function|clear
DECL|macro|QT_MAC_P_H
DECL|macro|check
DECL|member|buttons
DECL|member|lastAction
DECL|member|lastOperation
DECL|member|modifiers
DECL|member|rect
DECL|struct|QMacDndAnswerRecord
DECL|variable|QDragMoveEvent
DECL|variable|QMacInternalPasteboardMime
DECL|variable|QMimeData
DECL|variable|QWidget
