DECL|class|QSslSocketPtr
DECL|class|tst_QSslSocket_onDemandCertificates_member
DECL|enumerator|AuthBasic
DECL|enumerator|AuthMask
DECL|enumerator|AuthNtlm
DECL|enumerator|HttpProxy
DECL|enumerator|NoAuth
DECL|enumerator|NoProxy
DECL|enumerator|Socks5Proxy
DECL|enumerator|TypeMask
DECL|enum|ProxyTests
DECL|function|QSslSocketPtr
DECL|function|cleanup
DECL|function|init
DECL|function|initTestCase
DECL|function|initTestCase_data
DECL|function|newSocket
DECL|function|onDemandRootCertLoadingMemberMethods
DECL|function|operator QSslSocket *
DECL|function|proxyAuthenticationRequired
DECL|function|tst_QSslSocket_onDemandCertificates_member
DECL|function|~tst_QSslSocket_onDemandCertificates_member
DECL|member|proxyAuthCalled
DECL|member|socket
