DECL|class|tst_QTextScriptEngine
DECL|function|bengali
DECL|function|bengali_data
DECL|function|cleanup
DECL|function|combiningMarks_qtbug15675
DECL|function|controlInSyllable_qtbug14204
DECL|function|devanagari
DECL|function|devanagari_data
DECL|function|doShapingTests
DECL|function|greek
DECL|function|greek_data
DECL|function|gurmukhi
DECL|function|gurmukhi_data
DECL|function|init
DECL|function|initTestCase
DECL|function|kannada
DECL|function|kannada_data
DECL|function|khmer
DECL|function|khmer_data
DECL|function|linearB
DECL|function|linearB_data
DECL|function|malayalam
DECL|function|malayalam_data
DECL|function|mirroredChars
DECL|function|mirroredChars_data
DECL|function|oriya
DECL|function|oriya_data
DECL|function|prepareShapingTest
DECL|function|sinhala
DECL|function|sinhala_data
DECL|function|tamil
DECL|function|tamil_data
DECL|function|telugu
DECL|function|telugu_data
DECL|function|thaiIsolatedSaraAm
DECL|function|thaiMultipleVowels
DECL|function|thaiWithZWJ
DECL|function|tst_QTextScriptEngine
DECL|function|~tst_QTextScriptEngine
DECL|member|glyphs
DECL|member|haveTestFonts
DECL|member|unicode
DECL|struct|ShapeTable
