DECL|function|adjustIterationCount
DECL|function|adjustIterationCount
DECL|function|adjustMedianCount
DECL|function|adjustMedianCount
DECL|function|checkpoint
DECL|function|checkpoint
DECL|function|isMeasurementAccepted
DECL|function|isMeasurementAccepted
DECL|function|metricType
DECL|function|metricType
DECL|function|needsWarmupIteration
DECL|function|needsWarmupIteration
DECL|function|start
DECL|function|start
DECL|function|stop
DECL|function|stop
