DECL|function|QBenchmarkPerfEventsMeasurer
DECL|function|adjustIterationCount
DECL|function|adjustMedianCount
DECL|function|checkpoint
DECL|function|init
DECL|function|isAvailable
DECL|function|isMeasurementAccepted
DECL|function|listCounters
DECL|function|metricForEvent
DECL|function|metricType
DECL|function|perf_event_open
DECL|function|rawReadValue
DECL|function|readValue
DECL|function|setCounter
DECL|function|start
DECL|function|stop
DECL|function|~QBenchmarkPerfEventsMeasurer
DECL|macro|CACHE_BRANCH_READ
DECL|macro|CACHE_BRANCH_READ_MISS
DECL|macro|CACHE_L1D_PREFETCH
DECL|macro|CACHE_L1D_PREFETCH_MISS
DECL|macro|CACHE_L1D_READ
DECL|macro|CACHE_L1D_READ_MISS
DECL|macro|CACHE_L1D_WRITE
DECL|macro|CACHE_L1D_WRITE_MISS
DECL|macro|CACHE_L1I_PREFETCH
DECL|macro|CACHE_L1I_PREFETCH_MISS
DECL|macro|CACHE_L1I_READ
DECL|macro|CACHE_L1I_READ_MISS
DECL|macro|CACHE_LLC_PREFETCH
DECL|macro|CACHE_LLC_PREFETCH_MISS
DECL|macro|CACHE_LLC_READ
DECL|macro|CACHE_LLC_READ_MISS
DECL|macro|CACHE_LLC_WRITE
DECL|macro|CACHE_LLC_WRITE_MISS
DECL|member|event_id
DECL|member|metric
DECL|member|offset
DECL|member|type
DECL|struct|Events
DECL|variable|event_id
DECL|variable|event_type
DECL|variable|eventlist
DECL|variable|eventlist_strings
