DECL|class|TestLoggers
DECL|function|IgnoreResultList
DECL|function|addBenchmarkResult
DECL|function|addBenchmarkResult
DECL|function|addFail
DECL|function|addIgnoreMessage
DECL|function|addIncident
DECL|function|addLogger
DECL|function|addLogger
DECL|function|addMessage
DECL|function|addPass
DECL|function|addSkip
DECL|function|addXFail
DECL|function|addXPass
DECL|function|clearList
DECL|function|destroyLoggers
DECL|function|enterTestFunction
DECL|function|enterTestFunction
DECL|function|handleIgnoredMessage
DECL|function|info
DECL|function|leaveTestFunction
DECL|function|leaveTestFunction
DECL|function|loggerCount
DECL|function|loggerCount
DECL|function|loggerUsingStdout
DECL|function|messageHandler
DECL|function|outputString
DECL|function|printUnhandledIgnoreMessages
DECL|function|setMaxWarnings
DECL|function|setVerboseLevel
DECL|function|startLogging
DECL|function|startLogging
DECL|function|stopLogging
DECL|function|stopLogging
DECL|function|unhandledIgnoreMessages
DECL|function|verboseLevel
DECL|function|warn
DECL|function|~IgnoreResultList
DECL|macro|FOREACH_LOGGER
DECL|macro|FOREACH_LOGGER
DECL|member|ignoreResultList
DECL|member|logger
DECL|member|loggerUsingStdout
DECL|member|loggers
DECL|member|loggers
DECL|member|maxWarnings
DECL|member|msg
DECL|member|next
DECL|member|next
DECL|member|oldMessageHandler
DECL|member|type
DECL|member|verbosity
DECL|namespace|QTest
DECL|struct|IgnoreResultList
DECL|struct|LoggerList
