DECL|class|QTestTablePrivate
DECL|function|DataList
DECL|function|ElementList
DECL|function|QTestTable
DECL|function|QTestTablePrivate
DECL|function|addColumn
DECL|function|addColumn
DECL|function|addRow
DECL|function|clearGlobalTestTable
DECL|function|currentTestTable
DECL|function|dataAt
DECL|function|dataCount
DECL|function|dataTag
DECL|function|elementAt
DECL|function|elementCount
DECL|function|elementTypeId
DECL|function|globalTestTable
DECL|function|indexOf
DECL|function|isEmpty
DECL|function|newData
DECL|function|testData
DECL|function|~QTestTable
DECL|function|~QTestTablePrivate
DECL|member|currentTestTable
DECL|member|currentTestTable
DECL|member|data
DECL|member|dataList
DECL|member|elementName
DECL|member|elementType
DECL|member|gTable
DECL|member|gTable
DECL|member|list
DECL|member|next
DECL|member|next
DECL|struct|DataList
DECL|struct|ElementList
