DECL|class|NamePredicate
DECL|class|QTestTablePrivate
DECL|function|Element
DECL|function|Element
DECL|function|NamePredicate
DECL|function|QTestTable
DECL|function|addColumn
DECL|function|addColumn
DECL|function|addRow
DECL|function|clearGlobalTestTable
DECL|function|currentTestTable
DECL|function|dataCount
DECL|function|dataTag
DECL|function|elementCount
DECL|function|elementTypeId
DECL|function|globalTestTable
DECL|function|indexOf
DECL|function|isEmpty
DECL|function|newData
DECL|function|operator ()
DECL|function|testData
DECL|function|~QTestTable
DECL|member|currentTestTable
DECL|member|currentTestTable
DECL|member|dataList
DECL|member|elementList
DECL|member|gTable
DECL|member|gTable
DECL|member|m_needle
DECL|member|name
DECL|member|type
DECL|struct|Element
DECL|typedef|DataList
DECL|typedef|ElementList
