DECL|class|TestLoggers
DECL|function|IgnoreResultList
DECL|function|addBenchmarkResult
DECL|function|addBenchmarkResult
DECL|function|addFail
DECL|function|addIncident
DECL|function|addLogger
DECL|function|addLogger
DECL|function|addMessage
DECL|function|addPass
DECL|function|addSkip
DECL|function|addXFail
DECL|function|addXPass
DECL|function|clearIgnoreMessages
DECL|function|clearList
DECL|function|destroyLoggers
DECL|function|enterTestFunction
DECL|function|enterTestFunction
DECL|function|failCount
DECL|function|handleIgnoredMessage
DECL|function|ignoreMessage
DECL|function|info
DECL|function|installedTestCoverage
DECL|function|leaveTestFunction
DECL|function|leaveTestFunction
DECL|function|loggerCount
DECL|function|loggerCount
DECL|function|loggerUsingStdout
DECL|function|messageHandler
DECL|function|outputString
DECL|function|passCount
DECL|function|printUnhandledIgnoreMessages
DECL|function|resetCounters
DECL|function|saveCoverageTool
DECL|function|setInstalledTestCoverage
DECL|function|setMaxWarnings
DECL|function|setPrintAvailableTagsMode
DECL|function|setVerboseLevel
DECL|function|skipCount
DECL|function|startLogging
DECL|function|startLogging
DECL|function|stopLogging
DECL|function|stopLogging
DECL|function|unhandledIgnoreMessages
DECL|function|verboseLevel
DECL|function|warn
DECL|function|~IgnoreResultList
DECL|macro|FOREACH_LOGGER
DECL|macro|FOREACH_LOGGER
DECL|member|fails
DECL|member|ignoreResultList
DECL|member|installedTestCoverage
DECL|member|logger
DECL|member|loggerUsingStdout
DECL|member|loggers
DECL|member|loggers
DECL|member|maxWarnings
DECL|member|msg
DECL|member|next
DECL|member|next
DECL|member|oldMessageHandler
DECL|member|passes
DECL|member|printAvailableTags
DECL|member|skips
DECL|member|type
DECL|member|verbosity
DECL|namespace|QTest
DECL|struct|IgnoreResultList
DECL|struct|LoggerList
