DECL|function|IgnoreResultList
DECL|function|addBenchmarkResult
DECL|function|addFail
DECL|function|addIgnoreMessage
DECL|function|addPass
DECL|function|addSkip
DECL|function|addXFail
DECL|function|addXPass
DECL|function|clearList
DECL|function|enterTestFunction
DECL|function|handleIgnoredMessage
DECL|function|info
DECL|function|initLogger
DECL|function|leaveTestFunction
DECL|function|logMode
DECL|function|messageHandler
DECL|function|printUnhandledIgnoreMessages
DECL|function|setMaxWarnings
DECL|function|setVerboseLevel
DECL|function|startLogging
DECL|function|stopLogging
DECL|function|unhandledIgnoreMessages
DECL|function|verboseLevel
DECL|function|warn
DECL|function|~IgnoreResultList
DECL|member|ignoreResultList
DECL|member|logMode
DECL|member|maxWarnings
DECL|member|msg
DECL|member|next
DECL|member|oldMessageHandler
DECL|member|testLogger
DECL|member|type
DECL|member|verbosity
DECL|namespace|QTest
DECL|struct|IgnoreResultList
