DECL|function|QTestAccessibilityEvent
DECL|function|operator
DECL|macro|QTESTACCESSIBLE_H
DECL|macro|QTEST_ACCESSIBILITY
DECL|macro|QVERIFY_EVENT
DECL|member|child
DECL|member|event
DECL|member|object
DECL|struct|QTestAccessibilityEvent
DECL|typedef|EventList
