DECL|class|FatalSignalHandler
DECL|class|TestFunction
DECL|function|FatalSignalHandler
DECL|function|QTestDataSetter
DECL|function|TestFunction
DECL|function|addColumnInternal
DECL|function|addResult
DECL|function|cleanup
DECL|function|compare_helper
DECL|function|compare_string_helper
DECL|function|currentDataTag
DECL|function|currentTestFailed
DECL|function|currentTestFunction
DECL|function|data
DECL|function|defaultEventDelay
DECL|function|defaultKeyDelay
DECL|function|defaultMouseDelay
DECL|function|fetchData
DECL|function|function
DECL|function|ignoreMessage
DECL|function|installCoverageTool
DECL|function|invokeMethod
DECL|function|isValidSlot
DECL|function|isWindowsBuildDirectory
DECL|function|newRow
DECL|function|qCompare
DECL|function|qCompare
DECL|function|qData
DECL|function|qElementData
DECL|function|qExec
DECL|function|qExec
DECL|function|qExpectFail
DECL|function|qFail
DECL|function|qFindTestData
DECL|function|qFindTestData
DECL|function|qGlobalData
DECL|function|qInvokeTestMethod
DECL|function|qInvokeTestMethodDataEntry
DECL|function|qInvokeTestMethods
DECL|function|qMedian
DECL|function|qPrintDataTags
DECL|function|qPrintTestSlots
DECL|function|qSkip
DECL|function|qSleep
DECL|function|qToInt
DECL|function|qVerify
DECL|function|qWarn
DECL|function|qtest_qParseArgs
DECL|function|set
DECL|function|signal
DECL|function|testObject
DECL|function|toHexRepresentation
DECL|function|toString
DECL|function|toString
DECL|function|windowsFaultHandler
DECL|function|~FatalSignalHandler
DECL|function|~QTestDataSetter
DECL|function|~TestFuncCleanup
DECL|function|~TestFunction
DECL|macro|TO_STRING_IMPL
DECL|member|currentTestObject
DECL|member|data_
DECL|member|eventDelay
DECL|member|function_
DECL|member|handledSignals
DECL|member|keyDelay
DECL|member|mouseDelay
DECL|member|noCrashHandler
DECL|member|printAvailableFunctions
DECL|member|testFuncCleaner
DECL|member|testFuncCount
DECL|member|testFuncs
DECL|member|testFunctions
DECL|member|testTags
DECL|namespace|QTest
DECL|struct|QTestDataSetter
DECL|struct|TestFuncCleanup
