DECL|function|addFailure
DECL|function|addSkip
DECL|function|checkStatement
DECL|function|clearExpectFail
DECL|function|compare
DECL|function|compare
DECL|function|currentDataTag
DECL|function|currentGlobalDataTag
DECL|function|currentGlobalTestData
DECL|function|currentTestData
DECL|function|currentTestFailed
DECL|function|currentTestFunction
DECL|function|currentTestLocation
DECL|function|currentTestObjectName
DECL|function|expectFail
DECL|function|failCount
DECL|function|finishedCurrentTestFunction
DECL|function|ignoreMessage
DECL|function|isExpectFailData
DECL|function|passCount
DECL|function|reset
DECL|function|setCurrentGlobalTestData
DECL|function|setCurrentTestData
DECL|function|setCurrentTestFunction
DECL|function|setCurrentTestLocation
DECL|function|setCurrentTestObject
DECL|function|setSkipCurrentTest
DECL|function|skipCount
DECL|function|skipCurrentTest
DECL|function|testFailed
DECL|function|verify
DECL|member|currentGlobalTestData
DECL|member|currentTestData
DECL|member|currentTestFunc
DECL|member|currentTestObjectName
DECL|member|dataFailed
DECL|member|expectFailComment
DECL|member|expectFailMode
DECL|member|failed
DECL|member|fails
DECL|member|location
DECL|member|passes
DECL|member|skipCurrentTest
DECL|member|skips
DECL|namespace|QTest
