DECL|macro|QTEST_GLOBAL_H
DECL|macro|QTEST_NO_SPECIALIZATIONS
DECL|macro|QTEST_VERSION
DECL|macro|QTEST_VERSION_STR
DECL|macro|Q_TESTLIB_EXPORT
DECL|macro|Q_TESTLIB_EXPORT
DECL|macro|Q_TESTLIB_EXPORT
