DECL|function|QTestLogger
DECL|function|addBenchmarkResult
DECL|function|addIncident
DECL|function|addMessage
DECL|function|addTag
DECL|function|enterTestFunction
DECL|function|errorCount
DECL|function|failureCount
DECL|function|hasRandomSeed
DECL|function|infoCount
DECL|function|leaveTestFunction
DECL|function|passCount
DECL|function|qdebugCount
DECL|function|qfatalCount
DECL|function|qwarnCount
DECL|function|randomSeed
DECL|function|registerRandomSeed
DECL|function|skipCount
DECL|function|startLogging
DECL|function|stopLogging
DECL|function|systemCount
DECL|function|warningCount
DECL|function|~QTestLogger
