DECL|function|QXmlTestLogger
DECL|function|addBenchmarkResult
DECL|function|addIncident
DECL|function|addMessage
DECL|function|allocateStringFn
DECL|function|benchmarkResultFormatString
DECL|function|enterTestFunction
DECL|function|incidentFormatString
DECL|function|isEmpty
DECL|function|leaveTestFunction
DECL|function|messageFormatString
DECL|function|registerRandomSeed
DECL|function|startLogging
DECL|function|stopLogging
DECL|function|xmlCdata
DECL|function|xmlCdata
DECL|function|xmlIncidentType2String
DECL|function|xmlMessageType2String
DECL|function|xmlQuote
DECL|function|xmlQuote
DECL|function|~QXmlTestLogger
DECL|macro|MAP_ENTITY
DECL|macro|MAP_ENTITY
DECL|namespace|QTest
DECL|namespace|QTest
DECL|typedef|StringFormatFunction
