DECL|function|QXunitTestLogger
DECL|function|addBenchmarkResult
DECL|function|addIncident
DECL|function|addMessage
DECL|function|addTag
DECL|function|enterTestFunction
DECL|function|leaveTestFunction
DECL|function|startLogging
DECL|function|stopLogging
DECL|function|~QXunitTestLogger
