DECL|macro|ABSTRACTFORMBUILDER_H
DECL|variable|QAbstractButton
DECL|variable|QAbstractItemView
DECL|variable|QAction
DECL|variable|QActionGroup
DECL|variable|QButtonGroup
DECL|variable|QComboBox
DECL|variable|QIODevice
DECL|variable|QIcon
DECL|variable|QLayout
DECL|variable|QLayoutItem
DECL|variable|QListWidget
DECL|variable|QObject
DECL|variable|QSpacerItem
DECL|variable|QTableWidget
DECL|variable|QTreeWidget
DECL|variable|QVariant
DECL|variable|QWidget
