DECL|function|QFormBuilder
DECL|function|addItem
DECL|function|addItem
DECL|function|addPluginPath
DECL|function|applyProperties
DECL|function|clearPluginPaths
DECL|function|create
DECL|function|create
DECL|function|create
DECL|function|create
DECL|function|create
DECL|function|create
DECL|function|createConnections
DECL|function|createLayout
DECL|function|createWidget
DECL|function|customWidgets
DECL|function|insertPlugins
DECL|function|objectByName
DECL|function|pluginPaths
DECL|function|setPluginPath
DECL|function|updateCustomWidgets
DECL|function|widgetByName
DECL|function|~QFormBuilder
DECL|macro|DECLARE_COMPAT_WIDGET
DECL|macro|DECLARE_COMPAT_WIDGET
DECL|macro|DECLARE_COMPAT_WIDGET
DECL|macro|DECLARE_COMPAT_WIDGET
DECL|macro|DECLARE_LAYOUT
DECL|macro|DECLARE_LAYOUT
DECL|macro|DECLARE_LAYOUT
DECL|macro|DECLARE_LAYOUT
DECL|macro|DECLARE_WIDGET
DECL|macro|DECLARE_WIDGET
DECL|macro|DECLARE_WIDGET
DECL|macro|DECLARE_WIDGET
DECL|macro|DECLARE_WIDGET_1
DECL|macro|DECLARE_WIDGET_1
DECL|namespace|QFormInternal
