DECL|macro|ABSTRACTFORMBUILDERPRIVATE_H
DECL|variable|QAction
DECL|variable|QActionGroup
DECL|variable|QBoxLayout
DECL|variable|QButtonGroup
DECL|variable|QDesignerCustomWidgetInterface
DECL|variable|QGridLayout
DECL|variable|QLabel
DECL|variable|QObject
DECL|variable|QObject
DECL|variable|QVariant
DECL|variable|QWidget
