DECL|function|SslClient
DECL|function|appendString
DECL|function|displayCertificateInfo
DECL|function|secureConnect
DECL|function|sendData
DECL|function|socketEncrypted
DECL|function|socketReadyRead
DECL|function|socketStateChanged
DECL|function|sslErrors
DECL|function|updateEnabledState
DECL|function|~SslClient
