DECL|function|QDBusPlatformMenu
DECL|function|QDBusPlatformMenuItem
DECL|function|byId
DECL|function|byIds
DECL|function|createMenuItem
DECL|function|createSubMenu
DECL|function|emitUpdated
DECL|function|insertMenuItem
DECL|function|items
DECL|function|menuItemAt
DECL|function|menuItemForTag
DECL|function|removeMenuItem
DECL|function|setCheckable
DECL|function|setChecked
DECL|function|setContainingMenuItem
DECL|function|setEnabled
DECL|function|setEnabled
DECL|function|setIcon
DECL|function|setIcon
DECL|function|setIsSeparator
DECL|function|setMenu
DECL|function|setRole
DECL|function|setShortcut
DECL|function|setTag
DECL|function|setTag
DECL|function|setText
DECL|function|setText
DECL|function|setVisible
DECL|function|setVisible
DECL|function|syncMenuItem
DECL|function|syncSubMenu
DECL|function|trigger
DECL|function|~QDBusPlatformMenu
DECL|function|~QDBusPlatformMenuItem
DECL|variable|menuItemsByID
DECL|variable|nextDBusID
