DECL|class|FormBuilderPrivate
DECL|class|QUiLoaderPrivate
DECL|class|TranslatingTextBuilder
DECL|class|TranslationWatcher
DECL|function|FormBuilderPrivate
DECL|function|QUiLoader
DECL|function|TranslatingTextBuilder
DECL|function|TranslationWatcher
DECL|function|addItem
DECL|function|addPluginPath
DECL|function|applyProperties
DECL|function|availableLayouts
DECL|function|availableWidgets
DECL|function|clearPluginPaths
DECL|function|convertTranslatable
DECL|function|create
DECL|function|create
DECL|function|createAction
DECL|function|createAction
DECL|function|createActionGroup
DECL|function|createActionGroup
DECL|function|createLayout
DECL|function|createLayout
DECL|function|createWidget
DECL|function|createWidget
DECL|function|defaultCreateAction
DECL|function|defaultCreateActionGroup
DECL|function|defaultCreateLayout
DECL|function|defaultCreateWidget
DECL|function|eventFilter
DECL|function|isLanguageChangeEnabled
DECL|function|isScriptingEnabled
DECL|function|isTranslationEnabled
DECL|function|load
DECL|function|loadText
DECL|function|pluginPaths
DECL|function|reTranslateTableItem
DECL|function|reTranslateWidgetItem
DECL|function|recursiveReTranslate
DECL|function|setLanguageChangeEnabled
DECL|function|setScriptingEnabled
DECL|function|setTranslationEnabled
DECL|function|setWorkingDirectory
DECL|function|setupWidgetMap
DECL|function|toNativeValue
DECL|function|workingDirectory
DECL|function|~QUiLoader
DECL|macro|DECLARE_LAYOUT
DECL|macro|DECLARE_LAYOUT
DECL|macro|DECLARE_LAYOUT
DECL|macro|DECLARE_LAYOUT
DECL|macro|DECLARE_WIDGET
DECL|macro|DECLARE_WIDGET
DECL|macro|DECLARE_WIDGET
DECL|macro|DECLARE_WIDGET
DECL|macro|DECLARE_WIDGET_1
DECL|macro|RETRANSLATE_SUBWIDGET_PROP
DECL|macro|TRANSLATE_SUBWIDGET_PROP
DECL|member|builder
DECL|member|dynamicTr
DECL|member|loader
DECL|member|m_class
DECL|member|m_className
DECL|member|m_className
DECL|member|m_trEnabled
DECL|member|m_trwatch
DECL|member|qUiItemRoles
DECL|member|trEnabled
DECL|namespace|QFormInternal
DECL|typedef|ParentClass
DECL|typedef|widget_map
