DECL|class|EventFilter
DECL|class|MainWindow
DECL|class|TouchTestWidget
DECL|enumerator|MousePress
DECL|enumerator|MouseRelease
DECL|enumerator|TouchPoint
DECL|enum|PointType
DECL|function|EventFilter
DECL|function|MainWindow
DECL|function|Point
DECL|function|TouchTestWidget
DECL|function|appendToLog
DECL|function|clearPoints
DECL|function|color
DECL|function|drawPoints
DECL|function|dumpTouchDevices
DECL|function|event
DECL|function|eventFilter
DECL|function|main
DECL|function|operator <<
DECL|function|paintEvent
DECL|function|setDrawPoints
DECL|function|touchWidget
DECL|member|Q_DECL_OVERRIDE
DECL|member|Q_DECL_OVERRIDE
DECL|member|Q_DECL_OVERRIDE
DECL|member|m_drawPoints
DECL|member|m_logTextEdit
DECL|member|m_points
DECL|member|m_touchWidget
DECL|member|m_types
DECL|member|pos
DECL|member|source
DECL|member|type
DECL|struct|Point
DECL|typedef|EventTypeVector
DECL|variable|optIgnoreTouch
