DECL|function|QWidgetBackingStore
DECL|function|beginPaint
DECL|function|bltRect
DECL|function|dirtyRegion
DECL|function|discardInvalidateBufferRequest
DECL|function|discardSyncRequest
DECL|function|endPaint
DECL|function|flush
DECL|function|flushPaint
DECL|function|hasDirtyWindowDecoration
DECL|function|invalidateBuffer
DECL|function|invalidateBuffer
DECL|function|invalidateBuffer_resizeHelper
DECL|function|markDirty
DECL|function|markDirty
DECL|function|markDirtyOnScreen
DECL|function|moveRect
DECL|function|paintWindowDecoration
DECL|function|qRectIntersects
DECL|function|qt_flush
DECL|function|releaseBuffer
DECL|function|removeDirtyWidget
DECL|function|repaint_sys
DECL|function|scrollRect
DECL|function|sendUpdateRequest
DECL|function|showYellowThing
DECL|function|showYellowThing_win
DECL|function|staticContents
DECL|function|sync
DECL|function|sync
DECL|function|unflushPaint
DECL|function|updateLists
DECL|function|~QWidgetBackingStore
