DECL|enumerator|Circle
DECL|enumerator|Discard
DECL|enumerator|Ok
DECL|enumerator|Split
DECL|enum|ShiftResult
DECL|function|addCircle
DECL|function|addIfClose
DECL|function|addToPolygon
DECL|function|addToPolygon
DECL|function|bezierOnInterval
DECL|function|bounds
DECL|function|fromPoints
DECL|function|getSubRange
DECL|function|good_offset
DECL|function|length
DECL|function|mapBy
DECL|function|operator <<
DECL|function|quadraticRoots
DECL|function|shift
DECL|function|shifted
DECL|function|stationaryYPoints
DECL|function|tAtLength
DECL|function|tForY
DECL|function|toPolygon
DECL|macro|KAPPA
