DECL|function|color
DECL|function|isDetached
DECL|function|matrix
DECL|function|setColor
DECL|function|setSpread
DECL|function|style
DECL|function|transform
DECL|macro|QBRUSH_H
DECL|member|color
DECL|member|ref
DECL|member|style
DECL|member|transform
DECL|struct|QBrushData
DECL|typedef|QGradientStop
DECL|typedef|QGradientStops
DECL|typedef|qreal
DECL|variable|QGradient
DECL|variable|QGradientPrivate
DECL|variable|QPixmap
DECL|variable|QVariant
DECL|variable|operator
