DECL|function|QColor
DECL|function|QColor
DECL|function|QColor
DECL|function|QColor
DECL|function|QColor
DECL|function|darker
DECL|function|isValid
DECL|function|lighter
DECL|macro|QCOLOR_H
DECL|variable|QColor
DECL|variable|QColormap
DECL|variable|QVariant
