DECL|enumerator|Aliased
DECL|enumerator|AntiAliased
DECL|enumerator|Dashed
DECL|enumerator|FastDraw
DECL|enumerator|RegularDraw
DECL|enumerator|Solid
DECL|enum|StrokeSelection
DECL|function|Dasher
DECL|function|F16Dot16FixedDiv
DECL|function|NoDasher
DECL|function|adjust
DECL|function|adjust
DECL|function|calculateLastPoint
DECL|function|capAdjust
DECL|function|clipLine
DECL|function|drawLine
DECL|function|drawLine
DECL|function|drawLineAA
DECL|function|drawPath
DECL|function|drawPixel
DECL|function|drawPixelARGB32
DECL|function|drawPixelARGB32Opaque
DECL|function|drawPoints
DECL|function|drawPoints
DECL|function|on
DECL|function|on
DECL|function|renderCubic
DECL|function|renderCubicSubdivision
DECL|function|setup
DECL|function|sourceOver
DECL|function|splitCubic
DECL|function|strokeLine
DECL|function|subPath
DECL|function|swapCaps
DECL|macro|toF26Dot6
DECL|member|dashIndex
DECL|member|dashOn
DECL|member|offset
DECL|member|pattern
DECL|member|stroker
DECL|struct|Dasher
DECL|struct|NoDasher
DECL|typedef|DrawPixel
