DECL|function|QCUPSSupport
DECL|function|availablePrinters
DECL|function|availablePrintersCount
DECL|function|collectMarkedOptions
DECL|function|collectMarkedOptionsHelper
DECL|function|currentPPD
DECL|function|currentPrinterIndex
DECL|function|isAvailable
DECL|function|markOption
DECL|function|options
DECL|function|pageRect
DECL|function|pageSizes
DECL|function|paperRect
DECL|function|ppdOption
DECL|function|printFile
DECL|function|printerHasPPD
DECL|function|printerOption
DECL|function|resolveCups
DECL|function|saveOptions
DECL|function|setCurrentPrinter
DECL|function|tempFd
DECL|function|unicodeString
DECL|function|~QCUPSSupport
DECL|typedef|CupsAddOption
DECL|typedef|CupsFreeDests
DECL|typedef|CupsFreeOptions
DECL|typedef|CupsGetDests
DECL|typedef|CupsGetPPD
DECL|typedef|CupsLangEncoding
DECL|typedef|CupsLangGet
DECL|typedef|CupsMarkOptions
DECL|typedef|CupsPrintFile
DECL|typedef|CupsSetDests
DECL|typedef|CupsTempFd
DECL|typedef|PPDClose
DECL|typedef|PPDMarkDefaults
DECL|typedef|PPDMarkOption
DECL|typedef|PPDMarkOption
DECL|typedef|PPDOpenFile
DECL|variable|_cupsAddOption
DECL|variable|_cupsFreeDests
DECL|variable|_cupsFreeOptions
DECL|variable|_cupsGetDests
DECL|variable|_cupsGetPPD
DECL|variable|_cupsLangEncoding
DECL|variable|_cupsLangGet
DECL|variable|_cupsMarkOptions
DECL|variable|_cupsPrintFile
DECL|variable|_cupsSetDests
DECL|variable|_cupsTempFd
DECL|variable|_ppdClose
DECL|variable|_ppdMarkDefaults
DECL|variable|_ppdMarkOption
DECL|variable|_ppdOpenFile
DECL|variable|cupsLoaded
DECL|variable|qt_cups_num_printers
