DECL|class|QSimdSse2
DECL|function|comp_func_Plus_sse2
DECL|function|comp_func_SourceOver_sse2
DECL|function|comp_func_Source_sse2
DECL|function|comp_func_solid_SourceOver_sse2
DECL|function|qt_bitmapblit16_sse2
DECL|function|qt_bitmapblit32_sse2
DECL|function|qt_blend_argb32_on_argb32_sse2
DECL|function|qt_blend_rgb32_on_rgb32_sse2
DECL|function|qt_fetch_radial_gradient_sse2
DECL|function|qt_memfill16_sse2
DECL|function|qt_memfill32_sse2
DECL|function|qt_scale_image_argb32_on_argb32_sse2
DECL|function|v_add
DECL|function|v_add
DECL|function|v_and
DECL|function|v_dup
DECL|function|v_dup
DECL|function|v_dup
DECL|function|v_dup
DECL|function|v_greaterOrEqual
DECL|function|v_greaterOrEqual
DECL|function|v_max
DECL|function|v_min
DECL|function|v_min_16
DECL|function|v_mul
DECL|function|v_sqrt
DECL|function|v_sub
DECL|function|v_sub
DECL|function|v_toInt
DECL|member|f
DECL|member|i
DECL|member|v
DECL|member|v
DECL|typedef|Float32x4
DECL|typedef|Int32x4
DECL|union|Vect_buffer_f
DECL|union|Vect_buffer_i
DECL|variable|qt_functionForModeSolid_onlySSE2
DECL|variable|qt_functionForMode_onlySSE2
