DECL|function|qt_bitmapblit16_sse
DECL|function|qt_blend_argb32_on_argb32_sse
DECL|function|qt_blend_color_argb_sse
DECL|function|qt_blend_rgb32_on_rgb32_sse
DECL|function|qt_memfill32_sse
DECL|variable|qt_functionForModeSolid_SSE
DECL|variable|qt_functionForMode_SSE
