DECL|function|QEmulationPaintEngine
DECL|function|begin
DECL|function|beginNativePainting
DECL|function|brushChanged
DECL|function|brushOriginChanged
DECL|function|clip
DECL|function|clipEnabledChanged
DECL|function|compositionModeChanged
DECL|function|createState
DECL|function|drawImage
DECL|function|drawPixmap
DECL|function|drawStaticTextItem
DECL|function|drawTextItem
DECL|function|drawTiledPixmap
DECL|function|end
DECL|function|endNativePainting
DECL|function|fill
DECL|function|fillBGRect
DECL|function|opacityChanged
DECL|function|penChanged
DECL|function|renderHintsChanged
DECL|function|setState
DECL|function|stroke
DECL|function|transformChanged
DECL|function|type
