DECL|function|qt_qimageScaleAARGBA_down_x_up_y_sse4
DECL|function|qt_qimageScaleAARGBA_down_xy_sse4
DECL|function|qt_qimageScaleAARGBA_helper_x
DECL|function|qt_qimageScaleAARGBA_helper_y
DECL|function|qt_qimageScaleAARGBA_up_x_down_y_sse4
