DECL|function|qSmoothScaleImage
DECL|function|qimageCalcApoints
DECL|function|qimageCalcScaleInfo
DECL|function|qimageCalcXPoints
DECL|function|qimageCalcYPoints
DECL|function|qimageFreeScaleInfo
DECL|function|qt_qimageScaleAARGB
DECL|function|qt_qimageScaleAARGBA
DECL|macro|A_VAL
DECL|macro|B_VAL
DECL|macro|G_VAL
DECL|macro|INV_XAP
DECL|macro|INV_YAP
DECL|macro|R_VAL
DECL|macro|XAP
DECL|macro|YAP
DECL|member|xapoints
DECL|member|xpoints
DECL|member|xup_yup
DECL|member|yapoints
DECL|member|ypoints
DECL|namespace|QImageScale
DECL|namespace|QImageScale
DECL|struct|QImageScaleInfo
DECL|typedef|qt_qimageScaleFunc
DECL|variable|qt_qimageScaleArgb
DECL|variable|qt_qimageScaleRgb
