DECL|function|QPagedPaintDevice
DECL|function|devicePageLayout
DECL|function|devicePageLayout
DECL|function|margins
DECL|function|pageSize
DECL|function|pageSizeMM
DECL|function|setMargins
DECL|function|setPageSize
DECL|function|setPageSizeMM
DECL|function|~QPagedPaintDevice
