DECL|function|QPagedPaintDevice
DECL|function|QPagedPaintDevice
DECL|function|dd
DECL|function|devicePageLayout
DECL|function|devicePageLayout
DECL|function|margins
DECL|function|pageLayout
DECL|function|pageSize
DECL|function|pageSizeMM
DECL|function|setMargins
DECL|function|setPageLayout
DECL|function|setPageMargins
DECL|function|setPageMargins
DECL|function|setPageOrientation
DECL|function|setPageSize
DECL|function|setPageSize
DECL|function|setPageSizeMM
DECL|function|~QPagedPaintDevice
DECL|function|~QPagedPaintDevicePrivate
