DECL|class|QPagedPaintDevicePrivate
DECL|function|QPagedPaintDevice
DECL|function|margins
DECL|function|pageSize
DECL|function|pageSizeMM
DECL|function|setMargins
DECL|function|setPageSize
DECL|function|setPageSizeMM
DECL|function|~QPagedPaintDevice
DECL|member|height
DECL|member|margins
DECL|member|pageSize
DECL|member|pageSizeMM
DECL|member|width
DECL|variable|pageSizes
