DECL|function|qt_x11Handle
DECL|function|qt_x11Info
DECL|function|x11AppCells
DECL|function|x11AppColormap
DECL|function|x11AppDefaultColormap
DECL|function|x11AppDefaultVisual
DECL|function|x11AppDepth
DECL|function|x11AppDisplay
DECL|function|x11AppDpiX
DECL|function|x11AppDpiY
DECL|function|x11AppRootWindow
DECL|function|x11AppScreen
DECL|function|x11AppVisual
DECL|function|x11Cells
DECL|function|x11Colormap
DECL|function|x11DefaultColormap
DECL|function|x11DefaultVisual
DECL|function|x11Depth
DECL|function|x11Display
DECL|function|x11Screen
DECL|function|x11SetAppDpiX
DECL|function|x11SetAppDpiY
DECL|function|x11Visual
