DECL|function|addEllipse
DECL|function|addEllipse
DECL|function|addRect
DECL|function|addRoundRect
DECL|function|addRoundRect
DECL|function|addRoundRect
DECL|function|addRoundedRect
DECL|function|addText
DECL|function|arcMoveTo
DECL|function|arcTo
DECL|function|cubicTo
DECL|function|detach
DECL|function|elementAt
DECL|function|elementCount
DECL|function|isEmpty
DECL|function|lineTo
DECL|function|moveTo
DECL|function|quadTo
DECL|function|setElementPositionAt
DECL|function|translate
DECL|function|translated
DECL|macro|QPAINTERPATH_H
DECL|variable|QFont
DECL|variable|QPainterPathData
DECL|variable|QPainterPathPrivate
DECL|variable|QPainterPathStrokerPrivate
DECL|variable|QPolygonF
DECL|variable|QRegion
DECL|variable|QVectorPath
