DECL|function|data_ptr
DECL|function|data_ptr
DECL|function|data_ptr
DECL|function|qbrush_color
DECL|function|qbrush_fast_equals
DECL|function|qbrush_has_transform
DECL|function|qbrush_style
DECL|function|qpen_brush
DECL|function|qpen_capStyle
DECL|function|qpen_fast_equals
DECL|function|qpen_joinStyle
DECL|function|qpen_style
DECL|function|qpen_widthf
DECL|function|qt_pen_is_cosmetic
DECL|function|qtransform_fast_equals
DECL|macro|QPAINTER_P_H
DECL|member|brush
DECL|member|font
DECL|member|pen
DECL|member|ptr
DECL|member|transform
DECL|struct|DataPtrContainer
DECL|struct|QPainterDummyState
DECL|variable|QEmulationPaintEngine
DECL|variable|QPaintEngine
DECL|variable|QPaintEngineEx
DECL|variable|QRawFont
