DECL|class|QFakeDevice
DECL|class|QPaintBufferEnginePrivate
DECL|enumerator|ImageKey
DECL|enumerator|PixmapKey
DECL|enum|Type
DECL|function|QFakeDevice
DECL|function|QPaintBuffer
DECL|function|QPaintBuffer
DECL|function|QPaintBufferEngine
DECL|function|QPaintBufferPrivate
DECL|function|QPaintBufferResource
DECL|function|QTextItemIntCopy
DECL|function|backgroundModeChanged
DECL|function|begin
DECL|function|beginNewFrame
DECL|function|boundingRect
DECL|function|brushChanged
DECL|function|brushOriginChanged
DECL|function|clip
DECL|function|clip
DECL|function|clip
DECL|function|clip
DECL|function|clipEnabledChanged
DECL|function|commandDescription
DECL|function|compositionModeChanged
DECL|function|createState
DECL|function|devType
DECL|function|draw
DECL|function|draw
DECL|function|drawEllipse
DECL|function|drawEllipse
DECL|function|drawImage
DECL|function|drawImage
DECL|function|drawLines
DECL|function|drawLines
DECL|function|drawPath
DECL|function|drawPixmap
DECL|function|drawPixmap
DECL|function|drawPoints
DECL|function|drawPoints
DECL|function|drawPolygon
DECL|function|drawPolygon
DECL|function|drawRects
DECL|function|drawRects
DECL|function|drawStaticTextItem
DECL|function|drawTextItem
DECL|function|drawTiledPixmap
DECL|function|end
DECL|function|fill
DECL|function|fillRect
DECL|function|fillRect
DECL|function|frameEndIndex
DECL|function|frameStartIndex
DECL|function|insert
DECL|function|instance
DECL|function|isEmpty
DECL|function|metric
DECL|function|metric
DECL|function|numFrames
DECL|function|opacityChanged
DECL|function|operator <<
DECL|function|operator <<
DECL|function|operator <<
DECL|function|operator <<
DECL|function|operator =
DECL|function|operator >>
DECL|function|operator >>
DECL|function|operator >>
DECL|function|operator >>
DECL|function|paintEngine
DECL|function|paintEngine
DECL|function|penChanged
DECL|function|process
DECL|function|process
DECL|function|processCommands
DECL|function|processCommands
DECL|function|qRegisterPaintBufferMetaTypes
DECL|function|qpaintbuffer_storable_image
DECL|function|remove
DECL|function|renderHintsChanged
DECL|function|setBoundingRect
DECL|function|setDpiX
DECL|function|setDpiY
DECL|function|setState
DECL|function|setupTransform
DECL|function|stroke
DECL|function|systemStateChanged
DECL|function|transformChanged
DECL|function|updateBoundingRect
DECL|function|value
DECL|function|~QPaintBuffer
DECL|function|~QPaintBufferPrivate
DECL|function|~QPaintBufferResource
DECL|function|~QTextItemIntCopy
DECL|member|bits
DECL|member|cacheKey
DECL|member|dpi_x
DECL|member|dpi_y
DECL|member|flags
DECL|member|key
DECL|member|last
DECL|member|type
DECL|member|type
DECL|struct|Flags
DECL|struct|QPaintBufferCacheEntry
DECL|struct|QPaintBufferCacheEntryV2
