DECL|function|QAlphaPaintEngine
DECL|function|QAlphaPaintEnginePrivate
DECL|function|addAlphaRect
DECL|function|addPenWidth
DECL|function|alphaClipping
DECL|function|begin
DECL|function|cleanUp
DECL|function|continueCall
DECL|function|drawAlphaImage
DECL|function|drawImage
DECL|function|drawPath
DECL|function|drawPixmap
DECL|function|drawPolygon
DECL|function|drawTextItem
DECL|function|drawTiledPixmap
DECL|function|end
DECL|function|flushAndInit
DECL|function|fullyContained
DECL|function|resetState
DECL|function|toRect
DECL|function|updateState
DECL|function|~QAlphaPaintEngine
DECL|function|~QAlphaPaintEnginePrivate
