DECL|function|QPainter
DECL|function|QPainter
DECL|function|QPainterState
DECL|function|QPainterState
DECL|function|attachPainterPrivate
DECL|function|background
DECL|function|backgroundBrush
DECL|function|backgroundMode
DECL|function|backgroundMode
DECL|function|begin
DECL|function|beginNativePainting
DECL|function|boundingRect
DECL|function|boundingRect
DECL|function|boundingRect
DECL|function|brush
DECL|function|brush
DECL|function|brushNeedsResolving
DECL|function|brushOrigin
DECL|function|brushOrigin
DECL|function|checkEmulation
DECL|function|check_gradient
DECL|function|clipBoundingRect
DECL|function|clipOperation
DECL|function|clipPath
DECL|function|clipPath
DECL|function|clipRegion
DECL|function|clipRegion
DECL|function|combinedMatrix
DECL|function|combinedTransform
DECL|function|compositionMode
DECL|function|compositionMode
DECL|function|coordinateMode
DECL|function|create
DECL|function|detachPainterPrivate
DECL|function|device
DECL|function|deviceMatrix
DECL|function|deviceTransform
DECL|function|drawArc
DECL|function|drawChord
DECL|function|drawConvexPolygon
DECL|function|drawConvexPolygon
DECL|function|drawEllipse
DECL|function|drawEllipse
DECL|function|drawGlyphRun
DECL|function|drawGlyphs
DECL|function|drawImage
DECL|function|drawImage
DECL|function|drawLines
DECL|function|drawLines
DECL|function|drawLines
DECL|function|drawLines
DECL|function|drawOpaqueBackground
DECL|function|drawPath
DECL|function|drawPicture
DECL|function|drawPie
DECL|function|drawPixmap
DECL|function|drawPixmap
DECL|function|drawPixmapFragments
DECL|function|drawPoints
DECL|function|drawPoints
DECL|function|drawPolygon
DECL|function|drawPolygon
DECL|function|drawPolyline
DECL|function|drawPolyline
DECL|function|drawRects
DECL|function|drawRects
DECL|function|drawRoundRect
DECL|function|drawRoundedRect
DECL|function|drawStaticText
DECL|function|drawStretchedGradient
DECL|function|drawText
DECL|function|drawText
DECL|function|drawText
DECL|function|drawText
DECL|function|drawText
DECL|function|drawTextItem
DECL|function|drawTextItem
DECL|function|drawTextItemDecoration
DECL|function|drawTiledPixmap
DECL|function|draw_helper
DECL|function|end
DECL|function|endNativePainting
DECL|function|eraseRect
DECL|function|fillPath
DECL|function|fillRect
DECL|function|fillRect
DECL|function|fillRect
DECL|function|fillRect
DECL|function|font
DECL|function|font
DECL|function|fontInfo
DECL|function|fontMetrics
DECL|function|generateWavyPixmap
DECL|function|hasClipping
DECL|function|hidpiScaleTransform
DECL|function|init
DECL|function|initFrom
DECL|function|isActive
DECL|function|isClipEnabled
DECL|function|is_brush_transparent
DECL|function|is_pen_transparent
DECL|function|layoutDirection
DECL|function|line_emulation
DECL|function|matrix
DECL|function|matrix
DECL|function|matrixEnabled
DECL|function|needsResolving
DECL|function|opacity
DECL|function|opacity
DECL|function|paintEngine
DECL|function|painter
DECL|function|pen
DECL|function|pen
DECL|function|penNeedsResolving
DECL|function|qt_cleanup_painter_state
DECL|function|qt_draw_decoration_for_glyphs
DECL|function|qt_draw_helper
DECL|function|qt_format_text
DECL|function|qt_format_text
DECL|function|qt_painter_thread_test
DECL|function|redirected
DECL|function|renderHints
DECL|function|renderHints
DECL|function|resetMatrix
DECL|function|resetTransform
DECL|function|restore
DECL|function|restoreRedirected
DECL|function|rotate
DECL|function|roundInDeviceCoordinates
DECL|function|save
DECL|function|scale
DECL|function|setBackground
DECL|function|setBackgroundMode
DECL|function|setBrush
DECL|function|setBrush
DECL|function|setBrushOrigin
DECL|function|setClipPath
DECL|function|setClipRect
DECL|function|setClipRect
DECL|function|setClipRegion
DECL|function|setClipping
DECL|function|setCompositionMode
DECL|function|setFont
DECL|function|setLayoutDirection
DECL|function|setMatrix
DECL|function|setMatrixEnabled
DECL|function|setOpacity
DECL|function|setPen
DECL|function|setPen
DECL|function|setPen
DECL|function|setRedirected
DECL|function|setRenderHint
DECL|function|setRenderHints
DECL|function|setTransform
DECL|function|setViewTransformEnabled
DECL|function|setViewport
DECL|function|setWindow
DECL|function|setWorldMatrix
DECL|function|setWorldMatrixEnabled
DECL|function|setWorldTransform
DECL|function|shear
DECL|function|stretchGradientToUserSpace
DECL|function|strokePath
DECL|function|transform
DECL|function|transform
DECL|function|translate
DECL|function|updateEmulationSpecifier
DECL|function|updateInvMatrix
DECL|function|updateMatrix
DECL|function|updateState
DECL|function|updateStateImpl
DECL|function|viewTransform
DECL|function|viewTransformEnabled
DECL|function|viewport
DECL|function|window
DECL|function|worldMatrix
DECL|function|worldMatrixEnabled
DECL|function|worldTransform
DECL|function|~QPainter
DECL|function|~QPainterPrivate
DECL|function|~QPainterState
DECL|macro|QGradient_StretchToDevice
DECL|macro|QPaintEngine_OpaqueBackground
DECL|variable|qt_show_painter_debug_output
