DECL|function|QPathEdge
DECL|function|QPathSegments
DECL|function|QPathVertex
DECL|function|QPointF
DECL|function|addIntersection
DECL|function|addPoint
DECL|function|addVertex
DECL|function|directionTo
DECL|function|edge
DECL|function|edge
DECL|function|edgeCount
DECL|function|elementBounds
DECL|function|flip
DECL|function|flip
DECL|function|flip
DECL|function|flipDirection
DECL|function|flipTraversal
DECL|function|intersectionAt
DECL|function|intersections
DECL|function|lineAt
DECL|function|next
DECL|function|pathId
DECL|function|pointAt
DECL|function|points
DECL|function|segmentAt
DECL|function|segments
DECL|function|setNext
DECL|function|setNext
DECL|function|vertex
DECL|function|vertex
DECL|function|vertex
DECL|function|vertexCount
DECL|macro|QPATHCLIPPER_P_H
DECL|member|e
DECL|member|edge
DECL|member|public
DECL|member|x
DECL|member|y
DECL|struct|QPathVertex
