DECL|class|QPlatformBackingStorePrivate
DECL|function|QPlatformBackingStore
DECL|function|QPlatformBackingStorePrivate
DECL|function|beginPaint
DECL|function|endPaint
DECL|function|scroll
DECL|function|window
DECL|function|~QPlatformBackingStore
DECL|member|size
DECL|member|window
