DECL|class|QPlatformBackingStorePrivate
DECL|class|QPlatformTextureListPrivate
DECL|function|QPlatformBackingStore
DECL|function|QPlatformBackingStorePrivate
DECL|function|QPlatformTextureList
DECL|function|QPlatformTextureListPrivate
DECL|function|appendTexture
DECL|function|beginPaint
DECL|function|clear
DECL|function|composeAndFlush
DECL|function|count
DECL|function|deviceRect
DECL|function|deviceRegion
DECL|function|endPaint
DECL|function|geometry
DECL|function|isLocked
DECL|function|lock
DECL|function|scroll
DECL|function|stacksOnTop
DECL|function|textureId
DECL|function|toImage
DECL|function|toTexture
DECL|function|window
DECL|function|~QPlatformBackingStore
DECL|function|~QPlatformBackingStorePrivate
DECL|function|~QPlatformTextureList
DECL|member|blitter
DECL|member|locked
DECL|member|rect
DECL|member|size
DECL|member|stacksOnTop
DECL|member|textureId
DECL|member|textureId
DECL|member|textureSize
DECL|member|textures
DECL|member|window
DECL|struct|QBackingstoreTextureInfo
