DECL|function|Q_DECLARE_SHARED_NOT_MOVABLE_UNTIL_QT6
DECL|function|Q_DECLARE_SHARED_NOT_MOVABLE_UNTIL_QT6
DECL|function|point
DECL|function|setPoint
DECL|function|setPoint
DECL|function|translate
DECL|function|translate
DECL|function|translated
DECL|function|translated
DECL|macro|QPOLYGON_H
DECL|variable|QMatrix
DECL|variable|QRect
DECL|variable|QRectF
DECL|variable|QTransform
DECL|variable|QVariant
