DECL|function|QPdfEngine
DECL|function|QPdfEnginePrivate
DECL|function|begin
DECL|function|closeAllOpenFds
DECL|function|closePrintDevice
DECL|function|end
DECL|function|metric
DECL|function|newPage
DECL|function|openPrintDevice
DECL|function|property
DECL|function|qt_pdf_decide_features
DECL|function|setProperty
DECL|function|~QPdfEngine
DECL|function|~QPdfEnginePrivate
