DECL|function|QPdfEngine
DECL|function|QPdfEnginePrivate
DECL|function|QPdfPage
DECL|function|addBrushPattern
DECL|function|addConstantAlphaObject
DECL|function|addImage
DECL|function|addXrefEntry
DECL|function|begin
DECL|function|drawImage
DECL|function|drawPixmap
DECL|function|drawTextItem
DECL|function|drawTiledPixmap
DECL|function|embedFont
DECL|function|end
DECL|function|gradientBrush
DECL|function|newPage
DECL|function|newPage
DECL|function|pageMatrix
DECL|function|printString
DECL|function|qt_pdf_decide_features
DECL|function|setBrush
DECL|function|streamImage
DECL|function|type
DECL|function|writeCompressed
DECL|function|writeCompressed
DECL|function|writeFonts
DECL|function|writeHeader
DECL|function|writeImage
DECL|function|writeInfo
DECL|function|writePage
DECL|function|writePageRoot
DECL|function|writeTail
DECL|function|xprintf
DECL|function|~QPdfEngine
DECL|function|~QPdfEnginePrivate
DECL|variable|do_compress
DECL|variable|do_compress
DECL|variable|interpolateImages
