DECL|macro|QPRINTENGINE_QWS_P_H
DECL|macro|QT_QWS_PRINTER_DEFAULT_DPI
DECL|variable|QImage
DECL|variable|QPaintEngine
DECL|variable|QPrinterPrivate
DECL|variable|QRasterPaintEngine
DECL|variable|QtopiaPrintEnginePrivate
