DECL|class|QFastMutex
DECL|enumerator|Single
DECL|enumerator|Vector
DECL|function|CreateETandAET
DECL|function|EqualRegion
DECL|function|FreeStorage
DECL|function|InsertEdgeInET
DECL|function|InsertionSort
DECL|function|OffsetRegion
DECL|function|PointInRegion
DECL|function|PolygonRegion
DECL|function|PtsToRegion
DECL|function|QFastMutex
DECL|function|QRegion
DECL|function|QRegion
DECL|function|QRegion
DECL|function|QRegion
DECL|function|QRegion
DECL|function|QRegionPrivate
DECL|function|QRegionPrivate
DECL|function|QRegionPrivate
DECL|function|RectInRegion
DECL|function|SubtractRegion
DECL|function|UnionRectWithRegion
DECL|function|UnionRegion
DECL|function|XorRegion
DECL|function|append
DECL|function|boundingRect
DECL|function|canAppend
DECL|function|canPrepend
DECL|function|cleanUp
DECL|function|computeWAET
DECL|function|contains
DECL|function|contains
DECL|function|contains
DECL|function|copy
DECL|function|eor
DECL|function|intersect
DECL|function|intersect
DECL|function|isEmpty
DECL|function|isEmptyHelper
DECL|function|isRect
DECL|function|loadAET
DECL|function|lock
DECL|function|miCoalesce
DECL|function|miIntersectO
DECL|function|miRegionOp
DECL|function|miSetExtents
DECL|function|miSubtractNonO1
DECL|function|miSubtractO
DECL|function|miUnionNonO
DECL|function|miUnionO
DECL|function|operator &
DECL|function|operator &=
DECL|function|operator +=
DECL|function|operator =
DECL|function|operator =
DECL|function|operator ==
DECL|function|prepend
DECL|function|qt_allocRegion
DECL|function|qt_allocRegion
DECL|function|qt_allocRegion
DECL|function|qt_allocRegionMemory
DECL|function|qt_bitmapToRegion
DECL|function|qt_freeRegion
DECL|function|qt_freeRegionMemory
DECL|function|qt_region_strictContains
DECL|function|rects
DECL|function|setRects
DECL|function|subtract
DECL|function|translate
DECL|function|tryLock
DECL|function|unite
DECL|function|unlock
DECL|function|updateInnerRect
DECL|function|vector
DECL|function|~QRegion
DECL|macro|AddSpan
DECL|macro|AddSpan
DECL|macro|BRESINCRPGON
DECL|macro|BRESINCRPGONSTRUCT
DECL|macro|BRESINITPGON
DECL|macro|BRESINITPGONSTRUCT
DECL|macro|CLOCKWISE
DECL|macro|CONTAINSCHECK
DECL|macro|COUNTERCLOCKWISE
DECL|macro|EVALUATEEDGEEVENODD
DECL|macro|EVALUATEEDGEWINDING
DECL|macro|EXTENTCHECK
DECL|macro|EXTENTS
DECL|macro|EvenOddRule
DECL|macro|LARGE_COORDINATE
DECL|macro|MEMCHECK
DECL|macro|MERGERECT
DECL|macro|NUMPTSTOBUFFER
DECL|macro|RectangleIn
DECL|macro|RectangleOut
DECL|macro|RectanglePart
DECL|macro|SLLSPERBLOCK
DECL|macro|SMALL_COORDINATE
DECL|macro|WindingRule
DECL|macro|_XREGION_H
DECL|macro|private
DECL|macro|private
DECL|member|ClockWise
DECL|member|SLLs
DECL|member|back
DECL|member|bres
DECL|member|contenders
DECL|member|d
DECL|member|edgelist
DECL|member|extents
DECL|member|incr1
DECL|member|incr2
DECL|member|innerArea
DECL|member|innerRect
DECL|member|m
DECL|member|m1
DECL|member|minor_axis
DECL|member|mode
DECL|member|next
DECL|member|next
DECL|member|next
DECL|member|next
DECL|member|next
DECL|member|nextWETE
DECL|member|numRects
DECL|member|pts
DECL|member|rects
DECL|member|scanline
DECL|member|scanlines
DECL|member|semaphore
DECL|member|single
DECL|member|ymax
DECL|member|ymax
DECL|member|ymin
DECL|struct|QRegionPrivate
DECL|struct|_EdgeTableEntry
DECL|struct|_POINTBLOCK
DECL|struct|_ScanLineList
DECL|struct|_ScanLineListBlock
DECL|typedef|BRESINFO
DECL|typedef|EdgeTable
DECL|typedef|EdgeTableEntry
DECL|typedef|NonOverlapFunc
DECL|typedef|OverlapFunc
DECL|typedef|POINTBLOCK
DECL|typedef|ScanLineList
DECL|typedef|ScanLineListBlock
DECL|variable|qt_nextRegionLock
DECL|variable|qt_nextRegionPtr
