DECL|function|qAlpha
DECL|function|qBlue
DECL|function|qGray
DECL|function|qGray
DECL|function|qGreen
DECL|function|qIsGray
DECL|function|qRed
DECL|function|qRgb
DECL|function|qRgba
DECL|macro|QRGB_H
DECL|typedef|QRgb
DECL|variable|RGB_MASK
