DECL|class|QSubpathBackwardIterator
DECL|class|QSubpathFlatIterator
DECL|class|QSubpathForwardIterator
DECL|function|QDashStroker
DECL|function|QStroker
DECL|function|QStrokerOps
DECL|function|QSubpathBackwardIterator
DECL|function|QSubpathFlatIterator
DECL|function|QSubpathForwardIterator
DECL|function|adapted_angle_on_x
DECL|function|begin
DECL|function|capForJoinMode
DECL|function|end
DECL|function|hasNext
DECL|function|hasNext
DECL|function|hasNext
DECL|function|joinForJoinMode
DECL|function|joinModeForCap
DECL|function|joinModeForJoin
DECL|function|joinPoints
DECL|function|lineIntersectsRect
DECL|function|lineRectIntersectsRect
DECL|function|next
DECL|function|next
DECL|function|next
DECL|function|patternForStyle
DECL|function|position
DECL|function|position
DECL|function|processCurrentSubpath
DECL|function|processCurrentSubpath
DECL|function|qdashstroker_cubicTo
DECL|function|qdashstroker_lineTo
DECL|function|qdashstroker_moveTo
DECL|function|qt_curves_for_arc
DECL|function|qt_stroke_side
DECL|function|qt_t_for_arc_angle
DECL|function|strokeEllipse
DECL|function|strokePath
DECL|function|strokePolygon
DECL|function|~QStroker
DECL|function|~QStrokerOps
DECL|member|m_curve
DECL|member|m_curve_index
DECL|member|m_curve_threshold
DECL|member|m_path
DECL|member|m_path
DECL|member|m_path
DECL|member|m_pos
DECL|member|m_pos
DECL|member|m_pos
