DECL|function|begin
DECL|function|cubicTo
DECL|function|emitCubicTo
DECL|function|emitCubicTo
DECL|function|emitLineTo
DECL|function|emitLineTo
DECL|function|emitMoveTo
DECL|function|emitMoveTo
DECL|function|end
DECL|function|lineTo
DECL|function|moveTo
DECL|function|operator
DECL|macro|QSTROKER_P_H
DECL|macro|QT_PATH_KAPPA
DECL|macro|qt_fixed_to_int
DECL|macro|qt_fixed_to_real
DECL|macro|qt_int_to_fixed
DECL|macro|qt_real_to_fixed
DECL|member|x
DECL|member|y
DECL|struct|qfixed2d
DECL|typedef|qStrokerCubicToHook
DECL|typedef|qStrokerLineToHook
DECL|typedef|qStrokerMoveToHook
DECL|typedef|qfixed
