DECL|macro|AT
DECL|macro|END
DECL|macro|LEAF_MIPS32R2
DECL|macro|LEAF_MIPS_DSP
DECL|macro|LEAF_MIPS_DSPR2
DECL|macro|QT_MIPS_DSP_H__
DECL|macro|a0
DECL|macro|a1
DECL|macro|a2
DECL|macro|a3
DECL|macro|fp
DECL|macro|gp
DECL|macro|k0
DECL|macro|k1
DECL|macro|ra
DECL|macro|s0
DECL|macro|s1
DECL|macro|s2
DECL|macro|s3
DECL|macro|s4
DECL|macro|s5
DECL|macro|s6
DECL|macro|s7
DECL|macro|s8
DECL|macro|sp
DECL|macro|t0
DECL|macro|t1
DECL|macro|t2
DECL|macro|t3
DECL|macro|t4
DECL|macro|t5
DECL|macro|t6
DECL|macro|t7
DECL|macro|t8
DECL|macro|t9
DECL|macro|v0
DECL|macro|v1
DECL|macro|zero
