DECL|function|calculateSubPixelPositionCount
DECL|function|createTextureData
DECL|function|fillInPendingGlyphs
DECL|function|fillTexture
DECL|function|populate
DECL|function|qt_next_power_of_two
DECL|function|resizeTextureData
DECL|function|textureMapForGlyph
