DECL|function|QX11WindowSurface
DECL|function|beginPaint
DECL|function|features
DECL|function|flush
DECL|function|grabWidget
DECL|function|paintDevice
DECL|function|scroll
DECL|function|setGeometry
DECL|function|~QX11WindowSurface
DECL|member|device
DECL|member|translucentBackground
DECL|member|widget
DECL|struct|QX11WindowSurfacePrivate
