DECL|macro|QWINDOWSURFACE_RASTER_P_H
DECL|macro|Q_AC_SRC_ALPHA
DECL|macro|Q_LWA_ALPHA
DECL|macro|Q_ULW_ALPHA
DECL|macro|Q_WS_EX_LAYERED
DECL|member|cbSize
DECL|member|crKey
DECL|member|dwFlags
DECL|member|hdcDst
DECL|member|hdcSrc
DECL|member|pblend
DECL|member|pptDst
DECL|member|pptSrc
DECL|member|prcDirty
DECL|member|psize
DECL|struct|Q_UPDATELAYEREDWINDOWINFO
DECL|typedef|PtrUpdateLayeredWindow
DECL|typedef|PtrUpdateLayeredWindowIndirect
DECL|variable|QNativeImage
DECL|variable|QPaintDevice
DECL|variable|QPoint
DECL|variable|QRasterWindowSurfacePrivate
DECL|variable|QRegion
DECL|variable|QRegion
DECL|variable|QSize
DECL|variable|QWidget
