DECL|class|SpinBox
DECL|class|sizeHint_SpinBox
DECL|class|tst_QSpinBox
DECL|function|SpinBox
DECL|function|editingFinished
DECL|function|getSetCheck
DECL|function|init
DECL|function|integerOverflow
DECL|function|lineEdit
DECL|function|locale
DECL|function|locale_data
DECL|function|removeAll
DECL|function|setMinMax
DECL|function|setMinMax_data
DECL|function|setPrefixSuffix
DECL|function|setPrefixSuffix_data
DECL|function|setReadOnly
DECL|function|setSingleStep
DECL|function|setSingleStep_data
DECL|function|setSpecialValueText
DECL|function|setSpecialValueText_data
DECL|function|setTracking
DECL|function|setTracking_data
DECL|function|setValue
DECL|function|setValue_data
DECL|function|setWrapping
DECL|function|setWrapping_data
DECL|function|sizeHint
DECL|function|sizeHint
DECL|function|specialValue
DECL|function|startWithDash
DECL|function|stateName
DECL|function|taskQTBUG_5008_textFromValueAndValidate
DECL|function|textFromValue
DECL|function|textFromValue
DECL|function|tst_QSpinBox
DECL|function|undoRedo
DECL|function|validate
DECL|function|valueChangedHelper
DECL|function|valueChangedHelper
DECL|function|valueFromText
DECL|function|valueFromTextAndValidate
DECL|function|valueFromTextAndValidate_data
DECL|member|actualTexts
DECL|member|actualValues
DECL|member|sizeHintRequests
DECL|typedef|IntList
