DECL|class|EventTestTransition
DECL|class|TestClass
DECL|class|tst_QState
DECL|function|EventTestTransition
DECL|function|TestClass
DECL|function|assignProperty
DECL|function|assignPropertyTwice
DECL|function|eventTest
DECL|function|historyInitialState
DECL|function|onTransition
DECL|function|slot
DECL|function|transitions
DECL|function|tst_QState
DECL|function|~tst_QState
DECL|macro|QTRY_COMPARE
DECL|member|called
DECL|member|functionCalled
DECL|member|m_type
