DECL|class|EventTestTransition
DECL|class|MyState
DECL|class|MyTransition
DECL|class|SignalConnectionTester
DECL|class|TestClass
DECL|class|TestTrigger
DECL|class|tst_QState
DECL|function|EventTestTransition
DECL|function|MyState
DECL|function|MyTransition
DECL|function|SignalConnectionTester
DECL|function|TestClass
DECL|function|TestTrigger
DECL|function|assignProperty
DECL|function|assignPropertyTwice
DECL|function|emitPrivateSignals
DECL|function|emitPrivateSignals
DECL|function|emitTrigger
DECL|function|eventTest
DECL|function|historyInitialState
DECL|function|onTransition
DECL|function|parallelStateAndInitialState
DECL|function|privateSignals
DECL|function|slot
DECL|function|testSlot
DECL|function|transitions
DECL|member|called
DECL|member|m_type
DECL|member|testPassed
