DECL|function|TableModel
DECL|function|columnCount
DECL|function|data
DECL|function|flags
DECL|function|headerData
DECL|function|insertColumns
DECL|function|insertRows
DECL|function|removeColumns
DECL|function|removeRows
DECL|function|rowCount
DECL|function|setData
