DECL|class|MyModel
DECL|class|XyzDriver
DECL|class|XyzResult
DECL|function|QSqlDatabase_snippets
DECL|function|QSqlField_snippets
DECL|function|QSqlQueryModel_snippets
DECL|function|QSqlQuery_snippets
DECL|function|QSqlTableModel_snippets
DECL|function|XyzDriver
DECL|function|XyzResult
DECL|function|close
DECL|function|createResult
DECL|function|data
DECL|function|data
DECL|function|doSomething
DECL|function|fetch
DECL|function|fetchFirst
DECL|function|fetchLast
DECL|function|hasFeature
DECL|function|isNull
DECL|function|main
DECL|function|numRowsAffected
DECL|function|open
DECL|function|record
DECL|function|reset
DECL|function|size
DECL|function|sql_intro_snippets
DECL|function|tr
DECL|function|~XyzDriver
DECL|function|~XyzResult
DECL|member|m_specialColumnNo
