DECL|class|FileEngineHandler
DECL|class|Iterator
DECL|class|MountingFileEngine
DECL|class|ReferenceFileEngine
DECL|class|tst_QAbstractFileEngine
DECL|function|File
DECL|function|Iterator
DECL|function|MountingFileEngine
DECL|function|ReferenceFileEngine
DECL|function|beginEntryList
DECL|function|cleanupTestCase
DECL|function|close
DECL|function|copy
DECL|function|create
DECL|function|currentFileName
DECL|function|customHandler
DECL|function|fileFlags
DECL|function|fileFlags
DECL|function|fileIO
DECL|function|fileIO_data
DECL|function|fileName
DECL|function|fileTime
DECL|function|flush
DECL|function|hasNext
DECL|function|mounting
DECL|function|mounting_data
DECL|function|next
DECL|function|open
DECL|function|owner
DECL|function|ownerId
DECL|function|pos
DECL|function|read
DECL|function|remove
DECL|function|rename
DECL|function|resolveFile
DECL|function|seek
DECL|function|setFileName
DECL|function|setSize
DECL|function|size
DECL|function|write
DECL|member|access
DECL|member|content
DECL|member|creation
DECL|member|fileFlags
DECL|member|fileName_
DECL|member|fileSystem
DECL|member|fileSystem
DECL|member|fileSystemGroups
DECL|member|fileSystemGroups
DECL|member|fileSystemMutex
DECL|member|fileSystemMutex
DECL|member|fileSystemUsers
DECL|member|fileSystemUsers
DECL|member|filesForRemoval
DECL|member|groupId
DECL|member|index
DECL|member|modification
DECL|member|mutex
DECL|member|names
DECL|member|openFile_
DECL|member|openForRead_
DECL|member|openForWrite_
DECL|member|position_
DECL|member|userId
DECL|struct|File
