DECL|class|tst_QImage
DECL|function|alphaChannel
DECL|function|cacheKey
DECL|function|cleanupFunction
DECL|function|cleanupFunctions
DECL|function|compareIndexed
DECL|function|convertToFormat
DECL|function|convertToFormatPreserveDotsPrMeter
DECL|function|convertToFormatPreserveText
DECL|function|convertToFormatRgb888ToRGB32
DECL|function|convertToFormat_data
DECL|function|copy
DECL|function|count
DECL|function|create
DECL|function|createAlphaMask
DECL|function|createAlphaMask_data
DECL|function|createFromUChar
DECL|function|createHeuristicMask
DECL|function|createInvalidXPM
DECL|function|deepCopyWhenPaintingActive
DECL|function|destructor
DECL|function|dotsPerMeterAndDpi
DECL|function|dotsPerMeterZero
DECL|function|fillColor
DECL|function|fillColorWithAlpha
DECL|function|fillColor_data
DECL|function|fillRGB888
DECL|function|formatHandlersInput
DECL|function|formatHandlersInput_data
DECL|function|load
DECL|function|loadFromData
DECL|function|loadFromDataStream
DECL|function|nullSize
DECL|function|nullSize_data
DECL|function|paintEngine
DECL|function|pointOverloads
DECL|function|premultipliedAlphaConsistency
DECL|function|rand8
DECL|function|rasterClipping
DECL|function|rgbSwapped
DECL|function|rgbSwapped_data
DECL|function|rotate
DECL|function|rotate_data
DECL|function|scaled
DECL|function|scaled_QTBUG19157
DECL|function|setAlphaChannel
DECL|function|setAlphaChannelWhilePainting
DECL|function|setAlphaChannel_data
DECL|function|setColor
DECL|function|setColorCount
DECL|function|setPixel
DECL|function|setPixel_data
DECL|function|smoothScale
DECL|function|smoothScale2
DECL|function|smoothScale3
DECL|function|smoothScaleAlpha
DECL|function|smoothScaleBig
DECL|function|smoothScaledSubImage
DECL|function|swap
DECL|function|transformed
DECL|function|transformed2
DECL|function|transformed_data
DECL|function|tst_QImage
DECL|variable|monoPixmap
DECL|variable|transformed_image_height
DECL|variable|transformed_image_width
