DECL|class|Employee
DECL|function|Employee
DECL|member|myDateOfBirth
DECL|member|myName
DECL|variable|hash
DECL|variable|i
DECL|variable|i
DECL|variable|list
DECL|variable|list
DECL|variable|list
DECL|variable|map
DECL|variable|map
