DECL|class|Employee
DECL|function|Employee
DECL|function|operator <
DECL|macro|EMPLOYEE_H
DECL|member|myDateOfBirth
DECL|member|myName
DECL|variable|endl
DECL|variable|i
DECL|variable|i
DECL|variable|i
DECL|variable|i
DECL|variable|i
DECL|variable|i
DECL|variable|i
DECL|variable|i
DECL|variable|map
DECL|variable|map
DECL|variable|map
DECL|variable|map
DECL|variable|map
DECL|variable|map
DECL|variable|map
DECL|variable|map
DECL|variable|map
DECL|variable|map1
DECL|variable|map2
DECL|variable|map3
DECL|variable|num1
DECL|variable|num2
DECL|variable|timeout
DECL|variable|timeout
DECL|variable|upperBound
DECL|variable|values
DECL|variable|values
