DECL|class|Employee
DECL|function|Employee
DECL|function|operator ==
DECL|function|qHash
DECL|macro|EMPLOYEE_H
DECL|member|myDateOfBirth
DECL|member|myName
DECL|variable|endl
DECL|variable|hash
DECL|variable|hash
DECL|variable|hash
DECL|variable|hash
DECL|variable|hash
DECL|variable|hash
DECL|variable|hash
DECL|variable|hash1
DECL|variable|hash2
DECL|variable|hash3
DECL|variable|i
DECL|variable|i
DECL|variable|i
DECL|variable|i
DECL|variable|i
DECL|variable|i
DECL|variable|i
DECL|variable|i
DECL|variable|num1
DECL|variable|num2
DECL|variable|objectHash
DECL|variable|timeout
DECL|variable|timeout
DECL|variable|values
DECL|variable|values
