DECL|variable|data
DECL|variable|endl
DECL|variable|i
DECL|variable|integerVector
DECL|variable|list
DECL|variable|list
DECL|variable|stdvector
DECL|variable|stdvector
DECL|variable|stringVector
DECL|variable|vect
DECL|variable|vect
DECL|variable|vector
DECL|variable|vector
DECL|variable|vector
DECL|variable|vector
DECL|variable|vector
DECL|variable|vector
DECL|variable|vector
