DECL|class|KeyPressEater
DECL|class|MainWindow
DECL|class|MyClass
DECL|class|MyClass
DECL|class|MyObject
DECL|class|MyWidget
DECL|class|QLibrary
DECL|enumerator|ExportExternalSymbolsHint
DECL|enumerator|High
DECL|enumerator|LoadArchiveMemberHint
DECL|enumerator|Low
DECL|enumerator|ResolveAllSymbolsHint
DECL|enumerator|VeryHigh
DECL|enumerator|VeryLow
DECL|enum|LoadHint
DECL|enum|Priority
DECL|function|MainWindow
DECL|function|MyObject
DECL|function|MyWidget
DECL|function|MyWindow
DECL|function|eventFilter
DECL|function|eventFilter
DECL|function|timerEvent
DECL|member|button
DECL|member|button
DECL|member|childButtons
DECL|member|example
DECL|member|label
DECL|member|lineEdit
DECL|member|list
DECL|member|myButton
DECL|member|page
DECL|member|socket
DECL|member|text
DECL|member|text
DECL|member|textEdit
DECL|member|valueChangedSignal
DECL|variable|allPButtons
DECL|variable|button
DECL|variable|button
DECL|variable|false
DECL|variable|keyPressEater
DECL|variable|label
DECL|variable|layout
DECL|variable|lineEdit
DECL|variable|list
DECL|variable|list
DECL|variable|listView
DECL|variable|n
DECL|variable|obj
DECL|variable|obj
DECL|variable|obj
DECL|variable|pushButton
DECL|variable|scrollBar
DECL|variable|timer
DECL|variable|timer
DECL|variable|widgets
