DECL|variable|captured
DECL|variable|company
DECL|variable|count
DECL|variable|count
DECL|variable|country
DECL|variable|field
DECL|variable|it
DECL|variable|line1
DECL|variable|line2
DECL|variable|list
DECL|variable|list
DECL|variable|list
DECL|variable|list
DECL|variable|pos
DECL|variable|pos
DECL|variable|pos
DECL|variable|pos
DECL|variable|pos
DECL|variable|pos
DECL|variable|str
DECL|variable|str
DECL|variable|str
DECL|variable|web
