DECL|variable|captured
DECL|variable|captured
DECL|variable|escaped
DECL|variable|hasMatch
DECL|variable|hasMatch
DECL|variable|hasMatch
DECL|variable|hasMatch
DECL|variable|hasMatch
DECL|variable|hasMatch
DECL|variable|hasMatch
DECL|variable|hasMatch
DECL|variable|hasPartialMatch
DECL|variable|hasPartialMatch
DECL|variable|hasPartialMatch
DECL|variable|hasPartialMatch
DECL|variable|hasPartialMatch
DECL|variable|hasPartialMatch
DECL|variable|hasPartialMatch
DECL|variable|i
DECL|variable|i
DECL|variable|isValid
DECL|variable|match
DECL|variable|match
DECL|variable|match
DECL|variable|match
DECL|variable|match
DECL|variable|match
DECL|variable|match
DECL|variable|match
DECL|variable|match
DECL|variable|match
DECL|variable|match
DECL|variable|match
DECL|variable|match
DECL|variable|match
DECL|variable|match
DECL|variable|options
DECL|variable|pattern
DECL|variable|pattern
DECL|variable|re
DECL|variable|re
DECL|variable|words
