DECL|function|main
DECL|member|password
DECL|member|password
DECL|member|userName
DECL|member|userName
DECL|struct|Login
DECL|struct|Login
DECL|variable|color
DECL|variable|color
DECL|variable|groups
DECL|variable|keys
DECL|variable|keys
DECL|variable|keys
DECL|variable|keys
DECL|variable|logins
DECL|variable|logins
DECL|variable|settings
DECL|variable|settings
DECL|variable|settings
DECL|variable|settings
DECL|variable|settings
DECL|variable|settings
DECL|variable|settings
DECL|variable|settings
DECL|variable|size
