DECL|class|MyTrue
DECL|class|isEnum_D
DECL|class|isEnum_E
DECL|class|isEnum_F
DECL|class|isEnum_G
DECL|class|tst_QGlobal
DECL|enumerator|isEnum_B_Byte_x
DECL|enumerator|isEnum_B_Int_x
DECL|enumerator|isEnum_B_Short_x
DECL|enum|AnEnum
DECL|enum|isEnum_B_Byte
DECL|enum|isEnum_B_Int
DECL|enum|isEnum_B_Short
DECL|function|MyTrue
DECL|function|checkptr
DECL|function|foo
DECL|function|for_each
DECL|function|isEnum
DECL|function|myStartupFunc
DECL|function|qAlignOf
DECL|function|qConstructorFunction
DECL|function|qConstructorFunctionCtor
DECL|function|qCoreAppStartupFunction
DECL|function|qCoreAppStartupFunctionRestart
DECL|function|qIsNull
DECL|function|qassert
DECL|function|qstaticassert
DECL|function|qtry
DECL|function|~MyTrue
DECL|macro|IS_ENUM_FALSE
DECL|macro|IS_ENUM_FALSE
DECL|macro|IS_ENUM_TRUE
DECL|macro|IS_ENUM_TRUE
DECL|macro|TEST_AlignOf
DECL|macro|TEST_AlignOf
DECL|macro|TEST_AlignOf_RValueRef
DECL|macro|TEST_AlignOf_RValueRef
DECL|macro|TEST_AlignOf_RValueRef
DECL|macro|TEST_AlignOf_impl
DECL|macro|TEST_AlignOf_impl
DECL|member|True
DECL|member|Value
DECL|member|dummy
DECL|member|n_
DECL|struct|AlignmentInStruct
DECL|struct|Empty
DECL|struct|MyExpresion
DECL|struct|MyTemplate
DECL|struct|Template
DECL|struct|TypeDef
DECL|struct|isEnum_A
DECL|typedef|DependentType
DECL|typedef|T
DECL|typedef|fun
DECL|typedef|memFun
DECL|union|isEnum_C
DECL|variable|qConstructorFunctionCtor
DECL|variable|qConstructorFunctionValue
DECL|variable|qStartupFunctionValue
