DECL|class|MyTrue
DECL|class|tst_QGlobal
DECL|function|MyTrue
DECL|function|checkptr
DECL|function|foo
DECL|function|for_each
DECL|function|qConstructorFunction
DECL|function|qConstructorFunctionCtor
DECL|function|qIsNull
DECL|function|qassert
DECL|function|qstaticassert
DECL|function|qtry
DECL|function|~MyTrue
DECL|member|True
DECL|member|Value
DECL|struct|MyExpresion
DECL|struct|MyTemplate
DECL|struct|Template
DECL|struct|TypeDef
DECL|typedef|DependentType
DECL|typedef|T
DECL|variable|qConstructorFunctionCtor
DECL|variable|qConstructorFunctionValue
