DECL|function|QMatrix4x4
DECL|function|QMatrix4x4
DECL|function|column
DECL|function|fill
DECL|function|isIdentity
DECL|function|operator
DECL|function|operator
DECL|function|qGenericMatrixFromMatrix4x4
DECL|function|qGenericMatrixToMatrix4x4
DECL|function|row
DECL|function|setColumn
DECL|function|setRow
DECL|function|setToIdentity
DECL|function|toGenericMatrix
DECL|macro|QMATRIX4X4_H
DECL|member|operator
DECL|variable|M
DECL|variable|M
DECL|variable|N
DECL|variable|N
DECL|variable|N
DECL|variable|N
DECL|variable|N
DECL|variable|N
DECL|variable|QMatrix
DECL|variable|QTransform
DECL|variable|QVariant
