DECL|function|QQuaternion
DECL|function|QQuaternion
DECL|function|QQuaternion
DECL|function|conjugate
DECL|function|fromEulerAngles
DECL|function|getAxisAndAngle
DECL|function|inverted
DECL|function|isIdentity
DECL|function|isNull
DECL|function|scalar
DECL|function|setScalar
DECL|function|setVector
DECL|function|setVector
DECL|function|setX
DECL|function|setY
DECL|function|setZ
DECL|function|toEulerAngles
DECL|function|toVector4D
DECL|function|vector
DECL|function|x
DECL|function|y
DECL|function|z
DECL|function|zp
DECL|macro|QQUATERNION_H
DECL|member|operator
DECL|variable|QMatrix4x4
DECL|variable|QVariant
