DECL|function|QVector2D
DECL|function|QVector2D
DECL|function|QVector2D
DECL|function|QVector2D
DECL|function|isNull
DECL|function|operator
DECL|function|operator
DECL|function|setX
DECL|function|setY
DECL|function|x
DECL|function|y
DECL|macro|QVECTOR2D_H
DECL|member|operator
DECL|variable|QVariant
DECL|variable|QVector3D
DECL|variable|QVector4D
