DECL|function|Macro
DECL|macro|PREPROCESSOR_H
DECL|member|arguments
DECL|member|isFunction
DECL|member|isVariadic
DECL|member|symbols
DECL|struct|Macro
DECL|typedef|MacroName
DECL|typedef|MacroName
DECL|typedef|MacroName
DECL|typedef|Macros
DECL|variable|QIODevice
