DECL|function|QByteArray
DECL|function|SubArray
DECL|function|SubArray
DECL|function|SubArray
DECL|function|SubArray
DECL|function|Symbol
DECL|function|Symbol
DECL|function|Symbol
DECL|function|Symbol
DECL|function|lexem
DECL|function|operator
DECL|function|qHash
DECL|function|unquotedLexem
DECL|macro|SYMBOLS_H
DECL|member|array
DECL|member|from
DECL|member|len
DECL|member|lex
DECL|member|lexemStore
DECL|member|lineNum
DECL|member|token
DECL|struct|SubArray
DECL|struct|Symbol
DECL|typedef|LexemStore
DECL|typedef|SubArray
DECL|typedef|Symbols
