DECL|function|QByteArray
DECL|function|SubArray
DECL|function|SubArray
DECL|function|SubArray
DECL|function|SubArray
DECL|function|Symbol
DECL|function|Symbol
DECL|function|Symbol
DECL|function|Symbol
DECL|function|dontReplaceSymbol
DECL|function|excludeSymbols
DECL|function|lexem
DECL|function|operator
DECL|function|qHash
DECL|function|test
DECL|function|unquotedLexem
DECL|macro|SYMBOLS_H
DECL|member|array
DECL|member|excludedSymbols
DECL|member|expandedMacro
DECL|member|from
DECL|member|index
DECL|member|len
DECL|member|lex
DECL|member|lexemStore
DECL|member|lineNum
DECL|member|symbols
DECL|member|token
DECL|struct|SafeSymbols
DECL|struct|SubArray
DECL|struct|Symbol
DECL|typedef|LexemStore
DECL|typedef|SubArray
DECL|typedef|Symbols
