DECL|enumerator|AND
DECL|enumerator|ANDAND
DECL|enumerator|AND_EQ
DECL|enumerator|ARROW
DECL|enumerator|ARROW_STAR
DECL|enumerator|ASM
DECL|enumerator|AUTO
DECL|enumerator|BACKSLASH
DECL|enumerator|BOOL
DECL|enumerator|BOOLEAN_LITERAL
DECL|enumerator|BREAK
DECL|enumerator|CASE
DECL|enumerator|CATCH
DECL|enumerator|CHAR
DECL|enumerator|CHARACTER
DECL|enumerator|CHARACTER_LITERAL
DECL|enumerator|CLASS
DECL|enumerator|COLON
DECL|enumerator|COMMA
DECL|enumerator|CONST
DECL|enumerator|CONST_CAST
DECL|enumerator|CONTINUE
DECL|enumerator|CPP_COMMENT
DECL|enumerator|C_COMMENT
DECL|enumerator|DECR
DECL|enumerator|DEFAULT
DECL|enumerator|DELETE
DECL|enumerator|DIGIT
DECL|enumerator|DO
DECL|enumerator|DOT
DECL|enumerator|DOTSTAR
DECL|enumerator|DOUBLE
DECL|enumerator|DYNAMIC_CAST
DECL|enumerator|ELIPSIS
DECL|enumerator|ELSE
DECL|enumerator|ENUM
DECL|enumerator|EQ
DECL|enumerator|EQEQ
DECL|enumerator|EXPLICIT
DECL|enumerator|EXPORT
DECL|enumerator|EXTERN
DECL|enumerator|FLOAT
DECL|enumerator|FLOATING_LITERAL
DECL|enumerator|FOR
DECL|enumerator|FRIEND
DECL|enumerator|GE
DECL|enumerator|GOTO
DECL|enumerator|GTGT
DECL|enumerator|GTGT_EQ
DECL|enumerator|HASH
DECL|enumerator|HAT
DECL|enumerator|HAT_EQ
DECL|enumerator|HEADER_NAME
DECL|enumerator|IDENTIFIER
DECL|enumerator|IF
DECL|enumerator|INCOMPLETE
DECL|enumerator|INCR
DECL|enumerator|INLINE
DECL|enumerator|INT
DECL|enumerator|INTEGER_LITERAL
DECL|enumerator|LANGLE
DECL|enumerator|LANGLE_SCOPE
DECL|enumerator|LBRACE
DECL|enumerator|LBRACK
DECL|enumerator|LE
DECL|enumerator|LONG
DECL|enumerator|LPAREN
DECL|enumerator|LTLT
DECL|enumerator|LTLT_EQ
DECL|enumerator|MINUS
DECL|enumerator|MINUS_EQ
DECL|enumerator|MOC_INCLUDE_BEGIN
DECL|enumerator|MOC_INCLUDE_END
DECL|enumerator|MUTABLE
DECL|enumerator|NAMESPACE
DECL|enumerator|NE
DECL|enumerator|NEW
DECL|enumerator|NEWLINE
DECL|enumerator|NOT
DECL|enumerator|NOTOKEN
DECL|enumerator|OPERATOR
DECL|enumerator|OR
DECL|enumerator|OROR
DECL|enumerator|OR_EQ
DECL|enumerator|PERCENT
DECL|enumerator|PERCENT_EQ
DECL|enumerator|PLUS
DECL|enumerator|PLUS_EQ
DECL|enumerator|PP_AND
DECL|enumerator|PP_ANDAND
DECL|enumerator|PP_BACKSLASH
DECL|enumerator|PP_CHARACTER
DECL|enumerator|PP_CHARACTER_LITERAL
DECL|enumerator|PP_COLON
DECL|enumerator|PP_COMMA
DECL|enumerator|PP_CPP_COMMENT
DECL|enumerator|PP_C_COMMENT
DECL|enumerator|PP_DEFINE
DECL|enumerator|PP_DEFINED
DECL|enumerator|PP_DIGIT
DECL|enumerator|PP_ELIF
DECL|enumerator|PP_ELSE
DECL|enumerator|PP_ENDIF
DECL|enumerator|PP_EQEQ
DECL|enumerator|PP_FLOATING_LITERAL
DECL|enumerator|PP_GE
DECL|enumerator|PP_GTGT
DECL|enumerator|PP_HASH
DECL|enumerator|PP_HASHHASH
DECL|enumerator|PP_HAT
DECL|enumerator|PP_IDENTIFIER
DECL|enumerator|PP_IF
DECL|enumerator|PP_IFDEF
DECL|enumerator|PP_IFNDEF
DECL|enumerator|PP_INCLUDE
DECL|enumerator|PP_INCOMPLETE
DECL|enumerator|PP_INTEGER_LITERAL
DECL|enumerator|PP_LANGLE
DECL|enumerator|PP_LE
DECL|enumerator|PP_LPAREN
DECL|enumerator|PP_LTLT
DECL|enumerator|PP_MINUS
DECL|enumerator|PP_MOC_FALSE
DECL|enumerator|PP_MOC_TRUE
DECL|enumerator|PP_NE
DECL|enumerator|PP_NEWLINE
DECL|enumerator|PP_NOT
DECL|enumerator|PP_NOTOKEN
DECL|enumerator|PP_OR
DECL|enumerator|PP_OROR
DECL|enumerator|PP_PERCENT
DECL|enumerator|PP_PLUS
DECL|enumerator|PP_QUESTION
DECL|enumerator|PP_QUOTE
DECL|enumerator|PP_RANGLE
DECL|enumerator|PP_RPAREN
DECL|enumerator|PP_SINGLEQUOTE
DECL|enumerator|PP_SLASH
DECL|enumerator|PP_STAR
DECL|enumerator|PP_STRING_LITERAL
DECL|enumerator|PP_TILDE
DECL|enumerator|PP_UNDEF
DECL|enumerator|PP_WHITESPACE
DECL|enumerator|PRIVATE
DECL|enumerator|PROTECTED
DECL|enumerator|PUBLIC
DECL|enumerator|QUESTION
DECL|enumerator|QUOTE
DECL|enumerator|Q_CLASSINFO_TOKEN
DECL|enumerator|Q_DECLARE_FLAGS_TOKEN
DECL|enumerator|Q_DECLARE_INTERFACE_TOKEN
DECL|enumerator|Q_DECLARE_METATYPE_TOKEN
DECL|enumerator|Q_ENUMS_TOKEN
DECL|enumerator|Q_FLAGS_TOKEN
DECL|enumerator|Q_GADGET_TOKEN
DECL|enumerator|Q_INTERFACES_TOKEN
DECL|enumerator|Q_INVOKABLE_TOKEN
DECL|enumerator|Q_META_TOKEN_BEGIN
DECL|enumerator|Q_META_TOKEN_END
DECL|enumerator|Q_MOC_COMPAT_TOKEN
DECL|enumerator|Q_OBJECT_TOKEN
DECL|enumerator|Q_PRIVATE_PROPERTY_TOKEN
DECL|enumerator|Q_PRIVATE_SLOT_TOKEN
DECL|enumerator|Q_PROPERTY_TOKEN
DECL|enumerator|Q_REVISION_TOKEN
DECL|enumerator|Q_SCRIPTABLE_TOKEN
DECL|enumerator|Q_SIGNALS_TOKEN
DECL|enumerator|Q_SIGNAL_TOKEN
DECL|enumerator|Q_SLOTS_TOKEN
DECL|enumerator|Q_SLOT_TOKEN
DECL|enumerator|RANGLE
DECL|enumerator|RBRACE
DECL|enumerator|RBRACK
DECL|enumerator|REGISTER
DECL|enumerator|REINTERPRET_CAST
DECL|enumerator|RETURN
DECL|enumerator|RPAREN
DECL|enumerator|SCOPE
DECL|enumerator|SEMIC
DECL|enumerator|SHORT
DECL|enumerator|SIGNALS
DECL|enumerator|SIGNED
DECL|enumerator|SINGLEQUOTE
DECL|enumerator|SIZEOF
DECL|enumerator|SLASH
DECL|enumerator|SLASH_EQ
DECL|enumerator|SLOTS
DECL|enumerator|SPECIAL_TREATMENT_MARK
DECL|enumerator|STAR
DECL|enumerator|STAR_EQ
DECL|enumerator|STATIC
DECL|enumerator|STATIC_CAST
DECL|enumerator|STRING_LITERAL
DECL|enumerator|STRUCT
DECL|enumerator|SWITCH
DECL|enumerator|TEMPLATE
DECL|enumerator|THIS
DECL|enumerator|THROW
DECL|enumerator|TILDE
DECL|enumerator|TRY
DECL|enumerator|TYPEDEF
DECL|enumerator|TYPEID
DECL|enumerator|UNION
DECL|enumerator|UNSIGNED
DECL|enumerator|USING
DECL|enumerator|VIRTUAL
DECL|enumerator|VOID
DECL|enumerator|VOLATILE
DECL|enumerator|WCHAR
DECL|enumerator|WHILE
DECL|enumerator|WHITESPACE
DECL|enum|Token
DECL|macro|TOKEN_H
DECL|typedef|PP_Token
