DECL|class|ClosingServer
DECL|class|Server
DECL|class|tst_QHttp
DECL|function|ClosingServer
DECL|function|Server
DECL|function|abortInReadyRead
DECL|function|abortInResponseHeaderReceived
DECL|function|abortSender
DECL|function|addRequest
DECL|function|authorization
DECL|function|authorization_data
DECL|function|cachingProxyAndSsl
DECL|function|caseInsensitiveKeys
DECL|function|cleanup
DECL|function|cleanupTestCase
DECL|function|connectionClose
DECL|function|constructing
DECL|function|dataReadProgress
DECL|function|dataSendProgress
DECL|function|done
DECL|function|emptyBodyInReply
DECL|function|get
DECL|function|get_data
DECL|function|handleConnection
DECL|function|head
DECL|function|head_data
DECL|function|headerAreEqual
DECL|function|init
DECL|function|initTestCase
DECL|function|initTestCase_data
DECL|function|invalidRequests
DECL|function|nestedEventLoop
DECL|function|nestedEventLoop_slot
DECL|function|newHttp
DECL|function|pctEncodedPath
DECL|function|post
DECL|function|postAuthNtlm
DECL|function|post_data
DECL|function|proxy
DECL|function|proxy2
DECL|function|proxy2_slot
DECL|function|proxy3
DECL|function|proxyAndSsl
DECL|function|proxyAuthenticationRequired
DECL|function|proxy_data
DECL|function|readyRead
DECL|function|reconnect
DECL|function|reconnect_state
DECL|function|request
DECL|function|requestFinished
DECL|function|requestStarted
DECL|function|request_data
DECL|function|responseHeaderReceived
DECL|function|serveConnection
DECL|function|setSocket
DECL|function|stateChanged
DECL|function|tst_QHttp
DECL|function|unexpectedRemoteClose
DECL|function|~tst_QHttp
DECL|macro|CURRENTREQUEST_TEST
DECL|member|bytesDoneRead
DECL|member|bytesDoneSend
DECL|member|bytesTotalRead
DECL|member|bytesTotalSend
DECL|member|connectionWithAuth
DECL|member|cur_state
DECL|member|current_id
DECL|member|done_success
DECL|member|getId
DECL|member|headId
DECL|member|http
DECL|member|ids
DECL|member|postId
DECL|member|proxyAuthCalled
DECL|member|readyRead_ba
DECL|member|reconnect_state_connect_count
DECL|member|req
DECL|member|resp
DECL|member|resultMap
DECL|member|success
DECL|struct|RequestResult
DECL|typedef|ResMapIt
DECL|variable|bytesDone_init
DECL|variable|bytesTotal_init
