DECL|class|tst_QStringRef
DECL|enumerator|BigEndian
DECL|enumerator|ByteOrder
DECL|enumerator|LittleEndian
DECL|function|cleanup
DECL|function|compare
DECL|function|compare_data
DECL|function|contains
DECL|function|count
DECL|function|double_conversion
DECL|function|double_conversion_data
DECL|function|emptyRef
DECL|function|endsWith
DECL|function|indexOf
DECL|function|indexOf2
DECL|function|indexOf2_data
DECL|function|indexOf_data
DECL|function|inf
DECL|function|integer_conversion
DECL|function|integer_conversion_data
DECL|function|isEmpty
DECL|function|isLatin
DECL|function|lastIndexOf
DECL|function|lastIndexOf_data
DECL|function|left
DECL|function|length
DECL|function|length_data
DECL|function|mid
DECL|function|nan
DECL|function|operator_eqeq_nullstring
DECL|function|right
DECL|function|sign
DECL|function|startsWith
DECL|function|toDouble
DECL|function|toDouble_data
DECL|function|toFloat
DECL|function|toInt
DECL|function|toLong
DECL|function|toLongLong
DECL|function|toLong_data
DECL|function|toNum
DECL|function|toShort
DECL|function|toUInt
DECL|function|toULong
DECL|function|toULongLong
DECL|function|toULong_data
DECL|function|toUShort
DECL|function|trimmed
DECL|macro|CREATE_REF
DECL|macro|INFINITY
DECL|macro|INFINITY
DECL|macro|INFINITY
DECL|macro|MY_DOUBLE_EPSILON
DECL|macro|NAN
DECL|macro|NAN
DECL|macro|NAN
DECL|macro|TEST_BAD
DECL|macro|TEST_BAD
DECL|macro|TEST_BAD_ALL
DECL|macro|TEST_BAD_ALL
DECL|macro|TEST_BASE
DECL|macro|TEST_BASE
DECL|macro|TEST_DOUBLE
DECL|macro|TEST_DOUBLE
DECL|macro|TEST_NEG_BASE
DECL|macro|TEST_NEG_BASE
DECL|macro|TEST_TO_INT
DECL|macro|TEST_TO_INT
DECL|macro|TEST_TO_UINT
DECL|macro|TEST_TO_UINT
DECL|macro|isnan
DECL|macro|isnan
DECL|macro|isnan
DECL|typedef|IntList
DECL|variable|be_inf_bytes
DECL|variable|be_nan_bytes
DECL|variable|le_inf_bytes
DECL|variable|le_nan_bytes
