DECL|enumerator|DigitInput
DECL|enumerator|DigitInput
DECL|enumerator|Letter
DECL|enumerator|LetterOrNumberInput
DECL|enumerator|NoSpecialInput
DECL|enumerator|SpaceInput
DECL|enumerator|SpaceInput
DECL|enum|SpecialInputType
DECL|enum|SpecialInputType
DECL|function|Config
DECL|function|InputType
DECL|function|InputType
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|qHash
DECL|macro|GLOBAL_H
DECL|member|cache
DECL|member|caseSensitivity
DECL|member|className
DECL|member|configSections
DECL|member|debug
DECL|member|maxInputSet
DECL|member|ruleFile
DECL|member|specialInput
DECL|member|val
DECL|struct|Config
DECL|struct|InputType
DECL|typedef|InputType
DECL|variable|Epsilon
