DECL|function|RE2NFA
DECL|function|createCharNFA
DECL|function|lexemUntil
DECL|function|next
DECL|function|parse
DECL|function|parseAtom
DECL|function|parseBranch
DECL|function|parseExpr
DECL|function|parseMaybeQuantifier
DECL|function|parsePiece
DECL|function|parseSet
DECL|function|parseSet2
DECL|function|skipQuote
DECL|function|test
DECL|function|tokenize
