DECL|function|MoviePlayer
DECL|function|createButtons
DECL|function|createControls
DECL|function|fitToWindow
DECL|function|goToFrame
DECL|function|open
DECL|function|openFile
DECL|function|updateButtons
DECL|function|updateFrameSlider
