DECL|function|QXcbEglNativeInterfaceHandler
DECL|function|eglConfigForContext
DECL|function|eglContextForContext
DECL|function|eglDisplayForWindow
DECL|function|nativeResourceFunctionForContext
DECL|function|nativeResourceFunctionForWindow
DECL|function|resourceType
