DECL|function|activateCallbacks
DECL|function|buildAbi
DECL|function|buildCpuArchitecture
DECL|function|detectUnixVersion
DECL|function|fromstrerror_helper
DECL|function|fromstrerror_helper
DECL|function|macVersion
DECL|function|osKernelVersion
DECL|function|osType
DECL|function|osVersion
DECL|function|prettyOsName
DECL|function|qBadAlloc
DECL|function|qMemCopy
DECL|function|qMemSet
DECL|function|qgetenv
DECL|function|qputenv
DECL|function|qrand
DECL|function|qsrand
DECL|function|qt_check_pointer
DECL|function|qt_error_string
DECL|function|qt_int_sqrt
DECL|function|qt_mac_create_fsref
DECL|function|qt_mac_from_pascal_string
DECL|function|qt_mac_to_pascal_string
DECL|function|qunsetenv
DECL|function|readEtcOsRelease
DECL|function|registerCallback
DECL|function|unknownText
DECL|function|unquote
DECL|function|unregisterCallback
DECL|function|winOsVersion
DECL|function|winVer_helper
DECL|function|windowsVersion
DECL|macro|USE_ETC_OS_RELEASE
DECL|macro|VER_PLATFORM_WIN32_CE
DECL|macro|VER_PLATFORM_WIN32_NT
DECL|macro|VER_PLATFORM_WIN32_WINDOWS
DECL|macro|VER_PLATFORM_WIN32s
DECL|member|ByteOrder
DECL|member|MacintoshVersion
DECL|member|WindowsVersion
DECL|member|callbacks
DECL|member|sysName
DECL|member|sysNameLower
DECL|member|sysRelease
DECL|member|versionIdentifier
DECL|member|versionText
DECL|struct|QInternal_CallBackTable
DECL|struct|QUnixOSVersion
DECL|typedef|SeedStorage
DECL|typedef|SeedStorageType
DECL|typedef|SeedStorageType
DECL|variable|qt_one
