DECL|function|activateCallbacks
DECL|function|fromstrerror_helper
DECL|function|fromstrerror_helper
DECL|function|macVersion
DECL|function|qBadAlloc
DECL|function|qMemCopy
DECL|function|qMemSet
DECL|function|qgetenv
DECL|function|qputenv
DECL|function|qrand
DECL|function|qsrand
DECL|function|qt_check_pointer
DECL|function|qt_error_string
DECL|function|qt_int_sqrt
DECL|function|qt_mac_create_fsref
DECL|function|qt_mac_from_pascal_string
DECL|function|qt_mac_to_pascal_string
DECL|function|qunsetenv
DECL|function|registerCallback
DECL|function|unregisterCallback
DECL|function|windowsVersion
DECL|macro|VER_PLATFORM_WIN32_CE
DECL|macro|VER_PLATFORM_WIN32_NT
DECL|macro|VER_PLATFORM_WIN32_WINDOWS
DECL|macro|VER_PLATFORM_WIN32s
DECL|member|ByteOrder
DECL|member|MacintoshVersion
DECL|member|WindowsVersion
DECL|member|callbacks
DECL|struct|QInternal_CallBackTable
DECL|typedef|SeedStorage
DECL|typedef|SeedStorageType
DECL|typedef|SeedStorageType
DECL|variable|qt_one
