DECL|class|QLibraryInfoPrivate
DECL|function|QLibraryInfo
DECL|function|QLibrarySettings
DECL|function|buildDate
DECL|function|cleanup
DECL|function|configuration
DECL|function|findConfiguration
DECL|function|haveGroup
DECL|function|isDebugBuild
DECL|function|licensedProducts
DECL|function|licensee
DECL|function|location
DECL|function|qt_core_boilerplate
DECL|function|rawLocation
DECL|member|haveEffectivePaths
DECL|member|haveEffectiveSourcePaths
DECL|member|havePaths
DECL|member|key
DECL|member|settings
DECL|member|value
DECL|struct|QLibrarySettings
DECL|variable|qtConfEntries
DECL|variable|qt_core_interpreter
