DECL|class|QLibraryInfoPrivate
DECL|function|QLibraryInfo
DECL|function|QLibrarySettings
DECL|function|buildDate
DECL|function|configuration
DECL|function|findConfiguration
DECL|function|haveGroup
DECL|function|isDebugBuild
DECL|function|licensedProducts
DECL|function|licensee
DECL|function|location
DECL|function|platformPluginArguments
DECL|function|qt_core_boilerplate
DECL|function|rawLocation
DECL|macro|COMPILER_STRING
DECL|macro|COMPILER_STRING
DECL|macro|COMPILER_STRING
DECL|macro|COMPILER_STRING
DECL|macro|COMPILER_STRING
DECL|macro|COMPILER_STRING
DECL|macro|COMPILER_STRING
DECL|macro|COMPILER_STRING
DECL|macro|COMPILER_STRING
DECL|macro|COMPILER_STRING
DECL|macro|COMPILER_STRING
DECL|macro|COMPILER_STRING
DECL|macro|DEBUG_STRING
DECL|macro|DEBUG_STRING
DECL|macro|ICC_COMPAT
DECL|macro|ICC_COMPAT
DECL|macro|ICC_COMPAT
DECL|macro|ICC_COMPAT
DECL|macro|ICC_VERSION
DECL|macro|ICC_VERSION
DECL|macro|ICC_VERSION
DECL|macro|ICC_VERSION
DECL|macro|ICC_VERSION
DECL|macro|QT_BUILD_STR
DECL|macro|SHARED_STRING
DECL|macro|SHARED_STRING
DECL|member|haveEffectivePaths
DECL|member|haveEffectiveSourcePaths
DECL|member|havePaths
DECL|member|key
DECL|member|settings
DECL|member|value
DECL|struct|QLibrarySettings
DECL|variable|platformsSection
DECL|variable|qtConfEntries
DECL|variable|qt_core_interpreter
