DECL|function|QMessagePattern
DECL|function|android_default_message_handler
DECL|function|copy
DECL|function|critical
DECL|function|critical
DECL|function|critical
DECL|function|critical
DECL|function|critical
DECL|function|critical
DECL|function|debug
DECL|function|debug
DECL|function|debug
DECL|function|debug
DECL|function|debug
DECL|function|debug
DECL|function|grabMessageHandler
DECL|function|grabMessageHandler
DECL|function|isFatal
DECL|function|qCleanupFuncinfo
DECL|function|qDefaultMessageHandler
DECL|function|qDefaultMsgHandler
DECL|function|qErrnoWarning
DECL|function|qErrnoWarning
DECL|function|qFormatLogMessage
DECL|function|qInstallMessageHandler
DECL|function|qInstallMsgHandler
DECL|function|qSetMessagePattern
DECL|function|qt_logging_to_console
DECL|function|qt_message
DECL|function|qt_message_fatal
DECL|function|qt_message_output
DECL|function|qt_message_print
DECL|function|setPattern
DECL|function|slog2_default_handler
DECL|function|systemd_default_message_handler
DECL|function|ungrabMessageHandler
DECL|function|ungrabMessageHandler
DECL|function|warning
DECL|function|warning
DECL|function|warning
DECL|function|warning
DECL|function|warning
DECL|function|warning
DECL|function|willLogToConsole
DECL|function|~QMessagePattern
DECL|macro|HANDLE_IF_TOKEN
DECL|macro|HANDLE_IF_TOKEN
DECL|macro|IF_TOKEN
DECL|macro|IF_TOKEN
DECL|macro|QLOGGING_HAVE_BACKTRACE
DECL|macro|QLOGGING_HAVE_BACKTRACE
DECL|macro|QT_LOG_CODE
DECL|macro|SD_JOURNAL_SUPPRESS_LOCATION
DECL|macro|qCritical
DECL|macro|qDebug
DECL|macro|qFatal
DECL|macro|qWarning
DECL|member|backtraceDepth
DECL|member|backtraceSeparator
DECL|member|fromEnvironment
DECL|member|literals
DECL|member|mutex
DECL|member|mutex
DECL|member|startTime
DECL|member|timeFormat
DECL|member|timer
DECL|member|tokens
DECL|struct|QMessagePattern
DECL|typedef|QtMsgHandler
DECL|variable|appnameTokenC
DECL|variable|backtraceTokenC
DECL|variable|categoryTokenC
DECL|variable|defaultPattern
DECL|variable|emptyTokenC
DECL|variable|endifTokenC
DECL|variable|fileTokenC
DECL|variable|functionTokenC
DECL|variable|ifCategoryTokenC
DECL|variable|ifCriticalTokenC
DECL|variable|ifDebugTokenC
DECL|variable|ifFatalTokenC
DECL|variable|ifWarningTokenC
DECL|variable|lineTokenC
DECL|variable|messageHandler
DECL|variable|messageTokenC
DECL|variable|msgHandler
DECL|variable|msgHandlerGrabbed
DECL|variable|pidTokenC
DECL|variable|threadidTokenC
DECL|variable|timeTokenC
DECL|variable|typeTokenC
