DECL|enumerator|QtCriticalMsg
DECL|enumerator|QtDebugMsg
DECL|enumerator|QtFatalMsg
DECL|enumerator|QtSystemMsg
DECL|enumerator|QtWarningMsg
DECL|enum|QtMsgType
DECL|macro|QLOGGING_H
DECL|macro|QT_NO_QDEBUG_MACRO
DECL|macro|QT_NO_QWARNING_MACRO
DECL|macro|qCritical
DECL|macro|qDebug
DECL|macro|qDebug
DECL|macro|qDebug
DECL|macro|qFatal
DECL|macro|qWarning
DECL|macro|qWarning
DECL|macro|qWarning
DECL|typedef|QMessageHandler
DECL|typedef|QtMsgHandler
DECL|variable|QDebug
DECL|variable|QNoDebug
