DECL|function|qt_inf
DECL|function|qt_is_finite
DECL|function|qt_is_finite
DECL|function|qt_is_inf
DECL|function|qt_is_inf
DECL|function|qt_is_nan
DECL|function|qt_is_nan
DECL|function|qt_qnan
DECL|function|qt_snan
DECL|macro|QNUMERIC_P_H
DECL|member|c
DECL|member|c
DECL|member|c
DECL|member|c
DECL|member|c
DECL|member|c
DECL|member|d
DECL|member|d
DECL|member|d
DECL|member|d
DECL|member|d
DECL|member|d
DECL|variable|qt_be_inf_bytes
DECL|variable|qt_be_qnan_bytes
DECL|variable|qt_be_snan_bytes
DECL|variable|qt_le_inf_bytes
DECL|variable|qt_le_qnan_bytes
DECL|variable|qt_le_snan_bytes
