DECL|enumerator|Q_COMPLEX_TYPE
DECL|enumerator|Q_DUMMY_TYPE
DECL|enumerator|Q_MOVABLE_TYPE
DECL|enumerator|Q_PRIMITIVE_TYPE
DECL|enumerator|Q_RELOCATABLE_TYPE
DECL|enumerator|Q_STATIC_TYPE
DECL|macro|QTYPEINFO_H
DECL|macro|Q_DECLARE_MOVABLE_CONTAINER
DECL|macro|Q_DECLARE_MOVABLE_CONTAINER
DECL|macro|Q_DECLARE_SHARED
DECL|macro|Q_DECLARE_SHARED_IMPL
DECL|macro|Q_DECLARE_SHARED_NOT_MOVABLE_UNTIL_QT6
DECL|macro|Q_DECLARE_TYPEINFO
DECL|macro|Q_DECLARE_TYPEINFO_BODY
DECL|struct|T
DECL|variable|QFlags
DECL|variable|QLinkedList
DECL|variable|QList
DECL|variable|QQueue
DECL|variable|QSet
DECL|variable|QStack
DECL|variable|QVector
DECL|variable|T
DECL|variable|T
DECL|variable|T
DECL|variable|T1
DECL|variable|T2
DECL|variable|T3
DECL|variable|T4
DECL|variable|typename
