DECL|class|HttpReceiver
DECL|class|tst_qnetworkreply
DECL|function|finishedSlot
DECL|function|initTestCase
DECL|function|limiting
DECL|function|limiting_data
DECL|function|readyReadSlot
DECL|function|setSslConfiguration
DECL|function|setSslConfiguration_data
DECL|function|startTimer
DECL|function|timeoutSlot
DECL|macro|BANDWIDTH_LIMIT_BYTES
DECL|macro|TIME_ESTIMATION_SECONDS
DECL|member|stopwatch
DECL|member|timer
DECL|variable|reply
