DECL|function|CPixelMetricsMapperViewContainer
DECL|function|ClearL
DECL|function|ClearL
DECL|function|ComponentControl
DECL|function|ConstructL
DECL|function|ConstructL
DECL|function|CountComponentControls
DECL|function|DoActivateL
DECL|function|DoDeactivate
DECL|function|Draw
DECL|function|HandleCommandL
DECL|function|HandleControlEventL
DECL|function|HandleResourceChange
DECL|function|HandleStatusPaneSizeChange
DECL|function|Id
DECL|function|OfferKeyEventL
DECL|function|ShowL
DECL|function|ShowL
DECL|function|SizeChanged
DECL|function|~CPixelMetricsMapperView
DECL|function|~CPixelMetricsMapperViewContainer
