DECL|function|AppDllUid
DECL|function|CPixelMetricsMapperAppUi
DECL|function|ClearL
DECL|function|ConstructL
DECL|function|ConstructL
DECL|function|CreateAppUiL
DECL|function|CreateDocumentL
DECL|function|CreateHeaderFileL
DECL|function|CreateLayoutNameL
DECL|function|E32Main
DECL|function|HandleCommandL
DECL|function|HandleKeyEventL
DECL|function|NewApplication
DECL|function|ShowL
DECL|function|ShowSingleValueL
DECL|function|~CPixelMetricsMapperAppUi
DECL|typedef|TMyBigBuffer
DECL|typedef|TMySmallBuffer
DECL|variable|KHeaderValues
