DECL|class|QXmlCharRange
DECL|function|isBaseChar
DECL|function|isChar
DECL|function|isCombiningChar
DECL|function|isDigit
DECL|function|isEncName
DECL|function|isExtender
DECL|function|isIdeographic
DECL|function|isLetter
DECL|function|isNCName
DECL|function|isNameChar
DECL|function|isPublicID
DECL|function|rangeContains
DECL|member|max
DECL|member|min
DECL|typedef|RangeIter
DECL|variable|g_base_begin
DECL|variable|g_base_end
DECL|variable|g_combining_begin
DECL|variable|g_combining_end
DECL|variable|g_digit_begin
DECL|variable|g_digit_end
DECL|variable|g_extender_begin
DECL|variable|g_extender_end
DECL|variable|g_ideographic_begin
DECL|variable|g_ideographic_end
