DECL|macro|QXMLSTREAM_H
DECL|typedef|QXmlStreamEntityDeclarations
DECL|typedef|QXmlStreamNamespaceDeclarations
DECL|typedef|QXmlStreamNotationDeclarations
DECL|variable|QXmlStreamAttributes
DECL|variable|QXmlStreamReaderPrivate
DECL|variable|QXmlStreamWriterPrivate
