DECL|function|TestCompiler
DECL|function|addToEnvironment
DECL|function|clearCommandOutput
DECL|function|commandOutput
DECL|function|exists
DECL|function|make
DECL|function|makeClean
DECL|function|makeDistClean
DECL|function|qmake
DECL|function|removeMakefile
DECL|function|resetEnvironment
DECL|function|runCommand
DECL|function|setBaseCommands
DECL|function|targetName
DECL|function|~TestCompiler
