DECL|class|EventLoopExecutor
DECL|class|EventLoopExiter
DECL|class|EventLoopThread
DECL|class|MultipleExecThread
DECL|class|SocketEventsTester
DECL|class|SocketTestThread
DECL|class|StartStopEvent
DECL|class|TimerReceiver
DECL|class|tst_QEventLoop
DECL|enumerator|NbEvent
DECL|enumerator|NbEventQueue
DECL|enumerator|NbObject
DECL|enumerator|NbThread
DECL|function|CustomEvent
DECL|function|EventLoopExecutor
DECL|function|EventLoopExiter
DECL|function|MultipleExecThread
DECL|function|Object
DECL|function|SocketEventsTester
DECL|function|SocketTestThread
DECL|function|StartStopEvent
DECL|function|TimerReceiver
DECL|function|customEvent
DECL|function|customEvent
DECL|function|exec
DECL|function|exec
DECL|function|execAfterExit
DECL|function|exit
DECL|function|exit1
DECL|function|exit2
DECL|function|init
DECL|function|nestedLoops
DECL|function|processEvents
DECL|function|processEventsExcludeSocket
DECL|function|processEventsExcludeTimers
DECL|function|quit
DECL|function|reexec
DECL|function|run
DECL|function|run
DECL|function|run
DECL|function|sendAck
DECL|function|sendHello
DECL|function|timerEvent
DECL|function|wakeUp
DECL|function|~SocketEventsTester
DECL|macro|EXEC_TIMEOUT
DECL|macro|tst_QEventLoop
DECL|member|cond
DECL|member|count
DECL|member|dataArrived
DECL|member|dataArrived
DECL|member|el
DECL|member|eventLoop
DECL|member|eventLoop
DECL|member|eventLoop
DECL|member|gotTimerEvent
DECL|member|lastReceived
DECL|member|mutex
DECL|member|result1
DECL|member|result2
DECL|member|returnCode
DECL|member|server
DECL|member|slots
DECL|member|socket
DECL|member|testResult
DECL|member|testResult
DECL|member|value
DECL|namespace|DeliverInDefinedOrder
DECL|struct|CustomEvent
DECL|struct|Object
