DECL|function|StyleWidget
DECL|function|on_blueStyle_clicked
DECL|function|on_close_clicked
DECL|function|on_khakiStyle_clicked
DECL|function|on_noStyle_clicked
DECL|function|on_transparentStyle_clicked
