DECL|function|QRfbHextileEncoder
DECL|function|QVNCDirtyMap
DECL|function|QVNCScreenPrivate
DECL|function|QVNCServer
DECL|function|QVNCServer
DECL|function|beginRect
DECL|function|blendCursor
DECL|function|buttonChange
DECL|function|checkUpdate
DECL|function|clientCutText
DECL|function|convertPixels
DECL|function|dirty
DECL|function|discardClient
DECL|function|endRect
DECL|function|frameBufferUpdateRequest
DECL|function|init
DECL|function|keyEvent
DECL|function|newConnection
DECL|function|next
DECL|function|pixelConversionNeeded
DECL|function|pointerEvent
DECL|function|qt_conv16ToRgb
DECL|function|read
DECL|function|read
DECL|function|read
DECL|function|read
DECL|function|read
DECL|function|read
DECL|function|read
DECL|function|read
DECL|function|read
DECL|function|read
DECL|function|read
DECL|function|readClient
DECL|function|reset
DECL|function|screenImage
DECL|function|setClean
DECL|function|setColor
DECL|function|setDirty
DECL|function|setDirty
DECL|function|setDirty
DECL|function|setEncodings
DECL|function|setName
DECL|function|setPixelFormat
DECL|function|write
DECL|function|write
DECL|function|write
DECL|function|write
DECL|function|write
DECL|function|write
DECL|function|write
DECL|function|write
DECL|function|~QVNCDirtyMap
DECL|function|~QVNCScreenPrivate
DECL|function|~QVNCServer
DECL|macro|QT_NO_QWS_CURSOR
DECL|macro|QT_QWS_DEPTH16_RGB
DECL|macro|QT_QWS_VNC_DEBUG
DECL|member|keycode
DECL|member|keysym
DECL|variable|keyMap
DECL|variable|qt_bbits
DECL|variable|qt_blue_mask
DECL|variable|qt_blue_rounding_shift
DECL|variable|qt_gbits
DECL|variable|qt_green_mask
DECL|variable|qt_green_rounding_shift
DECL|variable|qt_green_shift
DECL|variable|qt_neg_blue_shift
DECL|variable|qt_rbits
DECL|variable|qt_red_mask
DECL|variable|qt_red_rounding_shift
DECL|variable|qt_red_shift
