DECL|function|createIconMask
DECL|function|qImageFromWinHBITMAP
DECL|function|qPixmapFromWinHBITMAP
DECL|function|qPixmapFromWinHICON
DECL|function|qPixmapToWinHBITMAP
DECL|function|qPixmapToWinHICON
