DECL|function|QWindowsCursor
DECL|function|QWindowsPixmapCursorCacheKey
DECL|function|changeCursor
DECL|function|createBitmapCursor
DECL|function|createBitmapCursor
DECL|function|createCursorFromShape
DECL|function|createPixmapCursor
DECL|function|createPixmapCursorFromData
DECL|function|cursorState
DECL|function|customCursor
DECL|function|customCursor
DECL|function|dragDefaultCursor
DECL|function|initResources
DECL|function|mousePosition
DECL|function|pixmapWindowCursor
DECL|function|pos
DECL|function|setPos
DECL|function|standardCursorSize
DECL|function|standardWindowCursor
DECL|function|systemCursorSize
DECL|member|fileName
DECL|member|hotSpotX
DECL|member|hotSpotY
DECL|member|resource
DECL|member|shape
DECL|member|shape
DECL|member|size
DECL|struct|QWindowsCustomPngCursor
DECL|struct|QWindowsStandardCursorMapping
