DECL|function|QWindowsScreen
DECL|function|QWindowsScreenData
DECL|function|QWindowsScreenManager
DECL|function|deviceDPI
DECL|function|deviceDPI
DECL|function|deviceSizeMM
DECL|function|findTopLevelAt
DECL|function|grabWindow
DECL|function|handleChanges
DECL|function|handleDisplayChange
DECL|function|handleScreenChanges
DECL|function|indexOfMonitor
DECL|function|indexOfMonitor
DECL|function|monitorData
DECL|function|monitorEnumCallback
DECL|function|operator <<
DECL|function|screenOf
DECL|function|virtualSiblings
DECL|function|windowAt
DECL|function|windowUnderMouse
DECL|function|~QWindowsScreenManager
DECL|typedef|WindowsScreenDataList
