DECL|class|QWindowsOleDropSource
DECL|function|AddRef
DECL|function|AddRef
DECL|function|DragEnter
DECL|function|DragLeave
DECL|function|DragOver
DECL|function|Drop
DECL|function|GiveFeedback
DECL|function|QWindowsDrag
DECL|function|QWindowsOleDropSource
DECL|function|QWindowsOleDropTarget
DECL|function|QueryContinueDrag
DECL|function|QueryInterface
DECL|function|QueryInterface
DECL|function|Release
DECL|function|Release
DECL|function|cancel
DECL|function|clearCursors
DECL|function|createCursors
DECL|function|defaultCursor
DECL|function|drop
DECL|function|findDragOverWindow
DECL|function|instance
DECL|function|move
DECL|function|releaseDropDataObject
DECL|function|retrieveDataObject
DECL|function|sendDragEnterEvent
DECL|function|startDrag
DECL|function|toQtKeyboardModifiers
DECL|function|translateToQDragDropAction
DECL|function|translateToQDragDropActions
DECL|function|translateToWinDragEffects
DECL|function|~QWindowsDrag
DECL|function|~QWindowsOleDropSource
DECL|function|~QWindowsOleDropTarget
DECL|macro|KEY_STATE_BUTTON_MASK
DECL|member|m_currentAction
DECL|member|m_currentButtons
DECL|member|m_cursors
DECL|member|m_drag
DECL|member|m_refs
DECL|typedef|ActionCursorMap
DECL|variable|copyDragCursorXpmC
DECL|variable|ignoreDragCursorXpmC
DECL|variable|linkDragCursorXpmC
DECL|variable|moveDragCursorXpmC
