DECL|function|QWindowsContext
DECL|function|QWindowsContextPrivate
DECL|function|QWindowsShell32DLL
DECL|function|QWindowsUser32DLL
DECL|function|addWindow
DECL|function|asyncExpose
DECL|function|clearWindowUnderMouse
DECL|function|comErrorString
DECL|function|componentVerbose
DECL|function|createDummyWindow
DECL|function|defaultDPI
DECL|function|displayContext
DECL|function|findClosestPlatformWindow
DECL|function|findPlatformWindow
DECL|function|findPlatformWindowAt
DECL|function|findWindow
DECL|function|handleContextMenuEvent
DECL|function|handleFocusEvent
DECL|function|hasTouchSupport
DECL|function|init
DECL|function|init
DECL|function|initTouch
DECL|function|instance
DECL|function|keyGrabber
DECL|function|mimeConverter
DECL|function|possibleKeys
DECL|function|qWindowsWndProc
DECL|function|registerWindowClass
DECL|function|registerWindowClass
DECL|function|removeWindow
DECL|function|screenDepth
DECL|function|screenManager
DECL|function|setAsyncExpose
DECL|function|setKeyGrabber
DECL|function|setWindowCreationContext
DECL|function|systemInfo
DECL|function|unregisterWindowClasses
DECL|function|useRTLExtensions
DECL|function|useRTL_Extensions
DECL|function|windowUnderMouse
DECL|function|windowsErrorMessage
DECL|function|windowsProc
DECL|function|~QWindowsContext
DECL|macro|LANG_SYRIAC
DECL|member|m_asyncExpose
DECL|member|m_creationContext
DECL|member|m_defaultDPI
DECL|member|m_displayContext
DECL|member|m_eventType
DECL|member|m_instance
DECL|member|m_keyMapper
DECL|member|m_lastActiveWindow
DECL|member|m_mimeConverter
DECL|member|m_mouseHandler
DECL|member|m_oleInitializeResult
DECL|member|m_registeredWindowClassNames
DECL|member|m_screenManager
DECL|member|m_systemInfo
DECL|member|m_windows
DECL|member|shell32dll
DECL|member|user32dll
DECL|member|verboseBackingStore
DECL|member|verboseDialogs
DECL|member|verboseEvents
DECL|member|verboseFonts
DECL|member|verboseGL
DECL|member|verboseInputMethods
DECL|member|verboseIntegration
DECL|member|verboseOLE
DECL|member|verboseTheming
DECL|member|verboseWindows
DECL|struct|QWindowsContextPrivate
DECL|typedef|HandleBaseWindowHash
