DECL|function|QWindowsTabletDeviceData
DECL|function|QWindowsWinTab32DLL
DECL|function|scalePressure
DECL|function|scaleTangentialPressure
DECL|macro|QWINDOWSTABLETSUPPORT_H
DECL|member|currentDevice
DECL|member|currentPointerType
DECL|member|maxPressure
DECL|member|maxTanPressure
DECL|member|maxX
DECL|member|maxY
DECL|member|maxZ
DECL|member|minPressure
DECL|member|minTanPressure
DECL|member|minX
DECL|member|minY
DECL|member|minZ
DECL|member|uniqueId
DECL|member|wTClose
DECL|member|wTEnable
DECL|member|wTGet
DECL|member|wTInfo
DECL|member|wTOpen
DECL|member|wTOverlap
DECL|member|wTPacketsGet
DECL|member|wTQueueSizeGet
DECL|member|wTQueueSizeSet
DECL|struct|QWindowsTabletDeviceData
DECL|struct|QWindowsWinTab32DLL
DECL|typedef|PtrWTClose
DECL|typedef|PtrWTEnable
DECL|typedef|PtrWTGet
DECL|typedef|PtrWTInfo
DECL|typedef|PtrWTOpen
DECL|typedef|PtrWTOverlap
DECL|typedef|PtrWTPacketsGet
DECL|typedef|PtrWTQueueSizeGet
DECL|typedef|PtrWTQueueSizeSet
DECL|variable|QDebug
DECL|variable|QRect
DECL|variable|QWindow
