DECL|class|QWindowsAccessible
DECL|class|QWindowsEnumerate
DECL|function|AddRef
DECL|function|AddRef
DECL|function|Clone
DECL|function|ContextSensitiveHelp
DECL|function|GetIDsOfNames
DECL|function|GetTypeInfo
DECL|function|GetTypeInfoCount
DECL|function|GetWindow
DECL|function|Invoke
DECL|function|Next
DECL|function|QStringToBSTR
DECL|function|QWindowsAccessibility
DECL|function|QWindowsAccessible
DECL|function|QWindowsEnumerate
DECL|function|QueryInterface
DECL|function|QueryInterface
DECL|function|Release
DECL|function|Release
DECL|function|Reset
DECL|function|Skip
DECL|function|accDoDefaultAction
DECL|function|accHitTest
DECL|function|accLocation
DECL|function|accNavigate
DECL|function|accSelect
DECL|function|childPointer
DECL|function|eventString
DECL|function|get_accChild
DECL|function|get_accChildCount
DECL|function|get_accDefaultAction
DECL|function|get_accDescription
DECL|function|get_accFocus
DECL|function|get_accHelp
DECL|function|get_accHelpTopic
DECL|function|get_accKeyboardShortcut
DECL|function|get_accName
DECL|function|get_accParent
DECL|function|get_accRole
DECL|function|get_accSelection
DECL|function|get_accState
DECL|function|get_accValue
DECL|function|handleAccessibleObjectFromWindowRequest
DECL|function|notifyAccessibilityUpdate
DECL|function|put_accName
DECL|function|put_accValue
DECL|function|roleString
DECL|function|showDebug
DECL|function|window_helper
DECL|function|~QWindowsAccessible
DECL|function|~QWindowsEnumerate
DECL|macro|UiaRootObjectId
DECL|member|accessible
DECL|member|array
DECL|member|current
DECL|member|ref
DECL|member|ref
DECL|typedef|NotifyMap
DECL|typedef|QAIPointer
DECL|variable|eventNum
