DECL|enumerator|QWindowsGLAccumBuffer
DECL|enumerator|QWindowsGLDirectRendering
DECL|enumerator|QWindowsGLOverlay
DECL|enumerator|QWindowsGLRenderToPixmap
DECL|enum|QWindowsGLFormatFlags
DECL|function|QOpenGLContextData
DECL|function|QOpenGLContextData
DECL|function|QWindowsOpenGLAdditionalFormat
DECL|function|moduleHandle
DECL|function|moduleIsNotOpengl32
DECL|macro|QWINDOWSGLCONTEXT_H
DECL|member|formatFlags
DECL|member|glGetError
DECL|member|glGetIntegerv
DECL|member|glGetString
DECL|member|hdc
DECL|member|hwnd
DECL|member|m_nonOpengl32
DECL|member|options
DECL|member|pixmapDepth
DECL|member|private
DECL|member|profile
DECL|member|renderingContext
DECL|member|version
DECL|member|wglCreateContext
DECL|member|wglDeleteContext
DECL|member|wglGetCurrentContext
DECL|member|wglGetCurrentDC
DECL|member|wglGetProcAddress
DECL|member|wglMakeCurrent
DECL|member|wglSetPixelFormat
DECL|member|wglShareLists
DECL|member|wglSwapBuffers
DECL|struct|QOpenGLContextData
DECL|struct|QWindowsOpenGLAdditionalFormat
DECL|struct|QWindowsOpenGLContextFormat
DECL|struct|QWindowsOpengl32DLL
DECL|variable|QDebug
DECL|variable|QOpenGLStaticContext
