DECL|function|QWindowsNativeImage
DECL|function|createDC
DECL|function|createDIB
DECL|function|systemFormat
DECL|function|~QWindowsNativeImage
DECL|member|blueMask
DECL|member|bmiHeader
DECL|member|greenMask
DECL|member|redMask
DECL|typedef|BITMAPINFO_MASK
