DECL|function|LOGFONT_to_QFont
DECL|function|addFontToDatabase
DECL|function|createFontFile
DECL|function|defaultFont
DECL|function|fallbacksForFamily
DECL|function|fontDir
DECL|function|fontEngine
DECL|function|fontEngine
DECL|function|getFntTable
DECL|function|populate
DECL|function|populateFontDatabase
DECL|function|scriptRequiresOpenType
DECL|function|storeFont
DECL|function|systemFont
DECL|function|verticalDPI
DECL|function|weightFromInteger
DECL|function|writingSystemFromCharSet
DECL|variable|ch_CN_tryFonts
DECL|variable|ch_TW_tryFonts
DECL|variable|jp_tryFonts
DECL|variable|kr_tryFonts
DECL|variable|other_tryFonts
DECL|variable|tryFonts
