DECL|function|QWindowsTheme
DECL|function|booleanSystemParametersInfo
DECL|function|createPlatformDialogHelper
DECL|function|dWordSystemParametersInfo
DECL|function|themeHint
DECL|function|usePlatformNativeDialog
