DECL|function|QWindowsTheme
DECL|function|booleanSystemParametersInfo
DECL|function|clearFonts
DECL|function|clearPalettes
DECL|function|createPlatformDialogHelper
DECL|function|dWordSystemParametersInfo
DECL|function|getSysColor
DECL|function|iconThemeSearchPaths
DECL|function|menuBarPalette
DECL|function|menuPalette
DECL|function|mixColors
DECL|function|operator <<
DECL|function|paletteRoleToString
DECL|function|paletteToString
DECL|function|refreshFonts
DECL|function|refreshPalettes
DECL|function|standardPalette
DECL|function|styleNames
DECL|function|systemPalette
DECL|function|themeHint
DECL|function|toolTipPalette
DECL|function|uiEffects
DECL|function|usePlatformNativeDialog
DECL|function|windowsThemeChanged
DECL|function|~QWindowsTheme
DECL|member|m_instance
DECL|member|name
