DECL|function|moduleHandle
DECL|function|moduleHandle
DECL|macro|QWINDOWSEGLCONTEXT_H
DECL|member|eglBindAPI
DECL|member|eglChooseConfig
DECL|member|eglCreateContext
DECL|member|eglCreatePbufferSurface
DECL|member|eglCreateWindowSurface
DECL|member|eglDestroyContext
DECL|member|eglDestroySurface
DECL|member|eglGetConfigAttrib
DECL|member|eglGetCurrentContext
DECL|member|eglGetCurrentDisplay
DECL|member|eglGetCurrentSurface
DECL|member|eglGetDisplay
DECL|member|eglGetError
DECL|member|eglGetPlatformDisplayEXT
DECL|member|eglGetProcAddress
DECL|member|eglInitialize
DECL|member|eglMakeCurrent
DECL|member|eglSwapBuffers
DECL|member|eglSwapInterval
DECL|member|eglTerminate
DECL|member|glGetString
DECL|member|m_lib
DECL|member|private
DECL|member|private
DECL|struct|QWindowsLibEGL
DECL|struct|QWindowsLibGLESv2
