DECL|class|QWindowsWindowCursorData
DECL|function|QWindowsCursor
DECL|function|QWindowsCursorCacheKey
DECL|function|QWindowsWindowCursor
DECL|function|QWindowsWindowCursor
DECL|function|QWindowsWindowCursor
DECL|function|QWindowsWindowCursorData
DECL|function|QWindowsWindowCursorData
DECL|function|changeCursor
DECL|function|createBitmapCursor
DECL|function|createPixmapCursor
DECL|function|createPixmapCursorFromData
DECL|function|createSystemCursor
DECL|function|cursor
DECL|function|cursorState
DECL|function|customCursor
DECL|function|customCursor
DECL|function|handle
DECL|function|initResources
DECL|function|isNull
DECL|function|mousePosition
DECL|function|operator =
DECL|function|pixmapWindowCursor
DECL|function|pos
DECL|function|setPos
DECL|function|standardCursorSize
DECL|function|standardWindowCursor
DECL|function|systemCursorSize
DECL|function|~QWindowsWindowCursor
DECL|function|~QWindowsWindowCursorData
DECL|member|fileName
DECL|member|hotSpotX
DECL|member|hotSpotY
DECL|member|m_cursor
DECL|member|m_handle
DECL|member|resource
DECL|member|shape
DECL|member|shape
DECL|member|size
DECL|struct|QWindowsCustomPngCursor
DECL|struct|QWindowsStandardCursorMapping
