DECL|class|DragCursorHandle
DECL|class|QWindowsDragCursorWindow
DECL|class|QWindowsOleDropSource
DECL|enumerator|MouseDrag
DECL|enumerator|TouchDrag
DECL|enum|Mode
DECL|function|AddRef
DECL|function|AddRef
DECL|function|CursorEntry
DECL|function|CursorEntry
DECL|function|DragCursorHandle
DECL|function|DragEnter
DECL|function|DragLeave
DECL|function|DragOver
DECL|function|Drop
DECL|function|GiveFeedback
DECL|function|QWindowsDrag
DECL|function|QWindowsDragCursorWindow
DECL|function|QWindowsOleDropSource
DECL|function|QWindowsOleDropTarget
DECL|function|QueryContinueDrag
DECL|function|QueryInterface
DECL|function|QueryInterface
DECL|function|Release
DECL|function|Release
DECL|function|createCursors
DECL|function|defaultCursor
DECL|function|drag
DECL|function|dragScaleFactor
DECL|function|dropData
DECL|function|dropHelper
DECL|function|handleDrag
DECL|function|instance
DECL|function|operator <<
DECL|function|paintEvent
DECL|function|releaseDropDataObject
DECL|function|retrieveDataObject
DECL|function|setPixmap
DECL|function|toQtKeyboardModifiers
DECL|function|translateToQDragDropAction
DECL|function|translateToQDragDropActions
DECL|function|translateToWinDragEffects
DECL|function|~DragCursorHandle
DECL|function|~QWindowsDrag
DECL|function|~QWindowsOleDropSource
DECL|function|~QWindowsOleDropTarget
DECL|macro|KEY_STATE_BUTTON_MASK
DECL|member|cacheKey
DECL|member|cursor
DECL|member|cursor
DECL|member|hotSpot
DECL|member|m_currentButtons
DECL|member|m_cursors
DECL|member|m_drag
DECL|member|m_mode
DECL|member|m_pixmap
DECL|member|m_refs
DECL|member|m_touchDragWindow
DECL|member|pixmap
DECL|struct|CursorEntry
DECL|typedef|ActionCursorMap
DECL|typedef|DragCursorHandlePtr
