DECL|enumerator|scancodeBitmask
DECL|function|GetKeyboardState
DECL|function|KeyRecord
DECL|function|KeyRecord
DECL|function|KeyRecorder
DECL|function|QWindowsKeyMapper
DECL|function|ToAscii
DECL|function|ToUnicode
DECL|function|asciiToKeycode
DECL|function|changeKeyboard
DECL|function|clearKeys
DECL|function|deleteLayouts
DECL|function|findKey
DECL|function|isModifierKey
DECL|function|messageKeyText
DECL|function|possibleKeys
DECL|function|queryKeyboardModifiers
DECL|function|sendExtendedPressRelease
DECL|function|setKbdState
DECL|function|showSystemMenu
DECL|function|storeKey
DECL|function|toKeyOrUnicode
DECL|function|translateKeyEvent
DECL|function|translateKeyEventInternal
DECL|function|translateMultimediaKeyEventInternal
DECL|function|updateKeyMap
DECL|function|updatePossibleKeyCodes
DECL|function|winceKeyBend
DECL|function|~QWindowsKeyMapper
DECL|macro|FAPPCOMMAND_KEY
DECL|macro|FAPPCOMMAND_MASK
DECL|macro|FAPPCOMMAND_MOUSE
DECL|macro|FAPPCOMMAND_OEM
DECL|macro|GET_APPCOMMAND_LPARAM
DECL|macro|GET_DEVICE_LPARAM
DECL|macro|GET_FLAGS_LPARAM
DECL|macro|GET_KEYSTATE_LPARAM
DECL|macro|GET_MOUSEORKEY_LPARAM
DECL|macro|LANG_DIVEHI
DECL|macro|LANG_PASHTO
DECL|macro|LANG_SYRIAC
DECL|macro|VK_OEM_3
DECL|macro|VK_OEM_PLUS
DECL|macro|disabled
DECL|macro|disabled
DECL|macro|enabled
DECL|macro|enabled
DECL|member|ascii
DECL|member|code
DECL|member|deleted_record
DECL|member|nrecs
DECL|member|records
DECL|member|state
DECL|member|text
DECL|struct|KeyRecord
DECL|struct|KeyRecorder
DECL|variable|CmdTbl
DECL|variable|KeyTbl
DECL|variable|ModsTbl
DECL|variable|NumMods
DECL|variable|QT_MAX_KEY_RECORDINGS
DECL|variable|key_recorder
