DECL|function|QWindowsGeometryHint
DECL|function|QWindowsWindowData
DECL|function|applyToMinMaxInfo
DECL|function|baseWindowOf
DECL|function|destroyIcon
DECL|function|handleOf
DECL|function|isLayered
DECL|function|mapFromGlobal
DECL|function|mapFromGlobal
DECL|function|mapToGlobal
DECL|function|mapToGlobal
DECL|function|setUserDataOf
DECL|function|userDataOf
DECL|macro|QWINDOWSWINDOW_H
DECL|member|customMargins
DECL|member|customMargins
DECL|member|customMargins
DECL|member|embedded
DECL|member|exStyle
DECL|member|flags
DECL|member|frame
DECL|member|frameHeight
DECL|member|frameWidth
DECL|member|frameX
DECL|member|frameY
DECL|member|geometry
DECL|member|geometryHint
DECL|member|hwnd
DECL|member|margins
DECL|member|maximumSize
DECL|member|minimumSize
DECL|member|obtainedGeometry
DECL|member|requestedGeometry
DECL|member|style
DECL|member|window
DECL|struct|QWindowCreationContext
DECL|struct|QWindowsGeometryHint
DECL|struct|QWindowsWindowData
DECL|variable|QDebug
DECL|variable|QWindowsOleDropTarget
