DECL|class|QWindowsWindowCursorData
DECL|function|QWindowsWindowCursor
DECL|function|QWindowsWindowCursor
DECL|function|QWindowsWindowCursor
DECL|function|QWindowsWindowCursorData
DECL|function|QWindowsWindowCursorData
DECL|function|changeCursor
DECL|function|createPixmapCursor
DECL|function|createSystemCursor
DECL|function|cursor
DECL|function|handle
DECL|function|isNull
DECL|function|mousePosition
DECL|function|operator =
DECL|function|setPos
DECL|function|standardWindowCursor
DECL|function|~QWindowsWindowCursor
DECL|function|~QWindowsWindowCursorData
DECL|member|m_cursor
DECL|member|m_handle
