DECL|function|QWindowsIntegration
DECL|function|QWindowsIntegrationPrivate
DECL|function|accessibility
DECL|function|clipboard
DECL|function|create
DECL|function|createEventDispatcher
DECL|function|createPlatformOpenGLContext
DECL|function|createPlatformSessionManager
DECL|function|createPlatformTheme
DECL|function|createPlatformWindow
DECL|function|createWindowData
DECL|function|doCreate
DECL|function|drag
DECL|function|fontDatabase
DECL|function|hasCapability
DECL|function|initialize
DECL|function|inputContext
DECL|function|instance
DECL|function|isQMLApplication
DECL|function|keyBoardAutoRepeatRateMS
DECL|function|openGLModuleType
DECL|function|options
DECL|function|parseIntOption
DECL|function|parseOptions
DECL|function|possibleKeys
DECL|function|queryKeyboardModifiers
DECL|function|services
DECL|function|staticOpenGLContext
DECL|function|styleHint
DECL|function|themeNames
DECL|function|~QWindowsIntegration
DECL|function|~QWindowsIntegrationPrivate
DECL|member|m_accessibility
DECL|member|m_clipboard
DECL|member|m_context
DECL|member|m_drag
DECL|member|m_fontDatabase
DECL|member|m_inputContext
DECL|member|m_options
DECL|member|m_services
DECL|member|m_staticOpenGLContext
DECL|struct|QWindowsIntegrationPrivate
