DECL|function|GpuDescription
DECL|function|GpuDriverVersion
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|macro|QWINDOWSOPENGLTESTER_H
DECL|member|build
DECL|member|description
DECL|member|deviceId
DECL|member|driverName
DECL|member|driverVersion
DECL|member|product
DECL|member|revision
DECL|member|subSysId
DECL|member|subVersion
DECL|member|vendorId
DECL|member|version
DECL|struct|GpuDescription
DECL|struct|GpuDriverVersion
DECL|variable|QDebug
DECL|variable|QVariant
DECL|variable|operator
