DECL|function|GpuDescription
DECL|macro|QWINDOWSOPENGLTESTER_H
DECL|member|description
DECL|member|deviceId
DECL|member|driverName
DECL|member|driverVersion
DECL|member|revision
DECL|member|subSysId
DECL|member|vendorId
DECL|struct|GpuDescription
DECL|variable|QDebug
DECL|variable|QVariant
