DECL|function|AddRef
DECL|function|AddRef
DECL|function|Clone
DECL|function|DAdvise
DECL|function|DUnadvise
DECL|function|EnumDAdvise
DECL|function|EnumFormatEtc
DECL|function|GetCanonicalFormatEtc
DECL|function|GetData
DECL|function|GetDataHere
DECL|function|Next
DECL|function|QWindowsOleDataObject
DECL|function|QWindowsOleEnumFmtEtc
DECL|function|QWindowsOleEnumFmtEtc
DECL|function|QueryGetData
DECL|function|QueryInterface
DECL|function|QueryInterface
DECL|function|Release
DECL|function|Release
DECL|function|Reset
DECL|function|SetData
DECL|function|Skip
DECL|function|copyFormatEtc
DECL|function|isNull
DECL|function|mimeData
DECL|function|releaseQt
DECL|function|reportedPerformedEffect
DECL|function|~QWindowsOleDataObject
DECL|function|~QWindowsOleEnumFmtEtc
