DECL|class|GeometrySink
DECL|function|AddBeziers
DECL|function|AddLines
DECL|function|AddRef
DECL|function|BeginFigure
DECL|function|Close
DECL|function|EndFigure
DECL|function|GeometrySink
DECL|function|QWindowsFontEngineDirectWrite
DECL|function|QueryInterface
DECL|function|Release
DECL|function|SetFillMode
DECL|function|SetSegmentFlags
DECL|function|addGlyphsToPath
DECL|function|alphaMapBoundingBox
DECL|function|alphaMapForGlyph
DECL|function|alphaRGBMapForGlyph
DECL|function|ascent
DECL|function|boundingBox
DECL|function|boundingBox
DECL|function|cloneWithSize
DECL|function|collectMetrics
DECL|function|descent
DECL|function|emSquareSize
DECL|function|fontNameSubstitute
DECL|function|fromD2D1_POINT_2F
DECL|function|getSfntTableData
DECL|function|glyphIndex
DECL|function|imageForGlyph
DECL|function|initFontInfo
DECL|function|leading
DECL|function|lineThickness
DECL|function|maxCharWidth
DECL|function|recalcAdvances
DECL|function|stringToCMap
DECL|function|supportsSubPixelPositions
DECL|function|underlinePosition
DECL|function|xHeight
DECL|function|~GeometrySink
DECL|function|~QWindowsFontEngineDirectWrite
DECL|macro|DESIGN_TO_LOGICAL
DECL|macro|WINVER
DECL|macro|WINVER
DECL|macro|_WIN32_WINNT
DECL|macro|_WIN32_WINNT
DECL|member|m_path
DECL|member|m_refCount
DECL|member|m_startPoint
