DECL|enumerator|LockScreen
DECL|enumerator|PrimaryScreen
DECL|enumerator|VirtualDesktop
DECL|enum|Flags
DECL|macro|QWINDOWSSCREEN_H
DECL|member|availableGeometry
DECL|member|depth
DECL|member|dpi
DECL|member|flags
DECL|member|format
DECL|member|geometry
DECL|member|name
DECL|member|orientation
DECL|member|physicalSizeMM
DECL|member|refreshRateHz
DECL|struct|QWindowsScreenData
