DECL|enumerator|max_font_count
DECL|function|QWindowsFontEngine
DECL|function|QWindowsMultiFontEngine
DECL|function|addGlyphToPath
DECL|function|addGlyphsToPath
DECL|function|addOutlineToPath
DECL|function|alphaMapForGlyph
DECL|function|alphaRGBMapForGlyph
DECL|function|ascent
DECL|function|averageCharWidth
DECL|function|boundingBox
DECL|function|boundingBox
DECL|function|calculateTTFGlyphWidth
DECL|function|canRender
DECL|function|cloneWithSize
DECL|function|descent
DECL|function|drawGDIGlyph
DECL|function|emSquareSize
DECL|function|faceId
DECL|function|getCMap
DECL|function|getChar
DECL|function|getGlyphBearings
DECL|function|getGlyphIndexes
DECL|function|getOutlineMetrics
DECL|function|getOutlineTextMetric
DECL|function|getSfntTableData
DECL|function|getUInt
DECL|function|getUShort
DECL|function|getUnscaledGlyph
DECL|function|hasCFFTable
DECL|function|initFontInfo
DECL|function|leading
DECL|function|lineThickness
DECL|function|loadEngine
DECL|function|maxCharWidth
DECL|function|minLeftBearing
DECL|function|minRightBearing
DECL|function|name
DECL|function|properties
DECL|function|qt_fixed_to_double
DECL|function|qt_to_qpointf
DECL|function|recalcAdvances
DECL|function|resolveGetCharWidthI
DECL|function|selectDesignFont
DECL|function|stringToCMap
DECL|function|synthesized
DECL|function|type
DECL|function|xHeight
DECL|function|~QWindowsFontEngine
DECL|function|~QWindowsMultiFontEngine
DECL|macro|CLEARTYPE_QUALITY
DECL|macro|GGO_UNHINTED
DECL|macro|MAKE_TAG
DECL|macro|MAKE_TAG
DECL|macro|SPI_GETFONTSMOOTHINGCONTRAST
DECL|macro|SPI_SETFONTSMOOTHINGCONTRAST
DECL|macro|TT_PRIM_CSPLINE
DECL|macro|_WIN32_WINNT
DECL|macro|_WIN32_WINNT
DECL|typedef|PtrGetCharWidthI
DECL|typedef|SCRIPT_CACHE
DECL|typedef|fScriptFreeCache
DECL|variable|char_table
DECL|variable|char_table_entries
DECL|variable|ptrGetCharWidthI
DECL|variable|resolvedGetCharWidthI
