DECL|class|QWindowsColorDialogHelper
DECL|class|QWindowsDialogThread
DECL|class|QWindowsFileDialogHelper
DECL|class|QWindowsNativeColorDialog
DECL|class|QWindowsNativeDialogBase
DECL|class|QWindowsNativeFileDialogBase
DECL|class|QWindowsNativeFileDialogEventHandler
DECL|class|QWindowsNativeOpenFileDialog
DECL|class|QWindowsNativeSaveFileDialog
DECL|enumerator|FDAP_BOTTOM
DECL|enumerator|FDAP_TOP
DECL|enumerator|FDESVR_ACCEPT
DECL|enumerator|FDESVR_DEFAULT
DECL|enumerator|FDESVR_REFUSE
DECL|enumerator|SIATTRIBFLAGS_AND
DECL|enumerator|SIATTRIBFLAGS_APPCOMPAT
DECL|enumerator|SIATTRIBFLAGS_MASK
DECL|enumerator|SIATTRIBFLAGS_OR
DECL|enumerator|SIGDN_DESKTOPABSOLUTEEDITING
DECL|enumerator|SIGDN_DESKTOPABSOLUTEPARSING
DECL|enumerator|SIGDN_FILESYSPATH
DECL|enumerator|SIGDN_NORMALDISPLAY
DECL|enumerator|SIGDN_PARENTRELATIVEEDITING
DECL|enumerator|SIGDN_PARENTRELATIVEFORADDRESSBAR
DECL|enumerator|SIGDN_PARENTRELATIVEPARSING
DECL|enumerator|SIGDN_URL
DECL|function|AddRef
DECL|function|COLORREFToQColor
DECL|function|DECLARE_INTERFACE_
DECL|function|DECLARE_INTERFACE_
DECL|function|DECLARE_INTERFACE_
DECL|function|DECLARE_INTERFACE_
DECL|function|DECLARE_INTERFACE_
DECL|function|DECLARE_INTERFACE_
DECL|function|DECLARE_INTERFACE_
DECL|function|DECLARE_INTERFACE_
DECL|function|DECLARE_INTERFACE_
DECL|function|OnFileOk
DECL|function|OnFolderChange
DECL|function|OnFolderChanging
DECL|function|OnHelp
DECL|function|OnOverwrite
DECL|function|OnSelectionChange
DECL|function|OnShareViolation
DECL|function|OnTypeChange
DECL|function|QWindowsColorDialogHelper
DECL|function|QWindowsDialogHelperBase
DECL|function|QWindowsDialogThread
DECL|function|QWindowsFileDialogHelper
DECL|function|QWindowsNativeColorDialog
DECL|function|QWindowsNativeDialogBase
DECL|function|QWindowsNativeFileDialogBase
DECL|function|QWindowsNativeFileDialogEventHandler
DECL|function|QueryInterface
DECL|function|Release
DECL|function|_q_platformRunNativeAppModalPanel
DECL|function|close
DECL|function|close
DECL|function|create
DECL|function|create
DECL|function|create
DECL|function|createNativeDialog
DECL|function|createNativeDialog
DECL|function|defaultNameFilterDisables
DECL|function|defaultNameFilterDisables
DECL|function|deleteNativeDialog_sys
DECL|function|dialogResultCode_sys
DECL|function|dialogType
DECL|function|directory
DECL|function|directory_sys
DECL|function|directory_sys
DECL|function|eatMouseMove
DECL|function|ensureNativeDialog
DECL|function|exec
DECL|function|exec
DECL|function|fileDialog
DECL|function|fileResult
DECL|function|fileResult
DECL|function|guidToString
DECL|function|hideFiltersDetails
DECL|function|init
DECL|function|itemPath
DECL|function|itemPaths
DECL|function|nativeDialog
DECL|function|nativeFileDialog
DECL|function|nativeFileDialog
DECL|function|nonNativeDialog
DECL|function|nonNativeDialog
DECL|function|onFolderChange
DECL|function|onSelectionChange
DECL|function|onTypeChange
DECL|function|openFileDialog
DECL|function|operator <<
DECL|function|ownerWindow
DECL|function|platformNativeDialogModalHelp
DECL|function|qColorToCOLORREF
DECL|function|result
DECL|function|result
DECL|function|run
DECL|function|selectFile_sys
DECL|function|selectFile_sys
DECL|function|selectNameFilter
DECL|function|selectNameFilter_sys
DECL|function|selectNameFilter_sys
DECL|function|selectedFiles
DECL|function|selectedFiles
DECL|function|selectedFiles_sys
DECL|function|selectedFiles_sys
DECL|function|selectedNameFilter
DECL|function|selectedNameFilter_sys
DECL|function|selectedNameFilter_sys
DECL|function|setDirectory
DECL|function|setDirectory_sys
DECL|function|setDirectory_sys
DECL|function|setFilter_sys
DECL|function|setFilter_sys
DECL|function|setHideFiltersDetails
DECL|function|setMode
DECL|function|setNameFilters
DECL|function|setNameFilters_sys
DECL|function|setNameFilters_sys
DECL|function|setVisible_sys
DECL|function|setWindowTitle
DECL|function|setWindowTitle
DECL|function|shellItem
DECL|function|supportsNonModalDialog
DECL|function|toBuffer
DECL|function|useHelper
DECL|function|~QWindowsNativeFileDialogBase
DECL|function|~QWindowsNativeFileDialogEventHandler
DECL|macro|BFFM_ENABLEOK
DECL|macro|BFFM_INITIALIZED
DECL|macro|BFFM_SELCHANGED
DECL|macro|BIF_BROWSEFORCOMPUTER
DECL|macro|BIF_BROWSEFORPRINTER
DECL|macro|BIF_BROWSEINCLUDEFILES
DECL|macro|BIF_NONEWFOLDERBUTTON
DECL|macro|BIF_NOTRANSLATETARGETS
DECL|macro|BIF_SHAREABLE
DECL|macro|FOS_ALLNONSTORAGEITEMS
DECL|macro|FOS_ALLOWMULTISELECT
DECL|macro|FOS_CREATEPROMPT
DECL|macro|FOS_DEFAULTNOMINIMODE
DECL|macro|FOS_DONTADDTORECENT
DECL|macro|FOS_FILEMUSTEXIST
DECL|macro|FOS_FORCEFILESYSTEM
DECL|macro|FOS_FORCEPREVIEWPANEON
DECL|macro|FOS_FORCESHOWHIDDEN
DECL|macro|FOS_HIDEMRUPLACES
DECL|macro|FOS_HIDEPINNEDPLACES
DECL|macro|FOS_NOCHANGEDIR
DECL|macro|FOS_NODEREFERENCELINKS
DECL|macro|FOS_NOREADONLYRETURN
DECL|macro|FOS_NOTESTFILECREATE
DECL|macro|FOS_NOVALIDATE
DECL|macro|FOS_OVERWRITEPROMPT
DECL|macro|FOS_PATHMUSTEXIST
DECL|macro|FOS_PICKFOLDERS
DECL|macro|FOS_SHAREAWARE
DECL|macro|FOS_STRICTFILETYPES
DECL|macro|GPS_BESTEFFORT
DECL|macro|GPS_DEFAULT
DECL|macro|GPS_DELAYCREATION
DECL|macro|GPS_FASTPROPERTIESONLY
DECL|macro|GPS_HANDLERPROPERTIESONLY
DECL|macro|GPS_MASK_VALID
DECL|macro|GPS_OPENSLOWITEM
DECL|macro|GPS_READWRITE
DECL|macro|GPS_TEMPORARY
DECL|macro|STRICT_TYPED_ITEMIDS
DECL|member|abID
DECL|member|cb
DECL|member|fmtid
DECL|member|hwndOwner
DECL|member|iImage
DECL|member|lParam
DECL|member|lpfn
DECL|member|lpszTitle
DECL|member|m_code
DECL|member|m_colorDialog
DECL|member|m_cookie
DECL|member|m_customColors
DECL|member|m_dialog
DECL|member|m_dialog
DECL|member|m_dialogEvents
DECL|member|m_fileDialog
DECL|member|m_fileDialog
DECL|member|m_hideFiltersDetails
DECL|member|m_nameFilters
DECL|member|m_nativeFileDialog
DECL|member|m_owner
DECL|member|m_ref
DECL|member|mkid
DECL|member|pid
DECL|member|pidlRoot
DECL|member|pszDisplayName
DECL|member|pszName
DECL|member|pszName
DECL|member|pszSpec
DECL|member|pszSpec
DECL|member|ulFlags
DECL|namespace|QWindowsDialogs
DECL|struct|_COMDLG_FILTERSPEC
DECL|typedef|BFFCALLBACK
DECL|typedef|COMDLG_FILTERSPEC
DECL|typedef|FDAP
DECL|typedef|FDE_OVERWRITE_RESPONSE
DECL|typedef|FDE_SHAREVIOLATION_RESPONSE
DECL|typedef|GETPROPERTYSTOREFLAGS
DECL|typedef|IFileOperationProgressSink
DECL|typedef|IPropertyStore
DECL|typedef|SIATTRIBFLAGS
DECL|typedef|SIGDN
DECL|typedef|qt_BROWSEINFO
DECL|typedef|qt_COMDLG_FILTERSPEC
DECL|typedef|qt_ITEMIDLIST
DECL|typedef|qt_LPCITEMIDLIST
DECL|typedef|qt_LPITEMIDLIST
DECL|typedef|qt_LPSHITEMID
DECL|typedef|qt_PROPERTYKEY
DECL|typedef|qt_SHITEMID
DECL|variable|CLSID_FileOpenDialog
DECL|variable|CLSID_FileSaveDialog
DECL|variable|IFileDialogEvents
DECL|variable|IID_IFileDialogEvents
DECL|variable|IID_IFileOpenDialog
DECL|variable|IID_IFileSaveDialog
DECL|variable|IID_IShellItem
