DECL|function|QWindowsScreen
DECL|function|QWindowsScreenData
DECL|function|QWindowsScreenManager
DECL|function|clearScreens
DECL|function|deviceDPI
DECL|function|deviceDPI
DECL|function|deviceSizeMM
DECL|function|grabWindow
DECL|function|handleChanges
DECL|function|handleDisplayChange
DECL|function|handleScreenChanges
DECL|function|indexOfMonitor
DECL|function|indexOfMonitor
DECL|function|maxMonitorHorizResolution
DECL|function|monitorDPI
DECL|function|monitorData
DECL|function|monitorData
DECL|function|monitorEnumCallback
DECL|function|monitorResolutionEnumCallback
DECL|function|moveToVirtualScreen
DECL|function|operator <<
DECL|function|removeScreen
DECL|function|screenAtDp
DECL|function|screenOf
DECL|function|sharedCursor
DECL|function|topLevelAt
DECL|function|virtualSiblings
DECL|function|windowAt
DECL|typedef|WindowsScreenDataList
