DECL|enumerator|ForceChild
DECL|enumerator|ForceTopLevel
DECL|enumerator|defaultWindowHeight
DECL|enumerator|defaultWindowWidth
DECL|enum|Flags
DECL|function|QWindowCreationContext
DECL|function|QWindowsGeometryHint
DECL|function|QWindowsWindow
DECL|function|RECTfromQRect
DECL|function|WindowCreationData
DECL|function|aboutToMakeCurrent
DECL|function|addRectToWinRegion
DECL|function|alertWindow
DECL|function|applyBlurBehindWindow
DECL|function|applyCursor
DECL|function|applyNewCursor
DECL|function|applyToMinMaxInfo
DECL|function|applyToMinMaxInfo
DECL|function|applyWindowFlags
DECL|function|clientSize
DECL|function|cornerToWinOrientation
DECL|function|create
DECL|function|create
DECL|function|createHIcon
DECL|function|createRectRegion
DECL|function|debugWinExStyle
DECL|function|debugWinStyle
DECL|function|defaultCursor
DECL|function|destroyWindow
DECL|function|findTransientChild
DECL|function|fireExpose
DECL|function|fixTopLevelWindowFlags
DECL|function|frame
DECL|function|frameGeometry
DECL|function|frameGeometry_sys
DECL|function|frameMarginsDp
DECL|function|fromWindow
DECL|function|geometry_sys
DECL|function|getDC
DECL|function|getSizeHints
DECL|function|handleCalculateSize
DECL|function|handleCompositionSettingsChanged
DECL|function|handleGeometryChange
DECL|function|handleGeometryChanging
DECL|function|handleGeometryChangingMessage
DECL|function|handleHidden
DECL|function|handleMoved
DECL|function|handleNonClientHitTest
DECL|function|handleResized
DECL|function|handleWindowStateChange
DECL|function|handleWmPaint
DECL|function|hide_sys
DECL|function|initialize
DECL|function|invalidateSurface
DECL|function|isActive
DECL|function|isEmbedded
DECL|function|isEnabled
DECL|function|isFullScreen_sys
DECL|function|isVisible
DECL|function|lower
DECL|function|mapFromGlobalDp
DECL|function|mapToGlobalDp
DECL|function|normalFrameGeometry
DECL|function|normalGeometryDp
DECL|function|operator <<
DECL|function|operator <<
DECL|function|operator <<
DECL|function|operator <<
DECL|function|positionIncludesFrame
DECL|function|propagateSizeHints
DECL|function|qRegionToWinRegion
DECL|function|qSizeOfRect
DECL|function|qrectFromRECT
DECL|function|raise
DECL|function|registerTouchWindow
DECL|function|releaseDC
DECL|function|requestActivateWindow
DECL|function|setAlertState
DECL|function|setCursor
DECL|function|setCustomMargins
DECL|function|setDropSiteEnabled
DECL|function|setEnabled
DECL|function|setExStyle
DECL|function|setFrameStrutEventsEnabled
DECL|function|setGeometryDp
DECL|function|setGeometry_sys
DECL|function|setKeyboardGrabEnabled
DECL|function|setMask
DECL|function|setMouseGrabEnabled
DECL|function|setOpacity
DECL|function|setParent
DECL|function|setParent_sys
DECL|function|setStyle
DECL|function|setTouchWindowTouchTypeStatic
DECL|function|setVisible
DECL|function|setWindowFlags
DECL|function|setWindowFlags_sys
DECL|function|setWindowIcon
DECL|function|setWindowLayered
DECL|function|setWindowOpacity
DECL|function|setWindowState
DECL|function|setWindowState_sys
DECL|function|setWindowTitle
DECL|function|shouldShowMaximizeButton
DECL|function|show_sys
DECL|function|startSystemResize
DECL|function|stopAlertWindow
DECL|function|surface
DECL|function|testShowWithoutActivating
DECL|function|topLevelOf
DECL|function|transientParentHwnd
DECL|function|updateDropSite
DECL|function|updateGLWindowSettings
DECL|function|updateTransientParent
DECL|function|validSize
DECL|function|windowEvent
DECL|function|windowIsOpenGL
DECL|function|windowPlacementOffset
DECL|function|~QWindowsWindow
DECL|member|desktop
DECL|member|dialog
DECL|member|embedded
DECL|member|exStyle
DECL|member|flags
DECL|member|hasAlpha
DECL|member|parentHandle
DECL|member|popup
DECL|member|style
DECL|member|tool
DECL|member|topLevel
DECL|member|type
DECL|struct|WindowCreationData
DECL|typedef|WindowData
