DECL|function|QWindowsEGLContext
DECL|function|QWindowsEGLStaticContext
DECL|function|chooseConfig
DECL|function|create
DECL|function|createConfigAttributesFromFormat
DECL|function|createContext
DECL|function|createWindowSurface
DECL|function|destroyWindowSurface
DECL|function|doneCurrent
DECL|function|formatFromConfig
DECL|function|getProcAddress
DECL|function|init
DECL|function|init
DECL|function|makeCurrent
DECL|function|reduceConfigAttributes
DECL|function|resolve
DECL|function|resolve
DECL|function|resolveFunc
DECL|function|resolveFunc
DECL|function|swapBuffers
DECL|function|~QWindowsEGLContext
DECL|function|~QWindowsEGLStaticContext
DECL|macro|RESOLVE
DECL|macro|RESOLVE
DECL|member|libEGL
DECL|member|libGLESv2
