DECL|function|QWindowsScreen
DECL|function|QWindowsScreenData
DECL|function|deviceDPI
DECL|function|deviceDPI
DECL|function|deviceSizeMM
DECL|function|findTopLevelAt
DECL|function|grabWindow
DECL|function|monitorEnumCallback
DECL|function|screenOf
DECL|function|screens
DECL|function|windowAt
DECL|function|windowUnderMouse
DECL|typedef|DPI
DECL|typedef|WindowsScreenDataList
