DECL|function|QWindowsGeometryHint
DECL|function|applyToMinMaxInfo
DECL|function|baseWindowOf
DECL|function|destroyIcon
DECL|function|handleOf
DECL|function|mapFromGlobal
DECL|function|mapFromGlobal
DECL|function|mapToGlobal
DECL|function|mapToGlobal
DECL|function|operator
DECL|function|operator
DECL|function|setUserDataOf
DECL|function|userDataOf
DECL|macro|QWINDOWSWINDOW_H
DECL|member|exStyle
DECL|member|frameHeight
DECL|member|frameWidth
DECL|member|frameX
DECL|member|frameY
DECL|member|geometryHint
DECL|member|margins
DECL|member|maximumSize
DECL|member|minimumSize
DECL|member|obtainedGeometry
DECL|member|requestedGeometry
DECL|member|style
DECL|struct|QWindowCreationContext
DECL|struct|QWindowsGeometryHint
DECL|variable|QDebug
DECL|variable|QWindowsEGLStaticContext
DECL|variable|QWindowsOleDropTarget
