DECL|function|QWindowsBackingStore
DECL|function|beginPaint
DECL|function|flush
DECL|function|getDC
DECL|function|paintDevice
DECL|function|resize
DECL|function|scroll
DECL|function|toImage
DECL|function|~QWindowsBackingStore
