DECL|function|moduleHandle
DECL|function|moduleHandle
DECL|macro|QWINDOWSEGLCONTEXT_H
DECL|member|eglBindAPI
DECL|member|eglChooseConfig
DECL|member|eglCreateContext
DECL|member|eglCreatePbufferSurface
DECL|member|eglCreateWindowSurface
DECL|member|eglDestroyContext
DECL|member|eglDestroySurface
DECL|member|eglGetConfigAttrib
DECL|member|eglGetCurrentContext
DECL|member|eglGetCurrentDisplay
DECL|member|eglGetCurrentSurface
DECL|member|eglGetDisplay
DECL|member|eglGetError
DECL|member|eglGetPlatformDisplayEXT
DECL|member|eglGetProcAddress
DECL|member|eglInitialize
DECL|member|eglMakeCurrent
DECL|member|eglSwapBuffers
DECL|member|eglSwapInterval
DECL|member|eglTerminate
DECL|member|glActiveTexture
DECL|member|glAttachShader
DECL|member|glBindAttribLocation
DECL|member|glBindBuffer
DECL|member|glBindFramebuffer
DECL|member|glBindRenderbuffer
DECL|member|glBindTexture
DECL|member|glBlendColor
DECL|member|glBlendEquation
DECL|member|glBlendEquationSeparate
DECL|member|glBlendFunc
DECL|member|glBlendFuncSeparate
DECL|member|glBufferData
DECL|member|glBufferSubData
DECL|member|glCheckFramebufferStatus
DECL|member|glClear
DECL|member|glClearColor
DECL|member|glClearDepthf
DECL|member|glClearStencil
DECL|member|glColorMask
DECL|member|glCompileShader
DECL|member|glCompressedTexImage2D
DECL|member|glCompressedTexSubImage2D
DECL|member|glCopyTexImage2D
DECL|member|glCopyTexSubImage2D
DECL|member|glCreateProgram
DECL|member|glCreateShader
DECL|member|glCullFace
DECL|member|glDeleteBuffers
DECL|member|glDeleteFramebuffers
DECL|member|glDeleteProgram
DECL|member|glDeleteRenderbuffers
DECL|member|glDeleteShader
DECL|member|glDeleteTextures
DECL|member|glDepthFunc
DECL|member|glDepthMask
DECL|member|glDepthRangef
DECL|member|glDetachShader
DECL|member|glDisable
DECL|member|glDisableVertexAttribArray
DECL|member|glDrawArrays
DECL|member|glDrawElements
DECL|member|glEnable
DECL|member|glEnableVertexAttribArray
DECL|member|glFinish
DECL|member|glFlush
DECL|member|glFramebufferRenderbuffer
DECL|member|glFramebufferTexture2D
DECL|member|glFrontFace
DECL|member|glGenBuffers
DECL|member|glGenFramebuffers
DECL|member|glGenRenderbuffers
DECL|member|glGenTextures
DECL|member|glGenerateMipmap
DECL|member|glGetActiveAttrib
DECL|member|glGetActiveUniform
DECL|member|glGetAttachedShaders
DECL|member|glGetAttribLocation
DECL|member|glGetBooleanv
DECL|member|glGetBufferParameteriv
DECL|member|glGetError
DECL|member|glGetFloatv
DECL|member|glGetFramebufferAttachmentParameteriv
DECL|member|glGetIntegerv
DECL|member|glGetProgramInfoLog
DECL|member|glGetProgramiv
DECL|member|glGetRenderbufferParameteriv
DECL|member|glGetShaderInfoLog
DECL|member|glGetShaderPrecisionFormat
DECL|member|glGetShaderSource
DECL|member|glGetShaderiv
DECL|member|glGetString
DECL|member|glGetTexParameterfv
DECL|member|glGetTexParameteriv
DECL|member|glGetUniformLocation
DECL|member|glGetUniformfv
DECL|member|glGetUniformiv
DECL|member|glGetVertexAttribPointerv
DECL|member|glGetVertexAttribfv
DECL|member|glGetVertexAttribiv
DECL|member|glHint
DECL|member|glIsBuffer
DECL|member|glIsEnabled
DECL|member|glIsFramebuffer
DECL|member|glIsProgram
DECL|member|glIsRenderbuffer
DECL|member|glIsShader
DECL|member|glIsTexture
DECL|member|glLineWidth
DECL|member|glLinkProgram
DECL|member|glPixelStorei
DECL|member|glPolygonOffset
DECL|member|glReadPixels
DECL|member|glReleaseShaderCompiler
DECL|member|glRenderbufferStorage
DECL|member|glSampleCoverage
DECL|member|glScissor
DECL|member|glShaderBinary
DECL|member|glShaderSource
DECL|member|glStencilFunc
DECL|member|glStencilFuncSeparate
DECL|member|glStencilMask
DECL|member|glStencilMaskSeparate
DECL|member|glStencilOp
DECL|member|glStencilOpSeparate
DECL|member|glTexImage2D
DECL|member|glTexParameterf
DECL|member|glTexParameterfv
DECL|member|glTexParameteri
DECL|member|glTexParameteriv
DECL|member|glTexSubImage2D
DECL|member|glUniform1f
DECL|member|glUniform1fv
DECL|member|glUniform1i
DECL|member|glUniform1iv
DECL|member|glUniform2f
DECL|member|glUniform2fv
DECL|member|glUniform2i
DECL|member|glUniform2iv
DECL|member|glUniform3f
DECL|member|glUniform3fv
DECL|member|glUniform3i
DECL|member|glUniform3iv
DECL|member|glUniform4f
DECL|member|glUniform4fv
DECL|member|glUniform4i
DECL|member|glUniform4iv
DECL|member|glUniformMatrix2fv
DECL|member|glUniformMatrix3fv
DECL|member|glUniformMatrix4fv
DECL|member|glUseProgram
DECL|member|glValidateProgram
DECL|member|glVertexAttrib1f
DECL|member|glVertexAttrib1fv
DECL|member|glVertexAttrib2f
DECL|member|glVertexAttrib2fv
DECL|member|glVertexAttrib3f
DECL|member|glVertexAttrib3fv
DECL|member|glVertexAttrib4f
DECL|member|glVertexAttrib4fv
DECL|member|glVertexAttribPointer
DECL|member|glViewport
DECL|member|m_lib
DECL|member|m_lib
DECL|member|private
DECL|member|private
DECL|struct|QWindowsLibEGL
DECL|struct|QWindowsLibGLESv2
