DECL|class|FakePointer
DECL|class|ShGetFileInfoFunction
DECL|enumerator|sHIL_EXTRALARGE
DECL|enumerator|sHIL_JUMBO
DECL|function|COLORREFToQColor
DECL|function|QWindowsTheme
DECL|function|ShGetFileInfoFunction
DECL|function|booleanSystemParametersInfo
DECL|function|clearFonts
DECL|function|clearPalettes
DECL|function|create
DECL|function|createPlatformDialogHelper
DECL|function|dWordSystemParametersInfo
DECL|function|dirIconPixmapCacheKey
DECL|function|fileIconPixmap
DECL|function|getSysColor
DECL|function|iconThemeSearchPaths
DECL|function|loadIconFromShell32
DECL|function|menuBarPalette
DECL|function|menuPalette
DECL|function|mixColors
DECL|function|operator ()
DECL|function|operator *
DECL|function|operator <<
DECL|function|operator delete
DECL|function|pixmapFromShellImageList
DECL|function|refreshFonts
DECL|function|refreshPalettes
DECL|function|shGetFileInfoBackground
DECL|function|standardPalette
DECL|function|standardPixmap
DECL|function|styleNames
DECL|function|systemPalette
DECL|function|themeHint
DECL|function|toolTipPalette
DECL|function|uiEffects
DECL|function|usePlatformNativeDialog
DECL|function|windowsThemeChanged
DECL|function|~QWindowsTheme
DECL|macro|USE_IIMAGELIST
DECL|macro|_WIN32_WINNT
DECL|macro|_WIN32_WINNT
DECL|member|m_attributes
DECL|member|m_fileName
DECL|member|m_flags
DECL|member|m_info
DECL|member|m_instance
DECL|member|m_result
DECL|member|name
