DECL|function|QWindowsMouseHandler
DECL|function|compressMouseMove
DECL|function|translateMouseEvent
DECL|function|translateMouseWheelEvent
DECL|function|translateTouchEvent
DECL|macro|PEEKMESSAGE_IS_BROKEN
