DECL|enumerator|QWindowsGLAccumBuffer
DECL|enumerator|QWindowsGLDirectRendering
DECL|enumerator|QWindowsGLOverlay
DECL|enumerator|QWindowsGLRenderToPixmap
DECL|enum|QWindowsGLFormatFlags
DECL|function|QOpenGLContextData
DECL|function|QOpenGLContextData
DECL|function|QWindowsOpenGLAdditionalFormat
DECL|function|moduleHandle
DECL|function|moduleIsNotOpengl32
DECL|macro|QWINDOWSGLCONTEXT_H
DECL|member|formatFlags
DECL|member|glBindTexture
DECL|member|glBlendFunc
DECL|member|glClear
DECL|member|glClearColor
DECL|member|glClearDepth
DECL|member|glClearStencil
DECL|member|glColorMask
DECL|member|glCopyTexImage2D
DECL|member|glCopyTexSubImage2D
DECL|member|glCullFace
DECL|member|glDeleteTextures
DECL|member|glDepthFunc
DECL|member|glDepthMask
DECL|member|glDepthRange
DECL|member|glDisable
DECL|member|glDrawArrays
DECL|member|glDrawElements
DECL|member|glEnable
DECL|member|glFinish
DECL|member|glFlush
DECL|member|glFrontFace
DECL|member|glGenTextures
DECL|member|glGetBooleanv
DECL|member|glGetError
DECL|member|glGetFloatv
DECL|member|glGetIntegerv
DECL|member|glGetString
DECL|member|glGetTexParameterfv
DECL|member|glGetTexParameteriv
DECL|member|glHint
DECL|member|glIsEnabled
DECL|member|glIsTexture
DECL|member|glLineWidth
DECL|member|glPixelStorei
DECL|member|glPolygonOffset
DECL|member|glReadPixels
DECL|member|glScissor
DECL|member|glStencilFunc
DECL|member|glStencilMask
DECL|member|glStencilOp
DECL|member|glTexImage2D
DECL|member|glTexParameterf
DECL|member|glTexParameterfv
DECL|member|glTexParameteri
DECL|member|glTexParameteriv
DECL|member|glTexSubImage2D
DECL|member|glViewport
DECL|member|hdc
DECL|member|hwnd
DECL|member|m_lib
DECL|member|m_nonOpengl32
DECL|member|options
DECL|member|pixmapDepth
DECL|member|private
DECL|member|profile
DECL|member|renderingContext
DECL|member|version
DECL|member|wglCreateContext
DECL|member|wglDeleteContext
DECL|member|wglGetCurrentContext
DECL|member|wglGetCurrentDC
DECL|member|wglGetProcAddress
DECL|member|wglMakeCurrent
DECL|member|wglSetPixelFormat
DECL|member|wglShareLists
DECL|member|wglSwapBuffers
DECL|struct|QOpenGLContextData
DECL|struct|QWindowsOpenGLAdditionalFormat
DECL|struct|QWindowsOpenGLContextFormat
DECL|struct|QWindowsOpengl32DLL
DECL|variable|QDebug
DECL|variable|QOpenGLStaticContext
