DECL|enumerator|JapaneseCsbBit
DECL|enumerator|KoreanCsbBit
DECL|enumerator|SimplifiedChineseCsbBit
DECL|enumerator|TraditionalChineseCsbBit
DECL|function|LOGFONT_to_QFont
DECL|function|QWindowsFontDatabase
DECL|function|QWindowsFontEngineData
DECL|function|addApplicationFont
DECL|function|addFontToDatabase
DECL|function|createEngine
DECL|function|defaultFont
DECL|function|defaultFonts
DECL|function|fallbacksForFamily
DECL|function|fontDir
DECL|function|fontEngine
DECL|function|fontEngine
DECL|function|initDirectWrite
DECL|function|operator <<
DECL|function|populate
DECL|function|populateFontDatabase
DECL|function|releaseHandle
DECL|function|scriptRequiresOpenType
DECL|function|storeFont
DECL|function|systemFont
DECL|function|verticalDPI
DECL|function|weightFromInteger
DECL|function|writingSystemFromScript
DECL|function|writingSystemsFromTrueTypeBits
DECL|function|~QWindowsFontDatabase
DECL|function|~QWindowsFontEngineData
DECL|variable|ch_CN_tryFonts
DECL|variable|ch_TW_tryFonts
DECL|variable|jp_tryFonts
DECL|variable|kr_tryFonts
DECL|variable|other_tryFonts
DECL|variable|requiredUnicodeBits
DECL|variable|tryFonts
