DECL|function|addFontToDatabase
DECL|function|createFontFile
DECL|function|defaultFont
DECL|function|fallbacksForFamily
DECL|function|fontDir
DECL|function|fontEngine
DECL|function|fontEngine
DECL|function|getFntTable
DECL|function|populate
DECL|function|populateFontDatabase
DECL|function|storeFont
DECL|function|storeFontSub
DECL|function|weightFromInteger
DECL|function|writingSystemFromCharSet
