DECL|function|QWindowsClipboard
DECL|function|clear
DECL|function|clipboardViewerWndProc
DECL|function|isProcessBeingDebugged
DECL|function|mimeData
DECL|function|operator <<
DECL|function|ownsClipboard
DECL|function|ownsMode
DECL|function|propagateClipboardMessage
DECL|function|qClipboardViewerWndProc
DECL|function|registerViewer
DECL|function|releaseDataObject
DECL|function|releaseIData
DECL|function|retrieveDataObject
DECL|function|setMimeData
DECL|function|supportsMode
DECL|function|unregisterViewer
DECL|function|~QWindowsClipboard
DECL|member|m_instance
DECL|variable|formatTextHtmlC
DECL|variable|formatTextPlainC
