DECL|enumerator|AltAny
DECL|enumerator|AltLeft
DECL|enumerator|AltRight
DECL|enumerator|CapsLock
DECL|enumerator|ControlAny
DECL|enumerator|ControlLeft
DECL|enumerator|ControlRight
DECL|enumerator|ExtendedKey
DECL|enumerator|LockAny
DECL|enumerator|MetaAny
DECL|enumerator|MetaLeft
DECL|enumerator|MetaRight
DECL|enumerator|NumLock
DECL|enumerator|ScrollLock
DECL|enumerator|ShiftAny
DECL|enumerator|ShiftLeft
DECL|enumerator|ShiftRight
DECL|enum|WindowsNativeModifiers
DECL|macro|QWINDOWSKEYMAPPER_H
DECL|member|NumQtKeys
DECL|member|deadkeys
DECL|member|dirty
DECL|member|exists
DECL|member|qtKey
DECL|struct|KeyboardLayoutItem
DECL|variable|QKeyEvent
DECL|variable|QWindow
