DECL|class|SubQStringMatcher
DECL|class|tst_QStringMatcher
DECL|function|assignOperator
DECL|function|caseSensitivity
DECL|function|indexIn
DECL|function|indexIn_data
DECL|function|qstringmatcher
DECL|function|setCaseSensitivity
DECL|function|setCaseSensitivity_data
