DECL|class|tst_QTextList
DECL|function|add
DECL|function|autoNumbering
DECL|function|autoNumberingPrefixAndSuffix
DECL|function|autoNumberingPrefixAndSuffixHtmlExportImport
DECL|function|autoNumberingPrefixAndSuffixRTL
DECL|function|autoNumberingRTL
DECL|function|blockUpdate
DECL|function|cleanup
DECL|function|cursorNavigation
DECL|function|defaultIndent
DECL|function|ensureItemOrder
DECL|function|formatChange
DECL|function|formatReferenceChange
DECL|function|init
DECL|function|item
DECL|function|numbering
DECL|function|numbering_data
DECL|function|partialRemoval
DECL|function|romanNumbering
DECL|function|romanNumberingLimit
DECL|function|tst_QTextList
DECL|member|cursor
DECL|member|doc
DECL|member|layout
