DECL|class|QFactoryLoaderPrivate
DECL|function|QFactoryLoader
DECL|function|QFactoryLoaderPrivate
DECL|function|iidKeyLiteral
DECL|function|indexOf
DECL|function|instance
DECL|function|keyMap
DECL|function|keysKeyLiteral
DECL|function|library
DECL|function|metaData
DECL|function|metaDataKeyLiteral
DECL|function|refreshAll
DECL|function|update
DECL|function|versionKeyLiteral
DECL|function|~QFactoryLoader
DECL|function|~QFactoryLoaderPrivate
DECL|member|cs
DECL|member|iid
DECL|member|keyMap
DECL|member|libraryList
DECL|member|loadedPaths
DECL|member|mutex
DECL|member|suffix
