DECL|class|QFactoryLoaderPrivate
DECL|function|QFactoryLoader
DECL|function|QFactoryLoaderPrivate
DECL|function|instance
DECL|function|instance
DECL|function|keys
DECL|function|library
DECL|function|metaData
DECL|function|refreshAll
DECL|function|update
DECL|function|~QFactoryLoader
DECL|function|~QFactoryLoaderPrivate
DECL|member|cs
DECL|member|iid
DECL|member|keyList
DECL|member|keyMap
DECL|member|libraryList
DECL|member|loadedPaths
DECL|member|mutex
DECL|member|suffix
