DECL|function|QLibrary
DECL|function|QLibrary
DECL|function|QLibrary
DECL|function|QLibrary
DECL|function|QLibraryPrivate
DECL|function|errorString
DECL|function|fileName
DECL|function|findOrCreate
DECL|function|isLibrary
DECL|function|isLoaded
DECL|function|isPlugin
DECL|function|libraryMap
DECL|function|load
DECL|function|load
DECL|function|loadHints
DECL|function|loadPlugin
DECL|function|qt_debug_component
DECL|function|qt_find_pattern
DECL|function|qt_get_verificationdata
DECL|function|qt_parse_pattern
DECL|function|qt_token_info
DECL|function|qt_tokenize
DECL|function|qt_try_versioninfo
DECL|function|qt_unix_query
DECL|function|release
DECL|function|resolve
DECL|function|resolve
DECL|function|resolve
DECL|function|resolve
DECL|function|resolve
DECL|function|setFileName
DECL|function|setFileNameAndVersion
DECL|function|setFileNameAndVersion
DECL|function|setLoadHints
DECL|function|unload
DECL|function|unload
DECL|function|~QLibrary
DECL|function|~QLibraryPrivate
DECL|macro|QLIBRARY_AS_DEBUG
DECL|macro|QT_NO_DEBUG_PLUGIN_CHECK
DECL|macro|QT_USE_MS_STD_EXCEPTION
DECL|member|field_count
DECL|member|fields
DECL|member|lengths
DECL|member|libraryMap
DECL|member|loadedLibs
DECL|member|results
DECL|struct|LibraryData
DECL|struct|qt_token_info
DECL|typedef|LibraryMap
DECL|typedef|QtPluginQueryVerificationDataFunction
DECL|typedef|QtPluginQueryVerificationDataFunction
