DECL|function|QPluginLoader
DECL|function|QPluginLoader
DECL|function|errorString
DECL|function|fileName
DECL|function|instance
DECL|function|isLoaded
DECL|function|load
DECL|function|loadHints
DECL|function|locatePlugin
DECL|function|metaData
DECL|function|qRegisterStaticPluginFunction
DECL|function|setFileName
DECL|function|setLoadHints
DECL|function|staticInstances
DECL|function|staticPlugins
DECL|function|unload
DECL|function|~QPluginLoader
DECL|typedef|StaticPluginList
