DECL|function|QPluginLoader
DECL|function|QPluginLoader
DECL|function|errorString
DECL|function|fileName
DECL|function|instance
DECL|function|isLoaded
DECL|function|load
DECL|function|loadHints
DECL|function|qRegisterStaticPluginInstanceFunction
DECL|function|setFileName
DECL|function|setLoadHints
DECL|function|staticInstances
DECL|function|unload
DECL|function|~QPluginLoader
DECL|typedef|StaticInstanceFunctionList
