DECL|class|GlobalViewGestures
DECL|class|GraphicsItemGestures
DECL|class|GraphicsView
DECL|class|MainWindow
DECL|class|StandardGestures
DECL|function|GlobalViewGestures
DECL|function|GraphicsItemGestures
DECL|function|GraphicsView
DECL|function|MainWindow
DECL|function|StandardGestures
DECL|function|main
DECL|function|setDirectory
DECL|function|viewportEvent
DECL|member|globalViewGestures
DECL|member|graphicsItemGestures
DECL|member|scene
DECL|member|scene
DECL|member|scene
DECL|member|standardGestures
DECL|member|tabWidget
DECL|member|view
DECL|member|view
DECL|member|view
