DECL|class|tst_QGroupBox
DECL|function|childrenAreDisabled
DECL|function|clickTimestampSlot
DECL|function|clicked
DECL|function|clicked_data
DECL|function|enabledPropagation
DECL|function|init
DECL|function|propagateFocus
DECL|function|setCheckable
DECL|function|setCheckable_data
DECL|function|setChecked
DECL|function|setChecked_data
DECL|function|setTitle
DECL|function|setTitle_data
DECL|function|sizeHint
DECL|function|toggleTimestampSlot
DECL|function|toggled
DECL|function|toggledHelperSlot
DECL|function|toggledVsClicked
DECL|function|tst_QGroupBox
DECL|function|~tst_QGroupBox
DECL|member|checked
DECL|member|clickTimeStamp
DECL|member|timeStamp
DECL|member|toggleTimeStamp
