DECL|class|MouseEventTestWidget
DECL|class|tst_QGroupBox
DECL|function|childrenAreDisabled
DECL|function|clickTimestampSlot
DECL|function|clicked
DECL|function|clicked_data
DECL|function|enabledChildPropagation
DECL|function|enabledPropagation
DECL|function|init
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|propagateFocus
DECL|function|reset
DECL|function|sendMouseMoveEvent
DECL|function|setCheckable
DECL|function|setCheckable_data
DECL|function|setChecked
DECL|function|setChecked_data
DECL|function|setTitle
DECL|function|setTitle_data
DECL|function|sizeHint
DECL|function|task_QTBUG_15519_propagateMouseEvents
DECL|function|task_QTBUG_19170_ignoreMouseReleseEvent
DECL|function|toggleTimestampSlot
DECL|function|toggled
DECL|function|toggledHelperSlot
DECL|function|toggledVsClicked
DECL|function|tst_QGroupBox
DECL|function|~tst_QGroupBox
DECL|member|checked
DECL|member|clickTimeStamp
DECL|member|mouseMoved
DECL|member|mousePressed
DECL|member|mouseReleased
DECL|member|timeStamp
DECL|member|toggleTimeStamp
