DECL|function|KeyboardModifiersToString
DECL|function|QDragManager
DECL|function|QDropData
DECL|function|QInternalMimeData
DECL|function|canReadData
DECL|function|currentTarget
DECL|function|defaultAction
DECL|function|dragActionsToString
DECL|function|dragCursor
DECL|function|formats
DECL|function|formatsHelper
DECL|function|hasCustomDragCursors
DECL|function|hasFormat
DECL|function|hasFormatHelper
DECL|function|imageReadMimeFormats
DECL|function|imageWriteMimeFormats
DECL|function|renderDataHelper
DECL|function|retrieveData
DECL|function|self
DECL|function|setCurrentTarget
DECL|function|~QDragManager
DECL|function|~QDropData
DECL|function|~QInternalMimeData
DECL|member|instance
