DECL|class|CustomLayoutStyle
DECL|class|tst_QBoxLayout
DECL|function|CustomLayoutStyle
DECL|function|cleanup
DECL|function|cleanupTestCase
DECL|function|init
DECL|function|initTestCase
DECL|function|insertSpacerItem
DECL|function|pixelMetric
DECL|function|setGeometry
DECL|function|setStyleShouldChangeSpacing
DECL|function|sizeConstraints
DECL|function|sizeHint
DECL|function|taskQTBUG_27420_takeAtShouldUnparentLayout
DECL|function|taskQTBUG_7103_minMaxWidthNotRespected
DECL|function|tst_QBoxLayout
DECL|function|~tst_QBoxLayout
DECL|member|hspacing
DECL|member|vspacing
