DECL|class|CustomLayoutStyle
DECL|class|LayoutItem
DECL|class|tst_QBoxLayout
DECL|function|CustomLayoutStyle
DECL|function|Descr
DECL|function|LayoutItem
DECL|function|cleanup
DECL|function|expandingDirections
DECL|function|geometry
DECL|function|insertLayout
DECL|function|insertSpacerItem
DECL|function|isEmpty
DECL|function|maximumSize
DECL|function|minimumSize
DECL|function|pixelMetric
DECL|function|replaceWidget
DECL|function|setFrameless
DECL|function|setGeometry
DECL|function|setGeometry
DECL|function|setStyleShouldChangeSpacing
DECL|function|sizeConstraints
DECL|function|sizeHint
DECL|function|sizeHint
DECL|function|taskQTBUG_27420_takeAtShouldUnparentLayout
DECL|function|taskQTBUG_40609_addingLayoutToItself
DECL|function|taskQTBUG_40609_addingWidgetToItsOwnLayout
DECL|function|taskQTBUG_7103_minMaxWidthNotRespected
DECL|function|testLayoutEngine
DECL|function|testLayoutEngine_data
DECL|member|empty
DECL|member|expanding
DECL|member|hspacing
DECL|member|m_descr
DECL|member|m_pos
DECL|member|m_size
DECL|member|maximumSize
DECL|member|minimumSize
DECL|member|sizeHint
DECL|member|stretch
DECL|member|vspacing
DECL|struct|Descr
DECL|typedef|DescrList
DECL|typedef|PosList
DECL|typedef|SizeList
DECL|variable|DescrList
