DECL|class|MainWindow
DECL|class|MyDockWidget
DECL|class|MyWidget
DECL|class|tst_QMainWindow
DECL|enumerator|AddMode
DECL|enumerator|SplitMode
DECL|enumerator|TabMode
DECL|enum|Mode
DECL|function|AddDockWidget
DECL|function|AddDockWidget
DECL|function|AddDockWidget
DECL|function|AddDockWidget
DECL|function|MoveSeparator
DECL|function|MoveSeparator
DECL|function|MoveSeparator
DECL|function|MyDockWidget
DECL|function|MyWidget
DECL|function|QTBUG2774_stylechange
DECL|function|addDockWidget
DECL|function|addToolBar
DECL|function|addToolBarBreak
DECL|function|addToolbarAfterShow
DECL|function|apply
DECL|function|apply
DECL|function|centralWidget
DECL|function|centralWidgetSize
DECL|function|constructor
DECL|function|corner
DECL|function|createPopupMenu
DECL|function|dockWidgetArea
DECL|function|dockWidgetGeometries
DECL|function|dockWidgetSize
DECL|function|findWidgetRecursively
DECL|function|getSetCheck
DECL|function|hideBeforeLayout
DECL|function|iconSize
DECL|function|iconSizeChanged
DECL|function|insertToolBar
DECL|function|insertToolBarBreak
DECL|function|isSeparator
DECL|function|menuBar
DECL|function|removeDockWidget
DECL|function|removeToolBar
DECL|function|restoreState
DECL|function|restoreStateFromPreviousVersion
DECL|function|saveRestore
DECL|function|saveRestore_data
DECL|function|saveState
DECL|function|setCentralWidget
DECL|function|setCorner
DECL|function|setCursor
DECL|function|setIconSize
DECL|function|setMenuBar
DECL|function|setStatusBar
DECL|function|setToolButtonStyle
DECL|function|sizeHint
DECL|function|splitDockWidget
DECL|function|statusBar
DECL|function|toggleUnifiedTitleAndToolBarOnMac
DECL|function|toolBarArea
DECL|function|toolButtonStyle
DECL|function|toolButtonStyleChanged
DECL|function|tst_QMainWindow
DECL|macro|COMPARE_DOCK_WIDGET_GEOS
DECL|member|a
DECL|member|area
DECL|member|delta
DECL|member|mode
DECL|member|name
DECL|member|name
DECL|member|o
DECL|member|other
DECL|struct|AddDockWidget
DECL|struct|MoveSeparator
DECL|typedef|AddList
DECL|typedef|MoveList
DECL|variable|restoreData41
DECL|variable|restoreData42
DECL|variable|restoreData43
