DECL|function|q_frameBuffer
DECL|function|q_initDD
DECL|function|q_linestep
DECL|function|q_lock
DECL|function|q_screenDepth
DECL|function|q_screenHeight
DECL|function|q_screenWidth
DECL|function|q_unlock
DECL|variable|bitCount
DECL|variable|buffer
DECL|variable|ddsCaps
DECL|variable|ddsSurfaceDesc
DECL|variable|g_pDD
DECL|variable|g_pDDSSurface
DECL|variable|height
DECL|variable|initialized
DECL|variable|locked
DECL|variable|pitch
DECL|variable|width
DECL|variable|windowId
