DECL|function|cleanup
DECL|function|query
DECL|function|resolveLibrary
DECL|struct|QDnsLookupStateDeleter
DECL|typedef|dn_expand_proto
DECL|typedef|res_nclose_proto
DECL|typedef|res_ninit_proto
DECL|typedef|res_nquery_proto
DECL|variable|local_dn_expand
DECL|variable|local_res_nclose
DECL|variable|local_res_ninit
DECL|variable|local_res_nquery
