DECL|function|QHostInfo
DECL|function|QHostInfo
DECL|function|QHostInfoCache
DECL|function|QHostInfoLookupManager
DECL|function|QHostInfoRunnable
DECL|function|abortHostLookup
DECL|function|abortLookup
DECL|function|addresses
DECL|function|clear
DECL|function|clear
DECL|function|error
DECL|function|errorString
DECL|function|fromName
DECL|function|fromName
DECL|function|fromName
DECL|function|get
DECL|function|globalInstance
DECL|function|hostName
DECL|function|isEnabled
DECL|function|lookupFinished
DECL|function|lookupHost
DECL|function|lookupId
DECL|function|operator =
DECL|function|put
DECL|function|qt_qhostinfo_clear_cache
DECL|function|qt_qhostinfo_enable_cache
DECL|function|qt_qhostinfo_lookup
DECL|function|run
DECL|function|scheduleLookup
DECL|function|setAddresses
DECL|function|setEnabled
DECL|function|setError
DECL|function|setErrorString
DECL|function|setHostName
DECL|function|setLookupId
DECL|function|wasAborted
DECL|function|work
DECL|function|~QHostInfo
DECL|function|~QHostInfoLookupManager
DECL|variable|theIdCounter
