DECL|function|fromName
DECL|function|localHostName
DECL|function|resolveLibrary
DECL|macro|NI_MAXHOST
DECL|macro|QT_SOCKLEN_T
DECL|member|ai_addr
DECL|member|ai_addrlen
DECL|member|ai_canonname
DECL|member|ai_family
DECL|member|ai_flags
DECL|member|ai_next
DECL|member|ai_protocol
DECL|member|ai_socktype
DECL|struct|qt_addrinfo
DECL|typedef|freeaddrinfoProto
DECL|typedef|getaddrinfoProto
DECL|typedef|getnameinfoProto
DECL|variable|local_freeaddrinfo
DECL|variable|local_getaddrinfo
DECL|variable|local_getnameinfo
DECL|variable|qPrivCEMutex
