DECL|function|addressFromSockaddr
DECL|function|convertFlags
DECL|function|createInterfaces
DECL|function|findInterface
DECL|function|interfaceListing
DECL|function|interfaceListing
DECL|function|interfaceNames
DECL|function|scan
DECL|macro|IFF_RUNNING
DECL|macro|IP_MULTICAST
DECL|macro|QT_NO_GETIFADDRS
DECL|macro|QT_NO_IPV6IFNAME
DECL|macro|SIOCGIFBRDADDR
