DECL|function|interfaceFromProfile
DECL|function|interfaceIndexFromName
DECL|function|interfaceListing
DECL|function|interfaceNameFromIndex
DECL|function|localDomainName
DECL|function|scan
DECL|member|adapterId
DECL|member|address
DECL|member|prefixLength
DECL|struct|HostNameInfo
