DECL|class|QUrlInfoPrivate
DECL|function|QUrlInfo
DECL|function|QUrlInfo
DECL|function|QUrlInfo
DECL|function|QUrlInfo
DECL|function|QUrlInfoPrivate
DECL|function|equal
DECL|function|greaterThan
DECL|function|group
DECL|function|isDir
DECL|function|isExecutable
DECL|function|isFile
DECL|function|isReadable
DECL|function|isSymLink
DECL|function|isValid
DECL|function|isWritable
DECL|function|lastModified
DECL|function|lastRead
DECL|function|lessThan
DECL|function|name
DECL|function|operator =
DECL|function|operator ==
DECL|function|owner
DECL|function|permissions
DECL|function|setDir
DECL|function|setFile
DECL|function|setGroup
DECL|function|setLastModified
DECL|function|setLastRead
DECL|function|setName
DECL|function|setOwner
DECL|function|setPermissions
DECL|function|setReadable
DECL|function|setSize
DECL|function|setSymLink
DECL|function|setWritable
DECL|function|size
DECL|function|~QUrlInfo
DECL|member|group
DECL|member|isDir
DECL|member|isExecutable
DECL|member|isFile
DECL|member|isReadable
DECL|member|isSymLink
DECL|member|isWritable
DECL|member|lastModified
DECL|member|lastRead
DECL|member|name
DECL|member|owner
DECL|member|permissions
DECL|member|size
