DECL|class|tst_QAtomicIntegerXX
DECL|enumerator|TypeIsSigned
DECL|enumerator|TypeIsUnsigned
DECL|function|addData
DECL|function|assign
DECL|function|assign_data
DECL|function|booleanHelper
DECL|function|constructor
DECL|function|constructor_data
DECL|function|copy
DECL|function|copy_data
DECL|function|fetchAndAdd
DECL|function|fetchAndAdd_data
DECL|function|fetchAndStore
DECL|function|fetchAndStore_data
DECL|function|initTestCase
DECL|function|loadAcquireStoreRelease
DECL|function|loadAcquireStoreRelease_data
DECL|function|refDeref
DECL|function|refDeref_data
DECL|function|static_checks
DECL|function|testAndSet
DECL|function|testAndSet_data
DECL|macro|QATOMIC_TEST_NOT_SUPPORTED
DECL|macro|QATOMIC_TYPE_SUPPORTED
DECL|macro|QATOMIC_TYPE_SUPPORTED
DECL|macro|QATOMIC_TYPE_SUPPORTED2
DECL|macro|TEST_TYPE
DECL|macro|TEST_TYPE
DECL|macro|TYPE_SUPPORTED_char
DECL|macro|TYPE_SUPPORTED_char16_t
DECL|macro|TYPE_SUPPORTED_char32_t
DECL|macro|TYPE_SUPPORTED_int
DECL|macro|TYPE_SUPPORTED_long
DECL|macro|TYPE_SUPPORTED_qlonglong
DECL|macro|TYPE_SUPPORTED_qptrdiff
DECL|macro|TYPE_SUPPORTED_quintptr
DECL|macro|TYPE_SUPPORTED_qulonglong
DECL|macro|TYPE_SUPPORTED_schar
DECL|macro|TYPE_SUPPORTED_short
DECL|macro|TYPE_SUPPORTED_uchar
DECL|macro|TYPE_SUPPORTED_uint
DECL|macro|TYPE_SUPPORTED_ulong
DECL|macro|TYPE_SUPPORTED_ushort
DECL|macro|TYPE_SUPPORTED_wchar_t
DECL|macro|TYPE_SUPPORTED_wchar_t
DECL|member|type
DECL|struct|LargeIntTemplate
DECL|struct|LargeIntTemplate
DECL|struct|TypeInStruct
DECL|typedef|LargeInt
DECL|typedef|T
DECL|typedef|Type
DECL|typedef|Type
DECL|typedef|Type
DECL|typedef|schar
