DECL|enumerator|GraphemeBreakCR
DECL|enumerator|GraphemeBreakControl
DECL|enumerator|GraphemeBreakExtend
DECL|enumerator|GraphemeBreakL
DECL|enumerator|GraphemeBreakLF
DECL|enumerator|GraphemeBreakLV
DECL|enumerator|GraphemeBreakLVT
DECL|enumerator|GraphemeBreakOther
DECL|enumerator|GraphemeBreakT
DECL|enumerator|GraphemeBreakV
DECL|enumerator|GraphemeBreak_Unassigned
DECL|enumerator|Joining_Causing
DECL|enumerator|Joining_Dual
DECL|enumerator|Joining_Left
DECL|enumerator|Joining_None
DECL|enumerator|Joining_Right
DECL|enumerator|Joining_Transparent
DECL|enumerator|Joining_Unassigned
DECL|enumerator|LineBreak_AL
DECL|enumerator|LineBreak_B2
DECL|enumerator|LineBreak_BA
DECL|enumerator|LineBreak_BB
DECL|enumerator|LineBreak_BK
DECL|enumerator|LineBreak_CL
DECL|enumerator|LineBreak_CM
DECL|enumerator|LineBreak_CR
DECL|enumerator|LineBreak_EX
DECL|enumerator|LineBreak_GL
DECL|enumerator|LineBreak_H2
DECL|enumerator|LineBreak_H3
DECL|enumerator|LineBreak_HY
DECL|enumerator|LineBreak_ID
DECL|enumerator|LineBreak_IN
DECL|enumerator|LineBreak_IS
DECL|enumerator|LineBreak_JL
DECL|enumerator|LineBreak_JT
DECL|enumerator|LineBreak_JV
DECL|enumerator|LineBreak_LF
DECL|enumerator|LineBreak_NS
DECL|enumerator|LineBreak_NU
DECL|enumerator|LineBreak_OP
DECL|enumerator|LineBreak_PO
DECL|enumerator|LineBreak_PR
DECL|enumerator|LineBreak_QU
DECL|enumerator|LineBreak_SA
DECL|enumerator|LineBreak_SG
DECL|enumerator|LineBreak_SP
DECL|enumerator|LineBreak_SY
DECL|enumerator|LineBreak_Unassigned
DECL|enumerator|LineBreak_WJ
DECL|enumerator|LineBreak_ZW
DECL|enumerator|SentenceBreakATerm
DECL|enumerator|SentenceBreakClose
DECL|enumerator|SentenceBreakFormat
DECL|enumerator|SentenceBreakLower
DECL|enumerator|SentenceBreakNumeric
DECL|enumerator|SentenceBreakOLetter
DECL|enumerator|SentenceBreakOther
DECL|enumerator|SentenceBreakSTerm
DECL|enumerator|SentenceBreakSep
DECL|enumerator|SentenceBreakSp
DECL|enumerator|SentenceBreakUpper
DECL|enumerator|SentenceBreak_Unassigned
DECL|enumerator|UD_BidiCategory
DECL|enumerator|UD_Category
DECL|enumerator|UD_CombiningClass
DECL|enumerator|UD_Comment
DECL|enumerator|UD_DecimalDigitValue
DECL|enumerator|UD_Decomposition
DECL|enumerator|UD_DigitValue
DECL|enumerator|UD_LowerCase
DECL|enumerator|UD_Mirrored
DECL|enumerator|UD_Name
DECL|enumerator|UD_NumericValue
DECL|enumerator|UD_OldName
DECL|enumerator|UD_TitleCase
DECL|enumerator|UD_UpperCase
DECL|enumerator|UD_Value
DECL|enumerator|WordBreakALetter
DECL|enumerator|WordBreakExtendNumLet
DECL|enumerator|WordBreakFormat
DECL|enumerator|WordBreakKatakana
DECL|enumerator|WordBreakMidLetter
DECL|enumerator|WordBreakMidNum
DECL|enumerator|WordBreakNumeric
DECL|enumerator|WordBreakOther
DECL|enumerator|WordBreak_Unassigned
DECL|enum|GraphemeBreak
DECL|enum|Joining
DECL|enum|LineBreakClass
DECL|enum|SentenceBreak
DECL|enum|UniDataFields
DECL|enum|WordBreak
DECL|function|DecompositionBlock
DECL|function|PropertyBlock
DECL|function|UnicodeData
DECL|function|appendToSpecialCaseMap
DECL|function|computeUniqueProperties
DECL|function|createCasingInfo
DECL|function|createCompositionInfo
DECL|function|createLigatureInfo
DECL|function|createNormalizationCorrections
DECL|function|createPropertyInfo
DECL|function|createScriptEnumDeclaration
DECL|function|createScriptTableDeclaration
DECL|function|initAgeMap
DECL|function|initCategoryMap
DECL|function|initDecompositionMap
DECL|function|initDirectionMap
DECL|function|initGraphemeBreak
DECL|function|initJoiningMap
DECL|function|initLineBreak
DECL|function|initSentenceBreak
DECL|function|initWordBreak
DECL|function|main
DECL|function|operator <
DECL|function|operator ==
DECL|function|operator ==
DECL|function|operator ==
DECL|function|readArabicShaping
DECL|function|readBidiMirroring
DECL|function|readCaseFolding
DECL|function|readDerivedAge
DECL|function|readDerivedNormalizationProps
DECL|function|readGraphemeBreak
DECL|function|readLineBreak
DECL|function|readScripts
DECL|function|readSentenceBreak
DECL|function|readSpecialCasing
DECL|function|readUnicodeData
DECL|function|readWordBreak
DECL|macro|DATA_VERSION_S
DECL|macro|DATA_VERSION_STR
DECL|macro|LAST_CODEPOINT
DECL|macro|LAST_CODEPOINT_STR
DECL|member|age
DECL|member|block
DECL|member|caseFoldDiff
DECL|member|caseFoldSpecial
DECL|member|category
DECL|member|codepoint
DECL|member|combiningClass
DECL|member|decomposition
DECL|member|decompositionPositions
DECL|member|decompositionType
DECL|member|digitValue
DECL|member|direction
DECL|member|excludedComposition
DECL|member|graphemeBreak
DECL|member|index
DECL|member|index
DECL|member|joining
DECL|member|ligature
DECL|member|line_break_class
DECL|member|lowerCaseDiff
DECL|member|lowerCaseSpecial
DECL|member|mapped
DECL|member|mirrorDiff
DECL|member|mirroredChar
DECL|member|p
DECL|member|properties
DECL|member|propertyIndex
DECL|member|sentenceBreak
DECL|member|specialFolding
DECL|member|titleCaseDiff
DECL|member|titleCaseSpecial
DECL|member|u1
DECL|member|u2
DECL|member|upperCaseDiff
DECL|member|upperCaseSpecial
DECL|member|vector
DECL|member|version
DECL|member|wordBreak
DECL|struct|DecompositionBlock
DECL|struct|ExtraBlock
DECL|struct|Ligature
DECL|struct|NormalizationCorrection
DECL|struct|PropertyBlock
DECL|struct|PropertyFlags
DECL|struct|UnicodeData
DECL|variable|SizeOfPropertiesStruct
DECL|variable|age_map
DECL|variable|categoryMap
DECL|variable|combiningClassUsage
DECL|variable|decompositionLength
DECL|variable|decompositionMap
DECL|variable|directionMap
DECL|variable|extraBlockList
DECL|variable|grapheme_break_map
DECL|variable|grapheme_break_string
DECL|variable|highestComposedCharacter
DECL|variable|highestLigature
DECL|variable|joining_map
DECL|variable|ligatureHashes
DECL|variable|lineBreakClass
DECL|variable|line_break_map
DECL|variable|maxCaseFoldDiff
DECL|variable|maxLowerCaseDiff
DECL|variable|maxMirroredDiff
DECL|variable|maxTitleCaseDiff
DECL|variable|maxUpperCaseDiff
DECL|variable|methods
DECL|variable|numLigatures
DECL|variable|property_string
DECL|variable|scriptAssignment
DECL|variable|scriptHash
DECL|variable|scriptNames
DECL|variable|scriptSentinel
DECL|variable|sentence_break_map
DECL|variable|sentence_break_string
DECL|variable|specialCaseMap
DECL|variable|specialCaseMaxLen
DECL|variable|unicodeData
DECL|variable|uniqueProperties
DECL|variable|word_break_map
DECL|variable|word_break_string
