DECL|class|QMirClientEvent
DECL|function|QMirClientEvent
DECL|function|QMirClientInput
DECL|function|customEvent
DECL|function|dispatchInputEvent
DECL|function|dispatchKeyEvent
DECL|function|dispatchOrientationEvent
DECL|function|dispatchPointerEvent
DECL|function|dispatchTouchEvent
DECL|function|extract_buttons
DECL|function|nativeEventTypeToStr
DECL|function|nativeOrientationDirectionToStr
DECL|function|postEvent
DECL|function|qt_modifiers_from_mir
DECL|function|translateKeysym
DECL|function|~QMirClientEvent
DECL|function|~QMirClientInput
DECL|macro|LOG_EVENTS
DECL|member|nativeEvent
DECL|member|window
DECL|variable|KeyTable
