DECL|class|QMirClientResourceMap
DECL|function|QMirClientNativeInterface
DECL|function|QMirClientResourceMap
DECL|function|nativeResourceForContext
DECL|function|nativeResourceForScreen
DECL|function|nativeResourceForWindow
DECL|function|~QMirClientNativeInterface
