DECL|function|generateTestData
DECL|function|getTestForPath
DECL|function|replaceInFile
DECL|function|subdirs
DECL|variable|extraArgs
DECL|variable|formats
DECL|variable|qtver
DECL|variable|replacements
DECL|variable|rootPath
