DECL|class|tst_Selftests
DECL|function|LoggerSet
DECL|function|allLoggerSets
DECL|function|cleanup
DECL|function|doRunSubTest
DECL|function|expectedResult
DECL|function|extractXmlAttribute
DECL|function|initTestCase
DECL|function|insertEnvironmentVariable
DECL|function|logFormat
DECL|function|logName
DECL|function|parse
DECL|function|processEnvironment
DECL|function|qCompare
DECL|function|runSubTest
DECL|function|runSubTest_data
DECL|function|splitLines
DECL|function|toString
DECL|member|arguments
DECL|member|iterations
DECL|member|loggers
DECL|member|name
DECL|member|total
DECL|member|unit
DECL|namespace|QTest
DECL|struct|BenchmarkResult
DECL|struct|LoggerSet
