DECL|class|MessageHandlerSetter
DECL|class|MyLine
DECL|class|MyPoint
DECL|class|tst_QDebug
DECL|function|MessageHandlerSetter
DECL|function|MyLine
DECL|function|MyPoint
DECL|function|assignment
DECL|function|criticalWithoutDebug
DECL|function|debugSpaceHandling
DECL|function|debugWithBool
DECL|function|defaultMessagehandler
DECL|function|myMessageHandler
DECL|function|operator <<
DECL|function|operator <<
DECL|function|qDebugQLatin1String
DECL|function|qDebugQStringRef
DECL|function|stateSaver
DECL|function|veryLongWarningMessage
DECL|function|warningWithoutDebug
DECL|function|~MessageHandlerSetter
DECL|member|oldMessageHandler
DECL|member|p1
DECL|member|p2
DECL|member|v1
DECL|member|v2
DECL|variable|s_file
DECL|variable|s_function
DECL|variable|s_line
DECL|variable|s_msg
DECL|variable|s_msgType
DECL|variable|tst_QDebug
