DECL|class|MessageHandlerSetter
DECL|class|tst_QDebug
DECL|function|MessageHandlerSetter
DECL|function|assignment
DECL|function|criticalWithoutDebug
DECL|function|debugWithBool
DECL|function|defaultMessagehandler
DECL|function|myMessageHandler
DECL|function|qDebugQStringRef
DECL|function|veryLongWarningMessage
DECL|function|warningWithoutDebug
DECL|function|~MessageHandlerSetter
DECL|member|oldMessageHandler
DECL|variable|s_file
DECL|variable|s_function
DECL|variable|s_line
DECL|variable|s_msg
DECL|variable|s_msgType
DECL|variable|tst_QDebug
