DECL|class|CustomEffect
DECL|class|CustomItem
DECL|class|DeviceEffect
DECL|class|MyGraphicsItem
DECL|class|PixmapItemEffect
DECL|class|tst_QGraphicsEffect
DECL|function|CustomEffect
DECL|function|CustomItem
DECL|function|MyGraphicsItem
DECL|function|PixmapItemEffect
DECL|function|boundingRect
DECL|function|boundingRect2
DECL|function|boundingRectFor
DECL|function|boundingRectFor
DECL|function|boundingRectFor
DECL|function|boundingRectFor
DECL|function|childrenVisibilityShouldInvalidateCache
DECL|function|colorize
DECL|function|deviceCoordinateTranslateCaching
DECL|function|draw
DECL|function|draw
DECL|function|draw
DECL|function|draw
DECL|function|drawPixmapItem
DECL|function|dropShadowClipping
DECL|function|grayscale
DECL|function|inheritOpacity
DECL|function|initTestCase
DECL|function|itemHasNoContents
DECL|function|margin
DECL|function|opacity
DECL|function|paint
DECL|function|paint
DECL|function|prepareGeometryChangeInvalidateCache
DECL|function|reset
DECL|function|reset
DECL|function|setEnabled
DECL|function|setMargin
DECL|function|source
DECL|function|sourceChanged
DECL|member|doNothingInDraw
DECL|member|m_margin
DECL|member|m_opacity
DECL|member|m_painter
DECL|member|m_painter
DECL|member|m_source
DECL|member|m_sourceChangedFlags
DECL|member|m_styleOption
DECL|member|m_styleOption
DECL|member|nbPaint
DECL|member|numRepaints
DECL|member|numRepaints
DECL|member|pixmap
DECL|member|repaints
