DECL|class|Consumer
DECL|class|Producer
DECL|class|tst_QSharedMemory
DECL|function|Producer
DECL|function|attach
DECL|function|attachTooMuch
DECL|function|attach_data
DECL|function|cleanup
DECL|function|constructor
DECL|function|create
DECL|function|create_data
DECL|function|emptyMemory
DECL|function|helperBinary
DECL|function|init
DECL|function|initTestCase
DECL|function|key
DECL|function|key_data
DECL|function|lock
DECL|function|readOnly
DECL|function|rememberKey
DECL|function|remove
DECL|function|removeWhileAttached
DECL|function|run
DECL|function|run
DECL|function|simpleDoubleProducerConsumer
DECL|function|simpleProcessProducerConsumer
DECL|function|simpleProcessProducerConsumer_data
DECL|function|simpleProducerConsumer
DECL|function|simpleProducerConsumer_data
DECL|function|simpleThreadedProducerConsumer
DECL|function|simpleThreadedProducerConsumer_data
DECL|function|tst_QSharedMemory
DECL|function|uniqueKey
DECL|function|uniqueKey_data
DECL|function|useTooMuchMemory
DECL|function|~tst_QSharedMemory
DECL|macro|EXISTING_SHARE
DECL|macro|EXISTING_SIZE
DECL|member|existingSharedMemory
DECL|member|jail
DECL|member|keys
DECL|member|producer
