DECL|class|tst_QLoggingRegistry
DECL|function|QLoggingRegistry_config
DECL|function|QLoggingRegistry_environment
DECL|function|QLoggingRegistry_rulePriorities
DECL|function|QLoggingSettingsParser_iniStyle
DECL|function|initTestCase
