DECL|class|Direct2DPathGeometryWriter
DECL|class|QWindowsDirect2DPaintEnginePrivate
DECL|class|QWindowsDirect2DPaintEngineSuspenderImpl
DECL|class|QWindowsDirect2DPaintEngineSuspenderPrivate
DECL|enumerator|AxisAlignedClip
DECL|enumerator|D2DDebugDrawEllipseFTag
DECL|enumerator|D2DDebugDrawEllipseTag
DECL|enumerator|D2DDebugDrawImageTag
DECL|enumerator|D2DDebugDrawInitialStateTag
DECL|enumerator|D2DDebugDrawPixmapTag
DECL|enumerator|D2DDebugDrawRectFsTag
DECL|enumerator|D2DDebugDrawRectsTag
DECL|enumerator|D2DDebugDrawStaticTextItemTag
DECL|enumerator|D2DDebugDrawTextItemTag
DECL|enumerator|D2DDebugFillRectTag
DECL|enumerator|D2DDebugFillTag
DECL|enumerator|LayerClip
DECL|enumerator|SimpleSystemClip
DECL|enum|ClipType
DECL|function|Direct2DPathGeometryWriter
DECL|function|QWindowsDirect2DPaintEngine
DECL|function|QWindowsDirect2DPaintEnginePrivate
DECL|function|QWindowsDirect2DPaintEngineSuspender
DECL|function|QWindowsDirect2DPaintEngineSuspenderImpl
DECL|function|QWindowsDirect2DPaintEngineSuspenderPrivate
DECL|function|adjustForAliasing
DECL|function|adjustForAliasing
DECL|function|adjustLine
DECL|function|adjusted
DECL|function|antiAliasingEnabled
DECL|function|antialiasMode
DECL|function|applyBrushOrigin
DECL|function|begin
DECL|function|begin
DECL|function|brushChanged
DECL|function|brushOriginChanged
DECL|function|cleanup_func
DECL|function|clearClips
DECL|function|clip
DECL|function|clip
DECL|function|clipEnabledChanged
DECL|function|close
DECL|function|compositionModeChanged
DECL|function|curveTo
DECL|function|dc
DECL|function|draw
DECL|function|drawEllipse
DECL|function|drawEllipse
DECL|function|drawGlyphRun
DECL|function|drawImage
DECL|function|drawPixmap
DECL|function|drawRects
DECL|function|drawRects
DECL|function|drawStaticTextItem
DECL|function|drawTextItem
DECL|function|emulationRequired
DECL|function|end
DECL|function|ensureBrush
DECL|function|ensureBrush
DECL|function|ensurePen
DECL|function|ensurePen
DECL|function|factory
DECL|function|fill
DECL|function|fillRect
DECL|function|fontFaceFromFontEngine
DECL|function|geometry
DECL|function|interpolationMode
DECL|function|isInFigure
DECL|function|isLinePositivelySloped
DECL|function|layerOptions
DECL|function|lineTo
DECL|function|moveTo
DECL|function|negateCurrentBrushOrigin
DECL|function|opacityChanged
DECL|function|penChanged
DECL|function|pushClip
DECL|function|rasterFill
DECL|function|renderHintsChanged
DECL|function|reset
DECL|function|reset
DECL|function|resume
DECL|function|resume
DECL|function|setAliasingEnabled
DECL|function|setPositiveSlopeAdjustmentEnabled
DECL|function|setState
DECL|function|setWindingFillEnabled
DECL|function|stroke
DECL|function|stroke
DECL|function|suspend
DECL|function|to_d2d_brush
DECL|function|transformChanged
DECL|function|transformFromLine
DECL|function|type
DECL|function|updateBrush
DECL|function|updateBrushOrigin
DECL|function|updateClipEnabled
DECL|function|updateCompositionMode
DECL|function|updateHints
DECL|function|updateOpacity
DECL|function|updatePen
DECL|function|updateTransform
DECL|function|vectorPathToID2D1PathGeometry
DECL|function|~QWindowsDirect2DPaintEngineSuspender
DECL|function|~QWindowsDirect2DPaintEngineSuspenderImpl
DECL|macro|D2D_TAG
DECL|member|aliased
DECL|member|antiAliased
DECL|member|bitmap
DECL|member|brush
DECL|member|brush
DECL|member|brush
DECL|member|clipFlags
DECL|member|currentBrushOrigin
DECL|member|dashBrush
DECL|member|dashLength
DECL|member|dcSuspender
DECL|member|emulate
DECL|member|emulate
DECL|member|engineSuspender
DECL|member|fallbackImage
DECL|member|flags
DECL|member|fontCache
DECL|member|m_active
DECL|member|m_adjustPositivelySlopedLines
DECL|member|m_engine
DECL|member|m_geometry
DECL|member|m_inFigure
DECL|member|m_previousPoint
DECL|member|m_roundCoordinates
DECL|member|m_sink
DECL|member|pen
DECL|member|pushedClips
DECL|member|qbrush
DECL|member|qpen
DECL|member|strokeStyle
DECL|struct|D2DVectorPathCache
DECL|variable|MAGICAL_ALIASING_OFFSET
