DECL|class|Direct2DPathGeometryWriter
DECL|class|QWindowsDirect2DPaintEnginePrivate
DECL|enumerator|AxisAlignedClip
DECL|enumerator|D2DDebugDrawImageTag
DECL|enumerator|D2DDebugDrawInitialStateTag
DECL|enumerator|D2DDebugDrawPixmapTag
DECL|enumerator|D2DDebugDrawStaticTextItemTag
DECL|enumerator|D2DDebugDrawTextItemTag
DECL|enumerator|D2DDebugFillTag
DECL|enumerator|LayerClip
DECL|enumerator|SimpleSystemClip
DECL|enum|ClipType
DECL|function|Direct2DPathGeometryWriter
DECL|function|QWindowsDirect2DPaintEngine
DECL|function|QWindowsDirect2DPaintEnginePrivate
DECL|function|adjusted
DECL|function|antialiasMode
DECL|function|applyBrushOrigin
DECL|function|begin
DECL|function|begin
DECL|function|brushChanged
DECL|function|brushOriginChanged
DECL|function|clearClips
DECL|function|clip
DECL|function|clip
DECL|function|clipEnabledChanged
DECL|function|close
DECL|function|compositionModeChanged
DECL|function|curveTo
DECL|function|dc
DECL|function|drawGlyphRun
DECL|function|drawImage
DECL|function|drawPixmap
DECL|function|drawStaticTextItem
DECL|function|drawTextItem
DECL|function|end
DECL|function|ensureBrush
DECL|function|ensureBrush
DECL|function|ensurePen
DECL|function|ensurePen
DECL|function|factory
DECL|function|fill
DECL|function|fontFaceFromFontEngine
DECL|function|fontSizeInDIP
DECL|function|geometry
DECL|function|interpolationMode
DECL|function|isInFigure
DECL|function|lineTo
DECL|function|moveTo
DECL|function|negateCurrentBrushOrigin
DECL|function|opacityChanged
DECL|function|painterPathToID2D1PathGeometry
DECL|function|penChanged
DECL|function|pixelSizeToDIP
DECL|function|pointSizeToDIP
DECL|function|pushClip
DECL|function|rasterFill
DECL|function|renderHintsChanged
DECL|function|reset
DECL|function|reset
DECL|function|setAliasingEnabled
DECL|function|setState
DECL|function|setWindingFillEnabled
DECL|function|to_d2d_brush
DECL|function|transformChanged
DECL|function|type
DECL|function|updateBrush
DECL|function|updateBrushOrigin
DECL|function|updateClipEnabled
DECL|function|updateCompositionMode
DECL|function|updateHints
DECL|function|updateOpacity
DECL|function|updatePen
DECL|function|updateTransform
DECL|function|vectorPathToID2D1PathGeometry
DECL|macro|D2D_TAG
DECL|member|bitmap
DECL|member|brush
DECL|member|brush
DECL|member|brush
DECL|member|clipFlags
DECL|member|currentBrushOrigin
DECL|member|emulate
DECL|member|emulate
DECL|member|m_geometry
DECL|member|m_inFigure
DECL|member|m_roundCoordinates
DECL|member|m_sink
DECL|member|pen
DECL|member|pushedClips
DECL|member|qbrush
DECL|member|qpen
DECL|member|strokeStyle
