DECL|class|QWindowsDirect2DBitmapPrivate
DECL|function|QWindowsDirect2DBitmap
DECL|function|QWindowsDirect2DBitmap
DECL|function|QWindowsDirect2DBitmapPrivate
DECL|function|bitmap
DECL|function|bitmapProperties
DECL|function|deviceContext
DECL|function|fill
DECL|function|fromImage
DECL|function|resize
DECL|function|resize
DECL|function|size
DECL|function|toImage
DECL|function|toImage
DECL|function|~QWindowsDirect2DBitmap
DECL|member|bitmap
DECL|member|deviceContext
