DECL|function|QWindowsDirect2DWindow
DECL|function|copyBackBuffer
DECL|function|flush
DECL|function|pixmap
DECL|function|present
DECL|function|resizeSwapChain
DECL|function|setWindowFlags
DECL|function|setupBitmap
DECL|function|setupSwapChain
DECL|function|~QWindowsDirect2DWindow
