DECL|class|QWindowsDirect2DPlatformPixmapPrivate
DECL|function|QWindowsDirect2DPlatformPixmap
DECL|function|QWindowsDirect2DPlatformPixmapPrivate
DECL|function|bitmap
DECL|function|devicePixelRatio
DECL|function|fill
DECL|function|fromImage
DECL|function|hasAlphaChannel
DECL|function|metric
DECL|function|paintEngine
DECL|function|resize
DECL|function|setDevicePixelRatio
DECL|function|toImage
DECL|function|toImage
DECL|function|~QWindowsDirect2DPlatformPixmap
DECL|member|bitmap
DECL|member|device
DECL|member|devicePixelRatio
DECL|variable|qt_d2dpixmap_serno
