DECL|function|QAsn1Element
DECL|function|createOidMap
DECL|function|fromInteger
DECL|function|fromObjectId
DECL|function|fromVector
DECL|function|read
DECL|function|read
DECL|function|toDateTime
DECL|function|toInfo
DECL|function|toObjectId
DECL|function|toObjectName
DECL|function|toString
DECL|function|toVector
DECL|function|write
DECL|typedef|OidNameMap
