DECL|function|QSslContext
DECL|function|cacheSession
DECL|function|createSsl
DECL|function|error
DECL|function|errorString
DECL|function|fromConfiguration
DECL|function|get_dh1024
DECL|function|initSslContext
DECL|function|msgErrorSettingEllipticCurves
DECL|function|next_proto_cb
DECL|function|npnContext
DECL|function|sessionASN1
DECL|function|sessionTicketLifeTimeHint
DECL|function|setSessionASN1
DECL|function|sharedFromConfiguration
DECL|function|~QSslContext
