DECL|function|clear
DECL|function|decodeDer
DECL|function|decodePem
DECL|function|deriveKey
DECL|function|handle
DECL|function|length
DECL|function|numberOfBits
DECL|function|toPem
DECL|variable|bits_table
