DECL|function|clear
DECL|function|decodeDer
DECL|function|decodePem
DECL|function|decrypt
DECL|function|doCrypt
DECL|function|encrypt
DECL|function|fromEVP_PKEY
DECL|function|handle
DECL|function|length
DECL|function|toPem
