DECL|function|SslKeyGlobal
DECL|function|clear
DECL|function|decodeDer
DECL|function|decodePem
DECL|function|handle
DECL|function|length
DECL|function|toPem
DECL|member|bufferFactory
DECL|member|key
DECL|member|keyProvider
DECL|struct|EVP_PKEY
DECL|struct|SslKeyGlobal
