DECL|class|tst_QLine
DECL|function|testAngle
DECL|function|testAngle2
DECL|function|testAngle2_data
DECL|function|testAngle3
DECL|function|testAngleTo
DECL|function|testAngleTo_data
DECL|function|testAngle_data
DECL|function|testIntersection
DECL|function|testIntersection_data
DECL|function|testLength
DECL|function|testLength_data
DECL|function|testNormalVector
DECL|function|testNormalVector_data
DECL|function|testSet
DECL|macro|M_2PI
DECL|macro|SQRT2
DECL|macro|UNITX_45
DECL|variable|epsilon
