DECL|macro|MOVIEPLAYER_H
DECL|variable|QCheckBox
DECL|variable|QGridLayout
DECL|variable|QHBoxLayout
DECL|variable|QLabel
DECL|variable|QMovie
DECL|variable|QSlider
DECL|variable|QSpinBox
DECL|variable|QToolButton
DECL|variable|QVBoxLayout
