DECL|function|HelloWindow
DECL|function|Renderer
DECL|function|color
DECL|function|createGeometry
DECL|function|exposeEvent
DECL|function|extrude
DECL|function|initialize
DECL|function|mousePressEvent
DECL|function|paintQtLogo
DECL|function|quad
DECL|function|render
DECL|function|setAnimating
DECL|function|updateColor
