DECL|function|HelloWindow
DECL|function|createGeometry
DECL|function|extrude
DECL|function|initialize
DECL|function|mousePressEvent
DECL|function|paintQtLogo
DECL|function|quad
DECL|function|render
DECL|function|updateColor
