DECL|class|CustomProxy
DECL|class|DrawTextStyle
DECL|class|MyWidget
DECL|class|Qt42Style
DECL|class|tst_QStyle
DECL|function|DrawTextStyle
DECL|function|MyWidget
DECL|function|Qt42Style
DECL|function|cleanup
DECL|function|cleanupTestCase
DECL|function|comparePixmap
DECL|function|defaultFont
DECL|function|drawItemPixmap
DECL|function|drawItemText
DECL|function|init
DECL|function|initTestCase
DECL|function|lineUpLayoutTest
DECL|function|paintEvent
DECL|function|pixelMetric
DECL|function|pixelMetric
DECL|function|pixelMetric
DECL|function|progressBarChangeStyle
DECL|function|qt_wince_is_smartphone
DECL|function|readImage
DECL|function|testAllFunctions
DECL|function|testCDEStyle
DECL|function|testCleanlooksStyle
DECL|function|testDrawingShortcuts
DECL|function|testMacStyle
DECL|function|testMotifStyle
DECL|function|testPainting
DECL|function|testPlastiqueStyle
DECL|function|testProxyStyle
DECL|function|testS60Style
DECL|function|testScrollBarSubControls
DECL|function|testStyleFactory
DECL|function|testWindowsCEStyle
DECL|function|testWindowsMobileStyle
DECL|function|testWindowsStyle
DECL|function|testWindowsVistaStyle
DECL|function|testWindowsXPStyle
DECL|function|tst_QStyle
DECL|function|writeImage
DECL|function|~tst_QStyle
DECL|member|alignment
DECL|member|margin
DECL|member|margin_toplevel
DECL|member|spacing
DECL|member|testWidget
