DECL|function|deviceState
DECL|function|getPos
DECL|function|point
DECL|function|processTouchCancel
DECL|function|processTouchDown
DECL|function|processTouchFrame
DECL|function|processTouchMotion
DECL|function|processTouchUp
DECL|function|registerDevice
DECL|function|unregisterDevice
