DECL|class|QSequentialFile
DECL|class|tst_QIcoImageFormat
DECL|function|QSequentialFile
DECL|function|SequentialFile
DECL|function|SequentialFile_data
DECL|function|canRead
DECL|function|canRead_data
DECL|function|format
DECL|function|imageCount
DECL|function|imageCount_data
DECL|function|initTestCase
DECL|function|isSequential
DECL|function|jumpToNextImage
DECL|function|jumpToNextImage_data
DECL|function|loopCount
DECL|function|loopCount_data
DECL|function|nextImageDelay
DECL|function|nextImageDelay_data
DECL|function|pngCompression
DECL|function|pngCompression_data
DECL|function|write
DECL|function|write_data
DECL|function|~QSequentialFile
DECL|member|m_IconPath
