DECL|function|QCupsPrintEngine
DECL|function|QCupsPrintEnginePrivate
DECL|function|changePrinter
DECL|function|closePrintDevice
DECL|function|openPrintDevice
DECL|function|property
DECL|function|setPageSize
DECL|function|setProperty
DECL|function|setupDefaultPrinter
DECL|function|~QCupsPrintEngine
DECL|function|~QCupsPrintEnginePrivate
