DECL|class|HackBrowser
DECL|class|HelpBrowser
DECL|class|TestBrowser
DECL|class|tst_QTextBrowser
DECL|function|TestBrowser
DECL|function|adjacentAnchors
DECL|function|anchors
DECL|function|anchorsWithSelfBuiltHtml
DECL|function|bgColorOnSourceChange
DECL|function|cleanup
DECL|function|clearHistory
DECL|function|focusHistory
DECL|function|focusIndicator
DECL|function|focusTheNextChild
DECL|function|focusThePreviousChild
DECL|function|forwardBackwardAvailable
DECL|function|forwardButton
DECL|function|init
DECL|function|loadResource
DECL|function|loadResource
DECL|function|loadResourceOnRelativeLocalFiles
DECL|function|noReloadOnAnchorJump
DECL|function|relativeLinks
DECL|function|relativeNonLocalUrls
DECL|function|resourceAutoDetection
DECL|function|sourceInsideLoadResource
DECL|function|textInteractionFlags_vs_readOnly
DECL|function|tst_QTextBrowser
DECL|function|urlEncoding
DECL|function|viewportPositionInHistory
DECL|function|~tst_QTextBrowser
DECL|macro|SRCDIR
DECL|member|browser
DECL|member|htmlLoadAttempts
DECL|member|lastResource
DECL|member|sourceInsideLoadResource
