DECL|class|QIBusPlatformInputContextPrivate
DECL|enumerator|debug
DECL|function|QIBusPlatformInputContext
DECL|function|QIBusPlatformInputContextPrivate
DECL|function|commit
DECL|function|commitText
DECL|function|createConnection
DECL|function|cursorRectChanged
DECL|function|deleteSurroundingText
DECL|function|filterEvent
DECL|function|filterEventFinished
DECL|function|invokeAction
DECL|function|isValid
DECL|function|reset
DECL|function|setFocusObject
DECL|function|surroundingTextRequired
DECL|function|update
DECL|function|updatePreeditText
DECL|function|~QIBusPlatformInputContext
DECL|function|~QIBusPlatformInputContextPrivate
DECL|macro|IBUS_RELEASE_MASK
DECL|member|bus
DECL|member|connection
DECL|member|context
DECL|member|needsSurroundingText
DECL|member|predit
DECL|member|valid
