DECL|class|QIBusPlatformInputContextPrivate
DECL|enumerator|debug
DECL|function|QIBusPlatformInputContext
DECL|function|QIBusPlatformInputContextPrivate
DECL|function|commit
DECL|function|commitText
DECL|function|createConnection
DECL|function|cursorRectChanged
DECL|function|handlesInputPanelVisibility
DECL|function|inputItemChanged
DECL|function|invokeAction
DECL|function|isValid
DECL|function|reset
DECL|function|update
DECL|function|updatePreeditText
DECL|function|x11FilterEvent
DECL|function|~QIBusPlatformInputContext
DECL|function|~QIBusPlatformInputContextPrivate
DECL|member|bus
DECL|member|connection
DECL|member|context
DECL|member|predit
DECL|member|valid
DECL|variable|keycode_table
