DECL|class|CounterButton
DECL|class|tst_QAccessibility
DECL|function|CounterButton
DECL|function|IsValidCEPlatform
DECL|function|abstractScrollAreaTest
DECL|function|accelerators
DECL|function|accessibleInterfaceAbove
DECL|function|accessibleInterfaceLeftOf
DECL|function|accessibleName
DECL|function|actionTest
DECL|function|applicationTest
DECL|function|bridgeTest
DECL|function|buttonTest
DECL|function|calendarWidgetTest
DECL|function|characterRect
DECL|function|childRect
DECL|function|cleanup
DECL|function|cleanupTestCase
DECL|function|comboBoxTest
DECL|function|createWidgets
DECL|function|customWidget
DECL|function|deletedWidget
DECL|function|dialTest
DECL|function|dialogButtonBoxTest
DECL|function|dockWidgetTest
DECL|function|doubleSpinBoxTest
DECL|function|eventTest
DECL|function|fuzzyRectCompare
DECL|function|groupBoxTest
DECL|function|hideShowTest
DECL|function|incClickCount
DECL|function|init
DECL|function|initTestCase
DECL|function|labelTest
DECL|function|lineEditTest
DECL|function|lineEditTextFunctions
DECL|function|lineEditTextFunctions_data
DECL|function|listTest
DECL|function|mainWindowTest
DECL|function|mdiAreaTest
DECL|function|mdiSubWindowTest
DECL|function|menuTest
DECL|function|msgRectMismatch
DECL|function|navigateHierarchy
DECL|function|onClicked
DECL|function|queryIA2
DECL|function|rubberBandTest
DECL|function|scrollAreaTest
DECL|function|scrollBarTest
DECL|function|setFrameless
DECL|function|sliderTest
DECL|function|spinBoxTest
DECL|function|state
DECL|function|statesStructTest
DECL|function|subWindowTest
DECL|function|subclassedWidget
DECL|function|tabTest
DECL|function|tabWidgetTest
DECL|function|tableTest
DECL|function|textAttributes
DECL|function|textAttributes_data
DECL|function|textBrowserTest
DECL|function|textEditTest
DECL|function|textInterfaceTest
DECL|function|textInterfaceTest_data
DECL|function|treeTest
DECL|function|tst_QAccessibility
DECL|function|verifyChild
DECL|function|verifyHierarchy
DECL|function|~tst_QAccessibility
DECL|macro|EXPECT
DECL|macro|QSETCOMPARE
DECL|macro|SPI_GETPLATFORMTYPE
DECL|macro|interface
DECL|member|clickCount
DECL|member|click_count
