DECL|class|QShortcutMapPrivate
DECL|function|QShortcutEntry
DECL|function|QShortcutEntry
DECL|function|QShortcutEntry
DECL|function|QShortcutMap
DECL|function|QShortcutMapPrivate
DECL|function|addShortcut
DECL|function|clearSequence
DECL|function|correctActionContext
DECL|function|correctContext
DECL|function|correctGraphicsWidgetContext
DECL|function|correctWidgetContext
DECL|function|createNewSequences
DECL|function|dispatchEvent
DECL|function|dumpMap
DECL|function|find
DECL|function|hasShortcutForKeySequence
DECL|function|matches
DECL|function|matches
DECL|function|nextState
DECL|function|operator <
DECL|function|qWidgetShortcutContextMatcher
DECL|function|removeShortcut
DECL|function|resetState
DECL|function|setShortcutAutoRepeat
DECL|function|setShortcutEnabled
DECL|function|state
DECL|function|translateModifiers
DECL|function|tryShortcutEvent
DECL|function|~QShortcutMap
DECL|member|ambigCount
DECL|member|autorepeat
DECL|member|context
DECL|member|contextMatcher
DECL|member|currentId
DECL|member|currentSequences
DECL|member|currentState
DECL|member|enabled
DECL|member|id
DECL|member|identicals
DECL|member|keyseq
DECL|member|newEntries
DECL|member|owner
DECL|member|prevSequence
DECL|member|q_ptr
DECL|member|sequences
DECL|struct|QShortcutEntry
