DECL|function|BencodeParser
DECL|function|dictionary
DECL|function|errorString
DECL|function|getByteString
DECL|function|getDictionary
DECL|function|getInteger
DECL|function|getList
DECL|function|infoSection
DECL|function|parse
