DECL|class|TorrentView
DECL|class|TorrentViewDelegate
DECL|function|MainWindow
DECL|function|TorrentView
DECL|function|TorrentViewDelegate
DECL|function|about
DECL|function|acceptFileDrop
DECL|function|addTorrent
DECL|function|addTorrent
DECL|function|clientForRow
DECL|function|closeEvent
DECL|function|dragMoveEvent
DECL|function|dropEvent
DECL|function|loadSettings
DECL|function|moveTorrentDown
DECL|function|moveTorrentUp
DECL|function|paint
DECL|function|pauseTorrent
DECL|function|rateFromValue
DECL|function|removeTorrent
DECL|function|rowOfClient
DECL|function|saveSettings
DECL|function|setActionsEnabled
DECL|function|setDownloadLimit
DECL|function|setUploadLimit
DECL|function|sizeHint
DECL|function|torrentError
DECL|function|torrentStopped
DECL|function|updateDownloadRate
DECL|function|updatePeerInfo
DECL|function|updateProgress
DECL|function|updateState
DECL|function|updateUploadRate
