DECL|function|PeerWireClient
DECL|function|availablePieces
DECL|function|canTransferMore
DECL|function|cancelRequest
DECL|function|chokePeer
DECL|function|connectToHost
DECL|function|diconnectFromHost
DECL|function|downloadSpeed
DECL|function|fromNetworkData
DECL|function|incomingBlocks
DECL|function|initialize
DECL|function|peer
DECL|function|processIncomingData
DECL|function|readData
DECL|function|readFromSocket
DECL|function|readLineData
DECL|function|requestBlock
DECL|function|sendBlock
DECL|function|sendHandShake
DECL|function|sendInterested
DECL|function|sendKeepAlive
DECL|function|sendNotInterested
DECL|function|sendPieceList
DECL|function|sendPieceNotification
DECL|function|setPeer
DECL|function|setReadBufferSize
DECL|function|socketStateChanged
DECL|function|timerEvent
DECL|function|toNetworkData
DECL|function|unchokePeer
DECL|function|uploadSpeed
DECL|function|writeData
DECL|function|writeToSocket
DECL|variable|ClientTimeout
DECL|variable|ConnectTimeout
DECL|variable|FullHeaderSize
DECL|variable|KeepAliveInterval
DECL|variable|MinimalHeaderSize
DECL|variable|PendingRequestTimeout
DECL|variable|ProtocolId
DECL|variable|ProtocolIdSize
DECL|variable|RateControlTimerDelay
