DECL|function|TorrentBlock
DECL|function|operator
DECL|macro|PEERWIRECLIENT_H
DECL|member|length
DECL|member|offset
DECL|member|pieceIndex
DECL|struct|TorrentBlock
DECL|variable|QHostAddress
DECL|variable|QTimerEvent
DECL|variable|TorrentPeer
