DECL|class|QTtfStream
DECL|enumerator|OffCurve
DECL|enumerator|OnCurve
DECL|enumerator|Repeat
DECL|enumerator|XSame
DECL|enumerator|XShortPositive
DECL|enumerator|XShortVector
DECL|enumerator|YSame
DECL|enumerator|YShortPositive
DECL|enumerator|YShortVector
DECL|enum|Flags
DECL|function|QTtfStream
DECL|function|addGlyph
DECL|function|align4
DECL|function|bindFont
DECL|function|checkRanges
DECL|function|checksum
DECL|function|convertPath
DECL|function|convertToRelative
DECL|function|createToUnicodeMap
DECL|function|generateGlyph
DECL|function|generateGlyphTables
DECL|function|generateHead
DECL|function|generateHhea
DECL|function|generateMaxp
DECL|function|generateName
DECL|function|generateName
DECL|function|getBounds
DECL|function|getGlyphData
DECL|function|getReverseMap
DECL|function|glyphName
DECL|function|glyphName
DECL|function|offset
DECL|function|operator <
DECL|function|operator <
DECL|function|operator <<
DECL|function|operator <<
DECL|function|operator <<
DECL|function|operator <<
DECL|function|operator <<
DECL|function|operator <<
DECL|function|operator <<
DECL|function|setOffset
DECL|function|toTruetype
DECL|function|widthArray
DECL|macro|TAG
DECL|macro|TO_TTF
DECL|member|advanceWidth
DECL|member|ascender
DECL|member|copyright
DECL|member|created
DECL|member|data
DECL|member|data
DECL|member|data
DECL|member|descender
DECL|member|family
DECL|member|flags
DECL|member|flags
DECL|member|font_revision
DECL|member|head
DECL|member|hhea
DECL|member|index
DECL|member|index
DECL|member|indexToLocFormat
DECL|member|lineGap
DECL|member|lsb
DECL|member|macStyle
DECL|member|maxAdvanceWidth
DECL|member|maxComponentDepth
DECL|member|maxComponentElements
DECL|member|maxCompositeContours
DECL|member|maxCompositePoints
DECL|member|maxContours
DECL|member|maxPoints
DECL|member|maxp
DECL|member|minLeftSideBearing
DECL|member|minRightSideBearing
DECL|member|modified
DECL|member|nameId
DECL|member|numContours
DECL|member|numGlyphs
DECL|member|numPoints
DECL|member|numberOfHMetrics
DECL|member|postscript_name
DECL|member|start
DECL|member|subfamily
DECL|member|tag
DECL|member|u
DECL|member|value
DECL|member|x
DECL|member|xMax
DECL|member|xMax
DECL|member|xMaxExtent
DECL|member|xMin
DECL|member|xMin
DECL|member|y
DECL|member|yMax
DECL|member|yMax
DECL|member|yMin
DECL|member|yMin
DECL|struct|QTtfGlyph
DECL|struct|QTtfNameRecord
DECL|struct|QTtfTable
DECL|struct|TTF_POINT
DECL|struct|qttf_font_tables
DECL|struct|qttf_head_table
DECL|struct|qttf_hhea_table
DECL|struct|qttf_maxp_table
DECL|struct|qttf_name_table
DECL|typedef|F2DOT14
DECL|typedef|GlyphID
DECL|typedef|Offset
DECL|typedef|Tag
DECL|variable|agl
DECL|variable|symbol_map
DECL|variable|unicode_to_aglindex
