DECL|enumerator|cmapCacheSize
DECL|function|QFreetypeFace
DECL|function|getGlyph
DECL|function|lock
DECL|function|qHash
DECL|function|unlock
DECL|function|~QFreetypeFace
DECL|macro|QFONTENGINE_FT_P_H
DECL|member|QFreetypeFace
DECL|member|_lock
DECL|member|cmapCache
DECL|member|face
DECL|member|fontData
DECL|member|hbFace
DECL|member|hbFace_destroy_func
DECL|member|matrix
DECL|member|private
DECL|member|ref
DECL|member|symbol_map
DECL|member|unicode_map
DECL|member|xsize
DECL|member|ysize
DECL|struct|QFreetypeFace
DECL|variable|QFontEngineFTRawFont
DECL|variable|QFontconfigDatabase
