DECL|class|QFontEngineQPF1Data
DECL|class|QPFGlyph
DECL|class|QPFGlyphMetrics
DECL|class|QPFGlyphTree
DECL|enumerator|RendererOwnsData
DECL|enum|Flags
DECL|function|QFontEngineQPF1
DECL|function|QPFGlyph
DECL|function|QPFGlyph
DECL|function|QPFGlyphTree
DECL|function|QPFGlyphTree
DECL|function|QPFGlyphTree
DECL|function|addOutlineToPath
DECL|function|alphaMapForGlyph
DECL|function|ascent
DECL|function|boundingBox
DECL|function|boundingBox
DECL|function|canRender
DECL|function|descent
DECL|function|draw
DECL|function|dump
DECL|function|get
DECL|function|getChar
DECL|function|inFont
DECL|function|leading
DECL|function|lineThickness
DECL|function|maxCharWidth
DECL|function|minLeftBearing
DECL|function|minRightBearing
DECL|function|qt_mmap
DECL|function|qt_mmap
DECL|function|read
DECL|function|read
DECL|function|readData
DECL|function|readData
DECL|function|readMetrics
DECL|function|readMetrics
DECL|function|readNode
DECL|function|readNode
DECL|function|recalcAdvances
DECL|function|stringToCMap
DECL|function|totalChars
DECL|function|type
DECL|function|underlinePosition
DECL|function|weight
DECL|function|~QFontEngineQPF1
DECL|function|~QPFGlyph
DECL|function|~QPFGlyphTree
DECL|macro|FM_SMOOTH
DECL|macro|MAP_FAILED
DECL|macro|MAP_FILE
DECL|macro|QT_USE_MMAP
DECL|member|advance
DECL|member|ascent
DECL|member|bearingx
DECL|member|bearingy
DECL|member|data
DECL|member|descent
DECL|member|flags
DECL|member|flags
DECL|member|fm
DECL|member|glyph
DECL|member|height
DECL|member|leading
DECL|member|leftbearing
DECL|member|less
DECL|member|linestep
DECL|member|max
DECL|member|maxwidth
DECL|member|metrics
DECL|member|min
DECL|member|mmapLength
DECL|member|mmapStart
DECL|member|more
DECL|member|reserved
DECL|member|reserved3
DECL|member|rightbearing
DECL|member|tree
DECL|member|underlinepos
DECL|member|underlinewidth
DECL|member|width
DECL|struct|QPFFontMetrics
