DECL|class|QFontEngineFTS60
DECL|class|QSymbianFontDatabaseExtrasImplementation
DECL|function|OpenFontFromBitmapFont
DECL|function|QFontEngineFTS60
DECL|function|QFontEngineMultiS60
DECL|function|QSymbianFontDatabaseExtrasImplementation
DECL|function|addFontFileToFontStore
DECL|function|alternativeFilePaths
DECL|function|appFontLimitReached
DECL|function|appFontMarker
DECL|function|cleanedFontDef
DECL|function|cleanup
DECL|function|cleanup
DECL|function|clear
DECL|function|dWordPadding
DECL|function|extras
DECL|function|findFont
DECL|function|initializeDb
DECL|function|load
DECL|function|load
DECL|function|loadEngine
DECL|function|pixelsToPoints
DECL|function|pointsToPixels
DECL|function|qt_cleanup_symbianFontDatabase
DECL|function|qt_symbian_appFontNameWithoutMarker
DECL|function|qt_symbian_fontFamiliesOnFontServer
DECL|function|qt_symbian_fontNameHasAppFontMarker
DECL|function|qt_symbian_fontNameWithAppFontMarker
DECL|function|registerFont
DECL|function|registerScreenDeviceFont
DECL|function|removeAllApplicationFonts
DECL|function|removeAppFontData
DECL|function|removeApplicationFont
DECL|function|supportsThreadedFontRendering
DECL|function|tempAppFontFolder
DECL|function|toDWordBoundary
DECL|function|ttfCalcChecksum
DECL|function|ttfCanSymbianLoadFont
DECL|function|ttfMarkAppFont
DECL|function|ttfMarkNameTable
DECL|function|~QSymbianFontDatabaseExtrasImplementation
DECL|member|appFontMarkerPrefix
DECL|member|appFontMarkerPrefix
DECL|member|checkSum
DECL|member|count
DECL|member|encodingID
DECL|member|entrySelector
DECL|member|format
DECL|member|languageID
DECL|member|length
DECL|member|length
DECL|member|m_applicationFontFamilies
DECL|member|m_extras
DECL|member|m_extrasHash
DECL|member|m_heap
DECL|member|m_rasterizer
DECL|member|m_store
DECL|member|nameID
DECL|member|numTables
DECL|member|offset
DECL|member|offset
DECL|member|platformID
DECL|member|rangeShift
DECL|member|searchRange
DECL|member|sfntVersion
DECL|member|stringOffset
DECL|member|tag
DECL|struct|CFontFromFontStoreReleaser
DECL|struct|CFontFromScreenDeviceReleaser
DECL|struct|NameRecord
DECL|struct|NameTableHead
DECL|struct|OffsetTable
DECL|struct|TableRecord
DECL|variable|ttfMaxFileSize
