DECL|class|QtFreetypeData
DECL|function|QFontEngineFT
DECL|function|QGlyphSet
DECL|function|QTransformToFTMatrix
DECL|function|QtFreetypeData
DECL|function|addBitmapToPath
DECL|function|addGlyphToPath
DECL|function|addGlyphsToPath
DECL|function|addOutlineToPath
DECL|function|alphaMapBoundingBox
DECL|function|alphaMapForGlyph
DECL|function|alphaRGBMapForGlyph
DECL|function|ascent
DECL|function|averageCharWidth
DECL|function|boundingBox
DECL|function|boundingBox
DECL|function|boundingBox
DECL|function|canRender
DECL|function|clear
DECL|function|cloneWithSize
DECL|function|computeSize
DECL|function|convertGRAYToARGB
DECL|function|convertRGBToARGB
DECL|function|convertRGBToARGB_V
DECL|function|convoluteBitmap
DECL|function|descent
DECL|function|doKerning
DECL|function|emSquareSize
DECL|function|faceId
DECL|function|filterPixel
DECL|function|fsType
DECL|function|getChar
DECL|function|getFace
DECL|function|getPointInOutline
DECL|function|getPointInOutline
DECL|function|getSfntTable
DECL|function|getSfntTableData
DECL|function|getUnscaledGlyph
DECL|function|glyphCount
DECL|function|hb_getSFntTable
DECL|function|init
DECL|function|init
DECL|function|initFromFontEngine
DECL|function|leading
DECL|function|lineThickness
DECL|function|loadFlags
DECL|function|loadGlyph
DECL|function|loadGlyphFor
DECL|function|loadGlyphs
DECL|function|loadTransformedGlyphSet
DECL|function|lockFace
DECL|function|lockedAlphaMapForGlyph
DECL|function|maxCharWidth
DECL|function|minLeftBearing
DECL|function|minRightBearing
DECL|function|non_locked_face
DECL|function|properties
DECL|function|properties
DECL|function|qt_getFreetype
DECL|function|qt_getFreetypeData
DECL|function|qt_getFreetypeData
DECL|function|recalcAdvances
DECL|function|release
DECL|function|removeGlyphFromCache
DECL|function|removeGlyphFromCache
DECL|function|scaleOutline
DECL|function|setDefaultHintStyle
DECL|function|setGlyph
DECL|function|shouldUseDesignMetrics
DECL|function|stringToCMap
DECL|function|synthesized
DECL|function|underlinePosition
DECL|function|unlockAlphaMapForGlyph
DECL|function|unlockFace
DECL|function|xHeight
DECL|function|~Glyph
DECL|function|~QFontEngineFT
DECL|function|~QGlyphSet
DECL|macro|CEIL
DECL|macro|FLOOR
DECL|macro|QT_MAX_CACHED_GLYPH_SIZE
DECL|macro|QT_USE_FREETYPE_LCDFILTER
DECL|macro|Q_FT_GLYPHSLOT_EMBOLDEN
DECL|macro|Q_FT_GLYPHSLOT_OBLIQUE
DECL|macro|Q_HAS_FT_GLYPHSLOT_OBLIQUE
DECL|macro|ROUND
DECL|macro|TRUNC
DECL|macro|X_SIZE
DECL|macro|Y_SIZE
DECL|member|faces
DECL|member|library
DECL|variable|char_table
DECL|variable|char_table_entries
DECL|variable|subpixel_filter
