DECL|enumerator|EdgeDown
DECL|enumerator|EdgeLeft
DECL|enumerator|EdgeRight
DECL|enumerator|EdgeUp
DECL|function|GlyphCacheEntry
DECL|function|GlyphCacheEntry
DECL|function|QFontEngine
DECL|function|QFontEngineBox
DECL|function|QFontEngineBox
DECL|function|QFontEngineMulti
DECL|function|QFontEngineMultiBasicImpl
DECL|function|QFontEngineMultiBasicImpl
DECL|function|QFontEngine_startCollectingEngines
DECL|function|QFontEngine_stopCollectingEngines
DECL|function|QTestFontEngine
DECL|function|addBitmapFontToPath
DECL|function|addGlyphsToPath
DECL|function|addOutlineToPath
DECL|function|addOutlineToPath
DECL|function|addOutlineToPath
DECL|function|alphaMapForGlyph
DECL|function|alphaMapForGlyph
DECL|function|alphaMapForGlyph
DECL|function|alphaMapForGlyph
DECL|function|alphaMapForGlyph
DECL|function|alphaMapForGlyph
DECL|function|alphaMapForGlyph
DECL|function|alphaMapForGlyph
DECL|function|alphaMapForGlyph
DECL|function|alphaRGBMapForGlyph
DECL|function|alphaRGBMapForGlyph
DECL|function|ascent
DECL|function|ascent
DECL|function|averageCharWidth
DECL|function|averageCharWidth
DECL|function|bitmapForGlyph
DECL|function|boundingBox
DECL|function|boundingBox
DECL|function|boundingBox
DECL|function|boundingBox
DECL|function|boundingBox
DECL|function|canRender
DECL|function|canRender
DECL|function|canRender
DECL|function|clearGlyphCache
DECL|function|cloneWithSize
DECL|function|collectSingleContour
DECL|function|convertToPostscriptFontFamilyName
DECL|function|createMultiFontEngine
DECL|function|descent
DECL|function|descent
DECL|function|doKerning
DECL|function|doKerning
DECL|function|draw
DECL|function|ensureFallbackFamiliesQueried
DECL|function|getCMap
DECL|function|getGlyphBearings
DECL|function|getGlyphBearings
DECL|function|getGlyphPositions
DECL|function|getPointInOutline
DECL|function|getSfntTable
DECL|function|getSfntTableData
DECL|function|getTrueTypeGlyphIndex
DECL|function|getUnscaledGlyph
DECL|function|glyphCache
DECL|function|glyphCount
DECL|function|glyphIndex
DECL|function|glyphIndex
DECL|function|harfbuzzFace
DECL|function|harfbuzzFont
DECL|function|hasUnreliableGlyphOutline
DECL|function|hb_canRender
DECL|function|hb_freeFace
DECL|function|hb_getAdvances
DECL|function|hb_getFontMetric
DECL|function|hb_getGlyphMetrics
DECL|function|hb_getPointInOutline
DECL|function|hb_getSFntTable
DECL|function|hb_stringToGlyphs
DECL|function|highByte
DECL|function|init
DECL|function|kerning
DECL|function|lastRightBearing
DECL|function|leading
DECL|function|leading
DECL|function|lineThickness
DECL|function|lineThickness
DECL|function|loadEngine
DECL|function|loadKerningPairs
DECL|function|lockedAlphaMapForGlyph
DECL|function|maxCharWidth
DECL|function|maxCharWidth
DECL|function|minLeftBearing
DECL|function|minRightBearing
DECL|function|operator =
DECL|function|properties
DECL|function|qSafeFromBigEndian
DECL|function|qt_addBitmapToPath
DECL|function|qt_get_font_table_default
DECL|function|qt_useHarfbuzzNG
DECL|function|qtransform_equals_no_translate
DECL|function|recalcAdvances
DECL|function|recalcAdvances
DECL|function|removeGlyphFromCache
DECL|function|setFallbackFamiliesList
DECL|function|setGlyphCache
DECL|function|shouldLoadFontEngineForCharacter
DECL|function|stringToCMap
DECL|function|stringToCMap
DECL|function|stripped
DECL|function|subPixelPositionForX
DECL|function|supportsScript
DECL|function|supportsTransformation
DECL|function|tightBoundingBox
DECL|function|underlinePosition
DECL|function|underlinePosition
DECL|function|unlockAlphaMapForGlyph
DECL|function|xHeight
DECL|function|xHeight
DECL|function|~GlyphCacheEntry
DECL|function|~QFontEngine
DECL|function|~QFontEngineBox
DECL|function|~QFontEngineMulti
DECL|macro|GRID
DECL|macro|GRID
DECL|macro|SET
DECL|macro|SET
DECL|variable|enginesCollector
DECL|variable|hb_fontClass
DECL|variable|sizeof
DECL|variable|sizeof
