DECL|function|QFontEngineMultiQPA
DECL|function|QFontEngineQPA
DECL|function|addOutlineToPath
DECL|function|alphaMapForGlyph
DECL|function|ascent
DECL|function|boundingBox
DECL|function|boundingBox
DECL|function|canRender
DECL|function|descent
DECL|function|extractHeaderField
DECL|function|findGlyph
DECL|function|generate
DECL|function|getChar
DECL|function|getSfntTableData
DECL|function|isValid
DECL|function|leading
DECL|function|lineThickness
DECL|function|loadEngine
DECL|function|maxCharWidth
DECL|function|minLeftBearing
DECL|function|minRightBearing
DECL|function|readValue
DECL|function|recalcAdvances
DECL|function|stringToCMap
DECL|function|type
DECL|function|underlinePosition
DECL|function|verifyHeader
DECL|function|verifyTag
DECL|function|writeBlock
DECL|function|writeGMap
DECL|function|writeHeader
DECL|function|writeTaggedQFixed
DECL|function|writeTaggedString
DECL|function|writeTaggedUInt32
DECL|function|writeTaggedUInt8
DECL|function|~QFontEngineQPA
DECL|macro|DEBUG_VERIFY
DECL|macro|DEBUG_VERIFY
DECL|macro|READ_VERIFY
DECL|macro|VERIFY
DECL|macro|VERIFY_TAG
DECL|variable|tagTypes
