DECL|class|QFontDatabasePrivate
DECL|enumerator|Supported
DECL|enumerator|Unknown
DECL|enumerator|Unsupported
DECL|enumerator|UnsupportedFT
DECL|enum|WritingSystemStatus
DECL|function|Key
DECL|function|Key
DECL|function|Key
DECL|function|QFontDatabase
DECL|function|QFontDatabasePrivate
DECL|function|QtFontDesc
DECL|function|QtFontFamily
DECL|function|QtFontFoundry
DECL|function|QtFontStyle
DECL|function|addAppFont
DECL|function|addApplicationFont
DECL|function|addApplicationFontFromData
DECL|function|applicationFontFamilies
DECL|function|bestFoundry
DECL|function|bestStyle
DECL|function|bold
DECL|function|createDatabase
DECL|function|families
DECL|function|family
DECL|function|familyList
DECL|function|font
DECL|function|foundry
DECL|function|free
DECL|function|getEngineData
DECL|function|getFontWeight
DECL|function|hasFamily
DECL|function|initFontDef
DECL|function|invalidate
DECL|function|isApplicationFont
DECL|function|isBitmapScalable
DECL|function|isFixedPitch
DECL|function|isScalable
DECL|function|isSmoothlyScalable
DECL|function|italic
DECL|function|match
DECL|function|matchFamilyName
DECL|function|operator !=
DECL|function|operator <
DECL|function|operator ==
DECL|function|parseFontName
DECL|function|parseFontName
DECL|function|pixelSize
DECL|function|pointSizes
DECL|function|qt_cleanupFontDatabase
DECL|function|qt_fontdata_from_index
DECL|function|qt_fontdatabase_mutex
DECL|function|qt_mac_get_fixed_pitch
DECL|function|qt_script_for_writing_system
DECL|function|qt_setQtEnableTestFont
DECL|function|smoothSizes
DECL|function|standardSizes
DECL|function|style
DECL|function|styleString
DECL|function|styleString
DECL|function|styleStringHelper
DECL|function|styles
DECL|function|weight
DECL|function|weightFromInteger
DECL|function|writingSystemName
DECL|function|writingSystemSample
DECL|function|writingSystems
DECL|function|writingSystems
DECL|function|~QFontDatabasePrivate
DECL|function|~QtFontFamily
DECL|function|~QtFontFoundry
DECL|function|~QtFontStyle
DECL|macro|FD_DEBUG
DECL|macro|FD_DEBUG
DECL|macro|FM_DEBUG
DECL|macro|FM_DEBUG
DECL|macro|SMOOTH_SCALABLE
DECL|member|aliases
DECL|member|antialiased
DECL|member|applicationFonts
DECL|member|askedForFallback
DECL|member|avgwidth
DECL|member|bitmapScalable
DECL|member|bogusWritingSystems
DECL|member|count
DECL|member|count
DECL|member|count
DECL|member|count
DECL|member|data
DECL|member|encoding
DECL|member|encoding
DECL|member|fallbackFamilies
DECL|member|fallbackFamilies
DECL|member|families
DECL|member|families
DECL|member|family
DECL|member|familyIndex
DECL|member|fileName
DECL|member|fixedPitch
DECL|member|fixedPitchComputed
DECL|member|foundries
DECL|member|foundry
DECL|member|handle
DECL|member|key
DECL|member|name
DECL|member|name
DECL|member|pitch
DECL|member|pixelSize
DECL|member|pixelSizes
DECL|member|reregisterAppFonts
DECL|member|size
DECL|member|smoothScalable
DECL|member|stretch
DECL|member|style
DECL|member|style
DECL|member|styleName
DECL|member|styles
DECL|member|weight
DECL|member|writingSystems
DECL|member|xpoint
DECL|member|xres
DECL|member|yres
DECL|struct|ApplicationFont
DECL|struct|Key
DECL|struct|QtFontDesc
DECL|struct|QtFontEncoding
DECL|struct|QtFontFamily
DECL|struct|QtFontFoundry
DECL|struct|QtFontSize
DECL|struct|QtFontStyle
DECL|variable|qt_enable_test_font
DECL|variable|scriptForWritingSystem
