DECL|class|FriendlyResource
DECL|function|addQPF2File
DECL|function|children
DECL|function|findFont
DECL|function|initializeDb
DECL|function|isDir
DECL|function|isFile
DECL|function|load
DECL|function|load
DECL|function|loadEngine
DECL|function|loadFromCache
DECL|function|loadSingleEngine
DECL|function|qt_applyFontDatabaseSettings
DECL|function|qt_qws_init_fontdb
DECL|function|qwsFontPath
DECL|function|registerFont
DECL|function|removeAllApplicationFonts
DECL|function|removeApplicationFont
DECL|function|supportsThreadedFontRendering
DECL|macro|X_SIZE
DECL|macro|X_SIZE
DECL|macro|Y_SIZE
DECL|macro|Y_SIZE
DECL|variable|DatabaseVersion
