DECL|enumerator|HB_Err_Invalid_Argument
DECL|enumerator|HB_Err_Invalid_SubTable
DECL|enumerator|HB_Err_Invalid_SubTable_Format
DECL|enumerator|HB_Err_Not_Covered
DECL|enumerator|HB_Err_Ok
DECL|enumerator|HB_Err_Out_Of_Memory
DECL|enumerator|HB_Err_Read_Error
DECL|macro|QHARFBUZZ_COPY_P_H
DECL|member|clusterStart
DECL|member|combiningClass
DECL|member|dontPrint
DECL|member|justification
DECL|member|klass
DECL|member|mark
DECL|member|userData
DECL|member|x
DECL|member|x_ppem
DECL|member|x_scale
DECL|member|y
DECL|member|y_ppem
DECL|member|y_scale
DECL|member|zeroWidth
DECL|struct|HB_Font_
DECL|typedef|HB_16Dot16
DECL|typedef|HB_Error
DECL|typedef|HB_Face
DECL|typedef|HB_Fixed
DECL|typedef|HB_FixedPoint
DECL|typedef|HB_Font
DECL|typedef|HB_FontRec
DECL|typedef|HB_Glyph
DECL|typedef|HB_GlyphAttributes
DECL|typedef|HB_UShort
DECL|typedef|hb_bitfield
DECL|typedef|hb_bitfield
DECL|typedef|hb_uint32
