DECL|class|QWritingSystemsPrivate
DECL|function|QSupportedWritingSystems
DECL|function|QSupportedWritingSystems
DECL|function|QWritingSystemsPrivate
DECL|function|QWritingSystemsPrivate
DECL|function|addApplicationFont
DECL|function|defaultFont
DECL|function|defaultFonts
DECL|function|detach
DECL|function|fallbacksForFamily
DECL|function|fontDir
DECL|function|fontEngine
DECL|function|fontEngine
DECL|function|operator =
DECL|function|populateFontDatabase
DECL|function|registerFont
DECL|function|registerQPF2Font
DECL|function|releaseHandle
DECL|function|resolveFontFamilyAlias
DECL|function|setSupported
DECL|function|supported
DECL|function|~QSupportedWritingSystems
DECL|member|ref
DECL|member|vector
