DECL|class|CustomFontFileLoader
DECL|class|DirectWriteFontFileLoader
DECL|class|DirectWriteFontFileStream
DECL|class|EmbeddedFont
DECL|function|AddRef
DECL|function|AddRef
DECL|function|CreateStreamFromKey
DECL|function|CustomFontFileLoader
DECL|function|DirectWriteFontFileLoader
DECL|function|DirectWriteFontFileStream
DECL|function|EmbeddedFont
DECL|function|GetFileSize
DECL|function|GetLastWriteTime
DECL|function|QueryInterface
DECL|function|QueryInterface
DECL|function|ReadFileFragment
DECL|function|Release
DECL|function|Release
DECL|function|ReleaseFileFragment
DECL|function|addKey
DECL|function|addKey
DECL|function|changeFamilyName
DECL|function|data
DECL|function|familyName
DECL|function|loader
DECL|function|operator =
DECL|function|operator T
DECL|function|platformCleanUp
DECL|function|platformLoadFromData
DECL|function|removeKey
DECL|function|removeKey
DECL|function|tableDirectoryEntry
DECL|function|~CustomFontFileLoader
DECL|function|~DirectWriteFontFileLoader
DECL|function|~DirectWriteFontFileStream
DECL|member|avgCharWidth
DECL|member|breakChar
DECL|member|capHeight
DECL|member|checkSum
DECL|member|codepageRanges
DECL|member|count
DECL|member|data
DECL|member|defaultChar
DECL|member|encodingID
DECL|member|entrySelector
DECL|member|familyClass
DECL|member|firstCharIndex
DECL|member|format
DECL|member|height
DECL|member|identifier
DECL|member|languageID
DECL|member|lastCharIndex
DECL|member|length
DECL|member|length
DECL|member|m_directWriteFactory
DECL|member|m_directWriteFontFileLoader
DECL|member|m_fontData
DECL|member|m_fontData
DECL|member|m_fontDatas
DECL|member|m_referenceCount
DECL|member|m_referenceCount
DECL|member|maxContext
DECL|member|nameID
DECL|member|numTables
DECL|member|offset
DECL|member|offset
DECL|member|panose
DECL|member|platformID
DECL|member|rangeShift
DECL|member|scalerType
DECL|member|searchRange
DECL|member|selection
DECL|member|strikeOutPosition
DECL|member|strikeOutSize
DECL|member|stringOffset
DECL|member|subscriptXOffset
DECL|member|subscriptXSize
DECL|member|subscriptYOffset
DECL|member|subscriptYSize
DECL|member|superscriptXOffset
DECL|member|superscriptXSize
DECL|member|superscriptYOffset
DECL|member|superscriptYSize
DECL|member|type
DECL|member|typoAscender
DECL|member|typoDescender
DECL|member|typoLineGap
DECL|member|unicodeRanges
DECL|member|vendorID
DECL|member|version
DECL|member|weightClass
DECL|member|widthClass
DECL|member|winAscent
DECL|member|winDescent
DECL|struct|BigEndian
DECL|struct|NameRecord
DECL|struct|NameTable
DECL|struct|OS2Table
DECL|struct|OffsetSubTable
DECL|struct|TableDirectory
