DECL|class|DrawTextItemDevice
DECL|class|DrawTextItemRecorder
DECL|function|DrawTextItemDevice
DECL|function|DrawTextItemRecorder
DECL|function|QStaticText
DECL|function|QStaticText
DECL|function|QStaticText
DECL|function|QStaticTextPrivate
DECL|function|QStaticTextPrivate
DECL|function|begin
DECL|function|chars
DECL|function|chars
DECL|function|detach
DECL|function|drawPixmap
DECL|function|drawPolygon
DECL|function|drawTextItem
DECL|function|end
DECL|function|get
DECL|function|glyphs
DECL|function|glyphs
DECL|function|init
DECL|function|items
DECL|function|items
DECL|function|metric
DECL|function|operator !=
DECL|function|operator =
DECL|function|operator ==
DECL|function|paintEngine
DECL|function|paintText
DECL|function|performanceHint
DECL|function|positions
DECL|function|positions
DECL|function|prepare
DECL|function|setFontEngine
DECL|function|setPerformanceHint
DECL|function|setText
DECL|function|setTextFormat
DECL|function|setTextOption
DECL|function|setTextWidth
DECL|function|size
DECL|function|text
DECL|function|textFormat
DECL|function|textOption
DECL|function|textWidth
DECL|function|type
DECL|function|updateState
DECL|function|~DrawTextItemDevice
DECL|function|~QStaticText
DECL|function|~QStaticTextItem
DECL|function|~QStaticTextPrivate
DECL|member|m_chars
DECL|member|m_currentColor
DECL|member|m_dirtyPen
DECL|member|m_glyphs
DECL|member|m_items
DECL|member|m_paintEngine
DECL|member|m_positions
DECL|member|m_untransformedCoordinates
DECL|member|m_useBackendOptimizations
