DECL|class|QSyntaxHighlighterPrivate
DECL|function|QSyntaxHighlighter
DECL|function|QSyntaxHighlighter
DECL|function|QSyntaxHighlighterPrivate
DECL|function|_q_delayedRehighlight
DECL|function|_q_reformatBlocks
DECL|function|applyFormatChanges
DECL|function|currentBlock
DECL|function|currentBlockState
DECL|function|currentBlockUserData
DECL|function|document
DECL|function|format
DECL|function|previousBlockState
DECL|function|reformatBlock
DECL|function|reformatBlocks
DECL|function|rehighlight
DECL|function|rehighlight
DECL|function|rehighlightBlock
DECL|function|setCurrentBlockState
DECL|function|setCurrentBlockUserData
DECL|function|setDocument
DECL|function|setFormat
DECL|function|setFormat
DECL|function|setFormat
DECL|function|~QSyntaxHighlighter
DECL|member|currentBlock
DECL|member|doc
DECL|member|formatChanges
DECL|member|inReformatBlocks
DECL|member|rehighlightPending
