DECL|function|QTextCopyHelper
DECL|function|QTextDocumentFragment
DECL|function|QTextDocumentFragment
DECL|function|QTextDocumentFragment
DECL|function|QTextDocumentFragment
DECL|function|QTextDocumentFragmentPrivate
DECL|function|QTextHtmlImporter
DECL|function|appendBlock
DECL|function|appendFragment
DECL|function|appendFragments
DECL|function|appendNodeText
DECL|function|closeTag
DECL|function|convertFormatIndex
DECL|function|copy
DECL|function|fromHtml
DECL|function|fromHtml
DECL|function|fromPlainText
DECL|function|import
DECL|function|insert
DECL|function|isEmpty
DECL|function|nextListStyle
DECL|function|operator =
DECL|function|processBlockNode
DECL|function|processSpecialNodes
DECL|function|scanTable
DECL|function|toHtml
DECL|function|toPlainText
DECL|function|~QTextDocumentFragment
