DECL|function|GlyphInfo
DECL|function|LineBreakHelper
DECL|function|QTextLayout
DECL|function|QTextLayout
DECL|function|QTextLayout
DECL|function|QTextLayout
DECL|function|QTextLineItemIterator
DECL|function|addNextCluster
DECL|function|addSelectedRegionsToPath
DECL|function|additionalFormats
DECL|function|adjustPreviousRightBearing
DECL|function|adjustRightBearing
DECL|function|adjustRightBearing
DECL|function|alignLine
DECL|function|ascent
DECL|function|ascent
DECL|function|atEnd
DECL|function|beginLayout
DECL|function|boundingRect
DECL|function|cacheEnabled
DECL|function|calculateNewWidth
DECL|function|checkFullOtherwiseExtend
DECL|function|clearAdditionalFormats
DECL|function|clearLayout
DECL|function|clipIfValid
DECL|function|createLine
DECL|function|currentGlyph
DECL|function|cursorToX
DECL|function|descent
DECL|function|descent
DECL|function|draw
DECL|function|draw
DECL|function|drawCursor
DECL|function|drawCursor
DECL|function|drawMenuText
DECL|function|endLayout
DECL|function|font
DECL|function|format
DECL|function|formatIndex
DECL|function|getSelectionBounds
DECL|function|glyphs
DECL|function|glyphs
DECL|function|height
DECL|function|height
DECL|function|horizontalAdvance
DECL|function|isOutsideSelection
DECL|function|isValidCursorPosition
DECL|function|layout_helper
DECL|function|leading
DECL|function|leadingIncluded
DECL|function|lineAt
DECL|function|lineCount
DECL|function|lineForTextPosition
DECL|function|maximumWidth
DECL|function|minimumWidth
DECL|function|naturalTextRect
DECL|function|naturalTextWidth
DECL|function|next
DECL|function|nextCursorPosition
DECL|function|offsetInLigature
DECL|function|position
DECL|function|position
DECL|function|preeditAreaPosition
DECL|function|preeditAreaText
DECL|function|previousCursorPosition
DECL|function|rect
DECL|function|rect
DECL|function|resetRightBearing
DECL|function|saveCurrentGlyph
DECL|function|setAdditionalFormats
DECL|function|setAscent
DECL|function|setCacheEnabled
DECL|function|setDescent
DECL|function|setFlags
DECL|function|setFont
DECL|function|setLeadingIncluded
DECL|function|setLineWidth
DECL|function|setNumColumns
DECL|function|setNumColumns
DECL|function|setPenAndDrawBackground
DECL|function|setPosition
DECL|function|setPosition
DECL|function|setPreeditArea
DECL|function|setText
DECL|function|setTextOption
DECL|function|setWidth
DECL|function|text
DECL|function|textDirection
DECL|function|textLength
DECL|function|textOption
DECL|function|textPosition
DECL|function|textStart
DECL|function|width
DECL|function|width
DECL|function|x
DECL|function|xToCursor
DECL|function|y
DECL|function|~QTextLayout
DECL|macro|LB_DEBUG
DECL|macro|ObjectSelectionBrush
DECL|macro|SuppressBackground
DECL|macro|SuppressText
DECL|member|currentPosition
DECL|member|eng
DECL|member|firstItem
DECL|member|flags
DECL|member|fontEngine
DECL|member|glyphCount
DECL|member|glyphLayout
DECL|member|glyphs
DECL|member|glyphsEnd
DECL|member|glyphsStart
DECL|member|item
DECL|member|itemEnd
DECL|member|itemLength
DECL|member|itemPosition
DECL|member|itemStart
DECL|member|itemWidth
DECL|member|lastItem
DECL|member|levels
DECL|member|line
DECL|member|lineEnd
DECL|member|logClusters
DECL|member|logicalItem
DECL|member|manualWrap
DECL|member|maxGlyphs
DECL|member|minimumRightBearing
DECL|member|minw
DECL|member|nItems
DECL|member|pos_x
DECL|member|previousGlyph
DECL|member|rightBearing
DECL|member|selection
DECL|member|si
DECL|member|softHyphenWidth
DECL|member|spaceData
DECL|member|tmpData
DECL|member|visualOrder
DECL|member|whiteSpaceOrObject
DECL|member|x
DECL|struct|GlyphInfo
DECL|struct|LineBreakHelper
DECL|struct|QTextLineItemIterator
