DECL|function|QTextLength
DECL|function|Q_DECLARE_SHARED
DECL|function|Q_DECLARE_SHARED
DECL|function|Q_DECLARE_SHARED
DECL|function|Q_DECLARE_SHARED
DECL|function|Q_DECLARE_SHARED
DECL|function|Q_DECLARE_SHARED
DECL|function|Q_DECLARE_SHARED
DECL|function|Q_DECLARE_SHARED
DECL|function|bottomPadding
DECL|function|leftPadding
DECL|function|lineHeight
DECL|function|rightPadding
DECL|function|setAlignment
DECL|function|setBottomMargin
DECL|function|setBottomPadding
DECL|function|setCellPadding
DECL|function|setHeight
DECL|function|setHeight
DECL|function|setHeight
DECL|function|setIndent
DECL|function|setIndent
DECL|function|setLeftMargin
DECL|function|setLeftPadding
DECL|function|setNumberPrefix
DECL|function|setNumberSuffix
DECL|function|setPadding
DECL|function|setPadding
DECL|function|setRightMargin
DECL|function|setRightPadding
DECL|function|setTableCellColumnSpan
DECL|function|setTopMargin
DECL|function|setWidth
DECL|function|setWidth
DECL|function|topPadding
DECL|macro|QTEXTFORMAT_H
DECL|variable|QFont
DECL|variable|QString
DECL|variable|QTextBlockFormat
DECL|variable|QTextCharFormat
DECL|variable|QTextCursor
DECL|variable|QTextDocument
DECL|variable|QTextFormat
DECL|variable|QTextFormatCollection
DECL|variable|QTextFormatPrivate
DECL|variable|QTextFrameFormat
DECL|variable|QTextImageFormat
DECL|variable|QTextLength
DECL|variable|QTextListFormat
DECL|variable|QTextObject
DECL|variable|QTextTableCellFormat
DECL|variable|QTextTableFormat
DECL|variable|QVariant
