DECL|macro|QTEXTLAYOUT_H
DECL|variable|QFont
DECL|variable|QPaintDevice
DECL|variable|QPainter
DECL|variable|QPalette
DECL|variable|QRect
DECL|variable|QRegion
DECL|variable|QTextBlock
DECL|variable|QTextFormat
DECL|variable|QTextFormat
DECL|variable|QTextLine
DECL|variable|QTextOption
