DECL|enumerator|AdjustDown
DECL|enumerator|AdjustNext
DECL|enumerator|AdjustPrev
DECL|enumerator|AdjustUp
DECL|function|QTextCursor
DECL|function|QTextCursor
DECL|function|QTextCursor
DECL|function|QTextCursor
DECL|function|QTextCursor
DECL|function|QTextCursor
DECL|function|QTextCursor
DECL|function|QTextCursorPrivate
DECL|function|QTextCursorPrivate
DECL|function|aboutToRemoveCell
DECL|function|adjustCursor
DECL|function|adjustPosition
DECL|function|anchor
DECL|function|atBlockEnd
DECL|function|atBlockStart
DECL|function|atEnd
DECL|function|atStart
DECL|function|beginEditBlock
DECL|function|block
DECL|function|blockCharFormat
DECL|function|blockFormat
DECL|function|blockLayout
DECL|function|blockNumber
DECL|function|canDelete
DECL|function|charFormat
DECL|function|clearCells
DECL|function|clearSelection
DECL|function|columnNumber
DECL|function|complexSelectionTable
DECL|function|createList
DECL|function|createList
DECL|function|currentFrame
DECL|function|currentList
DECL|function|currentTable
DECL|function|deleteChar
DECL|function|deletePreviousChar
DECL|function|document
DECL|function|endEditBlock
DECL|function|getText
DECL|function|hasComplexSelection
DECL|function|hasSelection
DECL|function|insertBlock
DECL|function|insertBlock
DECL|function|insertBlock
DECL|function|insertBlock
DECL|function|insertFragment
DECL|function|insertFrame
DECL|function|insertHtml
DECL|function|insertImage
DECL|function|insertImage
DECL|function|insertImage
DECL|function|insertImage
DECL|function|insertList
DECL|function|insertList
DECL|function|insertTable
DECL|function|insertTable
DECL|function|insertText
DECL|function|insertText
DECL|function|isCopyOf
DECL|function|isNull
DECL|function|joinPreviousEditBlock
DECL|function|keepPositionOnInsert
DECL|function|mergeBlockCharFormat
DECL|function|mergeBlockFormat
DECL|function|mergeCharFormat
DECL|function|movePosition
DECL|function|movePosition
DECL|function|operator !=
DECL|function|operator <
DECL|function|operator <=
DECL|function|operator =
DECL|function|operator ==
DECL|function|operator >
DECL|function|operator >=
DECL|function|position
DECL|function|positionInBlock
DECL|function|remove
DECL|function|removeSelectedText
DECL|function|select
DECL|function|selectedTableCells
DECL|function|selectedTableCells
DECL|function|selectedText
DECL|function|selection
DECL|function|selectionEnd
DECL|function|selectionStart
DECL|function|setBlockCharFormat
DECL|function|setBlockCharFormat
DECL|function|setBlockCharFormatHelper
DECL|function|setBlockFormat
DECL|function|setBlockFormat
DECL|function|setCharFormat
DECL|function|setCharFormat
DECL|function|setKeepPositionOnInsert
DECL|function|setPosition
DECL|function|setVerticalMovementX
DECL|function|setVisualNavigation
DECL|function|setX
DECL|function|verticalMovementX
DECL|function|visualNavigation
DECL|function|~QTextCursor
DECL|function|~QTextCursorPrivate
