DECL|function|QFragmentFindHelper
DECL|function|QTextTable
DECL|function|appendColumns
DECL|function|appendRows
DECL|function|begin
DECL|function|cellAt
DECL|function|cellAt
DECL|function|cellAt
DECL|function|column
DECL|function|columnSpan
DECL|function|columns
DECL|function|createTable
DECL|function|end
DECL|function|findCellIndex
DECL|function|firstCursorPosition
DECL|function|firstPosition
DECL|function|format
DECL|function|fragmentAdded
DECL|function|fragmentRemoved
DECL|function|insertColumns
DECL|function|insertRows
DECL|function|lastCursorPosition
DECL|function|lastPosition
DECL|function|mergeCells
DECL|function|mergeCells
DECL|function|operator <
DECL|function|operator <
DECL|function|removeColumns
DECL|function|removeRows
DECL|function|resize
DECL|function|row
DECL|function|rowEnd
DECL|function|rowSpan
DECL|function|rowStart
DECL|function|rows
DECL|function|setFormat
DECL|function|setFormat
DECL|function|splitCell
DECL|function|tableCellFormatIndex
DECL|function|update
DECL|function|~QTextTable
DECL|function|~QTextTablePrivate
DECL|member|fragmentMap
DECL|member|pos
DECL|struct|QFragmentFindHelper
