DECL|class|Itemizer
DECL|enumerator|MaxBidiLevel
DECL|enumerator|MaxItemLength
DECL|function|FontEngineCache
DECL|function|Itemizer
DECL|function|LayoutData
DECL|function|LayoutData
DECL|function|QBidiControl
DECL|function|QBidiStatus
DECL|function|QStackTextEngine
DECL|function|QTextEngine
DECL|function|QTextEngine
DECL|function|QTextItemInt
DECL|function|QTextItemInt
DECL|function|QTextLineItemIterator
DECL|function|addRequiredBoundaries
DECL|function|alignLine
DECL|function|appendItems
DECL|function|atSpace
DECL|function|atWordSeparator
DECL|function|attributes
DECL|function|baseLevel
DECL|function|basicDirection
DECL|function|beginningOfLine
DECL|function|bidiItemize
DECL|function|bidiReorder
DECL|function|boundingBox
DECL|function|calculateTabWidth
DECL|function|canPop
DECL|function|clearLineData
DECL|function|direction
DECL|function|elidedText
DECL|function|embed
DECL|function|endOfLine
DECL|function|findItem
DECL|function|font
DECL|function|fontEngine
DECL|function|format
DECL|function|formatIndex
DECL|function|freeMemory
DECL|function|generate
DECL|function|generateScriptItems
DECL|function|generateScriptItemsAndChangeCase
DECL|function|generateScriptItemsCapitalize
DECL|function|generateScriptItemsSmallCaps
DECL|function|getSelectionBounds
DECL|function|grow
DECL|function|hasCaseChange
DECL|function|heuristicSetGlyphAttributes
DECL|function|indexAdditionalFormats
DECL|function|init
DECL|function|insertionPointsForLine
DECL|function|invalidate
DECL|function|isRightToLeft
DECL|function|itemize
DECL|function|justify
DECL|function|leadingSpaceWidth
DECL|function|lineNumberForTextPosition
DECL|function|midItem
DECL|function|moveGlyphData
DECL|function|next
DECL|function|nextCharJoins
DECL|function|nextLogicalPosition
DECL|function|offsetInLigature
DECL|function|pdf
DECL|function|positionAfterVisualMovement
DECL|function|prevCharJoins
DECL|function|previousLogicalPosition
DECL|function|qt_true_matrix
DECL|function|reallocate
DECL|function|releaseCachedFontEngine
DECL|function|resolveAdditionalFormats
DECL|function|set
DECL|function|setBoundary
DECL|function|setDefaultHeight
DECL|function|shape
DECL|function|shapeLine
DECL|function|shapeText
DECL|function|shapeTextWithCE
DECL|function|shapeTextWithHarfbuzz
DECL|function|splitItem
DECL|function|stringToGlyphs
DECL|function|tightBoundingBox
DECL|function|transformed
DECL|function|validate
DECL|function|width
DECL|function|~Itemizer
DECL|function|~LayoutData
DECL|function|~QTextEngine
DECL|macro|BIDI_DEBUG
DECL|member|base
DECL|member|cCtx
DECL|member|ctx
DECL|member|dir
DECL|member|eor
DECL|member|fontEngine
DECL|member|glyph
DECL|member|kashidaWidth
DECL|member|last
DECL|member|lastStrong
DECL|member|level
DECL|member|level
DECL|member|m_analysis
DECL|member|m_items
DECL|member|m_splitter
DECL|member|m_string
DECL|member|override
DECL|member|override
DECL|member|type
DECL|struct|QBidiControl
DECL|struct|QBidiStatus
DECL|struct|QJustificationPoint
DECL|variable|directions
