DECL|enumerator|JustifyKashida
DECL|enumerator|JustifyNone
DECL|enumerator|JustifySpace
DECL|enumerator|LineOrParagraphSeparator
DECL|enumerator|Lowercase
DECL|enumerator|None
DECL|enumerator|Object
DECL|enumerator|SmallCaps
DECL|enumerator|Space
DECL|enumerator|SpaceTabOrObject
DECL|enumerator|Tab
DECL|enumerator|TabOrObject
DECL|enumerator|Uppercase
DECL|enum|Flags
DECL|enum|JustificationType
DECL|function|QGlyphJustification
DECL|function|QGlyphLayout
DECL|function|QGlyphLayout
DECL|function|QScriptItem
DECL|function|QScriptItem
DECL|function|QScriptLine
DECL|function|base
DECL|function|clear
DECL|function|data
DECL|function|effectiveAdvance
DECL|function|glyph_metrics_t
DECL|function|glyph_metrics_t
DECL|function|height
DECL|function|height
DECL|function|instance
DECL|function|isValid
DECL|function|mid
DECL|function|operator
DECL|function|qIsControlChar
DECL|function|setInstance
DECL|function|spaceNeededForGlyphLayout
DECL|macro|QTEXTENGINE_P_H
DECL|member|advance
DECL|member|advances_x
DECL|member|advances_y
DECL|member|analysis
DECL|member|ascent
DECL|member|ascent
DECL|member|attributes
DECL|member|attributes
DECL|member|bidiLevel
DECL|member|descent
DECL|member|descent
DECL|member|flags
DECL|member|from
DECL|member|glyph
DECL|member|glyph_data_offset
DECL|member|glyphs
DECL|member|gridfitted
DECL|member|hasTrailingSpaces
DECL|member|height
DECL|member|justification
DECL|member|justifications
DECL|member|justified
DECL|member|leading
DECL|member|leading
DECL|member|leadingIncluded
DECL|member|length
DECL|member|nKashidas
DECL|member|numGlyphs
DECL|member|num_glyphs
DECL|member|offset
DECL|member|offsets
DECL|member|operator
DECL|member|operator
DECL|member|position
DECL|member|private
DECL|member|public
DECL|member|script
DECL|member|space_18d6
DECL|member|textAdvance
DECL|member|textWidth
DECL|member|type
DECL|member|width
DECL|member|width
DECL|member|width
DECL|member|x
DECL|member|x
DECL|member|xoff
DECL|member|y
DECL|member|y
DECL|member|yoff
DECL|struct|QGlyphJustification
DECL|struct|QGlyphLayout
DECL|struct|QGlyphLayout
DECL|struct|QGlyphLayoutInstance
DECL|struct|QScriptAnalysis
DECL|struct|QScriptItem
DECL|struct|QScriptLine
DECL|struct|glyph_metrics_t
DECL|typedef|QScriptItemArray
DECL|variable|QAbstractTextDocumentLayout
DECL|variable|QFontEngine
DECL|variable|QFontPrivate
DECL|variable|QFontPrivate
DECL|variable|QPainter
DECL|variable|QString
DECL|variable|QTextFormatCollection
