DECL|function|Calculator
DECL|function|abortOperation
DECL|function|addToMemory
DECL|function|additiveOperatorClicked
DECL|function|backspaceClicked
DECL|function|calculate
DECL|function|changeSignClicked
DECL|function|clear
DECL|function|clearAll
DECL|function|clearMemory
DECL|function|createButton
DECL|function|digitClicked
DECL|function|equalClicked
DECL|function|multiplicativeOperatorClicked
DECL|function|pointClicked
DECL|function|readMemory
DECL|function|setMemory
DECL|function|unaryOperatorClicked
