DECL|enumerator|BLACKBERRY
DECL|enumerator|QNX
DECL|enumerator|WINDOWS
DECL|enumerator|WINDOWS_CE
DECL|enum|Platforms
DECL|function|ArchData
DECL|function|ArchData
DECL|function|Configure
DECL|function|addDefine
DECL|function|appendMakeItem
DECL|function|applySpecSpecifics
DECL|function|autoDetection
DECL|function|buildQmake
DECL|function|checkAngleAvailability
DECL|function|checkAvailability
DECL|function|compilerSupportsFlag
DECL|function|defaultTo
DECL|function|desc
DECL|function|desc
DECL|function|desc
DECL|function|detectArch
DECL|function|displayConfig
DECL|function|displayHelp
DECL|function|filesDiffer
DECL|function|firstLicensePath
DECL|function|formatPath
DECL|function|formatPaths
DECL|function|generateBuildKey
DECL|function|generateCachefile
DECL|function|generateConfigfiles
DECL|function|generateHeaders
DECL|function|generateMakefiles
DECL|function|generateOutputVars
DECL|function|generateQConfigCpp
DECL|function|generateQConfigPri
DECL|function|generateSystemVars
DECL|function|isDone
DECL|function|isOk
DECL|function|locateFile
DECL|function|operator <<
DECL|function|parseCmdLine
DECL|function|platform
DECL|function|platformName
DECL|function|projectType
DECL|function|promptKeyPress
DECL|function|qpaPlatformName
DECL|function|readLicense
DECL|function|reloadCmdLine
DECL|function|saveCmdLine
DECL|function|showLicense
DECL|function|showSummary
DECL|function|stripPrefix
DECL|function|tokenLength
DECL|function|tryCompileProject
DECL|function|validateArgs
DECL|function|verifyConfiguration
DECL|function|writeToFile
DECL|function|~Configure
DECL|macro|MARK_OPTION
DECL|macro|for
DECL|member|key
DECL|member|qmakespec
DECL|member|subarchKey
DECL|member|type
DECL|struct|ArchData
