DECL|function|Configure
DECL|function|addDefine
DECL|function|appendMakeItem
DECL|function|applySpecSpecifics
DECL|function|autoDetection
DECL|function|buildHostTools
DECL|function|buildQmake
DECL|function|checkAvailability
DECL|function|defaultTo
DECL|function|desc
DECL|function|desc
DECL|function|desc
DECL|function|displayConfig
DECL|function|displayHelp
DECL|function|escapeSeparators
DECL|function|filesDiffer
DECL|function|findFile
DECL|function|findFileInPaths
DECL|function|findProjects
DECL|function|firstLicensePath
DECL|function|fixSeparators
DECL|function|generateBuildKey
DECL|function|generateCachefile
DECL|function|generateConfigfiles
DECL|function|generateHeaders
DECL|function|generateMakefiles
DECL|function|generateOutputVars
DECL|function|isDone
DECL|function|isOk
DECL|function|locateFile
DECL|function|locateFileInPaths
DECL|function|mingwPaths
DECL|function|operator <<
DECL|function|parseCmdLine
DECL|function|projectType
DECL|function|readLicense
DECL|function|reloadCmdLine
DECL|function|saveCmdLine
DECL|function|showLicense
DECL|function|showSummary
DECL|function|tokenLength
DECL|function|validateArgs
DECL|function|verifyConfiguration
DECL|function|writeToFile
DECL|function|~Configure
DECL|macro|MARK_OPTION
DECL|macro|for
