DECL|function|compilerFromQMakeSpec
DECL|function|compilerInfo
DECL|function|cpdir
DECL|function|detectCompiler
DECL|function|detectDirectXSdk
DECL|function|detectMinGW
DECL|function|detectQMakeSpec
DECL|function|execute
DECL|function|execute
DECL|function|findFileInPaths
DECL|function|headerPaths
DECL|function|libraryPaths
DECL|function|mingwPaths
DECL|function|path
DECL|function|qt_create_commandline
DECL|function|qt_create_environment
DECL|function|rmdir
DECL|function|splitPathList
DECL|member|compiler
DECL|member|compilerStr
DECL|member|detectedCompiler
DECL|member|executable
DECL|member|regKey
DECL|struct|CompilerInfo
DECL|variable|compiler_info
