DECL|enumerator|CC_BORLAND
DECL|enumerator|CC_INTEL
DECL|enumerator|CC_MINGW
DECL|enumerator|CC_MSVC2005
DECL|enumerator|CC_MSVC2008
DECL|enumerator|CC_MSVC2010
DECL|enumerator|CC_MSVC2012
DECL|enumerator|CC_MSVC2013
DECL|enumerator|CC_UNKNOWN
DECL|enum|Compiler
