DECL|class|QSequentialFile
DECL|class|tst_QIcoImageFormat
DECL|function|QSequentialFile
DECL|function|SequentialFile
DECL|function|SequentialFile_data
DECL|function|canRead
DECL|function|canRead_data
DECL|function|cleanup
DECL|function|cleanupTestCase
DECL|function|format
DECL|function|imageCount
DECL|function|imageCount_data
DECL|function|init
DECL|function|initTestCase
DECL|function|isSequential
DECL|function|jumpToNextImage
DECL|function|jumpToNextImage_data
DECL|function|loopCount
DECL|function|loopCount_data
DECL|function|nextImageDelay
DECL|function|nextImageDelay_data
DECL|function|pngCompression
DECL|function|pngCompression_data
DECL|function|tst_QIcoImageFormat
DECL|function|~QSequentialFile
DECL|function|~tst_QIcoImageFormat
DECL|macro|SRCDIR
DECL|macro|STRINGIFY
DECL|macro|TOSTRING
DECL|member|m_IconPath
