DECL|class|Notepad
DECL|function|Notepad
DECL|function|main
DECL|function|open
DECL|function|save
DECL|member|exitAction
DECL|member|fileMenu
DECL|member|openAction
DECL|member|saveAction
DECL|member|textEdit
