DECL|class|QLinuxInputMouseHandlerData
DECL|function|QLinuxInputMouseHandler
DECL|function|QLinuxInputMouseHandlerData
DECL|function|advanceCurrentPoint
DECL|function|currentMoved
DECL|function|currentPoint
DECL|function|currentState
DECL|function|ensureCurrentPoint
DECL|function|readMouseData
DECL|function|sendMouseEvent
DECL|function|setCurrentPoint
DECL|function|setCurrentState
DECL|function|setCurrentX
DECL|function|updateCurrentPos
DECL|function|~QLinuxInputMouseHandler
DECL|member|currentIdx
DECL|member|currentX
DECL|member|currentY
DECL|member|seenMT
DECL|member|state
DECL|member|touchPoints
