DECL|function|Window
DECL|function|Window
DECL|function|exposeEvent
DECL|function|initialize
DECL|function|keyPressEvent
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|render
DECL|function|resizeEvent
DECL|function|scheduleRender
DECL|function|timerEvent
DECL|function|wheelEvent
DECL|variable|colorIndexId
DECL|variable|colorTable
