DECL|class|DialogOptionsWidget
DECL|function|Dialog
DECL|function|DialogOptionsWidget
DECL|function|addCheckBox
DECL|function|addSpacer
DECL|function|criticalMessage
DECL|function|errorMessage
DECL|function|informationMessage
DECL|function|questionMessage
DECL|function|setColor
DECL|function|setDouble
DECL|function|setExistingDirectory
DECL|function|setFont
DECL|function|setInteger
DECL|function|setItem
DECL|function|setMultiLineText
DECL|function|setOpenFileName
DECL|function|setOpenFileNames
DECL|function|setSaveFileName
DECL|function|setText
DECL|function|value
DECL|function|warningMessage
DECL|macro|MESSAGE
DECL|member|checkBoxEntries
DECL|member|layout
DECL|typedef|CheckBoxEntry
