DECL|function|QAbstractSpinBox
DECL|function|QAbstractSpinBox
DECL|function|QAbstractSpinBoxPrivate
DECL|function|QSpinBoxValidator
DECL|function|_q_editorCursorPositionChanged
DECL|function|_q_editorTextChanged
DECL|function|alignment
DECL|function|bound
DECL|function|buttonSymbols
DECL|function|changeEvent
DECL|function|clear
DECL|function|clearCache
DECL|function|closeEvent
DECL|function|contextMenuEvent
DECL|function|correctionMode
DECL|function|emitSignals
DECL|function|event
DECL|function|fixup
DECL|function|fixup
DECL|function|focusInEvent
DECL|function|focusOutEvent
DECL|function|getZeroVariant
DECL|function|hasAcceptableInput
DECL|function|hasFrame
DECL|function|hideEvent
DECL|function|init
DECL|function|initStyleOption
DECL|function|inputMethodQuery
DECL|function|interpret
DECL|function|interpretText
DECL|function|isAccelerated
DECL|function|isReadOnly
DECL|function|keyPressEvent
DECL|function|keyReleaseEvent
DECL|function|keyboardTracking
DECL|function|lineEdit
DECL|function|minimumSizeHint
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|newHoverControl
DECL|function|operator *
DECL|function|operator +
DECL|function|operator -
DECL|function|operator /
DECL|function|paintEvent
DECL|function|reset
DECL|function|resizeEvent
DECL|function|selectAll
DECL|function|setAccelerated
DECL|function|setAlignment
DECL|function|setButtonSymbols
DECL|function|setCorrectionMode
DECL|function|setFrame
DECL|function|setKeyboardTracking
DECL|function|setLineEdit
DECL|function|setRange
DECL|function|setReadOnly
DECL|function|setSpecialValueText
DECL|function|setValue
DECL|function|setWrapping
DECL|function|showEvent
DECL|function|sizeHint
DECL|function|specialValue
DECL|function|specialValueText
DECL|function|stepBy
DECL|function|stepDown
DECL|function|stepEnabled
DECL|function|stepUp
DECL|function|stripped
DECL|function|text
DECL|function|textFromValue
DECL|function|timerEvent
DECL|function|updateEdit
DECL|function|updateEditFieldGeometry
DECL|function|updateHoverControl
DECL|function|updateState
DECL|function|validate
DECL|function|validate
DECL|function|valueFromText
DECL|function|variantBound
DECL|function|variantCompare
DECL|function|wheelEvent
DECL|function|wrapping
DECL|function|~QAbstractSpinBox
DECL|function|~QAbstractSpinBoxPrivate
DECL|macro|QASBDEBUG
DECL|macro|QASBDEBUG
