DECL|enumerator|StateFlagFloating
DECL|enumerator|StateFlagVisible
DECL|function|QDockAreaLayout
DECL|function|QDockAreaLayoutInfo
DECL|function|QDockAreaLayoutInfo
DECL|function|QDockAreaLayoutItem
DECL|function|QDockAreaLayoutItem
DECL|function|QDockAreaLayoutItem
DECL|function|QDockAreaLayoutItem
DECL|function|QPlaceHolderItem
DECL|function|addDockWidget
DECL|function|apply
DECL|function|apply
DECL|function|clear
DECL|function|clear
DECL|function|constrainedRect
DECL|function|currentTabId
DECL|function|deleteAllLayoutItems
DECL|function|deleteAllLayoutItems
DECL|function|dockPosHelper
DECL|function|dockedGeometry
DECL|function|expansive
DECL|function|expansive
DECL|function|findSeparator
DECL|function|findSeparator
DECL|function|fitItems
DECL|function|fitLayout
DECL|function|gapIndex
DECL|function|gapIndex
DECL|function|gapRect
DECL|function|getGrid
DECL|function|grow
DECL|function|hasFixedSize
DECL|function|hasFixedSize
DECL|function|indexOf
DECL|function|indexOf
DECL|function|indexOfPlaceHolder
DECL|function|indexOfPlaceHolder
DECL|function|info
DECL|function|info
DECL|function|info
DECL|function|info
DECL|function|info
DECL|function|insertGap
DECL|function|insertGap
DECL|function|isEmpty
DECL|function|isValid
DECL|function|item
DECL|function|item
DECL|function|itemAt
DECL|function|itemAt
DECL|function|itemRect
DECL|function|itemRect
DECL|function|itemRect
DECL|function|keepSize
DECL|function|mainWindowLayout
DECL|function|maximumSize
DECL|function|maximumSize
DECL|function|minimumSize
DECL|function|minimumSize
DECL|function|minimumSize
DECL|function|next
DECL|function|operator =
DECL|function|paintSep
DECL|function|paintSeparators
DECL|function|paintSeparators
DECL|function|plug
DECL|function|plug
DECL|function|prev
DECL|function|qMax
DECL|function|realMaxSize
DECL|function|realMinSize
DECL|function|remove
DECL|function|remove
DECL|function|restoreDockWidget
DECL|function|restoreState
DECL|function|restoreState
DECL|function|saveState
DECL|function|saveState
DECL|function|separatorMove
DECL|function|separatorMove
DECL|function|separatorMoveHelper
DECL|function|separatorRect
DECL|function|separatorRect
DECL|function|separatorRect
DECL|function|separatorRect
DECL|function|separatorRegion
DECL|function|separatorRegion
DECL|function|setCurrentTab
DECL|function|setCurrentTabId
DECL|function|setGrid
DECL|function|setTabBarShape
DECL|function|shrink
DECL|function|size
DECL|function|sizeHint
DECL|function|sizeHint
DECL|function|sizeHint
DECL|function|skip
DECL|function|split
DECL|function|splitDockWidget
DECL|function|styleChangedEvent
DECL|function|tab
DECL|function|tabBarMinimumSize
DECL|function|tabBarSizeHint
DECL|function|tabContentRect
DECL|function|tabId
DECL|function|tabifyDockWidget
DECL|function|takeAt
DECL|function|takeAt
DECL|function|toDockWidgetArea
DECL|function|unnest
DECL|function|unplug
DECL|function|unplug
DECL|function|updateSeparatorWidgets
DECL|function|updateSeparatorWidgets
DECL|function|updateTabBar
DECL|function|usedSeparatorWidgets
DECL|function|usedSeparatorWidgets
DECL|function|usedTabBars
DECL|function|usedTabBars
DECL|function|~QDockAreaLayoutItem
DECL|variable|zero
