DECL|class|QDockWidgetTitleButton
DECL|function|QDockWidget
DECL|function|QDockWidget
DECL|function|QDockWidgetItem
DECL|function|QDockWidgetLayout
DECL|function|QDockWidgetTitleButton
DECL|function|_q_toggleTopLevel
DECL|function|_q_toggleView
DECL|function|addItem
DECL|function|allowedAreas
DECL|function|changeEvent
DECL|function|closeEvent
DECL|function|count
DECL|function|endDrag
DECL|function|enterEvent
DECL|function|event
DECL|function|features
DECL|function|hasFeature
DECL|function|hasFeature
DECL|function|init
DECL|function|initDrag
DECL|function|initStyleOption
DECL|function|isAnimating
DECL|function|isXcb
DECL|function|itemAt
DECL|function|itemForRole
DECL|function|leaveEvent
DECL|function|maximumSize
DECL|function|maximumSize
DECL|function|minimumSize
DECL|function|minimumSize
DECL|function|minimumSizeHint
DECL|function|minimumTitleWidth
DECL|function|mouseDoubleClickEvent
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|moveEvent
DECL|function|nativeWindowDeco
DECL|function|nativeWindowDeco
DECL|function|nonClientAreaMouseEvent
DECL|function|paintEvent
DECL|function|paintEvent
DECL|function|perp
DECL|function|pick
DECL|function|plug
DECL|function|setAllowedAreas
DECL|function|setFeatures
DECL|function|setFloating
DECL|function|setGeometry
DECL|function|setTitleBarWidget
DECL|function|setVerticalTitleBar
DECL|function|setWidget
DECL|function|setWidgetForRole
DECL|function|setWindowState
DECL|function|sizeFromContent
DECL|function|sizeHint
DECL|function|sizeHint
DECL|function|sizeHint
DECL|function|startDrag
DECL|function|takeAt
DECL|function|titleBarWidget
DECL|function|titleHeight
DECL|function|toggleViewAction
DECL|function|unplug
DECL|function|updateButtons
DECL|function|widget
DECL|function|widgetForRole
DECL|function|~QDockWidget
DECL|function|~QDockWidgetLayout
