DECL|class|QGroupBoxPrivate
DECL|function|QGroupBox
DECL|function|QGroupBox
DECL|function|_q_fixFocus
DECL|function|_q_setChildrenEnabled
DECL|function|alignment
DECL|function|calculateFrame
DECL|function|changeEvent
DECL|function|childEvent
DECL|function|click
DECL|function|event
DECL|function|focusInEvent
DECL|function|init
DECL|function|initStyleOption
DECL|function|isCheckable
DECL|function|isChecked
DECL|function|isFlat
DECL|function|minimumSizeHint
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|paintEvent
DECL|function|resizeEvent
DECL|function|setAlignment
DECL|function|setCheckable
DECL|function|setChecked
DECL|function|setFlat
DECL|function|setTitle
DECL|function|title
DECL|function|~QGroupBox
DECL|member|align
DECL|member|checkable
DECL|member|checked
DECL|member|flat
DECL|member|hover
DECL|member|overCheckBox
DECL|member|pressedControl
DECL|member|shortcutId
DECL|member|title
