DECL|class|QMainWindowPrivate
DECL|function|QMainWindow
DECL|function|QMainWindowPrivate
DECL|function|addDockWidget
DECL|function|addDockWidget
DECL|function|addToolBar
DECL|function|addToolBar
DECL|function|addToolBar
DECL|function|addToolBarBreak
DECL|function|adjustCursor
DECL|function|centralWidget
DECL|function|checkDockWidgetArea
DECL|function|checkToolBarArea
DECL|function|contextMenuEvent
DECL|function|corner
DECL|function|createPopupMenu
DECL|function|dockOptions
DECL|function|dockWidgetArea
DECL|function|documentMode
DECL|function|event
DECL|function|iconSize
DECL|function|init
DECL|function|insertToolBar
DECL|function|insertToolBarBreak
DECL|function|isAnimated
DECL|function|isDockNestingEnabled
DECL|function|isSeparator
DECL|function|mainWindowLayout
DECL|function|menuBar
DECL|function|menuWidget
DECL|function|qt_mainwindow_layout
DECL|function|qt_setMainWindowTitleWidget
DECL|function|removeDockWidget
DECL|function|removeToolBar
DECL|function|removeToolBarBreak
DECL|function|restoreDockWidget
DECL|function|restoreState
DECL|function|saveState
DECL|function|separatorCursor
DECL|function|setAnimated
DECL|function|setCentralWidget
DECL|function|setCorner
DECL|function|setDockNestingEnabled
DECL|function|setDockOptions
DECL|function|setDocumentMode
DECL|function|setIconSize
DECL|function|setMenuBar
DECL|function|setMenuWidget
DECL|function|setStatusBar
DECL|function|setTabPosition
DECL|function|setTabShape
DECL|function|setToolButtonStyle
DECL|function|setUnifiedTitleAndToolBarOnMac
DECL|function|splitDockWidget
DECL|function|statusBar
DECL|function|tabPosition
DECL|function|tabShape
DECL|function|tabifiedDockWidgets
DECL|function|tabifyDockWidget
DECL|function|toolBarArea
DECL|function|toolBarBreak
DECL|function|toolButtonStyle
DECL|function|unifiedTitleAndToolBarOnMac
DECL|function|~QMainWindow
DECL|member|activateUnifiedToolbarAfterFullScreen
DECL|member|adjustedCursor
DECL|member|explicitIconSize
DECL|member|hoverPos
DECL|member|hoverSeparator
DECL|member|iconSize
DECL|member|layout
DECL|member|oldCursor
DECL|member|toolButtonStyle
DECL|member|useHIToolBar
