DECL|class|ControlLabel
DECL|class|ControllerWidget
DECL|function|ControlContainer
DECL|function|ControlLabel
DECL|function|ControllerWidget
DECL|function|QMdiSubWindow
DECL|function|QMdiSubWindowPrivate
DECL|function|_q_enterInteractiveMode
DECL|function|_q_processFocusChanged
DECL|function|_q_updateStaysOnTopHint
DECL|function|addToSystemMenu
DECL|function|changeEvent
DECL|function|childEvent
DECL|function|closeEvent
DECL|function|colorref2qrgb
DECL|function|contextMenuEvent
DECL|function|createSystemMenu
DECL|function|desktopPalette
DECL|function|drawTitleBarWhenMaximized
DECL|function|ensureWindowState
DECL|function|enterRubberBandMode
DECL|function|event
DECL|function|event
DECL|function|event
DECL|function|eventFilter
DECL|function|focusInEvent
DECL|function|focusOutEvent
DECL|function|getMoveDeltaComponent
DECL|function|getOperation
DECL|function|getRegion
DECL|function|getResizeDeltaComponent
DECL|function|getSubControl
DECL|function|hasVisibleControls
DECL|function|hideEvent
DECL|function|iconSize
DECL|function|initOperationMap
DECL|function|initStyleOption
DECL|function|isChildOfQMdiSubWindow
DECL|function|isChildOfTabbedQMdiArea
DECL|function|isHoverControl
DECL|function|isShaded
DECL|function|keyPressEvent
DECL|function|keyboardPageStep
DECL|function|keyboardSingleStep
DECL|function|leaveEvent
DECL|function|leaveEvent
DECL|function|leaveInteractiveMode
DECL|function|leaveRubberBandMode
DECL|function|maximizedButtonsWidget
DECL|function|maximizedSystemMenuIconWidget
DECL|function|mdiArea
DECL|function|menuBar
DECL|function|minimumSizeHint
DECL|function|mouseDoubleClickEvent
DECL|function|mouseDoubleClickEvent
DECL|function|mouseMoveEvent
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mousePressEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|mouseReleaseEvent
DECL|function|mouseReleaseEvent
DECL|function|moveEvent
DECL|function|originalWindowTitle
DECL|function|paintEvent
DECL|function|paintEvent
DECL|function|paintEvent
DECL|function|processClickedSubControl
DECL|function|ptr
DECL|function|removeBaseWidget
DECL|function|removeButtonsFromMenuBar
DECL|function|removeButtonsFromMenuBar
DECL|function|resizeEvent
DECL|function|restoreFocus
DECL|function|setActive
DECL|function|setControlVisible
DECL|function|setEnabled
DECL|function|setFocusWidget
DECL|function|setKeyboardPageStep
DECL|function|setKeyboardSingleStep
DECL|function|setMaximizeMode
DECL|function|setMinimizeMode
DECL|function|setNewGeometry
DECL|function|setNewWindowTitle
DECL|function|setNormalMode
DECL|function|setOption
DECL|function|setSizeGrip
DECL|function|setSizeGripVisible
DECL|function|setSystemMenu
DECL|function|setVisible
DECL|function|setWidget
DECL|function|setWindowFlags
DECL|function|showButtonsInMenuBar
DECL|function|showButtonsInMenuBar
DECL|function|showEvent
DECL|function|showShaded
DECL|function|showSystemMenu
DECL|function|showToolTip
DECL|function|sizeHint
DECL|function|sizeHint
DECL|function|sizeHint
DECL|function|sizeParameters
DECL|function|systemMenu
DECL|function|testOption
DECL|function|timerEvent
DECL|function|titleBarHeight
DECL|function|titleBarOptions
DECL|function|updateActions
DECL|function|updateCursor
DECL|function|updateDirtyRegions
DECL|function|updateGeometryConstraints
DECL|function|updateInternalWindowTitle
DECL|function|updateMask
DECL|function|updateWindowIcon
DECL|function|updateWindowIcon
DECL|function|updateWindowTitle
DECL|function|widget
DECL|function|~ControlContainer
DECL|function|~QMdiSubWindow
DECL|macro|COLOR_GRADIENTACTIVECAPTION
DECL|macro|COLOR_GRADIENTINACTIVECAPTION
DECL|macro|SPI_GETGRADIENTCAPTIONS
DECL|member|activeControl
DECL|member|hoverControl
DECL|member|isPressed
DECL|member|label
DECL|member|mdiArea
DECL|member|visibleControls
DECL|namespace|QMdi
DECL|namespace|QMdi
DECL|variable|BoundaryMargin
DECL|variable|CustomizeWindowFlags
DECL|variable|NumSubControls
DECL|variable|SubControls
