DECL|function|QMacMenuAction
DECL|function|QMenuMergeItem
DECL|function|QSymbianMenuAction
DECL|function|QWceMenuAction
DECL|macro|QMENU_P_H
DECL|macro|QT_SYMBIAN_FIRST_MENU_ITEM
DECL|macro|QT_SYMBIAN_LAST_MENU_ITEM
DECL|member|action
DECL|member|action
DECL|member|action
DECL|member|action
DECL|member|command
DECL|member|command
DECL|member|ignore_accel
DECL|member|menu
DECL|member|menuHandle
DECL|member|menuItem
DECL|member|menuItem
DECL|member|menuPane
DECL|member|merged
DECL|member|parent
DECL|struct|QMacMenuAction
DECL|struct|QMenuMergeItem
DECL|struct|QSymbianMenuAction
DECL|struct|QWceMenuAction
DECL|typedef|QMenuMergeList
DECL|variable|CEikMenuPane
DECL|variable|NSMenuItem
DECL|variable|QEventLoop
DECL|variable|QTornOffMenu
