DECL|class|QPlainTextDocumentLayoutPrivate
DECL|function|QPlainTextDocumentLayout
DECL|function|QPlainTextDocumentLayoutPrivate
DECL|function|QPlainTextEdit
DECL|function|QPlainTextEdit
DECL|function|QPlainTextEdit
DECL|function|QPlainTextEditControl
DECL|function|QPlainTextEditPrivate
DECL|function|_q_adjustScrollbars
DECL|function|_q_cursorPositionChanged
DECL|function|_q_repaintContents
DECL|function|_q_verticalScrollbarActionTriggered
DECL|function|anchorAt
DECL|function|append
DECL|function|appendHtml
DECL|function|appendPlainText
DECL|function|backgroundVisible
DECL|function|blockBoundingGeometry
DECL|function|blockBoundingRect
DECL|function|blockBoundingRect
DECL|function|blockBoundingRect
DECL|function|blockCount
DECL|function|blockWidth
DECL|function|canInsertFromMimeData
DECL|function|canInsertFromMimeData
DECL|function|canPaste
DECL|function|centerCursor
DECL|function|centerOnScroll
DECL|function|changeEvent
DECL|function|clear
DECL|function|contentOffset
DECL|function|contextMenuEvent
DECL|function|copy
DECL|function|createMimeDataFromSelection
DECL|function|createMimeDataFromSelection
DECL|function|createStandardContextMenu
DECL|function|currentCharFormat
DECL|function|cursorForPosition
DECL|function|cursorRect
DECL|function|cursorRect
DECL|function|cursorWidth
DECL|function|cursorWidth
DECL|function|cut
DECL|function|doSetTextCursor
DECL|function|document
DECL|function|documentChanged
DECL|function|documentSize
DECL|function|dragEnterEvent
DECL|function|dragLeaveEvent
DECL|function|dragMoveEvent
DECL|function|draw
DECL|function|dropEvent
DECL|function|ensureBlockLayout
DECL|function|ensureCursorVisible
DECL|function|ensureCursorVisible
DECL|function|ensureViewportLayouted
DECL|function|ensureVisible
DECL|function|event
DECL|function|extraSelections
DECL|function|fillBackground
DECL|function|find
DECL|function|firstVisibleBlock
DECL|function|firstVisibleBlock
DECL|function|focusInEvent
DECL|function|focusNextPrevChild
DECL|function|focusOutEvent
DECL|function|frameBoundingRect
DECL|function|getPaintContext
DECL|function|hitTest
DECL|function|hitTest
DECL|function|init
DECL|function|inputMethodEvent
DECL|function|inputMethodQuery
DECL|function|insertFromMimeData
DECL|function|insertFromMimeData
DECL|function|insertPlainText
DECL|function|isReadOnly
DECL|function|keyPressEvent
DECL|function|keyReleaseEvent
DECL|function|layoutBlock
DECL|function|lineWrapMode
DECL|function|loadResource
DECL|function|mergeCurrentCharFormat
DECL|function|mouseDoubleClickEvent
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|moveCursor
DECL|function|overwriteMode
DECL|function|pageCount
DECL|function|pageUpDown
DECL|function|paintEvent
DECL|function|paste
DECL|function|print
DECL|function|priv
DECL|function|redo
DECL|function|relayout
DECL|function|relayoutDocument
DECL|function|requestUpdate
DECL|function|resizeEvent
DECL|function|scrollContentsBy
DECL|function|selectAll
DECL|function|setBackgroundVisible
DECL|function|setCenterOnScroll
DECL|function|setCurrentCharFormat
DECL|function|setCursorWidth
DECL|function|setCursorWidth
DECL|function|setDocument
DECL|function|setExtraSelections
DECL|function|setLineWrapMode
DECL|function|setOverwriteMode
DECL|function|setPlainText
DECL|function|setReadOnly
DECL|function|setTabChangesFocus
DECL|function|setTabStopWidth
DECL|function|setTextCursor
DECL|function|setTextInteractionFlags
DECL|function|setTextWidth
DECL|function|setTopBlock
DECL|function|setTopLine
DECL|function|setWordWrapMode
DECL|function|shouldEnableInputMethod
DECL|function|showEvent
DECL|function|tabChangesFocus
DECL|function|tabStopWidth
DECL|function|textCursor
DECL|function|textInteractionFlags
DECL|function|textWidth
DECL|function|timerEvent
DECL|function|undo
DECL|function|updateDefaultTextOption
DECL|function|updateViewport
DECL|function|verticalOffset
DECL|function|verticalOffset
DECL|function|wheelEvent
DECL|function|wordWrapMode
DECL|function|zoomIn
DECL|function|zoomOut
DECL|function|~QPlainTextDocumentLayout
DECL|function|~QPlainTextEdit
DECL|member|blockCount
DECL|member|blockDocumentSizeChanged
DECL|member|blockUpdate
DECL|member|cursorWidth
DECL|member|mainViewPrivate
DECL|member|maximumWidth
DECL|member|maximumWidthBlockNumber
DECL|member|textLayoutFlags
DECL|member|width
