DECL|function|QScrollBar
DECL|function|QScrollBar
DECL|function|activateControl
DECL|function|contextMenuEvent
DECL|function|event
DECL|function|flash
DECL|function|hideEvent
DECL|function|init
DECL|function|initStyleOption
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|newHoverControl
DECL|function|paintEvent
DECL|function|pixelPosToRangeValue
DECL|function|qt_qscrollbarStyleOption
DECL|function|setTransient
DECL|function|sizeHint
DECL|function|sliderChange
DECL|function|stopRepeatAction
DECL|function|updateHoverControl
DECL|function|wheelEvent
DECL|function|~QScrollBar
DECL|macro|HORIZONTAL
DECL|macro|VERTICAL
