DECL|function|QScrollArea
DECL|function|QScrollArea
DECL|function|alignment
DECL|function|ensureVisible
DECL|function|ensureWidgetVisible
DECL|function|event
DECL|function|eventFilter
DECL|function|focusNextPrevChild
DECL|function|resizeEvent
DECL|function|scrollContentsBy
DECL|function|setAlignment
DECL|function|setWidget
DECL|function|setWidgetResizable
DECL|function|sizeHint
DECL|function|takeWidget
DECL|function|updateScrollBars
DECL|function|updateWidgetPosition
DECL|function|viewportSizeHint
DECL|function|widget
DECL|function|widgetResizable
DECL|function|~QScrollArea
