DECL|class|QDoubleSpinBoxPrivate
DECL|class|QSpinBoxPrivate
DECL|function|QDoubleSpinBox
DECL|function|QDoubleSpinBoxPrivate
DECL|function|QSpinBox
DECL|function|QSpinBoxPrivate
DECL|function|cleanText
DECL|function|cleanText
DECL|function|decimals
DECL|function|emitSignals
DECL|function|emitSignals
DECL|function|event
DECL|function|fixup
DECL|function|fixup
DECL|function|init
DECL|function|init
DECL|function|maximum
DECL|function|maximum
DECL|function|minimum
DECL|function|minimum
DECL|function|prefix
DECL|function|prefix
DECL|function|round
DECL|function|setDecimals
DECL|function|setMaximum
DECL|function|setMaximum
DECL|function|setMinimum
DECL|function|setMinimum
DECL|function|setPrefix
DECL|function|setPrefix
DECL|function|setRange
DECL|function|setRange
DECL|function|setSingleStep
DECL|function|setSingleStep
DECL|function|setSuffix
DECL|function|setSuffix
DECL|function|setValue
DECL|function|setValue
DECL|function|singleStep
DECL|function|singleStep
DECL|function|suffix
DECL|function|suffix
DECL|function|textFromValue
DECL|function|textFromValue
DECL|function|textFromValue
DECL|function|textFromValue
DECL|function|validate
DECL|function|validate
DECL|function|validateAndInterpret
DECL|function|validateAndInterpret
DECL|function|value
DECL|function|value
DECL|function|valueFromText
DECL|function|valueFromText
DECL|function|valueFromText
DECL|function|valueFromText
DECL|function|~QDoubleSpinBox
DECL|function|~QSpinBox
DECL|macro|QSBDEBUG
DECL|member|actualMax
DECL|member|actualMin
DECL|member|decimals
