DECL|class|QSplashScreenPrivate
DECL|function|QSplashScreen
DECL|function|QSplashScreen
DECL|function|QSplashScreenPrivate
DECL|function|clearMessage
DECL|function|drawContents
DECL|function|event
DECL|function|finish
DECL|function|message
DECL|function|mousePressEvent
DECL|function|pixmap
DECL|function|repaint
DECL|function|setPixmap
DECL|function|showMessage
DECL|function|waitForWindowExposed
DECL|function|~QSplashScreen
DECL|member|currAlign
DECL|member|currColor
DECL|member|currStatus
DECL|member|pixmap
