DECL|function|QSplitter
DECL|function|QSplitter
DECL|function|QSplitterHandle
DECL|function|addContribution
DECL|function|addWidget
DECL|function|adjustPos
DECL|function|changeEvent
DECL|function|childEvent
DECL|function|childrenCollapsible
DECL|function|closestLegalPosition
DECL|function|closestLegalPosition
DECL|function|collapsible
DECL|function|count
DECL|function|createHandle
DECL|function|doMove
DECL|function|doResize
DECL|function|event
DECL|function|event
DECL|function|findWidget
DECL|function|findWidgetJustBeforeOrJustAfter
DECL|function|getHandleSize
DECL|function|getRange
DECL|function|getRange
DECL|function|getWidgetSize
DECL|function|handle
DECL|function|handleWidth
DECL|function|indexOf
DECL|function|init
DECL|function|insertWidget
DECL|function|insertWidget
DECL|function|insertWidget_helper
DECL|function|isCollapsible
DECL|function|minimumSizeHint
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|moveSplitter
DECL|function|moveSplitter
DECL|function|opaqueResize
DECL|function|opaqueResize
DECL|function|operator <<
DECL|function|operator >>
DECL|function|orientation
DECL|function|orientation
DECL|function|paintEvent
DECL|function|recalc
DECL|function|refresh
DECL|function|resizeEvent
DECL|function|resizeEvent
DECL|function|restoreState
DECL|function|saveState
DECL|function|setChildrenCollapsible
DECL|function|setCollapsible
DECL|function|setGeo
DECL|function|setHandleWidth
DECL|function|setOpaqueResize
DECL|function|setOrientation
DECL|function|setOrientation
DECL|function|setRubberBand
DECL|function|setSizes
DECL|function|setSizes_helper
DECL|function|setStretchFactor
DECL|function|sizeHint
DECL|function|sizeHint
DECL|function|sizes
DECL|function|splitter
DECL|function|storeSizes
DECL|function|updateHandles
DECL|function|widget
DECL|function|~QSplitter
DECL|function|~QSplitterHandle
DECL|variable|SplitterMagic
