DECL|class|QStackedWidgetPrivate
DECL|function|QStackedWidget
DECL|function|QStackedWidgetPrivate
DECL|function|addWidget
DECL|function|count
DECL|function|currentIndex
DECL|function|currentWidget
DECL|function|event
DECL|function|indexOf
DECL|function|insertWidget
DECL|function|removeWidget
DECL|function|setCurrentIndex
DECL|function|setCurrentWidget
DECL|function|widget
DECL|function|~QStackedWidget
DECL|member|blockChildAdd
DECL|member|layout
