DECL|function|CloseButton
DECL|function|QTabBar
DECL|function|_q_closeTab
DECL|function|_q_scrollTabs
DECL|function|addTab
DECL|function|addTab
DECL|function|at
DECL|function|at
DECL|function|calculateNewPosition
DECL|function|changeEvent
DECL|function|computeElidedText
DECL|function|count
DECL|function|currentIndex
DECL|function|documentMode
DECL|function|drawBase
DECL|function|elideMode
DECL|function|enterEvent
DECL|function|event
DECL|function|expanding
DECL|function|extraWidth
DECL|function|hideEvent
DECL|function|iconSize
DECL|function|indexAtPos
DECL|function|init
DECL|function|initStyleOption
DECL|function|insertTab
DECL|function|insertTab
DECL|function|isMovable
DECL|function|isTabEnabled
DECL|function|keyPressEvent
DECL|function|layoutTab
DECL|function|layoutTabs
DECL|function|layoutWidgets
DECL|function|leaveEvent
DECL|function|makeVisible
DECL|function|minimumSizeHint
DECL|function|minimumTabSizeHint
DECL|function|mouseDoubleClickEvent
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|moveTab
DECL|function|moveTab
DECL|function|moveTabFinished
DECL|function|paintEvent
DECL|function|paintEvent
DECL|function|refresh
DECL|function|removeTab
DECL|function|resizeEvent
DECL|function|selectionBehaviorOnRemove
DECL|function|setCurrentIndex
DECL|function|setCurrentNextEnabledIndex
DECL|function|setDocumentMode
DECL|function|setDrawBase
DECL|function|setElideMode
DECL|function|setExpanding
DECL|function|setIconSize
DECL|function|setMovable
DECL|function|setSelectionBehaviorOnRemove
DECL|function|setShape
DECL|function|setTabButton
DECL|function|setTabData
DECL|function|setTabEnabled
DECL|function|setTabIcon
DECL|function|setTabText
DECL|function|setTabTextColor
DECL|function|setTabToolTip
DECL|function|setTabWhatsThis
DECL|function|setTabsClosable
DECL|function|setUsesScrollButtons
DECL|function|setupMovableTab
DECL|function|shape
DECL|function|showEvent
DECL|function|sizeHint
DECL|function|sizeHint
DECL|function|slide
DECL|function|tabAt
DECL|function|tabButton
DECL|function|tabData
DECL|function|tabIcon
DECL|function|tabInserted
DECL|function|tabLayoutChange
DECL|function|tabRect
DECL|function|tabRemoved
DECL|function|tabSizeHint
DECL|function|tabText
DECL|function|tabTextColor
DECL|function|tabToolTip
DECL|function|tabWhatsThis
DECL|function|tabsClosable
DECL|function|updateMacBorderMetrics
DECL|function|usesScrollButtons
DECL|function|verticalTabs
DECL|function|wheelEvent
DECL|function|~QTabBar
