DECL|class|QTabWidgetPrivate
DECL|function|QTabWidget
DECL|function|QTabWidgetPrivate
DECL|function|_q_removeTab
DECL|function|_q_showTab
DECL|function|_q_tabMoved
DECL|function|addTab
DECL|function|addTab
DECL|function|basicSize
DECL|function|changeEvent
DECL|function|clear
DECL|function|cornerWidget
DECL|function|count
DECL|function|currentIndex
DECL|function|currentWidget
DECL|function|documentMode
DECL|function|elideMode
DECL|function|event
DECL|function|hasHeightForWidth
DECL|function|heightForWidth
DECL|function|iconSize
DECL|function|indexOf
DECL|function|init
DECL|function|initStyleOption
DECL|function|insertTab
DECL|function|insertTab
DECL|function|isMovable
DECL|function|isTabEnabled
DECL|function|keyPressEvent
DECL|function|minimumSizeHint
DECL|function|paintEvent
DECL|function|removeTab
DECL|function|resizeEvent
DECL|function|setCornerWidget
DECL|function|setCurrentIndex
DECL|function|setCurrentWidget
DECL|function|setDocumentMode
DECL|function|setElideMode
DECL|function|setIconSize
DECL|function|setMovable
DECL|function|setTabBar
DECL|function|setTabEnabled
DECL|function|setTabIcon
DECL|function|setTabPosition
DECL|function|setTabShape
DECL|function|setTabText
DECL|function|setTabToolTip
DECL|function|setTabWhatsThis
DECL|function|setTabsClosable
DECL|function|setUpLayout
DECL|function|setUsesScrollButtons
DECL|function|showEvent
DECL|function|sizeHint
DECL|function|tabBar
DECL|function|tabIcon
DECL|function|tabInserted
DECL|function|tabPosition
DECL|function|tabRemoved
DECL|function|tabShape
DECL|function|tabText
DECL|function|tabToolTip
DECL|function|tabWhatsThis
DECL|function|tabsClosable
DECL|function|updateTabBarPosition
DECL|function|usesScrollButtons
DECL|function|widget
DECL|function|~QTabWidget
DECL|function|~QTabWidgetPrivate
DECL|member|alignment
DECL|member|dirty
DECL|member|leftCornerWidget
DECL|member|panelRect
DECL|member|pos
DECL|member|rightCornerWidget
DECL|member|shape
DECL|member|stack
DECL|member|tabs
