DECL|class|QTextBrowserPrivate
DECL|function|HistoryEntry
DECL|function|QTextBrowser
DECL|function|QTextBrowser
DECL|function|QTextBrowserPrivate
DECL|function|_q_activateAnchor
DECL|function|_q_documentModified
DECL|function|_q_highlightLink
DECL|function|backward
DECL|function|backwardHistoryCount
DECL|function|clearHistory
DECL|function|createHistoryEntry
DECL|function|event
DECL|function|findFile
DECL|function|focusNextPrevChild
DECL|function|focusOutEvent
DECL|function|forward
DECL|function|forwardHistoryCount
DECL|function|history
DECL|function|historyTitle
DECL|function|historyUrl
DECL|function|home
DECL|function|init
DECL|function|isBackwardAvailable
DECL|function|isForwardAvailable
DECL|function|keyPressEvent
DECL|function|keypadMove
DECL|function|loadResource
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|openExternalLinks
DECL|function|openLinks
DECL|function|paintEvent
DECL|function|reload
DECL|function|resolveUrl
DECL|function|resolveUrl
DECL|function|restoreHistoryEntry
DECL|function|searchPaths
DECL|function|setOpenExternalLinks
DECL|function|setOpenLinks
DECL|function|setSearchPaths
DECL|function|setSource
DECL|function|setSource
DECL|function|source
DECL|function|~QTextBrowser
DECL|member|currentURL
DECL|member|focusIndicatorAnchor
DECL|member|focusIndicatorPosition
DECL|member|forceLoadOnSourceChange
DECL|member|forwardStack
DECL|member|home
DECL|member|hpos
DECL|member|lastKeypadScrollValue
DECL|member|oldCursor
DECL|member|openExternalLinks
DECL|member|openLinks
DECL|member|prevFocus
DECL|member|searchPaths
DECL|member|stack
DECL|member|textOrSourceChanged
DECL|member|title
DECL|member|url
DECL|member|vpos
DECL|struct|HistoryEntry
