DECL|function|QToolBarItem
DECL|function|QToolBarLayout
DECL|function|addItem
DECL|function|checkUsePopupMenu
DECL|function|count
DECL|function|createItem
DECL|function|defaultWidgetAction
DECL|function|expandedSize
DECL|function|expandingDirections
DECL|function|hasExpandFlag
DECL|function|indexOf
DECL|function|insertAction
DECL|function|invalidate
DECL|function|isEmpty
DECL|function|isEmpty
DECL|function|itemAt
DECL|function|layoutActions
DECL|function|minimumSize
DECL|function|movable
DECL|function|setExpanded
DECL|function|setGeometry
DECL|function|setUsePopupMenu
DECL|function|sizeHint
DECL|function|takeAt
DECL|function|updateGeomArray
DECL|function|updateMarginAndSpacing
DECL|function|~QToolBarLayout
