DECL|class|QMDIControl
DECL|class|QWorkspaceChild
DECL|class|QWorkspacePrivate
DECL|class|QWorkspaceTitleBar
DECL|class|QWorkspaceTitleBarPrivate
DECL|enumerator|CloseAct
DECL|enumerator|MaximizeAct
DECL|enumerator|MinimizeAct
DECL|enumerator|MoveAct
DECL|enumerator|NCountAct
DECL|enumerator|ResizeAct
DECL|enumerator|RestoreAct
DECL|enumerator|ShadeAct
DECL|enumerator|StaysOnTopAct
DECL|enum|WSActs
DECL|function|QMDIControl
DECL|function|QWorkspace
DECL|function|QWorkspaceChild
DECL|function|QWorkspaceTitleBar
DECL|function|QWorkspaceTitleBarPrivate
DECL|function|_q_minimizeActiveWindow
DECL|function|_q_normalizeActiveWindow
DECL|function|_q_operationMenuActivated
DECL|function|_q_popupOperationMenu
DECL|function|_q_scrollBarChanged
DECL|function|_q_showOperationMenu
DECL|function|_q_updateActions
DECL|function|activate
DECL|function|activateNextWindow
DECL|function|activatePreviousWindow
DECL|function|activateWindow
DECL|function|activeWindow
DECL|function|addWindow
DECL|function|adjustToFullscreen
DECL|function|arrangeIcons
DECL|function|autoRaise
DECL|function|background
DECL|function|baseSize
DECL|function|cascade
DECL|function|changeEvent
DECL|function|changeEvent
DECL|function|childEvent
DECL|function|childEvent
DECL|function|closeActiveWindow
DECL|function|closeAllWindows
DECL|function|colorref2qrgb
DECL|function|contextMenuEvent
DECL|function|doMove
DECL|function|doResize
DECL|function|enterEvent
DECL|function|enterEvent
DECL|function|event
DECL|function|event
DECL|function|event
DECL|function|eventFilter
DECL|function|eventFilter
DECL|function|findChild
DECL|function|findMenuBar
DECL|function|frameWidth
DECL|function|hideChild
DECL|function|hideEvent
DECL|function|hideMaximizeControls
DECL|function|iconWidget
DECL|function|init
DECL|function|initStyleOption
DECL|function|initStyleOption
DECL|function|insertIcon
DECL|function|internalRaise
DECL|function|isActive
DECL|function|isActive
DECL|function|isChildOf
DECL|function|isMovable
DECL|function|isTool
DECL|function|isWindowOrIconVisible
DECL|function|leaveEvent
DECL|function|leaveEvent
DECL|function|leaveEvent
DECL|function|maximizeWindow
DECL|function|minimizeWindow
DECL|function|minimumSizeHint
DECL|function|mouseDoubleClickEvent
DECL|function|mouseMoveEvent
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|mouseReleaseEvent
DECL|function|moveEvent
DECL|function|normalizeWindow
DECL|function|paintEvent
DECL|function|paintEvent
DECL|function|paintEvent
DECL|function|paintEvent
DECL|function|place
DECL|function|readColors
DECL|function|removeIcon
DECL|function|resizeEvent
DECL|function|resizeEvent
DECL|function|scrollBarsEnabled
DECL|function|setActive
DECL|function|setActive
DECL|function|setActiveWindow
DECL|function|setAutoRaise
DECL|function|setBackground
DECL|function|setMovable
DECL|function|setScrollBarsEnabled
DECL|function|show
DECL|function|showEvent
DECL|function|showMaximizeControls
DECL|function|showMaximized
DECL|function|showMinimized
DECL|function|showNormal
DECL|function|showShaded
DECL|function|showWindow
DECL|function|sizeHint
DECL|function|sizeHint
DECL|function|sizeHint
DECL|function|sizeHint
DECL|function|tile
DECL|function|titleBarDoubleClicked
DECL|function|titleBarState
DECL|function|updateMask
DECL|function|updateWorkspace
DECL|function|usesActiveColor
DECL|function|wheelEvent
DECL|function|window
DECL|function|windowList
DECL|function|windowWidget
DECL|function|~QWorkspace
DECL|function|~QWorkspaceChild
DECL|function|~QWorkspaceTitleBar
DECL|macro|COLOR_GRADIENTACTIVECAPTION
DECL|macro|COLOR_GRADIENTINACTIVECAPTION
DECL|macro|SPI_GETGRADIENTCAPTIONS
DECL|member|actions
DECL|member|active
DECL|member|activeControl
DECL|member|background
DECL|member|becomeActive
DECL|member|buttonDown
DECL|member|childWidget
DECL|member|corner
DECL|member|flags
DECL|member|focus
DECL|member|hbar
DECL|member|hoverControl
DECL|member|icons
DECL|member|iconw
DECL|member|inTitleChange
DECL|member|lastControl
DECL|member|maxRestore
DECL|member|maxWindow
DECL|member|maxcontrols
DECL|member|maxmenubar
DECL|member|maxtools
DECL|member|moveOffset
DECL|member|popup
DECL|member|px
DECL|member|py
DECL|member|shadeRestore
DECL|member|shadeRestoreMin
DECL|member|shortcutMap
DECL|member|titlebar
DECL|member|toolPopup
DECL|member|topTitle
DECL|member|vbar
DECL|member|widgetResizeHandler
DECL|member|window
DECL|member|windowSize
DECL|member|windows
DECL|member|xoffset
DECL|member|yoffset
