DECL|function|MainWindow
DECL|function|copySelection
DECL|function|cutSelection
DECL|function|insertList
DECL|function|pasteSelection
DECL|function|selectBlock
DECL|function|selectFrame
DECL|function|selectLine
DECL|function|selectWord
DECL|function|updateMenus
