DECL|class|GraphicsView
DECL|class|PixmapWidget
DECL|class|PlaceWidget
DECL|function|GraphicsView
DECL|function|PixmapWidget
DECL|function|PlaceWidget
DECL|function|boundingRect
DECL|function|main
DECL|function|paint
DECL|function|resizeEvent
DECL|function|resizeEvent
DECL|function|setGeometry
DECL|function|setZValue
DECL|function|sizeHint
DECL|function|~PixmapWidget
DECL|member|original
DECL|member|original
DECL|member|r
DECL|member|scaled
DECL|member|w
