DECL|class|MyServer
DECL|function|MyServer
DECL|function|address
DECL|function|callArgs
DECL|function|callCount
DECL|function|complexProp
DECL|function|emitSignal
DECL|function|handleConnection
DECL|function|isConnected
DECL|function|main
DECL|function|prop1
DECL|function|reset
DECL|function|setComplexProp
DECL|function|setProp1
DECL|member|callArgs
DECL|member|callCount
DECL|member|m_conn
DECL|member|obj
DECL|variable|objectPath
DECL|variable|serviceName
