DECL|class|CloseEventTestWindow
DECL|class|CloseWidget
DECL|class|DeleteLaterWidget
DECL|class|EventLoopNester
DECL|class|EventSpy
DECL|class|LineEdit
DECL|class|MyInputContext
DECL|class|PromptOnCloseWidget
DECL|class|QuitOnLastWindowClosedDialog
DECL|class|QuitOnLastWindowClosedWindow
DECL|class|SendPostedEventsTester
DECL|class|TestApplication
DECL|class|TouchEventPropagationTestWidget
DECL|class|tst_QApplication
DECL|function|CloseEventTestWindow
DECL|function|CloseWidget
DECL|function|DeleteLaterWidget
DECL|function|LineEdit
DECL|function|MyInputContext
DECL|function|QString2cstrings
DECL|function|QuitOnLastWindowClosedDialog
DECL|function|QuitOnLastWindowClosedWindow
DECL|function|TestApplication
DECL|function|TouchEventPropagationTestWidget
DECL|function|alert
DECL|function|allWidgets
DECL|function|args
DECL|function|args_data
DECL|function|checkDeleteLater
DECL|function|childDeleted
DECL|function|cleanup
DECL|function|closeAllWindows
DECL|function|closeEvent
DECL|function|closeEvent
DECL|function|cstrings2QString
DECL|function|deleteLaterAndEnterLoop
DECL|function|deleteLaterAndExitLoop
DECL|function|deleteLaterAndProcessEvents1
DECL|function|deleteLaterAndProcessEvents2
DECL|function|desktopSettingsAware
DECL|function|doTest
DECL|function|event
DECL|function|event
DECL|function|eventFilter
DECL|function|execAfterExit
DECL|function|execDialogThenShow
DECL|function|focusChanged
DECL|function|focusInEvent
DECL|function|focusOut
DECL|function|focusOutEvent
DECL|function|getSetCheck
DECL|function|globalStaticObjectDestruction
DECL|function|identifierName
DECL|function|init
DECL|function|isComposing
DECL|function|isPathListIncluded
DECL|function|language
DECL|function|lastWindowClosed
DECL|function|libraryPaths
DECL|function|libraryPaths_qt_plugin_path
DECL|function|libraryPaths_qt_plugin_path_2
DECL|function|main
DECL|function|multiple
DECL|function|multiple_data
DECL|function|nonGui
DECL|function|ok_clicked
DECL|function|processEventsOnly
DECL|function|processEventsWithDeferredDeletion
DECL|function|qtbug_12673
DECL|function|quitOnLastWindowClosed
DECL|function|reset
DECL|function|reset
DECL|function|runTest
DECL|function|sendEventsOnProcessEvents
DECL|function|sendPostedEvents
DECL|function|sendPostedEventsWithDeferredDelete
DECL|function|setActiveWindow
DECL|function|setAttribute
DECL|function|setFont
DECL|function|setFont_data
DECL|function|staticSetup
DECL|function|style
DECL|function|task109149
DECL|function|testDeleteLater
DECL|function|testDeleteLaterProcessEvents
DECL|function|thread
DECL|function|timerEvent
DECL|function|timerEvent
DECL|function|topLevelWidgets
DECL|function|touchEventPropagation
DECL|function|tst_QApplication
DECL|function|wheelScrollLines
DECL|function|windowsCommandLine
DECL|function|windowsCommandLine_data
DECL|function|~tst_QApplication
DECL|macro|QT_TST_QAPP_DEBUG
DECL|member|acceptMouseEvent
DECL|member|acceptTouchEvent
DECL|member|app
DECL|member|child_deleted
DECL|member|eventSpy
DECL|member|okButton
DECL|member|recordedEvents
DECL|member|seenMouseEvent
DECL|member|seenTouchEvent
DECL|variable|argv0
