DECL|class|tst_QLibrary
DECL|enumerator|DontSetFileName
DECL|enumerator|Load
DECL|enumerator|OperationMask
DECL|enumerator|Resolve
DECL|enumerator|Unload
DECL|enum|QLibraryOperation
DECL|function|errorString
DECL|function|errorString_data
DECL|function|fileName
DECL|function|fileName_data
DECL|function|isLibrary
DECL|function|isLibrary_data
DECL|function|library_data
DECL|function|load
DECL|function|loadHints
DECL|function|loadHints_data
DECL|function|load_data
DECL|function|multipleInstancesForOneLibrary
DECL|function|resolve
DECL|function|resolve_data
DECL|function|sys_qualifiedLibraryName
DECL|function|tst_QLibrary
DECL|function|unload
DECL|function|unload_after_implicit_load
DECL|function|unload_data
DECL|function|version
DECL|function|version_data
DECL|function|~tst_QLibrary
DECL|macro|DLL_VALID
DECL|macro|DLL_VALID
DECL|macro|DLL_VALID
DECL|macro|PREFIX
DECL|macro|PREFIX
DECL|macro|PREFIX
DECL|macro|PREFIX
DECL|macro|PREFIX
DECL|macro|PREFIX
DECL|macro|SUFFIX
DECL|macro|SUFFIX
DECL|macro|SUFFIX
DECL|macro|SUFFIX
DECL|macro|SUFFIX
DECL|macro|SUFFIX
DECL|macro|a_VALID
DECL|macro|a_VALID
DECL|macro|a_VALID
DECL|macro|bundle_VALID
DECL|macro|bundle_VALID
DECL|macro|bundle_VALID
DECL|macro|dll_VALID
DECL|macro|dll_VALID
DECL|macro|dll_VALID
DECL|macro|dylib_VALID
DECL|macro|dylib_VALID
DECL|macro|dylib_VALID
DECL|macro|sl_VALID
DECL|macro|sl_VALID
DECL|macro|sl_VALID
DECL|macro|so_VALID
DECL|macro|so_VALID
DECL|macro|so_VALID
DECL|macro|so_VALID
DECL|macro|so_VALID
DECL|macro|so_VALID
DECL|macro|so_VALID
DECL|macro|so_VALID
DECL|macro|so_VALID
DECL|member|app
DECL|typedef|VersionFunction
