DECL|class|QScriptLocalServer
DECL|class|QScriptLocalSocket
DECL|function|QScriptLocalServer
DECL|function|QScriptLocalSocket
DECL|function|_q_ScriptRegisterQObjectMetaType
DECL|function|_q_ScriptValueFromQObject
DECL|function|_q_ScriptValueToQObject
DECL|function|close
DECL|function|connectToServer
DECL|function|errorString
DECL|function|errorString
DECL|function|interactive
DECL|function|isConnected
DECL|function|listen
DECL|function|main
DECL|function|nextConnection
DECL|function|open
DECL|function|readLine
DECL|function|serverName
DECL|function|sleep
DECL|function|waitForBytesWritten
DECL|function|waitForConnected
DECL|function|waitForNewConnection
DECL|function|waitForReadyRead
DECL|function|write
DECL|member|lc
