DECL|class|Counter
DECL|class|Counter
DECL|function|Counter
DECL|function|Counter
DECL|function|cacheObject
DECL|function|decrement
DECL|function|decrement
DECL|function|increment
DECL|function|increment
DECL|function|main
DECL|function|removeFromCache
DECL|function|run
DECL|function|value
DECL|function|value
DECL|macro|Counter
DECL|macro|Counter
DECL|macro|Counter
DECL|member|mutex
DECL|member|n
DECL|member|n
DECL|typedef|SomeClass
DECL|variable|caches
