DECL|function|PaintedWindow
DECL|function|exposeEvent
DECL|function|mousePressEvent
DECL|function|orientationChanged
DECL|function|paint
DECL|function|paint
DECL|function|resizeEvent
DECL|function|rotationDone
DECL|function|setRotation
