DECL|class|QGL2GradientCacheWrapper
DECL|function|QGL2GradientCache
DECL|function|addCacheElement
DECL|function|cacheForContext
DECL|function|cacheForContext
DECL|function|cleanCache
DECL|function|freeResource
DECL|function|generateGradientColorTable
DECL|function|getBuffer
DECL|function|invalidateResource
DECL|function|qtToGlColor
DECL|function|~QGL2GradientCache
DECL|member|m_mutex
DECL|member|m_resource
