DECL|class|QOpenGLStaticTextUserData
DECL|function|QGL2PaintEngineEx
DECL|function|QOpenGL2PaintEngineState
DECL|function|QOpenGL2PaintEngineState
DECL|function|QOpenGLStaticTextUserData
DECL|function|begin
DECL|function|beginNativePainting
DECL|function|brushChanged
DECL|function|brushOriginChanged
DECL|function|cleanupVectorPath
DECL|function|clearClip
DECL|function|clip
DECL|function|clipEnabledChanged
DECL|function|composite
DECL|function|compositionModeChanged
DECL|function|createState
DECL|function|drawCachedGlyphs
DECL|function|drawImage
DECL|function|drawPixmap
DECL|function|drawPixmapFragments
DECL|function|drawPixmapFragments
DECL|function|drawStaticTextItem
DECL|function|drawTextItem
DECL|function|drawTexture
DECL|function|drawTexture
DECL|function|drawVertexArrays
DECL|function|end
DECL|function|endNativePainting
DECL|function|ensureActive
DECL|function|fill
DECL|function|fill
DECL|function|fillStencilWithVertexArray
DECL|function|invalidateState
DECL|function|isNativePaintingActive
DECL|function|opacityChanged
DECL|function|penChanged
DECL|function|prepareForDraw
DECL|function|qt_premultiplyColor
DECL|function|regenerateClip
DECL|function|renderHintsChanged
DECL|function|resetClipIfNeeded
DECL|function|resetGLState
DECL|function|scaleRect
DECL|function|setBrush
DECL|function|setCoords
DECL|function|setScissor
DECL|function|setState
DECL|function|shouldDrawCachedGlyphs
DECL|function|stroke
DECL|function|stroke
DECL|function|systemStateChanged
DECL|function|transferMode
DECL|function|transformChanged
DECL|function|updateBrushTexture
DECL|function|updateBrushUniforms
DECL|function|updateClipScissorTest
DECL|function|updateCompositionMode
DECL|function|updateMatrix
DECL|function|updateTextureFilter
DECL|function|useSimpleShader
DECL|function|writeClip
DECL|function|~QGL2PaintEngineEx
DECL|function|~QGL2PaintEngineExPrivate
DECL|function|~QOpenGL2PaintEngineState
DECL|function|~QOpenGLStaticTextUserData
DECL|macro|GL_FRAMEBUFFER_SRGB
DECL|macro|GL_MIRRORED_REPEAT_IBM
DECL|member|cacheSerialNumber
DECL|member|cacheSize
DECL|member|glyphType
DECL|member|ibo
DECL|member|indexCount
DECL|member|indexType
DECL|member|iscale
DECL|member|primitiveType
DECL|member|textureCoordinateArray
DECL|member|vbo
DECL|member|vertexCoordinateArray
DECL|member|vertexCount
DECL|struct|QGL2PEVectorPathCache
