DECL|function|QGLGlyphTexture
DECL|function|freeResource
DECL|function|invalidateResource
DECL|macro|QTEXTUREGLYPHCACHE_GL_P_H
DECL|member|m_fbo
DECL|member|m_height
DECL|member|m_texture
DECL|member|m_width
DECL|struct|QGLSharedResource
DECL|variable|QGL2PaintEngineExPrivate
