DECL|function|QMacInputContext
DECL|function|cleanup
DECL|function|createTextDocument
DECL|function|globalEventProcessor
DECL|function|initialize
DECL|function|language
DECL|function|mouseHandler
DECL|function|setFocusWidget
DECL|function|setLastKeydownEvent
DECL|function|~QMacInputContext
DECL|macro|typeByteCount
DECL|macro|typeRefCon
