DECL|function|VibraModeChanged
DECL|function|VibraStatusChanged
DECL|function|XQVibraPrivate
DECL|function|currentStatus
DECL|function|error
DECL|function|setIntensity
DECL|function|start
DECL|function|stop
DECL|function|~XQVibraPrivate
DECL|variable|KDefaultIntensity
