DECL|class|QOpenGLBufferPrivate
DECL|function|QOpenGLBuffer
DECL|function|QOpenGLBuffer
DECL|function|QOpenGLBuffer
DECL|function|QOpenGLBufferPrivate
DECL|function|allocate
DECL|function|bind
DECL|function|bufferId
DECL|function|create
DECL|function|destroy
DECL|function|freeBufferFunc
DECL|function|isCreated
DECL|function|map
DECL|function|operator =
DECL|function|read
DECL|function|release
DECL|function|release
DECL|function|setUsagePattern
DECL|function|size
DECL|function|type
DECL|function|unmap
DECL|function|usagePattern
DECL|function|write
DECL|function|~QOpenGLBuffer
DECL|member|actualUsagePattern
DECL|member|funcs
DECL|member|guard
DECL|member|ref
DECL|member|type
DECL|member|usagePattern
