DECL|function|glAccum
DECL|function|glAlphaFunc
DECL|function|glAreTexturesResident
DECL|function|glArrayElement
DECL|function|glBegin
DECL|function|glBindTexture
DECL|function|glBitmap
DECL|function|glBlendColor
DECL|function|glBlendEquation
DECL|function|glBlendFunc
DECL|function|glCallList
DECL|function|glCallLists
DECL|function|glClear
DECL|function|glClearAccum
DECL|function|glClearColor
DECL|function|glClearDepth
DECL|function|glClearIndex
DECL|function|glClearStencil
DECL|function|glClipPlane
DECL|function|glColor3b
DECL|function|glColor3bv
DECL|function|glColor3d
DECL|function|glColor3dv
DECL|function|glColor3f
DECL|function|glColor3fv
DECL|function|glColor3i
DECL|function|glColor3iv
DECL|function|glColor3s
DECL|function|glColor3sv
DECL|function|glColor3ub
DECL|function|glColor3ubv
DECL|function|glColor3ui
DECL|function|glColor3uiv
DECL|function|glColor3us
DECL|function|glColor3usv
DECL|function|glColor4b
DECL|function|glColor4bv
DECL|function|glColor4d
DECL|function|glColor4dv
DECL|function|glColor4f
DECL|function|glColor4fv
DECL|function|glColor4i
DECL|function|glColor4iv
DECL|function|glColor4s
DECL|function|glColor4sv
DECL|function|glColor4ub
DECL|function|glColor4ubv
DECL|function|glColor4ui
DECL|function|glColor4uiv
DECL|function|glColor4us
DECL|function|glColor4usv
DECL|function|glColorMask
DECL|function|glColorMaterial
DECL|function|glColorPointer
DECL|function|glColorSubTable
DECL|function|glColorTable
DECL|function|glColorTableParameterfv
DECL|function|glColorTableParameteriv
DECL|function|glConvolutionFilter1D
DECL|function|glConvolutionFilter2D
DECL|function|glConvolutionParameterf
DECL|function|glConvolutionParameterfv
DECL|function|glConvolutionParameteri
DECL|function|glConvolutionParameteriv
DECL|function|glCopyColorSubTable
DECL|function|glCopyColorTable
DECL|function|glCopyConvolutionFilter1D
DECL|function|glCopyConvolutionFilter2D
DECL|function|glCopyPixels
DECL|function|glCopyTexImage1D
DECL|function|glCopyTexImage2D
DECL|function|glCopyTexSubImage1D
DECL|function|glCopyTexSubImage2D
DECL|function|glCopyTexSubImage3D
DECL|function|glCullFace
DECL|function|glDeleteLists
DECL|function|glDeleteTextures
DECL|function|glDepthFunc
DECL|function|glDepthMask
DECL|function|glDepthRange
DECL|function|glDisable
DECL|function|glDisableClientState
DECL|function|glDrawArrays
DECL|function|glDrawBuffer
DECL|function|glDrawElements
DECL|function|glDrawPixels
DECL|function|glDrawRangeElements
DECL|function|glEdgeFlag
DECL|function|glEdgeFlagPointer
DECL|function|glEdgeFlagv
DECL|function|glEnable
DECL|function|glEnableClientState
DECL|function|glEnd
DECL|function|glEndList
DECL|function|glEvalCoord1d
DECL|function|glEvalCoord1dv
DECL|function|glEvalCoord1f
DECL|function|glEvalCoord1fv
DECL|function|glEvalCoord2d
DECL|function|glEvalCoord2dv
DECL|function|glEvalCoord2f
DECL|function|glEvalCoord2fv
DECL|function|glEvalMesh1
DECL|function|glEvalMesh2
DECL|function|glEvalPoint1
DECL|function|glEvalPoint2
DECL|function|glFeedbackBuffer
DECL|function|glFinish
DECL|function|glFlush
DECL|function|glFogf
DECL|function|glFogfv
DECL|function|glFogi
DECL|function|glFogiv
DECL|function|glFrontFace
DECL|function|glFrustum
DECL|function|glGenLists
DECL|function|glGenTextures
DECL|function|glGetBooleanv
DECL|function|glGetClipPlane
DECL|function|glGetColorTable
DECL|function|glGetColorTableParameterfv
DECL|function|glGetColorTableParameteriv
DECL|function|glGetConvolutionFilter
DECL|function|glGetConvolutionParameterfv
DECL|function|glGetConvolutionParameteriv
DECL|function|glGetDoublev
DECL|function|glGetError
DECL|function|glGetFloatv
DECL|function|glGetHistogram
DECL|function|glGetHistogramParameterfv
DECL|function|glGetHistogramParameteriv
DECL|function|glGetIntegerv
DECL|function|glGetLightfv
DECL|function|glGetLightiv
DECL|function|glGetMapdv
DECL|function|glGetMapfv
DECL|function|glGetMapiv
DECL|function|glGetMaterialfv
DECL|function|glGetMaterialiv
DECL|function|glGetMinmax
DECL|function|glGetMinmaxParameterfv
DECL|function|glGetMinmaxParameteriv
DECL|function|glGetPixelMapfv
DECL|function|glGetPixelMapuiv
DECL|function|glGetPixelMapusv
DECL|function|glGetPointerv
DECL|function|glGetPolygonStipple
DECL|function|glGetSeparableFilter
DECL|function|glGetString
DECL|function|glGetTexEnvfv
DECL|function|glGetTexEnviv
DECL|function|glGetTexGendv
DECL|function|glGetTexGenfv
DECL|function|glGetTexGeniv
DECL|function|glGetTexImage
DECL|function|glGetTexLevelParameterfv
DECL|function|glGetTexLevelParameteriv
DECL|function|glGetTexParameterfv
DECL|function|glGetTexParameteriv
DECL|function|glHint
DECL|function|glHistogram
DECL|function|glIndexMask
DECL|function|glIndexPointer
DECL|function|glIndexd
DECL|function|glIndexdv
DECL|function|glIndexf
DECL|function|glIndexfv
DECL|function|glIndexi
DECL|function|glIndexiv
DECL|function|glIndexs
DECL|function|glIndexsv
DECL|function|glIndexub
DECL|function|glIndexubv
DECL|function|glInitNames
DECL|function|glInterleavedArrays
DECL|function|glIsEnabled
DECL|function|glIsList
DECL|function|glIsTexture
DECL|function|glLightModelf
DECL|function|glLightModelfv
DECL|function|glLightModeli
DECL|function|glLightModeliv
DECL|function|glLightf
DECL|function|glLightfv
DECL|function|glLighti
DECL|function|glLightiv
DECL|function|glLineStipple
DECL|function|glLineWidth
DECL|function|glListBase
DECL|function|glLoadIdentity
DECL|function|glLoadMatrixd
DECL|function|glLoadMatrixf
DECL|function|glLoadName
DECL|function|glLogicOp
DECL|function|glMap1d
DECL|function|glMap1f
DECL|function|glMap2d
DECL|function|glMap2f
DECL|function|glMapGrid1d
DECL|function|glMapGrid1f
DECL|function|glMapGrid2d
DECL|function|glMapGrid2f
DECL|function|glMaterialf
DECL|function|glMaterialfv
DECL|function|glMateriali
DECL|function|glMaterialiv
DECL|function|glMatrixMode
DECL|function|glMinmax
DECL|function|glMultMatrixd
DECL|function|glMultMatrixf
DECL|function|glNewList
DECL|function|glNormal3b
DECL|function|glNormal3bv
DECL|function|glNormal3d
DECL|function|glNormal3dv
DECL|function|glNormal3f
DECL|function|glNormal3fv
DECL|function|glNormal3i
DECL|function|glNormal3iv
DECL|function|glNormal3s
DECL|function|glNormal3sv
DECL|function|glNormalPointer
DECL|function|glOrtho
DECL|function|glPassThrough
DECL|function|glPixelMapfv
DECL|function|glPixelMapuiv
DECL|function|glPixelMapusv
DECL|function|glPixelStoref
DECL|function|glPixelStorei
DECL|function|glPixelTransferf
DECL|function|glPixelTransferi
DECL|function|glPixelZoom
DECL|function|glPointSize
DECL|function|glPolygonMode
DECL|function|glPolygonOffset
DECL|function|glPolygonStipple
DECL|function|glPopAttrib
DECL|function|glPopClientAttrib
DECL|function|glPopMatrix
DECL|function|glPopName
DECL|function|glPrioritizeTextures
DECL|function|glPushAttrib
DECL|function|glPushClientAttrib
DECL|function|glPushMatrix
DECL|function|glPushName
DECL|function|glRasterPos2d
DECL|function|glRasterPos2dv
DECL|function|glRasterPos2f
DECL|function|glRasterPos2fv
DECL|function|glRasterPos2i
DECL|function|glRasterPos2iv
DECL|function|glRasterPos2s
DECL|function|glRasterPos2sv
DECL|function|glRasterPos3d
DECL|function|glRasterPos3dv
DECL|function|glRasterPos3f
DECL|function|glRasterPos3fv
DECL|function|glRasterPos3i
DECL|function|glRasterPos3iv
DECL|function|glRasterPos3s
DECL|function|glRasterPos3sv
DECL|function|glRasterPos4d
DECL|function|glRasterPos4dv
DECL|function|glRasterPos4f
DECL|function|glRasterPos4fv
DECL|function|glRasterPos4i
DECL|function|glRasterPos4iv
DECL|function|glRasterPos4s
DECL|function|glRasterPos4sv
DECL|function|glReadBuffer
DECL|function|glReadPixels
DECL|function|glRectd
DECL|function|glRectdv
DECL|function|glRectf
DECL|function|glRectfv
DECL|function|glRecti
DECL|function|glRectiv
DECL|function|glRects
DECL|function|glRectsv
DECL|function|glRenderMode
DECL|function|glResetHistogram
DECL|function|glResetMinmax
DECL|function|glRotated
DECL|function|glRotatef
DECL|function|glScaled
DECL|function|glScalef
DECL|function|glScissor
DECL|function|glSelectBuffer
DECL|function|glSeparableFilter2D
DECL|function|glShadeModel
DECL|function|glStencilFunc
DECL|function|glStencilMask
DECL|function|glStencilOp
DECL|function|glTexCoord1d
DECL|function|glTexCoord1dv
DECL|function|glTexCoord1f
DECL|function|glTexCoord1fv
DECL|function|glTexCoord1i
DECL|function|glTexCoord1iv
DECL|function|glTexCoord1s
DECL|function|glTexCoord1sv
DECL|function|glTexCoord2d
DECL|function|glTexCoord2dv
DECL|function|glTexCoord2f
DECL|function|glTexCoord2fv
DECL|function|glTexCoord2i
DECL|function|glTexCoord2iv
DECL|function|glTexCoord2s
DECL|function|glTexCoord2sv
DECL|function|glTexCoord3d
DECL|function|glTexCoord3dv
DECL|function|glTexCoord3f
DECL|function|glTexCoord3fv
DECL|function|glTexCoord3i
DECL|function|glTexCoord3iv
DECL|function|glTexCoord3s
DECL|function|glTexCoord3sv
DECL|function|glTexCoord4d
DECL|function|glTexCoord4dv
DECL|function|glTexCoord4f
DECL|function|glTexCoord4fv
DECL|function|glTexCoord4i
DECL|function|glTexCoord4iv
DECL|function|glTexCoord4s
DECL|function|glTexCoord4sv
DECL|function|glTexCoordPointer
DECL|function|glTexEnvf
DECL|function|glTexEnvfv
DECL|function|glTexEnvi
DECL|function|glTexEnviv
DECL|function|glTexGend
DECL|function|glTexGendv
DECL|function|glTexGenf
DECL|function|glTexGenfv
DECL|function|glTexGeni
DECL|function|glTexGeniv
DECL|function|glTexImage1D
DECL|function|glTexImage2D
DECL|function|glTexImage3D
DECL|function|glTexParameterf
DECL|function|glTexParameterfv
DECL|function|glTexParameteri
DECL|function|glTexParameteriv
DECL|function|glTexSubImage1D
DECL|function|glTexSubImage2D
DECL|function|glTexSubImage3D
DECL|function|glTranslated
DECL|function|glTranslatef
DECL|function|glVertex2d
DECL|function|glVertex2dv
DECL|function|glVertex2f
DECL|function|glVertex2fv
DECL|function|glVertex2i
DECL|function|glVertex2iv
DECL|function|glVertex2s
DECL|function|glVertex2sv
DECL|function|glVertex3d
DECL|function|glVertex3dv
DECL|function|glVertex3f
DECL|function|glVertex3fv
DECL|function|glVertex3i
DECL|function|glVertex3iv
DECL|function|glVertex3s
DECL|function|glVertex3sv
DECL|function|glVertex4d
DECL|function|glVertex4dv
DECL|function|glVertex4f
DECL|function|glVertex4fv
DECL|function|glVertex4i
DECL|function|glVertex4iv
DECL|function|glVertex4s
DECL|function|glVertex4sv
DECL|function|glVertexPointer
DECL|function|glViewport
DECL|macro|QOPENGLVERSIONFUNCTIONS_1_2_H
