DECL|class|QOpenGLTextureBlitterPrivate
DECL|class|TextureBinder
DECL|enumerator|Identity
DECL|enumerator|IdentityFlipped
DECL|enumerator|TEXTURE_2D
DECL|enumerator|TEXTURE_EXTERNAL_OES
DECL|enumerator|User
DECL|enum|ProgramIndex
DECL|enum|TextureMatrixUniform
DECL|function|Program
DECL|function|QOpenGLTextureBlitter
DECL|function|QOpenGLTextureBlitterPrivate
DECL|function|TextureBinder
DECL|function|bind
DECL|function|blit
DECL|function|blit
DECL|function|blit
DECL|function|blit
DECL|function|buildProgram
DECL|function|create
DECL|function|destroy
DECL|function|isCreated
DECL|function|prepareProgram
DECL|function|release
DECL|function|setOpacity
DECL|function|setSwizzleRB
DECL|function|sourceTransform
DECL|function|supportsExternalOESTarget
DECL|function|targetToProgramIndex
DECL|function|targetTransform
DECL|function|~QOpenGLTextureBlitter
DECL|function|~TextureBinder
DECL|macro|GL_TEXTURE_EXTERNAL_OES
DECL|member|currentTarget
DECL|member|glProgram
DECL|member|m_target
DECL|member|opacity
DECL|member|opacity
DECL|member|opacityUniformPos
DECL|member|programs
DECL|member|swizzle
DECL|member|swizzle
DECL|member|swizzleUniformPos
DECL|member|textureBuffer
DECL|member|textureCoordAttribPos
DECL|member|textureMatrixUniformState
DECL|member|textureTransformUniformPos
DECL|member|vao
DECL|member|vertexBuffer
DECL|member|vertexCoordAttribPos
DECL|member|vertexTransformUniformPos
DECL|struct|Program
DECL|variable|fragment_shader
DECL|variable|fragment_shader150
DECL|variable|fragment_shader_external_oes
DECL|variable|texture_buffer_data
DECL|variable|vertex_buffer_data
DECL|variable|vertex_shader
DECL|variable|vertex_shader150
