DECL|macro|APIENTRY
DECL|macro|APIENTRYP
DECL|macro|GLAPI
DECL|macro|GLEXT_64_TYPES_DEFINED
DECL|macro|GL_DOUBLE
DECL|macro|GL_DO_NOT_WARN_IF_MULTI_GL_VERSION_HEADERS_INCLUDED
DECL|macro|GL_GLEXT_LEGACY
DECL|macro|QOPENGLF_APIENTRY
DECL|macro|QOPENGLF_APIENTRY
DECL|macro|QOPENGLF_APIENTRYP
DECL|macro|QOPENGLF_APIENTRYP
DECL|macro|QOPENGL_H
DECL|macro|QT_OPENGL_3
DECL|typedef|GLDEBUGPROC
DECL|typedef|GLDEBUGPROCAMD
DECL|typedef|GLDEBUGPROCARB
DECL|typedef|GLchar
DECL|typedef|GLchar
DECL|typedef|GLcharARB
DECL|typedef|GLdouble
DECL|typedef|GLhalfARB
DECL|typedef|GLhalfNV
DECL|typedef|GLhandleARB
DECL|typedef|GLint64
DECL|typedef|GLint64EXT
DECL|typedef|GLintptr
DECL|typedef|GLintptrARB
DECL|typedef|GLsizeiptr
DECL|typedef|GLsizeiptrARB
DECL|typedef|GLsync
DECL|typedef|GLuint64
DECL|typedef|GLuint64EXT
DECL|typedef|GLvdpauSurfaceNV
DECL|typedef|int32_t
DECL|typedef|int32_t
DECL|typedef|int64_t
DECL|typedef|int64_t
DECL|typedef|int64_t
DECL|typedef|int64_t
DECL|typedef|qopengl_GLintptr
DECL|typedef|qopengl_GLsizeiptr
DECL|typedef|uint64_t
DECL|typedef|uint64_t
DECL|typedef|uint64_t
DECL|typedef|uint64_t
