DECL|function|QOpenGLFunctions_4_3_Compatibility
DECL|function|initializeOpenGLFunctions
DECL|function|isContextCompatible
DECL|function|versionProfile
DECL|function|~QOpenGLFunctions_4_3_Compatibility
