DECL|enumerator|CoreStatus
DECL|enumerator|DeprecatedStatus
DECL|enumerator|InvalidStatus
DECL|enum|OpenGLStatus
DECL|function|QOpenGLVersionStatus
DECL|function|QOpenGLVersionStatus
DECL|function|get
DECL|function|operator
DECL|function|operator
DECL|macro|QOPENGLVERSIONFUNCTIONS_H
DECL|macro|QOPENGL_DEPRECATEDFUNCTION
DECL|member|status
DECL|member|version
DECL|struct|QOpenGLVersionStatus
DECL|variable|QAbstractOpenGLFunctions
DECL|variable|QOpenGLContext
