DECL|function|QOpenGLTexture
DECL|function|QOpenGLTexture
DECL|function|QOpenGLTexturePrivate
DECL|function|allocateImmutableStorage
DECL|function|allocateMutableStorage
DECL|function|allocateStorage
DECL|function|allocateStorage
DECL|function|allocateStorage
DECL|function|bind
DECL|function|bind
DECL|function|bind
DECL|function|bind
DECL|function|borderColor
DECL|function|borderColor
DECL|function|borderColor
DECL|function|borderColor
DECL|function|boundTextureId
DECL|function|boundTextureId
DECL|function|create
DECL|function|create
DECL|function|createTextureView
DECL|function|createTextureView
DECL|function|depth
DECL|function|depthStencilMode
DECL|function|destroy
DECL|function|destroy
DECL|function|evaluateMipLevels
DECL|function|faces
DECL|function|format
DECL|function|generateMipMaps
DECL|function|generateMipMaps
DECL|function|hasFeature
DECL|function|height
DECL|function|initializeOpenGLFunctions
DECL|function|isAutoMipMapGenerationEnabled
DECL|function|isBound
DECL|function|isBound
DECL|function|isBound
DECL|function|isBound
DECL|function|isCreated
DECL|function|isFixedSamplePositions
DECL|function|isSizedTextureFormat
DECL|function|isStorageAllocated
DECL|function|isTextureView
DECL|function|layers
DECL|function|levelOfDetailRange
DECL|function|levelofDetailBias
DECL|function|magnificationFilter
DECL|function|maximumAnisotropy
DECL|function|maximumLevelOfDetail
DECL|function|maximumMipLevels
DECL|function|minMagFilters
DECL|function|minificationFilter
DECL|function|minimumLevelOfDetail
DECL|function|mipBaseLevel
DECL|function|mipLevelRange
DECL|function|mipLevels
DECL|function|mipMaxLevel
DECL|function|pixelFormatCompatibleWithInternalFormat
DECL|function|pixelTypeCompatibleWithInternalFormat
DECL|function|release
DECL|function|release
DECL|function|release
DECL|function|release
DECL|function|samples
DECL|function|setAutoMipMapGenerationEnabled
DECL|function|setBorderColor
DECL|function|setBorderColor
DECL|function|setBorderColor
DECL|function|setBorderColor
DECL|function|setCompressedData
DECL|function|setCompressedData
DECL|function|setCompressedData
DECL|function|setCompressedData
DECL|function|setCompressedData
DECL|function|setCompressedData
DECL|function|setCompressedData
DECL|function|setCompressedData
DECL|function|setCompressedData
DECL|function|setData
DECL|function|setData
DECL|function|setData
DECL|function|setData
DECL|function|setData
DECL|function|setData
DECL|function|setData
DECL|function|setData
DECL|function|setData
DECL|function|setData
DECL|function|setDepthStencilMode
DECL|function|setFixedSamplePositions
DECL|function|setFormat
DECL|function|setLayers
DECL|function|setLevelOfDetailRange
DECL|function|setLevelofDetailBias
DECL|function|setMagnificationFilter
DECL|function|setMaximumAnisotropy
DECL|function|setMaximumLevelOfDetail
DECL|function|setMinMagFilters
DECL|function|setMinificationFilter
DECL|function|setMinimumLevelOfDetail
DECL|function|setMipBaseLevel
DECL|function|setMipLevelRange
DECL|function|setMipLevels
DECL|function|setMipMaxLevel
DECL|function|setSamples
DECL|function|setSize
DECL|function|setSwizzleMask
DECL|function|setSwizzleMask
DECL|function|setWrapMode
DECL|function|setWrapMode
DECL|function|setWrapMode
DECL|function|setWrapMode
DECL|function|swizzleMask
DECL|function|target
DECL|function|textureId
DECL|function|width
DECL|function|wrapMode
DECL|function|wrapMode
DECL|function|~QOpenGLTexture
DECL|function|~QOpenGLTexturePrivate
DECL|macro|GL_TEXTURE_WRAP_R
