DECL|enumerator|Equals
DECL|enumerator|GreaterEqualThan
DECL|enumerator|GreaterThan
DECL|enumerator|LessEqualThan
DECL|enumerator|LessThan
DECL|enumerator|NotEqual
DECL|enum|Operator
DECL|function|QOpenGLExtensionMatcher
DECL|function|VersionTerm
DECL|function|contains
DECL|function|descriptionKey
DECL|function|deviceIdKey
DECL|function|driverDescriptionKey
DECL|function|driverVersionKey
DECL|function|exceptionsKey
DECL|function|featuresKey
DECL|function|fromContext
DECL|function|fromJson
DECL|function|fromJson
DECL|function|glVendorKey
DECL|function|gpuFeatures
DECL|function|gpuFeatures
DECL|function|gpuFeatures
DECL|function|gpuFeatures
DECL|function|hostKernelVersion
DECL|function|hostOs
DECL|function|idKey
DECL|function|isNull
DECL|function|isNull
DECL|function|matches
DECL|function|matches
DECL|function|matches
DECL|function|msgSyntaxWarning
DECL|function|opKey
DECL|function|operator <<
DECL|function|osKey
DECL|function|qgpu_features
DECL|function|readGpuFeatures
DECL|function|readGpuFeatures
DECL|function|readGpuFeatures
DECL|function|typeKey
DECL|function|valueKey
DECL|function|vendorIdKey
DECL|function|versionKey
DECL|member|number
DECL|member|op
DECL|member|type
DECL|member|versionTerm
DECL|struct|OsTypeTerm
DECL|struct|VersionTerm
DECL|typedef|JsonArrayConstIt
DECL|typedef|qt_glGetStringi
DECL|variable|operators
