DECL|class|QOpenGLVertexArrayObjectPrivate
DECL|class|QVertexArrayObjectHelper
DECL|enumerator|ARB
DECL|enumerator|Core_3_0
DECL|enumerator|Core_3_2
DECL|enumerator|NotSupported
DECL|function|QOpenGLVertexArrayObject
DECL|function|QOpenGLVertexArrayObject
DECL|function|QOpenGLVertexArrayObjectPrivate
DECL|function|QVertexArrayObjectHelper
DECL|function|_q_contextAboutToBeDestroyed
DECL|function|bind
DECL|function|bind
DECL|function|create
DECL|function|create
DECL|function|destroy
DECL|function|destroy
DECL|function|glBindVertexArray
DECL|function|glDeleteVertexArrays
DECL|function|glGenVertexArrays
DECL|function|isCreated
DECL|function|objectId
DECL|function|release
DECL|function|release
DECL|function|~QOpenGLVertexArrayObject
DECL|function|~QOpenGLVertexArrayObjectPrivate
DECL|member|arb
DECL|member|context
DECL|member|core_3_0
DECL|member|core_3_2
DECL|member|vao
DECL|member|vaoFuncs
DECL|member|vaoFuncs
DECL|member|vaoFuncsType
