DECL|class|QOpenGLVertexArrayObjectPrivate
DECL|enumerator|APPLE
DECL|enumerator|ARB
DECL|enumerator|Core_3_0
DECL|enumerator|Core_3_2
DECL|enumerator|NotSupported
DECL|enumerator|OES
DECL|function|QOpenGLVertexArrayObject
DECL|function|QOpenGLVertexArrayObject
DECL|function|QOpenGLVertexArrayObjectPrivate
DECL|function|_q_contextAboutToBeDestroyed
DECL|function|bind
DECL|function|bind
DECL|function|create
DECL|function|create
DECL|function|destroy
DECL|function|destroy
DECL|function|isCreated
DECL|function|objectId
DECL|function|qtInitializeVertexArrayObjectHelper
DECL|function|release
DECL|function|release
DECL|function|~QOpenGLVertexArrayObject
DECL|function|~QOpenGLVertexArrayObjectPrivate
DECL|member|context
DECL|member|core_3_0
DECL|member|core_3_2
DECL|member|helper
DECL|member|vao
DECL|member|vaoFuncs
DECL|member|vaoFuncsType
