DECL|class|QOpenGLEngineThreadStorage
DECL|class|QOpenGLPaintDevicePrivate
DECL|function|QOpenGLPaintDevice
DECL|function|QOpenGLPaintDevice
DECL|function|QOpenGLPaintDevice
DECL|function|QOpenGLPaintDevicePrivate
DECL|function|context
DECL|function|dotsPerMeterX
DECL|function|dotsPerMeterY
DECL|function|engine
DECL|function|ensureActiveTarget
DECL|function|metric
DECL|function|paintEngine
DECL|function|paintFlipped
DECL|function|setDevicePixelRatio
DECL|function|setDotsPerMeterX
DECL|function|setDotsPerMeterY
DECL|function|setPaintFlipped
DECL|function|setSize
DECL|function|size
DECL|function|~QOpenGLPaintDevice
DECL|member|ctx
DECL|member|devicePixelRatio
DECL|member|dpmx
DECL|member|dpmy
DECL|member|engine
DECL|member|flipped
DECL|member|size
DECL|member|storage
