DECL|class|QOpenGLTextureCacheWrapper
DECL|function|QOpenGLCachedTexture
DECL|function|QOpenGLTextureCache
DECL|function|QOpenGLTextureCacheWrapper
DECL|function|bindTexture
DECL|function|bindTexture
DECL|function|bindTexture
DECL|function|cacheForContext
DECL|function|cacheForContext
DECL|function|cleanupTexturesForCacheKey
DECL|function|cleanupTexturesForPixmapData
DECL|function|freeResource
DECL|function|freeTexture
DECL|function|invalidate
DECL|function|invalidateResource
DECL|function|~QOpenGLTextureCache
DECL|function|~QOpenGLTextureCacheWrapper
DECL|macro|GL_BGR
DECL|macro|GL_BGRA
DECL|macro|GL_RED
DECL|macro|GL_RGB10_A2
DECL|macro|GL_UNSIGNED_INT_2_10_10_10_REV
DECL|macro|GL_UNSIGNED_INT_8_8_8_8_REV
DECL|member|m_mutex
DECL|member|m_resource
