DECL|function|QOpenGLFramebufferObject
DECL|function|QOpenGLFramebufferObject
DECL|function|QOpenGLFramebufferObject
DECL|function|QOpenGLFramebufferObject
DECL|function|QOpenGLFramebufferObject
DECL|function|QOpenGLFramebufferObject
DECL|function|QOpenGLFramebufferObjectFormat
DECL|function|QOpenGLFramebufferObjectFormat
DECL|function|addColorAttachment
DECL|function|addColorAttachment
DECL|function|attachment
DECL|function|attachment
DECL|function|bind
DECL|function|bindDefault
DECL|function|blitFramebuffer
DECL|function|blitFramebuffer
DECL|function|blitFramebuffer
DECL|function|checkFramebufferStatus
DECL|function|detach
DECL|function|effectiveInternalFormat
DECL|function|format
DECL|function|freeFramebufferFunc
DECL|function|freeRenderbufferFunc
DECL|function|freeTextureFunc
DECL|function|handle
DECL|function|hasOpenGLFramebufferBlit
DECL|function|hasOpenGLFramebufferObjects
DECL|function|init
DECL|function|initColorBuffer
DECL|function|initDepthStencilAttachments
DECL|function|initTexture
DECL|function|internalTextureFormat
DECL|function|isBound
DECL|function|isValid
DECL|function|mipmap
DECL|function|operator !=
DECL|function|operator =
DECL|function|operator ==
DECL|function|qt_gl_read_framebuffer
DECL|function|qt_gl_read_framebuffer
DECL|function|qt_gl_read_framebuffer_rgb10a2
DECL|function|qt_gl_read_framebuffer_rgba8
DECL|function|release
DECL|function|samples
DECL|function|setAttachment
DECL|function|setAttachment
DECL|function|setInternalTextureFormat
DECL|function|setMipmap
DECL|function|setSamples
DECL|function|setTextureTarget
DECL|function|size
DECL|function|sizes
DECL|function|takeTexture
DECL|function|takeTexture
DECL|function|texture
DECL|function|textureTarget
DECL|function|textures
DECL|function|toImage
DECL|function|toImage
DECL|function|toImage
DECL|function|~QOpenGLFramebufferObject
DECL|function|~QOpenGLFramebufferObjectFormat
DECL|macro|GL_BGRA
DECL|macro|GL_DEPTH24_STENCIL8
DECL|macro|GL_DEPTH_COMPONENT24
DECL|macro|GL_DEPTH_COMPONENT24_OES
DECL|macro|GL_DRAW_FRAMEBUFFER
DECL|macro|GL_MAX_SAMPLES
DECL|macro|GL_READ_FRAMEBUFFER
DECL|macro|GL_RENDERBUFFER_SAMPLES
DECL|macro|GL_RGB10
DECL|macro|GL_RGB10_A2
DECL|macro|GL_RGB8
DECL|macro|GL_RGBA8
DECL|macro|GL_UNSIGNED_INT_2_10_10_10_REV
DECL|macro|GL_UNSIGNED_INT_8_8_8_8_REV
DECL|macro|QT_CHECK_GLERROR
DECL|macro|QT_RESET_GLERROR
