DECL|enumerator|Equals
DECL|enumerator|GreaterEqualThan
DECL|enumerator|GreaterThan
DECL|enumerator|LessEqualThan
DECL|enumerator|LessThan
DECL|enumerator|NotEqual
DECL|enum|Operator
DECL|function|QOpenGLExtensionMatcher
DECL|function|VersionTerm
DECL|function|contains
DECL|function|contains
DECL|function|fromContext
DECL|function|fromJson
DECL|function|fromJson
DECL|function|gpuFeatures
DECL|function|gpuFeatures
DECL|function|gpuFeatures
DECL|function|gpuFeatures
DECL|function|hostKernelVersion
DECL|function|hostOs
DECL|function|hostOsRelease
DECL|function|isNull
DECL|function|isNull
DECL|function|matches
DECL|function|matches
DECL|function|matches
DECL|function|msgSyntaxWarning
DECL|function|operator <<
DECL|function|qgpu_features
DECL|function|readGpuFeatures
DECL|function|readGpuFeatures
DECL|function|readGpuFeatures
DECL|member|number
DECL|member|op
DECL|member|release
DECL|member|type
DECL|member|versionTerm
DECL|struct|OsTypeTerm
DECL|struct|VersionTerm
DECL|typedef|JsonArrayConstIt
DECL|typedef|qt_glGetStringi
DECL|variable|operators
