DECL|class|tst_QFileSystemEntry
DECL|function|absoluteOrRelative
DECL|function|absoluteOrRelative_data
DECL|function|baseName
DECL|function|baseName_data
DECL|function|completeBaseName
DECL|function|completeBaseName_data
DECL|function|completeSuffix
DECL|function|completeSuffix_data
DECL|function|getSetCheck
DECL|function|getSetCheck
DECL|function|getSetCheck_data
DECL|function|getSetCheck_data
DECL|function|suffix
DECL|function|suffix_data
DECL|macro|WIN_STUFF
