DECL|function|QOpenGLCompositorBackingStore
DECL|function|beginPaint
DECL|function|composeAndFlush
DECL|function|flush
DECL|function|notifyComposited
DECL|function|paintDevice
DECL|function|resize
DECL|function|toImage
DECL|function|updateTexture
DECL|function|~QOpenGLCompositorBackingStore
