DECL|macro|PVRQWSDRAWABLE_P_H
DECL|macro|PVRQWS_MAX_BACK_BUFFERS
DECL|macro|PVRQWS_MAX_FLIP_BUFFERS
DECL|macro|PVRQWS_MAX_SCREENS
DECL|macro|PVRQWS_MAX_VISIBLE_RECTS
DECL|member|backBuffers
DECL|member|backBuffersValid
DECL|member|bytesPerPixel
DECL|member|context
DECL|member|currentBackBuffer
DECL|member|firstWinId
DECL|member|flipBuffers
DECL|member|flipChain
DECL|member|frameBuffer
DECL|member|initialized
DECL|member|isFullScreen
DECL|member|mapped
DECL|member|mappedLength
DECL|member|needsUnmap
DECL|member|nextWinId
DECL|member|numDrawables
DECL|member|numFlipBuffers
DECL|member|numVisibleRects
DECL|member|pixelFormat
DECL|member|pixelFormat
DECL|member|rect
DECL|member|refCount
DECL|member|refCount
DECL|member|rotationAngle
DECL|member|screen
DECL|member|screenDrawable
DECL|member|screenRect
DECL|member|screenStart
DECL|member|screenStride
DECL|member|screens
DECL|member|strideBytes
DECL|member|stridePixels
DECL|member|swapFunction
DECL|member|type
DECL|member|usePresentBlit
DECL|member|userData
DECL|member|usingFlipBuffers
DECL|member|visibleRects
DECL|member|winId
DECL|struct|_PvrQwsDrawable
DECL|typedef|PvrQwsDisplay
DECL|typedef|PvrQwsScreenInfo
