DECL|enumerator|PosAliasListOffset
DECL|enumerator|PosGenericIconsListOffset
DECL|enumerator|PosGlobListOffset
DECL|enumerator|PosIconsListOffset
DECL|enumerator|PosLiteralListOffset
DECL|enumerator|PosMagicListOffset
DECL|enumerator|PosParentListOffset
DECL|enumerator|PosReverseSuffixTreeOffset
DECL|function|CacheFile
DECL|function|QMimeBinaryProvider
DECL|function|QMimeProviderBase
DECL|function|QMimeXMLProvider
DECL|function|addAlias
DECL|function|addGlobPattern
DECL|function|addMagicMatcher
DECL|function|addMimeType
DECL|function|addParent
DECL|function|allMimeTypes
DECL|function|allMimeTypes
DECL|function|checkCache
DECL|function|checkCacheChanged
DECL|function|ensureLoaded
DECL|function|fallbackParent
DECL|function|findByFileName
DECL|function|findByFileName
DECL|function|findByMagic
DECL|function|findByMagic
DECL|function|findCacheFile
DECL|function|getCharStar
DECL|function|getUint16
DECL|function|getUint32
DECL|function|iconForMime
DECL|function|isValid
DECL|function|isValid
DECL|function|isValid
DECL|function|listAliases
DECL|function|listAliases
DECL|function|load
DECL|function|load
DECL|function|load
DECL|function|loadGenericIcon
DECL|function|loadIcon
DECL|function|loadMimeTypeList
DECL|function|loadMimeTypePrivate
DECL|function|matchGlobList
DECL|function|matchMagicRule
DECL|function|matchSuffixTree
DECL|function|mimeTypeForName
DECL|function|mimeTypeForName
DECL|function|mimeTypeForNameUnchecked
DECL|function|parents
DECL|function|parents
DECL|function|reload
DECL|function|resolveAlias
DECL|function|resolveAlias
DECL|function|shouldCheck
DECL|function|~CacheFile
DECL|function|~QMimeBinaryProvider
DECL|macro|QT_USE_MMAP
DECL|member|data
DECL|member|file
DECL|member|m_mtime
DECL|member|m_valid
DECL|struct|CacheFile
DECL|variable|qmime_secondsBetweenChecks
