DECL|function|createMagicMatchRule
DECL|function|nextState
DECL|function|parse
DECL|function|parseNumber
DECL|macro|QT_NO_CAST_FROM_ASCII
DECL|variable|aliasTagC
DECL|variable|caseSensitiveAttributeC
DECL|variable|commentTagC
DECL|variable|genericIconTagC
DECL|variable|globTagC
DECL|variable|iconTagC
DECL|variable|localeAttributeC
DECL|variable|magicTagC
DECL|variable|matchMaskAttributeC
DECL|variable|matchOffsetAttributeC
DECL|variable|matchTagC
DECL|variable|matchTypeAttributeC
DECL|variable|matchValueAttributeC
DECL|variable|mimeInfoTagC
DECL|variable|mimeTypeAttributeC
DECL|variable|mimeTypeTagC
DECL|variable|nameAttributeC
DECL|variable|patternAttributeC
DECL|variable|priorityAttributeC
DECL|variable|subClassTagC
DECL|variable|weightAttributeC
