DECL|function|QMimeDatabase
DECL|function|QMimeDatabasePrivate
DECL|function|allMimeTypes
DECL|function|allMimeTypes
DECL|function|findByData
DECL|function|inherits
DECL|function|instance
DECL|function|isTextFile
DECL|function|mimeTypeForData
DECL|function|mimeTypeForData
DECL|function|mimeTypeForFile
DECL|function|mimeTypeForFile
DECL|function|mimeTypeForFileName
DECL|function|mimeTypeForFileNameAndData
DECL|function|mimeTypeForFileNameAndData
DECL|function|mimeTypeForFileNameAndData
DECL|function|mimeTypeForName
DECL|function|mimeTypeForName
DECL|function|mimeTypeForUrl
DECL|function|mimeTypesForFileName
DECL|function|provider
DECL|function|setProvider
DECL|function|suffixForFileName
DECL|function|~QMimeDatabase
DECL|function|~QMimeDatabasePrivate
DECL|macro|DBG
DECL|macro|DBG
DECL|macro|DBG
