DECL|class|tst_QTemporaryFile
DECL|function|QTBUG_4796
DECL|function|QTBUG_4796_data
DECL|function|autoRemove
DECL|function|autoRemoveAfterFailedRename
DECL|function|cleanup
DECL|function|cleanupTestCase
DECL|function|construction
DECL|function|fileName
DECL|function|fileNameIsEmpty
DECL|function|fileTemplate
DECL|function|fileTemplate_data
DECL|function|getSetCheck
DECL|function|init
DECL|function|initTestCase
DECL|function|keepOpenMode
DECL|function|openCloseOpenClose
DECL|function|openOnRootDrives
DECL|function|reOpenThroughQFile
DECL|function|rename
DECL|function|renameFdLeak
DECL|function|resetTemplateAfterError
DECL|function|resize
DECL|function|setTemplateAfterOpen
DECL|function|size
DECL|function|stressTest
DECL|function|tst_QTemporaryFile
DECL|function|write
DECL|function|~tst_QTemporaryFile
DECL|macro|SRCDIR
