DECL|class|LoadAndConvert
DECL|class|LoadAndConvertMIB
DECL|class|tst_QTextCodec
DECL|function|LoadAndConvert
DECL|function|LoadAndConvertMIB
DECL|function|aliasForUTF16
DECL|function|asciiToIscii
DECL|function|checkAliases
DECL|function|checkAliases_data
DECL|function|codecForHtml
DECL|function|codecForHtml_data
DECL|function|codecForLocale
DECL|function|codecForName
DECL|function|codecForName_data
DECL|function|codecForTSCII
DECL|function|codecForUtfText
DECL|function|codecForUtfText_data
DECL|function|decode0D
DECL|function|flagCodepointFFFF
DECL|function|flagEFBFBF
DECL|function|flagF7808080
DECL|function|fromInvalidUtf8Sequence
DECL|function|fromUnicode
DECL|function|fromUnicode_data
DECL|function|invalidNames
DECL|function|mibForTSCII
DECL|function|moreToFromUnicode
DECL|function|moreToFromUnicode_data
DECL|function|run
DECL|function|run
DECL|function|shiftJis
DECL|function|threadSafety
DECL|function|toLocal8Bit
DECL|function|toUnicode
DECL|function|toUnicode_codecForHtml
DECL|function|toUnicode_data
DECL|function|toUnicode_incremental
DECL|function|userCodec
DECL|function|utf8Codec
DECL|function|utf8Codec_data
DECL|function|utf8bom
DECL|function|utf8bom_data
DECL|function|utfHeaders
DECL|function|utfHeaders_data
DECL|function|~DontCrashAtExit
DECL|member|codecName
DECL|member|mib
DECL|member|target
DECL|member|target
DECL|struct|DontCrashAtExit
DECL|struct|UserCodec
DECL|variable|dontCrashAtExit
