DECL|class|LayoutDirectionSaver
DECL|class|Menu
DECL|class|QtTestSlot
DECL|class|tst_QMenuBar
DECL|function|LayoutDirectionSaver
DECL|function|QtTestSlot
DECL|function|accel
DECL|function|activatedCount
DECL|function|addActions
DECL|function|allowActiveAndDisabled
DECL|function|check_accelKeys
DECL|function|check_altPress
DECL|function|check_cursorKeys1
DECL|function|check_cursorKeys2
DECL|function|check_cursorKeys3
DECL|function|check_endKey
DECL|function|check_escKey
DECL|function|check_homeKey
DECL|function|check_menuPosition
DECL|function|check_shortcutPress
DECL|function|cleanupTestCase
DECL|function|clear
DECL|function|clear
DECL|function|closeOnSecondClick
DECL|function|count
DECL|function|getSetCheck
DECL|function|init
DECL|function|initComplexMenubar
DECL|function|initSimpleMenubar
DECL|function|initTestCase
DECL|function|insertItem_QString_QObject
DECL|function|menubarSizeHint
DECL|function|onActivated
DECL|function|removeItem
DECL|function|removeItemAt
DECL|function|removeItemAt_data
DECL|function|removeItem_data
DECL|function|reset
DECL|function|resetCount
DECL|function|resetSlots
DECL|function|selCount
DECL|function|selected
DECL|function|task223138_triggered
DECL|function|task256322_highlight
DECL|function|taskQTBUG11823_crashwithInvisibleActions
DECL|function|taskQTBUG4965_escapeEaten
DECL|function|tst_QMenuBar
DECL|function|~LayoutDirectionSaver
DECL|function|~QtTestSlot
DECL|function|~tst_QMenuBar
DECL|member|action
DECL|member|action1
DECL|member|activated_count
DECL|member|item1_A
DECL|member|item1_B
DECL|member|item2_C
DECL|member|item2_D
DECL|member|item2_E
DECL|member|item2_F
DECL|member|item2_G
DECL|member|item2_H
DECL|member|last_accel_id
DECL|member|m_oldDirection
DECL|member|mb
DECL|member|menu1
DECL|member|menu2
DECL|member|menu3
DECL|member|menu4
DECL|member|mw
DECL|member|pm1
DECL|member|pm2
DECL|member|sel_count
DECL|variable|RESET
