DECL|class|PeekBug
DECL|class|tst_QIODevice
DECL|function|PeekBug
DECL|function|cleanup
DECL|function|constructing_QFile
DECL|function|constructing_QTcpSocket
DECL|function|getSetCheck
DECL|function|init
DECL|function|peek
DECL|function|peekAndRead
DECL|function|peekBug
DECL|function|readData
DECL|function|readLine
DECL|function|readLine2
DECL|function|readLine2_data
DECL|function|readLine_data
DECL|function|read_QByteArray
DECL|function|tst_QIODevice
DECL|function|unget
DECL|function|writeData
DECL|function|~tst_QIODevice
DECL|macro|SRCDIR
DECL|member|alphabet
DECL|member|counter
