DECL|class|QEvdevTabletData
DECL|function|QEvdevTabletData
DECL|function|QEvdevTabletHandler
DECL|function|QEvdevTabletHandlerThread
DECL|function|deviceId
DECL|function|processInputEvent
DECL|function|queryLimits
DECL|function|readData
DECL|function|report
DECL|function|run
DECL|function|~QEvdevTabletHandler
DECL|function|~QEvdevTabletHandlerThread
DECL|member|d
DECL|member|d
DECL|member|devName
DECL|member|down
DECL|member|lastEventType
DECL|member|lastReportDown
DECL|member|lastReportPos
DECL|member|lastReportTool
DECL|member|maxValues
DECL|member|minValues
DECL|member|p
DECL|member|p
DECL|member|q
DECL|member|state
DECL|member|tool
DECL|member|x
DECL|member|x
DECL|member|y
DECL|member|y
