DECL|class|KeypadNavigation
DECL|enumerator|DialogAboutQt
DECL|enumerator|DialogGetColor
DECL|enumerator|DialogGetExistingDirectory
DECL|enumerator|DialogGetFont
DECL|enumerator|DialogGetItem
DECL|enumerator|DialogGetOpenFileName
DECL|enumerator|DialogGetSaveFileName
DECL|enumerator|DialogQuestion
DECL|enum|Dialog
DECL|function|KeypadNavigation
DECL|function|main
DECL|function|openDialog
DECL|function|setNavigationMode
DECL|function|~KeypadNavigation
DECL|member|m_dialogSignalMapper
DECL|member|m_layoutSignalMapper
DECL|member|m_modeSignalMapper
DECL|member|ui
