DECL|function|BearerMonitor
DECL|function|configurationAdded
DECL|function|configurationChanged
DECL|function|configurationRemoved
DECL|function|createNewSession
DECL|function|createSessionFor
DECL|function|deleteSession
DECL|function|onlineStateChanged
DECL|function|performScan
DECL|function|registerNetwork
DECL|function|showConfigurationFor
DECL|function|unregisterNetwork
DECL|function|updateConfigurations
DECL|function|updateItem
DECL|function|updateSnapConfiguration
DECL|function|~BearerMonitor
DECL|macro|NS_NLA
DECL|macro|interface
