DECL|function|SessionWidget
DECL|function|clearError
DECL|function|closeSession
DECL|function|deleteSession
DECL|function|openSession
DECL|function|openSyncSession
DECL|function|stopSession
DECL|function|timerEvent
DECL|function|updateSession
DECL|function|updateSessionError
DECL|function|updateSessionState
DECL|function|~SessionWidget
