DECL|class|tst_QReadLocker
DECL|class|tst_QReadLockerThread
DECL|function|lockerStateTest
DECL|function|releaseThread
DECL|function|scopeTest
DECL|function|unlockAndRelockTest
DECL|function|waitForTest
DECL|function|waitForThread
DECL|member|lock
DECL|member|semaphore
DECL|member|testSemaphore
DECL|member|thread
