DECL|class|SomeSingleton
DECL|class|tst_QFileSystemWatcher
DECL|function|QTBUG15255_deadlock
DECL|function|SomeSingleton
DECL|function|addPath
DECL|function|addPaths
DECL|function|basicTest
DECL|function|basicTest_data
DECL|function|bla
DECL|function|cleanup
DECL|function|nonExistingFile
DECL|function|removeFileAndUnWatch
DECL|function|removePath
DECL|function|removePaths
DECL|function|tst_QFileSystemWatcher
DECL|function|watchDirectory
DECL|function|watchDirectory_data
DECL|function|watchFileAndItsDirectory
DECL|function|watchFileAndItsDirectory_data
DECL|member|do_force_engines
DECL|member|do_force_native
DECL|member|mFsWatcher
