DECL|class|tst_QQuaternion
DECL|class|tst_QQuaternionProperties
DECL|function|add
DECL|function|add_data
DECL|function|compare
DECL|function|conjugate
DECL|function|conjugate_data
DECL|function|create
DECL|function|divide
DECL|function|divide_data
DECL|function|fromAxisAndAngle
DECL|function|fromAxisAndAngle_data
DECL|function|fuzzyCompare
DECL|function|length
DECL|function|length_data
DECL|function|metaTypes
DECL|function|multiply
DECL|function|multiplyFactor
DECL|function|multiplyFactor_data
DECL|function|multiply_data
DECL|function|negate
DECL|function|negate_data
DECL|function|nlerp
DECL|function|nlerp_data
DECL|function|normalize
DECL|function|normalize_data
DECL|function|normalized
DECL|function|normalized_data
DECL|function|properties
DECL|function|quaternion
DECL|function|setQuaternion
DECL|function|slerp
DECL|function|slerp_data
DECL|function|subtract
DECL|function|subtract_data
DECL|function|tst_QQuaternion
DECL|function|tst_QQuaternionProperties
DECL|function|~tst_QQuaternion
DECL|member|q
