DECL|class|Frame
DECL|function|Animation
DECL|function|Frame
DECL|function|currentFrame
DECL|function|load
DECL|function|name
DECL|function|nodeCount
DECL|function|nodeCount
DECL|function|nodePos
DECL|function|nodePos
DECL|function|save
DECL|function|setCurrentFrame
DECL|function|setName
DECL|function|setNodeCount
DECL|function|setNodeCount
DECL|function|setNodePos
DECL|function|setNodePos
DECL|function|setTotalFrames
DECL|function|totalFrames
DECL|function|~Animation
DECL|member|m_nodePositions
