DECL|macro|LIFECYCLE_H
DECL|variable|GraphicsView
DECL|variable|QAbstractState
DECL|variable|QAbstractTransition
DECL|variable|QAnimationGroup
DECL|variable|QObject
DECL|variable|QState
DECL|variable|QStateMachine
DECL|variable|StickMan
