DECL|class|QFontEngineFTRawData
DECL|function|QFontEngineFTRawData
DECL|function|addApplicationFont
DECL|function|addTTFile
DECL|function|fallbacksForFamily
DECL|function|fontEngine
DECL|function|fontEngine
DECL|function|fontNameFromTTFile
DECL|function|initFromData
DECL|function|populateFontDatabase
DECL|function|releaseHandle
DECL|function|scriptRequiresOpenType
DECL|function|updateFamilyNameAndStyle
DECL|macro|QT_NO_FREETYPE
DECL|member|checkSum
DECL|member|encodingID
DECL|member|entrySelector
DECL|member|fontSelector
DECL|member|languageID
DECL|member|length
DECL|member|majorVersion
DECL|member|minorVersion
DECL|member|nameID
DECL|member|nrCount
DECL|member|numTables
DECL|member|offset
DECL|member|platformID
DECL|member|rangeShift
DECL|member|searchRange
DECL|member|storageOffset
DECL|member|stringLength
DECL|member|stringOffset
DECL|member|tag
DECL|typedef|NAME_RECORD
DECL|typedef|NAME_TABLE_HEADER
DECL|typedef|OFFSET_TABLE
DECL|typedef|TABLE_DIRECTORY
