DECL|class|Caching
DECL|class|Fonts
DECL|class|Labels
DECL|class|MainWindow
DECL|class|PixmapPainter
DECL|class|StandardIcons
DECL|class|Style
DECL|function|Labels
DECL|function|MainWindow
DECL|function|PixmapPainter
DECL|function|Style
DECL|function|apiTest
DECL|function|apiTestdevicePixelRatioGetter
DECL|function|apiTestdevicePixelRatioSetter
DECL|function|main
DECL|function|paintEvent
DECL|function|paintEvent
DECL|function|paintEvent
DECL|function|paintEvent
DECL|member|button
DECL|member|fileToolBar
DECL|member|image1X
DECL|member|image2X
DECL|member|imageLarge
DECL|member|lineEdit
DECL|member|pixmap1X
DECL|member|pixmap1X
DECL|member|pixmap2X
DECL|member|pixmap2X
DECL|member|pixmapLarge
DECL|member|pixmapLarge
DECL|member|qtIcon
DECL|member|qtIcon
DECL|member|qtIcon
DECL|member|qtIcon1x
DECL|member|qtIcon2x
DECL|member|row1
DECL|member|slider
