DECL|function|MainWindow
DECL|function|about
DECL|function|addParagraph
DECL|function|createActions
DECL|function|createDockWindows
DECL|function|createStatusBar
DECL|function|insertCustomer
DECL|function|newLetter
DECL|function|print
DECL|function|save
DECL|function|undo
