DECL|class|DBusDispatcherPrivate
DECL|class|PendingCallInfo
DECL|function|DBusDispatcher
DECL|function|DBusDispatcher
DECL|function|DBusDispatcherPrivate
DECL|function|appendVariantToDBusMessage
DECL|function|call
DECL|function|callAsynchronous
DECL|function|constantVariantList
DECL|function|emitCallReply
DECL|function|emitSignalReceived
DECL|function|freePendingCallInfo
DECL|function|getVariantFromDBusMessage
DECL|function|pendingCallFunction
DECL|function|prepareDBusCall
DECL|function|setupDBus
DECL|function|signalHandler
DECL|function|synchronousDispatch
DECL|function|variantToSignature
DECL|function|~DBusDispatcher
DECL|function|~DBusDispatcherPrivate
DECL|member|connection
DECL|member|dispatcher
DECL|member|interface
DECL|member|method
DECL|member|path
DECL|member|pending_calls
DECL|member|priv
DECL|member|service
DECL|member|signalPath
DECL|member|signal_vtable
DECL|namespace|Maemo
