DECL|class|IAPConfPrivate
DECL|function|IAPConf
DECL|function|getAll
DECL|function|value
DECL|function|valueToVariant
DECL|function|variantToValue
DECL|function|~IAPConf
DECL|macro|QSTRING_TO_CONST_CSTR
DECL|member|settings
DECL|namespace|Maemo
