DECL|class|IAPMonitorPrivate
DECL|function|IAPMonitor
DECL|function|IAPMonitorPrivate
DECL|function|conn_settings_notify_func
DECL|function|iapAdded
DECL|function|iapAdded
DECL|function|iapRemoved
DECL|function|iapRemoved
DECL|function|~IAPMonitor
DECL|function|~IAPMonitorPrivate
DECL|member|monitor
DECL|member|settings
DECL|namespace|Maemo
