DECL|class|GConfItemFast
DECL|class|NetworkProxyFactory
DECL|class|ProxyConfPrivate
DECL|function|GConfItemFast
DECL|function|NetworkProxyFactory
DECL|function|ProxyConf
DECL|function|clear
DECL|function|convertKey
DECL|function|convertValue
DECL|function|flush
DECL|function|flush
DECL|function|getEntries
DECL|function|getHttpValues
DECL|function|getValues
DECL|function|isHostExcluded
DECL|function|queryProxy
DECL|function|readProxyData
DECL|function|readProxyData
DECL|function|update
DECL|function|~ProxyConf
DECL|macro|CONF_PROXY
DECL|macro|GET
DECL|macro|GET_HTTP
DECL|macro|HTTP_PROXY
DECL|macro|withClient
DECL|member|autoconfig_url
DECL|member|ftp_host
DECL|member|ftp_port
DECL|member|http_port
DECL|member|http_prefix
DECL|member|http_proxy
DECL|member|ignore_hosts
DECL|member|key
DECL|member|lock
DECL|member|mode
DECL|member|prefix
DECL|member|proxy_conf
DECL|member|proxy_data_read
DECL|member|refcount
DECL|member|rtsp_host
DECL|member|rtsp_port
DECL|member|secure_host
DECL|member|secure_port
DECL|member|socks_host
DECL|member|socks_port
DECL|member|use_http_host
DECL|namespace|Maemo
