DECL|function|TetrixBoard
DECL|function|clearBoard
DECL|function|drawSquare
DECL|function|dropDown
DECL|function|keyPressEvent
DECL|function|minimumSizeHint
DECL|function|newPiece
DECL|function|oneLineDown
DECL|function|paintEvent
DECL|function|pause
DECL|function|pieceDropped
DECL|function|removeFullLines
DECL|function|setNextPieceLabel
DECL|function|showNextPiece
DECL|function|sizeHint
DECL|function|start
DECL|function|timerEvent
DECL|function|tryMove
