DECL|class|tst_QPainterPath
DECL|function|angleAtPercent
DECL|function|arcWinding
DECL|function|arcWinding_data
DECL|function|closing
DECL|function|connectPathDuplicatePoint
DECL|function|connectPathMoveTo
DECL|function|contains_QPointF
DECL|function|contains_QPointF_data
DECL|function|contains_QRectF
DECL|function|contains_QRectF_data
DECL|function|currentPosition
DECL|function|ellipsePath
DECL|function|getSetCheck
DECL|function|intersects_QRectF
DECL|function|intersects_QRectF_data
DECL|function|linePath
DECL|function|lineWithinBounds
DECL|function|operators
DECL|function|operators_data
DECL|function|pathFuzzyCompare
DECL|function|pathFuzzyCompare
DECL|function|pointAtPercent
DECL|function|pointAtPercent_data
DECL|function|rectPath
DECL|function|setElementPositionAt
DECL|function|swap
DECL|function|testArcMoveTo
DECL|function|testArcMoveTo_data
DECL|function|testContainsAndIntersects
DECL|function|testContainsAndIntersects_data
DECL|function|testNaNandInfinites
DECL|function|testOnPath
DECL|function|testOnPath_data
DECL|function|testOperatorDatastream
DECL|function|testOperatorEquals
DECL|function|testOperatorEquals_fuzzy
DECL|function|testSimplified
DECL|function|testSimplified_data
DECL|function|testStroker
DECL|function|testStroker_data
DECL|function|testToFillPolygons
DECL|function|translate
DECL|macro|ANGLE
DECL|macro|M_PI
DECL|macro|SIGN
DECL|macro|_USE_MATH_DEFINES
