DECL|class|QAuBucketS60
DECL|class|QAuServerS60
DECL|function|MapcInitComplete
DECL|function|MapcPlayComplete
DECL|function|QAuBucketS60
DECL|function|QAuServerS60
DECL|function|bucket
DECL|function|init
DECL|function|okay
DECL|function|play
DECL|function|play
DECL|function|play
DECL|function|playCompleted
DECL|function|qt_new_audio_server
DECL|function|sound
DECL|function|stop
DECL|function|stop
DECL|function|~QAuBucketS60
DECL|member|m_playCalled
DECL|member|m_playUtility
DECL|member|m_prepared
DECL|member|m_server
DECL|member|m_sound
DECL|member|staticPlayingSounds
