DECL|class|tst_QAtomicPointer
DECL|function|alignment
DECL|function|assignment_operator
DECL|function|bar
DECL|function|constAndVolatile
DECL|function|constAndVolatile_helper
DECL|function|constructor
DECL|function|copy_constructor
DECL|function|fetchAndAdd
DECL|function|fetchAndAdd_data
DECL|function|fetchAndStore
DECL|function|forwardDeclared
DECL|function|isFetchAndAddNative
DECL|function|isFetchAndAddWaitFree
DECL|function|isFetchAndStoreNative
DECL|function|isFetchAndStoreWaitFree
DECL|function|isTestAndSetNative
DECL|function|isTestAndSetWaitFree
DECL|function|operators
DECL|function|operators_helper
DECL|function|testAndSet
DECL|function|warningFree
DECL|function|warningFreeHelper
DECL|member|d
DECL|member|ptr
DECL|struct|Big
DECL|struct|ContainsForwardDeclared
DECL|struct|WFHC
