DECL|class|ContentHandler
DECL|function|ContentHandler
DECL|function|Parser
DECL|function|attributeDecl
DECL|function|characters
DECL|function|comment
DECL|function|endCDATA
DECL|function|endDTD
DECL|function|endDocument
DECL|function|endElement
DECL|function|endEntity
DECL|function|endPrefixMapping
DECL|function|error
DECL|function|errorMsg
DECL|function|errorMsg
DECL|function|escapeStr
DECL|function|externalEntityDecl
DECL|function|fatalError
DECL|function|formatAttributes
DECL|function|ignorableWhitespace
DECL|function|internalEntityDecl
DECL|function|nestPrefix
DECL|function|notationDecl
DECL|function|parseFile
DECL|function|processingInstruction
DECL|function|resolveEntity
DECL|function|result
DECL|function|result
DECL|function|setDocumentLocator
DECL|function|skippedEntity
DECL|function|startCDATA
DECL|function|startDTD
DECL|function|startDocument
DECL|function|startElement
DECL|function|startEntity
DECL|function|startPrefixMapping
DECL|function|unparsedEntityDecl
DECL|function|warning
DECL|function|~Parser
DECL|member|m_error_msg
DECL|member|m_nest
DECL|member|m_result
