DECL|class|QMaliitPlatformInputContextPrivate
DECL|enumerator|Angle0
DECL|enumerator|Angle180
DECL|enumerator|Angle270
DECL|enumerator|Angle90
DECL|enumerator|CustomContentType
DECL|enumerator|EmailContentType
DECL|enumerator|FreeTextContentType
DECL|enumerator|InputPanelHidden
DECL|enumerator|InputPanelShowRequested
DECL|enumerator|InputPanelShown
DECL|enumerator|NumberContentType
DECL|enumerator|PhoneNumberContentType
DECL|enumerator|UrlContentType
DECL|enumerator|debug
DECL|enum|InputPanelVisibility
DECL|enum|MaliitOrientationAngle
DECL|enum|TextContentType
DECL|function|QMaliitPlatformInputContext
DECL|function|QMaliitPlatformInputContextPrivate
DECL|function|activationLostEvent
DECL|function|commitString
DECL|function|contentTypeFromHints
DECL|function|copy
DECL|function|hideInputPanel
DECL|function|imInitiatedHide
DECL|function|inputItemChanged
DECL|function|invokeAction
DECL|function|isInputPanelVisible
DECL|function|isValid
DECL|function|keyEvent
DECL|function|keyboardRect
DECL|function|maliitServerAddress
DECL|function|orientationAngle
DECL|function|paste
DECL|function|preeditRectangle
DECL|function|reset
DECL|function|selection
DECL|function|sendStateUpdate
DECL|function|setDetectableAutoRepeat
DECL|function|setGlobalCorrectionEnabled
DECL|function|setLanguage
DECL|function|setRedirectKeys
DECL|function|setSelection
DECL|function|showInputPanel
DECL|function|update
DECL|function|updateInputMethodArea
DECL|function|updatePreedit
DECL|function|updateServerWindowOrientation
DECL|function|~QMaliitPlatformInputContext
DECL|function|~QMaliitPlatformInputContextPrivate
DECL|member|active
DECL|member|adaptor
DECL|member|connection
DECL|member|correctionEnabled
DECL|member|imState
DECL|member|keyboardRect
DECL|member|preedit
DECL|member|q
DECL|member|server
DECL|member|valid
DECL|member|visibility
DECL|member|window
