DECL|class|Emitter
DECL|class|ExceptionThrower
DECL|class|FlexibleThrower
DECL|class|Receiver
DECL|class|tst_ExceptionSafety
DECL|enumerator|ThrowAtComparison
DECL|enumerator|ThrowAtCopy
DECL|enumerator|ThrowAtCreate
DECL|enumerator|ThrowLater
DECL|enumerator|ThrowNot
DECL|enum|ThrowType
DECL|function|FlexibleThrower
DECL|function|FlexibleThrower
DECL|function|FlexibleThrower
DECL|function|Receiver
DECL|function|emitTestSignal
DECL|function|exceptionHash
DECL|function|exceptionInSlot
DECL|function|exceptionLinkedList
DECL|function|exceptionList
DECL|function|exceptionMap
DECL|function|exceptionVector
DECL|function|initTestCase
DECL|function|operator <
DECL|function|operator ==
DECL|function|qHash
DECL|function|receiver
DECL|function|thrower
DECL|function|value
DECL|function|~FlexibleThrower
DECL|member|_value
DECL|member|dummy
DECL|member|received
DECL|typedef|FlexibleThrowerSmall
DECL|typedef|MyHash
DECL|typedef|MyMap
DECL|variable|objCounter
DECL|variable|throwType
