DECL|function|QAndroidPlatformMenu
DECL|function|icon
DECL|function|insertMenuItem
DECL|function|isEnabled
DECL|function|isVisible
DECL|function|menuItemAt
DECL|function|menuItemForTag
DECL|function|menuItems
DECL|function|menuItemsMutex
DECL|function|removeMenuItem
DECL|function|setEnabled
DECL|function|setIcon
DECL|function|setTag
DECL|function|setText
DECL|function|setVisible
DECL|function|syncMenuItem
DECL|function|syncSeparatorsCollapsible
DECL|function|tag
DECL|function|text
DECL|function|~QAndroidPlatformMenu
