DECL|function|QAndroidPlatformTheme
DECL|function|createPlatformMenu
DECL|function|createPlatformMenuBar
DECL|function|createPlatformMenuItem
DECL|function|font
DECL|function|fontType
DECL|function|palette
DECL|function|paletteType
DECL|function|themeHint
