DECL|macro|QANDROIDPLATFORMINTERATION_H
DECL|variable|QAndroidOpenGLPlatformWindow
DECL|variable|QAndroidPlatformServices
DECL|variable|QAndroidSystemLocale
DECL|variable|QDesktopWidget
DECL|variable|QPlatformAccessibility
