DECL|enumerator|DefaultWindowHeight
DECL|enumerator|DefaultWindowWidth
DECL|function|FrameMoved
DECL|function|FrameResized
DECL|function|HaikuWindowProxy
DECL|function|Minimize
DECL|function|QHaikuWindow
DECL|function|QuitRequested
DECL|function|WindowActivated
DECL|function|Zoom
DECL|function|frameMargins
DECL|function|haikuDrawRequest
DECL|function|haikuEnteredView
DECL|function|haikuExitedView
DECL|function|haikuKeyEvent
DECL|function|haikuMouseEvent
DECL|function|haikuWheelEvent
DECL|function|haikuWindowActivated
DECL|function|haikuWindowMinimized
DECL|function|haikuWindowMoved
DECL|function|haikuWindowQuitRequested
DECL|function|haikuWindowResized
DECL|function|haikuWindowZoomed
DECL|function|isActive
DECL|function|isExposed
DECL|function|nativeHandle
DECL|function|propagateSizeHints
DECL|function|requestActivateWindow
DECL|function|setGeometry
DECL|function|setVisible
DECL|function|setWindowFlags
DECL|function|setWindowState
DECL|function|setWindowTitle
DECL|function|winId
DECL|function|zoomByQt
DECL|function|~QHaikuWindow
