DECL|function|Draw
DECL|function|HaikuViewProxy
DECL|function|KeyDown
DECL|function|KeyUp
DECL|function|MessageReceived
DECL|function|MouseDown
DECL|function|MouseMoved
DECL|function|MouseUp
DECL|function|QHaikuRasterWindow
DECL|function|handleKeyEvent
DECL|function|keyStateToModifiers
DECL|function|keyStateToMouseButtons
DECL|function|nativeViewHandle
DECL|function|~QHaikuRasterWindow
