DECL|class|SomeHandler
DECL|class|Window
DECL|function|SomeHandler
DECL|function|Window
DECL|function|main
DECL|function|on_cbSelectionMode_currentIndexChanged
DECL|function|on_ckMovable_toggled
DECL|function|on_taskCombo_currentIndexChanged
DECL|function|setupComboBox
DECL|function|setupGroupBox
DECL|function|setupTableView
DECL|function|slotSectionResized
DECL|function|updateControls
DECL|macro|DO_CORRECT_OFFSET_AND_SB
DECL|member|cbSelectionMode
DECL|member|ckMovable
DECL|member|instructions
DECL|member|m
DECL|member|m_hv
DECL|member|m_taskInstructions
DECL|member|m_tv
DECL|member|sectionsMovable
DECL|member|selectionMode
DECL|member|tableView
DECL|member|title
DECL|struct|ManualTask
DECL|variable|tasks
