DECL|function|childIdListForAccessibleObject
DECL|function|clickAction
DECL|function|descriptionForAccessibleObject
DECL|function|hitTest
DECL|function|interfaceFromId
DECL|function|parentId
DECL|function|populateNode
DECL|function|registerNatives
DECL|function|screenRect
DECL|function|setActive
DECL|macro|CALL_METHOD
DECL|macro|FIND_AND_CHECK_CLASS
DECL|member|methods
DECL|namespace|QtAndroidAccessibility
DECL|variable|m_classErrorMsg
DECL|variable|m_methodErrorMsg
DECL|variable|m_qtTag
