DECL|class|ScopedProfiler
DECL|function|QAndroidPlatformScreen
DECL|function|ScopedProfiler
DECL|function|addWindow
DECL|function|doRedraw
DECL|function|logicalDpi
DECL|function|lower
DECL|function|nativeOrientation
DECL|function|orientation
DECL|function|raise
DECL|function|rasterSurfaces
DECL|function|removeWindow
DECL|function|scheduleUpdate
DECL|function|setDirty
DECL|function|setGeometry
DECL|function|setPhysicalSize
DECL|function|surfaceChanged
DECL|function|topLevelAt
DECL|function|topWindow
DECL|function|topWindowChanged
DECL|function|~QAndroidPlatformScreen
DECL|function|~ScopedProfiler
DECL|macro|PROFILE_SCOPE
DECL|member|m_msg
DECL|member|m_timer
