DECL|function|QAndroidPlatformMenuItem
DECL|function|icon
DECL|function|isCheckable
DECL|function|isChecked
DECL|function|isEnabled
DECL|function|isSeparator
DECL|function|isVisible
DECL|function|menu
DECL|function|role
DECL|function|setCheckable
DECL|function|setChecked
DECL|function|setEnabled
DECL|function|setFont
DECL|function|setIcon
DECL|function|setIsSeparator
DECL|function|setMenu
DECL|function|setRole
DECL|function|setShortcut
DECL|function|setTag
DECL|function|setText
DECL|function|setVisible
DECL|function|tag
DECL|function|text
