DECL|function|QAndroidPlatformTheme
DECL|function|createPlatformDialogHelper
DECL|function|createPlatformMenu
DECL|function|createPlatformMenuBar
DECL|function|createPlatformMenuItem
DECL|function|font
DECL|function|fontType
DECL|function|fontType
DECL|function|loadAndroidStyle
DECL|function|palette
DECL|function|paletteType
DECL|function|paletteType
DECL|function|setPaletteColor
DECL|function|showPlatformMenuBar
DECL|function|standardButtonText
DECL|function|themeHint
DECL|function|usePlatformNativeDialog
DECL|member|textStyle_bold
DECL|member|textStyle_italic
DECL|member|typeface_monospace
DECL|member|typeface_sans
DECL|member|typeface_serif
