DECL|function|QAndroidPlatformOpenGLWindow
DECL|function|applicationStateChanged
DECL|function|checkNativeSurface
DECL|function|clearEgl
DECL|function|createEgl
DECL|function|eglSurface
DECL|function|format
DECL|function|setGeometry
DECL|function|surfaceChanged
DECL|function|~QAndroidPlatformOpenGLWindow
