DECL|function|QAndroidPlatformMessageDialogHelper
DECL|function|addButtons
DECL|function|dialogResult
DECL|function|dialogResult
DECL|function|exec
DECL|function|hide
DECL|function|htmlText
DECL|function|registerNatives
DECL|function|show
DECL|macro|FIND_AND_CHECK_CLASS
DECL|member|QtMessageHandlerHelperClassName
DECL|member|g_messageDialogHelperClass
DECL|member|methods
DECL|namespace|QtAndroidDialogHelpers
