DECL|function|QAndroidPlatformWindow
DECL|function|lower
DECL|function|platformScreen
DECL|function|propagateSizeHints
DECL|function|raise
DECL|function|requestActivateWindow
DECL|function|setGeometry
DECL|function|setVisible
DECL|function|setWindowFlags
DECL|function|setWindowState
DECL|function|updateStatusBarVisibility
DECL|function|windowFlags
