DECL|class|tst_Counting
DECL|enumerator|Fail
DECL|enumerator|Pass
DECL|enumerator|Skip
DECL|enum|TestResult
DECL|function|helper
DECL|function|testFailFail
DECL|function|testFailFail_data
DECL|function|testFailPass
DECL|function|testFailPass_data
DECL|function|testFailSkip
DECL|function|testFailSkip_data
DECL|function|testPassFail
DECL|function|testPassFail_data
DECL|function|testPassPass
DECL|function|testPassPass_data
DECL|function|testPassSkip
DECL|function|testPassSkip_data
DECL|function|testSkipFail
DECL|function|testSkipFail_data
DECL|function|testSkipPass
DECL|function|testSkipPass_data
DECL|function|testSkipSkip
DECL|function|testSkipSkip_data
DECL|variable|TestResult
