DECL|class|PressDelayHandler
DECL|enumerator|RegrabMouseAfterwards
DECL|enumerator|UngrabMouseBefore
DECL|function|PressDelayHandler
DECL|function|QFlickGesture
DECL|function|QFlickGesturePrivate
DECL|function|QFlickGestureRecognizer
DECL|function|copyMouseEvent
DECL|function|create
DECL|function|instance
DECL|function|isDelaying
DECL|function|pressed
DECL|function|recognize
DECL|function|released
DECL|function|reset
DECL|function|scrollerBecameActive
DECL|function|scrollerWasIntercepted
DECL|function|sendMouseEvent
DECL|function|shouldEventBeIgnored
DECL|function|timerEvent
DECL|function|~QFlickGesture
DECL|macro|qFGDebug
DECL|member|inst
DECL|member|mouseButton
DECL|member|mouseTarget
DECL|member|pressDelayEvent
DECL|member|pressDelayTimer
DECL|member|sendingEvent
