DECL|class|QSystemTrayIconSys
DECL|function|QSystemTrayIconPrivate
DECL|function|QSystemTrayIconSys
DECL|function|addToTray
DECL|function|event
DECL|function|geometry_sys
DECL|function|globalGeometry
DECL|function|install_sys
DECL|function|isSystemTrayAvailable_sys
DECL|function|locateSystemTray
DECL|function|mouseDoubleClickEvent
DECL|function|mousePressEvent
DECL|function|paintEvent
DECL|function|remove_sys
DECL|function|showMessage_sys
DECL|function|supportsMessages_sys
DECL|function|systemTrayIcon
DECL|function|systemTrayWindowChanged
DECL|function|updateIcon
DECL|function|updateIcon_sys
DECL|function|updateMenu_sys
DECL|function|updateToolTip_sys
DECL|function|~QSystemTrayIconPrivate
DECL|member|q
