DECL|class|QSystemTrayIconSys
DECL|class|QX11SystemTrayContext
DECL|enumerator|SYSTEM_TRAY_BEGIN_MESSAGE
DECL|enumerator|SYSTEM_TRAY_CANCEL_MESSAGE
DECL|enumerator|SYSTEM_TRAY_REQUEST_DOCK
DECL|function|QSystemTrayIconPrivate
DECL|function|QSystemTrayIconSys
DECL|function|QX11SystemTrayContext
DECL|function|display
DECL|function|event
DECL|function|geometry_sys
DECL|function|globalGeometry
DECL|function|install_sys
DECL|function|isSystemTrayAvailable_sys
DECL|function|isValid
DECL|function|locateSystemTray
DECL|function|mouseDoubleClickEvent
DECL|function|mousePressEvent
DECL|function|paintEvent
DECL|function|remove_sys
DECL|function|screenNumber
DECL|function|showMessage_sys
DECL|function|supportsMessages_sys
DECL|function|systemTrayIcon
DECL|function|updateIcon
DECL|function|updateIcon_sys
DECL|function|updateMenu_sys
DECL|function|updateToolTip_sys
DECL|function|~QSystemTrayIconPrivate
DECL|function|~QX11SystemTrayContext
DECL|member|m_display
DECL|member|m_screenNumber
DECL|member|m_systemTraySelection
DECL|member|q
