DECL|class|QSystemTrayIconSys
DECL|function|QSystemTrayIconPrivate
DECL|function|QSystemTrayIconSys
DECL|function|allowsMessages
DECL|function|createIcon
DECL|function|createTrayIconMessageWindow
DECL|function|findIconGeometry
DECL|function|geometry_sys
DECL|function|iconFlag
DECL|function|install_sys
DECL|function|isSystemTrayAvailable_sys
DECL|function|qStringToLimitedWCharArray
DECL|function|qWindowsTrayconWndProc
DECL|function|remove_sys
DECL|function|setIconContents
DECL|function|showMessage
DECL|function|showMessage_sys
DECL|function|supportsMessages_sys
DECL|function|trayMessage
DECL|function|updateIcon_sys
DECL|function|updateMenu_sys
DECL|function|updateToolTip_sys
DECL|function|winEvent
DECL|function|~QSystemTrayIconPrivate
DECL|function|~QSystemTrayIconSys
DECL|macro|MYWM_NOTIFYICON
DECL|macro|NIF_SHOWTIP
DECL|macro|NIN_BALLOONTIMEOUT
DECL|macro|NIN_BALLOONUSERCLICK
DECL|macro|NIN_KEYSELECT
DECL|macro|NIN_SELECT
DECL|macro|NOTIFYICON_VERSION_4
DECL|macro|Q_MSGFLT_ALLOW
DECL|macro|_WIN32_IE
DECL|macro|_WIN32_IE
DECL|macro|_WIN32_WINNT
DECL|macro|_WIN32_WINNT
DECL|member|cbSize
DECL|member|globalPos
DECL|member|guidItem
DECL|member|hIcon
DECL|member|hWnd
DECL|member|ignoreNextMouseRelease
DECL|member|m_hwnd
DECL|member|notifyIconSize
DECL|member|q
DECL|member|uID
DECL|member|version
DECL|struct|Q_NOTIFYICONIDENTIFIER
DECL|typedef|HandleTrayIconHash
DECL|typedef|PtrChangeWindowMessageFilter
DECL|typedef|PtrChangeWindowMessageFilterEx
DECL|typedef|PtrShell_NotifyIconGetRect
DECL|variable|MYWM_TASKBARCREATED
DECL|variable|q_uNOTIFYICONID
