DECL|class|QUndoModel
DECL|class|QUndoViewPrivate
DECL|function|QUndoModel
DECL|function|QUndoView
DECL|function|QUndoView
DECL|function|QUndoView
DECL|function|QUndoViewPrivate
DECL|function|cleanIcon
DECL|function|cleanIcon
DECL|function|columnCount
DECL|function|data
DECL|function|emptyLabel
DECL|function|emptyLabel
DECL|function|group
DECL|function|index
DECL|function|init
DECL|function|parent
DECL|function|rowCount
DECL|function|selectedIndex
DECL|function|selectionModel
DECL|function|setCleanIcon
DECL|function|setCleanIcon
DECL|function|setEmptyLabel
DECL|function|setEmptyLabel
DECL|function|setGroup
DECL|function|setStack
DECL|function|setStack
DECL|function|setStackCurrentIndex
DECL|function|stack
DECL|function|stack
DECL|function|stackChanged
DECL|function|stackDestroyed
DECL|function|~QUndoView
DECL|member|group
DECL|member|m_clean_icon
DECL|member|m_emty_label
DECL|member|m_sel_model
DECL|member|m_stack
DECL|member|model
