DECL|function|QUndoAction
DECL|function|QUndoCommand
DECL|function|QUndoCommand
DECL|function|QUndoStack
DECL|function|actionText
DECL|function|beginMacro
DECL|function|canRedo
DECL|function|canUndo
DECL|function|checkUndoLimit
DECL|function|child
DECL|function|childCount
DECL|function|cleanIndex
DECL|function|clear
DECL|function|command
DECL|function|count
DECL|function|createRedoAction
DECL|function|createUndoAction
DECL|function|endMacro
DECL|function|id
DECL|function|index
DECL|function|isActive
DECL|function|isClean
DECL|function|mergeWith
DECL|function|push
DECL|function|redo
DECL|function|redo
DECL|function|redoText
DECL|function|setActive
DECL|function|setClean
DECL|function|setIndex
DECL|function|setIndex
DECL|function|setPrefixedText
DECL|function|setText
DECL|function|setTextFormat
DECL|function|setUndoLimit
DECL|function|text
DECL|function|text
DECL|function|undo
DECL|function|undo
DECL|function|undoLimit
DECL|function|undoText
DECL|function|~QUndoCommand
DECL|function|~QUndoStack
