DECL|class|QUndoGroupPrivate
DECL|function|QUndoGroup
DECL|function|QUndoGroupPrivate
DECL|function|activeStack
DECL|function|addStack
DECL|function|canRedo
DECL|function|canUndo
DECL|function|createRedoAction
DECL|function|createUndoAction
DECL|function|isClean
DECL|function|redo
DECL|function|redoText
DECL|function|removeStack
DECL|function|setActiveStack
DECL|function|stacks
DECL|function|undo
DECL|function|undoText
DECL|function|~QUndoGroup
DECL|member|active
DECL|member|stack_list
