DECL|class|QExternalProcess
DECL|class|QExternalTestPrivate
DECL|enumerator|Compile
DECL|enumerator|Link
DECL|enumerator|Run
DECL|enum|Target
DECL|function|QExternalTest
DECL|function|QExternalTestPrivate
DECL|function|applicationType
DECL|function|clear
DECL|function|commonSetup
DECL|function|createProjectFile
DECL|function|createTemporaryDirectory
DECL|function|errorReport
DECL|function|exitCode
DECL|function|extraProgramSources
DECL|function|failedStage
DECL|function|fullProgramSource
DECL|function|makespec
DECL|function|prepareSourceCode
DECL|function|programHeader
DECL|function|qmakeSettings
DECL|function|qtModules
DECL|function|removeRecursive
DECL|function|removeTemporaryDirectory
DECL|function|runMake
DECL|function|runQmake
DECL|function|setApplicationType
DECL|function|setExtraProgramSources
DECL|function|setProgramHeader
DECL|function|setQmakeSettings
DECL|function|setQtModules
DECL|function|setupChildProcess
DECL|function|standardError
DECL|function|standardOutput
DECL|function|tryCompile
DECL|function|tryCompile
DECL|function|tryCompileFail
DECL|function|tryLink
DECL|function|tryLink
DECL|function|tryLinkFail
DECL|function|tryRun
DECL|function|tryRun
DECL|function|tryRunFail
DECL|function|~QExternalTest
DECL|function|~QExternalTestPrivate
DECL|macro|DEFAULT_MAKESPEC
DECL|member|appType
DECL|member|exitCode
DECL|member|extraProgramSources
DECL|member|failedStage
DECL|member|programHeader
DECL|member|qmakeLines
DECL|member|qtModules
DECL|member|sourceCode
DECL|member|std_err
DECL|member|std_out
DECL|member|temporaryDir
DECL|namespace|QTest
