DECL|class|QODBCDriverPrivate
DECL|class|QODBCPrivate
DECL|enumerator|Lower
DECL|enumerator|MSSqlServer
DECL|enumerator|Mixed
DECL|enumerator|MySqlServer
DECL|enumerator|Oracle
DECL|enumerator|PostgreSQL
DECL|enumerator|Sensitive
DECL|enumerator|Sybase
DECL|enumerator|UnknownDB
DECL|enumerator|Upper
DECL|enum|DBMSType
DECL|enum|DefaultCase
DECL|function|QODBCDriver
DECL|function|QODBCDriver
DECL|function|QODBCDriverPrivate
DECL|function|QODBCPrivate
DECL|function|QODBCResult
DECL|function|adjustCase
DECL|function|beginTransaction
DECL|function|checkDBMS
DECL|function|checkDateTimePrecision
DECL|function|checkDriver
DECL|function|checkHasMultiResults
DECL|function|checkHasSQLFetchScroll
DECL|function|checkSchemaUsage
DECL|function|checkUnicode
DECL|function|cleanup
DECL|function|clearValues
DECL|function|close
DECL|function|commitTransaction
DECL|function|createResult
DECL|function|data
DECL|function|defaultCase
DECL|function|detachFromResultSet
DECL|function|dpDbc
DECL|function|dpEnv
DECL|function|endTrans
DECL|function|escapeIdentifier
DECL|function|exec
DECL|function|fetch
DECL|function|fetchFirst
DECL|function|fetchLast
DECL|function|fetchNext
DECL|function|fetchPrevious
DECL|function|formatValue
DECL|function|fromSQLTCHAR
DECL|function|handle
DECL|function|handle
DECL|function|hasFeature
DECL|function|init
DECL|function|isIdentifierEscaped
DECL|function|isNull
DECL|function|isStmtHandleValid
DECL|function|lastInsertId
DECL|function|nextResult
DECL|function|numRowsAffected
DECL|function|open
DECL|function|prepare
DECL|function|primaryIndex
DECL|function|qDecodeODBCType
DECL|function|qGetBigIntData
DECL|function|qGetBinaryData
DECL|function|qGetDoubleData
DECL|function|qGetIntData
DECL|function|qGetODBCVersion
DECL|function|qGetStringData
DECL|function|qMakeError
DECL|function|qMakeError
DECL|function|qMakeFieldInfo
DECL|function|qMakeFieldInfo
DECL|function|qODBCWarn
DECL|function|qODBCWarn
DECL|function|qSqlWarning
DECL|function|qSqlWarning
DECL|function|qWarnODBCHandle
DECL|function|quoteChar
DECL|function|record
DECL|function|record
DECL|function|reset
DECL|function|rollbackTransaction
DECL|function|setConnectionOptions
DECL|function|setForwardOnly
DECL|function|size
DECL|function|splitTableQualifier
DECL|function|tables
DECL|function|toSQLTCHAR
DECL|function|updateStmtHandleState
DECL|function|virtual_hook
DECL|function|~QODBCDriver
DECL|function|~QODBCResult
DECL|macro|ODBC_CHECK_DRIVER
DECL|member|datetime_precision
DECL|member|dbmsType
DECL|member|disconnectCount
DECL|member|disconnectCount
DECL|member|driverPrivate
DECL|member|fieldCache
DECL|member|fieldCacheIdx
DECL|member|hDbc
DECL|member|hEnv
DECL|member|hStmt
DECL|member|hasMultiResultSets
DECL|member|hasSQLFetchScroll
DECL|member|hasSQLFetchScroll
DECL|member|isFreeTDSDriver
DECL|member|isQuoteInitialized
DECL|member|quote
DECL|member|rInf
DECL|member|unicode
DECL|member|unicode
DECL|member|useSchema
DECL|member|useSchema
DECL|member|userForwardOnly
DECL|variable|COLNAMESIZE
DECL|variable|qParamType
