DECL|class|TestThread
DECL|class|Window
DECL|class|tst_NoQtEventLoop
DECL|enumerator|MouseClick
DECL|enumerator|MouseMove
DECL|function|TestThread
DECL|function|Window
DECL|function|cleanup
DECL|function|consumeMouseEvents
DECL|function|consumeSocketEvents
DECL|function|event
DECL|function|initTestCase
DECL|function|mouseClick
DECL|function|mouseInput
DECL|function|mouseMove
DECL|function|passed
DECL|function|received
DECL|function|reset
DECL|function|run
DECL|function|wndProc
DECL|member|m_childWindow
DECL|member|m_hwnd
DECL|member|m_received
DECL|member|m_screenH
DECL|member|m_screenW
DECL|member|m_testPassed
DECL|member|m_windowPos
DECL|variable|g_exit
