DECL|class|NotifierSink
DECL|class|tst_QWinOverlappedIoNotifier
DECL|function|IOResult
DECL|function|NotifierSink
DECL|function|brokenPipe
DECL|function|initTestCase
DECL|function|multipleOperations
DECL|function|notified
DECL|function|readFile
DECL|function|readFile_data
DECL|function|waitForNotified
DECL|function|waitForNotified_data
DECL|macro|PIPE_REJECT_REMOTE_CLIENTS
DECL|member|bytes
DECL|member|errorCode
DECL|member|notifications
DECL|member|notifiedBytesRead
DECL|member|notifiedErrorCode
DECL|member|overlapped
DECL|member|sourceFileInfo
DECL|member|threshold
DECL|struct|IOResult
