DECL|function|QKmsScreen
DECL|function|cursor
DECL|function|depth
DECL|function|device
DECL|function|format
DECL|function|geometry
DECL|function|handlePageFlipped
DECL|function|initializeScreenMode
DECL|function|initializeWithFormat
DECL|function|performPageFlip
DECL|function|physicalSize
DECL|function|swapBuffers
DECL|function|tweakFormat
DECL|function|waitForPageFlipComplete
DECL|function|~QKmsScreen
DECL|variable|builtin_1024x768
