DECL|class|QtTestModel
DECL|class|SimpleModel
DECL|class|protected_QHeaderView
DECL|class|tst_QHeaderView
DECL|function|QTBUG12268_hiddenMovedSectionSorting
DECL|function|QTBUG6058_reset
DECL|function|QTBUG7833_sectionClicked
DECL|function|QTBUG8650_crashOnInsertSections
DECL|function|QtTestModel
DECL|function|SimpleModel
DECL|function|checkHeaderViewOrder
DECL|function|cleanup
DECL|function|cleanup
DECL|function|cleanupTestCase
DECL|function|clickable
DECL|function|columnCount
DECL|function|columnCount
DECL|function|currentChanged
DECL|function|data
DECL|function|data
DECL|function|defaultAlignment
DECL|function|defaultAlignment_data
DECL|function|defaultSectionSize
DECL|function|defaultSectionSize_data
DECL|function|emptyModel
DECL|function|emptySectionSpan
DECL|function|event
DECL|function|focusPolicy
DECL|function|getSetCheck
DECL|function|globalResizeMode
DECL|function|globalResizeMode_data
DECL|function|headerDataChanged
DECL|function|hidden
DECL|function|hiddenSectionCount
DECL|function|hideAndInsert
DECL|function|hideAndInsert_data
DECL|function|highlightSections
DECL|function|horizontalOffset
DECL|function|index
DECL|function|init
DECL|function|initTestCase
DECL|function|initialSortOrderRole
DECL|function|insertOneColumn
DECL|function|invisibleStretchLastSection
DECL|function|isEditable
DECL|function|length
DECL|function|logicalIndex
DECL|function|logicalIndexAt
DECL|function|movable
DECL|function|moveAndInsertSection
DECL|function|moveAndInsertSection_data
DECL|function|moveSection
DECL|function|moveSectionAndRemove
DECL|function|moveSectionAndReset
DECL|function|moveSection_data
DECL|function|noModel
DECL|function|offset
DECL|function|oneSectionSize
DECL|function|parent
DECL|function|preserveHiddenSectionWidth
DECL|function|protected_QHeaderView
DECL|function|removeAllColumns
DECL|function|removeAllRows
DECL|function|removeAndInsertRow
DECL|function|removeCols
DECL|function|removeLastColumn
DECL|function|removeLastRow
DECL|function|removeOneColumn
DECL|function|removeRows
DECL|function|removeSection
DECL|function|resizeAndInsertSection
DECL|function|resizeAndInsertSection_data
DECL|function|resizeAndMoveSection
DECL|function|resizeAndMoveSection_data
DECL|function|resizeHiddenSection
DECL|function|resizeHiddenSection_data
DECL|function|resizeMode
DECL|function|resizeSection
DECL|function|resizeSection_data
DECL|function|resizeWithResizeModes
DECL|function|resizeWithResizeModes_data
DECL|function|rowCount
DECL|function|rowCount
DECL|function|saveRestore
DECL|function|sectionClickedSignal
DECL|function|sectionClickedSignal_data
DECL|function|sectionPressedSignal
DECL|function|sectionPressedSignal_data
DECL|function|sectionSize
DECL|function|sectionSizeHint
DECL|function|sectionSize_data
DECL|function|setColumnCount
DECL|function|showSortIndicator
DECL|function|sortIndicatorTracking
DECL|function|stretch
DECL|function|stretchSectionCount
DECL|function|swapSections
DECL|function|task236450_hidden
DECL|function|task236450_hidden_data
DECL|function|task248050_hideRow
DECL|function|testEvent
DECL|function|testhorizontalOffset
DECL|function|testverticalOffset
DECL|function|tst_QHeaderView
DECL|function|unhideSection
DECL|function|verticalOffset
DECL|function|visualIndex
DECL|function|visualIndexAt
DECL|function|visualIndexAt_data
DECL|function|~tst_QHeaderView
DECL|member|cols
DECL|member|m_col_count
DECL|member|model
DECL|member|rows
DECL|member|topLevel
DECL|member|view
DECL|member|wrongIndex
DECL|typedef|BoolList
DECL|typedef|IntList
