DECL|class|tst_QRingBuffer
DECL|function|readPointerAtPositionEmptyRead
DECL|function|readPointerAtPositionReadTooMuch
DECL|function|readPointerAtPositionWithHead
DECL|function|readPointerAtPositionWriteRead
DECL|function|sizeWhenEmpty
DECL|function|sizeWhenReserved
DECL|function|sizeWhenReservedAndChopped
