DECL|class|MainApplicationAdaptor
DECL|class|MainApplicationAdaptor
DECL|function|MainApplicationAdaptor
DECL|function|MyInterfaceAdaptor
DECL|function|caption
DECL|function|caption
DECL|function|focusChangedSlot
DECL|function|focusChangedSlot
DECL|function|main
DECL|function|mainWindowObject
DECL|function|mainWindowObject
DECL|function|organizationDomain
DECL|function|organizationDomain
DECL|function|organizationName
DECL|function|organizationName
DECL|function|processRequest
DECL|function|quit
DECL|function|quit
DECL|function|reparseConfiguration
DECL|function|reparseConfiguration
DECL|function|sendReply
DECL|function|setCaption
DECL|function|setCaption
DECL|function|setSessionManagement
DECL|function|setSessionManagement
DECL|member|app
DECL|member|processedData
DECL|member|reply
DECL|member|request
DECL|struct|RequestData
