DECL|function|QEucJpCodec
DECL|function|_mibEnum
DECL|function|_name
DECL|function|convertFromUnicode
DECL|function|convertToUnicode
DECL|function|~QEucJpCodec
DECL|macro|IsEucChar
DECL|macro|IsKana
DECL|macro|QValidChar
DECL|variable|Ss2
DECL|variable|Ss3
