DECL|function|QFontKsc5601Codec
DECL|function|_mibEnum
DECL|function|_mibEnum
DECL|function|_mibEnum
DECL|function|_name
DECL|function|_name
DECL|function|_name
DECL|function|convertFromUnicode
DECL|function|convertFromUnicode
DECL|function|convertFromUnicode
DECL|function|convertToUnicode
DECL|function|convertToUnicode
DECL|function|convertToUnicode
DECL|function|ksc2unicode
DECL|function|qt_Ksc5601ToUnicode
DECL|function|qt_UnicodeToKsc5601
DECL|function|unicode2ksc
DECL|macro|IsCP949Char
DECL|macro|IsEucChar
DECL|macro|QValidChar
DECL|member|kscode
DECL|member|unicode
DECL|struct|map
DECL|variable|ksc5601_hangul_to_unicode
DECL|variable|ksc5601_hanja_to_unicode
DECL|variable|ksc5601_symbol_to_unicode
DECL|variable|unicode_to_ksc5601_hanja
DECL|variable|unicode_to_ksc5601_symbol
