DECL|function|QFontGb18030_0Codec
DECL|function|QFontGb2312Codec
DECL|function|QFontGbkCodec
DECL|function|QGb18030Codec
DECL|function|QGb2312Codec
DECL|function|QGbkCodec
DECL|function|_aliases
DECL|function|_mibEnum
DECL|function|_mibEnum
DECL|function|_mibEnum
DECL|function|_mibEnum
DECL|function|_mibEnum
DECL|function|_name
DECL|function|_name
DECL|function|_name
DECL|function|_name
DECL|function|_name
DECL|function|convertFromUnicode
DECL|function|convertFromUnicode
DECL|function|convertFromUnicode
DECL|function|convertFromUnicode
DECL|function|convertFromUnicode
DECL|function|convertFromUnicode
DECL|function|convertToUnicode
DECL|function|convertToUnicode
DECL|function|convertToUnicode
DECL|function|convertToUnicode
DECL|function|convertToUnicode
DECL|function|convertToUnicode
DECL|function|gb4lin_to_gb
DECL|function|qt_Gb18030ToUnicode
DECL|function|qt_UnicodeToGb18030
DECL|function|qt_UnicodeToGbk
DECL|macro|InRange
DECL|macro|Is1stByte
DECL|macro|Is2ndByte
DECL|macro|Is2ndByteIn2Bytes
DECL|macro|Is2ndByteIn4Bytes
DECL|macro|Is3rdByte
DECL|macro|Is4thByte
DECL|macro|IsByteInGb2312
DECL|macro|IsLatin
DECL|macro|IsUDA1
DECL|macro|IsUDA2
DECL|macro|IsUDA3
DECL|macro|qValidChar
DECL|member|algOffset
DECL|member|tblBegin
DECL|member|tblEnd
DECL|member|tblOffset
DECL|typedef|indexTbl_t
DECL|variable|gb18030_2byte_to_ucs
DECL|variable|gb18030_4byte_to_ucs
DECL|variable|gb18030_to_ucs_index
DECL|variable|ucs_to_gb18030
DECL|variable|ucs_to_gb18030_index
