DECL|function|IconvState
DECL|function|QIconvCodec
DECL|function|convertFromUnicode
DECL|function|convertToUnicode
DECL|function|createIconv_t
DECL|function|mibEnum
DECL|function|name
DECL|function|qIconvCodecStateFree
DECL|function|saveChars
DECL|function|setByteOrder
DECL|function|~IconvState
DECL|function|~QIconvCodec
DECL|macro|GNU_LIBICONV
DECL|macro|NO_BOM
DECL|macro|NO_BOM
DECL|macro|NO_BOM
DECL|macro|UTF16
DECL|macro|UTF16
DECL|macro|UTF16
DECL|macro|UTF16
DECL|macro|UTF16
DECL|macro|iconv
DECL|macro|iconv
DECL|macro|iconv_close
DECL|macro|iconv_close
DECL|macro|iconv_open
DECL|macro|iconv_open
DECL|typedef|Ptr_iconv
DECL|typedef|Ptr_iconv_close
DECL|typedef|Ptr_iconv_open
DECL|variable|ptr_iconv
DECL|variable|ptr_iconv_close
DECL|variable|ptr_iconv_open
