DECL|function|QIcuCodec
DECL|function|aliases
DECL|function|availableCodecs
DECL|function|availableMibs
DECL|function|codecForMib
DECL|function|codecForName
DECL|function|convertFromUnicode
DECL|function|convertToUnicode
DECL|function|getConverter
DECL|function|mibEnum
DECL|function|name
DECL|function|nameMatch
DECL|function|qIcuCodecStateFree
DECL|function|~QIcuCodec
DECL|member|index
DECL|member|mib
DECL|struct|MibToName
DECL|variable|mibToName
DECL|variable|mibToNameSize
DECL|variable|mibToNameTable
