DECL|enumerator|Ascii
DECL|enumerator|Esc
DECL|enumerator|JISX0201_Kana
DECL|enumerator|JISX0201_Latin
DECL|enumerator|JISX0208_1978
DECL|enumerator|JISX0208_1983
DECL|enumerator|JISX0212
DECL|enumerator|MaxState
DECL|enumerator|MinState
DECL|enumerator|Overline
DECL|enumerator|ReverseSolidus
DECL|enumerator|Si
DECL|enumerator|So
DECL|enumerator|Tilde
DECL|enumerator|UnknownState
DECL|enumerator|YenSign
DECL|enum|Iso2022State
DECL|function|QJisCodec
DECL|function|_aliases
DECL|function|_mibEnum
DECL|function|_name
DECL|function|convertFromUnicode
DECL|function|convertToUnicode
DECL|function|~QJisCodec
DECL|macro|IsJisChar
DECL|macro|IsKana
DECL|macro|QValidChar
DECL|variable|Esc_Ascii
DECL|variable|Esc_CHARS
DECL|variable|Esc_JISX0201_Kana
DECL|variable|Esc_JISX0201_Latin
DECL|variable|Esc_JISX0208_1978
DECL|variable|Esc_JISX0208_1983
DECL|variable|Esc_JISX0212
DECL|variable|Esc_SEQ
