DECL|enumerator|Esc
DECL|function|QSjisCodec
DECL|function|_aliases
DECL|function|_mibEnum
DECL|function|_name
DECL|function|convertFromUnicode
DECL|function|convertToUnicode
DECL|function|~QSjisCodec
DECL|macro|IsKana
DECL|macro|IsSjisChar1
DECL|macro|IsSjisChar2
DECL|macro|IsUserDefinedChar1
DECL|macro|QValidChar
