DECL|function|codecForCStrings
DECL|function|codecForTr
DECL|function|setCodecForCStrings
DECL|function|setCodecForTr
DECL|macro|QTEXTCODEC_H
DECL|variable|QIODevice
DECL|variable|QTextCodec
DECL|variable|QTextDecoder
DECL|variable|QTextEncoder
