DECL|class|QSymbianTextCodec
DECL|class|QSymbianTextCodecWithName
DECL|function|QSymbianTextCodec
DECL|function|QSymbianTextCodecWithName
DECL|function|aliases
DECL|function|aliases
DECL|function|convertFromUnicode
DECL|function|convertToUnicode
DECL|function|converter
DECL|function|getLanguageDependentCharacterSet
DECL|function|init
DECL|function|mibEnum
DECL|function|name
DECL|function|name
DECL|member|aliases
DECL|member|charsetId
DECL|member|localeMapper
DECL|member|localeMapper
DECL|member|m_charsetId
DECL|member|m_name
DECL|member|m_staticIndex
DECL|member|mib
DECL|struct|QSymbianCodecInitData
DECL|variable|codecsData
