DECL|function|QTextCodec
DECL|function|QTextDecoder
DECL|function|QTextEncoder
DECL|function|aliases
DECL|function|availableCodecs
DECL|function|availableMibs
DECL|function|canEncode
DECL|function|canEncode
DECL|function|checkForCodec
DECL|function|codecForHtml
DECL|function|codecForHtml
DECL|function|codecForLocale
DECL|function|codecForMib
DECL|function|codecForName
DECL|function|codecForUtfText
DECL|function|codecForUtfText
DECL|function|fromUnicode
DECL|function|fromUnicode
DECL|function|fromUnicode
DECL|function|hasFailure
DECL|function|hasFailure
DECL|function|makeDecoder
DECL|function|makeEncoder
DECL|function|qTextCodecNameMatch
DECL|function|qTextCodecsMutex
DECL|function|qisalnum
DECL|function|qtolower
DECL|function|setCodecForLocale
DECL|function|setup
DECL|function|setup
DECL|function|setupLocaleMapper
DECL|function|toUnicode
DECL|function|toUnicode
DECL|function|toUnicode
DECL|function|toUnicode
DECL|function|toUnicode
DECL|function|~ConverterState
DECL|function|~QTextCodec
DECL|function|~QTextDecoder
DECL|function|~QTextEncoder
DECL|typedef|ByteArrayListConstIt
DECL|typedef|TextCodecListConstIt
