DECL|class|QTextCodecCleanup
DECL|class|QWindowsLocalCodec
DECL|function|QTextCodec
DECL|function|QTextDecoder
DECL|function|QTextEncoder
DECL|function|QWindowsLocalCodec
DECL|function|aliases
DECL|function|availableCodecs
DECL|function|availableMibs
DECL|function|canEncode
DECL|function|canEncode
DECL|function|checkForCodec
DECL|function|codecForHtml
DECL|function|codecForHtml
DECL|function|codecForLocale
DECL|function|codecForMib
DECL|function|codecForName
DECL|function|codecForUtfText
DECL|function|codecForUtfText
DECL|function|convertFromUnicode
DECL|function|convertToUnicode
DECL|function|convertToUnicodeCharByChar
DECL|function|createForMib
DECL|function|createForName
DECL|function|fromUnicode
DECL|function|fromUnicode
DECL|function|fromUnicode
DECL|function|hasFailure
DECL|function|hasFailure
DECL|function|makeDecoder
DECL|function|makeEncoder
DECL|function|mibEnum
DECL|function|name
DECL|function|nameMatch
DECL|function|qisalnum
DECL|function|qtolower
DECL|function|ru_RU_hack
DECL|function|setCodecForLocale
DECL|function|setup
DECL|function|setupLocaleMapper
DECL|function|toUnicode
DECL|function|toUnicode
DECL|function|toUnicode
DECL|function|toUnicode
DECL|function|toUnicode
DECL|function|try_locale_list
DECL|function|validCodecs
DECL|function|~ConverterState
DECL|function|~QTextCodec
DECL|function|~QTextCodecCleanup
DECL|function|~QTextDecoder
DECL|function|~QTextEncoder
DECL|function|~QWindowsLocalCodec
DECL|macro|QT_NO_SETLOCALE
DECL|member|cftr
DECL|typedef|QTextCodecCache
DECL|variable|all
DECL|variable|cp_1251locales
DECL|variable|destroying_is_ok
DECL|variable|iso8859_13locales
DECL|variable|iso8859_15locales
DECL|variable|iso8859_2locales
DECL|variable|iso8859_3locales
DECL|variable|iso8859_4locales
DECL|variable|iso8859_5locales
DECL|variable|iso8859_6locales
DECL|variable|iso8859_7locales
DECL|variable|iso8859_8locales
DECL|variable|iso8859_9locales
DECL|variable|koi8_ulocales
DECL|variable|localeMapper
DECL|variable|probably_koi8_rlocales
DECL|variable|pt_154locales
DECL|variable|tis_620locales
