DECL|enumerator|Data
DECL|enumerator|Endian
DECL|function|aliases
DECL|function|aliases
DECL|function|aliases
DECL|function|aliases
DECL|function|aliases
DECL|function|aliases
DECL|function|convertFromUnicode
DECL|function|convertFromUnicode
DECL|function|convertFromUnicode
DECL|function|convertFromUnicode
DECL|function|convertFromUnicode
DECL|function|convertFromUnicode
DECL|function|convertFromUnicode
DECL|function|convertToUnicode
DECL|function|convertToUnicode
DECL|function|convertToUnicode
DECL|function|convertToUnicode
DECL|function|convertToUnicode
DECL|function|convertToUnicode
DECL|function|convertToUnicode
DECL|function|convertToUnicode
DECL|function|mibEnum
DECL|function|mibEnum
DECL|function|mibEnum
DECL|function|mibEnum
DECL|function|mibEnum
DECL|function|mibEnum
DECL|function|mibEnum
DECL|function|name
DECL|function|name
DECL|function|name
DECL|function|name
DECL|function|name
DECL|function|name
DECL|function|name
DECL|function|simdDecodeAscii
DECL|function|simdDecodeAscii
DECL|function|simdEncodeAscii
DECL|function|simdEncodeAscii
DECL|function|~QUtf16Codec
DECL|function|~QUtf32Codec
DECL|function|~QUtf8Codec
DECL|variable|utf8bom
