DECL|class|tst_QToolBox
DECL|class|tst_QToolBoxPrivate
DECL|function|change
DECL|function|cleanup
DECL|function|cleanupTestCase
DECL|function|clear
DECL|function|currentChanged
DECL|function|getSetCheck
DECL|function|init
DECL|function|initTestCase
DECL|function|populate
DECL|function|tst_QToolBox
DECL|function|~tst_QToolBox
DECL|member|ci0
DECL|member|ci1
DECL|member|ci2
DECL|member|ci3
DECL|member|ci4
DECL|member|ci_correct
DECL|member|count0
DECL|member|count1
DECL|member|count2
DECL|member|count3
DECL|member|count4
DECL|member|currentIndex
DECL|member|d
DECL|member|i0
DECL|member|i1
DECL|member|i2
DECL|member|i3
DECL|member|i4
DECL|member|idx1
DECL|member|idx2
DECL|member|idx3
DECL|member|idx32
DECL|member|manual_count
DECL|member|testWidget
