DECL|function|QWaylandGLWindowSurface
DECL|function|beginPaint
DECL|function|blitTexture
DECL|function|context
DECL|function|drawTexture
DECL|function|flush
DECL|function|paintDevice
DECL|function|resize
DECL|function|~QWaylandGLWindowSurface
