DECL|function|Android9PatchDrawable
DECL|function|AndroidClipDrawable
DECL|function|AndroidColorDrawable
DECL|function|AndroidCompoundButtonControl
DECL|function|AndroidControl
DECL|function|AndroidDrawable
DECL|function|AndroidGradientDrawable
DECL|function|AndroidImageDrawable
DECL|function|AndroidLayerDrawable
DECL|function|AndroidProgressBarControl
DECL|function|AndroidSeekBarControl
DECL|function|AndroidSpinnerControl
DECL|function|AndroidStateDrawable
DECL|function|QAndroidStyle
DECL|function|backgroundDrawable
DECL|function|backgroundDrawable
DECL|function|bestAndroidStateMatch
DECL|function|calculateStretch
DECL|function|draw
DECL|function|draw
DECL|function|draw
DECL|function|draw
DECL|function|draw
DECL|function|draw
DECL|function|draw
DECL|function|drawComplexControl
DECL|function|drawControl
DECL|function|drawControl
DECL|function|drawControl
DECL|function|drawControl
DECL|function|drawControl
DECL|function|drawPrimitive
DECL|function|extractIntArray
DECL|function|extractMargins
DECL|function|extractState
DECL|function|fontType
DECL|function|fromMap
DECL|function|generatedIconPixmap
DECL|function|hitTestComplexControl
DECL|function|initPadding
DECL|function|layer
DECL|function|padding
DECL|function|padding
DECL|function|paletteType
DECL|function|pixelMetric
DECL|function|polish
DECL|function|qtControl
DECL|function|qtControl
DECL|function|qtControl
DECL|function|qtControl
DECL|function|qtControl
DECL|function|qtControl
DECL|function|setFactor
DECL|function|setFactor
DECL|function|setPaddingLeftToSizeWidth
DECL|function|setPaddingLeftToSizeWidth
DECL|function|setPaletteColor
DECL|function|size
DECL|function|size
DECL|function|size
DECL|function|size
DECL|function|sizeFromContents
DECL|function|sizeFromContents
DECL|function|sizeFromContents
DECL|function|sizeFromContents
DECL|function|standardPalette
DECL|function|standardPixmap
DECL|function|styleHint
DECL|function|subControlRect
DECL|function|subControlRect
DECL|function|subControlRect
DECL|function|subControlRect
DECL|function|subElementRect
DECL|function|subElementRect
DECL|function|subElementRect
DECL|function|type
DECL|function|type
DECL|function|type
DECL|function|type
DECL|function|type
DECL|function|type
DECL|function|type
DECL|function|unpolish
DECL|function|~AndroidClipDrawable
DECL|function|~AndroidCompoundButtonControl
DECL|function|~AndroidControl
DECL|function|~AndroidDrawable
DECL|function|~AndroidLayerDrawable
DECL|function|~AndroidProgressBarControl
DECL|function|~AndroidSeekBarControl
DECL|function|~AndroidStateDrawable
DECL|function|~QAndroidStyle
DECL|member|NO_COLOR
DECL|member|TRANSPARENT_COLOR
DECL|member|textStyle_bold
DECL|member|textStyle_italic
DECL|member|typeface_monospace
DECL|member|typeface_sans
DECL|member|typeface_serif
