DECL|function|QTileRules
DECL|function|QTileRules
DECL|function|qDrawBorderPixmap
DECL|macro|QDRAWUTIL_H
DECL|member|horizontal
DECL|member|vertical
DECL|struct|QTileRules
DECL|variable|QBrush
DECL|variable|QColor
DECL|variable|QPalette
DECL|variable|QPoint
DECL|variable|QRect
