DECL|function|QGtkStyle
DECL|function|QGtkStyle
DECL|function|drawComplexControl
DECL|function|drawControl
DECL|function|drawItemPixmap
DECL|function|drawItemText
DECL|function|drawPrimitive
DECL|function|fromQColor
DECL|function|generatedIconPixmap
DECL|function|getGConfBool
DECL|function|getGConfString
DECL|function|hitTestComplexControl
DECL|function|itemPixmapRect
DECL|function|mergedColors
DECL|function|pixelMetric
DECL|function|polish
DECL|function|polish
DECL|function|polish
DECL|function|qt_gtk_draw_mdibutton
DECL|function|qt_gtk_get_icon
DECL|function|qt_gtk_state
DECL|function|sizeFromContents
DECL|function|standardIcon
DECL|function|standardPalette
DECL|function|standardPixmap
DECL|function|styleHint
DECL|function|subControlRect
DECL|function|subElementRect
DECL|function|unpolish
DECL|function|unpolish
DECL|function|~QGtkStyle
DECL|macro|signals
DECL|variable|dock_widget_close_xpm
DECL|variable|dock_widget_restore_xpm
DECL|variable|groupBoxBottomMargin
DECL|variable|groupBoxTitleMargin
DECL|variable|groupBoxTopMargin
DECL|variable|qt_scrollbar_button_arrow_down
DECL|variable|qt_scrollbar_button_arrow_up
DECL|variable|qt_titlebar_context_help
