DECL|macro|QMACSTYLE_MAC_H
DECL|macro|Q_WIDGETS_EXPORT_STYLE_MAC
DECL|macro|Q_WIDGETS_EXPORT_STYLE_MAC
DECL|variable|QMacStylePrivate
DECL|variable|QPalette
DECL|variable|QPushButton
DECL|variable|QStyleOptionButton
