DECL|function|QProxyStyle
DECL|function|QProxyStyle
DECL|function|baseStyle
DECL|function|drawComplexControl
DECL|function|drawControl
DECL|function|drawItemPixmap
DECL|function|drawItemText
DECL|function|drawPrimitive
DECL|function|ensureBaseStyle
DECL|function|event
DECL|function|generatedIconPixmap
DECL|function|hitTestComplexControl
DECL|function|itemPixmapRect
DECL|function|itemTextRect
DECL|function|layoutSpacing
DECL|function|pixelMetric
DECL|function|polish
DECL|function|polish
DECL|function|polish
DECL|function|setBaseStyle
DECL|function|sizeFromContents
DECL|function|standardIcon
DECL|function|standardPalette
DECL|function|standardPixmap
DECL|function|styleHint
DECL|function|subControlRect
DECL|function|subElementRect
DECL|function|unpolish
DECL|function|unpolish
DECL|function|~QProxyStyle
