DECL|function|QBlendStyleAnimation
DECL|function|QNumberStyleAnimation
DECL|function|QProgressStyleAnimation
DECL|function|QStyleAnimation
DECL|function|animationStep
DECL|function|blendedImage
DECL|function|currentImage
DECL|function|currentValue
DECL|function|delay
DECL|function|duration
DECL|function|endImage
DECL|function|endValue
DECL|function|isUpdateNeeded
DECL|function|isUpdateNeeded
DECL|function|isUpdateNeeded
DECL|function|progressStep
DECL|function|setDelay
DECL|function|setDuration
DECL|function|setEndImage
DECL|function|setEndValue
DECL|function|setSpeed
DECL|function|setStartImage
DECL|function|setStartTime
DECL|function|setStartValue
DECL|function|speed
DECL|function|startImage
DECL|function|startTime
DECL|function|startValue
DECL|function|target
DECL|function|updateCurrentTime
DECL|function|updateCurrentTime
DECL|function|updateTarget
DECL|function|~QStyleAnimation
