DECL|function|angle
DECL|function|calcBigLineSize
DECL|function|calcLines
DECL|function|calcRadialPos
DECL|function|dpiScaled
DECL|function|drawBorderPixmap
DECL|function|drawDial
DECL|function|hasAncestor
DECL|function|uniqueName
DECL|namespace|QStyleHelper
