DECL|macro|QSTYLE_H
DECL|variable|QAction
DECL|variable|QDebug
DECL|variable|QFontMetrics
DECL|variable|QStyleHintReturn
DECL|variable|QStyleOption
DECL|variable|QStyleOptionComplex
DECL|variable|QStylePrivate
DECL|variable|QTab
