DECL|enumerator|SlDown
DECL|enumerator|SlLeft
DECL|enumerator|SlRight
DECL|enumerator|SlUp
DECL|enum|QSliderDirection
DECL|function|QWindowsStyle
DECL|function|QWindowsStyle
DECL|function|QWindowsStylePrivate
DECL|function|colorref2qrgb
DECL|function|drawComplexControl
DECL|function|drawControl
DECL|function|drawPrimitive
DECL|function|eventFilter
DECL|function|hasSeenAlt
DECL|function|pixelMetric
DECL|function|polish
DECL|function|polish
DECL|function|polish
DECL|function|sizeFromContents
DECL|function|standardIcon
DECL|function|standardPixmap
DECL|function|styleHint
DECL|function|subElementRect
DECL|function|unpolish
DECL|function|unpolish
DECL|function|~QWindowsStyle
DECL|macro|COLOR_GRADIENTACTIVECAPTION
DECL|macro|COLOR_GRADIENTINACTIVECAPTION
DECL|macro|PTSARRLEN
DECL|macro|_SHGFI_ICON
DECL|macro|_SHGFI_LARGEICON
DECL|macro|_SHGFI_SMALLICON
DECL|macro|_SIID_SHIELD
DECL|member|cbSize
DECL|member|hIcon
DECL|member|iIcon
DECL|member|iSysImageIndex
DECL|member|szPath
DECL|typedef|PtrSHGetStockIconInfo
DECL|typedef|QSHSTOCKICONINFO
DECL|variable|pSHGetStockIconInfo
