DECL|enumerator|MaskAlpha
DECL|enumerator|NoAlpha
DECL|enumerator|RealAlpha
DECL|enumerator|UnknownAlpha
DECL|enum|AlphaChannelType
DECL|function|ThemeMapData
DECL|function|ThemeMapKey
DECL|function|ThemeMapKey
DECL|function|operator
DECL|function|qHash
DECL|macro|BT_BORDERFILL
DECL|macro|BT_IMAGEFILE
DECL|macro|BT_NONE
DECL|macro|CBS_INACTIVE
DECL|macro|DTBG_CLIPRECT
DECL|macro|DTBG_COMPUTINGREGION
DECL|macro|DTBG_DRAWSOLID
DECL|macro|DTBG_MIRRORDC
DECL|macro|DTBG_OMITBORDER
DECL|macro|DTBG_OMITCONTENT
DECL|macro|GT_IMAGEGLYPH
DECL|macro|GT_NONE
DECL|macro|HBS_INACTIVE
DECL|macro|MAXBS_INACTIVE
DECL|macro|MINBS_INACTIVE
DECL|macro|QWINDOWSXPSTYLE_P_P_H
DECL|macro|RBS_INACTIVE
DECL|macro|TMT_BGTYPE
DECL|macro|TMT_BORDERCOLOR
DECL|macro|TMT_BORDERCOLORHINT
DECL|macro|TMT_BORDERONLY
DECL|macro|TMT_BORDERSIZE
DECL|macro|TMT_CAPTIONMARGINS
DECL|macro|TMT_CONTENTMARGINS
DECL|macro|TMT_FILLCOLOR
DECL|macro|TMT_GLYPHTYPE
DECL|macro|TMT_PROGRESSCHUNKSIZE
DECL|macro|TMT_SIZINGMARGINS
DECL|macro|TMT_TEXTCOLOR
DECL|macro|TMT_TEXTSHADOWCOLOR
DECL|macro|TMT_TEXTSHADOWCOLOR
DECL|macro|TMT_TEXTSHADOWTYPE
DECL|macro|TMT_TRANSPARENTCOLOR
DECL|macro|TST_NONE
DECL|macro|_WIN32_WINNT
DECL|macro|_WIN32_WINNT
DECL|member|alphaType
DECL|member|dataValid
DECL|member|dwFlags
DECL|member|dwSize
DECL|member|hadInvalidAlpha
DECL|member|hasAlphaChannel
DECL|member|hasAnyData
DECL|member|noBorder
DECL|member|noContent
DECL|member|partId
DECL|member|partIsTransparent
DECL|member|rcClip
DECL|member|stateId
DECL|member|theme
DECL|member|wasAlphaSwapped
DECL|struct|ThemeMapData
DECL|struct|ThemeMapKey
DECL|struct|_DTBGOPTS
DECL|typedef|DTBGOPTS
DECL|typedef|PDTBGOPTS
