DECL|class|ColorWidget
DECL|class|MyWindowSurface
DECL|class|tst_QWindowSurface
DECL|function|ColorWidget
DECL|function|MyWindowSurface
DECL|function|VERIFY_COLOR
DECL|function|flush
DECL|function|flushOutsidePaintEvent
DECL|function|getSetWindowSurface
DECL|function|grabWidget
DECL|function|paintDevice
DECL|function|paintEvent
DECL|function|reset
DECL|function|tst_QWindowSurface
DECL|function|~tst_QWindowSurface
DECL|member|color
DECL|member|image
DECL|member|r
