DECL|function|HintControl
DECL|function|TypeControl
DECL|function|WindowStateControl
DECL|function|WindowStatesControl
DECL|function|activeValue
DECL|function|hints
DECL|function|setActiveValue
DECL|function|setHints
DECL|function|setState
DECL|function|setStates
DECL|function|setType
DECL|function|setVisibleValue
DECL|function|setVisibleValue
DECL|function|slotChanged
DECL|function|slotCheckBoxChanged
DECL|function|state
DECL|function|states
DECL|function|type
DECL|function|visibleValue
DECL|function|visibleValue
