DECL|function|bezier1
DECL|function|bezier2
DECL|function|bezier3
DECL|function|bezier4
DECL|function|bezierFlower
DECL|function|bezierQuadrant
DECL|function|body
DECL|function|circleWithHole
DECL|function|clover
DECL|function|deer
DECL|function|ellipses
DECL|function|fire
DECL|function|frame1
DECL|function|frame2
DECL|function|frame3
DECL|function|frame4
DECL|function|heart
DECL|function|heart2
DECL|function|interRect
DECL|function|lips
DECL|function|mailbox
DECL|function|node
DECL|function|oddEvenFill
DECL|function|random1
DECL|function|random2
DECL|function|rect
DECL|function|rect2
DECL|function|rect3
DECL|function|rect4
DECL|function|rect5
DECL|function|rect6
DECL|function|simpleCurve
DECL|function|simpleCurve2
DECL|function|simpleCurve3
DECL|function|squareWithHole
DECL|function|triangle1
DECL|function|triangle2
DECL|function|windingFill
