DECL|class|tst_QVarLengthArray
DECL|function|Foo
DECL|function|Foo
DECL|function|MyBase
DECL|function|MyBase
DECL|function|MyComplex
DECL|function|MyMovable
DECL|function|MyPrimitive
DECL|function|MyPrimitive
DECL|function|append
DECL|function|appendCausingRealloc
DECL|function|contains
DECL|function|count
DECL|function|countMoved
DECL|function|first
DECL|function|hasMoved
DECL|function|indexOf
DECL|function|initializeList
DECL|function|initializeListComplex
DECL|function|initializeListInt
DECL|function|initializeListMovable
DECL|function|last
DECL|function|lastIndexOf
DECL|function|oldTests
DECL|function|operator =
DECL|function|operator =
DECL|function|operator ==
DECL|function|operator ==
DECL|function|operators
DECL|function|realloc
DECL|function|reallocTest
DECL|function|removeLast
DECL|function|resize
DECL|function|reverseIterators
DECL|function|squeeze
DECL|function|~Foo
DECL|function|~MyBase
DECL|function|~MyPrimitive
DECL|member|copyCount
DECL|member|copyCount
DECL|member|data
DECL|member|errorCount
DECL|member|errorCount
DECL|member|i
DECL|member|i
DECL|member|isCopy
DECL|member|liveCount
DECL|member|liveCount
DECL|member|p
DECL|struct|Foo
DECL|struct|MyBase
DECL|struct|MyComplex
DECL|struct|MyMovable
DECL|struct|MyPrimitive
DECL|variable|N
DECL|variable|fooCtor
DECL|variable|fooDtor
DECL|variable|reallocTestProceed
