DECL|class|tst_QVarLengthArray
DECL|function|Foo
DECL|function|Foo
DECL|function|MyBase
DECL|function|MyBase
DECL|function|MyPrimitive
DECL|function|MyPrimitive
DECL|function|QTBUG10978_realloc
DECL|function|QTBUG10978_test
DECL|function|QTBUG6718_resize
DECL|function|append
DECL|function|countMoved
DECL|function|hasMoved
DECL|function|oldTests
DECL|function|operator =
DECL|function|operator =
DECL|function|removeLast
DECL|function|task214223
DECL|function|~Foo
DECL|function|~MyBase
DECL|function|~MyPrimitive
DECL|member|copyCount
DECL|member|copyCount
DECL|member|data
DECL|member|errorCount
DECL|member|errorCount
DECL|member|isCopy
DECL|member|liveCount
DECL|member|liveCount
DECL|member|p
DECL|struct|Foo
DECL|struct|MyBase
DECL|struct|MyComplex
DECL|struct|MyMovable
DECL|struct|MyPrimitive
DECL|variable|N
DECL|variable|QTBUG10978_proceed
DECL|variable|fooCtor
DECL|variable|fooDtor
