DECL|class|CustomRoleModel
DECL|class|ListenerObject
DECL|class|OverrideRoleNames
DECL|class|QtTestModel
DECL|class|SignalArgumentChecker
DECL|class|tst_QAbstractItemModel
DECL|enumerator|Custom1
DECL|enumerator|Custom2
DECL|enumerator|UserRole
DECL|enum|Roles
DECL|function|CustomRoleModel
DECL|function|ListenerObject
DECL|function|OverrideRoleNames
DECL|function|QtTestModel
DECL|function|QtTestModel
DECL|function|SignalArgumentChecker
DECL|function|changePersistentIndex
DECL|function|cleanup
DECL|function|columnCount
DECL|function|complexChangesWithPersistent
DECL|function|data
DECL|function|data
DECL|function|dropMimeData
DECL|function|dropMimeData_data
DECL|function|emitSignals
DECL|function|fillIndexStores
DECL|function|hasChildren
DECL|function|hasChildren
DECL|function|headerData
DECL|function|index
DECL|function|index
DECL|function|init
DECL|function|initTestCase
DECL|function|insertColumns
DECL|function|insertColumns
DECL|function|insertRows
DECL|function|insertRows
DECL|function|itemData
DECL|function|itemFlags
DECL|function|layoutAboutToBeChanged
DECL|function|layoutChanged
DECL|function|match
DECL|function|movePersistentIndex
DECL|function|parent
DECL|function|parent
DECL|function|qStringTableRow
DECL|function|removeColumns
DECL|function|removeColumns
DECL|function|removeRows
DECL|function|removeRows
DECL|function|reset
DECL|function|reset
DECL|function|roleNames
DECL|function|rowCount
DECL|function|setData
DECL|function|setPersistent
DECL|function|slotAboutToBeReset
DECL|function|slotReset
DECL|function|testChildrenLayoutsChanged
DECL|function|testDataChanged
DECL|function|testMoveSameParentDown
DECL|function|testMoveSameParentDown_data
DECL|function|testMoveSameParentUp
DECL|function|testMoveSameParentUp_data
DECL|function|testMoveThroughProxy
DECL|function|testMoveToDescendants
DECL|function|testMoveToGrandParent
DECL|function|testMoveToGrandParent_data
DECL|function|testMoveToSibling
DECL|function|testMoveToSibling_data
DECL|function|testMoveToUncle
DECL|function|testMoveToUncle_data
DECL|function|testMoveWithinOwnRange
DECL|function|testMoveWithinOwnRange_data
DECL|function|testReset
DECL|function|testRoleNames
DECL|macro|STRINGTABLE
DECL|macro|STRINGTABLE
DECL|member|cCount
DECL|member|m_model
DECL|member|m_model
DECL|member|m_nonPersistentIndexes
DECL|member|m_p1
DECL|member|m_p1Persistent
DECL|member|m_p2
DECL|member|m_p2Persistent
DECL|member|m_persistentIndexes
DECL|member|rCount
DECL|member|table
DECL|member|wrongIndex
DECL|typedef|Position
DECL|typedef|Selection
DECL|typedef|StringTable
DECL|typedef|StringTableRow
