DECL|class|DerivedException
DECL|class|IntResult
DECL|class|ResultObject
DECL|class|SignalSlotObject
DECL|class|VoidResult
DECL|class|tst_QFuture
DECL|function|SignalSlotObject
DECL|function|cancel
DECL|function|canceled
DECL|function|clone
DECL|function|createDerivedExceptionFuture
DECL|function|createExceptionFuture
DECL|function|createExceptionResultFuture
DECL|function|exceptions
DECL|function|exceptions_QTBUG18149
DECL|function|finished
DECL|function|future
DECL|function|futureInterface
DECL|function|implicitConversions
DECL|function|indexedResults
DECL|function|iterators
DECL|function|multipleResults
DECL|function|pause
DECL|function|progress
DECL|function|progress
DECL|function|progressRange
DECL|function|progressText
DECL|function|raise
DECL|function|refcounting
DECL|function|resultReady
DECL|function|resultReady
DECL|function|resultStore
DECL|function|resultsAfterFinished
DECL|function|resultsAsList
DECL|function|run
DECL|function|run
DECL|function|statePropagation
DECL|function|testRefCounting
DECL|function|throttling
DECL|function|voidConversions
DECL|macro|QFUTURE_TEST
DECL|member|canceledCalled
DECL|member|finishedCalled
DECL|member|rangeBegin
DECL|member|rangeEnd
DECL|member|reportedProgress
DECL|member|results
DECL|variable|resultCount
DECL|variable|value
