DECL|class|tst_QFontMetrics
DECL|function|averageCharWidth
DECL|function|boundingRect
DECL|function|bypassShaping
DECL|function|cleanup
DECL|function|elidedMultiLength
DECL|function|elidedMultiLengthF
DECL|function|elidedMultiLength_helper
DECL|function|elidedText
DECL|function|elidedText_data
DECL|function|inFontUcs4
DECL|function|init
DECL|function|lineWidth
DECL|function|metrics
DECL|function|same
DECL|function|tst_QFontMetrics
DECL|function|veryNarrowElidedText
DECL|function|~tst_QFontMetrics
