DECL|class|QShivaContext
DECL|class|ShivaVGWindowSurfacePrivate
DECL|function|QShivaContext
DECL|function|ShivaVGWindowSurface
DECL|function|ShivaVGWindowSurfacePrivate
DECL|function|beginPaint
DECL|function|doneCurrent
DECL|function|endPaint
DECL|function|ensureContext
DECL|function|flush
DECL|function|makeCurrent
DECL|function|metric
DECL|function|paintDevice
DECL|function|paintEngine
DECL|function|scroll
DECL|function|setGeometry
DECL|function|~QShivaContext
DECL|function|~ShivaVGWindowSurface
DECL|function|~ShivaVGWindowSurfacePrivate
DECL|macro|GL_GLEXT_PROTOTYPES
DECL|member|context
DECL|member|currentSize
DECL|member|currentSurface
DECL|member|drawable
DECL|member|engine
DECL|member|fbo
DECL|member|initialized
DECL|member|isCurrent
DECL|member|needsResize
DECL|member|size
DECL|member|texture
