DECL|enumerator|MedianSize
DECL|enumerator|TargetRatio
DECL|function|BlockSizeManager
DECL|function|blockSize
DECL|function|elapsed
DECL|function|getticks
DECL|function|getticks
DECL|function|getticks
DECL|function|timeAfterUser
DECL|function|timeBeforeUser
DECL|namespace|QtConcurrent
