DECL|function|NorwegianWoodStyle
DECL|function|drawControl
DECL|function|drawPrimitive
DECL|function|pixelMetric
DECL|function|polish
DECL|function|polish
DECL|function|roundRectPath
DECL|function|setTexture
DECL|function|styleHint
DECL|function|unpolish
