DECL|class|Blob
DECL|function|AddRef
DECL|function|Blob
DECL|function|D3DCompile
DECL|function|GetBufferPointer
DECL|function|GetBufferSize
DECL|function|QueryInterface
DECL|function|Release
DECL|function|cacheKeyFor
DECL|function|loadCompiler
DECL|function|makePath
DECL|function|serviceAvailable
DECL|function|~Blob
DECL|member|IID_ID3DBlob
DECL|member|IID_IUnknown
DECL|member|compile
DECL|member|m_data
DECL|member|m_ref
DECL|namespace|D3DCompiler
DECL|typedef|D3DCompileFunc
