DECL|function|GLWidget
DECL|function|initializeGL
DECL|function|minimumSizeHint
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|paintGL
DECL|function|qNormalizeAngle
DECL|function|resizeGL
DECL|function|setXRotation
DECL|function|setYRotation
DECL|function|setZRotation
DECL|function|sizeHint
DECL|function|~GLWidget
DECL|macro|GL_MULTISAMPLE
