DECL|class|FontBlaster
DECL|function|FontBlaster
DECL|function|keyPressEvent
DECL|function|main
DECL|function|mousePressEvent
DECL|function|nextMode
DECL|function|paintDifferentFontStyles
DECL|function|paintEvent
DECL|function|paintInternationalText
DECL|function|paintLongLatinText
DECL|member|function
DECL|member|m_currentMode
DECL|member|m_lastMeasurements
DECL|member|m_modes
DECL|member|m_modes
DECL|member|m_modesCount
DECL|member|m_modesCount
DECL|member|m_timer
DECL|member|name
DECL|struct|mode
DECL|variable|lastMeasurementsCount
