DECL|function|bannerPageToString
DECL|function|clearCupsOption
DECL|function|cupsOptionsList
DECL|function|jobHoldToString
DECL|function|setBannerPages
DECL|function|setCupsOption
DECL|function|setCupsOptions
DECL|function|setJobBilling
DECL|function|setJobHold
DECL|function|setJobPriority
DECL|function|setPageRange
DECL|function|setPageSet
DECL|function|setPagesPerSheetLayout
