DECL|enumerator|HBitmapAlpha
DECL|enumerator|HBitmapNoAlpha
DECL|enumerator|HBitmapPremultipliedAlpha
DECL|enum|HBitmapFormat
DECL|function|QWin32PrintEngine
DECL|function|abort
DECL|function|begin
DECL|function|composeGdiPath
DECL|function|createGlobalDevNames
DECL|function|doReinit
DECL|function|drawPath
DECL|function|drawPixmap
DECL|function|drawPolygon
DECL|function|drawTextItem
DECL|function|drawTiledPixmap
DECL|function|draw_text_item_win
DECL|function|end
DECL|function|fillPath
DECL|function|fillPath_dev
DECL|function|findCustomPaperSize
DECL|function|getDC
DECL|function|getPageMargins
DECL|function|globalDevMode
DECL|function|inchesToMM
DECL|function|initDevRects
DECL|function|initHDC
DECL|function|initialize
DECL|function|mapDevmodePaperSize
DECL|function|mapDevmodePaperSource
DECL|function|mapPaperSizeDevmode
DECL|function|mapPaperSourceDevmode
DECL|function|metric
DECL|function|mmToInches
DECL|function|newPage
DECL|function|printerPaperSizes
DECL|function|printerState
DECL|function|property
DECL|function|queryDefault
DECL|function|queryDefaultPrinter
DECL|function|queryResolutions
DECL|function|qwcsnlen
DECL|function|release
DECL|function|releaseDC
DECL|function|setDevModePaperFlags
DECL|function|setGlobalDevMode
DECL|function|setPageMargins
DECL|function|setProperty
DECL|function|strokePath
DECL|function|strokePath_dev
DECL|function|supportedPaperSizes
DECL|function|supportedSizesWithNames
DECL|function|updateClipPath
DECL|function|updateCustomPaperSize
DECL|function|updateMatrix
DECL|function|updateOrigin
DECL|function|updateState
DECL|function|~QWin32PrintEnginePrivate
DECL|member|qtSizeName
DECL|member|qtSourceName
DECL|member|winSizeName
DECL|member|winSourceName
DECL|variable|dmMapping
DECL|variable|sources
