DECL|class|QPrinterInfoPrivateDeleter
DECL|function|QPrinterInfo
DECL|function|QPrinterInfo
DECL|function|QPrinterInfo
DECL|function|QPrinterInfo
DECL|function|QPrinterInfoPrivate
DECL|function|availablePrinterNames
DECL|function|availablePrinters
DECL|function|cleanup
DECL|function|defaultDuplexMode
DECL|function|defaultPageSize
DECL|function|defaultPrinter
DECL|function|defaultPrinterName
DECL|function|description
DECL|function|isDefault
DECL|function|isNull
DECL|function|isRemote
DECL|function|location
DECL|function|makeAndModel
DECL|function|maximumPhysicalPageSize
DECL|function|minimumPhysicalPageSize
DECL|function|operator =
DECL|function|printerInfo
DECL|function|printerName
DECL|function|state
DECL|function|supportedDuplexModes
DECL|function|supportedPageSizes
DECL|function|supportedPaperSizes
DECL|function|supportedResolutions
DECL|function|supportedSizesWithNames
DECL|function|supportsCustomPageSizes
DECL|function|~QPrinterInfo
DECL|function|~QPrinterInfoPrivate
