DECL|function|QPdfPrintEngine
DECL|function|QPdfPrintEngine
DECL|function|QPdfPrintEnginePrivate
DECL|function|begin
DECL|function|closePrintDevice
DECL|function|end
DECL|function|metric
DECL|function|newPage
DECL|function|openPrintDevice
DECL|function|property
DECL|function|setProperty
DECL|function|~QPdfPrintEngine
DECL|function|~QPdfPrintEnginePrivate
