DECL|function|QPrintDevice
DECL|function|QPrintDevice
DECL|function|QPrintDevice
DECL|function|QPrintDevice
DECL|function|defaultColorMode
DECL|function|defaultDuplexMode
DECL|function|defaultInputSlot
DECL|function|defaultOutputBin
DECL|function|defaultPageSize
DECL|function|defaultResolution
DECL|function|format
DECL|function|id
DECL|function|isDefault
DECL|function|isRemote
DECL|function|isValid
DECL|function|isValidPageLayout
DECL|function|location
DECL|function|makeAndModel
DECL|function|maximumPhysicalPageSize
DECL|function|minimumPhysicalPageSize
DECL|function|name
DECL|function|operator <<
DECL|function|operator =
DECL|function|operator ==
DECL|function|printableMargins
DECL|function|state
DECL|function|supportedColorModes
DECL|function|supportedDuplexModes
DECL|function|supportedInputSlots
DECL|function|supportedMimeTypes
DECL|function|supportedOutputBins
DECL|function|supportedPageSize
DECL|function|supportedPageSize
DECL|function|supportedPageSize
DECL|function|supportedPageSize
DECL|function|supportedPageSize
DECL|function|supportedPageSizes
DECL|function|supportedResolutions
DECL|function|supportsCollateCopies
DECL|function|supportsCustomPageSizes
DECL|function|supportsMultipleCopies
DECL|function|~QPrintDevice
