DECL|enumerator|HBitmapAlpha
DECL|enumerator|HBitmapNoAlpha
DECL|enumerator|HBitmapPremultipliedAlpha
DECL|enum|HBitmapFormat
DECL|function|QWin32PrintEngine
DECL|function|abort
DECL|function|begin
DECL|function|composeGdiPath
DECL|function|createGlobalDevNames
DECL|function|debugMetrics
DECL|function|doReinit
DECL|function|drawPath
DECL|function|drawPixmap
DECL|function|drawPolygon
DECL|function|drawTextItem
DECL|function|drawTiledPixmap
DECL|function|draw_text_item_win
DECL|function|end
DECL|function|fillPath
DECL|function|fillPath_dev
DECL|function|getDC
DECL|function|globalDevMode
DECL|function|indexOfId
DECL|function|indexOfWindowsId
DECL|function|initHDC
DECL|function|initialize
DECL|function|metric
DECL|function|msgBeginFailed
DECL|function|newPage
DECL|function|printerState
DECL|function|property
DECL|function|release
DECL|function|releaseDC
DECL|function|resetDC
DECL|function|setGlobalDevMode
DECL|function|setPageSize
DECL|function|setProperty
DECL|function|strokePath
DECL|function|strokePath_dev
DECL|function|updateClipPath
DECL|function|updateMatrix
DECL|function|updateMetrics
DECL|function|updatePageLayout
DECL|function|updateState
DECL|function|~QWin32PrintEnginePrivate
