DECL|class|DestroyThread
DECL|class|MyObject
DECL|class|RaceObject
DECL|class|RaceThread
DECL|class|tst_QObjectRace
DECL|enumerator|OneMinute
DECL|enumerator|TenMinutes
DECL|enumerator|TwentyFiveMinutes
DECL|enumerator|TwoMinutes
DECL|function|RaceObject
DECL|function|RaceThread
DECL|function|addThread
DECL|function|checkStopWatch
DECL|function|destroSlot
DECL|function|destroyRace
DECL|function|moveToThreadRace
DECL|function|run
DECL|function|run
DECL|function|setObject
DECL|function|setObjects
DECL|function|slot1
DECL|function|slot2
DECL|function|slot3
DECL|function|slot4
DECL|function|slot5
DECL|function|slot6
DECL|function|slot7
DECL|function|start
DECL|function|theSlot
DECL|macro|EXTRA_THREAD_WAIT
DECL|macro|EXTRA_THREAD_WAIT
DECL|macro|MAIN_THREAD_WAIT
DECL|macro|MAIN_THREAD_WAIT
DECL|member|count
DECL|member|number
DECL|member|object
DECL|member|objects
DECL|member|stopWatch
DECL|member|threads
