DECL|variable|a2
DECL|variable|d
DECL|variable|doc
DECL|variable|doc
DECL|variable|docElem
DECL|variable|document
DECL|variable|e
DECL|variable|elem
DECL|variable|element
DECL|variable|element1
DECL|variable|element2
DECL|variable|element3
DECL|variable|element4
DECL|variable|elt
DECL|variable|elt1
DECL|variable|elt2
DECL|variable|elt3
DECL|variable|impl
DECL|variable|n
DECL|variable|n
DECL|variable|root
DECL|variable|t
DECL|variable|tag
DECL|variable|xml
