DECL|function|UserObjectComparison
DECL|function|data
DECL|function|length
DECL|function|runscript
DECL|function|v8test_eval
DECL|function|v8test_evalwithinwith
DECL|function|v8test_externalteardown
DECL|function|v8test_globalcall
DECL|function|v8test_userobjectcompare
DECL|function|~MyResource
DECL|function|~MyStringResource
DECL|macro|BEGINTEST
DECL|macro|ENDTEST
DECL|macro|SET_EXPECTED
DECL|macro|SOURCE
DECL|macro|SOURCE
DECL|macro|SOURCE
DECL|macro|SOURCE
DECL|macro|VERIFY
DECL|member|wasDestroyed
DECL|member|wasDestroyed
DECL|member|wasDestroyed
DECL|member|wasDestroyed
DECL|struct|MyResource
DECL|struct|MyStringResource
DECL|variable|expectedLhs
DECL|variable|expectedObjectsCompared
DECL|variable|expectedRhs
DECL|variable|userObjectComparisonCalled
DECL|variable|userObjectComparisonReturn
