DECL|enumerator|XCursorShape
DECL|enumerator|XFocusIn
DECL|enumerator|XFocusOut
DECL|enumerator|XGrayScale
DECL|enumerator|XKeyPress
DECL|enumerator|XKeyRelease
DECL|enumerator|XNone
DECL|enumerator|XRevertToParent
DECL|function|qglx_buildSpec
DECL|function|qglx_findConfig
DECL|function|qglx_findVisualInfo
DECL|function|qglx_platformWindowFromGLXFBConfig
DECL|function|qglx_reducePlatformWindowFormat
DECL|macro|CursorShape
DECL|macro|FocusIn
DECL|macro|FocusOut
DECL|macro|FontChange
DECL|macro|GrayScale
DECL|macro|KeyPress
DECL|macro|KeyRelease
DECL|macro|None
DECL|macro|RevertToParent
