DECL|function|QQnxRasterWindow
DECL|function|adjustBufferSize
DECL|function|blitPreviousToCurrent
DECL|function|pixelFormat
DECL|function|post
DECL|function|renderBuffer
DECL|function|resetBuffers
DECL|function|scroll
DECL|macro|qRasterWindowDebug
DECL|macro|qRasterWindowDebug
