DECL|function|QQnxIntegration
DECL|function|addWindow
DECL|function|clipboard
DECL|function|createDisplay
DECL|function|createDisplays
DECL|function|createPlatformBackingStore
DECL|function|createPlatformOpenGLContext
DECL|function|createPlatformTheme
DECL|function|createPlatformWindow
DECL|function|destroyDisplays
DECL|function|drag
DECL|function|guiThreadEventDispatcher
DECL|function|hasCapability
DECL|function|inputContext
DECL|function|moveToScreen
DECL|function|nativeInterface
DECL|function|primaryDisplay
DECL|function|removeDisplay
DECL|function|removeWindow
DECL|function|screenForNative
DECL|function|services
DECL|function|styleHint
DECL|function|supportsNavigatorEvents
DECL|function|themeNames
DECL|function|window
DECL|function|~QQnxIntegration
DECL|macro|qIntegrationDebug
DECL|macro|qIntegrationDebug
DECL|member|ms_windowMapper
DECL|member|ms_windowMapperMutex
