DECL|function|QQnxGLContext
DECL|function|checkEGLError
DECL|function|contextAttrs
DECL|function|doneCurrent
DECL|function|getEglDisplay
DECL|function|getProcAddress
DECL|function|initialize
DECL|function|makeCurrent
DECL|function|shutdown
DECL|function|swapBuffers
DECL|function|~QQnxGLContext
DECL|macro|qGLContextDebug
DECL|macro|qGLContextDebug
DECL|member|ms_eglDisplay
