DECL|function|QQnxNavigatorEventNotifier
DECL|function|handleMessage
DECL|function|parsePPS
DECL|function|readData
DECL|function|replyPPS
DECL|function|start
DECL|function|~QQnxNavigatorEventNotifier
DECL|variable|navigatorControlPath
DECL|variable|ppsBufferSize
