DECL|function|QQnxScreen
DECL|function|activateWindowGroup
DECL|function|addOverlayWindow
DECL|function|addWindow
DECL|function|availableGeometry
DECL|function|cursor
DECL|function|deactivateWindowGroup
DECL|function|defaultDepth
DECL|function|depth
DECL|function|determineScreenSize
DECL|function|findWindow
DECL|function|isOrthogonal
DECL|function|keyboardHeightChanged
DECL|function|lowerWindow
DECL|function|nativeOrientation
DECL|function|newWindowCreated
DECL|function|onWindowPost
DECL|function|orientation
DECL|function|raiseWindow
DECL|function|refreshRate
DECL|function|removeOverlayWindow
DECL|function|removeWindow
DECL|function|resizeNativeWidgetWindow
DECL|function|resizeTopLevelWindow
DECL|function|resizeWindows
DECL|function|setRotation
DECL|function|updateHierarchy
DECL|function|windowClosed
DECL|function|~QQnxScreen
DECL|macro|QQNX_PHYSICAL_SCREEN_SIZE_DEFINED
DECL|macro|qScreenDebug
DECL|macro|qScreenDebug
