DECL|function|QQnxNavigatorPps
DECL|function|openPpsConnection
DECL|function|parsePPS
DECL|function|requestInvokeUrl
DECL|function|sendPpsMessage
DECL|function|~QQnxNavigatorPps
DECL|macro|qNavigatorDebug
DECL|macro|qNavigatorDebug
DECL|variable|navigatorControlPath
DECL|variable|ppsBufferSize
