DECL|function|QQnxVirtualKeyboardPps
DECL|function|applyKeyboardOptions
DECL|function|close
DECL|function|connect
DECL|function|enterKeyTypeStr
DECL|function|handleKeyboardInfoMessage
DECL|function|hideKeyboard
DECL|function|keyboardModeStr
DECL|function|ppsDataReady
DECL|function|prepareToSend
DECL|function|queryPPSInfo
DECL|function|showKeyboard
DECL|function|start
DECL|function|writeCurrentPPSEncoder
DECL|function|~QQnxVirtualKeyboardPps
DECL|macro|qVirtualKeyboardDebug
DECL|macro|qVirtualKeyboardDebug
DECL|member|ms_PPSPath
DECL|member|ms_bufferSize
