DECL|function|QQnxWindow
DECL|function|adjustBufferSize
DECL|function|applyWindowState
DECL|function|blitFrom
DECL|function|blitHelper
DECL|function|blitPreviousToCurrent
DECL|function|createEGLSurface
DECL|function|destroyEGLSurface
DECL|function|findWindow
DECL|function|gainedFocus
DECL|function|getSurface
DECL|function|isExposed
DECL|function|lower
DECL|function|minimize
DECL|function|platformWindowFormatToNativeFormat
DECL|function|post
DECL|function|propagateSizeHints
DECL|function|raise
DECL|function|removeFromParent
DECL|function|renderBuffer
DECL|function|requestActivateWindow
DECL|function|requestedBufferSize
DECL|function|scroll
DECL|function|setBufferSize
DECL|function|setGeometry
DECL|function|setGeometryHelper
DECL|function|setOffset
DECL|function|setOpacity
DECL|function|setParent
DECL|function|setPlatformOpenGLContext
DECL|function|setScreen
DECL|function|setVisible
DECL|function|setWindowState
DECL|function|swapEGLBuffers
DECL|function|updateVisibility
DECL|function|updateZorder
DECL|function|~QQnxWindow
DECL|macro|qWindowDebug
DECL|macro|qWindowDebug
