DECL|function|QQnxInputContext
DECL|function|filterEvent
DECL|function|handleKeyboardEvent
DECL|function|hasPhysicalKeyboard
DECL|function|hideInputPanel
DECL|function|isInputPanelVisible
DECL|function|isValid
DECL|function|keyboardLocaleChanged
DECL|function|keyboardRect
DECL|function|keyboardVisibilityChanged
DECL|function|locale
DECL|function|reset
DECL|function|setFocusObject
DECL|function|showInputPanel
DECL|function|~QQnxInputContext
DECL|macro|qInputContextDebug
DECL|macro|qInputContextDebug
