DECL|function|QQnxIntegration
DECL|function|addWindow
DECL|function|clipboard
DECL|function|createDisplays
DECL|function|createPlatformBackingStore
DECL|function|createPlatformOpenGLContext
DECL|function|createPlatformWindow
DECL|function|destroyDisplays
DECL|function|guiThreadEventDispatcher
DECL|function|hasCapability
DECL|function|inputContext
DECL|function|moveToScreen
DECL|function|nativeInterface
DECL|function|primaryDisplay
DECL|function|removeWindow
DECL|function|services
DECL|function|styleHint
DECL|function|window
DECL|function|~QQnxIntegration
DECL|member|ms_windowMapper
DECL|member|ms_windowMapperMutex
