DECL|function|QQnxScreen
DECL|function|addWindow
DECL|function|availableGeometry
DECL|function|defaultDepth
DECL|function|depth
DECL|function|findWindow
DECL|function|isOrthogonal
DECL|function|keyboardHeightChanged
DECL|function|lowerWindow
DECL|function|onWindowPost
DECL|function|raiseWindow
DECL|function|removeWindow
DECL|function|setRotation
DECL|function|updateHierarchy
DECL|function|~QQnxScreen
