DECL|class|tst_QFileSelector
DECL|function|basicTest
DECL|function|basicTest_data
DECL|function|tst_QFileSelector
DECL|function|urlConvenience
DECL|function|urlConvenience_data
DECL|variable|selectorIndicator
