DECL|function|QItemSelection
DECL|function|QItemSelectionModel
DECL|function|QItemSelectionModel
DECL|function|QItemSelectionModel
DECL|function|_q_columnsAboutToBeInserted
DECL|function|_q_columnsAboutToBeRemoved
DECL|function|_q_layoutAboutToBeChanged
DECL|function|_q_layoutChanged
DECL|function|_q_rowsAboutToBeInserted
DECL|function|_q_rowsAboutToBeRemoved
DECL|function|clear
DECL|function|clearCurrentIndex
DECL|function|clearSelection
DECL|function|columnIntersectsSelection
DECL|function|contains
DECL|function|currentIndex
DECL|function|emitSelectionChanged
DECL|function|expandSelection
DECL|function|hasSelection
DECL|function|indexes
DECL|function|indexes
DECL|function|indexesFromRange
DECL|function|initModel
DECL|function|intersected
DECL|function|intersects
DECL|function|isColumnSelected
DECL|function|isEmpty
DECL|function|isRowSelected
DECL|function|isSelected
DECL|function|merge
DECL|function|mergeIndexes
DECL|function|mergeRowLengths
DECL|function|model
DECL|function|operator <<
DECL|function|qSelectionPersistentRowLengths
DECL|function|qSelectionPersistentindexes
DECL|function|reset
DECL|function|rowIntersectsSelection
DECL|function|rowLengthsFromRange
DECL|function|select
DECL|function|select
DECL|function|select
DECL|function|selectedColumns
DECL|function|selectedIndexes
DECL|function|selectedRows
DECL|function|selection
DECL|function|setCurrentIndex
DECL|function|split
DECL|function|~QItemSelectionModel
