DECL|function|QStringListModel
DECL|function|QStringListModel
DECL|function|ascendingLessThan
DECL|function|data
DECL|function|decendingLessThan
DECL|function|flags
DECL|function|insertRows
DECL|function|removeRows
DECL|function|rowCount
DECL|function|setData
DECL|function|setStringList
DECL|function|sibling
DECL|function|sort
DECL|function|stringList
DECL|function|supportedDropActions
