DECL|class|CustomEffect
DECL|class|CustomItem
DECL|class|PaddingEffect
DECL|class|tst_QGraphicsEffectSource
DECL|function|CustomEffect
DECL|function|CustomItem
DECL|function|PaddingEffect
DECL|function|boundingRect
DECL|function|boundingRectFor
DECL|function|boundingRectFor
DECL|function|cleanupTestCase
DECL|function|clippedBoundingRect
DECL|function|deviceRect
DECL|function|draw
DECL|function|draw
DECL|function|draw
DECL|function|graphicsItem
DECL|function|init
DECL|function|initTestCase
DECL|function|isPixmap
DECL|function|margin
DECL|function|paint
DECL|function|pixmap
DECL|function|pixmapPadding
DECL|function|pixmapPadding_data
DECL|function|reset
DECL|function|reset
DECL|function|setMargin
DECL|function|sourceBoundingRectChanged
DECL|function|sourceChanged
DECL|function|styleOption
DECL|function|update
DECL|member|coordinateMode
DECL|member|deviceCoordinatesPixmap
DECL|member|deviceRect
DECL|member|doNothingInDraw
DECL|member|effect
DECL|member|item
DECL|member|m_margin
DECL|member|m_painter
DECL|member|m_painter
DECL|member|m_source
DECL|member|m_sourceBoundingRectChanged
DECL|member|m_sourceChanged
DECL|member|numRepaints
DECL|member|numRepaints
DECL|member|offset
DECL|member|padMode
DECL|member|pix
DECL|member|scene
DECL|member|sourceDeviceBoundingRect
DECL|member|storeDeviceDependentStuff
DECL|member|view
