DECL|function|QWSInputContext
DECL|function|activeWidget
DECL|function|isComposing
DECL|function|mouseHandler
DECL|function|reset
DECL|function|setFocusWidget
DECL|function|translateIMEvent
DECL|function|translateIMInitEvent
DECL|function|translateIMQueryEvent
DECL|function|update
DECL|function|updateImeStatus
DECL|function|widgetDestroyed
DECL|variable|activeWidget
DECL|variable|qt_qws_inputMethodStatusChanged
