DECL|function|QXIMInputContext
DECL|function|clear
DECL|function|close_xim
DECL|function|createICData
DECL|function|create_xim
DECL|function|getFontSet
DECL|function|icData
DECL|function|identifierName
DECL|function|isComposing
DECL|function|language
DECL|function|mouseHandler
DECL|function|reset
DECL|function|setFocusWidget
DECL|function|update
DECL|function|widgetDestroyed
DECL|function|x11FilterEvent
DECL|function|xic_done_callback
DECL|function|xic_draw_callback
DECL|function|xic_start_callback
DECL|function|xim_create_callback
DECL|function|xim_destroy_callback
DECL|function|~QXIMInputContext
DECL|macro|XIM_DEBUG
DECL|member|xim_style
DECL|variable|fontsetCache
DECL|variable|fontsetRefCount
DECL|variable|fontsetnames
DECL|variable|xim_default_style
