DECL|function|QNmDBusHelper
DECL|function|deviceStateChanged
DECL|function|slotAccessPointAdded
DECL|function|slotAccessPointRemoved
DECL|function|slotPropertiesChanged
DECL|function|slotSettingsRemoved
DECL|function|~QNmDBusHelper
