DECL|class|tst_QVector
DECL|function|Foo
DECL|function|Foo
DECL|function|append
DECL|function|at
DECL|function|capacity
DECL|function|clear
DECL|function|constData
DECL|function|const_shared_null
DECL|function|constructors
DECL|function|contains
DECL|function|count
DECL|function|data
DECL|function|empty
DECL|function|endsWith
DECL|function|fill
DECL|function|first
DECL|function|fromList
DECL|function|fromStdVector
DECL|function|indexOf
DECL|function|initializeList
DECL|function|insert
DECL|function|isEmpty
DECL|function|last
DECL|function|lastIndexOf
DECL|function|mid
DECL|function|operator =
DECL|function|outOfMemory
DECL|function|prepend
DECL|function|reallocAfterCopy
DECL|function|reallocAfterCopy_data
DECL|function|remove
DECL|function|reserve
DECL|function|size
DECL|function|startsWith
DECL|function|swap
DECL|function|testOperators
DECL|function|toList
DECL|function|toStdVector
DECL|function|value
DECL|function|~Foo
DECL|member|p
DECL|struct|Foo
DECL|variable|fooCtor
DECL|variable|fooDtor
