DECL|class|tst_QDate
DECL|function|addDays
DECL|function|addDays_data
DECL|function|addMonths
DECL|function|addMonths_data
DECL|function|addYears
DECL|function|addYears_data
DECL|function|dayOfWeek
DECL|function|dayOfWeek_data
DECL|function|dayOfYear
DECL|function|dayOfYear_data
DECL|function|daysInMonth
DECL|function|daysInMonth_data
DECL|function|daysInYear
DECL|function|daysInYear_data
DECL|function|daysTo
DECL|function|defDate
DECL|function|fromStringDateFormat
DECL|function|fromStringDateFormat_data
DECL|function|fromStringFormat
DECL|function|fromStringFormat_data
DECL|function|getDate
DECL|function|invalidDate
DECL|function|isLeapYear
DECL|function|isNull
DECL|function|isNull_data
DECL|function|isValid
DECL|function|isValid_data
DECL|function|julianDay
DECL|function|julianDay_data
DECL|function|julianDaysLimits
DECL|function|longDayName
DECL|function|longMonthName
DECL|function|negativeYear
DECL|function|operator_eq_eq
DECL|function|operator_eq_eq_data
DECL|function|operator_gt
DECL|function|operator_gt_eq
DECL|function|operator_insert_extract
DECL|function|operator_insert_extract_data
DECL|function|operator_lt
DECL|function|operator_lt_eq
DECL|function|printNegativeYear
DECL|function|roundtrip
DECL|function|roundtripGermanLocale
DECL|function|shortDayName
DECL|function|shortMonthName
DECL|function|standaloneLongDayName
DECL|function|standaloneLongMonthName
DECL|function|standaloneShortDayName
DECL|function|standaloneShortMonthName
DECL|function|toStringDateFormat
DECL|function|toStringDateFormat_data
DECL|function|toStringFormat
DECL|function|toStringFormat_data
DECL|function|weekNumber
DECL|function|weekNumber_data
DECL|function|weekNumber_invalid
DECL|function|weekNumber_invalid_data
DECL|function|yearsZeroToNinetyNine
