DECL|function|PathStrokeControls
DECL|function|PathStrokeRenderer
DECL|function|PathStrokeWidget
DECL|function|createCommonControls
DECL|function|emitOkSignal
DECL|function|emitQuitSignal
DECL|function|event
DECL|function|hideControls
DECL|function|initializePoints
DECL|function|layoutForDesktop
DECL|function|layoutForSmallScreens
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|paint
DECL|function|setAnimation
DECL|function|setStyle
DECL|function|showControls
DECL|function|timerEvent
DECL|function|updatePoints
