DECL|class|tst_QSet
DECL|function|begin
DECL|function|capacity
DECL|function|clear
DECL|function|contains
DECL|function|containsSet
DECL|function|detach
DECL|function|end
DECL|function|initializerList
DECL|function|insert
DECL|function|isDetached
DECL|function|javaIterator
DECL|function|javaMutableIterator
DECL|function|makeSureTheComfortFunctionsCompile
DECL|function|operator_eq
DECL|function|remove
DECL|function|reserve
DECL|function|setOperations
DECL|function|size
DECL|function|squeeze
DECL|function|stlIterator
DECL|function|stlMutableIterator
DECL|function|swap
DECL|function|toNumber
