DECL|macro|MAINWINDOW_H
DECL|variable|QAbstractItemModel
DECL|variable|QCheckBox
DECL|variable|QComboBox
DECL|variable|QCompleter
DECL|variable|QLabel
DECL|variable|QLineEdit
DECL|variable|QProgressBar
DECL|variable|QSpinBox
