DECL|class|QDesktopWidgetPrivate
DECL|function|QDesktopWidget
DECL|function|QDesktopWidgetPrivate
DECL|function|availableGeometry
DECL|function|cleanup
DECL|function|enumCallback
DECL|function|init
DECL|function|isVirtualDesktop
DECL|function|numScreens
DECL|function|primaryScreen
DECL|function|qt_get_sip_info
DECL|function|resizeEvent
DECL|function|screen
DECL|function|screenGeometry
DECL|function|screenNumber
DECL|function|screenNumber
DECL|function|~QDesktopWidget
DECL|function|~QDesktopWidgetPrivate
DECL|member|cbSize
DECL|member|dwFlags
DECL|member|enumDisplayMonitors
DECL|member|enumDisplayMonitors
DECL|member|getMonitorInfo
DECL|member|getMonitorInfo
DECL|member|primaryScreen
DECL|member|primaryScreen
DECL|member|rcMonitor
DECL|member|rcWork
DECL|member|rects
DECL|member|rects
DECL|member|refcount
DECL|member|refcount
DECL|member|screenCount
DECL|member|screenCount
DECL|member|workrects
DECL|member|workrects
DECL|struct|MONITORINFO
DECL|typedef|EnumFunc
DECL|typedef|EnumProc
DECL|typedef|InfoFunc
DECL|variable|screen_number
