DECL|function|cleanup
DECL|function|defaultFamily
DECL|function|handle
DECL|function|initialize
DECL|function|lastResortFamily
DECL|function|lastResortFont
DECL|function|pixelSize
DECL|function|pointSize
DECL|function|qt_LOGFONTtoQFont
DECL|function|rawName
DECL|function|setRawName
