DECL|function|addFontToDatabase
DECL|function|fontNameSubstitute
DECL|function|getEnglishName
DECL|function|getEnglishName
DECL|function|getFamiliesAndSignatures
DECL|function|getFontTable
DECL|function|getTrueTypeFontOffsets
DECL|function|getUShort
DECL|function|initFontInfo
DECL|function|initFontInfo
DECL|function|initializeDb
DECL|function|load
DECL|function|load
DECL|function|loadEngine
DECL|function|loadWin
DECL|function|localizedName
DECL|function|populate_database
DECL|function|qt_load_font_engine_win
DECL|function|registerFont
DECL|function|removeAllApplicationFonts
DECL|function|removeApplicationFont
DECL|function|storeFont
DECL|function|styleHint
DECL|function|supportsThreadedFontRendering
DECL|function|systemFont
DECL|macro|DEFAULT_GUI_FONT
DECL|macro|FR_PRIVATE
DECL|macro|MAKE_TAG
DECL|macro|MAKE_TAG
DECL|typedef|PtrAddFontMemResourceEx
DECL|typedef|PtrAddFontResourceExW
DECL|typedef|PtrRemoveFontMemResourceEx
DECL|typedef|PtrRemoveFontResourceExW
DECL|variable|ch_CN_tryFonts
DECL|variable|ch_TW_tryFonts
DECL|variable|jp_tryFonts
DECL|variable|kr_tryFonts
DECL|variable|other_tryFonts
DECL|variable|stock_sysfont
DECL|variable|tryFonts
