DECL|enumerator|PreeditFormat
DECL|enumerator|SelectionFormat
DECL|enum|StandardFormat
DECL|function|DefWindowProc
DECL|function|QWinInputContext
DECL|function|TranslateMessage
DECL|function|composition
DECL|function|enable
DECL|function|enableIme
DECL|function|enablePopupChild
DECL|function|endComposition
DECL|function|findParentforPopup
DECL|function|getCompositionString
DECL|function|getContext
DECL|function|getCursorPosition
DECL|function|getDefaultIMEWnd
DECL|function|getString
DECL|function|isComposing
DECL|function|isInPopup
DECL|function|isPopup
DECL|function|language
DECL|function|mouseHandler
DECL|function|notifyIME
DECL|function|reconvertString
DECL|function|releaseContext
DECL|function|reset
DECL|function|setFocusWidget
DECL|function|startComposition
DECL|function|update
DECL|function|updateImeStatus
DECL|function|~QWinInputContext
DECL|macro|IFMETHOD
DECL|macro|LGRPID_ARABIC
DECL|macro|LGRPID_ARMENIAN
DECL|macro|LGRPID_BALTIC
DECL|macro|LGRPID_CENTRAL_EUROPE
DECL|macro|LGRPID_CYRILLIC
DECL|macro|LGRPID_GEORGIAN
DECL|macro|LGRPID_GREEK
DECL|macro|LGRPID_HEBREW
DECL|macro|LGRPID_INDIC
DECL|macro|LGRPID_INSTALLED
DECL|macro|LGRPID_JAPANESE
DECL|macro|LGRPID_KOREAN
DECL|macro|LGRPID_SIMPLIFIED_CHINESE
DECL|macro|LGRPID_SUPPORTED
DECL|macro|LGRPID_THAI
DECL|macro|LGRPID_TRADITIONAL_CHINESE
DECL|macro|LGRPID_TURKISH
DECL|macro|LGRPID_VIETNAMESE
DECL|macro|LGRPID_WESTERN_EUROPE
DECL|variable|IEnumInputContext
DECL|variable|IEnumRegisterWordW
DECL|variable|WM_MSIME_MOUSE
DECL|variable|aimm
DECL|variable|aimmpump
DECL|variable|defaultContext
DECL|variable|haveCaret
DECL|variable|imeComposition
DECL|variable|imePosition
DECL|variable|qt_use_rtl_extensions
