DECL|class|IconEngine
DECL|class|tst_QIcon
DECL|function|actualSize
DECL|function|actualSize2
DECL|function|actualSize2_data
DECL|function|actualSize_data
DECL|function|addFile
DECL|function|availableSizes
DECL|function|bestMatch
DECL|function|cacheKey
DECL|function|cleanup
DECL|function|detach
DECL|function|fromTheme
DECL|function|haveImageFormat
DECL|function|init
DECL|function|isNull
DECL|function|name
DECL|function|operator <
DECL|function|paint
DECL|function|sizeLess
DECL|function|streamAvailableSizes
DECL|function|streamAvailableSizes_data
DECL|function|svg
DECL|function|svgActualSize
DECL|function|swap
DECL|function|task184901_badCache
DECL|function|task223279_inconsistentAddFile
DECL|function|task239461_custom_iconengine_crash
DECL|function|tst_QIcon
DECL|function|~IconEngine
DECL|macro|SRCDIR
DECL|member|destructorCalled
DECL|member|destructorCalled
DECL|member|oldCurrentDir
DECL|member|staticIcon
DECL|member|staticIcon
