DECL|class|tst_QtEndian
DECL|function|fromBigEndian
DECL|function|fromLittleEndian
DECL|function|toBigEndian
DECL|function|toLittleEndian
DECL|macro|ENDIAN_TEST
DECL|macro|ENDIAN_TEST
DECL|macro|ENDIAN_TEST
DECL|macro|ENDIAN_TEST
DECL|macro|EXPAND_ENDIAN_TEST
DECL|member|data
DECL|member|data16
DECL|member|data32
DECL|member|data64
DECL|member|data8
DECL|member|rawData
DECL|member|reserved
DECL|struct|TestData
DECL|union|RawTestData
DECL|variable|inBigEndian
DECL|variable|inLittleEndian
DECL|variable|inNativeEndian
