DECL|class|TypesInterface
DECL|class|tst_QDBusReply
DECL|function|MyStruct
DECL|function|TypesInterface
DECL|function|complexTypes
DECL|function|error
DECL|function|init
DECL|function|initTestCase
DECL|function|operator <<
DECL|function|operator ==
DECL|function|operator >>
DECL|function|retrieveBool
DECL|function|retrieveByteArray
DECL|function|retrieveDouble
DECL|function|retrieveInt
DECL|function|retrieveIntStringMap
DECL|function|retrieveList
DECL|function|retrieveLongLong
DECL|function|retrieveMap
DECL|function|retrieveObjectPath
DECL|function|retrieveObjectPathList
DECL|function|retrieveShort
DECL|function|retrieveSignature
DECL|function|retrieveString
DECL|function|retrieveStringList
DECL|function|retrieveStruct
DECL|function|retrieveUChar
DECL|function|retrieveUInt
DECL|function|retrieveULongLong
DECL|function|retrieveUShort
DECL|function|retrieveVariant
DECL|function|simpleTypes
DECL|function|tst_QDBusReply
DECL|function|unconnected
DECL|function|wrongTypes
DECL|member|adaptor
DECL|member|i
DECL|member|iface
DECL|member|s
DECL|struct|MyStruct
DECL|typedef|IntStringMap
