DECL|class|Widget_task183679
DECL|class|tst_QToolTip
DECL|function|Widget_task183679
DECL|function|cleanup
DECL|function|findWhatsThat
DECL|function|init
DECL|function|setPalette
DECL|function|showDelayedToolTip
DECL|function|showToolTip
DECL|function|task183679
DECL|function|task183679_data
DECL|function|whatsThis
