DECL|class|Window
DECL|class|tst_QWindowContainer
DECL|function|Window
DECL|function|cleanup
DECL|function|exposeEvent
DECL|function|testActivation
DECL|function|testAncestorChange
DECL|function|testBehindTheScenesDeletion
DECL|function|testDockWidget
DECL|function|testExposeObscure
DECL|function|testOwnership
DECL|function|testPositionAndSize
DECL|function|testShow
DECL|function|testUnparenting
DECL|function|tst_QWindowContainer
DECL|member|m_availableGeometry
DECL|member|numberOfExposes
DECL|member|numberOfObscures
