DECL|function|QOfonoConnectionContextInterface
DECL|function|QOfonoDataConnectionManagerInterface
DECL|function|QOfonoManagerInterface
DECL|function|QOfonoModemInterface
DECL|function|QOfonoNetworkRegistrationInterface
DECL|function|accessPointName
DECL|function|active
DECL|function|bearer
DECL|function|contexts
DECL|function|currentModem
DECL|function|getModems
DECL|function|getProperties
DECL|function|getProperties
DECL|function|getProperties
DECL|function|getProperties
DECL|function|getProperty
DECL|function|getProperty
DECL|function|getProperty
DECL|function|getProperty
DECL|function|getTechnology
DECL|function|interfaces
DECL|function|isOnline
DECL|function|isPowered
DECL|function|modemAdded
DECL|function|modemRemoved
DECL|function|name
DECL|function|operator <<
DECL|function|operator >>
DECL|function|propertyChanged
DECL|function|propertyChanged
DECL|function|propertyChanged
DECL|function|roamingAllowed
DECL|function|~QOfonoConnectionContextInterface
DECL|function|~QOfonoDataConnectionManagerInterface
DECL|function|~QOfonoManagerInterface
DECL|function|~QOfonoModemInterface
DECL|function|~QOfonoNetworkRegistrationInterface
