DECL|function|CodeMarker
DECL|function|append
DECL|function|encode
DECL|function|initialize
DECL|function|initializeMarker
DECL|function|insert
DECL|function|insert
DECL|function|insertReimpFunc
DECL|function|linkTag
DECL|function|macName
DECL|function|macRefsForNode
DECL|function|markerForCode
DECL|function|markerForFileName
DECL|function|markerForLanguage
DECL|function|nodeForString
DECL|function|protect
DECL|function|qmlSections
DECL|function|sortName
DECL|function|stringForNode
DECL|function|taggedNode
DECL|function|taggedQmlNode
DECL|function|terminate
DECL|function|terminateMarker
DECL|function|typified
DECL|function|~CodeMarker
DECL|function|~FastSection
DECL|function|~Section
DECL|member|defaultLang
DECL|member|markers
DECL|variable|samp
DECL|variable|sgt
DECL|variable|slt
DECL|variable|squot
