DECL|function|CppCodeMarker
DECL|function|addMarkUp
DECL|function|atomType
DECL|function|functionBeginRegExp
DECL|function|functionEndRegExp
DECL|function|markedUpCode
DECL|function|markedUpEnumValue
DECL|function|markedUpFullName
DECL|function|markedUpIncludes
DECL|function|markedUpName
DECL|function|markedUpQmlItem
DECL|function|markedUpSynopsis
DECL|function|plainFullName
DECL|function|plainName
DECL|function|qmlSections
DECL|function|recognizeCode
DECL|function|recognizeExtension
DECL|function|recognizeLanguage
DECL|function|resolveTarget
DECL|function|sections
DECL|function|~CppCodeMarker
DECL|macro|readChar
DECL|variable|keywordTable
DECL|variable|typeTable
