DECL|function|Generator
DECL|function|appendFullName
DECL|function|appendFullName
DECL|function|appendFullNames
DECL|function|appendSortedNames
DECL|function|appendSortedQmlNames
DECL|function|endText
DECL|function|findAllSince
DECL|function|formattingLeftMap
DECL|function|formattingRightMap
DECL|function|fullName
DECL|function|generateAlsoList
DECL|function|generateAtom
DECL|function|generateAtomList
DECL|function|generateBody
DECL|function|generateClassLikeNode
DECL|function|generateExampleFiles
DECL|function|generateFakeNode
DECL|function|generateFileList
DECL|function|generateInheritedBy
DECL|function|generateInherits
DECL|function|generateMaintainerList
DECL|function|generateQmlInherits
DECL|function|generateQmlText
DECL|function|generateReimplementedFrom
DECL|function|generateSince
DECL|function|generateStatus
DECL|function|generateText
DECL|function|generateThreadSafeness
DECL|function|generatorForFormat
DECL|function|getMetadataElement
DECL|function|getMetadataElements
DECL|function|imageFileName
DECL|function|indent
DECL|function|initialize
DECL|function|initializeGenerator
DECL|function|matchAhead
DECL|function|outputPrefix
DECL|function|plainCode
DECL|function|setImageFileExtensions
DECL|function|singularPlural
DECL|function|skipAtoms
DECL|function|startText
DECL|function|supplementAlsoList
DECL|function|terminate
DECL|function|terminateGenerator
DECL|function|trimmedTrailing
DECL|function|typeString
DECL|function|unknownAtom
DECL|function|~Generator
DECL|member|baseDir_
DECL|member|exampleDirs
DECL|member|exampleImgExts
DECL|member|fmtLeftMaps
DECL|member|fmtRightMaps
DECL|member|generators
DECL|member|imageDirs
DECL|member|imageFiles
DECL|member|imgFileExts
DECL|member|outDir_
DECL|member|outputFormats
DECL|member|outputPrefixes
DECL|member|project
DECL|member|scriptDirs
DECL|member|scriptFiles
DECL|member|sinceTitles
DECL|member|styleDirs
DECL|member|styleFiles
