DECL|macro|GENERATOR_H
DECL|typedef|NewClassMaps
DECL|typedef|NewSinceMaps
DECL|typedef|Node
DECL|typedef|NodeMap
DECL|typedef|NodeMultiMap
DECL|typedef|ParentMaps
DECL|typedef|QString
DECL|typedef|QString
DECL|typedef|QString
DECL|typedef|QString
DECL|variable|ClassNode
DECL|variable|CodeMarker
DECL|variable|Config
DECL|variable|FakeNode
DECL|variable|FunctionNode
DECL|variable|InnerNode
DECL|variable|Location
DECL|variable|NamespaceNode
DECL|variable|Node
DECL|variable|Tree
