DECL|function|creationTimeBefore
DECL|function|main
DECL|function|printHelp
DECL|function|printVersion
DECL|function|processQdocconfFile
DECL|member|key
DECL|member|value
DECL|variable|defaults
DECL|variable|defines
DECL|variable|dependModules
DECL|variable|highlighting
DECL|variable|indexDirs
DECL|variable|obsoleteLinks
DECL|variable|showInternal
