DECL|function|QDocDatabase
DECL|function|addGroup
DECL|function|addModule
DECL|function|addQmlModule
DECL|function|addToGroup
DECL|function|addToModule
DECL|function|addToQmlModule
DECL|function|buildCollections
DECL|function|destroyQdocDB
DECL|function|findAllClasses
DECL|function|findAllFunctions
DECL|function|findAllLegaleseTexts
DECL|function|findAllNamespaces
DECL|function|findAllSince
DECL|function|findDocNodeByTitle
DECL|function|findGroup
DECL|function|findModule
DECL|function|findNodeForTarget
DECL|function|findQmlModule
DECL|function|findQmlType
DECL|function|findTarget
DECL|function|findUnambiguousTarget
DECL|function|generateIndex
DECL|function|generateTagFile
DECL|function|getClassMap
DECL|function|getGroup
DECL|function|getQmlTypeMap
DECL|function|getSinceMap
DECL|function|insertTarget
DECL|function|printModules
DECL|function|printQmlModules
DECL|function|qdocDB
DECL|function|readIndexes
DECL|function|refForAtom
DECL|function|resolveIssues
DECL|function|resolveQmlInheritance
DECL|function|resolveTarget
DECL|function|resolveTargets
DECL|function|~QDocDatabase
DECL|member|qdocDB_
DECL|variable|emptyNodeMap_
DECL|variable|emptyNodeMultiMap_
