DECL|function|QDocDatabase
DECL|function|addModule
DECL|function|addQmlModule
DECL|function|addToModule
DECL|function|addToQmlModule
DECL|function|buildCollections
DECL|function|destroyQdocDB
DECL|function|findAllClasses
DECL|function|findAllFunctions
DECL|function|findAllLegaleseTexts
DECL|function|findAllNamespaces
DECL|function|findAllSince
DECL|function|findModule
DECL|function|findNodeForTarget
DECL|function|findQmlModule
DECL|function|findQmlType
DECL|function|getClassMap
DECL|function|getGroup
DECL|function|getQmlTypeMap
DECL|function|getSinceMap
DECL|function|printModules
DECL|function|printQmlModules
DECL|function|qdocDB
DECL|function|resolveIssues
DECL|function|resolveTarget
DECL|function|~QDocDatabase
DECL|member|qdocDB_
DECL|variable|emptyNodeMap_
DECL|variable|emptyNodeMultiMap_
