DECL|function|QDocDatabase
DECL|function|addGroup
DECL|function|addModule
DECL|function|addQmlModule
DECL|function|addToGroup
DECL|function|addToModule
DECL|function|addToQmlModule
DECL|function|buildCollections
DECL|function|destroyQdocDB
DECL|function|findAllClasses
DECL|function|findAllFunctions
DECL|function|findAllLegaleseTexts
DECL|function|findAllNamespaces
DECL|function|findAllObsoleteThings
DECL|function|findAllSince
DECL|function|findGroup
DECL|function|findModule
DECL|function|findNodeForTarget
DECL|function|findNodeInOpenNamespace
DECL|function|findNodeInOpenNamespace
DECL|function|findQmlModule
DECL|function|findQmlType
DECL|function|findQmlType
DECL|function|firstRoot
DECL|function|firstTree
DECL|function|generateIndex
DECL|function|generateTagFile
DECL|function|getClassMap
DECL|function|getGroup
DECL|function|getQmlTypeMap
DECL|function|getSinceMap
DECL|function|initializeDB
DECL|function|newIndexTree
DECL|function|newPrimaryTree
DECL|function|nextRoot
DECL|function|nextTree
DECL|function|printModules
DECL|function|printQmlModules
DECL|function|processForest
DECL|function|qdocDB
DECL|function|readIndexes
DECL|function|resolveIssues
DECL|function|resolveQmlInheritance
DECL|function|resolveTargetHelper
DECL|function|resolveType
DECL|function|resolveTypeHelper
DECL|function|searchOrder
DECL|function|setSearchOrder
DECL|function|~QDocDatabase
DECL|function|~QDocForest
DECL|member|qdocDB_
DECL|member|typeNodeMap_
DECL|variable|emptyNodeMap_
DECL|variable|emptyNodeMultiMap_
