DECL|function|Tokenizer
DECL|function|Tokenizer
DECL|function|getToken
DECL|function|getTokenAfterPreprocessor
DECL|function|hashKword
DECL|function|init
DECL|function|initialize
DECL|function|insertKwordIntoHash
DECL|function|isTrue
DECL|function|lexeme
DECL|function|popSkipping
DECL|function|previousLexeme
DECL|function|pushSkipping
DECL|function|start
DECL|function|terminate
DECL|function|~Tokenizer
DECL|macro|LANGUAGE_CPP
DECL|variable|KwordHashTableSize
DECL|variable|comment
DECL|variable|definedX
DECL|variable|defines
DECL|variable|falsehoods
DECL|variable|ignoredTokensAndDirectives
DECL|variable|kwordHashTable
DECL|variable|kwords
DECL|variable|sourceCodec
DECL|variable|versionX
