DECL|function|Tree
DECL|function|addPropertyFunction
DECL|function|addToGroup
DECL|function|addToJsModule
DECL|function|addToModule
DECL|function|addToQmlModule
DECL|function|allBaseClasses
DECL|function|checkForCollision
DECL|function|findClassNode
DECL|function|findCollection
DECL|function|findDocumentNodeByTitle
DECL|function|findFunctionNode
DECL|function|findFunctionNode
DECL|function|findFunctionNode
DECL|function|findNamespaceNode
DECL|function|findNode
DECL|function|findNodeByNameAndType
DECL|function|findNodeForInclude
DECL|function|findNodeForTarget
DECL|function|findNodeRecursive
DECL|function|findNodeRecursive
DECL|function|findQmlTypeNode
DECL|function|findRelatesNode
DECL|function|findUnambiguousTarget
DECL|function|findVirtualFunctionInBaseClasses
DECL|function|fixInheritance
DECL|function|getCollection
DECL|function|getCollectionMap
DECL|function|getNewLinkTarget
DECL|function|getRef
DECL|function|getTargetList
DECL|function|insertQmlType
DECL|function|insertTarget
DECL|function|matchPathAndTarget
DECL|function|refForAtom
DECL|function|relatesTypes
DECL|function|resolveCppToQmlLinks
DECL|function|resolveInheritance
DECL|function|resolveInheritanceHelper
DECL|function|resolveProperties
DECL|function|resolveTargets
DECL|function|~Tree
DECL|variable|t
