DECL|function|Tree
DECL|function|addBaseClass
DECL|function|addPropertyFunction
DECL|function|addToGroup
DECL|function|addToPublicGroup
DECL|function|allBaseClasses
DECL|function|checkForCollision
DECL|function|findClassNode
DECL|function|findCollisionNode
DECL|function|findEnumNode
DECL|function|findFunctionNode
DECL|function|findFunctionNode
DECL|function|findFunctionNode
DECL|function|findFunctionNode
DECL|function|findGroupNode
DECL|function|findNamespaceNode
DECL|function|findNode
DECL|function|findNode
DECL|function|findNodeByNameAndType
DECL|function|findNodeRecursive
DECL|function|findQmlModuleNode
DECL|function|findQmlTypeNode
DECL|function|findVirtualFunctionInBaseClasses
DECL|function|fixInheritance
DECL|function|fixPropertyUsingBaseClasses
DECL|function|groups
DECL|function|publicGroups
DECL|function|resolveCppToQmlLinks
DECL|function|resolveGroups
DECL|function|resolveInheritance
DECL|function|resolveInheritance
DECL|function|resolveProperties
DECL|function|~Tree
