DECL|function|Tree
DECL|function|addGroup
DECL|function|addModule
DECL|function|addPropertyFunction
DECL|function|addQmlModule
DECL|function|addToGroup
DECL|function|addToModule
DECL|function|addToQmlModule
DECL|function|allBaseClasses
DECL|function|checkForCollision
DECL|function|findClassNode
DECL|function|findDocNodeByTitle
DECL|function|findFunctionNode
DECL|function|findFunctionNode
DECL|function|findFunctionNode
DECL|function|findGroup
DECL|function|findModule
DECL|function|findNamespaceNode
DECL|function|findNode
DECL|function|findNodeByNameAndType
DECL|function|findNodeForInclude
DECL|function|findNodeForTarget
DECL|function|findNodeRecursive
DECL|function|findNodeRecursive
DECL|function|findQmlModule
DECL|function|findQmlTypeNode
DECL|function|findRelatesNode
DECL|function|findUnambiguousTarget
DECL|function|findVirtualFunctionInBaseClasses
DECL|function|fixInheritance
DECL|function|getCorrespondingCollection
DECL|function|getGroup
DECL|function|getModule
DECL|function|getNewLinkTarget
DECL|function|getQmlModule
DECL|function|getRef
DECL|function|getTargetList
DECL|function|insertQmlType
DECL|function|insertTarget
DECL|function|matchPathAndTarget
DECL|function|refForAtom
DECL|function|relatesTypes
DECL|function|resolveCppToQmlLinks
DECL|function|resolveInheritance
DECL|function|resolveInheritanceHelper
DECL|function|resolveProperties
DECL|function|resolveTargets
DECL|function|~Tree
DECL|variable|t
