DECL|function|CircleItem
DECL|function|ItemBase
DECL|function|QtBox
DECL|function|SquareItem
DECL|function|boundingRect
DECL|function|contextMenuEvent
DECL|function|createNew
DECL|function|createNew
DECL|function|createNew
DECL|function|deleteSelectedItems
DECL|function|duplicateSelectedItems
DECL|function|growSelectedItems
DECL|function|hoverMoveEvent
DECL|function|isInResizeArea
DECL|function|keyPressEvent
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|paint
DECL|function|paint
DECL|function|paint
DECL|function|paint
DECL|function|shrinkSelectedItems
DECL|function|type
DECL|function|wheelEvent
DECL|function|~ItemBase
DECL|function|~QtBox
DECL|variable|MAX_ITEM_SIZE
DECL|variable|MIN_ITEM_SIZE
DECL|variable|ROTATE_SPEED_X
DECL|variable|ROTATE_SPEED_Y
DECL|variable|ROTATE_SPEED_Z
