DECL|class|DummyQAnimationGroup
DECL|class|TestableQAbstractAnimation
DECL|class|tst_QAbstractAnimation
DECL|function|TestableQAbstractAnimation
DECL|function|avoidJumpAtStart
DECL|function|avoidJumpAtStartWithStop
DECL|function|construction
DECL|function|currentLoop
DECL|function|currentLoopTime
DECL|function|currentTime
DECL|function|destruction
DECL|function|direction
DECL|function|duration
DECL|function|duration
DECL|function|group
DECL|function|loopCount
DECL|function|setDuration
DECL|function|state
DECL|function|totalDuration
DECL|function|updateCurrentTime
DECL|function|updateCurrentTime
DECL|function|~TestableQAbstractAnimation
DECL|member|m_duration
