DECL|class|Consumer
DECL|class|Producer
DECL|function|Consumer
DECL|function|Producer
DECL|function|main
DECL|variable|BufferSize
DECL|variable|DataSize
DECL|variable|buffer
DECL|variable|bufferNotEmpty
DECL|variable|bufferNotFull
DECL|variable|mutex
DECL|variable|numUsedBytes
