DECL|class|tst_QDnsLookup
DECL|function|domainName
DECL|function|domainNameList
DECL|function|domainNameListAlternatives
DECL|function|initTestCase
DECL|function|lookup
DECL|function|lookupAbortRetry
DECL|function|lookupReuse
DECL|function|lookup_data
DECL|function|waitForDone
