DECL|class|MainWindow
DECL|function|MainWindow
DECL|function|createColorsPage
DECL|function|createHintsPage
DECL|function|createMetricsPage
DECL|function|createStandardPixmapPage
DECL|function|formatEnumValue
DECL|function|main
DECL|function|pixmapDescription
DECL|function|updateDescription
DECL|member|m_descriptionLabel
DECL|member|m_tabWidget
