DECL|class|C
DECL|class|M
DECL|class|P
DECL|class|tst_QPair
DECL|function|taskQTBUG_48780_pairContainingCArray
DECL|function|testConstexpr
DECL|function|testConversions
DECL|macro|rhs
DECL|macro|rhs
DECL|macro|rhs
DECL|macro|rhs
DECL|member|_
DECL|member|_
DECL|member|_
DECL|typedef|QPairCC
DECL|typedef|QPairCM
DECL|typedef|QPairCP
DECL|typedef|QPairMC
DECL|typedef|QPairMM
DECL|typedef|QPairMP
DECL|typedef|QPairPC
DECL|typedef|QPairPM
DECL|typedef|QPairPP
DECL|variable|isComplex
DECL|variable|isComplex
DECL|variable|isComplex
DECL|variable|isComplex
DECL|variable|isComplex
DECL|variable|isComplex
DECL|variable|isComplex
DECL|variable|isComplex
DECL|variable|isStatic
DECL|variable|isStatic
DECL|variable|isStatic
DECL|variable|isStatic
DECL|variable|isStatic
