DECL|function|MainWindow
DECL|function|MainWindow
DECL|function|about
DECL|function|closeEvent
DECL|function|createActions
DECL|function|createStatusBar
DECL|function|documentWasModified
DECL|function|fileKey
DECL|function|findMainWindow
DECL|function|hasRecentFiles
DECL|function|init
DECL|function|loadFile
DECL|function|maybeSave
DECL|function|newFile
DECL|function|open
DECL|function|openFile
DECL|function|openRecentFile
DECL|function|prependToRecentFiles
DECL|function|readRecentFiles
DECL|function|readSettings
DECL|function|recentFilesKey
DECL|function|save
DECL|function|saveAs
DECL|function|saveFile
DECL|function|setCurrentFile
DECL|function|setRecentFilesVisible
DECL|function|strippedName
DECL|function|tile
DECL|function|updateRecentFileActions
DECL|function|writeRecentFiles
DECL|function|writeSettings
