DECL|class|Slider
DECL|class|tst_QAbstractSlider
DECL|function|Slider
DECL|function|actionTriggered
DECL|function|cleanupTestCase
DECL|function|connectedSliders
DECL|function|initTestCase
DECL|function|keyPressed
DECL|function|keyPressed_data
DECL|function|minimum_maximum
DECL|function|minimum_maximum_data
DECL|function|rangeChanged
DECL|function|rangeChanged
DECL|function|rangeChanged_data
DECL|function|setFrameless
DECL|function|setOrientation
DECL|function|setRepeatAction
DECL|function|setSliderPosition
DECL|function|setSliderPosition_data
DECL|function|setValue
DECL|function|setValue_data
DECL|function|sliderMoved
DECL|function|sliderMoved
DECL|function|sliderMoved_data
DECL|function|sliderPressedReleased
DECL|function|sliderPressedReleased_data
DECL|function|triggerAction
DECL|function|triggerAction_data
DECL|function|valueChanged
DECL|function|waitUntilTimeElapsed
DECL|function|wheelEvent
DECL|function|wheelEvent_data
DECL|macro|WHEEL_DELTA
DECL|member|actionTriggeredTimeStamp
DECL|member|previousAction
DECL|member|rangeChangedTimeStamp
DECL|member|reportedMaximum
DECL|member|reportedMinimum
DECL|member|reportedSliderPosition
DECL|member|reportedValue
DECL|member|slider
DECL|member|sliderMovedTimeStamp
DECL|member|timeStamp
DECL|member|topLevel
DECL|member|valueChangedTimeStamp
