DECL|enumerator|debugWriteIncludes
DECL|enumerator|warnHeaderGeneration
DECL|function|WriteIncludes
DECL|function|acceptCustomWidget
DECL|function|acceptCustomWidgets
DECL|function|acceptInclude
DECL|function|acceptIncludes
DECL|function|acceptLayout
DECL|function|acceptProperty
DECL|function|acceptSpacer
DECL|function|acceptUI
DECL|function|acceptWidget
DECL|function|acceptWidgetScripts
DECL|function|activateScripts
DECL|function|add
DECL|function|insertInclude
DECL|function|insertIncludeForClass
DECL|function|moduleHeader
DECL|function|writeHeaders
DECL|macro|QT_CLASS_LIB
DECL|macro|QT_CLASS_LIB
DECL|member|header
DECL|member|klass
DECL|member|module
DECL|namespace|CPP
DECL|struct|ClassInfoEntry
DECL|variable|qclass_lib_map
