DECL|class|Configuration
DECL|class|LogThread
DECL|class|tst_QLogging
DECL|function|Configuration
DECL|function|LogThread
DECL|function|QLoggingCategory_categoryName
DECL|function|QLoggingCategory_installFilter
DECL|function|QLoggingCategory_isEnabled
DECL|function|QLoggingCategory_setEnabled
DECL|function|addKey
DECL|function|addKey
DECL|function|array
DECL|function|checkEmptyCategoryName
DECL|function|checkFiltering
DECL|function|checkLegacyLogs
DECL|function|checkLegacyMessageLogger
DECL|function|checkLogWithCategoryObject
DECL|function|checkMultithreading
DECL|function|checkNoCategoryLogActive
DECL|function|cleanLogLine
DECL|function|cleanupTestCase
DECL|function|clear
DECL|function|customCategoryFilter
DECL|function|initTestCase
DECL|function|myCustomMessageHandler
DECL|function|qCDebugMacros
DECL|function|qDebugMacros
DECL|function|qMyMessageFormatString
DECL|function|run
DECL|function|writeCategoryLogs
DECL|member|_config
DECL|member|_configitemEntryOrder
DECL|member|_configuration
DECL|member|_logtext
DECL|member|_values
DECL|member|logEntries
DECL|variable|configuration1
DECL|variable|configuration2
DECL|variable|customCategoryFilterArgs
DECL|variable|logMessage
DECL|variable|multithreadtest
DECL|variable|oldMessageHandler
DECL|variable|threadmutex
DECL|variable|threadtest
DECL|variable|usedefaultformat
