DECL|function|QEglFSKmsCursor
DECL|function|changeCursor
DECL|function|initCursorAtlas
DECL|function|pointerEvent
DECL|function|pos
DECL|function|setPos
DECL|function|~QEglFSKmsCursor
DECL|macro|DRM_CAP_CURSOR_HEIGHT
DECL|macro|DRM_CAP_CURSOR_WIDTH
