DECL|class|QEglFSKmsInterruptHandler
DECL|function|QEglFSKmsInterruptHandler
DECL|function|QEglFSKmsScreen
DECL|function|bufferDestroyedHandler
DECL|function|createSurface
DECL|function|cursor
DECL|function|depth
DECL|function|destroySurface
DECL|function|flip
DECL|function|flipFinished
DECL|function|format
DECL|function|framebufferForBufferObject
DECL|function|geometry
DECL|function|handleSuspendRequest
DECL|function|logicalDpi
DECL|function|name
DECL|function|nativeOrientation
DECL|function|orientation
DECL|function|physicalSize
DECL|function|refreshRate
DECL|function|restoreMode
DECL|function|restoreVideoMode
DECL|function|waitForFlip
DECL|function|~QEglFSKmsScreen
DECL|member|m_screen
DECL|member|m_vtHandler
