DECL|enumerator|OutputConfigCurrent
DECL|enumerator|OutputConfigMode
DECL|enumerator|OutputConfigModeline
DECL|enumerator|OutputConfigOff
DECL|enumerator|OutputConfigPreferred
DECL|enum|OutputConfiguration
DECL|function|QEglFSKmsDevice
DECL|function|close
DECL|function|createScreens
DECL|function|crtcForConnector
DECL|function|device
DECL|function|fd
DECL|function|handleDrmEvent
DECL|function|nameForConnector
DECL|function|open
DECL|function|pageFlipHandler
DECL|function|parseModeline
DECL|function|screenForConnector
DECL|macro|ARRAY_LENGTH
DECL|variable|connector_type_names
