DECL|macro|QEGLFSKMSSCREEN_H
DECL|member|connector_id
DECL|member|crtc_id
DECL|member|mode
DECL|member|mode_set
DECL|member|modes
DECL|member|name
DECL|member|physical_size
DECL|member|saved_crtc
DECL|struct|QEglFSKmsOutput
DECL|variable|QEglFSKmsCursor
DECL|variable|QEglFSKmsDevice
DECL|variable|QEglFSKmsInterruptHandler
