DECL|class|MixingWithTimersHelper
DECL|class|UnexpectedDisconnectTester
DECL|class|tst_QSocketNotifier
DECL|function|MixingWithTimersHelper
DECL|function|UnexpectedDisconnectTester
DECL|function|handleActivated
DECL|function|mixingWithTimers
DECL|function|posixSockets
DECL|function|socketFired
DECL|function|timerFired
DECL|function|unexpectedDisconnection
DECL|macro|NATIVESOCKETENGINE
DECL|macro|max
DECL|macro|min
DECL|member|readEnd1
DECL|member|readEnd2
DECL|member|sequence
DECL|member|socketActivated
DECL|member|timerActivated
