DECL|class|tst_Warnings
DECL|function|testMissingWarnings
DECL|function|testMissingWarningsRegularExpression
DECL|function|testMissingWarningsWithData
DECL|function|testMissingWarningsWithData_data
DECL|function|testWarnings
