DECL|class|TestItemDelegate
DECL|class|TestItemModel
DECL|class|tst_QItemDelegate
DECL|enumerator|ColorTestRole
DECL|enumerator|DoubleTestRole
DECL|enumerator|IconTestRole
DECL|enumerator|ImageTestRole
DECL|enumerator|LineEdit
DECL|enumerator|PixmapTestRole
DECL|enumerator|PlainTextEdit
DECL|enumerator|TextEdit
DECL|enum|Roles
DECL|enum|WidgetType
DECL|function|QTBUG4435_keepSelectionOnCheck
DECL|function|TestItemDelegate
DECL|function|TestItemModel
DECL|function|cleanup
DECL|function|cleanupTestCase
DECL|function|columnCount
DECL|function|data
DECL|function|dateTimeEditor
DECL|function|dateTimeEditor_data
DECL|function|decoration
DECL|function|decoration_data
DECL|function|doLayout
DECL|function|doLayout
DECL|function|doLayout_data
DECL|function|doubleEditorNegativeInput
DECL|function|drawDecoration
DECL|function|drawDisplay
DECL|function|editorEvent
DECL|function|editorEvent
DECL|function|editorEvent_data
DECL|function|editorKeyPress
DECL|function|editorKeyPress_data
DECL|function|enterKey
DECL|function|enterKey_data
DECL|function|eventFilter
DECL|function|eventFilter
DECL|function|font
DECL|function|font_data
DECL|function|getSetCheck
DECL|function|init
DECL|function|initTestCase
DECL|function|rect
DECL|function|rect
DECL|function|rect_data
DECL|function|rowCount
DECL|function|sizeHint
DECL|function|sizeHint_data
DECL|function|task257859_finalizeEdit
DECL|function|textRectangle
DECL|function|textRectangle
DECL|function|textRectangle_data
DECL|function|tst_QItemDelegate
DECL|function|~TestItemDelegate
DECL|function|~TestItemModel
DECL|function|~tst_QItemDelegate
DECL|macro|Q_CHECK_PAINTEVENTS
DECL|member|decorationPixmap
DECL|member|decorationRect
DECL|member|displayFont
DECL|member|displayText
DECL|member|size
DECL|variable|WidgetType
