DECL|function|SpreadSheet
DECL|function|actionAdd
DECL|function|actionDivide
DECL|function|actionMath_helper
DECL|function|actionMultiply
DECL|function|actionSubtract
DECL|function|actionSum
DECL|function|clear
DECL|function|createActions
DECL|function|decode_pos
DECL|function|encode_pos
DECL|function|print
DECL|function|returnPressed
DECL|function|runInputDialog
DECL|function|selectColor
DECL|function|selectFont
DECL|function|setupContents
DECL|function|setupContextMenu
DECL|function|setupMenuBar
DECL|function|showAbout
DECL|function|updateColor
DECL|function|updateLineEdit
DECL|function|updateStatus
DECL|variable|htmlText
