DECL|function|SubMarine
DECL|function|currentDirection
DECL|function|currentSpeed
DECL|function|destroy
DECL|function|launchTorpedo
DECL|function|points
DECL|function|setCurrentDirection
DECL|function|setCurrentSpeed
DECL|function|setupDestroyAnimation
DECL|function|type
