DECL|class|tst_QSizePolicy
DECL|function|PrettyPrint
DECL|function|cleanup
DECL|function|data
DECL|function|dataStream
DECL|function|defaultValues
DECL|function|getSetCheck
DECL|function|getSetCheck_data
DECL|function|horizontalStretch
DECL|function|makeRow
DECL|function|qhash
DECL|function|qhash_data
DECL|function|qtest
DECL|function|s
DECL|function|verticalStretch
DECL|function|~PrettyPrint
DECL|macro|CHECK
DECL|macro|CHECK
DECL|macro|CHECK2
DECL|macro|CHECK2
DECL|macro|FETCH_TEST_DATA
DECL|macro|FETCH_TEST_DATA
DECL|macro|ITEMCOUNT
DECL|macro|ITEMCOUNT
DECL|member|m_s
DECL|struct|PrettyPrint
