DECL|class|PaintUnderOverWindow
DECL|class|PainterWindow
DECL|class|PartialPainterWindow
DECL|class|Window
DECL|class|tst_QOpenGLWindow
DECL|enumerator|Error
DECL|enumerator|None
DECL|enumerator|Paint
DECL|enumerator|PaintOver
DECL|enumerator|PaintUnder
DECL|enum|State
DECL|function|PaintUnderOverWindow
DECL|function|PartialPainterWindow
DECL|function|basic
DECL|function|create
DECL|function|painter
DECL|function|partial
DECL|function|partial_data
DECL|function|reset
DECL|function|underOver
DECL|member|img
DECL|member|img
DECL|member|initCount
DECL|member|m_state
DECL|member|paintCount
DECL|member|paintCount
DECL|member|resizeCount
DECL|member|x
