DECL|class|QVGFontEngineCleaner
DECL|class|QVGPaintEnginePrivate
DECL|enumerator|QT_VG_BLEND_CLEAR_KHR
DECL|enumerator|QT_VG_BLEND_COLORBURN_KHR
DECL|enumerator|QT_VG_BLEND_COLORDODGE_KHR
DECL|enumerator|QT_VG_BLEND_DIFFERENCE_KHR
DECL|enumerator|QT_VG_BLEND_DST_ATOP_KHR
DECL|enumerator|QT_VG_BLEND_DST_KHR
DECL|enumerator|QT_VG_BLEND_DST_OUT_KHR
DECL|enumerator|QT_VG_BLEND_EXCLUSION_KHR
DECL|enumerator|QT_VG_BLEND_HARDLIGHT_KHR
DECL|enumerator|QT_VG_BLEND_HARDMIX_KHR
DECL|enumerator|QT_VG_BLEND_INVERT_KHR
DECL|enumerator|QT_VG_BLEND_LINEARBURN_KHR
DECL|enumerator|QT_VG_BLEND_LINEARDODGE_KHR
DECL|enumerator|QT_VG_BLEND_LINEARLIGHT_KHR
DECL|enumerator|QT_VG_BLEND_OVERLAY_KHR
DECL|enumerator|QT_VG_BLEND_PINLIGHT_KHR
DECL|enumerator|QT_VG_BLEND_SOFTLIGHT_KHR
DECL|enumerator|QT_VG_BLEND_SOFTLIGHT_SVG_KHR
DECL|enumerator|QT_VG_BLEND_SRC_ATOP_KHR
DECL|enumerator|QT_VG_BLEND_SRC_OUT_KHR
DECL|enumerator|QT_VG_BLEND_SUBTRACT_KHR
DECL|enumerator|QT_VG_BLEND_VIVIDLIGHT_KHR
DECL|enumerator|QT_VG_BLEND_XOR_KHR
DECL|enum|AdvancedBlending
DECL|function|QVGCompositionHelper
DECL|function|QVGFontEngineCleaner
DECL|function|QVGFontGlyphCache
DECL|function|QVGPaintEngine
DECL|function|QVGPaintEngine
DECL|function|QVGPaintEnginePrivate
DECL|function|QVGPainterState
DECL|function|QVGPainterState
DECL|function|begin
DECL|function|beginNativePainting
DECL|function|blitWindow
DECL|function|brushChanged
DECL|function|brushOriginChanged
DECL|function|cacheGlyphs
DECL|function|canVgWritePixels
DECL|function|clearModes
DECL|function|clearRect
DECL|function|clearScissor
DECL|function|clip
DECL|function|clip
DECL|function|clip
DECL|function|clip
DECL|function|clip
DECL|function|clip
DECL|function|clip
DECL|function|clip
DECL|function|clipEnabledChanged
DECL|function|clipTransformIsSimple
DECL|function|colorizeBitmap
DECL|function|compositionModeChanged
DECL|function|createState
DECL|function|defaultClipRegion
DECL|function|destroy
DECL|function|draw
DECL|function|draw
DECL|function|drawCachedGlyphs
DECL|function|drawCursorPixmap
DECL|function|drawEllipse
DECL|function|drawEllipse
DECL|function|drawImage
DECL|function|drawImage
DECL|function|drawImageTiled
DECL|function|drawLines
DECL|function|drawLines
DECL|function|drawPath
DECL|function|drawPixmap
DECL|function|drawPixmap
DECL|function|drawPixmapFragments
DECL|function|drawPoints
DECL|function|drawPoints
DECL|function|drawPolygon
DECL|function|drawPolygon
DECL|function|drawRects
DECL|function|drawRects
DECL|function|drawRoundedRect
DECL|function|drawStaticTextItem
DECL|function|drawTextItem
DECL|function|drawTiledPixmap
DECL|function|drawVGImage
DECL|function|drawVGImage
DECL|function|end
DECL|function|endCompositing
DECL|function|endNativePainting
DECL|function|ensureBrush
DECL|function|ensureMask
DECL|function|ensurePathTransform
DECL|function|ensurePen
DECL|function|fill
DECL|function|fill
DECL|function|fillBackground
DECL|function|fillBackgroundRect
DECL|function|fillRect
DECL|function|fillRect
DECL|function|fillRegion
DECL|function|fontEngineDestroyed
DECL|function|init
DECL|function|initObjects
DECL|function|isDefaultClipRect
DECL|function|isDefaultClipRegion
DECL|function|modifyMask
DECL|function|modifyMask
DECL|function|opacityChanged
DECL|function|painterPathToVGPath
DECL|function|penChanged
DECL|function|pixmapFilter
DECL|function|qt_vg_drawVGImage
DECL|function|qt_vg_drawVGImageStencil
DECL|function|qt_vg_image_to_vg_format
DECL|function|qt_vg_pathToRect
DECL|function|renderHintsChanged
DECL|function|restoreState
DECL|function|roundedRectPath
DECL|function|setBlendMode
DECL|function|setBrush
DECL|function|setBrushTransform
DECL|function|setFillRule
DECL|function|setImageMode
DECL|function|setImageOptions
DECL|function|setImageQuality
DECL|function|setPenParams
DECL|function|setRenderingQuality
DECL|function|setScaleFromText
DECL|function|setScissor
DECL|function|setState
DECL|function|setTransform
DECL|function|setupColorRamp
DECL|function|startCompositing
DECL|function|stroke
DECL|function|stroke
DECL|function|systemStateChanged
DECL|function|toVGImage
DECL|function|toVGImageSubRect
DECL|function|toVGImageWithOpacity
DECL|function|toVGImageWithOpacitySubRect
DECL|function|transformChanged
DECL|function|updateScissor
DECL|function|updateTransform
DECL|function|vectorPathToVGPath
DECL|function|~QVGCompositionHelper
DECL|function|~QVGFontEngineCleaner
DECL|function|~QVGFontGlyphCache
DECL|function|~QVGPaintEngine
DECL|function|~QVGPaintEnginePrivate
DECL|function|~QVGPainterState
DECL|macro|QVG_NO_RENDER_TO_MASK
DECL|macro|QVG_NO_RENDER_TO_MASK
DECL|member|blendMode
DECL|member|blurFilter
DECL|member|brushOrigin
DECL|member|brushPaint
DECL|member|brushTransform
DECL|member|brushType
DECL|member|clearColor
DECL|member|clearOpacity
DECL|member|colorizeFilter
DECL|member|convolutionFilter
DECL|member|currentBrush
DECL|member|currentPen
DECL|member|d_ptr
DECL|member|dirty
DECL|member|dropShadowFilter
DECL|member|fillPaint
DECL|member|fillRule
DECL|member|fontCache
DECL|member|fontEngineCleaner
DECL|member|forceBrushChange
DECL|member|forcePenChange
DECL|member|hasAdvancedBlending
DECL|member|imageMode
DECL|member|imageQuality
DECL|member|imageTransform
DECL|member|linePath
DECL|member|maskIsSet
DECL|member|maskRect
DECL|member|maskValid
DECL|member|matrixMode
DECL|member|maxScissorRects
DECL|member|opacity
DECL|member|opacityPaint
DECL|member|paintOpacity
DECL|member|pathTransform
DECL|member|pathTransformSet
DECL|member|penPaint
DECL|member|penScale
DECL|member|penTransform
DECL|member|penType
DECL|member|q
DECL|member|rawVG
DECL|member|rectPath
DECL|member|renderingQuality
DECL|member|roundRectPath
DECL|member|scissorActive
DECL|member|scissorDirty
DECL|member|scissorMask
DECL|member|scissorRegion
DECL|member|simpleTransform
DECL|member|transform
DECL|typedef|QVGFontCache
DECL|variable|aliasedCoordinateDelta
