DECL|function|QVGPixmapData
DECL|function|buffer
DECL|function|copy
DECL|function|createCompatiblePixmapData
DECL|function|createPixmapForImage
DECL|function|destroyImageAndContext
DECL|function|destroyImages
DECL|function|detachImageFromPool
DECL|function|ensureReadback
DECL|function|fill
DECL|function|forceToImage
DECL|function|fromData
DECL|function|fromFile
DECL|function|fromImage
DECL|function|fromImageReader
DECL|function|hasAlphaChannel
DECL|function|hibernate
DECL|function|idealFormat
DECL|function|isValid
DECL|function|metric
DECL|function|paintEngine
DECL|function|qPixmapToVGImage
DECL|function|reclaimImages
DECL|function|resize
DECL|function|setAlphaChannel
DECL|function|sourceFormat
DECL|function|toImage
DECL|function|toVGImage
DECL|function|toVGImage
DECL|function|updateSerial
DECL|function|~QVGPixmapData
DECL|variable|qt_vg_pixmap_serial
