DECL|class|QVGImagePoolPrivate
DECL|function|QVGImagePool
DECL|function|QVGImagePoolPrivate
DECL|function|createImageForPixmap
DECL|function|createPermanentImage
DECL|function|createTemporaryImage
DECL|function|detachImage
DECL|function|hibernate
DECL|function|instance
DECL|function|moveToHeadOfLRU
DECL|function|pixmapLRU
DECL|function|reclaimSpace
DECL|function|releaseImage
DECL|function|removeFromLRU
DECL|function|setImagePool
DECL|function|useImage
DECL|function|~QVGImagePool
DECL|member|lruFirst
DECL|member|lruLast
DECL|variable|qt_vg_image_pool
