DECL|function|PathDeformControls
DECL|function|PathDeformRenderer
DECL|function|PathDeformWidget
DECL|function|circle_bounds
DECL|function|generateLensPixmap
DECL|function|hideControls
DECL|function|layoutForDesktop
DECL|function|layoutForSmallScreen
DECL|function|lensDeform
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|paint
DECL|function|setAnimated
DECL|function|setIntensity
DECL|function|setRadius
DECL|function|setStyle
DECL|function|setText
DECL|function|showControls
DECL|function|timerEvent
DECL|variable|LENS_EXTENT
