DECL|function|QGtkPainter
DECL|function|getIcon
DECL|function|getStyle
DECL|function|gtkState
DECL|function|paintArrow
DECL|function|paintBox
DECL|function|paintBoxGap
DECL|function|paintCheckbox
DECL|function|paintExpander
DECL|function|paintExtention
DECL|function|paintFlatBox
DECL|function|paintFocus
DECL|function|paintHandle
DECL|function|paintHline
DECL|function|paintOption
DECL|function|paintResizeGrip
DECL|function|paintShadow
DECL|function|paintSlider
DECL|function|paintVline
DECL|function|renderTheme
DECL|function|uniqueName
DECL|macro|DRAW_TO_CACHE
DECL|macro|GTK_ALPHA
DECL|macro|GTK_BLUE
DECL|macro|GTK_GREEN
DECL|macro|GTK_OBJECT_FLAGS
DECL|macro|GTK_OBJECT_FLAGS
DECL|macro|GTK_RED
DECL|macro|QT_ALPHA
DECL|macro|QT_BLUE
DECL|macro|QT_GREEN
DECL|macro|QT_RED
