DECL|function|QMotifStyle
DECL|function|QMotifStyle
DECL|function|QMotifStylePrivate
DECL|function|drawComplexControl
DECL|function|drawControl
DECL|function|drawPrimitive
DECL|function|event
DECL|function|eventFilter
DECL|function|get_combo_extra_width
DECL|function|get_combo_parameters
DECL|function|pixelMetric
DECL|function|polish
DECL|function|polish
DECL|function|polish
DECL|function|rot
DECL|function|setUseHighlightColors
DECL|function|sizeFromContents
DECL|function|standardIconImplementation
DECL|function|standardPalette
DECL|function|standardPixmap
DECL|function|styleHint
DECL|function|subControlRect
DECL|function|subElementRect
DECL|function|timerEvent
DECL|function|unpolish
DECL|function|unpolish
DECL|function|useHighlightColors
DECL|function|~QMotifStyle
DECL|macro|CBOT
DECL|macro|CBOT
DECL|macro|CLEFT
DECL|macro|CLEFT
DECL|macro|CMID
DECL|macro|CMID
DECL|macro|CTOP
DECL|macro|CTOP
DECL|macro|INTARRLEN
DECL|variable|critical_xpm
DECL|variable|dock_window_close_xpm
DECL|variable|information_xpm
DECL|variable|motifArrowHMargin
DECL|variable|motifCheckMarkHMargin
DECL|variable|motifCheckMarkSpace
DECL|variable|motifItemFrame
DECL|variable|motifItemHMargin
DECL|variable|motifItemVMargin
DECL|variable|motifSepHeight
DECL|variable|motifTabSpacing
DECL|variable|qt_close_xpm
DECL|variable|qt_maximize_xpm
DECL|variable|qt_menu_xpm
DECL|variable|qt_minimize_xpm
DECL|variable|qt_normalizeup_xpm
DECL|variable|qt_shade_xpm
DECL|variable|qt_unshade_xpm
DECL|variable|question_xpm
DECL|variable|warning_xpm
