DECL|function|QStyle
DECL|function|QStyle
DECL|function|alignedRect
DECL|function|combinedLayoutSpacing
DECL|function|drawItemPixmap
DECL|function|drawItemText
DECL|function|itemPixmapRect
DECL|function|itemTextRect
DECL|function|layoutSpacing
DECL|function|layoutSpacingImplementation
DECL|function|operator <<
DECL|function|polish
DECL|function|polish
DECL|function|polish
DECL|function|proxy
DECL|function|setProxy
DECL|function|sliderPositionFromValue
DECL|function|sliderValueFromPosition
DECL|function|standardIcon
DECL|function|standardIconImplementation
DECL|function|standardPalette
DECL|function|unpackControlTypes
DECL|function|unpolish
DECL|function|unpolish
DECL|function|visualAlignment
DECL|function|visualPos
DECL|function|visualRect
DECL|function|~QStyle
DECL|variable|MaxBits
