DECL|class|QClipboardData
DECL|function|QClipboardData
DECL|function|cleanupClipboardData
DECL|function|clear
DECL|function|clear
DECL|function|clipboardData
DECL|function|connectNotify
DECL|function|connected
DECL|function|event
DECL|function|mimeData
DECL|function|ownerDestroyed
DECL|function|ownsMode
DECL|function|readFromStreamLX
DECL|function|readSymbianStoreLX
DECL|function|setMimeData
DECL|function|setSource
DECL|function|source
DECL|function|supportsMode
DECL|function|writeToStreamLX
DECL|function|writeToSymbianStoreLX
DECL|function|~QClipboardData
DECL|member|connection
DECL|member|src
DECL|variable|KPlainTextBegin
DECL|variable|KQtCbDataStream
DECL|variable|internalCbData
