DECL|function|QCursor
DECL|function|QCursorData
DECL|function|create32BitCursor
DECL|function|handle
DECL|function|pos
DECL|function|setBitmap
DECL|function|setPos
DECL|function|update
DECL|function|~QCursorData
