DECL|class|tst_Spdy
DECL|function|download
DECL|function|download_data
DECL|function|errors
DECL|function|errors_data
DECL|function|headerFields
DECL|function|md5sum
DECL|function|multipleRequests
DECL|function|multipleRequestsFinishedSlot
DECL|function|multipleRequests_data
DECL|function|proxyAuthenticationRequired
DECL|function|settingsAndNegotiation
DECL|function|settingsAndNegotiation_data
DECL|function|tst_Spdy
DECL|function|upload
DECL|function|upload_data
DECL|function|~tst_Spdy
DECL|member|m_manager
DECL|member|m_multipleRepliesFinishedCount
DECL|member|m_multipleRequestsCount
