DECL|class|tst_QBitArray
DECL|function|QStringToQBitArray
DECL|function|countBits
DECL|function|countBits2
DECL|function|countBits_data
DECL|function|datastream
DECL|function|datastream_data
DECL|function|fill
DECL|function|invertOnNull
DECL|function|isEmpty
DECL|function|operator_andeq
DECL|function|operator_andeq_data
DECL|function|operator_neg
DECL|function|operator_neg_data
DECL|function|operator_noteq
DECL|function|operator_noteq_data
DECL|function|operator_oreq
DECL|function|operator_oreq_data
DECL|function|operator_xoreq
DECL|function|operator_xoreq_data
DECL|function|resize
DECL|function|size
DECL|function|size_data
DECL|function|swap
DECL|function|toggleBit
DECL|function|toggleBit_data
