DECL|class|tst_QTemporaryDir
DECL|function|QTBUG_4796
DECL|function|QTBUG_4796_data
DECL|function|autoRemove
DECL|function|autoRemoveAfterFailedRename
DECL|function|cleanup
DECL|function|cleanupTestCase
DECL|function|construction
DECL|function|fileName
DECL|function|fileTemplate
DECL|function|fileTemplate_data
DECL|function|getSetCheck
DECL|function|init
DECL|function|initTestCase
DECL|function|nonWritableCurrentDir
DECL|function|openOnRootDrives
DECL|function|rename
DECL|function|stressTest
DECL|function|tst_QTemporaryDir
DECL|function|~tst_QTemporaryDir
