DECL|enumerator|OtherSize
DECL|function|MainWindow
DECL|function|about
DECL|function|addImages
DECL|function|addOtherImages
DECL|function|addSampleImages
DECL|function|changeIcon
DECL|function|changeSize
DECL|function|changeStyle
DECL|function|checkCurrentStyle
DECL|function|createActions
DECL|function|createContextMenu
DECL|function|createHighDpiIconSizeGroupBox
DECL|function|createIconSizeGroupBox
DECL|function|createImagesGroupBox
DECL|function|loadImages
DECL|function|removeAllImages
DECL|function|screenChanged
DECL|function|show
DECL|function|triggerChangeSize
DECL|function|useHighDpiPixmapsChanged
