DECL|macro|MAINWINDOW_H
DECL|variable|IconPreviewArea
DECL|variable|IconSizeSpinBox
DECL|variable|QAction
DECL|variable|QActionGroup
DECL|variable|QButtonGroup
DECL|variable|QLabel
DECL|variable|QMenu
DECL|variable|QRadioButton
DECL|variable|QTableWidget
