DECL|class|tst_QVariant
DECL|function|Foo
DECL|function|MyClass
DECL|function|MyData
DECL|function|MyData
DECL|function|MyMovable
DECL|function|MyMovable
DECL|function|MyType
DECL|function|MyType
DECL|function|basicUserType
DECL|function|canConvert
DECL|function|canConvertMetaTypeToInt
DECL|function|canConvertQStringList
DECL|function|canConvertQStringList_data
DECL|function|canConvert_data
DECL|function|checkDataStream
DECL|function|colorInteger
DECL|function|compareCustomTypes
DECL|function|comparePointers
DECL|function|constData
DECL|function|constructor
DECL|function|convertBoolToByteArray
DECL|function|convertBoolToByteArray_data
DECL|function|convertByteArrayToBool
DECL|function|convertByteArrayToBool_data
DECL|function|convertMetaType
DECL|function|convertToQUint8
DECL|function|copy_constructor
DECL|function|copyingUserTypes
DECL|function|dataStar
DECL|function|data_
DECL|function|forwardDeclare
DECL|function|globalColor
DECL|function|invalidDateTime
DECL|function|invalidQColor
DECL|function|isNull
DECL|function|loadBrokenUserType
DECL|function|loadUnknownUserType
DECL|function|matrix
DECL|function|matrix4x4
DECL|function|moreCustomTypes
DECL|function|numericalConvert
DECL|function|operator <<
DECL|function|operator =
DECL|function|operator ==
DECL|function|operator ==
DECL|function|operator ==
DECL|function|operator >>
DECL|function|operator_eq_eq
DECL|function|operator_eq_eq_data
DECL|function|operator_eq_eq_rhs
DECL|function|playWithVariant
DECL|function|podUserType
DECL|function|quaternion
DECL|function|qvariant_cast_QObject
DECL|function|qvariant_cast_QObject_data
DECL|function|saveLoadCustomTypes
DECL|function|streamInvalidVariant
DECL|function|swap
DECL|function|task172061_invalidDate
DECL|function|task256984_setValue
DECL|function|timeToDateTime
DECL|function|toBool
DECL|function|toBool_data
DECL|function|toBrush
DECL|function|toBrush_data
DECL|function|toByteArray
DECL|function|toByteArray_data
DECL|function|toChar
DECL|function|toChar_data
DECL|function|toColor
DECL|function|toColor_data
DECL|function|toDate
DECL|function|toDateTime
DECL|function|toDateTime_data
DECL|function|toDate_data
DECL|function|toDouble
DECL|function|toDouble_data
DECL|function|toFont
DECL|function|toFont_data
DECL|function|toImage
DECL|function|toImage_data
DECL|function|toInt
DECL|function|toIntFromDouble
DECL|function|toIntFromQString
DECL|function|toInt_data
DECL|function|toKeySequence
DECL|function|toKeySequence_data
DECL|function|toLine
DECL|function|toLineF
DECL|function|toLineF_data
DECL|function|toLine_data
DECL|function|toLocale
DECL|function|toLongLong
DECL|function|toLongLong_data
DECL|function|toPixmap
DECL|function|toPixmap_data
DECL|function|toPoint
DECL|function|toPointF
DECL|function|toPointF_data
DECL|function|toPoint_data
DECL|function|toRect
DECL|function|toRectF
DECL|function|toRectF_data
DECL|function|toRect_data
DECL|function|toRegExp
DECL|function|toSize
DECL|function|toSizeF
DECL|function|toSizeF_data
DECL|function|toSize_data
DECL|function|toString
DECL|function|toString_data
DECL|function|toTime
DECL|function|toTime_data
DECL|function|toUInt
DECL|function|toUInt_data
DECL|function|toULongLong
DECL|function|toULongLong_data
DECL|function|transform
DECL|function|tst_QVariant
DECL|function|typeName
DECL|function|typeName_data
DECL|function|typeToName
DECL|function|url
DECL|function|userType
DECL|function|variantHash
DECL|function|variantInVariant
DECL|function|variantMap
DECL|function|variantToDateTimeWithoutWarnings
DECL|function|variant_to
DECL|function|vector2D
DECL|function|vector3D
DECL|function|vector4D
DECL|function|voidStar
DECL|function|writeToReadFromDataStream
DECL|function|writeToReadFromDataStream_data
DECL|function|writeToReadFromOldDataStream
DECL|function|~MyData
DECL|function|~MyMovable
DECL|function|~MyType
DECL|macro|N
DECL|macro|N
DECL|macro|N
DECL|macro|PLAY_WITH_VARIANT
DECL|macro|Y
DECL|macro|Y
DECL|macro|Y
DECL|member|a
DECL|member|b
DECL|member|count
DECL|member|count
DECL|member|i
DECL|member|i
DECL|member|myValue
DECL|member|number
DECL|member|ptr
DECL|member|text
DECL|member|v
DECL|member|x
DECL|member|x
DECL|member|y
DECL|struct|Blah
DECL|struct|Data
DECL|struct|Foo
DECL|struct|MyClass
DECL|struct|MyData
DECL|struct|MyMovable
DECL|struct|MyPrimitive
DECL|struct|MyType
DECL|struct|MyTypePOD
DECL|struct|WontCompare
DECL|variable|WontCompare
DECL|variable|instanceCount
DECL|variable|intMax1
DECL|variable|qint8
DECL|variable|uintMax1
