DECL|class|MessageHandler
DECL|class|tst_QVariant
DECL|enumerator|Value
DECL|function|Foo
DECL|function|MessageHandler
DECL|function|MyClass
DECL|function|MyData
DECL|function|MyData
DECL|function|MyMovable
DECL|function|MyMovable
DECL|function|MyNotMovable
DECL|function|MyNotMovable
DECL|function|MyType
DECL|function|MyType
DECL|function|basicUserType
DECL|function|canConvert
DECL|function|canConvertMetaTypeToInt
DECL|function|canConvertQStringList
DECL|function|canConvertQStringList_data
DECL|function|canConvert_data
DECL|function|checkDataStream
DECL|function|colorInteger
DECL|function|compareCustomTypes
DECL|function|comparePointers
DECL|function|constData
DECL|function|constructor
DECL|function|convertBoolToByteArray
DECL|function|convertBoolToByteArray_data
DECL|function|convertByteArrayToBool
DECL|function|convertByteArrayToBool_data
DECL|function|convertMetaType
DECL|function|convertToQUint8
DECL|function|copy_constructor
DECL|function|copyingUserTypes
DECL|function|dataStar
DECL|function|dataStream_data
DECL|function|data_
DECL|function|debugStream
DECL|function|debugStream_data
DECL|function|forwardDeclare
DECL|function|globalColor
DECL|function|handler
DECL|function|invalidDate
DECL|function|invalidDateTime
DECL|function|invalidQColor
DECL|function|isNull
DECL|function|loadBrokenUserType
DECL|function|loadQVariantFromDataStream
DECL|function|loadQt4Stream
DECL|function|loadQt4Stream_data
DECL|function|loadQt5Stream
DECL|function|loadQt5Stream_data
DECL|function|loadUnknownUserType
DECL|function|matrix
DECL|function|matrix4x4
DECL|function|moreCustomTypes
DECL|function|movabilityTest
DECL|function|numericalConvert
DECL|function|operator <<
DECL|function|operator <<
DECL|function|operator =
DECL|function|operator =
DECL|function|operator ==
DECL|function|operator ==
DECL|function|operator ==
DECL|function|operator ==
DECL|function|operator ==
DECL|function|operator >>
DECL|function|operator >>
DECL|function|operator_eq_eq
DECL|function|operator_eq_eq_data
DECL|function|operator_eq_eq_rhs
DECL|function|playWithVariant
DECL|function|podUserType
DECL|function|quaternion
DECL|function|qvariant_cast_QObject
DECL|function|qvariant_cast_QObject_data
DECL|function|saveLoadCustomTypes
DECL|function|saveQVariantFromDataStream
DECL|function|saveQt4Stream
DECL|function|saveQt4Stream_data
DECL|function|saveQt5Stream
DECL|function|saveQt5Stream_data
DECL|function|setValue
DECL|function|streamInvalidVariant
DECL|function|swap
DECL|function|testPassed
DECL|function|timeToDateTime
DECL|function|toBool
DECL|function|toBool_data
DECL|function|toBrush
DECL|function|toBrush_data
DECL|function|toByteArray
DECL|function|toByteArray_data
DECL|function|toChar
DECL|function|toChar_data
DECL|function|toColor
DECL|function|toColor_data
DECL|function|toDate
DECL|function|toDateTime
DECL|function|toDateTime_data
DECL|function|toDate_data
DECL|function|toDouble
DECL|function|toDouble_data
DECL|function|toFont
DECL|function|toFont_data
DECL|function|toImage
DECL|function|toImage_data
DECL|function|toInt
DECL|function|toIntFromDouble
DECL|function|toIntFromQString
DECL|function|toInt_data
DECL|function|toKeySequence
DECL|function|toKeySequence_data
DECL|function|toLine
DECL|function|toLineF
DECL|function|toLineF_data
DECL|function|toLine_data
DECL|function|toLocale
DECL|function|toLongLong
DECL|function|toLongLong_data
DECL|function|toPixmap
DECL|function|toPixmap_data
DECL|function|toPoint
DECL|function|toPointF
DECL|function|toPointF_data
DECL|function|toPoint_data
DECL|function|toRect
DECL|function|toRectF
DECL|function|toRectF_data
DECL|function|toRect_data
DECL|function|toRegExp
DECL|function|toSize
DECL|function|toSizeF
DECL|function|toSizeF_data
DECL|function|toSize_data
DECL|function|toString
DECL|function|toString_data
DECL|function|toTime
DECL|function|toTime_data
DECL|function|toUInt
DECL|function|toUInt_data
DECL|function|toULongLong
DECL|function|toULongLong_data
DECL|function|transform
DECL|function|typeName
DECL|function|typeName_data
DECL|function|typeToName
DECL|function|url
DECL|function|userType
DECL|function|variantHash
DECL|function|variantInVariant
DECL|function|variantMap
DECL|function|variantToDateTimeWithoutWarnings
DECL|function|variant_to
DECL|function|vector2D
DECL|function|vector3D
DECL|function|vector4D
DECL|function|voidStar
DECL|function|writeToReadFromDataStream
DECL|function|writeToReadFromDataStream_data
DECL|function|writeToReadFromOldDataStream
DECL|function|~MessageHandler
DECL|function|~MyData
DECL|function|~MyMovable
DECL|function|~MyNotMovable
DECL|function|~MyType
DECL|macro|CONVERT_META_TYPE
DECL|macro|CONVERT_META_TYPE
DECL|macro|N
DECL|macro|N
DECL|macro|N
DECL|macro|PLAY_WITH_VARIANT
DECL|macro|Y
DECL|macro|Y
DECL|macro|Y
DECL|member|a
DECL|member|b
DECL|member|count
DECL|member|count
DECL|member|count
DECL|member|count
DECL|member|currentId
DECL|member|currentId
DECL|member|e
DECL|member|i
DECL|member|i
DECL|member|i
DECL|member|movable
DECL|member|myValue
DECL|member|number
DECL|member|ok
DECL|member|ok
DECL|member|oldMsgHandler
DECL|member|ptr
DECL|member|q
DECL|member|r
DECL|member|t
DECL|member|text
DECL|member|that
DECL|member|v
DECL|member|w
DECL|member|x
DECL|member|x
DECL|member|y
DECL|member|y
DECL|member|z
DECL|namespace|QtPrivate
DECL|struct|Blah
DECL|struct|CustomStreamableClass
DECL|struct|Data
DECL|struct|Foo
DECL|struct|IsPointerToTypeDerivedFromQObject
DECL|struct|MyClass
DECL|struct|MyData
DECL|struct|MyMovable
DECL|struct|MyNotMovable
DECL|struct|MyPrimitive
DECL|struct|MyShared
DECL|struct|MyType
DECL|struct|MyTypePOD
DECL|struct|WontCompare
DECL|variable|CustomStreamableClass
DECL|variable|WontCompare
DECL|variable|instanceCount
DECL|variable|intMax1
DECL|variable|qint8
DECL|variable|uintMax1
