DECL|function|FileInfoCacheKey
DECL|function|FixStringCacheKey
DECL|function|hashCode
DECL|function|hashCode
DECL|function|isRelativePath
DECL|function|operator
DECL|function|operator
DECL|function|qHash
DECL|function|qHash
DECL|function|qmakeDeleteCacheClear
DECL|function|qmakeFreeCacheClear
DECL|macro|CACHEKEYS_H
DECL|member|file
DECL|member|flags
DECL|member|hash
DECL|member|hash
DECL|member|pwd
DECL|member|pwd
DECL|member|string
DECL|struct|FileInfoCacheKey
DECL|struct|FixStringCacheKey
DECL|typedef|qmakeCacheClearFunc
