DECL|enumerator|FixEnvVars
DECL|enumerator|FixNone
DECL|enumerator|FixPathCanonicalize
DECL|enumerator|FixPathToLocalSeparators
DECL|enumerator|FixPathToNormalSeparators
DECL|enumerator|FixPathToTargetSeparators
DECL|enumerator|QMAKE_CMDLINE_BAIL
DECL|enumerator|QMAKE_CMDLINE_ERROR
DECL|enumerator|QMAKE_CMDLINE_SHOW_USAGE
DECL|enumerator|QMAKE_CMDLINE_SUCCESS
DECL|enumerator|QMAKE_GENERATE_MAKEFILE
DECL|enumerator|QMAKE_GENERATE_NOTHING
DECL|enumerator|QMAKE_GENERATE_PRL
DECL|enumerator|QMAKE_GENERATE_PROJECT
DECL|enumerator|QMAKE_QUERY_PROPERTY
DECL|enumerator|QMAKE_SET_PROPERTY
DECL|enumerator|QMAKE_UNSET_PROPERTY
DECL|enumerator|WarnAll
DECL|enumerator|WarnDeprecated
DECL|enumerator|WarnLogic
DECL|enumerator|WarnNone
DECL|enumerator|WarnParser
DECL|enum|CmdLineFlags
DECL|enum|QMAKE_MODE
DECL|enum|QMakeWarn
DECL|enum|StringFixFlags
DECL|function|fixEnvVariables
DECL|function|fixPathToLocalOS
DECL|function|fixPathToTargetOS
DECL|function|hasFileExtension
DECL|function|normalizePath
DECL|function|splitPathList
DECL|macro|OPTION_H
DECL|macro|QMAKE_VERSION_STR
DECL|macro|debug_msg
DECL|member|c_ext
DECL|member|cachefile_depth
DECL|member|cpp_ext
DECL|member|cpp_moc_ext
DECL|member|debug_level
DECL|member|dir_sep
DECL|member|do_dep_heuristics
DECL|member|do_deps
DECL|member|do_mocs
DECL|member|do_preprocess
DECL|member|do_pwd
DECL|member|do_stub_makefile
DECL|member|evalHandler
DECL|member|field_sep
DECL|member|globals
DECL|member|h_ext
DECL|member|h_moc_mod
DECL|member|lex_ext
DECL|member|lex_mod
DECL|member|libtool_ext
DECL|member|obj_ext
DECL|member|output
DECL|member|output_dir
DECL|member|parser
DECL|member|pkgcfg_ext
DECL|member|prf_ext
DECL|member|private
DECL|member|prl_ext
DECL|member|proFileCache
DECL|member|pro_ext
DECL|member|project_dirs
DECL|member|project_files
DECL|member|properties
DECL|member|qmake_args
DECL|member|qmake_mode
DECL|member|recursive
DECL|member|res_ext
DECL|member|state
DECL|member|ui_ext
DECL|member|warn_level
DECL|member|yacc_ext
DECL|member|yacc_mod
DECL|struct|Option
DECL|struct|mkfile
DECL|struct|projfile
DECL|struct|prop
DECL|variable|QMakeProject
