DECL|class|QMakeCacheClearItem
DECL|function|QMakeCacheClearItem
DECL|function|aboutToEval
DECL|function|debug_msg_internal
DECL|function|default_mode
DECL|function|detectProjectFile
DECL|function|doneWithEval
DECL|function|fileMessage
DECL|function|fixString
DECL|function|init
DECL|function|message
DECL|function|parseCommandLine
DECL|function|postProcessProject
DECL|function|prepareProject
DECL|function|qmakeAddCacheClear
DECL|function|qmakeClearCaches
DECL|function|qt_libraryInfoFile
DECL|function|usage
DECL|function|warn_msg
DECL|function|~QMakeCacheClearItem
DECL|member|c_ext
DECL|member|cachefile_depth
DECL|member|cpp_ext
DECL|member|cpp_moc_ext
DECL|member|data
DECL|member|debug_level
DECL|member|dir_sep
DECL|member|do_dep_heuristics
DECL|member|do_deps
DECL|member|do_mocs
DECL|member|do_preprocess
DECL|member|do_pwd
DECL|member|do_stub_makefile
DECL|member|evalHandler
DECL|member|field_sep
DECL|member|func
DECL|member|globals
DECL|member|h_ext
DECL|member|h_moc_mod
DECL|member|lex_ext
DECL|member|lex_mod
DECL|member|libtool_ext
DECL|member|obj_ext
DECL|member|output
DECL|member|output_dir
DECL|member|parser
DECL|member|pkgcfg_ext
DECL|member|prf_ext
DECL|member|prl_ext
DECL|member|proFileCache
DECL|member|pro_ext
DECL|member|project_dirs
DECL|member|project_files
DECL|member|properties
DECL|member|qmake_args
DECL|member|qmake_mode
DECL|member|recursive
DECL|member|res_ext
DECL|member|ui_ext
DECL|member|warn_level
DECL|member|yacc_ext
DECL|member|yacc_mod
DECL|variable|cache_items
