DECL|class|QMakeCacheClearItem
DECL|function|QMakeCacheClearItem
DECL|function|applyHostMode
DECL|function|debug_msg_internal
DECL|function|default_mode
DECL|function|detectProjectFile
DECL|function|detectShellPath
DECL|function|fixString
DECL|function|init
DECL|function|parseCommandLine
DECL|function|postProcessProject
DECL|function|prepareProject
DECL|function|qmakeAddCacheClear
DECL|function|qmakeClearCaches
DECL|function|qmake_libraryInfoFile
DECL|function|qmake_version
DECL|function|usage
DECL|function|warn_msg
DECL|function|~QMakeCacheClearItem
DECL|member|after_user_configs
DECL|member|after_user_vars
DECL|member|application_argv0
DECL|member|before_user_vars
DECL|member|c_ext
DECL|member|cachefile
DECL|member|cachefile_depth
DECL|member|cpp_ext
DECL|member|cpp_moc_ext
DECL|member|cpp_moc_mod
DECL|member|data
DECL|member|debug_level
DECL|member|dir_sep
DECL|member|dirlist_sep
DECL|member|do_cache
DECL|member|do_dep_heuristics
DECL|member|do_deps
DECL|member|do_mocs
DECL|member|do_preprocess
DECL|member|do_pwd
DECL|member|do_stub_makefile
DECL|member|field_sep
DECL|member|func
DECL|member|h_ext
DECL|member|h_moc_ext
DECL|member|h_moc_mod
DECL|member|host_mode
DECL|member|js_ext
DECL|member|lex_ext
DECL|member|lex_mod
DECL|member|libtool_ext
DECL|member|mmp_ext
DECL|member|obj_ext
DECL|member|output
DECL|member|output_dir
DECL|member|pkgcfg_ext
DECL|member|prf_ext
DECL|member|prl_ext
DECL|member|pro_ext
DECL|member|project_build_root
DECL|member|project_dirs
DECL|member|project_files
DECL|member|properties
DECL|member|qmake_abslocation
DECL|member|qmake_mode
DECL|member|qmakespec
DECL|member|qmakespec_commandline
DECL|member|recursive
DECL|member|res_ext
DECL|member|shellPath
DECL|member|sysenv_mod
DECL|member|target_mode
DECL|member|target_mode_overridden
DECL|member|ui_ext
DECL|member|user_configs
DECL|member|user_template
DECL|member|user_template_prefix
DECL|member|warn_level
DECL|member|yacc_ext
DECL|member|yacc_mod
DECL|variable|cache_items
