DECL|enumerator|E_BASENAME
DECL|enumerator|E_CAT
DECL|enumerator|E_DIRNAME
DECL|enumerator|E_ESCAPE_EXPAND
DECL|enumerator|E_EVAL
DECL|enumerator|E_FILES
DECL|enumerator|E_FIND
DECL|enumerator|E_FIRST
DECL|enumerator|E_FROMFILE
DECL|enumerator|E_JOIN
DECL|enumerator|E_LAST
DECL|enumerator|E_LIST
DECL|enumerator|E_LOWER
DECL|enumerator|E_MEMBER
DECL|enumerator|E_PROMPT
DECL|enumerator|E_QUOTE
DECL|enumerator|E_REPLACE
DECL|enumerator|E_RESOLVE_DEPENDS
DECL|enumerator|E_RE_ESCAPE
DECL|enumerator|E_SECTION
DECL|enumerator|E_SIZE
DECL|enumerator|E_SORT_DEPENDS
DECL|enumerator|E_SPLIT
DECL|enumerator|E_SPRINTF
DECL|enumerator|E_SYSTEM
DECL|enumerator|E_UNIQUE
DECL|enumerator|E_UPPER
DECL|enumerator|T_BREAK
DECL|enumerator|T_CLEAR
DECL|enumerator|T_CONFIG
DECL|enumerator|T_CONTAINS
DECL|enumerator|T_COUNT
DECL|enumerator|T_DEBUG
DECL|enumerator|T_DEFINED
DECL|enumerator|T_EQUALS
DECL|enumerator|T_ERROR
DECL|enumerator|T_EVAL
DECL|enumerator|T_EXISTS
DECL|enumerator|T_EXPORT
DECL|enumerator|T_GREATERTHAN
DECL|enumerator|T_IF
DECL|enumerator|T_INCLUDE
DECL|enumerator|T_INFILE
DECL|enumerator|T_ISEMPTY
DECL|enumerator|T_LESSTHAN
DECL|enumerator|T_LOAD
DECL|enumerator|T_MESSAGE
DECL|enumerator|T_NEXT
DECL|enumerator|T_OPTION
DECL|enumerator|T_REQUIRES
DECL|enumerator|T_RETURN
DECL|enumerator|T_SYSTEM
DECL|enumerator|T_UNSET
DECL|enumerator|T_WARNING
DECL|enum|ExpandFunc
DECL|enum|TestFunc
DECL|function|FunctionBlock
DECL|function|IteratorBlock
DECL|function|ParsableBlock
DECL|function|Parse
DECL|function|QMakeProject
DECL|function|Test
DECL|function|continueBlock
DECL|function|continueBlock
DECL|function|deref
DECL|function|doProjectCheckReqs
DECL|function|doProjectExpand
DECL|function|doProjectExpand
DECL|function|doProjectExpand
DECL|function|doProjectInclude
DECL|function|doProjectTest
DECL|function|doProjectTest
DECL|function|doProjectTest
DECL|function|doProjectTest
DECL|function|doVariableReplace
DECL|function|doVariableReplaceExpand
DECL|function|eval
DECL|function|exec
DECL|function|exec
DECL|function|expand
DECL|function|expand
DECL|function|expand
DECL|function|init
DECL|function|isActiveConfig
DECL|function|isEmpty
DECL|function|parse
DECL|function|populateDeps
DECL|function|qmake_error_msg
DECL|function|qmake_expandFunctions
DECL|function|qmake_feature_paths
DECL|function|qmake_mkspec_paths
DECL|function|qmake_testFunctions
DECL|function|read
DECL|function|read
DECL|function|read
DECL|function|read
DECL|function|ref
DECL|function|remove_quotes
DECL|function|reset
DECL|function|resolveSpec
DECL|function|split_arg_list
DECL|function|split_value_list
DECL|function|test
DECL|function|test
DECL|function|validateModes
DECL|function|values
DECL|function|varMap
DECL|function|~ParsableBlock
DECL|function|~QMakeProject
DECL|function|~ScopeBlock
DECL|macro|QT_PCLOSE
DECL|macro|QT_PCLOSE
DECL|macro|QT_POPEN
DECL|macro|QT_POPEN
DECL|macro|SKIP_WS
DECL|macro|SKIP_WS
DECL|member|args
DECL|member|calling_place
DECL|member|cause_break
DECL|member|cause_next
DECL|member|cause_return
DECL|member|file
DECL|member|from_file
DECL|member|func
DECL|member|invert
DECL|member|line_no
DECL|member|list
DECL|member|loop_forever
DECL|member|parselist
DECL|member|pi
DECL|member|pi
DECL|member|ref_cnt
DECL|member|return_value
DECL|member|scope_level
DECL|member|scope_level
DECL|member|test
DECL|member|text
DECL|member|variable
DECL|member|vars
DECL|struct|FunctionBlock
DECL|struct|IteratorBlock
DECL|struct|ParsableBlock
DECL|struct|Parse
DECL|struct|Test
DECL|struct|parser_info
DECL|variable|parser
