DECL|class|ProjectBuilderSources
DECL|function|ProjectBuilderMakefileGenerator
DECL|function|ProjectBuilderSources
DECL|function|ProjectBuilderSubDirs
DECL|function|compilerName
DECL|function|escapeFilePath
DECL|function|files
DECL|function|findProgram
DECL|function|fixForOutput
DECL|function|fixListForOutput
DECL|function|groupName
DECL|function|isBuildable
DECL|function|isObjectOutput
DECL|function|keyFor
DECL|function|keyName
DECL|function|openOutput
DECL|function|pbuilderVersion
DECL|function|pbxbuild
DECL|function|projectSuffix
DECL|function|qtSha1
DECL|function|reftypeForFile
DECL|function|sourceTreeForFile
DECL|function|writeMakeParts
DECL|function|writeMakefile
DECL|function|writeSettings
DECL|function|writeSubDirs
DECL|function|xcodeFiletypeForFilename
DECL|function|~ProjectBuilderSubDirs
DECL|member|autoDelete
DECL|member|buildable
DECL|member|compiler
DECL|member|group
DECL|member|key
DECL|member|object_output
DECL|member|project
DECL|member|subdir
DECL|struct|ProjectBuilderSubDirs
