DECL|function|QWaylandDisplay
DECL|function|argbPremultipliedVisual
DECL|function|argbVisual
DECL|function|blockingReadEvents
DECL|function|createNewScreen
DECL|function|createShmBuffer
DECL|function|createSurface
DECL|function|displayHandleGlobal
DECL|function|displayHandleGlobal
DECL|function|eglIntegration
DECL|function|flushRequests
DECL|function|frameCallback
DECL|function|handleSelectionOffer
DECL|function|handleVisual
DECL|function|outputHandleGeometry
DECL|function|readEvents
DECL|function|rgbVisual
DECL|function|shellHandleConfigure
DECL|function|sourceUpdate
DECL|function|syncCallback
DECL|function|waitForScreens
DECL|function|windowManagerIntegration
DECL|function|~QWaylandDisplay
DECL|member|compositorListener
DECL|member|outputListener
DECL|member|shellListener
