DECL|class|QWaylandDragOfferWrapper
DECL|class|QWaylandDragWrapper
DECL|function|QWaylandDrag
DECL|function|QWaylandDragOfferWrapper
DECL|function|QWaylandDragWrapper
DECL|function|createDragOffer
DECL|function|drop
DECL|function|finish
DECL|function|instance
DECL|function|mimeData
DECL|function|motion
DECL|function|offer
DECL|function|pipeReadable
DECL|function|platformDropData
DECL|function|pointerFocus
DECL|function|reject
DECL|function|sendEventToWindow
DECL|function|showDragPixmap
DECL|function|startDrag
DECL|function|target
DECL|function|~QWaylandDrag
DECL|function|~QWaylandDragOfferWrapper
DECL|function|~QWaylandDragWrapper
DECL|member|dragListener
DECL|member|dragListener
DECL|member|dragOfferListener
DECL|member|dragOfferListener
DECL|member|mAccepted
DECL|member|mAcceptedType
DECL|member|mData
DECL|member|mData
DECL|member|mDisplay
DECL|member|mDisplay
DECL|member|mDrag
DECL|member|mFocusSurface
DECL|member|mLastEventPos
DECL|member|mOffer
DECL|member|mOfferedTypes
DECL|variable|dnd
