DECL|class|QWaylandSelection
DECL|function|QWaylandClipboard
DECL|function|QWaylandSelection
DECL|function|cancelled
DECL|function|createSelectionOffer
DECL|function|forceRoundtrip
DECL|function|getTime
DECL|function|keyboardFocus
DECL|function|mimeData
DECL|function|offer
DECL|function|send
DECL|function|setMimeData
DECL|function|supportsMode
DECL|function|syncCallback
DECL|function|unregisterSelection
DECL|function|~QWaylandClipboard
DECL|function|~QWaylandSelection
DECL|member|mMimeData
DECL|member|mSelection
DECL|member|selectionListener
DECL|member|selectionListener
DECL|member|selectionOfferListener
DECL|variable|clipboard
