DECL|class|tst_uic
DECL|function|cleanupTestCase
DECL|function|compare
DECL|function|compare_data
DECL|function|initTestCase
DECL|function|msgProcessStartFailed
DECL|function|run
DECL|function|runCompare
DECL|function|runTranslation
DECL|function|run_data
DECL|function|stdOut
DECL|function|tst_uic
DECL|member|m_baseline
DECL|member|m_command
DECL|member|m_generated
