DECL|class|tst_QDirModel
DECL|function|cleanup
DECL|function|cleanupTestCase
DECL|function|fileName
DECL|function|fileName_data
DECL|function|filePath
DECL|function|filter
DECL|function|getSetCheck
DECL|function|hidden
DECL|function|init
DECL|function|initTestCase
DECL|function|mkdir
DECL|function|mkdir_data
DECL|function|rmdir
DECL|function|rmdir_data
DECL|function|roleNames
DECL|function|roleNames_data
DECL|function|rowsAboutToBeRemoved
DECL|function|rowsAboutToBeRemoved_cleanup
DECL|function|rowsAboutToBeRemoved_data
DECL|function|rowsAboutToBeRemoved_init
DECL|function|task196768_sorting
DECL|function|task244669_remove
DECL|function|tst_QDirModel
DECL|function|unreadable
DECL|function|~tst_QDirModel
