DECL|class|AutoRegistrationObject
DECL|class|ClassWithOneMember
DECL|class|ClassWithPrivateSignals
DECL|class|CustomQObject
DECL|class|CustomQObject2
DECL|class|MyDPointer
DECL|class|NamespacedQObject
DECL|class|NamespacedQObject2
DECL|class|Obj
DECL|class|PrivateClass
DECL|class|PrivatePropertyTest
DECL|class|QTBUG11647_constInTemplateParameter
DECL|class|QTBUG12260_defaultTemplate_Object
DECL|class|QTBUG5590_DummyObject
DECL|class|QTBUG5590_PropertyObject
DECL|class|QTBUG7421_ReturnConstTemplate
DECL|class|QTBUG9354_constInName
DECL|class|QTBUG_17635_InvokableAndProperty
DECL|class|SignalConnectionTester
DECL|class|StaticPluginInstance
DECL|class|StringLiteralsInMacroExtension
DECL|class|SubClassFromPrivateSignals
DECL|class|TestClassReferencingUnrelatedEnum
DECL|class|TestTemplate2
DECL|class|UnrelatedClass
DECL|class|VersionTest
DECL|class|VersionTestNotify
DECL|class|VeryLongStringData
DECL|enumerator|One
DECL|enumerator|One
DECL|enumerator|One
DECL|enumerator|One
DECL|enumerator|Something
DECL|enumerator|SomethingElse
DECL|enumerator|Two
DECL|enumerator|Two
DECL|enumerator|Two
DECL|enumerator|Two
DECL|enumerator|UnrelatedInvalidValue
DECL|enumerator|UnrelatedValue
DECL|enumerator|Zero
DECL|enumerator|Zero
DECL|enum|MyEnum
DECL|enum|Number
DECL|enum|Number
DECL|enum|TestEnum
DECL|enum|TestEnum
DECL|enum|UnrelatedEnum
DECL|function|AutoRegistrationObject
DECL|function|ClassWithPrivateSignals
DECL|function|CustomQObject
DECL|function|CustomQObject2
DECL|function|MyDPointer
DECL|function|NamespacedQObject
DECL|function|NamespacedQObject2
DECL|function|PrivateClass
DECL|function|PrivatePropertyTest
DECL|function|QTBUG12260_defaultTemplate
DECL|function|QTBUG17635_invokableAndProperty
DECL|function|QTBUG32933_relatedObjectsDontIncludeItself
DECL|function|QTBUG5590_PropertyObject
DECL|function|QTBUG5590_dummyProperty
DECL|function|SignalConnectionTester
DECL|function|StaticPluginInstance
DECL|function|SubClassFromPrivateSignals
DECL|function|TestClassReferencingUnrelatedEnum
DECL|function|autoMethodArgumentMetaTypeRegistration
DECL|function|autoPropertyMetaTypeRegistration
DECL|function|autoSignalSpyMetaTypeRegistration
DECL|function|bar
DECL|function|baz
DECL|function|blub
DECL|function|bu1
DECL|function|bu2
DECL|function|bu3
DECL|function|bu4
DECL|function|bu5
DECL|function|bu6
DECL|function|c
DECL|function|construct
DECL|function|construct
DECL|function|constructors
DECL|function|cstyleEnums
DECL|function|customNonQObjectNamespaced
DECL|function|customObject
DECL|function|customObjectNamespaced
DECL|function|customObjectP
DECL|function|customObjectSlot
DECL|function|customObjectTP
DECL|function|customObjectTypedef
DECL|function|customObjectWP
DECL|function|cxx11Enums
DECL|function|cxx11Enums_data
DECL|function|d_func
DECL|function|defineMacroViaCmdline
DECL|function|doSomething
DECL|function|emitPrivateSignals
DECL|function|emitProtectedSignals
DECL|function|enumProperty
DECL|function|enumSlot
DECL|function|enumValue
DECL|function|escapesInStringLiterals
DECL|function|explicitOverrideControl
DECL|function|explicitOverrideControl_data
DECL|function|finalClasses
DECL|function|finalClasses_data
DECL|function|foo
DECL|function|foo
DECL|function|foo
DECL|function|foo
DECL|function|foo
DECL|function|foo
DECL|function|foo
DECL|function|forgottenQInterface
DECL|function|frameworkSearchPath
DECL|function|getChicken
DECL|function|getEgg
DECL|function|ignoreOptionClashes
DECL|function|inlineSlotsWithThrowDeclaration
DECL|function|invokable
DECL|function|listCustomObjectSlot
DECL|function|listInt
DECL|function|listIntSlot
DECL|function|listObject
DECL|function|memberProperties
DECL|function|memberProperties2
DECL|function|memberProperties_data
DECL|function|method1
DECL|function|method1
DECL|function|method2
DECL|function|method2
DECL|function|namespacedFlags
DECL|function|namespacedNonQObjectSlot
DECL|function|namespacedQObjectSlot
DECL|function|notifyError
DECL|function|numberOfChickens
DECL|function|numberOfEggs
DECL|function|object
DECL|function|objectSlot
DECL|function|os9Newline
DECL|function|parseDefines
DECL|function|plop
DECL|function|preprocessorOnly
DECL|function|privateClass
DECL|function|privateSignalConnection
DECL|function|qprivateproperties
DECL|function|qprivateslots
DECL|function|ref1
DECL|function|ref2
DECL|function|ref3
DECL|function|ref4
DECL|function|relatedMetaObjectsInGadget
DECL|function|relatedMetaObjectsNameConflict
DECL|function|relatedMetaObjectsNameConflict_data
DECL|function|relatedMetaObjectsWithinNamespaces
DECL|function|returnConstInt
DECL|function|returnConstString
DECL|function|returnConstString2
DECL|function|returnConstTemplate1
DECL|function|returnConstTemplate2
DECL|function|returnRefs
DECL|function|revisions
DECL|function|revisions_T
DECL|function|setBar
DECL|function|setBaz
DECL|function|setBlub
DECL|function|setEnumProperty
DECL|function|setFoo
DECL|function|setPlop
DECL|function|setValue
DECL|function|setValue2
DECL|function|sharedPointerSlot
DECL|function|singleFunctionKeywordSignalAndSlot
DECL|function|slot1
DECL|function|slot1
DECL|function|slot2
DECL|function|slot2
DECL|function|slot3
DECL|function|slot3
DECL|function|slot4
DECL|function|slot4
DECL|function|slotChooseScientificConst0
DECL|function|slotsWithVoidTemplate
DECL|function|someSlot
DECL|function|someSlot2
DECL|function|specifyMetaTagsFromCmdline
DECL|function|strignLiteralsInMacroExtension
DECL|function|structQObject
DECL|function|templateGtGt
DECL|function|testSlot
DECL|function|testSlot
DECL|function|testSlot2
DECL|function|testSlot3
DECL|function|testSlotWith1Arg
DECL|function|testSlotWith2Args
DECL|function|trackingPointerSlot
DECL|function|typedefSlot
DECL|function|typenameWithUnsigned
DECL|function|unterminatedFunctionMacro
DECL|function|value
DECL|function|value2
DECL|function|vectorListCustomObjectSlot
DECL|function|vectorListInt
DECL|function|vectorListIntSlot
DECL|function|vectorListObject
DECL|function|vectorVariant
DECL|function|vectorVariantSlot
DECL|function|veryLongStringData
DECL|function|warnOnMultipleInheritance
DECL|function|warnOnPropertyWithoutREAD
DECL|function|warnOnVirtualSignal
DECL|function|warnings
DECL|function|warnings_data
DECL|function|weakPointerSlot
DECL|function|winNewline
DECL|function|writeEnumFromUnrelatedClass
DECL|macro|ADD
DECL|macro|ADD
DECL|macro|DONT_CONFUSE_MOC
DECL|macro|DONT_CONFUSE_MOC_EVEN_MORE
DECL|macro|FOR_EACH_SLOT_ARG_TYPE
DECL|macro|FOR_EACH_SLOT_ARG_TYPE
DECL|macro|MACRO_DEFINED
DECL|macro|MACRO_WITH_POSSIBLE_COMPILER_SPECIFIC_ATTRIBUTES
DECL|macro|Macro
DECL|macro|Macro
DECL|macro|Macro
DECL|macro|Macro
DECL|macro|Macro
DECL|macro|Macro
DECL|macro|SKIP_NEWLINE_TEST
DECL|macro|TYPE_LOOP
DECL|macro|TYPE_LOOP
DECL|macro|_TASK_119503
DECL|macro|emit
DECL|macro|repeat1024
DECL|macro|repeat1024
DECL|macro|repeat128
DECL|macro|repeat128
DECL|macro|repeat16
DECL|macro|repeat16
DECL|macro|repeat16384
DECL|macro|repeat16384
DECL|macro|repeat2
DECL|macro|repeat2
DECL|macro|repeat2048
DECL|macro|repeat2048
DECL|macro|repeat256
DECL|macro|repeat256
DECL|macro|repeat32
DECL|macro|repeat32
DECL|macro|repeat32768
DECL|macro|repeat32768
DECL|macro|repeat4
DECL|macro|repeat4
DECL|macro|repeat4096
DECL|macro|repeat4096
DECL|macro|repeat512
DECL|macro|repeat512
DECL|macro|repeat64
DECL|macro|repeat64
DECL|macro|repeat65534
DECL|macro|repeat65534
DECL|macro|repeat8
DECL|macro|repeat8
DECL|macro|repeat8192
DECL|macro|repeat8192
DECL|macro|signals
DECL|macro|slots
DECL|member|ba
DECL|member|d
DECL|member|mBar
DECL|member|mBaz
DECL|member|mBlub
DECL|member|mConst
DECL|member|mFoo
DECL|member|mPlop
DECL|member|m_enumProperty
DECL|member|m_value
DECL|member|m_value2
DECL|member|member
DECL|member|member
DECL|member|p
DECL|member|pp
DECL|member|testPassed
DECL|member|tst
DECL|member|v
DECL|member|val
DECL|namespace|NS
DECL|namespace|QTBUG32933_relatedObjectsDontIncludeItself
DECL|namespace|SomeNamespace
DECL|namespace|SomeNamespace2
DECL|struct|CustomObject10
DECL|struct|CustomObject11
DECL|struct|CustomObject12
DECL|struct|CustomObject3
DECL|struct|CustomObject4
DECL|struct|CustomObject5
DECL|struct|CustomObject6
DECL|struct|CustomObject7
DECL|struct|CustomObject8
DECL|struct|CustomObject9
DECL|struct|DefaultConstructor
DECL|struct|DefaultConstructor
DECL|struct|NamespacedNonQObject
DECL|struct|NamespacedNonQObject2
DECL|struct|QTBUG_31218
DECL|struct|QTBUG_31218_Derived
DECL|typedef|CustomQObject2Star
DECL|typedef|CustomQObjectStar
DECL|variable|QList
DECL|variable|staticInstance
