DECL|macro|ADD
DECL|macro|ADD
DECL|macro|DONT_CONFUSE_MOC
DECL|macro|DONT_CONFUSE_MOC_EVEN_MORE
DECL|macro|FOR_EACH_SLOT_ARG_TYPE
DECL|macro|FOR_EACH_SLOT_ARG_TYPE
DECL|macro|MACRO_DEFINED
DECL|macro|MACRO_WITH_POSSIBLE_COMPILER_SPECIFIC_ATTRIBUTES
DECL|macro|Macro
DECL|macro|Macro
DECL|macro|Macro
DECL|macro|Macro
DECL|macro|Macro
DECL|macro|Macro
DECL|macro|SKIP_NEWLINE_TEST
DECL|macro|TYPE_LOOP
DECL|macro|TYPE_LOOP
DECL|macro|_TASK_119503
DECL|macro|emit
DECL|macro|repeat1024
DECL|macro|repeat1024
DECL|macro|repeat128
DECL|macro|repeat128
DECL|macro|repeat16
DECL|macro|repeat16
DECL|macro|repeat16384
DECL|macro|repeat16384
DECL|macro|repeat2
DECL|macro|repeat2
DECL|macro|repeat2048
DECL|macro|repeat2048
DECL|macro|repeat256
DECL|macro|repeat256
DECL|macro|repeat32
DECL|macro|repeat32
DECL|macro|repeat32768
DECL|macro|repeat32768
DECL|macro|repeat4
DECL|macro|repeat4
DECL|macro|repeat4096
DECL|macro|repeat4096
DECL|macro|repeat512
DECL|macro|repeat512
DECL|macro|repeat64
DECL|macro|repeat64
DECL|macro|repeat65534
DECL|macro|repeat65534
DECL|macro|repeat8
DECL|macro|repeat8
DECL|macro|repeat8192
DECL|macro|repeat8192
DECL|macro|signals
DECL|macro|slots
DECL|struct|QTBUG_31218
