DECL|class|CtorTestClass
DECL|class|EnumSourceClass
DECL|class|EnumUserClass
DECL|class|MyDPointer
DECL|class|PrivateClass
DECL|class|PrivatePropertyTest
DECL|class|PropertyTestClass
DECL|class|PropertyUseClass
DECL|class|QTBUG11647_constInTemplateParameter
DECL|class|QTBUG12260_defaultTemplate_Object
DECL|class|QTBUG5590_DummyObject
DECL|class|QTBUG5590_PropertyObject
DECL|class|QTBUG7421_ReturnConstTemplate
DECL|class|QTBUG9354_constInName
DECL|class|QTBUG_17635_InvokableAndProperty
DECL|class|Receiver
DECL|class|Sender
DECL|class|TestClass
DECL|class|TestClassinfoWithEscapes
DECL|class|TestSuperClass
DECL|class|TestTemplate2
DECL|class|VersionTest
DECL|class|VersionTestNotify
DECL|class|tst_Moc
DECL|enumerator|One
DECL|enumerator|One
DECL|enumerator|One
DECL|enumerator|Three
DECL|enumerator|Two
DECL|enumerator|Two
DECL|enumerator|Two
DECL|enumerator|Value
DECL|enum|TestEnum
DECL|enum|TestEnum
DECL|enum|TestEnum
DECL|enum|TestEnum
DECL|function|CtorTestClass
DECL|function|CtorTestClass
DECL|function|CtorTestClass
DECL|function|CtorTestClass
DECL|function|MyDPointer
DECL|function|Points
DECL|function|PrivateClass
DECL|function|PrivatePropertyTest
DECL|function|QTBUG12260_defaultTemplate
DECL|function|QTBUG17635_invokableAndProperty
DECL|function|QTBUG5590_PropertyObject
DECL|function|QTBUG5590_dummyProperty
DECL|function|Receiver
DECL|function|TestClass
DECL|function|TestSuperClass
DECL|function|arrayArguments
DECL|function|bar
DECL|function|baz
DECL|function|blackslashNewlines
DECL|function|blub1
DECL|function|blub2
DECL|function|c
DECL|function|classinfoWithEscapes
DECL|function|constructors
DECL|function|cstyleEnums
DECL|function|cxx11Enums
DECL|function|cxx11Enums_data
DECL|function|d_func
DECL|function|defineMacroViaCmdline
DECL|function|doAnotherThing
DECL|function|doSomething
DECL|function|dontStripNamespaces
DECL|function|escapesInStringLiterals
DECL|function|expressionEvaluationShortcut1
DECL|function|expressionEvaluationShortcut2
DECL|function|foo
DECL|function|foo
DECL|function|foo
DECL|function|foo
DECL|function|foo
DECL|function|foo
DECL|function|foo
DECL|function|foo
DECL|function|foo
DECL|function|forgottenQInterface
DECL|function|frameworkSearchPath
DECL|function|getChicken
DECL|function|getEgg
DECL|function|initTestCase
DECL|function|inlineSlotsWithThrowDeclaration
DECL|function|inputFileNameWithDotsButNoExtension
DECL|function|invalidSlot
DECL|function|invalidSlot
DECL|function|invokable
DECL|function|longDoubleProperty
DECL|function|longIntProperty
DECL|function|method1
DECL|function|method1
DECL|function|method2
DECL|function|method2
DECL|function|multilineComments
DECL|function|myInvokableReturningConstRef
DECL|function|myInvokableReturningRef
DECL|function|namespaceTypeProperty
DECL|function|namespacedFlags
DECL|function|notifyError
DECL|function|numberOfChickens
DECL|function|numberOfEggs
DECL|function|oldStyleCasts
DECL|function|os9Newline
DECL|function|plop
DECL|function|points
DECL|function|ppExpressionEvaluation
DECL|function|preprocessorConditionals
DECL|function|privateClass
DECL|function|qprivateproperties
DECL|function|qprivateslots
DECL|function|receive
DECL|function|receive
DECL|function|returnConstInt
DECL|function|returnConstString
DECL|function|returnConstString2
DECL|function|returnConstTemplate1
DECL|function|returnConstTemplate2
DECL|function|returnRefs
DECL|function|revisions
DECL|function|revisions_T
DECL|function|sendValue
DECL|function|sendValue
DECL|function|setBar
DECL|function|setBaz
DECL|function|setFoo
DECL|function|setPlop
DECL|function|setPoints
DECL|function|setValue
DECL|function|setValue2
DECL|function|shortIntProperty
DECL|function|signedLongIntProperty
DECL|function|signedShortIntProperty
DECL|function|singleFunctionKeywordSignalAndSlot
DECL|function|slot1
DECL|function|slot1
DECL|function|slot2
DECL|function|slot2
DECL|function|slot3
DECL|function|slot3
DECL|function|slot4
DECL|function|slot4
DECL|function|slotChooseScientificConst0
DECL|function|slotInElif
DECL|function|slotInElse
DECL|function|slotInIf
DECL|function|slotInLastElse
DECL|function|slotWithAReallyLongName
DECL|function|slotWithArray
DECL|function|slotWithColonColonType
DECL|function|slotWithException
DECL|function|slotWithLong
DECL|function|slotWithLongLong
DECL|function|slotWithMultiArray
DECL|function|slotWithNamedArray
DECL|function|slotWithReferenceReturnType
DECL|function|slotWithSillyConst
DECL|function|slotWithSillyConst
DECL|function|slotWithSillyConst2
DECL|function|slotWithULong
DECL|function|slotWithULongLong
DECL|function|slotWithULongLongP
DECL|function|slotWithVoidStar
DECL|function|slotsWithVoidTemplate
DECL|function|someSlot
DECL|function|someSlot2
DECL|function|srcify
DECL|function|structQObject
DECL|function|supportConstSignals
DECL|function|task87883
DECL|function|templateGtGt
DECL|function|testExtraData
DECL|function|testExtraDataForEnum
DECL|function|testSlot
DECL|function|testSlot2
DECL|function|testSlot3
DECL|function|trNoopInClassInfo
DECL|function|tst_Moc
DECL|function|typenameWithUnsigned
DECL|function|uLongLong
DECL|function|unsignedLongIntProperty
DECL|function|unsignedShortIntProperty
DECL|function|user1
DECL|function|user2
DECL|function|user3
DECL|function|userFunction
DECL|function|userProperties
DECL|function|value
DECL|function|value2
DECL|function|warnOnExtraSignalSlotQualifiaction
DECL|function|warnOnMultipleInheritance
DECL|function|warnOnPropertyWithoutREAD
DECL|function|warnOnVirtualSignal
DECL|function|warnings
DECL|function|warnings_data
DECL|function|winNewline
DECL|macro|DONT_CONFUSE_MOC
DECL|macro|DONT_CONFUSE_MOC_EVEN_MORE
DECL|macro|MACRO_DEFINED
DECL|macro|MACRO_WITH_POSSIBLE_COMPILER_SPECIFIC_ATTRIBUTES
DECL|macro|SKIP_NEWLINE_TEST
DECL|macro|_TASK_119503
DECL|member|d
DECL|member|doNotConfuseMoc
DECL|member|intCallCount
DECL|member|mBar
DECL|member|mBaz
DECL|member|mFoo
DECL|member|mPlop
DECL|member|m_points
DECL|member|m_str
DECL|member|m_value
DECL|member|m_value2
DECL|member|p1
DECL|member|p2
DECL|member|qtIncludePath
DECL|member|stringCallCount
DECL|namespace|Int
DECL|namespace|MyNamespace
DECL|namespace|String
DECL|namespace|myNS
DECL|struct|MyStruct
DECL|struct|MyStruct2
DECL|struct|Points
DECL|struct|StructQObject
DECL|struct|SuperClass
DECL|typedef|OldStyleCStruct
DECL|typedef|Type
DECL|typedef|Type
DECL|variable|QList
DECL|variable|test_multiple_number_of_escapes
