DECL|class|QTouchScreenData
DECL|function|Contact
DECL|function|QTouchScreenData
DECL|function|QTouchScreenHandler
DECL|function|QTouchScreenHandlerThread
DECL|function|assignIds
DECL|function|findClosestContact
DECL|function|processInputEvent
DECL|function|readData
DECL|function|registerDevice
DECL|function|reportPoints
DECL|function|run
DECL|function|~QTouchScreenHandler
DECL|function|~QTouchScreenHandlerThread
DECL|member|flags
DECL|member|hw_name
DECL|member|hw_pressure_max
DECL|member|hw_pressure_min
DECL|member|hw_range_x_max
DECL|member|hw_range_x_min
DECL|member|hw_range_y_max
DECL|member|hw_range_y_min
DECL|member|m_contacts
DECL|member|m_currentData
DECL|member|m_device
DECL|member|m_forceToActiveWindow
DECL|member|m_lastContacts
DECL|member|m_lastEventType
DECL|member|m_touchPoints
DECL|member|maj
DECL|member|pressure
DECL|member|q
DECL|member|state
DECL|member|trackingId
DECL|member|x
DECL|member|y
DECL|struct|Contact
