DECL|class|tst_QDateTime
DECL|function|addDays
DECL|function|addMSecs
DECL|function|addMSecs_data
DECL|function|addMonths
DECL|function|addMonths_data
DECL|function|addSecs
DECL|function|addSecs_data
DECL|function|addYears
DECL|function|addYears_data
DECL|function|ctor
DECL|function|currentDateTime
DECL|function|currentDateTimeUtc
DECL|function|currentDateTimeUtc2
DECL|function|date
DECL|function|daylightSavingsTimeChange
DECL|function|daysTo
DECL|function|defDate
DECL|function|defDateTime
DECL|function|defTime
DECL|function|dt
DECL|function|fewDigitsInYear
DECL|function|fromMSecsSinceEpoch
DECL|function|fromMSecsSinceEpoch_data
DECL|function|fromStringDateFormat
DECL|function|fromStringDateFormat_data
DECL|function|fromStringStringFormat
DECL|function|fromStringStringFormat_data
DECL|function|fromStringToStringLocale
DECL|function|fromStringToStringLocale_data
DECL|function|fromString_LOCALE_ILDATE
DECL|function|getDate
DECL|function|init
DECL|function|invalidDate
DECL|function|invalidDateTime
DECL|function|invalidTime
DECL|function|isNull
DECL|function|isValid
DECL|function|msecsTo
DECL|function|msecsTo_data
DECL|function|operator_eq
DECL|function|operator_eqeq
DECL|function|operator_eqeq_data
DECL|function|operator_insert_extract
DECL|function|operator_insert_extract_data
DECL|function|printNegativeYear
DECL|function|roundtripGermanLocale
DECL|function|secsTo
DECL|function|secsTo_data
DECL|function|setDate
DECL|function|setMSecsSinceEpoch
DECL|function|setMSecsSinceEpoch_data
DECL|function|setTime
DECL|function|setTimeSpec
DECL|function|setTimeSpec_data
DECL|function|setTime_data
DECL|function|setTime_t
DECL|function|setUtcOffset
DECL|function|str
DECL|function|time
DECL|function|timeSpec
DECL|function|toLocalTime
DECL|function|toLocalTime_data
DECL|function|toString_enumformat
DECL|function|toString_isoDate
DECL|function|toString_isoDate_data
DECL|function|toString_strformat
DECL|function|toString_strformat_data
DECL|function|toTimeSpec
DECL|function|toTimeSpec_data
DECL|function|toTime_t
DECL|function|toTime_t_data
DECL|function|toUTC
DECL|function|toUTC_data
DECL|function|tst_QDateTime
DECL|function|utcOffset
DECL|function|utcOffsetLessThan
DECL|member|europeanTimeZone
