DECL|class|tst_QVersionNumber
DECL|function|assignment
DECL|function|assignment_data
DECL|function|commonPrefix
DECL|function|commonPrefix_data
DECL|function|compare
DECL|function|compareEqual
DECL|function|compareEqual_data
DECL|function|compareGreater
DECL|function|compareGreaterEqual
DECL|function|compareGreaterEqual_data
DECL|function|compareGreater_data
DECL|function|compareLess
DECL|function|compareLessEqual
DECL|function|compareLessEqual_data
DECL|function|compareLess_data
DECL|function|compareNotEqual
DECL|function|compareNotEqual_data
DECL|function|compare_data
DECL|function|comparisonData
DECL|function|constructorCopy
DECL|function|constructorCopy_data
DECL|function|constructorDefault
DECL|function|constructorExplicit
DECL|function|constructorVersioned
DECL|function|constructorVersioned_data
DECL|function|fromString
DECL|function|fromString_data
DECL|function|initTestCase
DECL|function|isNormalized
DECL|function|isNormalized_data
DECL|function|isNull
DECL|function|isNull_data
DECL|function|isPrefixOf
DECL|function|isPrefixOf_data
DECL|function|moveSemantics
DECL|function|normalized
DECL|function|normalized_data
DECL|function|operator +
DECL|function|serialize
DECL|function|serialize_data
DECL|function|singleInstanceData
DECL|function|toString
DECL|function|toString_data
DECL|macro|Q_MSVC_2010
DECL|namespace|UglyOperator
