DECL|function|Cube
DECL|function|CubeBuilder
DECL|function|Tile
DECL|function|TileBuilder
DECL|function|addQuad
DECL|function|append
DECL|function|draw
DECL|function|initialize
DECL|function|loadArrays
DECL|function|newCube
DECL|function|newTile
DECL|function|qMultMatrix
DECL|function|qSetColor
DECL|function|removeBounce
DECL|function|setAltitude
DECL|function|setAnimationPaused
DECL|function|setColors
DECL|function|setColors
DECL|function|setRange
DECL|function|setRotation
DECL|function|startAnimation
DECL|function|~Cube
DECL|variable|FACE_SIZE
DECL|variable|amplitudes
DECL|variable|speeds
