DECL|function|qIsFinite
DECL|function|qIsFinite
DECL|function|qIsInf
DECL|function|qIsInf
DECL|function|qIsNaN
DECL|function|qIsNaN
DECL|function|qtInf
DECL|function|qtQnan
DECL|function|qtSnan
DECL|macro|QNUM_H
DECL|macro|Q_INFINITY
DECL|macro|Q_QNAN
DECL|macro|Q_SNAN
DECL|variable|qt_be_inf_bytes
DECL|variable|qt_be_qnan_bytes
DECL|variable|qt_be_snan_bytes
DECL|variable|qt_le_inf_bytes
DECL|variable|qt_le_qnan_bytes
DECL|variable|qt_le_snan_bytes
