DECL|class|WidgetWindowControl
DECL|class|Window
DECL|class|WindowControl
DECL|function|BaseWindowControl
DECL|function|ControllerWidget
DECL|function|CoordinateControl
DECL|function|RectControl
DECL|function|WidgetWindowControl
DECL|function|Window
DECL|function|WindowControl
DECL|function|addChildWindow
DECL|function|coordinates
DECL|function|eventFilter
DECL|function|exposeEvent
DECL|function|framePosChanged
DECL|function|handleChanged
DECL|function|hideWindow
DECL|function|lowerWindow
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|objectFramePosition
DECL|function|objectFramePosition
DECL|function|objectGeometry
DECL|function|objectGeometry
DECL|function|objectMapToGlobal
DECL|function|objectMapToGlobal
DECL|function|objectWindowFlags
DECL|function|posChanged
DECL|function|raiseWindow
DECL|function|rectValue
DECL|function|refresh
DECL|function|refresh
DECL|function|refresh
DECL|function|render
DECL|function|setCoordinates
DECL|function|setObjectFramePosition
DECL|function|setObjectFramePosition
DECL|function|setObjectGeometry
DECL|function|setObjectGeometry
DECL|function|setObjectWindowFlags
DECL|function|setObjectWindowFlags
DECL|function|setRectValue
DECL|function|showWindow
DECL|function|sizeChanged
DECL|function|spinBoxChanged
DECL|function|statesChanged
DECL|function|toggleAttachWindow
DECL|function|~ControllerWidget
DECL|member|m_backingStore
DECL|member|m_color
DECL|member|m_detachedParent
DECL|member|m_mouseDownPosition
DECL|member|m_stateControl
DECL|member|m_statesControl
DECL|member|m_window
