DECL|class|tst_QStatusBar
DECL|function|QTBUG4334_hiddenOnMaximizedWindow
DECL|function|cleanup
DECL|function|cleanupTestCase
DECL|function|init
DECL|function|initTestCase
DECL|function|insertPermanentWidget
DECL|function|insertWidget
DECL|function|messageChanged
DECL|function|setSizeGripEnabled
DECL|function|task194017_hiddenWidget
DECL|function|tempMessage
DECL|function|tst_QStatusBar
DECL|function|~tst_QStatusBar
DECL|member|currentMessage
DECL|member|testWidget
