DECL|class|InputTestWindow
DECL|class|Window
DECL|class|tst_QWindow
DECL|function|InputTestWindow
DECL|function|Window
DECL|function|event
DECL|function|isActive
DECL|function|keyPressEvent
DECL|function|keyReleaseEvent
DECL|function|mapGlobal
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|positioning
DECL|function|received
DECL|function|reset
DECL|function|testInputEvents
DECL|function|touchEvent
DECL|member|keyPressCode
DECL|member|keyReleaseCode
DECL|member|m_received
DECL|member|mousePressButton
DECL|member|mouseReleaseButton
DECL|member|touchPressedCount
DECL|member|touchReleasedCount
DECL|variable|tst_QWindow
