DECL|class|InputTestWindow
DECL|class|Window
DECL|class|tst_QWindow
DECL|function|InputTestWindow
DECL|function|Window
DECL|function|activateAndClose
DECL|function|close
DECL|function|event
DECL|function|eventIndex
DECL|function|eventOrderOnShow
DECL|function|initTestCase
DECL|function|isActive
DECL|function|isExposed
DECL|function|keyPressEvent
DECL|function|keyReleaseEvent
DECL|function|mapGlobal
DECL|function|mouseDoubleClickEvent
DECL|function|mouseEventSequence
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|mouseToTouchLoop
DECL|function|mouseToTouchTranslation
DECL|function|orientation
DECL|function|positioning
DECL|function|received
DECL|function|reset
DECL|function|resetCounters
DECL|function|testInputEvents
DECL|function|touchCancel
DECL|function|touchCancelWithTouchToMouse
DECL|function|touchEvent
DECL|function|touchToMouseTranslation
DECL|function|windowModality
DECL|member|ignoreMouse
DECL|member|ignoreTouch
DECL|member|keyPressCode
DECL|member|keyReleaseCode
DECL|member|m_order
DECL|member|m_received
DECL|member|mouseDoubleClickedCount
DECL|member|mouseMoveButton
DECL|member|mouseMoveScreenPos
DECL|member|mousePressButton
DECL|member|mousePressScreenPos
DECL|member|mousePressedCount
DECL|member|mouseReleaseButton
DECL|member|mouseReleasedCount
DECL|member|mouseSequenceSignature
DECL|member|touchDevice
DECL|member|touchEventType
DECL|member|touchMovedCount
DECL|member|touchPressedCount
DECL|member|touchReleasedCount
