DECL|class|InputTestWindow
DECL|class|Window
DECL|class|tst_QWindow
DECL|function|InputTestWindow
DECL|function|Window
DECL|function|event
DECL|function|initTestCase
DECL|function|isActive
DECL|function|keyPressEvent
DECL|function|keyReleaseEvent
DECL|function|mapGlobal
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|mouseToTouchLoop
DECL|function|mouseToTouchTranslation
DECL|function|orientation
DECL|function|positioning
DECL|function|received
DECL|function|reset
DECL|function|testInputEvents
DECL|function|touchEvent
DECL|function|touchToMouseTranslation
DECL|member|ignoreMouse
DECL|member|ignoreTouch
DECL|member|keyPressCode
DECL|member|keyReleaseCode
DECL|member|m_received
DECL|member|mouseMoveButton
DECL|member|mouseMoveScreenPos
DECL|member|mousePressButton
DECL|member|mousePressScreenPos
DECL|member|mouseReleaseButton
DECL|member|touchDevice
DECL|member|touchPressedCount
DECL|member|touchReleasedCount
DECL|variable|tst_QWindow
