DECL|class|MyButton
DECL|class|tst_QAbstractButton
DECL|function|MyButton
DECL|function|animateClick
DECL|function|cleanup
DECL|function|cleanupTestCase
DECL|function|init
DECL|function|initTestCase
DECL|function|isCheckable
DECL|function|isChecked
DECL|function|keyNavigation
DECL|function|onClicked
DECL|function|onPressed
DECL|function|onReleased
DECL|function|onToggled
DECL|function|paintEvent
DECL|function|pressed
DECL|function|released
DECL|function|resetTimerEvents
DECL|function|resetValues
DECL|function|setAutoRepeat
DECL|function|setAutoRepeat_data
DECL|function|setDown
DECL|function|setEnabled
DECL|function|setIcon
DECL|function|setShortcut
DECL|function|setText
DECL|function|shortcutEvents
DECL|function|sizeHint
DECL|function|stopRepeatTimer
DECL|function|timerEvent
DECL|function|timerEventCount
DECL|function|toggled
DECL|function|tst_QAbstractButton
DECL|function|~tst_QAbstractButton
DECL|macro|REPEAT_DELAY
DECL|member|click_count
DECL|member|press_count
DECL|member|release_count
DECL|member|testWidget
DECL|member|timerEvents
DECL|member|toggle_count
DECL|variable|last_mode
DECL|variable|test_count
