DECL|class|ScriptSharedMemory
DECL|class|ScriptSystemLock
DECL|class|ScriptSystemSemaphore
DECL|enumerator|AlreadyExists
DECL|enumerator|InvalidSize
DECL|enumerator|KeyError
DECL|enumerator|LockError
DECL|enumerator|NoError
DECL|enumerator|NotFound
DECL|enumerator|OutOfResources
DECL|enumerator|PermissionDenied
DECL|enumerator|UnknownError
DECL|enum|SharedMemoryError
DECL|function|ScriptSharedMemory
DECL|function|ScriptSystemLock
DECL|function|ScriptSystemSemaphore
DECL|function|acquire
DECL|function|attach
DECL|function|attachReadOnly
DECL|function|create
DECL|function|createReadOnly
DECL|function|data
DECL|function|detach
DECL|function|error
DECL|function|errorString
DECL|function|get
DECL|function|interactive
DECL|function|isAttached
DECL|function|key
DECL|function|key
DECL|function|key
DECL|function|lock
DECL|function|lock
DECL|function|lockReadOnly
DECL|function|main
DECL|function|release
DECL|function|set
DECL|function|setKey
DECL|function|setKey
DECL|function|setKey
DECL|function|size
DECL|function|sleep
DECL|function|unlock
DECL|function|unlock
DECL|member|sl
DECL|member|sm
DECL|member|ss
