DECL|function|QFbScreen
DECL|function|QFbWindow
DECL|function|QFbWindowSurface
DECL|function|QPlatformSoftwareCursor
DECL|function|addWindow
DECL|function|beginPaint
DECL|function|changeCursor
DECL|function|dirtyRect
DECL|function|doRedraw
DECL|function|drawCursor
DECL|function|endPaint
DECL|function|flush
DECL|function|generateRects
DECL|function|getCurrentRect
DECL|function|lower
DECL|function|lower
DECL|function|pointerEvent
DECL|function|raise
DECL|function|raise
DECL|function|removeWindow
DECL|function|repaint
DECL|function|resize
DECL|function|scroll
DECL|function|setCursor
DECL|function|setCursor
DECL|function|setCursor
DECL|function|setDepth
DECL|function|setDirty
DECL|function|setFormat
DECL|function|setGeometry
DECL|function|setGeometry
DECL|function|setPhysicalSize
DECL|function|setVisible
DECL|function|setWindowFlags
DECL|function|topLevelAt
DECL|function|windowFlags
DECL|function|~QFbScreen
DECL|function|~QFbWindow
DECL|function|~QFbWindowSurface
