DECL|function|FlowLayout
DECL|function|count
DECL|function|doLayout
DECL|function|insertItem
DECL|function|itemAt
DECL|function|maxSize
DECL|function|minSize
DECL|function|prefSize
DECL|function|removeAt
DECL|function|setGeometry
DECL|function|setSpacing
DECL|function|sizeHint
DECL|function|spacing
