DECL|function|QEGLPlatformWindow
DECL|function|create
DECL|function|endCompositing
DECL|function|isRaster
DECL|function|newWId
DECL|function|setOpacity
DECL|function|sourceWindow
DECL|function|textures
DECL|function|winId
