DECL|function|QEGLCompositor
DECL|function|destroy
DECL|function|ensureProgram
DECL|function|instance
DECL|function|render
DECL|function|renderAll
DECL|function|schedule
DECL|function|~QEGLCompositor
DECL|variable|compositor
