DECL|function|QEGLPlatformContext
DECL|function|QEGLPlatformContext
DECL|function|bindApi
DECL|function|doneCurrent
DECL|function|eglConfig
DECL|function|eglContext
DECL|function|eglDisplay
DECL|function|format
DECL|function|getProcAddress
DECL|function|init
DECL|function|makeCurrent
DECL|function|swapBuffers
DECL|function|~QEGLPlatformContext
