DECL|enumerator|BlockCount
DECL|enumerator|InitialNextValue
DECL|enumerator|Offset0
DECL|enumerator|Offset1
DECL|enumerator|Offset2
DECL|enumerator|Offset3
DECL|enumerator|Offset4
DECL|enumerator|Offset5
DECL|enumerator|Size0
DECL|enumerator|Size1
DECL|enumerator|Size2
DECL|enumerator|Size3
DECL|enumerator|Size4
DECL|enumerator|Size5
DECL|function|QAbstractEventDispatcher
DECL|function|QAbstractEventDispatcher
DECL|function|allocateTimerId
DECL|function|closingDown
DECL|function|filterEvent
DECL|function|instance
DECL|function|registerTimer
DECL|function|releaseTimerId
DECL|function|setEventFilter
DECL|function|startingUp
DECL|function|~QAbstractEventDispatcher
DECL|member|Sizes
DECL|member|Sizes
DECL|struct|QtTimerIdFreeListConstants
DECL|typedef|QtTimerIdFreeList
