DECL|function|normalizedTimespec
DECL|function|operator
DECL|function|operator
DECL|macro|EINTR_LOOP
DECL|macro|QCORE_UNIX_P_H
DECL|macro|QT_CLOSE
DECL|macro|QT_CLOSE
DECL|macro|QT_OPEN
DECL|macro|QT_OPEN
DECL|macro|QT_READ
DECL|macro|QT_READ
DECL|macro|QT_UNIX_SUPPORTS_THREADSAFE_CLOEXEC
DECL|macro|QT_UNIX_SUPPORTS_THREADSAFE_CLOEXEC
DECL|macro|QT_WRITE
DECL|macro|QT_WRITE
DECL|macro|_POSIX_MONOTONIC_CLOCK
DECL|member|array
DECL|member|buf
DECL|member|val
DECL|union|qt_semun
DECL|variable|operator
