DECL|macro|DEBUG
DECL|macro|DEBUG
DECL|macro|DEBUG
DECL|macro|DEBUG
DECL|macro|OLD_DEBUG
DECL|macro|OLD_DEBUG
DECL|macro|OLD_DEBUG
DECL|macro|QCORE_MAC_P_H
DECL|macro|SRefCon
DECL|macro|URefCon
DECL|macro|__IMAGECAPTURE__
DECL|macro|old_qDebug
DECL|macro|old_qDebug
DECL|macro|qDebug
DECL|macro|qDebug
DECL|macro|qDebug
DECL|typedef|CGFloat
DECL|typedef|NSInteger
DECL|typedef|NSUInteger
