DECL|class|QWinMsgHandlerCriticalSection
DECL|function|FLAG_STRING
DECL|function|QWinMsgHandlerCriticalSection
DECL|function|appName
DECL|function|decodeMSG
DECL|function|decodeMSG
DECL|function|findWMstr
DECL|function|flagCheck
DECL|function|lock
DECL|function|operator <<
DECL|function|qAppFileName
DECL|function|qWinAppCmdShow
DECL|function|qWinAppInst
DECL|function|qWinAppPrevInst
DECL|function|qWinMain
DECL|function|qWinMsgHandler
DECL|function|removePostedTimerEvent
DECL|function|unlock
DECL|function|valueCheck
DECL|function|winEventFilter
DECL|function|~QWinMsgHandlerCriticalSection
DECL|macro|FLGSTR
DECL|macro|GET_X_LPARAM
DECL|macro|GET_Y_LPARAM
DECL|macro|WM_NCACTIVATE
DECL|member|WM
DECL|member|cs
DECL|member|str
DECL|member|str
DECL|member|value
DECL|struct|FLAG_STRING_STRUCT
DECL|struct|KnownWM
DECL|variable|appCmdShow
DECL|variable|knownWM
DECL|variable|usingWinMain
