DECL|function|normalizedTimespec
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|qt_make_pollfd
DECL|function|qt_poll_msecs
DECL|function|qt_safe_ftok
DECL|macro|EINTR_LOOP
DECL|macro|QCORE_UNIX_P_H
DECL|macro|QT_CLOSE
DECL|macro|QT_CLOSE
DECL|macro|QT_OPEN
DECL|macro|QT_OPEN
DECL|macro|QT_READ
DECL|macro|QT_READ
DECL|macro|QT_WRITE
DECL|macro|QT_WRITE
DECL|macro|_POSIX_MONOTONIC_CLOCK
DECL|member|array
DECL|member|buf
DECL|member|val
DECL|union|qt_semun
DECL|variable|operator
