DECL|function|normalizedTimespec
DECL|function|operator
DECL|function|operator
DECL|function|operator
DECL|function|qt_safe_ftok
DECL|macro|EINTR_LOOP
DECL|macro|POLLERR
DECL|macro|POLLHUP
DECL|macro|POLLIN
DECL|macro|POLLNVAL
DECL|macro|POLLOUT
DECL|macro|POLLPRI
DECL|macro|POLLRDBAND
DECL|macro|POLLRDNORM
DECL|macro|POLLWRBAND
DECL|macro|POLLWRNORM
DECL|macro|QCORE_UNIX_P_H
DECL|macro|QT_CLOSE
DECL|macro|QT_CLOSE
DECL|macro|QT_OPEN
DECL|macro|QT_OPEN
DECL|macro|QT_READ
DECL|macro|QT_READ
DECL|macro|QT_WRITE
DECL|macro|QT_WRITE
DECL|macro|_POSIX_MONOTONIC_CLOCK
DECL|member|array
DECL|member|buf
DECL|member|events
DECL|member|fd
DECL|member|revents
DECL|member|val
DECL|struct|pollfd
DECL|typedef|nfds_t
DECL|union|qt_semun
DECL|variable|operator
