DECL|function|sendEvent
DECL|function|sendSpontaneousEvent
DECL|function|translate
DECL|macro|QCOREAPPLICATION_H
DECL|macro|Q_COREAPP_STARTUP_FUNCTION
DECL|macro|Q_DECLARE_TR_FUNCTIONS
DECL|macro|qApp
DECL|typedef|MSG
DECL|typedef|QtCleanUpFunction
DECL|typedef|QtStartUpFunction
DECL|variable|QAbstractEventDispatcher
DECL|variable|QAbstractNativeEventFilter
DECL|variable|QCoreApplicationPrivate
DECL|variable|QPostEventList
DECL|variable|QStringList
DECL|variable|QTextCodec
DECL|variable|QTranslator
