DECL|class|QMutexUnlocker
DECL|function|QCoreApplication
DECL|function|QCoreApplication
DECL|function|QCoreApplicationData
DECL|function|QCoreApplicationPrivate
DECL|function|QMutexUnlocker
DECL|function|_q_initializeProcessManager
DECL|function|addLibraryPath
DECL|function|appName
DECL|function|appendApplicationPathToLibraryPaths
DECL|function|applicationDirPath
DECL|function|applicationFilePath
DECL|function|applicationName
DECL|function|applicationPid
DECL|function|applicationVersion
DECL|function|argc
DECL|function|arguments
DECL|function|argv
DECL|function|checkInstance
DECL|function|checkReceiverThread
DECL|function|checkReceiverThread
DECL|function|closingDown
DECL|function|compressEvent
DECL|function|createEventDispatcher
DECL|function|enter_loop
DECL|function|event
DECL|function|exec
DECL|function|exit
DECL|function|exit_loop
DECL|function|filterEvent
DECL|function|flush
DECL|function|hasPendingEvents
DECL|function|init
DECL|function|installTranslator
DECL|function|isTranslatorInstalled
DECL|function|libraryPaths
DECL|function|loopLevel
DECL|function|macMenuBarName
DECL|function|mainThread
DECL|function|notify
DECL|function|notifyInternal
DECL|function|notify_helper
DECL|function|organizationDomain
DECL|function|organizationName
DECL|function|postEvent
DECL|function|postEvent
DECL|function|processEvents
DECL|function|processEvents
DECL|function|qAddPostRoutine
DECL|function|qAppName
DECL|function|qGlobalPostedEventsCount
DECL|function|qRemovePostRoutine
DECL|function|qtTrId
DECL|function|qt_call_post_routines
DECL|function|qt_cleanup_apa_cmd_line
DECL|function|qt_init_symbian_apa_arguments
DECL|function|qt_register_signal_spy_callbacks
DECL|function|qt_set_current_thread_to_main_thread
DECL|function|qt_startup_hook
DECL|function|quit
DECL|function|removeLibraryPath
DECL|function|removePostedEvent
DECL|function|removePostedEvents
DECL|function|removePostedEvents
DECL|function|removeTranslator
DECL|function|replacePercentN
DECL|function|sendPostedEvents
DECL|function|sendPostedEvents
DECL|function|sendThroughApplicationEventFilters
DECL|function|sendThroughObjectEventFilters
DECL|function|setApplicationName
DECL|function|setApplicationVersion
DECL|function|setAttribute
DECL|function|setEventFilter
DECL|function|setLibraryPaths
DECL|function|setOrganizationDomain
DECL|function|setOrganizationName
DECL|function|startingUp
DECL|function|symbianCommandLine
DECL|function|symbianInit
DECL|function|testAttribute
DECL|function|translate
DECL|function|translate
DECL|function|unlock
DECL|function|~QCoreApplication
DECL|function|~QCoreApplicationData
DECL|function|~QCoreApplicationPrivate
DECL|function|~QMutexUnlocker
DECL|member|app_compile_version
DECL|member|app_libpaths
DECL|member|application
DECL|member|applicationVersion
DECL|member|attribs
DECL|member|eventDispatcher
DECL|member|is_app_closing
DECL|member|is_app_running
DECL|member|mtx
DECL|member|orgDomain
DECL|member|orgName
DECL|member|self
DECL|member|theMainThread
DECL|member|useQt3Support
DECL|struct|QCoreApplicationData
DECL|typedef|QVFuncList
DECL|typedef|SystemDriveFunc
DECL|variable|PtrGetSystemDrive
DECL|variable|apaArgv
DECL|variable|apaCommandLine
DECL|variable|apaTail
DECL|variable|qt_application_thread_id
DECL|variable|qt_locale_initialized
DECL|variable|qt_signal_spy_callback_set
