DECL|class|QEventLoopPrivate
DECL|function|QEventLoop
DECL|function|QEventLoopPrivate
DECL|function|exec
DECL|function|exit
DECL|function|isRunning
DECL|function|processEvents
DECL|function|processEvents
DECL|function|quit
DECL|function|wakeUp
DECL|function|~QEventLoop
DECL|member|exit
DECL|member|inExec
DECL|member|returnCode
