DECL|function|QSockFd
DECL|macro|QEVENTDISPATCHER_WIN_P_H
DECL|member|dispatcher
DECL|member|event
DECL|member|fastTimerId
DECL|member|fd
DECL|member|inTimerEvent
DECL|member|interval
DECL|member|obj
DECL|member|obj
DECL|member|selected
DECL|member|timeout
DECL|member|timerId
DECL|member|timerType
DECL|struct|QSockFd
DECL|struct|QSockNot
DECL|struct|WinTimerInfo
DECL|typedef|QSFDict
DECL|typedef|QSNDict
DECL|typedef|WinTimerDict
DECL|typedef|WinTimerVec
DECL|variable|QEventDispatcherWin32Private
DECL|variable|QWinEventNotifier
