DECL|class|SocketAsyncHandler
DECL|enumerator|SendPostedEventsWindowsTimerId
DECL|enumerator|WM_QT_SENDPOSTEDEVENTS
DECL|enumerator|WM_QT_SOCKETNOTIFIER
DECL|function|QEventDispatcherWin32
DECL|function|QEventDispatcherWin32
DECL|function|QEventDispatcherWin32Private
DECL|function|SocketAsyncHandler
DECL|function|WSAAsyncSelect
DECL|function|activateEventNotifier
DECL|function|activateEventNotifiers
DECL|function|closingDown
DECL|function|createInternalHwnd
DECL|function|doWsaAsyncSelect
DECL|function|event
DECL|function|flush
DECL|function|hasPendingEvents
DECL|function|inputTimerMask
DECL|function|interrupt
DECL|function|processEvents
DECL|function|qt_GetMessageHook
DECL|function|qt_create_internal_window
DECL|function|qt_fast_timer_proc
DECL|function|qt_internal_proc
DECL|function|registerEventNotifier
DECL|function|registerSocketNotifier
DECL|function|registerTimer
DECL|function|registerTimer
DECL|function|registeredTimers
DECL|function|remainingTime
DECL|function|removeSelect
DECL|function|resolveTimerAPI
DECL|function|run
DECL|function|safeRemove
DECL|function|select
DECL|function|sendPostedEvents
DECL|function|sendTimerEvent
DECL|function|startingUp
DECL|function|unregisterEventNotifier
DECL|function|unregisterSocketNotifier
DECL|function|unregisterTimer
DECL|function|unregisterTimer
DECL|function|unregisterTimers
DECL|function|wakeUp
DECL|function|~QEventDispatcherWin32
DECL|function|~QEventDispatcherWin32Private
DECL|function|~SocketAsyncHandler
DECL|macro|DWORD_PTR
DECL|macro|QS_RAWINPUT
DECL|macro|QS_RAWINPUT
DECL|macro|TIME_KILL_SYNCHRONOUS
DECL|macro|WM_GESTURE
DECL|macro|WM_GESTURENOTIFY
DECL|macro|WM_TOUCH
DECL|member|cond
DECL|member|ev
DECL|member|handle
DECL|member|msg
DECL|member|mutex
DECL|member|sockets
DECL|member|supposedToDie
DECL|struct|SockInfo
DECL|typedef|ptimeKillEvent
DECL|typedef|ptimeSetEvent
DECL|variable|qtimeKillEvent
DECL|variable|qtimeSetEvent
