DECL|macro|QEVENTDISPATCHER_WIN_P_H
DECL|member|dispatcher
DECL|member|fastTimerId
DECL|member|fd
DECL|member|inTimerEvent
DECL|member|interval
DECL|member|obj
DECL|member|obj
DECL|member|timerId
DECL|struct|QSockNot
DECL|struct|WinTimerInfo
DECL|typedef|QSNDict
DECL|typedef|WinTimerDict
DECL|typedef|WinTimerVec
DECL|variable|QEventDispatcherWin32Private
DECL|variable|QWinEventNotifier
