DECL|class|QEventDispatcherWinRTPrivate
DECL|class|QZeroTimerEvent
DECL|function|QEventDispatcherWinRT
DECL|function|QEventDispatcherWinRT
DECL|function|QEventDispatcherWinRTPrivate
DECL|function|QZeroTimerEvent
DECL|function|WinRTTimerInfo
DECL|function|cancel
DECL|function|closingDown
DECL|function|event
DECL|function|flush
DECL|function|hasPendingEvents
DECL|function|interrupt
DECL|function|processEvents
DECL|function|registerEventNotifier
DECL|function|registerSocketNotifier
DECL|function|registerTimer
DECL|function|registeredTimers
DECL|function|remainingTime
DECL|function|sendPostedEvents
DECL|function|startingUp
DECL|function|timerDestroyed
DECL|function|timerExpired
DECL|function|unregisterEventNotifier
DECL|function|unregisterSocketNotifier
DECL|function|unregisterTimer
DECL|function|unregisterTimers
DECL|function|wakeUp
DECL|function|~QEventDispatcherWinRT
DECL|function|~QEventDispatcherWinRTPrivate
DECL|member|coreDispatcher
DECL|member|dispatcher
DECL|member|id
DECL|member|inTimerEvent
DECL|member|interrupt
DECL|member|interval
DECL|member|isFinished
DECL|member|obj
DECL|member|thread
DECL|member|timeout
DECL|member|timer
DECL|member|timerDict
DECL|member|timerFactory
DECL|member|timerType
DECL|struct|WinRTTimerInfo
