DECL|macro|QEVENTDISPATCHER_UNIX_P_H
DECL|member|Q_DECL_NOTHROW
DECL|member|Q_DECL_NOTHROW
DECL|member|Q_DECL_NOTHROW
DECL|member|notifiers
DECL|struct|Q_DECL_FINAL
DECL|variable|QEventDispatcherUNIXPrivate
