DECL|class|AgileDispatchedHandler
DECL|class|QEventDispatcherWinRTPrivate
DECL|function|AgileDispatchedHandler
DECL|function|Invoke
DECL|function|QEventDispatcherWinRT
DECL|function|QEventDispatcherWinRT
DECL|function|QEventDispatcherWinRTPrivate
DECL|function|WinRTTimerInfo
DECL|function|addTimer
DECL|function|closingDown
DECL|function|event
DECL|function|flush
DECL|function|hasPendingEvents
DECL|function|interrupt
DECL|function|processEvents
DECL|function|registerEventNotifier
DECL|function|registerSocketNotifier
DECL|function|registerTimer
DECL|function|registeredTimers
DECL|function|remainingTime
DECL|function|removeTimer
DECL|function|runOnXamlThread
DECL|function|sendPostedEvents
DECL|function|startingUp
DECL|function|unregisterEventNotifier
DECL|function|unregisterSocketNotifier
DECL|function|unregisterTimer
DECL|function|unregisterTimers
DECL|function|wakeUp
DECL|function|~QEventDispatcherWinRT
DECL|function|~QEventDispatcherWinRTPrivate
DECL|macro|INTERRUPT_HANDLE
DECL|macro|INVALID_TIMER_ID
DECL|member|delegate
DECL|member|inEvent
DECL|member|object
DECL|member|targetTime
DECL|member|timerFactory
DECL|member|timerHandleToId
DECL|member|timerIdToCancelHandle
DECL|member|timerIdToHandle
DECL|member|timerIdToObject
DECL|member|timerInfos
DECL|struct|WinRTTimerInfo
