DECL|function|QEventDispatcherUNIX
DECL|function|QEventDispatcherUNIX
DECL|function|QEventDispatcherUNIXPrivate
DECL|function|QThreadPipe
DECL|function|activateSocketNotifiers
DECL|function|activateTimers
DECL|function|check
DECL|function|flush
DECL|function|hasPendingEvents
DECL|function|init
DECL|function|initThreadPipeFD
DECL|function|interrupt
DECL|function|markPendingSocketNotifiers
DECL|function|prepare
DECL|function|processEvents
DECL|function|registerSocketNotifier
DECL|function|registerTimer
DECL|function|registeredTimers
DECL|function|remainingTime
DECL|function|setSocketNotifierPending
DECL|function|socketType
DECL|function|unregisterSocketNotifier
DECL|function|unregisterTimer
DECL|function|unregisterTimers
DECL|function|wakeUp
DECL|function|wakeUp
DECL|function|~QEventDispatcherUNIX
DECL|function|~QEventDispatcherUNIXPrivate
DECL|function|~QThreadPipe
DECL|macro|_POSIX_MONOTONIC_CLOCK
DECL|macro|_POSIX_MONOTONIC_CLOCK
