DECL|macro|CF_HDROP
DECL|macro|CF_METAFILEPICT
DECL|macro|CREATE_NO_WINDOW
DECL|macro|CoInitialize
DECL|macro|CreateFileA
DECL|macro|DEFAULT_GUI_FONT
DECL|macro|ETO_GLYPH_INDEX
DECL|macro|FTP_TRANSFER_TYPE_ASCII
DECL|macro|FTP_TRANSFER_TYPE_ASCII
DECL|macro|FTP_TRANSFER_TYPE_BINARY
DECL|macro|FTP_TRANSFER_TYPE_BINARY
DECL|macro|GMEM_MOVEABLE
DECL|macro|GPTR
DECL|macro|GetThreadLocale
DECL|macro|HWND_NOTOPMOST
DECL|macro|HWND_TOPMOST
DECL|macro|IDC_APPSTARTING
DECL|macro|IDC_ARROW
DECL|macro|IDC_CROSS
DECL|macro|IDC_HAND
DECL|macro|IDC_HELP
DECL|macro|IDC_IBEAM
DECL|macro|IDC_ICON
DECL|macro|IDC_NO
DECL|macro|IDC_SIZE
DECL|macro|IDC_SIZEALL
DECL|macro|IDC_SIZENESW
DECL|macro|IDC_SIZENS
DECL|macro|IDC_SIZENWSE
DECL|macro|IDC_SIZEWE
DECL|macro|IDC_UPARROW
DECL|macro|IDC_WAIT
DECL|macro|KF_ALTDOWN
DECL|macro|MM_ANISOTROPIC
DECL|macro|MWMO_ALERTABLE
DECL|macro|NO_ERRNO_H
DECL|macro|O_APPEND
DECL|macro|O_CREAT
DECL|macro|O_EXCL
DECL|macro|O_RDONLY
DECL|macro|O_RDWR
DECL|macro|O_TRUNC
DECL|macro|O_WRONLY
DECL|macro|PD_ALLPAGES
DECL|macro|PD_HIDEPRINTTOFILE
DECL|macro|PD_NOPAGENUMS
DECL|macro|PD_NOSELECTION
DECL|macro|PD_USEDEVMODECOPIES
DECL|macro|PS_DOT
DECL|macro|QFUNCTIONS_WCE_H
DECL|macro|SEM_FAILCRITICALERRORS
DECL|macro|SEM_NOOPENFILEERRORBOX
DECL|macro|SM_CXCURSOR
DECL|macro|SM_CYCURSOR
DECL|macro|SPI_GETWORKAREA
DECL|macro|SWP_NOREDRAW
DECL|macro|SW_NORMAL
DECL|macro|SW_RESTORE
DECL|macro|S_IFCHR
DECL|macro|S_IFDIR
DECL|macro|S_IFMT
DECL|macro|S_IFREG
DECL|macro|S_IREAD
DECL|macro|S_IWRITE
DECL|macro|SetErrorMode
DECL|macro|SetWindowOrgEx
DECL|macro|TLS_OUT_OF_INDEXES
DECL|macro|WAIT_OBJECT_0
DECL|macro|WM_ENTERIDLE
DECL|macro|WM_NCCREATE
DECL|macro|WM_NCDESTROY
DECL|macro|WM_PARENTNOTIFY
DECL|macro|WM_PRINT
DECL|macro|WM_SETCURSOR
DECL|macro|WSAGETSELECTEVENT
DECL|macro|WS_EX_CAPTIONOKBTN
DECL|macro|WS_EX_NODRAG
DECL|macro|WS_EX_NOPARENTNOTIFY
DECL|macro|WS_EX_TOOLWINDOW
DECL|macro|WS_MAXIMIZE
DECL|macro|WS_MINIMIZE
DECL|macro|WS_OVERLAPPEDWINDOW
DECL|macro|WS_POPUPWINDOW
DECL|macro|WS_THICKFRAME
DECL|macro|WS_TILED
DECL|macro|WS_TILEDWINDOW
DECL|macro|_IOFBF
DECL|macro|_IOLBF
DECL|macro|_IONBF
DECL|macro|_O_APPEND
DECL|macro|_O_CREAT
DECL|macro|_O_EXCL
DECL|macro|_O_RDONLY
DECL|macro|_O_RDWR
DECL|macro|_O_TRUNC
DECL|macro|_O_WRONLY
DECL|macro|_STAT_DEFINED
DECL|macro|_S_IFCHR
DECL|macro|_S_IFDIR
DECL|macro|_S_IFMT
DECL|macro|_S_IFREG
DECL|macro|_S_IREAD
DECL|macro|_S_IWRITE
DECL|macro|_TIME_T_DEFINED
DECL|macro|_TM_DEFINED
DECL|macro|_beginthread
DECL|macro|_beginthreadex
DECL|macro|_chmod
DECL|macro|_control87
DECL|macro|_endthreadex
DECL|macro|_fdopen
DECL|macro|_getdrive
DECL|macro|_getpid
DECL|macro|_putenv_s
DECL|macro|_remove
DECL|macro|_rename
DECL|macro|_waccess
DECL|macro|_wchmod
DECL|macro|_wopen
DECL|macro|bool
DECL|macro|bsearch
DECL|macro|calloc
DECL|macro|false
DECL|macro|fdopen
DECL|macro|getenv_s
DECL|macro|rewind
DECL|macro|time_tToFt
DECL|macro|tmpfile
DECL|macro|true
DECL|member|st_atime
DECL|member|st_ctime
DECL|member|st_mode
DECL|member|st_mtime
DECL|member|st_nlink
DECL|member|st_size
DECL|member|tm_hour
DECL|member|tm_isdst
DECL|member|tm_mday
DECL|member|tm_min
DECL|member|tm_mon
DECL|member|tm_sec
DECL|member|tm_wday
DECL|member|tm_yday
DECL|member|tm_year
DECL|struct|stat
DECL|struct|tm
DECL|typedef|HDROP
DECL|typedef|OLE_COLOR
DECL|typedef|UWORD
DECL|typedef|mode_t
DECL|typedef|time_t
