DECL|function|isascii
DECL|macro|NSIG
DECL|macro|QFUNCTIONS_VXWORKS_H
DECL|macro|RTLD_LOCAL
DECL|macro|m_act
DECL|macro|m_data
DECL|macro|m_ext
DECL|macro|m_flags
DECL|macro|m_hdr
DECL|macro|m_len
DECL|macro|m_next
DECL|macro|m_nextpkt
DECL|macro|m_pkthdr
DECL|macro|m_type
DECL|macro|mbuf
DECL|member|gr_gid
DECL|member|gr_mem
DECL|member|gr_name
DECL|member|gr_passwd
DECL|member|pw_dir
DECL|member|pw_gecos
DECL|member|pw_gid
DECL|member|pw_name
DECL|member|pw_passwd
DECL|member|pw_shell
DECL|member|pw_uid
DECL|struct|group
DECL|struct|passwd
