DECL|function|Variable
DECL|function|Variable
DECL|macro|QFUNCTIONS_FAKE_ENV_P_H
DECL|member|Q_DECL_NOTHROW
DECL|member|name
DECL|member|name
DECL|member|name
DECL|member|value
DECL|struct|NameEquals
DECL|struct|Variable
DECL|typedef|result_type
