DECL|function|qAcos
DECL|function|qAsin
DECL|function|qAtan
DECL|function|qAtan2
DECL|function|qCeil
DECL|function|qCos
DECL|function|qExp
DECL|function|qFabs
DECL|function|qFastCos
DECL|function|qFastSin
DECL|function|qFloor
DECL|function|qLn
DECL|function|qPow
DECL|function|qSin
DECL|function|qSqrt
DECL|function|qTan
DECL|macro|M_1_PI
DECL|macro|M_2_PI
DECL|macro|M_2_SQRTPI
DECL|macro|M_E
DECL|macro|M_LN10
DECL|macro|M_LN2
DECL|macro|M_LOG10E
DECL|macro|M_LOG2E
DECL|macro|M_PI
DECL|macro|M_PI_2
DECL|macro|M_PI_4
DECL|macro|M_SQRT1_2
DECL|macro|M_SQRT2
DECL|macro|QMATH_H
DECL|macro|QT_SINE_TABLE_SIZE
