DECL|class|QCustomTypeInfo
DECL|class|SizeOf
DECL|class|TypeConstructor
DECL|class|TypeDestructor
DECL|function|Construct
DECL|function|Construct
DECL|function|Destruct
DECL|function|Destruct
DECL|function|Size
DECL|function|Size
DECL|function|SizeOf
DECL|function|TypeConstructor
DECL|function|TypeDestructor
DECL|function|construct
DECL|function|create
DECL|function|customTypeConstructor
DECL|function|customTypeDestructor
DECL|function|customTypeSizeOf
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|destroy
DECL|function|destruct
DECL|function|isRegistered
DECL|function|load
DECL|function|qMetaTypeCustomType_unlocked
DECL|function|qMetaTypeStaticType
DECL|function|registerStreamOperators
DECL|function|registerStreamOperators
DECL|function|registerType
DECL|function|registerType
DECL|function|registerTypedef
DECL|function|save
DECL|function|sizeOf
DECL|function|type
DECL|function|typeName
DECL|function|unregisterType
DECL|macro|NS
DECL|macro|QT_ADD_STATIC_METATYPE
DECL|macro|QT_ADD_STATIC_METATYPE_ALIASES_ITER
DECL|macro|QT_ADD_STATIC_METATYPE_HACKS_ITER
DECL|macro|QT_METATYPE_TYPEID_TYPENAME_CONVERTER
DECL|macro|QT_METATYPE_TYPEID_TYPENAME_CONVERTER
DECL|macro|QT_NO_GEOM_VARIANT
DECL|member|IsAccepted
DECL|member|IsAvailable
DECL|member|IsAvailable
DECL|member|IsAvailable
DECL|member|IsAvailable
DECL|member|IsAvailable
DECL|member|IsAvailable
DECL|member|IsAvailable
DECL|member|IsAvailable
DECL|member|IsAvailable
DECL|member|IsAvailable
DECL|member|IsAvailable
DECL|member|IsAvailable
DECL|member|IsAvailable
DECL|member|IsAvailable
DECL|member|IsAvailable
DECL|member|IsAvailable
DECL|member|IsAvailable
DECL|member|alias
DECL|member|iface
DECL|member|m_type
DECL|member|m_type
DECL|member|m_type
DECL|member|m_where
DECL|member|type
DECL|member|typeName
DECL|member|typeName
DECL|member|typeNameLength
DECL|struct|Acceptor
DECL|struct|ConstructorImpl
DECL|struct|ConstructorImpl
DECL|struct|DefinedTypesFilter
DECL|struct|DestructorImpl
DECL|struct|DestructorImpl
DECL|struct|SizeOfImpl
DECL|struct|SizeOfImpl
DECL|struct|TypeDefiniton
DECL|struct|TypeDefiniton
DECL|struct|TypeDefiniton
DECL|struct|TypeDefiniton
DECL|struct|TypeDefiniton
DECL|struct|TypeDefiniton
DECL|struct|TypeDefiniton
DECL|struct|TypeDefiniton
DECL|struct|TypeDefiniton
DECL|struct|TypeDefiniton
DECL|struct|TypeDefiniton
DECL|struct|TypeDefiniton
DECL|struct|TypeDefiniton
DECL|struct|TypeDefiniton
DECL|struct|TypeDefiniton
DECL|struct|TypeDefiniton
DECL|struct|TypeDefiniton
DECL|union|CheckThatItIsPod
DECL|variable|qMetaTypeGuiHelper
DECL|variable|qMetaTypeWidgetsHelper
DECL|variable|types
