DECL|macro|QMETAOBJECTBUILDER_H
DECL|variable|QMetaEnumBuilder
DECL|variable|QMetaEnumBuilderPrivate
DECL|variable|QMetaMethodBuilder
DECL|variable|QMetaMethodBuilderPrivate
DECL|variable|QMetaObjectBuilderPrivate
DECL|variable|QMetaPropertyBuilder
DECL|variable|QMetaPropertyBuilderPrivate
