DECL|enumerator|Defined
DECL|enumerator|Defined
DECL|function|QT_MODULE
DECL|function|qMetaTypeConstructHelper
DECL|function|qMetaTypeDeleteHelper
DECL|function|qMetaTypeId
DECL|function|qMetaTypeLoadHelper
DECL|function|qMetaTypeSaveHelper
DECL|function|qRegisterMetaType
DECL|function|qRegisterMetaType
DECL|function|qRegisterMetaTypeStreamOperators
DECL|function|qRegisterMetaTypeStreamOperators
DECL|function|qt_metatype_id
DECL|macro|QMETATYPE_H
DECL|macro|Q_DECLARE_BUILTIN_METATYPE
DECL|macro|Q_DECLARE_METATYPE
DECL|struct|QMetaTypeId
DECL|struct|QMetaTypeId2
DECL|variable|QBitArray
DECL|variable|QBitmap
DECL|variable|QBrush
DECL|variable|QByteArray
DECL|variable|QChar
DECL|variable|QColor
DECL|variable|QColorGroup
DECL|variable|QCursor
DECL|variable|QDate
DECL|variable|QDateTime
DECL|variable|QEasingCurve
DECL|variable|QFont
DECL|variable|QIcon
DECL|variable|QImage
DECL|variable|QKeySequence
DECL|variable|QLine
DECL|variable|QLineF
DECL|variable|QLocale
DECL|variable|QMatrix
DECL|variable|QMatrix4x4
DECL|variable|QObject
DECL|variable|QPalette
DECL|variable|QPen
DECL|variable|QPixmap
DECL|variable|QPoint
DECL|variable|QPointF
DECL|variable|QPolygon
DECL|variable|QQuaternion
DECL|variable|QRect
DECL|variable|QRectF
DECL|variable|QRegExp
DECL|variable|QRegion
DECL|variable|QSize
DECL|variable|QSizeF
DECL|variable|QSizePolicy
DECL|variable|QString
DECL|variable|QStringList
DECL|variable|QTextFormat
DECL|variable|QTextLength
DECL|variable|QTime
DECL|variable|QTransform
DECL|variable|QUrl
DECL|variable|QVariant
DECL|variable|QVector2D
DECL|variable|QVector3D
DECL|variable|QVector4D
DECL|variable|QWidget
