DECL|class|Flags
DECL|class|MetaObject
DECL|class|QCustomTypeInfo
DECL|class|QMetaTypeConversionRegistry
DECL|class|SizeOf
DECL|class|TypeConstructor
DECL|class|TypeCreator
DECL|class|TypeDestroyer
DECL|class|TypeDestructor
DECL|class|TypeInfo
DECL|function|Construct
DECL|function|Construct
DECL|function|Create
DECL|function|Create
DECL|function|Destroy
DECL|function|Destroy
DECL|function|Destruct
DECL|function|Destruct
DECL|function|Flags
DECL|function|Flags
DECL|function|Flags
DECL|function|MetaObject
DECL|function|QCustomTypeInfo
DECL|function|QMetaType
DECL|function|QMetaType
DECL|function|Size
DECL|function|Size
DECL|function|SizeOf
DECL|function|TypeConstructor
DECL|function|TypeCreator
DECL|function|TypeDestroyer
DECL|function|TypeDestructor
DECL|function|TypeInfo
DECL|function|TypeInfoImpl
DECL|function|TypeInfoImpl
DECL|function|construct
DECL|function|constructExtended
DECL|function|contains
DECL|function|convert
DECL|function|create
DECL|function|createExtended
DECL|function|ctor
DECL|function|customMetaObject
DECL|function|customTypeConstructor
DECL|function|customTypeDestroyer
DECL|function|customTypeDestructor
DECL|function|customTypeFlags
DECL|function|customTypeInfo
DECL|function|customTypeSizeOf
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|delegate
DECL|function|destroy
DECL|function|destroyExtended
DECL|function|destruct
DECL|function|destructExtended
DECL|function|dtor
DECL|function|flagsExtended
DECL|function|function
DECL|function|hasRegisteredConverterFunction
DECL|function|insertIfNotContains
DECL|function|isRegistered
DECL|function|load
DECL|function|metaObjectExtended
DECL|function|metaObjectForQWidget
DECL|function|metaObjectForType
DECL|function|operator =
DECL|function|qMetaTypeCustomType_unlocked
DECL|function|qMetaTypeStaticType
DECL|function|qMetaTypeTypeImpl
DECL|function|qMetaTypeTypeInternal
DECL|function|registerConverterFunction
DECL|function|registerStreamOperators
DECL|function|registerStreamOperators
DECL|function|registerType
DECL|function|registerType
DECL|function|registerTypedef
DECL|function|remove
DECL|function|save
DECL|function|sizeExtended
DECL|function|sizeOf
DECL|function|type
DECL|function|typeFlags
DECL|function|typeInfo
DECL|function|typeName
DECL|function|unregisterConverterFunction
DECL|function|~QMetaTypeConversionRegistry
DECL|macro|NS
DECL|macro|QT_ADD_STATIC_METATYPE
DECL|macro|QT_ADD_STATIC_METATYPE_ALIASES_ITER
DECL|macro|QT_ADD_STATIC_METATYPE_HACKS_ITER
DECL|macro|QT_METATYPE_TYPEID_TYPENAME_CONVERTER
DECL|macro|QT_METATYPE_TYPEID_TYPENAME_CONVERTER
DECL|member|IsAccepted
DECL|member|alias
DECL|member|iface
DECL|member|info
DECL|member|lock
DECL|member|m_type
DECL|member|m_type
DECL|member|m_type
DECL|member|m_type
DECL|member|m_type
DECL|member|m_type
DECL|member|m_type
DECL|member|m_type
DECL|member|m_where
DECL|member|map
DECL|member|type
DECL|member|typeName
DECL|member|typeName
DECL|member|typeNameLength
DECL|namespace|QtPrivate
DECL|struct|Acceptor
DECL|struct|ConstructorImpl
DECL|struct|ConstructorImpl
DECL|struct|CreatorImpl
DECL|struct|CreatorImpl
DECL|struct|DefinedTypesFilter
DECL|struct|DestroyerImpl
DECL|struct|DestroyerImpl
DECL|struct|DestructorImpl
DECL|struct|DestructorImpl
DECL|struct|FlagsImpl
DECL|struct|FlagsImpl
DECL|struct|SizeOfImpl
DECL|struct|SizeOfImpl
DECL|struct|TypeInfoImpl
DECL|struct|TypeInfoImpl
DECL|typedef|Key
DECL|union|CheckThatItIsPod
DECL|variable|constructor
DECL|variable|creator
DECL|variable|deleter
DECL|variable|destructor
DECL|variable|flags
DECL|variable|qMetaObjectWidgetsHelper
DECL|variable|qMetaTypeGuiHelper
DECL|variable|qMetaTypeWidgetsHelper
DECL|variable|size
DECL|variable|types
