DECL|class|QCustomTypeInfo
DECL|function|QCustomTypeInfo
DECL|function|construct
DECL|function|create
DECL|function|destroy
DECL|function|destruct
DECL|function|isRegistered
DECL|function|load
DECL|function|qMetaTypeCustomType_unlocked
DECL|function|qMetaTypeStaticType
DECL|function|registerStreamOperators
DECL|function|registerStreamOperators
DECL|function|registerType
DECL|function|registerType
DECL|function|registerTypedef
DECL|function|save
DECL|function|sizeOf
DECL|function|type
DECL|function|typeName
DECL|function|unregisterType
DECL|macro|NS
DECL|macro|QT_ADD_STATIC_METATYPE
DECL|macro|QT_ADD_STATIC_METATYPE_ALIASES_ITER
DECL|macro|QT_ADD_STATIC_METATYPE_HACKS_ITER
DECL|macro|QT_METATYPE_TYPEID_TYPENAME_CONVERTER
DECL|macro|QT_METATYPE_TYPEID_TYPENAME_CONVERTER
DECL|macro|QT_NO_GEOM_VARIANT
DECL|member|alias
DECL|member|constructor
DECL|member|constructor
DECL|member|creator
DECL|member|creator
DECL|member|deleter
DECL|member|deleter
DECL|member|destructor
DECL|member|destructor
DECL|member|loadOp
DECL|member|loadOp
DECL|member|saveOp
DECL|member|saveOp
DECL|member|size
DECL|member|size
DECL|member|type
DECL|member|typeName
DECL|member|typeName
DECL|member|typeNameLength
DECL|struct|QMetaTypeGuiHelper
DECL|variable|qMetaTypeGuiHelper
DECL|variable|qMetaTypeWidgetsHelper
DECL|variable|types
