DECL|function|connect
DECL|function|qFindChild
DECL|function|qFindChildren
DECL|function|qFindChildren
DECL|function|qobject_cast
DECL|function|qobject_cast
DECL|function|qobject_interface_iid
DECL|macro|QOBJECT_H
DECL|macro|Q_DECLARE_INTERFACE
DECL|typedef|QObjectList
DECL|variable|QChildEvent
DECL|variable|QObject
DECL|variable|QObjectPrivate
DECL|variable|QObjectUserData
DECL|variable|QRegExp
DECL|variable|QThread
DECL|variable|QTimerEvent
DECL|variable|QVariant
DECL|variable|QWidget
