DECL|enumerator|QObjectPrivateVersion
DECL|function|connectNotify
DECL|function|createProperty
DECL|function|disconnectNotify
DECL|function|isSignalConnected
DECL|function|metaCall
DECL|function|objectDestroyed
DECL|function|resetCurrentSender
DECL|function|setCurrentSender
DECL|macro|QOBJECT_P_H
DECL|member|ownedByQml1
DECL|member|signal_begin_callback
DECL|member|signal_end_callback
DECL|member|slot_begin_callback
DECL|member|slot_end_callback
DECL|member|unused
DECL|struct|QAbstractDeclarativeData
DECL|struct|QDynamicMetaObjectData
DECL|struct|QMetaObject
DECL|struct|QSignalSpyCallbackSet
DECL|typedef|BeginCallback
DECL|typedef|EndCallback
DECL|variable|Func1
DECL|variable|Func1
DECL|variable|QDynamicMetaObjectData
DECL|variable|QObjectConnectionListVector
DECL|variable|QSemaphore
DECL|variable|QThreadData
DECL|variable|QVariant
