DECL|class|QPpsMaxSize
DECL|function|QPpsMaxSize
DECL|function|QPpsObject
DECL|function|QPpsObjectPrivate
DECL|function|close
DECL|function|decode
DECL|function|decode
DECL|function|decodeArray
DECL|function|decodeBool
DECL|function|decodeData
DECL|function|decodeNestedData
DECL|function|decodeNumber
DECL|function|decodeObject
DECL|function|decodeString
DECL|function|decodeWithFlags
DECL|function|decodeWithFlags
DECL|function|encode
DECL|function|encode
DECL|function|encodeArray
DECL|function|encodeData
DECL|function|encodeMessage
DECL|function|encodeMessage
DECL|function|encodeObject
DECL|function|error
DECL|function|errorString
DECL|function|isBlocking
DECL|function|isOpen
DECL|function|isReadyReadEnabled
DECL|function|open
DECL|function|read
DECL|function|readFlags
DECL|function|remove
DECL|function|safeAssign
DECL|function|sendMessage
DECL|function|sendMessage
DECL|function|sendMessage
DECL|function|sendMessage
DECL|function|setBlocking
DECL|function|setReadyReadEnabled
DECL|function|variantFromPpsAttribute
DECL|function|variantMapFromPpsAttributeMap
DECL|function|write
DECL|function|writeMessage
DECL|function|writeMessage
DECL|function|~QPpsObject
DECL|member|value
