DECL|function|QSharedMemory
DECL|function|QSharedMemory
DECL|function|attach
DECL|function|constData
DECL|function|create
DECL|function|data
DECL|function|data
DECL|function|detach
DECL|function|error
DECL|function|errorString
DECL|function|initKey
DECL|function|isAttached
DECL|function|key
DECL|function|lock
DECL|function|makePlatformSafeKey
DECL|function|nativeKey
DECL|function|setKey
DECL|function|setNativeKey
DECL|function|size
DECL|function|unlock
DECL|function|~QSharedMemory
