DECL|class|QSingleShotTimer
DECL|function|QSingleShotTimer
DECL|function|QSingleShotTimer
DECL|function|QTimer
DECL|function|remainingTime
DECL|function|setInterval
DECL|function|singleShot
DECL|function|singleShot
DECL|function|singleShotImpl
DECL|function|start
DECL|function|start
DECL|function|stop
DECL|function|timerEvent
DECL|function|timerEvent
DECL|function|~QSingleShotTimer
DECL|function|~QTimer
DECL|member|Q_DECL_OVERRIDE
DECL|member|hasValidReceiver
DECL|member|receiver
DECL|member|slotObj
DECL|member|timerId
DECL|variable|INV_TIMER
