DECL|macro|QTIMERINFO_UNIX_P_H
DECL|member|activateRef
DECL|member|count
DECL|member|cumulativeError
DECL|member|expected
DECL|member|id
DECL|member|interval
DECL|member|obj
DECL|member|timeout
DECL|member|timerType
DECL|struct|QTimerInfo
