DECL|function|QTimerInfoList
DECL|function|activateTimers
DECL|function|qAbs
DECL|function|registerTimer
DECL|function|registeredTimers
DECL|function|repairTimersIfNeeded
DECL|function|repairTimersIfNeeded
DECL|function|roundToMillisecond
DECL|function|timeChanged
DECL|function|timerInsert
DECL|function|timerRepair
DECL|function|timerWait
DECL|function|unregisterTimer
DECL|function|unregisterTimers
DECL|function|updateCurrentTime
DECL|variable|qt_disable_lowpriority_timers
