DECL|enumerator|Q_AND
DECL|enumerator|Q_BETWEEN
DECL|enumerator|Q_EQ
DECL|enumerator|Q_GEQ
DECL|enumerator|Q_GT
DECL|enumerator|Q_LEAD_1000
DECL|enumerator|Q_LEQ
DECL|enumerator|Q_LT
DECL|enumerator|Q_MOD_10
DECL|enumerator|Q_MOD_100
DECL|enumerator|Q_NEQ
DECL|enumerator|Q_NEWRULE
DECL|enumerator|Q_NOT
DECL|enumerator|Q_NOT_BETWEEN
DECL|enumerator|Q_OP_MASK
DECL|enumerator|Q_OR
DECL|macro|QTRANSLATOR_P_H
