DECL|function|QVariant
DECL|function|QVariant
DECL|function|QVariant
DECL|function|isDetached
DECL|function|isValid
DECL|function|operator
DECL|function|operator
DECL|function|qVariantCanConvert
DECL|function|qVariantFromValue
DECL|function|qVariantFromValue
DECL|function|qVariantSetValue
DECL|function|qVariantValue
DECL|function|qvariant_cast
DECL|function|setValue
DECL|macro|QVARIANT_H
DECL|variable|QDataStream
DECL|variable|QDate
DECL|variable|QDateTime
DECL|variable|QEasingCurve
DECL|variable|QLine
DECL|variable|QLineF
DECL|variable|QLocale
DECL|variable|QMatrix
DECL|variable|QPoint
DECL|variable|QPointF
DECL|variable|QRect
DECL|variable|QRectF
DECL|variable|QRegExp
DECL|variable|QSize
DECL|variable|QSizeF
DECL|variable|QStringList
DECL|variable|QTextFormat
DECL|variable|QTextLength
DECL|variable|QTime
DECL|variable|QTransform
DECL|variable|QUrl
DECL|variable|QVariant
DECL|variable|QVariantComparisonHelper
DECL|variable|operator
