DECL|class|QWinEventNotifierPrivate
DECL|function|QWinEventNotifier
DECL|function|QWinEventNotifier
DECL|function|QWinEventNotifierPrivate
DECL|function|QWinEventNotifierPrivate
DECL|function|event
DECL|function|handle
DECL|function|isEnabled
DECL|function|setEnabled
DECL|function|setHandle
DECL|function|~QWinEventNotifier
DECL|member|enabled
DECL|member|handleToEvent
