DECL|class|QAutoClose
DECL|class|QS60DocumentHandler
DECL|function|Forget
DECL|function|HandleServerAppExit
DECL|function|QAutoClose
DECL|function|QS60DocumentHandler
DECL|function|documentHandler
DECL|function|handleMailtoScheme
DECL|function|handleMailtoSchemeLX
DECL|function|handleOtherSchemes
DECL|function|handleOtherSchemesL
DECL|function|handleUrl
DECL|function|handleUrlL
DECL|function|launchWebBrowser
DECL|function|launchWebBrowser
DECL|function|openDocument
DECL|function|openDocument
DECL|function|openDocumentL
DECL|function|~QAutoClose
DECL|function|~QS60DocumentHandler
DECL|member|docHandler
DECL|member|mPtr
DECL|variable|KUidBrowser
DECL|variable|KUidMsgTypeSMTP
