DECL|function|QGridLayoutEngine
DECL|function|QGridLayoutItem
DECL|function|add
DECL|function|addItem
DECL|function|box
DECL|function|calculateGeometries
DECL|function|cellRect
DECL|function|columnCount
DECL|function|columnSpan
DECL|function|combine
DECL|function|compare
DECL|function|constraintOrientation
DECL|function|controlTypes
DECL|function|controlTypes
DECL|function|distributeMultiCells
DECL|function|dump
DECL|function|dump
DECL|function|dump
DECL|function|dump
DECL|function|dump
DECL|function|effectiveAlignment
DECL|function|effectiveFirstRow
DECL|function|effectiveLastRow
DECL|function|effectiveMaxSize
DECL|function|ensureColumnAndRowData
DECL|function|ensureDynamicConstraint
DECL|function|ensureEffectiveFirstAndLastRows
DECL|function|ensureGeometries
DECL|function|fillRowData
DECL|function|firstColumn
DECL|function|firstRow
DECL|function|fixedDescent
DECL|function|geometryWithin
DECL|function|growthFactorBelowPreferredSize
DECL|function|hasDynamicConstraint
DECL|function|insertItem
DECL|function|insertOrRemoveItems
DECL|function|insertOrRemoveRows
DECL|function|insertOrRemoveRows
DECL|function|insertOrRemoveRows
DECL|function|invalidate
DECL|function|itemAt
DECL|function|itemAt
DECL|function|itemCount
DECL|function|lastColumn
DECL|function|lastRow
DECL|function|maybeExpandGrid
DECL|function|normalize
DECL|function|operator ==
DECL|function|qround
DECL|function|regenerateGrid
DECL|function|removeItem
DECL|function|reset
DECL|function|rowAlignment
DECL|function|rowCount
DECL|function|rowSizeHint
DECL|function|rowSpacing
DECL|function|rowSpan
DECL|function|rowStretchFactor
DECL|function|setFirstRow
DECL|function|setGeometries
DECL|function|setItemAt
DECL|function|setRowAlignment
DECL|function|setRowSizeHint
DECL|function|setRowSpacing
DECL|function|setRowSpan
DECL|function|setRowStretchFactor
DECL|function|setSpacing
DECL|function|setStretchFactor
DECL|function|setVisualDirection
DECL|function|sizeHint
DECL|function|spacing
DECL|function|stealBox
DECL|function|stretchFactor
DECL|function|totalBox
DECL|function|transpose
DECL|function|transpose
DECL|function|visualDirection
DECL|function|visualRect
