DECL|function|QBalloonTip
DECL|function|QSystemTrayIcon
DECL|function|QSystemTrayIcon
DECL|function|balloon
DECL|function|contextMenu
DECL|function|event
DECL|function|geometry
DECL|function|hideBalloon
DECL|function|icon
DECL|function|isBalloonVisible
DECL|function|isSystemTrayAvailable
DECL|function|isVisible
DECL|function|mousePressEvent
DECL|function|paintEvent
DECL|function|qtsystray_sendActivated
DECL|function|resizeEvent
DECL|function|setContextMenu
DECL|function|setIcon
DECL|function|setToolTip
DECL|function|setVisible
DECL|function|showBalloon
DECL|function|showMessage
DECL|function|supportsMessages
DECL|function|timerEvent
DECL|function|toolTip
DECL|function|~QBalloonTip
DECL|function|~QSystemTrayIcon
DECL|variable|theSolitaryBalloonTip
