DECL|class|QSystemTrayIconSys
DECL|function|QSystemTrayIconSys
DECL|function|createIcon
DECL|function|findTrayGeometry
DECL|function|geometry_sys
DECL|function|install_sys
DECL|function|isSystemTrayAvailable_sys
DECL|function|remove_sys
DECL|function|setIconContents
DECL|function|showMessage_sys
DECL|function|supportsMessages_sys
DECL|function|trayMessage
DECL|function|updateIcon_sys
DECL|function|updateMenu_sys
DECL|function|updateToolTip_sys
DECL|function|winEvent
DECL|function|~QSystemTrayIconSys
DECL|macro|MYWM_NOTIFYICON
DECL|macro|_WIN32_IE
DECL|member|cbSize
DECL|member|globalPos
DECL|member|guidItem
DECL|member|hIcon
DECL|member|hWnd
DECL|member|ignoreNextMouseRelease
DECL|member|maxTipLength
DECL|member|notifyIconSize
DECL|member|q
DECL|member|uID
DECL|struct|Q_NOTIFYICONIDENTIFIER
DECL|variable|q_uNOTIFYICONID
