DECL|class|Bar
DECL|class|MyClass
DECL|class|tst_QHash
DECL|function|Bar
DECL|function|Foo
DECL|function|Foo
DECL|function|MyClass
DECL|function|MyClass
DECL|function|MyClass
DECL|function|clear
DECL|function|compare
DECL|function|compare2
DECL|function|constFind
DECL|function|const_shared_null
DECL|function|contains
DECL|function|count
DECL|function|dont_need_default_constructor
DECL|function|empty
DECL|function|erase
DECL|function|find
DECL|function|insert1
DECL|function|iterators
DECL|function|key
DECL|function|keys_values_uniqueKeys
DECL|function|noNeedlessRehashes
DECL|function|operator =
DECL|function|operator_eq
DECL|function|qhash
DECL|function|qmultihash_specific
DECL|function|rehash_isnt_quadratic
DECL|function|sorted
DECL|function|swap
DECL|function|take
DECL|function|tst_QHash
DECL|function|~Foo
DECL|function|~MyClass
DECL|function|~tst_QHash
DECL|member|c
DECL|member|count
DECL|member|count
DECL|member|count
DECL|member|count
DECL|member|data
DECL|member|j
DECL|member|str
DECL|struct|Foo
DECL|typedef|MyMap
