DECL|class|QtActivityDelegate
DECL|field|APPLICATION_PARAMETERS_KEY
DECL|field|BUNDLED_LIBRARIES_KEY
DECL|field|ENVIRONMENT_VARIABLES_KEY
DECL|field|ImhDialableCharactersOnly
DECL|field|ImhDigitsOnly
DECL|field|ImhEmailCharactersOnly
DECL|field|ImhFormattedNumbersOnly
DECL|field|ImhHiddenText
DECL|field|ImhLowercaseOnly
DECL|field|ImhMultiLine
DECL|field|ImhNoAutoUppercase
DECL|field|ImhNoPredictiveText
DECL|field|ImhPreferLowercase
DECL|field|ImhPreferNumbers
DECL|field|ImhPreferUppercase
DECL|field|ImhUppercaseOnly
DECL|field|ImhUrlCharactersOnly
DECL|field|MAIN_LIBRARY_KEY
DECL|field|NATIVE_LIBRARIES_KEY
DECL|field|NECESSITAS_API_LEVEL_KEY
DECL|field|STATIC_INIT_CLASSES_KEY
DECL|field|m_activity
DECL|field|m_applicationParameters
DECL|field|m_contextMenuVisible
DECL|field|m_currentOrientation
DECL|field|m_debuggerProcess
DECL|field|m_editText
DECL|field|m_environmentVariables
DECL|field|m_fullScreen
DECL|field|m_imm
DECL|field|m_keyboardIsHiding
DECL|field|m_keyboardIsVisible
DECL|field|m_lastChar
DECL|field|m_layout
DECL|field|m_mainLib
DECL|field|m_metaState
DECL|field|m_opionsMenuIsVisible
DECL|field|m_quitApp
DECL|field|m_started
DECL|field|m_super_dispatchKeyEvent
DECL|field|m_super_onConfigurationChanged
DECL|field|m_super_onKeyDown
DECL|field|m_super_onKeyUp
DECL|field|m_super_onRestoreInstanceState
DECL|field|m_super_onRetainNonConfigurationInstance
DECL|field|m_super_onSaveInstanceState
DECL|field|m_surface
DECL|method|closeContextMenu
DECL|method|dispatchKeyEvent
DECL|method|getAppIconSize
DECL|method|getQtLayout
DECL|method|getQtSurface
DECL|method|hideSoftwareKeyboard
DECL|method|isSoftwareKeyboardVisible
DECL|method|loadApplication
DECL|method|onConfigurationChanged
DECL|method|onContextItemSelected
DECL|method|onContextMenuClosed
DECL|method|onCreate
DECL|method|onCreateContextMenu
DECL|method|onCreateOptionsMenu
DECL|method|onDestroy
DECL|method|onKeyDown
DECL|method|onKeyUp
DECL|method|onOptionsItemSelected
DECL|method|onOptionsMenuClosed
DECL|method|onPrepareOptionsMenu
DECL|method|onRestoreInstanceState
DECL|method|onResume
DECL|method|onRetainNonConfigurationInstance
DECL|method|onSaveInstanceState
DECL|method|onTerminate
DECL|method|openContextMenu
DECL|method|redrawWindow
DECL|method|resetOptionsMenu
DECL|method|resetSoftwareKeyboard
DECL|method|setFullScreen
DECL|method|showSoftwareKeyboard
DECL|method|startApplication
DECL|method|updateSelection
DECL|package|org.qtproject.qt5.android
