DECL|class|ButtonStruct
DECL|class|QtMessageDialogHelper
DECL|class|QtNativeDialogHelper
DECL|field|m_activity
DECL|field|m_buttonsList
DECL|field|m_detailedText
DECL|field|m_dialog
DECL|field|m_dialog
DECL|field|m_handler
DECL|field|m_icon
DECL|field|m_id
DECL|field|m_informativeText
DECL|field|m_text
DECL|field|m_text
DECL|field|m_theme
DECL|field|m_title
DECL|method|ButtonStruct
DECL|method|QtMessageDialogHelper
DECL|method|addButton
DECL|method|dialogResult
DECL|method|getIconDrawable
DECL|method|getStyledDrawable
DECL|method|handler
DECL|method|hide
DECL|method|onClick
DECL|method|reset
DECL|method|setDetailedText
DECL|method|setIcon
DECL|method|setInformativeText
DECL|method|setText
DECL|method|setTextAppearance
DECL|method|setTile
DECL|method|show
DECL|package|org.qtproject.qt5.android
