DECL|class|QtNative
DECL|field|QtTAG
DECL|field|m_activity
DECL|field|m_activityDelegate
DECL|field|m_classLoader
DECL|field|m_clipboardManager
DECL|field|m_displayMetricsDesktopHeightPixels
DECL|field|m_displayMetricsDesktopWidthPixels
DECL|field|m_displayMetricsScaledDensity
DECL|field|m_displayMetricsScreenHeightPixels
DECL|field|m_displayMetricsScreenWidthPixels
DECL|field|m_displayMetricsXDpi
DECL|field|m_displayMetricsYDpi
DECL|field|m_lostActions
DECL|field|m_mainActivityMutex
DECL|field|m_moveThreshold
DECL|field|m_oldx
DECL|field|m_oldy
DECL|field|m_started
DECL|method|activity
DECL|method|activityDelegate
DECL|method|classLoader
DECL|method|clearLostActions
DECL|method|closeContextMenu
DECL|method|createSurface
DECL|method|destroySurface
DECL|method|getAction
DECL|method|getClipboardText
DECL|method|getLostActions
DECL|method|getSSLCertificates
DECL|method|handleOrientationChanged
DECL|method|hasClipboardText
DECL|method|hideSoftwareKeyboard
DECL|method|insertNativeView
DECL|method|keyDown
DECL|method|keyUp
DECL|method|keyboardVisibilityChanged
DECL|method|loadBundledLibraries
DECL|method|loadQtLibraries
DECL|method|longPress
DECL|method|mouseDown
DECL|method|mouseMove
DECL|method|mouseUp
DECL|method|onActivityResult
DECL|method|onContextItemSelected
DECL|method|onContextMenuClosed
DECL|method|onCreateContextMenu
DECL|method|onOptionsItemSelected
DECL|method|onOptionsMenuClosed
DECL|method|onPrepareOptionsMenu
DECL|method|openContextMenu
DECL|method|openOptionsMenu
DECL|method|openURL
DECL|method|quitApp
DECL|method|quitQtAndroidPlugin
DECL|method|registerClipboardManager
DECL|method|resetOptionsMenu
DECL|method|resetSoftwareKeyboard
DECL|method|runAction
DECL|method|sendTouchEvent
DECL|method|sendTrackballEvent
DECL|method|setActivity
DECL|method|setApplicationDisplayMetrics
DECL|method|setClassLoader
DECL|method|setClipboardText
DECL|method|setDisplayMetrics
DECL|method|setFullScreen
DECL|method|setSurface
DECL|method|setSurfaceGeometry
DECL|method|showSoftwareKeyboard
DECL|method|startApplication
DECL|method|startQtAndroidPlugin
DECL|method|startQtApplication
DECL|method|terminateQt
DECL|method|touchAdd
DECL|method|touchBegin
DECL|method|touchEnd
DECL|method|updateApplicationState
DECL|method|updateSelection
DECL|method|updateWindow
DECL|package|org.qtproject.qt5.android
