DECL|class|QtSurface
DECL|field|m_accessibilityDelegate
DECL|field|m_gestureDetector
DECL|method|QtSurface
DECL|method|onTouchEvent
DECL|method|onTrackballEvent
DECL|method|surfaceChanged
DECL|method|surfaceCreated
DECL|method|surfaceDestroyed
DECL|package|org.qtproject.qt5.android
