DECL|class|QGtk2Dialog
DECL|function|QGtk2ColorDialogHelper
DECL|function|QGtk2Dialog
DECL|function|applyOptions
DECL|function|currentColor
DECL|function|exec
DECL|function|exec
DECL|function|gtkDialog
DECL|function|hide
DECL|function|hide
DECL|function|onAccepted
DECL|function|onColorChanged
DECL|function|onResponse
DECL|function|setCurrentColor
DECL|function|show
DECL|function|show
DECL|function|~QGtk2ColorDialogHelper
DECL|function|~QGtk2Dialog
DECL|macro|signals
DECL|member|gtkWidget
