DECL|class|QAccessibleTabButton
DECL|function|QAccessibleAbstractScrollArea
DECL|function|QAccessibleComboBox
DECL|function|QAccessibleScrollArea
DECL|function|QAccessibleTabBar
DECL|function|QAccessibleTabButton
DECL|function|abstractScrollArea
DECL|function|accessibleChildren
DECL|function|actionNames
DECL|function|child
DECL|function|child
DECL|function|child
DECL|function|childAt
DECL|function|childAt
DECL|function|childCount
DECL|function|childCount
DECL|function|childCount
DECL|function|comboBox
DECL|function|doAction
DECL|function|elementType
DECL|function|index
DECL|function|indexOfChild
DECL|function|indexOfChild
DECL|function|indexOfChild
DECL|function|isLeftToRight
DECL|function|isValid
DECL|function|keyBindingsForAction
DECL|function|localizedActionDescription
DECL|function|tabBar
DECL|function|text
DECL|function|text
DECL|function|~QAccessibleTabBar
DECL|member|m_index
DECL|member|m_parent
