DECL|macro|ACCESSIBLE_ITEMVIEWS_H
DECL|variable|QAccessibleInterface
DECL|variable|QAccessibleTableCell
DECL|variable|QAccessibleTableCellInterface
DECL|variable|QAccessibleTableHeaderCell
DECL|variable|QAccessibleTableInterface
