DECL|class|QACConnectionObject
DECL|class|QAccessibleWidgetPrivate
DECL|function|QAccessibleWidget
DECL|function|QAccessibleWidgetPrivate
DECL|function|actionNames
DECL|function|addControllingSignal
DECL|function|backgroundColor
DECL|function|buddyString
DECL|function|child
DECL|function|childCount
DECL|function|childWidgets
DECL|function|doAction
DECL|function|focusChild
DECL|function|foregroundColor
DECL|function|indexOfChild
DECL|function|interface_cast
DECL|function|isAncestor
DECL|function|isSender
DECL|function|isValid
DECL|function|keyBindingsForAction
DECL|function|parent
DECL|function|parentObject
DECL|function|qt_accAmpIndex
DECL|function|qt_accHotKey
DECL|function|qt_accStripAmp
DECL|function|receiverList
DECL|function|rect
DECL|function|relations
DECL|function|role
DECL|function|senderList
DECL|function|state
DECL|function|text
DECL|function|widget
DECL|function|window
DECL|function|~QAccessibleWidget
DECL|member|name
DECL|member|primarySignals
DECL|member|role
