DECL|class|QAccessibleObjectPrivate
DECL|function|QAccessibleApplication
DECL|function|QAccessibleObject
DECL|function|QAccessibleObjectEx
DECL|function|actionList
DECL|function|actionText
DECL|function|actionText
DECL|function|actionText
DECL|function|childAt
DECL|function|childCount
DECL|function|doAction
DECL|function|doAction
DECL|function|doAction
DECL|function|indexOfChild
DECL|function|isValid
DECL|function|isValid
DECL|function|navigate
DECL|function|object
DECL|function|object
DECL|function|rect
DECL|function|rect
DECL|function|relationTo
DECL|function|role
DECL|function|setText
DECL|function|setText
DECL|function|state
DECL|function|text
DECL|function|topLevelWidgets
DECL|function|userActionCount
DECL|function|userActionCount
DECL|function|userActionCount
DECL|function|~QAccessibleObject
DECL|function|~QAccessibleObjectEx
DECL|member|object
DECL|variable|action_text
