DECL|class|QACConnectionObject
DECL|class|QAccessibleWidgetPrivate
DECL|function|QAccessibleWidget
DECL|function|QAccessibleWidgetPrivate
DECL|function|actionText
DECL|function|addControllingSignal
DECL|function|buddyString
DECL|function|childAt
DECL|function|childCount
DECL|function|childWidgets
DECL|function|doAction
DECL|function|indexOfChild
DECL|function|invokeMethod
DECL|function|isAncestor
DECL|function|isSender
DECL|function|navigate
DECL|function|parentObject
DECL|function|qt_accHotKey
DECL|function|qt_accStripAmp
DECL|function|receiverList
DECL|function|rect
DECL|function|relationTo
DECL|function|role
DECL|function|senderList
DECL|function|setAccelerator
DECL|function|setDescription
DECL|function|setHelp
DECL|function|setValue
DECL|function|state
DECL|function|text
DECL|function|userActionCount
DECL|function|widget
DECL|function|~QAccessibleWidget
DECL|member|accelerator
DECL|member|asking
DECL|member|description
DECL|member|help
DECL|member|name
DECL|member|primarySignals
DECL|member|role
DECL|member|value
