DECL|macro|RANGECONTROLS_H
DECL|variable|QAbstractSlider
DECL|variable|QAbstractSpinBox
DECL|variable|QAccessibleWidget
DECL|variable|QAccessibleWidget
DECL|variable|QDial
DECL|variable|QDoubleSpinBox
DECL|variable|QScrollBar
DECL|variable|QSlider
DECL|variable|QSpinBox
