DECL|function|QAccessibleAbstractSlider
DECL|function|QAccessibleAbstractSpinBox
DECL|function|QAccessibleDial
DECL|function|QAccessibleDoubleSpinBox
DECL|function|QAccessibleScrollBar
DECL|function|QAccessibleSlider
DECL|function|QAccessibleSpinBox
DECL|function|abstractSlider
DECL|function|abstractSpinBox
DECL|function|addSelection
DECL|function|attributes
DECL|function|characterCount
DECL|function|characterRect
DECL|function|currentValue
DECL|function|currentValue
DECL|function|cursorPosition
DECL|function|deleteText
DECL|function|dial
DECL|function|doubleSpinBox
DECL|function|insertText
DECL|function|interface_cast
DECL|function|interface_cast
DECL|function|lineEditIface
DECL|function|maximumValue
DECL|function|maximumValue
DECL|function|minimumStepSize
DECL|function|minimumStepSize
DECL|function|minimumValue
DECL|function|minimumValue
DECL|function|offsetAtPoint
DECL|function|removeSelection
DECL|function|replaceText
DECL|function|scrollBar
DECL|function|scrollToSubstring
DECL|function|selection
DECL|function|selectionCount
DECL|function|setCurrentValue
DECL|function|setCurrentValue
DECL|function|setCursorPosition
DECL|function|setSelection
DECL|function|slider
DECL|function|spinBox
DECL|function|text
DECL|function|text
DECL|function|text
DECL|function|text
DECL|function|text
DECL|function|text
DECL|function|textAfterOffset
DECL|function|textAtOffset
DECL|function|textBeforeOffset
DECL|function|~QAccessibleAbstractSpinBox
