DECL|function|ScribbleArea
DECL|function|clearImage
DECL|function|event
DECL|function|openImage
DECL|function|paintEvent
DECL|function|print
DECL|function|resizeEvent
DECL|function|resizeImage
DECL|function|saveImage
