DECL|function|defaultInstall
DECL|function|findLibraries
DECL|function|hashCode
DECL|function|installRoot
DECL|function|noIO
DECL|function|qHash
DECL|function|setNoIO
DECL|function|~MakefileGenerator
DECL|macro|MAKEFILE_H
DECL|macro|QT_PCLOSE
DECL|macro|QT_POPEN
DECL|macro|QT_POPEN_READ
DECL|member|forShell
DECL|member|hash
DECL|member|in
DECL|member|out
DECL|member|pwd
DECL|member|var
DECL|struct|ReplaceExtraCompilerCacheKey
