DECL|function|MakefileGenerator
DECL|function|ReplaceExtraCompilerCacheKey
DECL|function|buildArgs
DECL|function|build_args
DECL|function|canExecute
DECL|function|checkMultipleDefinition
DECL|function|createObjectList
DECL|function|escapeDependencyPaths
DECL|function|escapeFilePaths
DECL|function|fileFixify
DECL|function|fileFixify
DECL|function|fileInfo
DECL|function|filePrefixRoot
DECL|function|filterIncludedFiles
DECL|function|findDependencies
DECL|function|findFileForDep
DECL|function|findFileInfo
DECL|function|findFilesInVPATH
DECL|function|findSubDirsSubTargets
DECL|function|fixPathForFile
DECL|function|init
DECL|function|initCompiler
DECL|function|initOutPaths
DECL|function|mkdir
DECL|function|mkdir_p_asstring
DECL|function|openOutput
DECL|function|operator ==
DECL|function|pkgConfigFileName
DECL|function|pkgConfigFixPath
DECL|function|pkgConfigPrefix
DECL|function|prlFileName
DECL|function|processPrlFile
DECL|function|processPrlFiles
DECL|function|processPrlVariable
DECL|function|projectFile
DECL|function|replaceExtraCompilerVariables
DECL|function|setProjectFile
DECL|function|specdir
DECL|function|unescapeFilePath
DECL|function|unescapeFilePaths
DECL|function|usePlatformDir
DECL|function|val
DECL|function|valGlue
DECL|function|valList
DECL|function|var
DECL|function|varGlue
DECL|function|varList
DECL|function|verifyCompilers
DECL|function|verifyExtraCompiler
DECL|function|write
DECL|function|writeExtraCompilerTargets
DECL|function|writeExtraCompilerVariables
DECL|function|writeExtraTargets
DECL|function|writeExtraVariables
DECL|function|writeHeader
DECL|function|writeInstalls
DECL|function|writeMakeQmake
DECL|function|writeMakefile
DECL|function|writeObj
DECL|function|writePkgConfigFile
DECL|function|writePrlFile
DECL|function|writePrlFile
DECL|function|writeProjectMakefile
DECL|function|writeStubMakefile
DECL|function|writeSubDirs
DECL|function|writeSubMakeCall
DECL|function|writeSubTargets
DECL|macro|MAKE_CD_IN_AND_OUT
DECL|macro|S_ISDIR
