DECL|class|SourceFiles
DECL|function|QMakeLocalFileName
DECL|function|QMakeSourceFileInfo
DECL|function|SourceDependChildren
DECL|function|SourceFile
DECL|function|SourceFileNode
DECL|function|SourceFiles
DECL|function|addChild
DECL|function|addFile
DECL|function|addSourceFile
DECL|function|addSourceFiles
DECL|function|containsSourceFile
DECL|function|dependTreeWalker
DECL|function|dependencies
DECL|function|findDeps
DECL|function|findFileForDep
DECL|function|findFileInfo
DECL|function|findMocs
DECL|function|fixPathForFile
DECL|function|getBuffer
DECL|function|getCacheVerification
DECL|function|hash
DECL|function|included
DECL|function|loadCache
DECL|function|local
DECL|function|lookupFile
DECL|function|lookupFile
DECL|function|lookupFile
DECL|function|mocable
DECL|function|saveCache
DECL|function|setCacheFile
DECL|function|setDependencyPaths
DECL|function|verifyCache
DECL|function|~QMakeSourceFileInfo
DECL|function|~SourceDependChildren
DECL|function|~SourceFile
DECL|function|~SourceFileNode
DECL|function|~SourceFiles
DECL|macro|S_ISDIR
DECL|macro|qmake_endOfLine
DECL|member|children
DECL|member|dep_checked
DECL|member|deps
DECL|member|exists
DECL|member|file
DECL|member|file
DECL|member|included_count
DECL|member|key
DECL|member|moc_checked
DECL|member|mocable
DECL|member|next
DECL|member|nodes
DECL|member|num_nodes
DECL|member|num_nodes
DECL|member|own_file
DECL|member|traversed
DECL|member|type
DECL|member|used_nodes
DECL|struct|SourceDependChildren
DECL|struct|SourceFile
DECL|struct|SourceFileNode
