DECL|class|BuildsMetaMakefileGenerator
DECL|class|SubdirsMetaMakefileGenerator
DECL|function|BuildsMetaMakefileGenerator
DECL|function|Subdir
DECL|function|SubdirsMetaMakefileGenerator
DECL|function|clearBuilds
DECL|function|createMakefileGenerator
DECL|function|createMetaGenerator
DECL|function|init
DECL|function|init
DECL|function|modesForGenerator
DECL|function|processBuild
DECL|function|type
DECL|function|type
DECL|function|write
DECL|function|write
DECL|function|~BuildsMetaMakefileGenerator
DECL|function|~MetaMakefileGenerator
DECL|function|~Subdir
DECL|function|~SubdirsMetaMakefileGenerator
DECL|macro|BUILDSMETATYPE
DECL|macro|SUBDIRSMETATYPE
DECL|member|build
DECL|member|indent
DECL|member|init_flag
DECL|member|init_flag
DECL|member|input_dir
DECL|member|makefile
DECL|member|makefile
DECL|member|makefiles
DECL|member|name
DECL|member|output_dir
DECL|member|output_file
DECL|member|subs
DECL|struct|Build
DECL|struct|Subdir
