DECL|function|attr
DECL|function|attrTag
DECL|function|attribute
DECL|function|attributeTag
DECL|function|cdata
DECL|function|closeall
DECL|function|closetag
DECL|function|closetag
DECL|function|comment
DECL|function|data
DECL|function|decl
DECL|function|declaration
DECL|function|import
DECL|function|noxml
DECL|function|raw
DECL|function|tag
DECL|function|tagValue
DECL|function|valueTag
DECL|macro|XMLOUTPUT_H
