DECL|function|QBasicAtomicPointer
DECL|function|QT_MODULE
DECL|function|fetchAndAddAcquire
DECL|function|fetchAndAddOrdered
DECL|function|fetchAndAddRelaxed
DECL|function|fetchAndAddRelease
DECL|function|fetchAndStoreAcquire
DECL|function|fetchAndStoreOrdered
DECL|function|fetchAndStoreRelaxed
DECL|function|fetchAndStoreRelease
DECL|function|isFetchAndAddNative
DECL|function|isFetchAndAddWaitFree
DECL|function|isFetchAndStoreNative
DECL|function|isFetchAndStoreWaitFree
DECL|function|isTestAndSetNative
DECL|function|isTestAndSetWaitFree
DECL|function|load
DECL|function|loadAcquire
DECL|function|store
DECL|function|storeRelease
DECL|function|testAndSetAcquire
DECL|function|testAndSetOrdered
DECL|function|testAndSetRelaxed
DECL|function|testAndSetRelease
DECL|macro|QBASICATOMIC_H
DECL|macro|QT_OLD_ATOMICS
DECL|macro|QT_OLD_ATOMICS
DECL|macro|Q_BASIC_ATOMIC_INITIALIZER
DECL|member|_q_value
DECL|member|operator
DECL|member|operator
DECL|struct|QBasicAtomicPointer
DECL|typedef|AtomicType
DECL|typedef|Ops
DECL|typedef|QBasicAtomicInt
DECL|typedef|Type
