DECL|class|Base
DECL|function|Base
DECL|function|ExceptionHolder
DECL|function|ExceptionHolder
DECL|function|clone
DECL|function|clone
DECL|function|exception
DECL|function|exception
DECL|function|hasException
DECL|function|hasThrown
DECL|function|operator =
DECL|function|raise
DECL|function|raise
DECL|function|setException
DECL|function|throwPossibleException
DECL|function|~Base
DECL|function|~ExceptionHolder
DECL|function|~QException
DECL|function|~QUnhandledException
DECL|member|exception
DECL|member|hasThrown
DECL|namespace|QtPrivate
