DECL|enumerator|IsSupported
DECL|enumerator|IsSupported
DECL|macro|QGENERICATOMIC_H
DECL|member|AddScale
DECL|member|AddScale
DECL|member|T
DECL|member|T
DECL|member|T
DECL|member|T
DECL|member|T
DECL|member|T
DECL|member|T
DECL|member|T
DECL|member|T
DECL|member|T
DECL|member|T
DECL|member|T
DECL|struct|AtomicType
DECL|struct|QAtomicAdditiveType
DECL|struct|QAtomicOpsSupport
DECL|struct|QAtomicOpsSupport
DECL|struct|QGenericAtomicOps
DECL|struct|T
DECL|typedef|AdditiveT
DECL|typedef|AdditiveT
DECL|typedef|PointerType
DECL|typedef|Type
