DECL|enumerator|IsInteger
DECL|enumerator|IsInteger
DECL|macro|QGENERICATOMIC_H
DECL|macro|always_inline
DECL|macro|always_inline
DECL|member|AddScale
DECL|member|AddScale
DECL|member|T
DECL|member|T
DECL|member|T
DECL|member|T
DECL|member|T
DECL|member|T
DECL|member|T
DECL|member|T
DECL|member|T
DECL|struct|AtomicType
DECL|struct|QAtomicAdditiveType
DECL|struct|QAtomicIntegerTraits
DECL|struct|QGenericAtomicOps
DECL|struct|T
DECL|struct|char32_t
DECL|typedef|AdditiveT
DECL|typedef|AdditiveT
DECL|typedef|PointerType
DECL|typedef|Type
