DECL|enumerator|IsInteger
DECL|function|acquireMemoryFence
DECL|function|deref
DECL|function|fetchAndAddAcquire
DECL|function|fetchAndAddOrdered
DECL|function|fetchAndAddRelaxed
DECL|function|fetchAndAddRelease
DECL|function|fetchAndStoreAcquire
DECL|function|fetchAndStoreOrdered
DECL|function|fetchAndStoreRelaxed
DECL|function|fetchAndStoreRelease
DECL|function|isFetchAndAddNative
DECL|function|isFetchAndAddWaitFree
DECL|function|isFetchAndStoreNative
DECL|function|isFetchAndStoreWaitFree
DECL|function|isReferenceCountingNative
DECL|function|isReferenceCountingWaitFree
DECL|function|load
DECL|function|loadAcquire
DECL|function|orderedMemoryFence
DECL|function|ref
DECL|function|releaseMemoryFence
DECL|function|store
DECL|function|storeRelease
DECL|function|testAndSetAcquire
DECL|function|testAndSetOrdered
DECL|function|testAndSetRelease
DECL|macro|QGENERICATOMIC_H
DECL|macro|always_inline
DECL|macro|always_inline
DECL|member|AddScale
DECL|member|AddScale
DECL|struct|AtomicType
DECL|struct|QAtomicAdditiveType
DECL|struct|QAtomicIntegerTraits
DECL|struct|QGenericAtomicOps
DECL|struct|T
DECL|typedef|AdditiveT
DECL|typedef|AdditiveT
DECL|typedef|PointerType
DECL|typedef|Type
