DECL|function|checkElapsedTimerIsTrivial
DECL|function|checkElapsedTimerIsTrivial
DECL|function|checkFutexPrivateSupport
DECL|function|dummyFutexValue
DECL|function|futexFlags
DECL|variable|futexFlagSupport
