DECL|class|QRecursiveMutexPrivate
DECL|enumerator|BlockCount
DECL|enumerator|MaxIndex
DECL|function|QMutex
DECL|function|QRecursiveMutexPrivate
DECL|function|allocate
DECL|function|freelist
DECL|function|freelist
DECL|function|isRecursive
DECL|function|isRecursive
DECL|function|release
DECL|function|~QMutex
DECL|member|QT_MUTEX_LOCK_NOEXCEPT
DECL|member|Q_DECL_NOTHROW
DECL|member|Sizes
DECL|member|Sizes
DECL|member|count
DECL|member|mutex
DECL|member|owner
DECL|struct|FreeListConstants
DECL|typedef|FreeList
