DECL|enumerator|BlockCount
DECL|enumerator|MaxIndex
DECL|function|QMutex
DECL|function|allocate
DECL|function|derefWaiters
DECL|function|isRecursive
DECL|function|lock
DECL|function|lockInternal
DECL|function|release
DECL|function|unlock
DECL|function|unlockInternal
DECL|function|~QMutex
DECL|member|Sizes
DECL|member|Sizes
DECL|struct|FreeListConstants
DECL|typedef|FreeList
