DECL|function|QReadWriteLockPrivate
DECL|macro|QREADWRITELOCK_P_H
DECL|member|accessCount
DECL|member|currentWriter
DECL|member|mutex
DECL|member|readerWait
DECL|member|recursive
DECL|member|waitingReaders
DECL|member|waitingWriters
DECL|member|writerWait
DECL|struct|QReadWriteLockPrivate
