DECL|enumerator|BlockCount
DECL|enumerator|MaxIndex
DECL|enumerator|StateLockedForRead
DECL|enumerator|StateLockedForWrite
DECL|enumerator|StateMask
DECL|function|QReadWriteLock
DECL|function|allocate
DECL|function|isUncontendedLocked
DECL|function|lockForRead
DECL|function|lockForRead
DECL|function|lockForWrite
DECL|function|lockForWrite
DECL|function|recursiveLockForRead
DECL|function|recursiveLockForWrite
DECL|function|recursiveUnlock
DECL|function|release
DECL|function|stateForWaitCondition
DECL|function|tryLockForRead
DECL|function|tryLockForRead
DECL|function|tryLockForWrite
DECL|function|tryLockForWrite
DECL|function|unlock
DECL|function|unlock
DECL|function|~QReadWriteLock
DECL|member|Sizes
DECL|member|Sizes
DECL|member|dummyLockedForRead
DECL|member|dummyLockedForWrite
DECL|struct|FreeListConstants
DECL|typedef|FreeList
