DECL|class|QWinRTThreadGlobal
DECL|function|QWinRTThreadGlobal
DECL|function|clearCurrentThreadData
DECL|function|createEventDispatcher
DECL|function|current
DECL|function|dispatch
DECL|function|dispatch
DECL|function|finish
DECL|function|init
DECL|function|msleep
DECL|function|nativePriority
DECL|function|push
DECL|function|setPriority
DECL|function|setTerminationEnabled
DECL|function|sleep
DECL|function|start
DECL|function|start
DECL|function|terminate
DECL|function|usleep
DECL|function|wait
DECL|function|yieldCurrentThread
DECL|function|~QWinRTThreadGlobal
DECL|member|dispatchEvent
DECL|member|notifier
DECL|member|notifierFactory
DECL|member|threads
DECL|member|workItemFactory
DECL|variable|qt_current_thread_data
