DECL|class|tst_LargeFile
DECL|function|appendRaw
DECL|function|cleanup
DECL|function|cleanupTestCase
DECL|function|closeFile
DECL|function|closeSparseFile
DECL|function|createSparseFile
DECL|function|fdPositioning
DECL|function|fdPositioning_data
DECL|function|fileCreated
DECL|function|filePositioning
DECL|function|filePositioning_data
DECL|function|fillFileSparsely
DECL|function|fillFileSparsely_data
DECL|function|generateDataBlock
DECL|function|getDataBlock
DECL|function|init
DECL|function|initTestCase
DECL|function|mapFile
DECL|function|mapFile_data
DECL|function|mapOffsetOverflow
DECL|function|openFileForReading
DECL|function|readFile
DECL|function|readFile_data
DECL|function|sparseFileData
DECL|function|streamPositioning
DECL|function|streamPositioning_data
DECL|function|topUpWith
DECL|function|tst_LargeFile
DECL|macro|FSCTL_SET_SPARSE
DECL|member|blockSize
DECL|member|fd_
DECL|member|generatedBlocks
DECL|member|largeFile
DECL|member|maxSizeBits
DECL|member|stream_
