DECL|class|tst_QDate
DECL|function|addDays
DECL|function|addDays_data
DECL|function|addMonths
DECL|function|addMonths_data
DECL|function|addYears
DECL|function|addYears_data
DECL|function|cleanup
DECL|function|fromString
DECL|function|fromString_data
DECL|function|fromString_format
DECL|function|fromString_format_data
DECL|function|init
DECL|function|isLeapYear
DECL|function|isValid
DECL|function|isValid_data
DECL|function|julianDay
DECL|function|julianDay_data
DECL|function|longDayName
DECL|function|longMonthName
DECL|function|negativeYear
DECL|function|operator_eq_eq
DECL|function|operator_gt
DECL|function|operator_gt_eq
DECL|function|operator_lt
DECL|function|operator_lt_eq
DECL|function|operator_not_eq
DECL|function|printNegativeYear
DECL|function|roundtrip
DECL|function|roundtripGermanLocale
DECL|function|shortDayName
DECL|function|shortMonthName
DECL|function|standaloneLongDayName
DECL|function|standaloneLongMonthName
DECL|function|standaloneShortDayName
DECL|function|standaloneShortMonthName
DECL|function|toString
DECL|function|toString_format
DECL|function|toString_format_data
DECL|function|tst_QDate
DECL|function|weekNumber
DECL|function|weekNumber_data
DECL|function|weekNumber_invalid
DECL|function|weekNumber_invalid_data
DECL|function|yearsZeroToNinetyNine
DECL|function|~tst_QDate
