DECL|class|DnDEventLoggerWidget
DECL|class|MoveWidget
DECL|class|ResizeWidget
DECL|class|TestWidget
DECL|class|tst_QWidget_window
DECL|function|DnDEventLoggerWidget
DECL|function|MoveWidget
DECL|function|ResizeWidget
DECL|function|cleanup
DECL|function|cleanupTestCase
DECL|function|dragEnterEvent
DECL|function|dragLeaveEvent
DECL|function|dragMoveEvent
DECL|function|dropEvent
DECL|function|event
DECL|function|formatDropEvent
DECL|function|initTestCase
DECL|function|msgEventAccepted
DECL|function|reset
DECL|function|setFrameless
DECL|function|tst_QWidget_window
DECL|function|tst_dnd
DECL|function|tst_min_max_size
DECL|function|tst_min_max_size_data
DECL|function|tst_move_count
DECL|function|tst_move_show
DECL|function|tst_paintEventOnSecondShow
DECL|function|tst_qtbug35600
DECL|function|tst_recreateWindow_QTBUG40817
DECL|function|tst_resize_count
DECL|function|tst_resize_show
DECL|function|tst_showWithoutActivating
DECL|function|tst_show_move
DECL|function|tst_show_move_hide_show
DECL|function|tst_show_resize
DECL|function|tst_show_resize_hide_show
DECL|function|tst_updateWinId_QTBUG40681
DECL|function|tst_windowFilePath
DECL|function|tst_windowFilePathAndwindowTitle
DECL|function|tst_windowFilePathAndwindowTitle_data
DECL|function|tst_windowFilePath_data
DECL|member|m_first
DECL|member|m_log
DECL|member|m_next
DECL|member|moveCount
DECL|member|paintEventReceived
DECL|member|resizeCount
DECL|variable|expectedLogC
