DECL|class|AccessibleTestWindow
DECL|class|tst_QAccessibilityLinux
DECL|function|AccessibleTestWindow
DECL|function|addWidget
DECL|function|cleanupTestCase
DECL|function|clearChildren
DECL|function|getAtspiState
DECL|function|getChildren
DECL|function|getInterface
DECL|function|getParent
DECL|function|initTestCase
DECL|function|registerDbus
DECL|function|testFocus
DECL|function|testLabel
DECL|function|testLineEdit
DECL|function|testListWidget
DECL|function|testSlider
DECL|function|testTextEdit
DECL|function|testTreeWidget
DECL|function|tst_QAccessibilityLinux
DECL|macro|COMPARE3
DECL|macro|ROOTPATH
DECL|member|address
DECL|member|dbus
DECL|member|m_window
DECL|member|mainWindow
DECL|member|root
DECL|member|rootApplication
