DECL|class|QSymbianTGetFontTableParam
DECL|function|QFontEngineS60
DECL|function|QSymbianTypeFaceExtras
DECL|function|addGlyphsToPath
DECL|function|alphaMapForGlyph
DECL|function|ascent
DECL|function|boundingBox
DECL|function|boundingBox
DECL|function|boundingBox_const
DECL|function|canRender
DECL|function|cmap
DECL|function|descent
DECL|function|emSquareSize
DECL|function|fontOwner
DECL|function|fontWithSize
DECL|function|getChar
DECL|function|getCharacterData
DECL|function|getSfntTable
DECL|function|getSfntTable
DECL|function|getSfntTableData
DECL|function|getSfntTableData
DECL|function|isSymbolCMap
DECL|function|leading
DECL|function|maxCharWidth
DECL|function|name
DECL|function|parseGlyphPathData
DECL|function|recalcAdvances
DECL|function|releaseFont
DECL|function|setFontScale
DECL|function|skipSpacesAndComma
DECL|function|stringToCMap
DECL|function|symbianFontTableApiAvailable
DECL|function|type
DECL|function|unitsPerEm
DECL|function|~QFontEngineS60
DECL|function|~QSymbianTypeFaceExtras
DECL|member|iContent
DECL|member|iLength
DECL|member|iTag
DECL|variable|QSymbianKFontGetFontTable
DECL|variable|QSymbianKFontReleaseFontTable
