DECL|class|tst_QSystemSemaphore
DECL|function|acquire_js
DECL|function|acquirerelease_js
DECL|function|basicProcesses
DECL|function|basicacquire
DECL|function|cleanup
DECL|function|complexacquire
DECL|function|init
DECL|function|initialValue
DECL|function|key
DECL|function|key_data
DECL|function|makeFile
DECL|function|processes
DECL|function|processes_data
DECL|function|release_js
DECL|function|tst_QSystemSemaphore
DECL|function|undo
DECL|function|~tst_QSystemSemaphore
DECL|macro|EXISTING_SHARE
DECL|macro|LACKEYLOC
DECL|macro|LACKEYLOC
DECL|macro|LACKYWAITTIME
DECL|member|existingLock
DECL|member|tempFiles
