DECL|class|CancelObject
DECL|class|DummyObject
DECL|class|IntTask
DECL|class|ProgressEmitterTask
DECL|class|ProgressObject
DECL|class|ProgressTextTask
DECL|class|ResultReadyTester
DECL|class|SignalSlotObject
DECL|class|tst_QFutureWatcher
DECL|function|CancelObject
DECL|function|ResultReadyTester
DECL|function|callInterface
DECL|function|callInterface
DECL|function|cancel
DECL|function|cancelEvents
DECL|function|canceled
DECL|function|canceled
DECL|function|changeFuture
DECL|function|createList
DECL|function|disconnectRunningFuture
DECL|function|dummySlot
DECL|function|filterer
DECL|function|finished
DECL|function|finishedState
DECL|function|function
DECL|function|futureSignals
DECL|function|incrementalFilterResults
DECL|function|incrementalMapResults
DECL|function|mapSleeper
DECL|function|mapper
DECL|function|pauseEvents
DECL|function|printProgress
DECL|function|printText
DECL|function|progressRangeChanged
DECL|function|progressText
DECL|function|progressValueChanged
DECL|function|progressValueChanged
DECL|function|qfutureSynchornizer
DECL|function|registerProgress
DECL|function|registerText
DECL|function|resultAt
DECL|function|resultReadyAt
DECL|function|resultReadyAt
DECL|function|resultReadyAt
DECL|function|resultReadyAt
DECL|function|runFunctor
DECL|function|runFunctor
DECL|function|runFunctor
DECL|function|sharedFutureInterface
DECL|function|sleeper
DECL|function|startFinish
DECL|function|started
DECL|function|throttling
DECL|function|toMuchProgress
DECL|function|warnRace
DECL|function|watchCanceledFuture
DECL|function|watchFinishedFuture
DECL|member|count
DECL|member|filter
DECL|member|m_watcher
DECL|member|ok
DECL|member|wasCanceled
DECL|variable|maxProgress
DECL|variable|mutex
DECL|variable|progressTexts
DECL|variable|progressValues
