DECL|enumerator|XCursorShape
DECL|enumerator|XFocusIn
DECL|enumerator|XFocusOut
DECL|enumerator|XGrayScale
DECL|enumerator|XKeyPress
DECL|enumerator|XKeyRelease
DECL|enumerator|XNone
DECL|enumerator|XRevertToParent
DECL|function|QXcbSoftwareOpenGLEnforcer
DECL|function|cleanup
DECL|function|qglx_buildSpec
DECL|function|qglx_findConfig
DECL|function|qglx_findVisualInfo
DECL|function|qglx_reduceFormat
DECL|function|qglx_surfaceFormatFromGLXFBConfig
DECL|function|qglx_surfaceFormatFromVisualInfo
DECL|function|~QXcbSoftwareOpenGLEnforcer
DECL|macro|CursorShape
DECL|macro|FocusIn
DECL|macro|FocusOut
DECL|macro|FontChange
DECL|macro|GrayScale
DECL|macro|KeyPress
DECL|macro|KeyRelease
DECL|macro|None
DECL|macro|RevertToParent
DECL|member|checkedForceSoftwareOpenGL
DECL|member|checkedForceSoftwareOpenGL
DECL|member|forceSoftwareOpenGL
DECL|member|forceSoftwareOpenGL
DECL|struct|QXcbSoftwareOpenGLEnforcer
DECL|struct|QXlibScopedPointerDeleter
