DECL|class|QWinRTIntegrationPrivate
DECL|function|QWinRTIntegration
DECL|function|createEventDispatcher
DECL|function|createPlatformBackingStore
DECL|function|createPlatformOpenGLContext
DECL|function|createPlatformTheme
DECL|function|createPlatformWindow
DECL|function|fontDatabase
DECL|function|hasCapability
DECL|function|inputContext
DECL|function|onBackButtonPressed
DECL|function|onResume
DECL|function|onSuspended
DECL|function|qHash
DECL|function|qHash
DECL|function|queryKeyboardModifiers
DECL|function|services
DECL|function|styleHint
DECL|function|succeeded
DECL|function|themeNames
DECL|function|~QWinRTIntegration
DECL|member|application
DECL|member|applicationTokens
DECL|member|buttonsTokens
DECL|member|fontDatabase
DECL|member|hardwareButtons
DECL|member|inputContext
DECL|member|mainScreen
DECL|member|platformServices
DECL|typedef|BackPressedHandler
DECL|typedef|CoreApplicationCallbackRemover
DECL|typedef|HardwareButtonsCallbackRemover
DECL|typedef|ResumeHandler
DECL|typedef|SuspendHandler
