DECL|enumerator|Mouse
DECL|enumerator|Tablet
DECL|enumerator|TouchScreen
DECL|enumerator|Unknown
DECL|enum|Type
DECL|macro|QWINRTSCREEN_H
DECL|member|device
DECL|member|type
DECL|struct|Pointer
DECL|variable|QTouchDevice
DECL|variable|QWinRTCursor
DECL|variable|QWinRTEGLContext
DECL|variable|QWinRTInputContext
DECL|variable|QWinRTPageFlipper
