DECL|class|QWinRTThemePrivate
DECL|function|QWinRTTheme
DECL|function|createPlatformDialogHelper
DECL|function|fromColor
DECL|function|palette
DECL|function|styleHint
DECL|function|uiSettings
DECL|function|usePlatformNativeDialog
DECL|member|palette
