DECL|enumerator|Texture2D
DECL|enumerator|TextureCube
DECL|enum|TextureType
DECL|function|Attribute
DECL|function|QWinRTBackingStore
DECL|function|Sampler
DECL|function|ShaderString
DECL|function|Uniform
DECL|function|Uniform
DECL|function|UniformIndex
DECL|function|beginPaint
DECL|function|createAngleBinary
DECL|function|endPaint
DECL|function|flush
DECL|function|operator <<
DECL|function|paintDevice
DECL|function|resize
DECL|function|~QWinRTBackingStore
DECL|member|active
DECL|member|arraySize
DECL|member|data
DECL|member|element
DECL|member|index
DECL|member|index
DECL|member|name
DECL|member|name
DECL|member|name
DECL|member|precision
DECL|member|psRegisterIndex
DECL|member|registerCount
DECL|member|type
DECL|member|type
DECL|member|type
DECL|member|unit
DECL|member|vsRegisterIndex
DECL|struct|Attribute
DECL|struct|Sampler
DECL|struct|ShaderString
DECL|struct|Uniform
DECL|struct|UniformIndex
DECL|variable|normCoords
DECL|variable|quadCoords
