DECL|class|QWinRTEGLContextPrivate
DECL|function|QWinRTEGLContext
DECL|function|QWinRTEGLContextPrivate
DECL|function|WinRTEGLDisplay
DECL|function|display
DECL|function|doneCurrent
DECL|function|format
DECL|function|getProcAddress
DECL|function|initialize
DECL|function|makeCurrent
DECL|function|swapBuffers
DECL|function|~QWinRTEGLContext
DECL|function|~WinRTEGLDisplay
DECL|macro|EGL_EGLEXT_PROTOTYPES
DECL|member|eglConfig
DECL|member|eglContext
DECL|member|eglDisplay
DECL|member|eglShareContext
DECL|member|format
DECL|struct|WinRTEGLDisplay
