DECL|class|QWinRTScreenPrivate
DECL|function|QWinRTScreen
DECL|function|addWindow
DECL|function|coreWindow
DECL|function|cursor
DECL|function|depth
DECL|function|eglConfig
DECL|function|eglDisplay
DECL|function|eglSurface
DECL|function|format
DECL|function|geometry
DECL|function|handleExpose
DECL|function|inputContext
DECL|function|keyboardModifiers
DECL|function|logicalDpi
DECL|function|lower
DECL|function|nativeOrientation
DECL|function|nativeOrientationsFromQt
DECL|function|onActivated
DECL|function|onAutomationProviderRequested
DECL|function|onBackButtonPressed
DECL|function|onCharacterReceived
DECL|function|onClosed
DECL|function|onDpiChanged
DECL|function|onKeyDown
DECL|function|onKeyUp
DECL|function|onOrientationChanged
DECL|function|onPointerEntered
DECL|function|onPointerExited
DECL|function|onPointerUpdated
DECL|function|onResume
DECL|function|onSizeChanged
DECL|function|onSuspended
DECL|function|onVisibilityChanged
DECL|function|orientation
DECL|function|physicalSize
DECL|function|qHash
DECL|function|qHash
DECL|function|qHash
DECL|function|qHash
DECL|function|qIsNonPrintable
DECL|function|qKeyFromCode
DECL|function|qKeyFromVirtual
DECL|function|qtOrientationsFromNative
DECL|function|raise
DECL|function|removeWindow
DECL|function|surfaceFormat
DECL|function|topWindow
DECL|function|~QWinRTScreen
DECL|macro|EGL_EGLEXT_PROTOTYPES
DECL|member|activeKeys
DECL|member|application
DECL|member|applicationTokens
DECL|member|buttonsTokens
DECL|member|coreWindow
DECL|member|cursor
DECL|member|displayInformation
DECL|member|displayTokens
DECL|member|eglConfig
DECL|member|eglDisplay
DECL|member|eglSurface
DECL|member|hardwareButtons
DECL|member|inputContext
DECL|member|inputContext
DECL|member|logicalDpi
DECL|member|logicalSize
DECL|member|nativeOrientation
DECL|member|orientation
DECL|member|physicalDpi
DECL|member|scaleFactor
DECL|member|surfaceFormat
DECL|member|touchDevice
DECL|member|touchPoints
DECL|member|visibleWindows
DECL|member|windowTokens
DECL|typedef|ActivatedHandler
DECL|typedef|AutomationProviderRequestedHandler
DECL|typedef|BackPressedHandler
DECL|typedef|CharacterReceivedHandler
DECL|typedef|ClosedHandler
DECL|typedef|CoreApplicationCallbackRemover
DECL|typedef|CoreWindowCallbackRemover
DECL|typedef|DisplayCallbackRemover
DECL|typedef|DisplayInformationHandler
DECL|typedef|HardwareButtonsCallbackRemover
DECL|typedef|InputEnabledHandler
DECL|typedef|KeyHandler
DECL|typedef|PointerHandler
DECL|typedef|ResumeHandler
DECL|typedef|SizeChangedHandler
DECL|typedef|SuspendHandler
DECL|typedef|VisibilityChangedHandler
