DECL|class|QWinRTWindowPrivate
DECL|function|QWinRTWindow
DECL|function|devicePixelRatio
DECL|function|format
DECL|function|isActive
DECL|function|isExposed
DECL|function|lower
DECL|function|raise
DECL|function|setGeometry
DECL|function|setVisible
DECL|function|setWindowTitle
DECL|function|winId
DECL|function|~QWinRTWindow
DECL|macro|EGL_EGLEXT_PROTOTYPES
DECL|member|screen
DECL|member|surfaceFormat
DECL|member|swapChainPanel
DECL|member|windowTitle
