DECL|function|defaultFont
DECL|function|defaultFont
DECL|function|fontDir
DECL|function|fontEngine
DECL|function|fontsAlwaysScalable
DECL|function|populateFamily
DECL|function|populateFontDatabase
DECL|function|releaseHandle
DECL|function|writingSystemFromUnicodeRange
DECL|function|~QWinRTFontDatabase
