DECL|function|QWinRTClipboard
DECL|function|convertToWindowsLineEnding
DECL|function|mimeData
DECL|function|onContentChanged
DECL|function|setMimeData
DECL|function|supportsMode
DECL|macro|RETURN_NULLPTR_IF_FAILED
DECL|typedef|ContentChangedHandler
