DECL|function|QWinRTScreen
DECL|function|addWindow
DECL|function|coreWindow
DECL|function|cursor
DECL|function|depth
DECL|function|eglDisplay
DECL|function|eglSurface
DECL|function|format
DECL|function|geometry
DECL|function|handleExpose
DECL|function|inputContext
DECL|function|lower
DECL|function|nativeOrientation
DECL|function|onActivated
DECL|function|onAutomationProviderRequested
DECL|function|onCharacterReceived
DECL|function|onClosed
DECL|function|onKey
DECL|function|onOrientationChanged
DECL|function|onPointerEntered
DECL|function|onPointerExited
DECL|function|onPointerUpdated
DECL|function|onSizeChanged
DECL|function|onVisibilityChanged
DECL|function|orientation
DECL|function|qKeyFromChar
DECL|function|qKeyModifiers
DECL|function|qMetaKeyFromVirtual
DECL|function|qOrientationFromNative
DECL|function|raise
DECL|function|removeWindow
DECL|function|surfaceFormat
DECL|function|topWindow
DECL|typedef|ActivatedHandler
DECL|typedef|AutomationProviderRequestedHandler
DECL|typedef|CharacterReceivedHandler
DECL|typedef|ClosedHandler
DECL|typedef|InputEnabledHandler
DECL|typedef|KeyHandler
DECL|typedef|PointerHandler
DECL|typedef|SizeChangedHandler
DECL|typedef|VisibilityChangedHandler
