DECL|class|QWinRTFileEngineHandlerPrivate
DECL|class|QWinRTFileEnginePrivate
DECL|function|QWinRTFileEngine
DECL|function|QWinRTFileEngineHandler
DECL|function|QWinRTFileEnginePrivate
DECL|function|close
DECL|function|copy
DECL|function|create
DECL|function|fileFlags
DECL|function|fileName
DECL|function|fileTime
DECL|function|flush
DECL|function|getDestinationFolder
DECL|function|open
DECL|function|pos
DECL|function|read
DECL|function|registerFile
DECL|function|registeredFile
DECL|function|remove
DECL|function|rename
DECL|function|renameOverwrite
DECL|function|seek
DECL|function|setPermissions
DECL|function|size
DECL|function|write
DECL|function|~QWinRTFileEngine
DECL|function|~QWinRTFileEngineHandler
DECL|macro|RETURN_AND_SET_ERROR_IF_FAILED
DECL|member|bufferFactory
DECL|member|file
DECL|member|fileName
DECL|member|files
DECL|member|firstDot
DECL|member|lastSeparator
DECL|member|openMode
DECL|member|pos
DECL|member|q_ptr
DECL|member|stream
DECL|typedef|StreamCompletedHandler
DECL|typedef|StreamReadCompletedHandler
