DECL|function|EngineInstanceHolder
DECL|function|QBBEngine
DECL|function|capabilities
DECL|function|cleanup
DECL|function|cleanup
DECL|function|connectToId
DECL|function|createSessionBackend
DECL|function|defaultConfiguration
DECL|function|disconnectFromId
DECL|function|doRequestUpdate
DECL|function|getInterfaceFromId
DECL|function|hasIdentifier
DECL|function|idForName
DECL|function|initialize
DECL|function|interfaceType
DECL|function|nativeEventFilter
DECL|function|removeConfiguration
DECL|function|requestUpdate
DECL|function|requiresPolling
DECL|function|sessionStateForId
DECL|function|updateConfiguration
DECL|function|~QBBEngine
DECL|macro|qBearerDebug
DECL|macro|qBearerDebug
DECL|member|instance
DECL|struct|EngineInstanceHolder
DECL|struct|NetstatusInterfaceCleanupHelper
DECL|struct|NetstatusInterfaceListCleanupHelper
