DECL|class|QDBusCustomTypeInfo
DECL|function|QDBusCustomTypeInfo
DECL|function|demarshall
DECL|function|init
DECL|function|marshall
DECL|function|registerHelper
DECL|function|registerMarshallOperators
DECL|function|signatureToType
DECL|function|typeToSignature
DECL|macro|DBUS_TYPE_UNIX_FD
DECL|macro|DBUS_TYPE_UNIX_FD_AS_STRING
DECL|member|demarshall
DECL|member|marshall
DECL|member|signature
