DECL|function|QDBusInterface
DECL|function|QDBusInterfacePrivate
DECL|function|copyArgument
DECL|function|metaObject
DECL|function|metacall
DECL|function|qt_metacall
DECL|function|qt_metacast
DECL|function|~QDBusInterface
DECL|function|~QDBusInterfacePrivate
