DECL|function|QDBusXmlParser
DECL|function|parseAnnotation
DECL|function|parseArg
DECL|function|parseMethod
DECL|function|parseProperty
DECL|function|parseSignal
DECL|function|readInterface
DECL|function|readNode
DECL|macro|qDBusParserError
DECL|macro|qDBusParserError
