DECL|class|QDBusDefaultConnection
DECL|function|QDBusConnection
DECL|function|QDBusConnection
DECL|function|QDBusConnection
DECL|function|QDBusDefaultConnection
DECL|function|asyncCall
DECL|function|baseService
DECL|function|call
DECL|function|callWithCallback
DECL|function|callWithCallback
DECL|function|connect
DECL|function|connect
DECL|function|connect
DECL|function|connectToBus
DECL|function|connectToBus
DECL|function|connectToPeer
DECL|function|connection
DECL|function|connectionCapabilities
DECL|function|disconnect
DECL|function|disconnect
DECL|function|disconnect
DECL|function|disconnectFromBus
DECL|function|disconnectFromPeer
DECL|function|instance
DECL|function|interface
DECL|function|internalPointer
DECL|function|isConnected
DECL|function|lastError
DECL|function|localMachineId
DECL|function|name
DECL|function|objectRegisteredAt
DECL|function|operator =
DECL|function|qDBusBindToApplication
DECL|function|registerObject
DECL|function|registerService
DECL|function|removeConnection
DECL|function|send
DECL|function|sender
DECL|function|sender
DECL|function|sessionBus
DECL|function|setBusService
DECL|function|setConnection
DECL|function|setSender
DECL|function|setSender
DECL|function|systemBus
DECL|function|unregisterObject
DECL|function|unregisterService
DECL|function|~QDBusConnection
DECL|function|~QDBusConnectionManager
DECL|function|~QDBusDefaultConnection
DECL|member|ownName
DECL|variable|_q_sessionBusName
DECL|variable|_q_systemBusName
