DECL|macro|QDBUSINTEGRATOR_P_H
DECL|member|flags
DECL|member|hash
DECL|member|metaTypes
DECL|member|slotIdx
DECL|struct|Data
DECL|struct|QDBusSlotCache
DECL|typedef|Hash
DECL|typedef|QString
DECL|variable|QDBusConnectionPrivate
