DECL|function|atEnd
DECL|function|beginArray
DECL|function|beginCommon
DECL|function|beginMap
DECL|function|beginMapEntry
DECL|function|beginStructure
DECL|function|currentSignature
DECL|function|currentType
DECL|function|duplicate
DECL|function|endArray
DECL|function|endCommon
DECL|function|endMap
DECL|function|endMapEntry
DECL|function|endStructure
DECL|function|isCurrentTypeStringLike
DECL|function|qIterGet
DECL|function|toBool
DECL|function|toByte
DECL|function|toByteArray
DECL|function|toDouble
DECL|function|toInt
DECL|function|toLongLong
DECL|function|toObjectPath
DECL|function|toObjectPathUnchecked
DECL|function|toShort
DECL|function|toSignature
DECL|function|toSignatureUnchecked
DECL|function|toString
DECL|function|toStringList
DECL|function|toStringUnchecked
DECL|function|toUInt
DECL|function|toULongLong
DECL|function|toUShort
DECL|function|toUnixFileDescriptor
DECL|function|toVariant
DECL|function|toVariantInternal
DECL|function|~QDBusDemarshaller
