DECL|function|QDBusAbstractInterface
DECL|function|QDBusAbstractInterface
DECL|function|QDBusAbstractInterfaceBase
DECL|function|QDBusAbstractInterfacePrivate
DECL|function|_q_serviceOwnerChanged
DECL|function|asyncCall
DECL|function|asyncCallWithArgumentList
DECL|function|call
DECL|function|call
DECL|function|callWithArgumentList
DECL|function|callWithCallback
DECL|function|callWithCallback
DECL|function|canMakeCalls
DECL|function|checkIfValid
DECL|function|connectNotify
DECL|function|connection
DECL|function|disconnectNotify
DECL|function|interface
DECL|function|internalConstCall
DECL|function|internalPropGet
DECL|function|internalPropSet
DECL|function|isValid
DECL|function|lastError
DECL|function|path
DECL|function|property
DECL|function|qt_metacall
DECL|function|service
DECL|function|setProperty
DECL|function|setTimeout
DECL|function|timeout
DECL|function|~QDBusAbstractInterface
