DECL|function|QDBusXmlParser
DECL|function|QDBusXmlParser
DECL|function|interfaces
DECL|function|object
DECL|function|objectTree
DECL|function|parseAnnotations
DECL|function|parseArgs
DECL|macro|qDBusParserError
DECL|macro|qDBusParserError
