DECL|function|demarshaller
DECL|function|marshaller
DECL|macro|DBUS_TYPE_UNIX_FD
DECL|macro|DBUS_TYPE_UNIX_FD_AS_STRING
DECL|macro|QDBUSARGUMENT_P_H
DECL|variable|QDBusDemarshaller
DECL|variable|QDBusMarshaller
