DECL|class|QDirectFbEGLContext
DECL|class|QDirectFbScreenEGL
DECL|class|QDirectFbWindowEGL
DECL|function|QDirectFbEGLContext
DECL|function|QDirectFbScreenEGL
DECL|function|QDirectFbWindowEGL
DECL|function|createPlatformOpenGLContext
DECL|function|createPlatformWindow
DECL|function|eglDisplay
DECL|function|eglSurfaceForPlatformSurface
DECL|function|format
DECL|function|initializeEGL
DECL|function|initializeScreen
DECL|function|platformDestroy
DECL|function|platformInit
DECL|function|~QDirectFbScreenEGL
DECL|function|~QDirectFbWindowEGL
DECL|member|m_eglDisplay
DECL|member|m_eglSurface
DECL|member|m_screen
