DECL|function|QDirectFbKeyMap
DECL|function|colorDepthForSurface
DECL|function|dfbDisplayLayer
DECL|function|dfbInterface
DECL|function|dfbSurfaceForPlatformPixmap
DECL|function|eventType
DECL|function|imageFormatFromSurfaceFormat
DECL|function|keyMap
DECL|function|keyboardModifiers
DECL|function|mouseButton
DECL|function|mouseButtons
DECL|function|toDfbScreen
DECL|member|dfbKeymap
