DECL|function|QDirectFbWindow
DECL|function|dfbSurface
DECL|function|dfbWindow
DECL|function|lower
DECL|function|raise
DECL|function|setGeometry
DECL|function|setKeyboardGrabEnabled
DECL|function|setMouseGrabEnabled
DECL|function|setOpacity
DECL|function|setVisible
DECL|function|setWindowFlags
DECL|function|winId
DECL|function|~QDirectFbWindow
