DECL|function|QDirectFbIntegration
DECL|function|QDirectFbScreen
DECL|function|createPixmapData
DECL|function|createPlatformWindow
DECL|function|createWindowSurface
DECL|function|fontDatabase
DECL|function|~QDirectFbIntegration
DECL|function|~QDirectFbScreen
