DECL|function|QDirectFbWindowSurface
DECL|function|beginPaint
DECL|function|endPaint
DECL|function|flush
DECL|function|paintDevice
DECL|function|resize
DECL|function|scroll
DECL|function|scrollSurface
DECL|function|~QDirectFbWindowSurface
