DECL|class|LightWidget
DECL|class|TrafficLight
DECL|class|TrafficLightWidget
DECL|function|LightWidget
DECL|function|TrafficLight
DECL|function|TrafficLightWidget
DECL|function|createLightState
DECL|function|greenLight
DECL|function|isOn
DECL|function|main
DECL|function|paintEvent
DECL|function|redLight
DECL|function|setOn
DECL|function|turnOff
DECL|function|turnOn
DECL|function|yellowLight
DECL|member|m_color
DECL|member|m_green
DECL|member|m_on
DECL|member|m_red
DECL|member|m_yellow
