DECL|class|tst_QScopedValueRollback
DECL|function|earlyExitScope
DECL|function|earlyExitScope_helper
DECL|function|exceptions
DECL|function|leavingScope
DECL|function|leavingScopeAfterCommit
DECL|function|rollbackToPreviousCommit
