DECL|function|getpagesize
DECL|macro|QPLATFORMDEFS_H
DECL|macro|QT_NO_READDIR64
DECL|macro|QT_QWS_TEMP_DIR
DECL|macro|QT_SNPRINTF
DECL|macro|QT_USE_XOPEN_LFS_EXTENSIONS
DECL|macro|QT_VSNPRINTF
DECL|macro|__STDC_CONSTANT_MACROS
