DECL|class|ColorWidget
DECL|class|DummyMoveSurface
DECL|class|DummyScreen
DECL|class|tst_QWSWindowSystem
DECL|function|ColorWidget
DECL|function|DummyMoveSurface
DECL|function|DummyMoveSurface
DECL|function|DummyScreen
DECL|function|WA_PaintOnScreen
DECL|function|blit
DECL|function|color
DECL|function|connect
DECL|function|createSurface
DECL|function|directPainter
DECL|function|disconnect
DECL|function|dontFlushUnitializedWindowSurfaces
DECL|function|exposeRegion
DECL|function|fillWindowSurface
DECL|function|getWindow
DECL|function|initDevice
DECL|function|initTestCase
DECL|function|initialGeometry
DECL|function|key
DECL|function|move
DECL|function|paintEvent
DECL|function|raiseLowerWindow
DECL|function|setMaxWindowRect
DECL|function|setMode
DECL|function|showHideWindow
DECL|function|solidFill
DECL|function|task188025
DECL|function|task188025_data
DECL|function|toplevelMove
DECL|function|tst_QWSWindowSystem
DECL|function|windowOpacity
DECL|function|~DummyScreen
DECL|function|~tst_QWSWindowSystem
DECL|macro|VERIFY_COLOR
DECL|member|bgColor
DECL|member|c
DECL|member|s
