DECL|class|QTouchScreenData
DECL|function|QTouchScreenData
DECL|function|QTouchScreenHandler
DECL|function|QTouchScreenHandlerThread
DECL|function|Slot
DECL|function|addObserver
DECL|function|handle
DECL|function|readData
DECL|function|run
DECL|function|try_udev
DECL|function|~QTouchScreenHandler
DECL|function|~QTouchScreenHandlerThread
DECL|member|hw_name
DECL|member|hw_range_x_max
DECL|member|hw_range_x_min
DECL|member|hw_range_y_max
DECL|member|hw_range_y_min
DECL|member|m_currentSlot
DECL|member|m_lastReport
DECL|member|m_observers
DECL|member|m_prevState
DECL|member|m_slots
DECL|member|m_state
DECL|member|m_touchPoints
DECL|member|primary
DECL|member|q
DECL|member|state
DECL|member|trackingId
DECL|member|x
DECL|member|y
DECL|struct|Slot
