DECL|class|HIDDeviceHandler
DECL|class|HIDDriverHandler
DECL|class|IntNotifier
DECL|function|HIDDeviceHandler
DECL|function|HIDDriverHandler
DECL|function|IntNotifier
DECL|function|QIntegrityHIDManager
DECL|function|async_wait
DECL|function|async_wait
DECL|function|find_devices
DECL|function|get_driver
DECL|function|get_handle
DECL|function|open_devices
DECL|function|process_event
DECL|function|process_event
DECL|function|run
DECL|function|~HIDDeviceHandler
DECL|function|~HIDDriverHandler
DECL|function|~IntNotifier
DECL|function|~QIntegrityHIDManager
DECL|member|ActivityPriority
DECL|member|Q_DECL_OVERRIDE
DECL|member|Q_DECL_OVERRIDE
DECL|member|Q_DECL_OVERRIDE
DECL|member|Q_DECL_OVERRIDE
DECL|member|act
DECL|member|buttons
DECL|member|currentPos
DECL|member|devices
DECL|member|driver
DECL|member|driver
DECL|member|handle
