DECL|function|QMinimalIntegration
DECL|function|createEventDispatcher
DECL|function|createPlatformBackingStore
DECL|function|createPlatformPixmap
DECL|function|createPlatformWindow
DECL|function|hasCapability
