DECL|function|Report
DECL|function|addItems
DECL|function|addResult
DECL|function|computeStats
DECL|function|end
DECL|function|filePath
DECL|function|generateCompared
DECL|function|generateThumbnail
DECL|function|handleCGIQuery
DECL|function|init
DECL|function|numberOfMismatches
DECL|function|reportProduced
DECL|function|summary
DECL|function|updateLatestPointer
DECL|function|write
DECL|function|writeFooter
DECL|function|writeFunctionResults
DECL|function|writeHeader
DECL|function|writeItem
DECL|function|writeResultsXmlFiles
DECL|function|~Report
