DECL|class|ActiveMdiSubWindowFunctor
DECL|function|ActiveMdiSubWindowFunctor
DECL|function|MainWindow
DECL|function|about
DECL|function|activeMdiChild
DECL|function|closeEvent
DECL|function|copy
DECL|function|createActions
DECL|function|createMdiChild
DECL|function|createStatusBar
DECL|function|cut
DECL|function|fileKey
DECL|function|findMdiChild
DECL|function|hasRecentFiles
DECL|function|loadFile
DECL|function|newFile
DECL|function|open
DECL|function|openFile
DECL|function|openRecentFile
DECL|function|operator ()
DECL|function|paste
DECL|function|prependToRecentFiles
DECL|function|readRecentFiles
DECL|function|readSettings
DECL|function|recentFilesKey
DECL|function|save
DECL|function|saveAs
DECL|function|setRecentFilesVisible
DECL|function|switchLayoutDirection
DECL|function|updateMenus
DECL|function|updateRecentFileActions
DECL|function|updateWindowMenu
DECL|function|writeRecentFiles
DECL|function|writeSettings
DECL|member|m_activeWindow
DECL|member|m_mdiArea
