DECL|class|ComboAction
DECL|class|CrashedAction
DECL|class|tst_QWidgetAction
DECL|function|ComboAction
DECL|function|CrashedAction
DECL|function|createWidget
DECL|function|createWidget
DECL|function|createdWidgets
DECL|function|customWidget
DECL|function|defaultWidget
DECL|function|keepOwnership
DECL|function|popup
DECL|function|releaseWidgetCrash
DECL|function|setEnabled
DECL|function|setFrameless
DECL|function|visibility
DECL|function|visibilityUpdate
