DECL|function|QEditorInfo
DECL|function|QEditorInfo
DECL|macro|QABSTRACTITEMVIEW_P_H
DECL|member|isStatic
DECL|member|widget
DECL|struct|QEditorInfo
DECL|typedef|QEditorIndexHash
DECL|typedef|QIndexEditorHash
DECL|typedef|QItemViewPaintPair
DECL|typedef|QItemViewPaintPairs
DECL|typedef|QPersistentModelIndex
DECL|typedef|QRect
DECL|typedef|QWidget
