DECL|function|QProxyModel
DECL|function|QProxyModel
DECL|function|_q_sourceColumnsAboutToBeInserted
DECL|function|_q_sourceColumnsAboutToBeRemoved
DECL|function|_q_sourceColumnsInserted
DECL|function|_q_sourceColumnsRemoved
DECL|function|_q_sourceDataChanged
DECL|function|_q_sourceRowsAboutToBeInserted
DECL|function|_q_sourceRowsAboutToBeRemoved
DECL|function|_q_sourceRowsInserted
DECL|function|_q_sourceRowsRemoved
DECL|function|columnCount
DECL|function|connectToModel
DECL|function|data
DECL|function|disconnectFromModel
DECL|function|dropMimeData
DECL|function|fetchMore
DECL|function|flags
DECL|function|hasChildren
DECL|function|headerData
DECL|function|index
DECL|function|insertColumns
DECL|function|insertRows
DECL|function|match
DECL|function|mimeData
DECL|function|mimeTypes
DECL|function|model
DECL|function|parent
DECL|function|revert
DECL|function|rowCount
DECL|function|setData
DECL|function|setHeaderData
DECL|function|setModel
DECL|function|setProxyModel
DECL|function|setSourceModel
DECL|function|sort
DECL|function|span
DECL|function|submit
DECL|function|supportedDropActions
DECL|function|~QProxyModel
