DECL|function|QTreeViewItem
DECL|macro|QTREEVIEW_P_H
DECL|member|expanded
DECL|member|hasChildren
DECL|member|hasMoreSiblings
DECL|member|height
DECL|member|index
DECL|member|level
DECL|member|parentItem
DECL|member|spanning
DECL|member|total
DECL|struct|QTreeViewItem
