DECL|function|QT_FORWARD_DECLARE_CLASS
DECL|macro|HTMLGENERATOR_H
DECL|member|QString
DECL|member|foreignImages
DECL|member|images
DECL|member|public
DECL|member|public
DECL|member|referenceImages
DECL|member|rows
DECL|struct|HTMLRow
DECL|struct|HTMLSuite
