DECL|function|QEglProperties
DECL|function|QEglProperties
DECL|function|noegl
DECL|function|reduceConfiguration
DECL|function|removeValue
DECL|function|setDeviceType
DECL|function|setPaintDeviceFormat
DECL|function|setPixelFormat
DECL|function|setRenderableType
DECL|function|setValue
DECL|function|toString
DECL|function|value
DECL|macro|NOEGL
