DECL|function|QEglContext
DECL|function|chooseConfig
DECL|function|chooseConfig
DECL|function|configAttrib
DECL|function|createContext
DECL|function|createSurface
DECL|function|createSurface
DECL|function|currentContext
DECL|function|defaultConfig
DECL|function|destroyContext
DECL|function|destroySurface
DECL|function|display
DECL|function|doneCurrent
DECL|function|dumpAllConfigs
DECL|function|eglCreateImageKHR
DECL|function|eglDestroyImageKHR
DECL|function|eglSwapBuffersRegion2NOK
DECL|function|errorString
DECL|function|extensions
DECL|function|hasExtension
DECL|function|isCurrent
DECL|function|isValid
DECL|function|lazyDoneCurrent
DECL|function|makeCurrent
DECL|function|nativeDisplay
DECL|function|nativePixmap
DECL|function|nativeWindow
DECL|function|noegl
DECL|function|setCurrentContext
DECL|function|swapBuffers
DECL|function|swapBuffersRegion2NOK
DECL|function|~QEglContext
DECL|macro|NOEGL
