DECL|function|MainWindow
DECL|function|about
DECL|function|createMenus
DECL|function|load
DECL|function|save
DECL|function|setAlphaValuator
DECL|function|setBrushColor
DECL|function|setLineWidthValuator
DECL|function|setSaturationValuator
