DECL|macro|alpha
DECL|macro|arm
DECL|macro|avr32
DECL|macro|bfin
DECL|macro|i386
DECL|macro|ia64
DECL|macro|mips
DECL|macro|power
DECL|macro|s390
DECL|macro|sh
DECL|macro|sparc
DECL|macro|unknown
DECL|macro|x86_64
