DECL|macro|QUIKITWINDOW_H
DECL|variable|EAGLPlatformContext
DECL|variable|QUIKitScreen
DECL|variable|autocorrectionType
DECL|variable|keyboardAppearance
DECL|variable|returnKeyType
DECL|variable|secureTextEntry
