DECL|class|MyGraphicsItem
DECL|class|MyGraphicsView
DECL|function|MyGraphicsItem
DECL|function|MyGraphicsView
DECL|function|main
DECL|function|mouseMoveEvent
DECL|function|paint
DECL|function|updateRubberbandInfo
DECL|member|rubberbandLabel
