DECL|function|My3Server
DECL|function|My3Socket
DECL|function|My4Server
DECL|function|My4Socket
DECL|function|Test
DECL|function|closed
DECL|function|closed
DECL|function|incomingConnection
DECL|function|newConnection
DECL|function|read
DECL|function|read
DECL|function|sendTest
DECL|function|sendTest
DECL|function|stopServer
DECL|function|stopServer
