DECL|function|Inputcontext1Adaptor
DECL|function|activationLostEvent
DECL|function|commitString
DECL|function|copy
DECL|function|imInitiatedHide
DECL|function|keyEvent
DECL|function|paste
DECL|function|preeditRectangle
DECL|function|selection
DECL|function|setDetectableAutoRepeat
DECL|function|setGlobalCorrectionEnabled
DECL|function|setLanguage
DECL|function|setRedirectKeys
DECL|function|setSelection
DECL|function|updateInputMethodArea
DECL|function|updatePreedit
DECL|function|~Inputcontext1Adaptor
