DECL|class|QtAccessibilityDelegate
DECL|field|DEFAULT_CLASS_NAME
DECL|field|INVALID_ID
DECL|field|TAG
DECL|field|m_focusedVirtualViewId
DECL|field|m_globalOffset
DECL|field|m_hoveredVirtualViewId
DECL|field|m_manager
DECL|field|m_nodeProvider
DECL|field|m_view
DECL|method|QtAccessibilityDelegate
DECL|method|dispatchHoverEvent
DECL|method|dumpNodes
DECL|method|getAccessibilityNodeProvider
DECL|method|getEventForVirtualViewId
DECL|method|getNodeForView
DECL|method|getNodeForVirtualViewId
DECL|method|invalidateVirtualViewId
DECL|method|performActionForVirtualViewId
DECL|method|sendEventForVirtualViewId
DECL|method|setHoveredVirtualViewId
DECL|package|org.qtproject.qt5.android.accessibility
