DECL|class|QtNativeAccessibility
DECL|method|childIdListForAccessibleObject
DECL|method|clickAction
DECL|method|descriptionForAccessibleObject
DECL|method|hitTest
DECL|method|parentId
DECL|method|populateNode
DECL|method|screenRect
DECL|method|setActive
DECL|package|org.qtproject.qt5.android.accessibility
