DECL|class|QClipboardData
DECL|class|QClipboardINCRTransaction
DECL|class|QClipboardWatcher
DECL|function|QClipboard
DECL|function|QClipboardData
DECL|function|QClipboardINCRTransaction
DECL|function|QClipboardWatcher
DECL|function|checkForClipboardEvents
DECL|function|cleanup
DECL|function|cleanupClipboardData
DECL|function|cleanupSelectionData
DECL|function|clear
DECL|function|clear
DECL|function|clipboardData
DECL|function|clipboardReadIncrementalProperty
DECL|function|clipboardReadProperty
DECL|function|clipboardWaitForEvent
DECL|function|connectNotify
DECL|function|empty
DECL|function|event
DECL|function|formats_sys
DECL|function|getDataInFormat
DECL|function|hasFormat_sys
DECL|function|maxSelectionIncr
DECL|function|mimeData
DECL|function|mimeDataRef
DECL|function|ownerDestroyed
DECL|function|ownsMode
DECL|function|qt_check_clipboard_sentinel
DECL|function|qt_check_selection_sentinel
DECL|function|qt_init_timestamp_scanner
DECL|function|qt_x11_clipboard_event_filter
DECL|function|qt_x11_incr_event_filter
DECL|function|qt_xclb_incr_timeout
DECL|function|qt_xfixes_clipboard_changed
DECL|function|qt_xfixes_selection_changed
DECL|function|retrieveData_sys
DECL|function|selectionData
DECL|function|send_selection
DECL|function|send_targets_selection
DECL|function|setMimeData
DECL|function|setSource
DECL|function|setupOwner
DECL|function|source
DECL|function|supportsMode
DECL|function|x11Event
DECL|function|~QClipboardData
DECL|function|~QClipboardINCRTransaction
DECL|function|~QClipboardWatcher
DECL|macro|DEBUG
DECL|macro|DEBUG
DECL|macro|VDEBUG
DECL|macro|VDEBUG
DECL|member|atom
DECL|member|clipboardData
DECL|member|clipboardData
DECL|member|data
DECL|member|format
DECL|member|formatList
DECL|member|format_atoms
DECL|member|increment
DECL|member|mode
DECL|member|offset
DECL|member|property
DECL|member|selectionData
DECL|member|selectionData
DECL|member|target
DECL|member|timestamp
DECL|member|timestamp
DECL|member|window
DECL|struct|qt_init_timestamp_data
DECL|typedef|TransactionMap
DECL|variable|capture_event_type
DECL|variable|capture_event_win
DECL|variable|captured_event
DECL|variable|clipboard_timeout
DECL|variable|clipboard_watcher
DECL|variable|has_captured_event
DECL|variable|incr_timer_id
DECL|variable|internalCbData
DECL|variable|internalSelData
DECL|variable|owner
DECL|variable|pending_clipboard_changed
DECL|variable|pending_selection_changed
DECL|variable|pending_timer_id
DECL|variable|prev_event_filter
DECL|variable|requestor
DECL|variable|selection_watcher
DECL|variable|timer_event_clear
DECL|variable|timer_id
DECL|variable|transactions
DECL|variable|waiting_for_data
