DECL|class|QColormapPrivate
DECL|function|QColormap
DECL|function|QColormap
DECL|function|QColormapPrivate
DECL|function|cleanup
DECL|function|colorAt
DECL|function|colormap
DECL|function|cube_root
DECL|function|depth
DECL|function|find_visual
DECL|function|init_direct
DECL|function|init_gray
DECL|function|init_indexed
DECL|function|initialize
DECL|function|instance
DECL|function|lowest_bit
DECL|function|mode
DECL|function|operator =
DECL|function|pixel
DECL|function|query_colormap
DECL|function|right_align
DECL|function|size
DECL|function|~QColormap
DECL|member|b_max
DECL|member|b_shift
DECL|member|colormap
DECL|member|colors
DECL|member|defaultColormap
DECL|member|defaultVisual
DECL|member|depth
DECL|member|g_max
DECL|member|g_shift
DECL|member|mode
DECL|member|pixels
DECL|member|r_max
DECL|member|r_shift
DECL|member|ref
DECL|member|visual
DECL|variable|cmaps
