DECL|function|DndByteOrder
DECL|function|DndFillClientMessage
DECL|function|DndOperationsToQtDropActions
DECL|function|DndParseClientMessage
DECL|function|DndReadSourceProperty
DECL|function|DndWriteReceiverProperty
DECL|function|MotifWindow
DECL|function|QtDropActionToDndOperation
DECL|function|TargetsTable
DECL|function|_DndIndexToTargets
DECL|function|motifdndEnable
DECL|function|motifdndFormat
DECL|function|motifdndHandle
DECL|function|motifdndObtainData
DECL|macro|BYTE
DECL|macro|CARD16
DECL|macro|CARD32
DECL|macro|DND_CLEAR_EVENT_TYPE
DECL|macro|DND_COMPLETION_MASK
DECL|macro|DND_COMPLETION_SHIFT
DECL|macro|DND_COPY
DECL|macro|DND_DRAG_DROP_ONLY
DECL|macro|DND_DRAG_DROP_ONLY_EQUIV
DECL|macro|DND_DRAG_DYNAMIC
DECL|macro|DND_DRAG_DYNAMIC_EQUIV1
DECL|macro|DND_DRAG_DYNAMIC_EQUIV2
DECL|macro|DND_DRAG_MOTION
DECL|macro|DND_DRAG_NONE
DECL|macro|DND_DROP
DECL|macro|DND_DROP_CANCEL
DECL|macro|DND_DROP_HELP
DECL|macro|DND_DROP_SITE_ENTER
DECL|macro|DND_DROP_SITE_LEAVE
DECL|macro|DND_DROP_START
DECL|macro|DND_EVENT_TYPE_MASK
DECL|macro|DND_EVENT_TYPE_SHIFT
DECL|macro|DND_GET_COMPLETION
DECL|macro|DND_GET_EVENT_TYPE
DECL|macro|DND_GET_OPERATION
DECL|macro|DND_GET_OPERATIONS
DECL|macro|DND_GET_STATUS
DECL|macro|DND_INVALID_DROP_SITE
DECL|macro|DND_LINK
DECL|macro|DND_MOVE
DECL|macro|DND_NOOP
DECL|macro|DND_NO_DROP_SITE
DECL|macro|DND_OPERATIONS_MASK
DECL|macro|DND_OPERATIONS_SHIFT
DECL|macro|DND_OPERATION_CHANGED
DECL|macro|DND_OPERATION_MASK
DECL|macro|DND_OPERATION_SHIFT
DECL|macro|DND_PROTOCOL_VERSION
DECL|macro|DND_SET_COMPLETION
DECL|macro|DND_SET_EVENT_TYPE
DECL|macro|DND_SET_OPERATION
DECL|macro|DND_SET_OPERATIONS
DECL|macro|DND_SET_STATUS
DECL|macro|DND_STATUS_MASK
DECL|macro|DND_STATUS_SHIFT
DECL|macro|DND_TOP_LEVEL_ENTER
DECL|macro|DND_TOP_LEVEL_LEAVE
DECL|macro|DND_VALID_DROP_SITE
DECL|macro|DndIncludeVersion
DECL|macro|DndRevision
DECL|macro|DndVersion
DECL|macro|INT16
DECL|macro|SWAP2BYTES
DECL|macro|SWAP4BYTES
DECL|member|byte_order
DECL|member|byte_order
DECL|member|byte_order
DECL|member|byte_order
DECL|member|completion
DECL|member|data
DECL|member|data_size
DECL|member|entries
DECL|member|flags
DECL|member|num_drop_sites
DECL|member|num_entries
DECL|member|num_target_lists
DECL|member|num_targets
DECL|member|operation
DECL|member|operations
DECL|member|pad1
DECL|member|pad2
DECL|member|pot
DECL|member|property
DECL|member|property
DECL|member|property
DECL|member|protocol_style
DECL|member|protocol_version
DECL|member|protocol_version
DECL|member|protocol_version
DECL|member|proxy_window
DECL|member|reason
DECL|member|reason
DECL|member|selection
DECL|member|src_window
DECL|member|src_window
DECL|member|src_window
DECL|member|status
DECL|member|target_index
DECL|member|targets
DECL|member|time
DECL|member|time
DECL|member|top
DECL|member|total_size
DECL|member|x
DECL|member|x
DECL|member|y
DECL|member|y
DECL|struct|_DndMessage
DECL|struct|_DndPot
DECL|struct|_DndReceiverProp
DECL|struct|_DndSrcProp
DECL|struct|_DndTop
DECL|typedef|DndData
DECL|typedef|DndMessage
DECL|typedef|DndPot
DECL|typedef|DndReceiverProp
DECL|typedef|DndSrcProp
DECL|typedef|DndTargets
DECL|typedef|DndTargetsTable
DECL|typedef|DndTargetsTableEntry
DECL|typedef|DndTargetsTableEntryRec
DECL|typedef|DndTargetsTableRec
DECL|typedef|DndTop
DECL|variable|Dnd_selection
DECL|variable|Dnd_selection_time
DECL|variable|dropWidget
DECL|variable|lastAcceptedAction
DECL|variable|num_src_targets
DECL|variable|sourceWindow
DECL|variable|src_targets
