DECL|class|QXRenderTessellator
DECL|function|QX11PaintEngine
DECL|function|QX11PaintEngine
DECL|function|QXRenderTessellator
DECL|function|addTrap
DECL|function|begin
DECL|function|clipLine
DECL|function|clipPolygon_dev
DECL|function|clipStraightLine
DECL|function|done
DECL|function|drawEllipse
DECL|function|drawEllipse
DECL|function|drawFreetype
DECL|function|drawImage
DECL|function|drawLines
DECL|function|drawLines
DECL|function|drawPath
DECL|function|drawPixmap
DECL|function|drawPoints
DECL|function|drawPoints
DECL|function|drawPolygon
DECL|function|drawRects
DECL|function|drawRects
DECL|function|drawTextItem
DECL|function|drawTiledPixmap
DECL|function|drawXLFD
DECL|function|end
DECL|function|fillPath
DECL|function|fillPolygon_dev
DECL|function|fillPolygon_translated
DECL|function|getPatternFill
DECL|function|handle
DECL|function|init
DECL|function|path_for_glyphs
DECL|function|qpainterOpToXrender
DECL|function|qt_XRenderCompositeTrapezoids
DECL|function|qt_decide_features
DECL|function|qt_getClipRects
DECL|function|qt_patternForAlpha
DECL|function|qt_render_bitmap
DECL|function|qt_x11_drawImage
DECL|function|qt_x11_get_brush_gc
DECL|function|qt_x11_get_pen_gc
DECL|function|resetAdaptedOrigin
DECL|function|setCapStyle
DECL|function|setupAdaptedOrigin
DECL|function|strokePolygon_dev
DECL|function|strokePolygon_translated
DECL|function|supportedRenderHints
DECL|function|systemStateChanged
DECL|function|tessellate
DECL|function|updateBrush
DECL|function|updateClipRegion_dev
DECL|function|updateFont
DECL|function|updateMatrix
DECL|function|updatePen
DECL|function|updateRenderHints
DECL|function|updateState
DECL|function|x11ClearClipRegion
DECL|function|x11SetClipRegion
DECL|function|~QX11PaintEngine
DECL|function|~QXRenderTessellator
DECL|macro|DITHER_SIZE
DECL|macro|X11
DECL|macro|X11
DECL|member|allocated
DECL|member|size
DECL|member|traps
DECL|variable|aliasedCoordinateDelta
DECL|variable|base_dither_matrix
DECL|variable|compositionModeToRenderOp
