DECL|function|QX11AlphaDetector
DECL|function|QX11PlatformPixmap
DECL|function|alphaChannel
DECL|function|bitmapFromImage
DECL|function|bitmap_to_mask
DECL|function|build_scale_table
DECL|function|canTakeQImageFromXImage
DECL|function|cleanup_scale_tables
DECL|function|convertToARGB32
DECL|function|copy
DECL|function|createBitmapFromImage
DECL|function|createCompatiblePlatformPixmap
DECL|function|fill
DECL|function|fromImage
DECL|function|fromX11Pixmap
DECL|function|grabWindow
DECL|function|hasAlpha
DECL|function|hasAlphaChannel
DECL|function|hasXRenderAndAlpha
DECL|function|highest_bit
DECL|function|lowest_bit
DECL|function|mask
DECL|function|mask_to_bitmap
DECL|function|metric
DECL|function|n_bits
DECL|function|paintEngine
DECL|function|qSafeXDestroyImage
DECL|function|qt_cleanup_mitshm
DECL|function|qt_create_mitshm_buffer
DECL|function|qt_renderformat_for_depth
DECL|function|qt_toX11Pixmap
DECL|function|qt_toX11Pixmap
DECL|function|release
DECL|function|resize
DECL|function|scroll
DECL|function|setAlphaChannel
DECL|function|setMask
DECL|function|takeQImageFromXImage
DECL|function|toImage
DECL|function|toImage
DECL|function|toImage
DECL|function|transformed
DECL|function|x11ConvertToDefaultDepth
DECL|function|x11Info
DECL|function|x11PictureHandle
DECL|function|x11SetDefaultScreen
DECL|function|x11SetScreen
DECL|function|~QX11PlatformPixmap
DECL|macro|CYCLE
DECL|macro|GET_PIXEL
DECL|macro|GET_PIXEL_DITHER_TC
DECL|macro|GET_PIXEL_DITHER_TC_OPT
DECL|macro|QT_MITSHM
DECL|macro|for
DECL|member|checked
DECL|member|has
DECL|member|image
DECL|member|xi
DECL|struct|QX11AlphaDetector
DECL|struct|QXImageWrapper
DECL|variable|blue_scale_table
DECL|variable|defaultScreen
DECL|variable|green_scale_table
DECL|variable|qt_pixmap_serial
DECL|variable|qt_x11_preferred_pixmap_depth
DECL|variable|red_scale_table
DECL|variable|xshmimg
DECL|variable|xshminfo
DECL|variable|xshminit
DECL|variable|xshmpm
