DECL|class|MocParser
DECL|function|loadIntData
DECL|function|loadStringData
DECL|function|main
DECL|function|parse
DECL|function|parseCmdLine
DECL|function|parseError
DECL|function|readLine
DECL|function|showHelp
DECL|function|showVersion
DECL|function|~MocParser
DECL|macro|PROGRAMCOPYRIGHT
DECL|macro|PROGRAMNAME
DECL|macro|PROGRAMVERSION
DECL|member|filename
DECL|member|input
DECL|member|lineNumber
DECL|member|objects
DECL|variable|docTypeHeader
DECL|variable|flags
DECL|variable|help
DECL|variable|outputFile
