DECL|class|CustomItem
DECL|class|tst_QStandardItem
DECL|function|CustomItem
DECL|function|CustomItem
DECL|function|appendColumn
DECL|function|appendColumn_data
DECL|function|appendRow
DECL|function|appendRow_data
DECL|function|cleanup
DECL|function|clone
DECL|function|clone
DECL|function|ctor
DECL|function|deleteItem
DECL|function|emitDataChanged
DECL|function|getSetChild
DECL|function|getSetChild_data
DECL|function|getSetData
DECL|function|getSetFlags
DECL|function|getSetRowAndColumnCount
DECL|function|iconTextCtor
DECL|function|init
DECL|function|insertColumn
DECL|function|insertColumn_data
DECL|function|insertColumns
DECL|function|insertColumns_data
DECL|function|insertRow
DECL|function|insertRow_data
DECL|function|insertRows
DECL|function|insertRows_data
DECL|function|operator <
DECL|function|parent
DECL|function|rowsColumnsCtor
DECL|function|sortChildren
DECL|function|streamItem
DECL|function|subclassing
DECL|function|takeChild
DECL|function|takeColumn
DECL|function|takeColumn_data
DECL|function|takeRow
DECL|function|takeRow_data
DECL|function|textCtor
DECL|function|tst_QStandardItem
DECL|function|type
DECL|function|~CustomItem
DECL|function|~tst_QStandardItem
