DECL|macro|WINDOW_H
DECL|variable|QComboBox
DECL|variable|QDataWidgetMapper
DECL|variable|QItemSelectionModel
DECL|variable|QLabel
DECL|variable|QLineEdit
DECL|variable|QPushButton
DECL|variable|QSqlRelationalTableModel
DECL|variable|QStandardItemModel
DECL|variable|QStringListModel
DECL|variable|QTextEdit
