DECL|class|tst_QTransform
DECL|function|assignments
DECL|function|boundingRect
DECL|function|cleanup
DECL|function|controlPointRect
DECL|function|init
DECL|function|inverted
DECL|function|inverted_data
DECL|function|mapEmptyPath
DECL|function|mapInt
DECL|function|mapPathWithPoint
DECL|function|mapRect
DECL|function|mapRect_data
DECL|function|mapToPolygon
DECL|function|mapToPolygon_data
DECL|function|mapping_data
DECL|function|matrix
DECL|function|projectivePathMapping
DECL|function|scalarOps
DECL|function|scale
DECL|function|testOffset
DECL|function|transform
DECL|function|translate
DECL|function|tst_QTransform
DECL|function|types
DECL|function|~tst_QTransform
DECL|macro|M_PI
