DECL|function|Document
DECL|function|Shape
DECL|function|addShape
DECL|function|color
DECL|function|currentShapeName
DECL|function|deleteShape
DECL|function|fileName
DECL|function|gradient
DECL|function|indexAt
DECL|function|indexOf
DECL|function|load
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|name
DECL|function|paintEvent
DECL|function|rect
DECL|function|resizeHandle
DECL|function|save
DECL|function|setCurrentShape
DECL|function|setFileName
DECL|function|setShapeColor
DECL|function|setShapeRect
DECL|function|shape
DECL|function|stringToType
DECL|function|triangle
DECL|function|type
DECL|function|typeToString
DECL|function|undoStack
DECL|function|uniqueName
DECL|variable|resizeHandleWidth
