DECL|class|QBasicKeyEventTransitionPrivate
DECL|function|QBasicKeyEventTransition
DECL|function|QBasicKeyEventTransition
DECL|function|QBasicKeyEventTransition
DECL|function|QBasicKeyEventTransitionPrivate
DECL|function|eventTest
DECL|function|eventType
DECL|function|get
DECL|function|key
DECL|function|modifierMask
DECL|function|onTransition
DECL|function|setEventType
DECL|function|setKey
DECL|function|setModifierMask
DECL|function|~QBasicKeyEventTransition
DECL|member|eventType
DECL|member|key
DECL|member|modifierMask
