DECL|class|LanguageTestStateMachine
DECL|class|TransformTranslator
DECL|class|tst_languageChange
DECL|enumerator|CloseDialog
DECL|enumerator|ColorDialog
DECL|enumerator|FileDialog
DECL|enumerator|InputDialog
DECL|enumerator|InstallTranslator
DECL|enum|DialogType
DECL|enum|State
DECL|function|LanguageTestStateMachine
DECL|function|TransformTranslator
DECL|function|TransformTranslator
DECL|function|cleanupTestCase
DECL|function|initTestCase
DECL|function|isEmpty
DECL|function|retranslatability
DECL|function|retranslatability_data
DECL|function|start
DECL|function|timeout
DECL|function|translate
DECL|function|tst_languageChange
DECL|member|m_state
DECL|member|m_timer
DECL|member|m_translations
DECL|member|m_translator
DECL|typedef|TranslationSet
