DECL|class|KeyMap
DECL|class|QDirectFBKeyboardHandlerPrivate
DECL|function|KeyMap
DECL|function|QDirectFBKeyboardHandler
DECL|function|QDirectFBKeyboardHandlerPrivate
DECL|function|readKeyboardData
DECL|function|resume
DECL|function|suspend
DECL|function|~QDirectFBKeyboardHandler
DECL|function|~QDirectFBKeyboardHandlerPrivate
DECL|member|bytesRead
DECL|member|event
DECL|member|eventBuffer
DECL|member|handler
DECL|member|keyboardNotifier
DECL|member|lastKeycode
DECL|member|lastModifiers
DECL|member|lastUnicode
