DECL|class|QDirectFBPaintEnginePrivate
DECL|class|SurfaceCache
DECL|enumerator|ALL
DECL|enumerator|ClipUnset
DECL|enumerator|ComplexClip
DECL|enumerator|DRAW_COLORSPANS
DECL|enumerator|DRAW_ELLIPSE
DECL|enumerator|DRAW_IMAGE
DECL|enumerator|DRAW_LINES
DECL|enumerator|DRAW_PATH
DECL|enumerator|DRAW_PIXMAP
DECL|enumerator|DRAW_POINTS
DECL|enumerator|DRAW_POLYGON
DECL|enumerator|DRAW_RECTS
DECL|enumerator|DRAW_ROUNDED_RECT
DECL|enumerator|DRAW_STATICTEXT
DECL|enumerator|DRAW_TEXT
DECL|enumerator|DRAW_TILED_PIXMAP
DECL|enumerator|FILL_PATH
DECL|enumerator|FILL_RECT
DECL|enumerator|HasAlpha
DECL|enumerator|Matrix_BlitsUnsupported
DECL|enumerator|Matrix_NegativeScale
DECL|enumerator|Matrix_RectsUnsupported
DECL|enumerator|NoClip
DECL|enumerator|PorterDuff_AlwaysBlend
DECL|enumerator|PorterDuff_None
DECL|enumerator|PorterDuff_PremultiplyColors
DECL|enumerator|PorterDuff_Supported
DECL|enumerator|Premultiplied
DECL|enumerator|RasterDisable
DECL|enumerator|RasterWarn
DECL|enumerator|RectClip
DECL|enumerator|RegionClip
DECL|enumerator|STROKE_PATH
DECL|enum|BlitFlag
DECL|enum|ClipType
DECL|enum|CompositionModeStatus
DECL|enum|PaintOperation
DECL|enum|TransformationTypeFlags
DECL|function|ALPHA_MUL
DECL|function|QDirectFBPaintEngine
DECL|function|QDirectFBPaintEnginePrivate
DECL|function|SurfaceCache
DECL|function|begin
DECL|function|blit
DECL|function|cacheCost
DECL|function|cachedImageCleanupHook
DECL|function|clear
DECL|function|clip
DECL|function|clip
DECL|function|clip
DECL|function|clipEnabledChanged
DECL|function|compositionModeChanged
DECL|function|drawBufferSpan
DECL|function|drawEllipse
DECL|function|drawImage
DECL|function|drawImage
DECL|function|drawLines
DECL|function|drawLines
DECL|function|drawLines
DECL|function|drawPath
DECL|function|drawPixmap
DECL|function|drawPixmap
DECL|function|drawPoints
DECL|function|drawPoints
DECL|function|drawPolygon
DECL|function|drawPolygon
DECL|function|drawRects
DECL|function|drawRects
DECL|function|drawRects
DECL|function|drawRoundedRect
DECL|function|drawStaticTextItem
DECL|function|drawTextItem
DECL|function|drawTiledPixmap
DECL|function|drawTiledPixmap
DECL|function|end
DECL|function|fill
DECL|function|fillRect
DECL|function|fillRect
DECL|function|fillRects
DECL|function|fixCoord
DECL|function|getSurface
DECL|function|getSurface
DECL|function|getTransformationType
DECL|function|initImageCache
DECL|function|isSimpleBrush
DECL|function|lock
DECL|function|map
DECL|function|map
DECL|function|mapRect
DECL|function|mapRect
DECL|function|opacityChanged
DECL|function|penChanged
DECL|function|prepareForBlit
DECL|function|ptr
DECL|function|ptr
DECL|function|rasterFallbackWarn
DECL|function|rasterFallbacksMask
DECL|function|renderHintsChanged
DECL|function|setCompositionMode
DECL|function|setDFBColor
DECL|function|setPen
DECL|function|setRenderHints
DECL|function|setState
DECL|function|setTransform
DECL|function|stroke
DECL|function|supportsStretchBlit
DECL|function|systemStateChanged
DECL|function|transformChanged
DECL|function|unlock
DECL|function|unlock
DECL|function|updateClip
DECL|function|~CachedImage
DECL|function|~QDirectFBPaintEngine
DECL|function|~QDirectFBPaintEnginePrivate
DECL|function|~SurfaceCache
DECL|macro|CLIPPED_PAINT
DECL|macro|RASTERFALLBACK
DECL|macro|VOID_ARG
DECL|member|antialiased
DECL|member|buffer
DECL|member|bufsize
DECL|member|clipType
DECL|member|compositionModeStatus
DECL|member|currentClip
DECL|member|dfbDevice
DECL|member|fb
DECL|member|inClip
DECL|member|isPremultiplied
DECL|member|opacity
DECL|member|q
DECL|member|simplePen
DECL|member|surface
DECL|member|surface
DECL|member|surface
DECL|member|surfaceCache
DECL|member|transformationType
DECL|struct|CachedImage
