DECL|function|QDirectFBWindowSurface
DECL|function|QDirectFBWindowSurface
DECL|function|beginPaint
DECL|function|createWindow
DECL|function|directFBSurface
DECL|function|directFBWindow
DECL|function|endPaint
DECL|function|flush
DECL|function|isValid
DECL|function|move
DECL|function|permanentState
DECL|function|raise
DECL|function|releaseSurface
DECL|function|scroll
DECL|function|setGeometry
DECL|function|setOpaque
DECL|function|setPermanentState
DECL|function|setWindowGeometry
DECL|function|surfaceForWidget
DECL|function|updateIsOpaque
DECL|function|~QDirectFBWindowSurface
