DECL|class|QDirectFBScreenCursor
DECL|class|QDirectFBScreenPrivate
DECL|function|PaintCommand
DECL|function|QDirectFBScreen
DECL|function|QDirectFBScreenCursor
DECL|function|QDirectFBScreenPrivate
DECL|function|alphaPixmapFormat
DECL|function|blank
DECL|function|clearRect
DECL|function|colorFromName
DECL|function|connect
DECL|function|copyDFBSurface
DECL|function|createDFBSurface
DECL|function|createDFBSurface
DECL|function|createDFBSurface
DECL|function|createPixmapData
DECL|function|createSurface
DECL|function|createSurface
DECL|function|createWindow
DECL|function|depth
DECL|function|depth
DECL|function|dfb
DECL|function|dfbDisplayLayer
DECL|function|directFBFlags
DECL|function|disconnect
DECL|function|exposeRegion
DECL|function|flagDescriptions
DECL|function|flipSurface
DECL|function|getImageFormat
DECL|function|getSubSurface
DECL|function|getSurfaceDescription
DECL|function|getSurfacePixelFormat
DECL|function|hide
DECL|function|initDevice
DECL|function|initParameters
DECL|function|initSurfaceDescriptionPixelFormat
DECL|function|instance
DECL|function|isFullUpdate
DECL|function|lockSurface
DECL|function|move
DECL|function|onWindowEvent
DECL|function|primarySurface
DECL|function|printDirectFBInfo
DECL|function|qt_directfb_subsurface_for_widget
DECL|function|qt_directfb_surface_for_widget
DECL|function|qt_directfb_window_for_widget
DECL|function|releaseDFBSurface
DECL|function|set
DECL|function|setDirectFBImageProvider
DECL|function|setFlipFlags
DECL|function|setIntOption
DECL|function|setMode
DECL|function|setSurfaceColorTable
DECL|function|show
DECL|function|shutdownDevice
DECL|function|solidFill
DECL|function|solidFill
DECL|function|subSurfaceForWidget
DECL|function|surfaceForWidget
DECL|function|waitIdle
DECL|function|windowForWidget
DECL|function|~QDirectFBScreen
DECL|function|~QDirectFBScreenCursor
DECL|function|~QDirectFBScreenPrivate
DECL|member|allocatedSurfaces
DECL|member|alphaPixmapFormat
DECL|member|backgroundColor
DECL|member|blittingFlags
DECL|member|cursorImageKey
DECL|member|cursorSurface
DECL|member|dfb
DECL|member|dfbLayer
DECL|member|dfbScreen
DECL|member|dfbSurface
DECL|member|directFBFlags
DECL|member|flag
DECL|member|flipFlags
DECL|member|image
DECL|member|imageProvider
DECL|member|instance
DECL|member|instance
DECL|member|keyboard
DECL|member|layer
DECL|member|mouse
DECL|member|name
DECL|member|primarySurface
DECL|member|q
DECL|member|source
DECL|member|window
DECL|member|windowOpacity
DECL|member|windowPosition
DECL|struct|FlagDescription
DECL|struct|PaintCommand
DECL|variable|accelerationDescriptions
DECL|variable|accelerationDescriptions
DECL|variable|blitDescriptions
DECL|variable|blitDescriptions
DECL|variable|drawDescriptions
DECL|variable|drawDescriptions
