DECL|class|QDirectFBPointer
DECL|function|QDirectFBPixmapData
DECL|function|QDirectFBPointer
DECL|function|buffer
DECL|function|checkForAlphaPixels
DECL|function|cleanup
DECL|function|copy
DECL|function|fill
DECL|function|fromData
DECL|function|fromDataBufferDescription
DECL|function|fromFile
DECL|function|fromImage
DECL|function|hasAlphaChannel
DECL|function|invalidate
DECL|function|isOpaqueFormat
DECL|function|paintEngine
DECL|function|qt_directfb_surface_for_pixmap
DECL|function|resize
DECL|function|scroll
DECL|function|toImage
DECL|function|transformed
DECL|function|~QDirectFBPixmapData
DECL|struct|QDirectFBInterfaceCleanupHandler
DECL|variable|global_ser_no
