DECL|class|QDirectFBMouseHandlerPrivate
DECL|function|QDirectFBMouseHandler
DECL|function|QDirectFBMouseHandlerPrivate
DECL|function|readMouseData
DECL|function|resume
DECL|function|setEnabled
DECL|function|suspend
DECL|function|~QDirectFBMouseHandler
DECL|function|~QDirectFBMouseHandlerPrivate
DECL|member|bytesRead
DECL|member|event
DECL|member|eventBuffer
DECL|member|handler
DECL|member|layer
DECL|member|mouseNotifier
DECL|member|prevPoint
DECL|member|prevbuttons
