DECL|function|QDirectFBPaintDevice
DECL|function|bytesPerLine
DECL|function|directFBSurface
DECL|function|format
DECL|function|lockSurface
DECL|function|memory
DECL|function|metric
DECL|function|paintEngine
DECL|function|releaseSubSurface
DECL|function|size
DECL|function|unlockSurface
DECL|function|~QDirectFBPaintDevice
