DECL|function|AddressBook
DECL|function|addContact
DECL|function|cancel
DECL|function|editContact
DECL|function|findContact
DECL|function|next
DECL|function|previous
DECL|function|removeContact
DECL|function|submitContact
DECL|function|updateInterface
