DECL|class|QEglKmsHooks
DECL|class|QKmsCursor
DECL|function|CursorAtlas
DECL|function|FrameBuffer
DECL|function|QEglKmsHooks
DECL|function|QKmsCursor
DECL|function|changeCursor
DECL|function|createCursor
DECL|function|createNativeWindow
DECL|function|destroyNativeWindow
DECL|function|framebufferForBufferObject
DECL|function|gbm_bo_destroyed_callback
DECL|function|hasCapability
DECL|function|initCursorAtlas
DECL|function|page_flip_handler
DECL|function|physicalScreenSize
DECL|function|platformDestroy
DECL|function|platformDisplay
DECL|function|platformInit
DECL|function|pointerEvent
DECL|function|pos
DECL|function|presentBuffer
DECL|function|screenDepth
DECL|function|screenSize
DECL|function|setPos
DECL|function|setup_kms
DECL|function|surfaceFormatFor
DECL|function|~QKmsCursor
DECL|member|Q_DECL_OVERRIDE
DECL|member|Q_DECL_OVERRIDE
DECL|member|Q_DECL_OVERRIDE
DECL|member|Q_DECL_OVERRIDE
DECL|member|Q_DECL_OVERRIDE
DECL|member|Q_DECL_OVERRIDE
DECL|member|Q_DECL_OVERRIDE
DECL|member|Q_DECL_OVERRIDE
DECL|member|Q_DECL_OVERRIDE
DECL|member|Q_DECL_OVERRIDE
DECL|member|Q_DECL_OVERRIDE
DECL|member|Q_DECL_OVERRIDE
DECL|member|Q_DECL_OVERRIDE
DECL|member|Q_DECL_OVERRIDE
DECL|member|Q_DECL_OVERRIDE
DECL|member|Q_DECL_OVERRIDE
DECL|member|cursorHeight
DECL|member|cursorWidth
DECL|member|cursorsPerRow
DECL|member|fb
DECL|member|height
DECL|member|hotSpots
DECL|member|image
DECL|member|m_bo
DECL|member|m_crtc
DECL|member|m_cursorAtlas
DECL|member|m_cursorImage
DECL|member|m_device
DECL|member|m_dri_fd
DECL|member|m_dri_fd
DECL|member|m_drm_connector
DECL|member|m_drm_crtc
DECL|member|m_drm_encoder
DECL|member|m_drm_mode
DECL|member|m_gbm_device
DECL|member|m_gbm_device
DECL|member|m_gbm_surface
DECL|member|m_pos
DECL|member|m_visible
DECL|member|width
DECL|struct|CursorAtlas
DECL|struct|FrameBuffer
DECL|variable|kms_hooks
DECL|variable|platformHooks
