DECL|class|CursorUpdateEvent
DECL|function|CursorUpdateEvent
DECL|function|QEglFSCursor
DECL|function|changeCursor
DECL|function|createCursorTexture
DECL|function|createShaderPrograms
DECL|function|cursorRect
DECL|function|draw
DECL|function|event
DECL|function|hasMouse
DECL|function|initCursorAtlas
DECL|function|onDeviceListChanged
DECL|function|paintOnScreen
DECL|function|pointerEvent
DECL|function|pos
DECL|function|pos
DECL|function|region
DECL|function|resetResources
DECL|function|setCurrentCursor
DECL|function|setPos
DECL|function|update
DECL|function|updateMouseStatus
DECL|function|~QEglFSCursor
DECL|member|m_pos
DECL|member|m_region
