DECL|function|createNativeWindow
DECL|function|destroyNativeWindow
DECL|function|hasCapability
DECL|function|platformDestroy
DECL|function|platformDisplay
DECL|function|platformInit
DECL|function|screenSize
DECL|variable|display
DECL|variable|platform_hooks
