DECL|function|createCursor
DECL|function|createNativeWindow
DECL|function|destroyNativeWindow
DECL|function|filterConfig
DECL|function|hasCapability
DECL|function|platformDestroy
DECL|function|platformDisplay
DECL|function|platformInit
DECL|function|screenDepth
DECL|function|screenFormat
DECL|function|screenSize
DECL|function|surfaceFormatFor
DECL|variable|stubHooks
