DECL|function|QEglFSContext
DECL|function|createTemporaryOffscreenSurface
DECL|function|destroyTemporaryOffscreenSurface
DECL|function|eglSurfaceForPlatformSurface
DECL|function|runGLChecks
DECL|function|swapBuffers
