DECL|function|createCursor
DECL|function|createNativeOffscreenWindow
DECL|function|createNativeWindow
DECL|function|destroyNativeWindow
DECL|function|fbDeviceName
DECL|function|filterConfig
DECL|function|framebufferIndex
DECL|function|hasCapability
DECL|function|logicalDpi
DECL|function|nativeOrientation
DECL|function|orientation
DECL|function|physicalScreenSize
DECL|function|platformDestroy
DECL|function|platformDisplay
DECL|function|platformInit
DECL|function|presentBuffer
DECL|function|screenDepth
DECL|function|screenFormat
DECL|function|screenSize
DECL|function|supportsPBuffers
DECL|function|surfaceFormatFor
DECL|function|waitForVSync
DECL|variable|framebuffer
DECL|variable|stubHooks
