DECL|class|EventReader
DECL|class|QEglFSX11Hooks
DECL|function|EventReader
DECL|function|QEglFSX11Hooks
DECL|function|connection
DECL|function|createNativeWindow
DECL|function|destroyNativeWindow
DECL|function|hasCapability
DECL|function|platformDestroy
DECL|function|platformDisplay
DECL|function|platformInit
DECL|function|run
DECL|function|screenSize
DECL|function|sendConnectionEvent
DECL|function|translateMouseButton
DECL|function|translateMouseButtons
DECL|member|m_connection
DECL|member|m_connection
DECL|member|m_connectionEventListener
DECL|member|m_eventReader
DECL|variable|display
DECL|variable|eglFSX11Hooks
DECL|variable|platformHooks
DECL|variable|running
