DECL|function|QEglFSIntegration
DECL|function|createEventDispatcher
DECL|function|createPlatformBackingStore
DECL|function|createPlatformGLContext
DECL|function|createPlatformWindow
DECL|function|fontDatabase
DECL|function|hasCapability
