DECL|function|QEglFSScreen
DECL|function|cursor
DECL|function|depth
DECL|function|format
DECL|function|geometry
DECL|function|logicalDpi
DECL|function|physicalSize
DECL|function|setPrimarySurface
DECL|function|~QEglFSScreen
