DECL|function|create
DECL|function|createCursor
DECL|function|createDisplay
DECL|function|createNativeOffscreenWindow
DECL|function|createNativeWindow
DECL|function|createWindow
DECL|function|destroyNativeWindow
DECL|function|fbDeviceName
DECL|function|filterConfig
DECL|function|framebufferIndex
DECL|function|hasCapability
DECL|function|keys
DECL|function|logicalDpi
DECL|function|nativeOrientation
DECL|function|orientation
DECL|function|physicalScreenSize
DECL|function|pixelDensity
DECL|function|platformDestroy
DECL|function|platformDisplay
DECL|function|platformInit
DECL|function|presentBuffer
DECL|function|refreshRate
DECL|function|screenDepth
DECL|function|screenDestroy
DECL|function|screenFormat
DECL|function|screenInit
DECL|function|screenSize
DECL|function|supportsPBuffers
DECL|function|supportsSurfacelessContexts
DECL|function|surfaceFormatFor
DECL|function|surfaceType
DECL|function|usesDefaultScreen
DECL|function|waitForVSync
DECL|function|wlDisplay
DECL|variable|framebuffer
