DECL|class|QEglFSContext
DECL|function|QEglFSContext
DECL|function|QEglFSScreen
DECL|function|createAndSetPlatformContext
DECL|function|createAndSetPlatformContext
DECL|function|cursor
DECL|function|depth
DECL|function|eglSurfaceForPlatformSurface
DECL|function|format
DECL|function|geometry
DECL|function|platformContext
DECL|function|swapBuffers
DECL|function|~QEglFSScreen
DECL|member|attr
DECL|member|name
DECL|struct|AttrInfo
DECL|variable|attrs
