DECL|function|QEglFSCompositor
DECL|function|destroy
DECL|function|ensureProgram
DECL|function|instance
DECL|function|render
DECL|function|renderAll
DECL|function|schedule
DECL|function|~QEglFSCompositor
DECL|variable|compositor
