DECL|function|QEglFSCursor
DECL|function|changeCursor
DECL|function|createCursorTexture
DECL|function|createProgram
DECL|function|createShader
DECL|function|createShaderPrograms
DECL|function|cursorRect
DECL|function|initCursorAtlas
DECL|function|pointerEvent
DECL|function|pos
DECL|function|render
DECL|function|setPos
DECL|function|~QEglFSCursor
