DECL|function|QEglFSScreen
DECL|function|addWindow
DECL|function|changeWindowIndex
DECL|function|cursor
DECL|function|depth
DECL|function|format
DECL|function|geometry
DECL|function|logicalDpi
DECL|function|moveToTop
DECL|function|nativeOrientation
DECL|function|orientation
DECL|function|physicalSize
DECL|function|removeWindow
DECL|function|rootWindow
DECL|function|setPrimarySurface
DECL|function|~QEglFSScreen
