DECL|function|QEglFSCursor
DECL|function|changeCursor
DECL|function|createCursorTexture
DECL|function|createProgram
DECL|function|createShader
DECL|function|createShaderPrograms
DECL|function|cursorRect
DECL|function|draw
DECL|function|initCursorAtlas
DECL|function|paintOnScreen
DECL|function|pointerEvent
DECL|function|pos
DECL|function|resetResources
DECL|function|setCurrentCursor
DECL|function|setPos
DECL|function|update
DECL|function|~QEglFSCursor
