DECL|function|compileSource
DECL|function|getLocations
DECL|function|getVariables
DECL|function|getWord
DECL|function|main
DECL|function|readConf
DECL|function|readSourceFile
DECL|function|toInt
DECL|function|trimmed
DECL|function|writeIncludeFile
DECL|function|writeTypesEnum
DECL|function|writeVariablesEnum
DECL|macro|TAB
DECL|typedef|QStringPair
