DECL|class|QIBusPlatformInputContextPrivate
DECL|function|QIBusPlatformInputContext
DECL|function|QIBusPlatformInputContextPrivate
DECL|function|commitText
DECL|function|createConnection
DECL|function|isValid
DECL|function|mouseHandler
DECL|function|reset
DECL|function|setFocusObject
DECL|function|update
DECL|function|updatePreeditText
DECL|function|x11FilterEvent
DECL|function|~QIBusPlatformInputContext
DECL|function|~QIBusPlatformInputContextPrivate
DECL|member|bus
DECL|member|connection
DECL|member|context
DECL|member|valid
DECL|variable|keycode_table
