DECL|class|tst_MakeTestSelfTest
DECL|enumerator|Flat
DECL|enumerator|Recursive
DECL|enum|FindSubdirsMode
DECL|function|find_subdirs
DECL|function|find_test_class
DECL|function|format_list
DECL|function|looks_like_subdirs
DECL|function|looks_like_testcase
DECL|function|make_check
DECL|function|naming_convention
DECL|function|naming_convention_data
DECL|function|tests_pro_files
DECL|function|tests_pro_files_data
DECL|member|all_test_classes
