DECL|function|ConnectionWidget
DECL|function|currentDatabase
DECL|function|on_tree_currentItemChanged
DECL|function|on_tree_itemActivated
DECL|function|qDBCaption
DECL|function|qSetBold
DECL|function|refresh
DECL|function|setActive
DECL|function|showMetaData
DECL|function|~ConnectionWidget
