DECL|function|QWindowsGuiEventDispatcher
DECL|function|messageDebugEntry
DECL|function|processEvents
DECL|function|sendPostedEvents
DECL|function|windowsMessageName
DECL|member|description
DECL|member|interesting
DECL|member|message
DECL|struct|MessageDebugEntry
DECL|variable|messageDebugEntries
