DECL|class|ScreenPropertyWatcher
DECL|class|ScreenWatcherMainWindow
DECL|function|ScreenPropertyWatcher
DECL|function|ScreenWatcherMainWindow
DECL|function|event
DECL|function|main
DECL|function|msgScreenChange
DECL|function|screenAdded
DECL|function|screenRemoved
DECL|function|screenSubject
DECL|function|screenSubject
DECL|function|setScreenSubject
DECL|function|updateSiblings
DECL|member|Q_DECL_OVERRIDE
DECL|member|m_annotation
DECL|member|m_watcher
DECL|variable|i
