DECL|class|tst_QPoint
DECL|enumerator|Double
DECL|enumerator|Float
DECL|enumerator|Int
DECL|enum|PrimitiveType
DECL|function|dotProduct
DECL|function|dotProduct_data
DECL|function|getSet
DECL|function|getSet_data
DECL|function|isNull
DECL|function|manhattanLength
DECL|function|manhattanLength_data
DECL|function|multiplyTest
DECL|function|operator_add
DECL|function|operator_add_data
DECL|function|operator_divide
DECL|function|operator_divide_data
DECL|function|operator_eq
DECL|function|operator_eq_data
DECL|function|operator_multiply
DECL|function|operator_multiply_data
DECL|function|operator_subtract
DECL|function|operator_subtract_data
DECL|function|operator_unary_minus
DECL|function|operator_unary_minus_data
DECL|function|operator_unary_plus
DECL|function|operator_unary_plus_data
DECL|function|rx
DECL|function|ry
DECL|function|stream
DECL|function|stream_data
