DECL|class|tst_Cmptest
DECL|function|boolfunc
DECL|function|boolfunc2
DECL|function|compareQImages
DECL|function|compareQImages_data
DECL|function|compareQListDouble
DECL|function|compareQListInt
DECL|function|compareQPixmaps
DECL|function|compareQPixmaps_data
DECL|function|compareQStringLists
DECL|function|compareQStringLists_data
DECL|function|compare_boolfuncs
DECL|function|compare_pointerfuncs
DECL|function|compare_tostring
DECL|function|compare_tostring_data
DECL|function|intptr
DECL|member|i
DECL|struct|PhonyClass
DECL|variable|i
DECL|variable|xpmPixmapData1
DECL|variable|xpmPixmapData2
DECL|variable|xpmPixmapData3
