DECL|class|QGLDefaultExtensions
DECL|class|QGLDefaultOverlayFormat
DECL|function|QGLContext
DECL|function|QGLContext
DECL|function|QGLContextGroup
DECL|function|QGLContextGroupList
DECL|function|QGLContextPrivate
DECL|function|QGLDefaultExtensions
DECL|function|QGLDefaultOverlayFormat
DECL|function|QGLExtensionMatcher
DECL|function|QGLExtensionMatcher
DECL|function|QGLFormat
DECL|function|QGLFormat
DECL|function|QGLFormat
DECL|function|QGLTextureCache
DECL|function|QGLWidget
DECL|function|QGLWidget
DECL|function|QGLWidget
DECL|function|QGLWidget
DECL|function|accumBufferSize
DECL|function|addShare
DECL|function|alphaBufferSize
DECL|function|append
DECL|function|areSharing
DECL|function|autoBufferSwap
DECL|function|bindCompressedTexture
DECL|function|bindCompressedTexture
DECL|function|bindCompressedTextureDDS
DECL|function|bindCompressedTexturePVR
DECL|function|bindTexture
DECL|function|bindTexture
DECL|function|bindTexture
DECL|function|bindTexture
DECL|function|bindTexture
DECL|function|bindTexture
DECL|function|bindTexture
DECL|function|bindTexture
DECL|function|bindTexture
DECL|function|bindTexture
DECL|function|bindTexture
DECL|function|bindTexture
DECL|function|bindTexture
DECL|function|blueBufferSize
DECL|function|canBindCompressedTexture
DECL|function|cleanup
DECL|function|cleanupBeforePixmapDestruction
DECL|function|cleanupTexturesForCacheKey
DECL|function|cleanupTexturesForPixampData
DECL|function|context
DECL|function|convertFromGLImage
DECL|function|convertToGLFormat
DECL|function|convertToGLFormatHelper
DECL|function|create
DECL|function|currentContext
DECL|function|currentContextExtensions
DECL|function|defaultFormat
DECL|function|defaultOverlayFormat
DECL|function|deleteTexture
DECL|function|deleteTexture
DECL|function|depthBufferSize
DECL|function|detach
DECL|function|device
DECL|function|deviceIsPixmap
DECL|function|doneCurrent
DECL|function|doubleBuffer
DECL|function|drawTexture
DECL|function|drawTexture
DECL|function|drawTexture
DECL|function|drawTexture
DECL|function|extensionFuncs
DECL|function|format
DECL|function|format
DECL|function|functions
DECL|function|glDraw
DECL|function|glExtensions
DECL|function|glInit
DECL|function|grabFrameBuffer
DECL|function|greenBufferSize
DECL|function|init
DECL|function|init
DECL|function|initContext
DECL|function|initializeGL
DECL|function|initializeOverlayGL
DECL|function|initialized
DECL|function|insert
DECL|function|instance
DECL|function|instance
DECL|function|isSharing
DECL|function|isSharing
DECL|function|isValid
DECL|function|isValid
DECL|function|majorVersion
DECL|function|makeCurrent
DECL|function|maxTextureSize
DECL|function|minorVersion
DECL|function|moveToThread
DECL|function|openGLVersionFlags
DECL|function|operator !=
DECL|function|operator <<
DECL|function|operator =
DECL|function|operator ==
DECL|function|paintEngine
DECL|function|paintEvent
DECL|function|paintGL
DECL|function|paintOverlayGL
DECL|function|plane
DECL|function|profile
DECL|function|qDrawTextureRect
DECL|function|qOpenGLVersionFlagsFromString
DECL|function|qglClearColor
DECL|function|qglColor
DECL|function|qgl_byteSwapImage
DECL|function|qgluProject
DECL|function|qt_add_rect_to_array
DECL|function|qt_add_texcoords_to_array
DECL|function|qt_gl_convertToGLFormatHelper
DECL|function|qt_gl_draw_text
DECL|function|qt_gl_library_name
DECL|function|qt_gl_read_framebuffer
DECL|function|qt_gl_read_texture
DECL|function|qt_gl_transfer_context
DECL|function|qt_next_power_of_two
DECL|function|qt_qgl_paint_engine
DECL|function|qt_restore_gl_state
DECL|function|qt_save_gl_state
DECL|function|qt_set_gl_library_name
DECL|function|redBufferSize
DECL|function|remove
DECL|function|remove
DECL|function|remove
DECL|function|removeContextTextures
DECL|function|removeShare
DECL|function|renderPixmap
DECL|function|renderText
DECL|function|renderText
DECL|function|requestedFormat
DECL|function|resizeGL
DECL|function|resizeOverlayGL
DECL|function|samples
DECL|function|setAccum
DECL|function|setAccumBufferSize
DECL|function|setAlpha
DECL|function|setAlphaBufferSize
DECL|function|setAutoBufferSwap
DECL|function|setBlueBufferSize
DECL|function|setCurrentContext
DECL|function|setDefaultFormat
DECL|function|setDefaultOverlayFormat
DECL|function|setDepth
DECL|function|setDepthBufferSize
DECL|function|setDevice
DECL|function|setDirectRendering
DECL|function|setDoubleBuffer
DECL|function|setFormat
DECL|function|setFormat
DECL|function|setGreenBufferSize
DECL|function|setInitialized
DECL|function|setOption
DECL|function|setOverlay
DECL|function|setPlane
DECL|function|setProfile
DECL|function|setRedBufferSize
DECL|function|setRgba
DECL|function|setSampleBuffers
DECL|function|setSamples
DECL|function|setStencil
DECL|function|setStencilBufferSize
DECL|function|setStereo
DECL|function|setSwapInterval
DECL|function|setTextureCacheLimit
DECL|function|setValid
DECL|function|setVersion
DECL|function|setVertexAttribArrayEnabled
DECL|function|setWindowCreated
DECL|function|stencilBufferSize
DECL|function|swapBuffers
DECL|function|swapInterval
DECL|function|swapRegion
DECL|function|syncGlState
DECL|function|testOption
DECL|function|textureCacheLimit
DECL|function|textureCacheLookup
DECL|function|transform_point
DECL|function|updateGL
DECL|function|windowCreated
DECL|function|~QGLContext
DECL|function|~QGLContextGroup
DECL|function|~QGLContextPrivate
DECL|function|~QGLFormat
DECL|function|~QGLTextureCache
DECL|function|~QGLThreadContext
DECL|function|~QGLWidget
DECL|macro|FOURCC_DXT1
DECL|macro|FOURCC_DXT2
DECL|macro|FOURCC_DXT3
DECL|macro|FOURCC_DXT4
DECL|macro|FOURCC_DXT5
DECL|macro|GL_COMPRESSED_RGBA_PVRTC_2BPPV1_IMG
DECL|macro|GL_COMPRESSED_RGBA_PVRTC_4BPPV1_IMG
DECL|macro|GL_COMPRESSED_RGBA_S3TC_DXT1_EXT
DECL|macro|GL_COMPRESSED_RGBA_S3TC_DXT3_EXT
DECL|macro|GL_COMPRESSED_RGBA_S3TC_DXT5_EXT
DECL|macro|GL_COMPRESSED_RGB_PVRTC_2BPPV1_IMG
DECL|macro|GL_COMPRESSED_RGB_PVRTC_4BPPV1_IMG
DECL|macro|GL_COMPRESSED_RGB_S3TC_DXT1_EXT
DECL|macro|GL_ETC1_RGB8_OES
DECL|macro|GL_FRAMEBUFFER_SRGB_CAPABLE_EXT
DECL|macro|GL_GENERATE_MIPMAP_HINT_SGIS
DECL|macro|GL_GENERATE_MIPMAP_SGIS
DECL|macro|GL_NUM_EXTENSIONS
DECL|macro|GL_UNSIGNED_INT_8_8_8_8_REV
DECL|macro|M
DECL|macro|M
DECL|macro|PVR_ALPHA_IN_TEXTURE
DECL|macro|PVR_BORDER_ADDED
DECL|macro|PVR_CUBE_MAP
DECL|macro|PVR_FALSE_COLOR_MIPMAPS
DECL|macro|PVR_FORMAT_ETC1
DECL|macro|PVR_FORMAT_MASK
DECL|macro|PVR_FORMAT_PVRTC2
DECL|macro|PVR_FORMAT_PVRTC4
DECL|macro|PVR_HAS_MIPMAPS
DECL|macro|PVR_MAGIC
DECL|macro|PVR_NORMAL_MAP
DECL|macro|PVR_TWIDDLED
DECL|macro|PVR_VERTICAL_FLIP
DECL|macro|PVR_VOLUME_TEXTURE
DECL|macro|ctx
DECL|macro|ctx
DECL|macro|ctx
DECL|macro|ctx
DECL|member|alphaMask
DECL|member|bitsPerPixel
DECL|member|blueMask
DECL|member|context
DECL|member|currentCtx
DECL|member|dataSize
DECL|member|ddsPixelFormat
DECL|member|dummy1
DECL|member|dummy2
DECL|member|dummy3
DECL|member|dummy4
DECL|member|dwFlags
DECL|member|dwFourCC
DECL|member|dwHeight
DECL|member|dwLinearSize
DECL|member|dwMipMapCount
DECL|member|dwSize
DECL|member|dwWidth
DECL|member|extensions
DECL|member|flags
DECL|member|greenMask
DECL|member|headerSize
DECL|member|height
DECL|member|m_list
DECL|member|m_mutex
DECL|member|magic
DECL|member|mipMapCount
DECL|member|qt_extensionFuncs
DECL|member|redMask
DECL|member|surfaceCount
DECL|member|width
DECL|struct|DDSFormat
DECL|struct|PvrHeader
DECL|struct|QGLContextGroupList
DECL|struct|QGLThreadContext
DECL|typedef|qt_glGetStringi
