DECL|function|accum
DECL|function|alpha
DECL|function|depth
DECL|function|directRendering
DECL|function|doubleBuffer
DECL|function|hasOverlay
DECL|function|rgba
DECL|function|sampleBuffers
DECL|function|stencil
DECL|function|stereo
DECL|macro|GL_DOUBLE
DECL|macro|QGL_H
DECL|typedef|GLdouble
DECL|variable|QGLContextPrivate
DECL|variable|QGLFormatPrivate
DECL|variable|QGLFunctions
DECL|variable|QGLWidgetPrivate
DECL|variable|QPixmap
