DECL|function|QT_MODULE
DECL|function|accum
DECL|function|alpha
DECL|function|depth
DECL|function|directRendering
DECL|function|doubleBuffer
DECL|function|hasOverlay
DECL|function|qGLVersion
DECL|function|rgba
DECL|function|sampleBuffers
DECL|function|stencil
DECL|function|stereo
DECL|macro|QGL_H
DECL|macro|QGL_VERSION
DECL|macro|QGL_VERSION_STR
DECL|macro|Q_MAC_COMPAT_GL_FUNCTIONS
DECL|typedef|QMacCompatGLenum
DECL|typedef|QMacCompatGLint
DECL|typedef|QMacCompatGLuint
DECL|variable|QGLCmap
DECL|variable|QGLContextPrivate
DECL|variable|QGLFormatPrivate
DECL|variable|QGLOverlayWidget
DECL|variable|QGLWidgetPrivate
DECL|variable|QPixmap
