DECL|class|QGLTemporaryContextPrivate
DECL|function|QGLTemporaryContext
DECL|function|chooseContext
DECL|function|cleanupColormaps
DECL|function|colormap
DECL|function|event
DECL|function|glScreenForDevice
DECL|function|hasOpenGLOverlays
DECL|function|init
DECL|function|makeOverlayCurrent
DECL|function|overlayContext
DECL|function|qt_egl_create_surface
DECL|function|resizeEvent
DECL|function|setColormap
DECL|function|setContext
DECL|function|updateOverlayGL
DECL|function|~QGLTemporaryContext
DECL|member|widget
