DECL|function|getTexture
DECL|function|maxCost
DECL|function|operator
DECL|function|qHash
DECL|function|qt_gl_preferredTextureFormat
DECL|function|qt_gl_preferredTextureTarget
DECL|function|setMaxCost
DECL|function|size
DECL|macro|QGL_P_H
DECL|macro|QT_GL_VERTEX_ARRAY_TRACKED_COUNT
DECL|macro|old_qDebug
DECL|macro|old_qDebug
DECL|macro|qDebug
DECL|macro|qDebug
DECL|macro|qDebug
DECL|member|group
DECL|member|key
DECL|struct|QGLTextureCacheKey
DECL|variable|QEglContext
DECL|variable|QGLContext
DECL|variable|QGLContextGroupResourceBase
DECL|variable|QGLContextResourceBase
DECL|variable|QGLOverlayWidget
DECL|variable|QGLSharedResourceGuard
DECL|variable|QGLTemporaryContextPrivate
DECL|variable|QGLTexture
DECL|variable|QGLTextureDestroyer
DECL|variable|QMacWindowChangeEvent
DECL|variable|QPixmap
DECL|variable|QPixmapFilter
DECL|variable|QWSGLWindowSurface
