DECL|class|QGLTemporaryContextPrivate
DECL|function|QGLContext
DECL|function|QGLTemporaryContext
DECL|function|chooseContext
DECL|function|cleanupColormaps
DECL|function|colorIndex
DECL|function|colormap
DECL|function|contextHandle
DECL|function|doneCurrent
DECL|function|event
DECL|function|fromOpenGLContext
DECL|function|fromSurfaceFormat
DECL|function|getProcAddress
DECL|function|hasOpenGL
DECL|function|hasOpenGLOverlays
DECL|function|init
DECL|function|makeCurrent
DECL|function|makeOverlayCurrent
DECL|function|overlayContext
DECL|function|overlayTransparentColor
DECL|function|qDeleteQGLContext
DECL|function|renderCxPm
DECL|function|reset
DECL|function|resizeEvent
DECL|function|setColormap
DECL|function|setContext
DECL|function|setupSharing
DECL|function|swapBuffers
DECL|function|toSurfaceFormat
DECL|function|updateOverlayGL
DECL|function|~QGLTemporaryContext
DECL|member|context
DECL|member|oldContext
DECL|member|window
