DECL|class|QGLTemporaryContextPrivate
DECL|function|QGLTemporaryContext
DECL|function|chooseContext
DECL|function|cleanupColormaps
DECL|function|colormap
DECL|function|createFromNativeImageHandleProvider
DECL|function|fromNativeType
DECL|function|hasOpenGLOverlays
DECL|function|init
DECL|function|initFromNativeImageHandle
DECL|function|knownGoodFormat
DECL|function|makeOverlayCurrent
DECL|function|overlayContext
DECL|function|recreateEglSurface
DECL|function|releaseNativeImageHandle
DECL|function|resizeEvent
DECL|function|setColormap
DECL|function|setContext
DECL|function|toNativeType
DECL|function|updateOverlayGL
DECL|function|~QGLTemporaryContext
DECL|macro|QGL_DIRECT_TO_WINDOW
DECL|macro|QGL_NO_PRESERVED_SWAP
DECL|member|context
DECL|member|display
DECL|member|initialized
DECL|member|surface
DECL|member|window
