DECL|class|QGLCmap
DECL|class|QGLCmapPrivate
DECL|class|QGLTemporaryContextPrivate
DECL|enumerator|Allocated
DECL|enumerator|Reserved
DECL|enumerator|Reserved
DECL|enumerator|UnAllocated
DECL|enum|AllocState
DECL|enum|Flags
DECL|function|QGLCmap
DECL|function|QGLCmap
DECL|function|QGLCmapPrivate
DECL|function|QGLTemporaryContext
DECL|function|allocate
DECL|function|chooseContext
DECL|function|choosePixelFormat
DECL|function|cleanupColormaps
DECL|function|colorIndex
DECL|function|colormap
DECL|function|colors
DECL|function|deref
DECL|function|detach
DECL|function|doneCurrent
DECL|function|find
DECL|function|findNearest
DECL|function|generateFontDisplayLists
DECL|function|getProcAddress
DECL|function|hasOpenGL
DECL|function|hasOpenGLOverlays
DECL|function|init
DECL|function|makeCurrent
DECL|function|makeOverlayCurrent
DECL|function|maxSize
DECL|function|operator =
DECL|function|overlayContext
DECL|function|overlayTransparentColor
DECL|function|pfdToQGLFormat
DECL|function|pfiToQGLFormat
DECL|function|qLogEq
DECL|function|qStoreColors
DECL|function|qgl_create_context
DECL|function|qgl_create_rgb_palette
DECL|function|qgl_rgb_palette_comp
DECL|function|qwglError
DECL|function|ref
DECL|function|renderCxPm
DECL|function|reset
DECL|function|resize
DECL|function|resizeEvent
DECL|function|setColormap
DECL|function|setContext
DECL|function|setEntry
DECL|function|setMouseTracking
DECL|function|size
DECL|function|swapBuffers
DECL|function|updateColormap
DECL|function|updateFormatVersion
DECL|function|updateOverlayGL
DECL|function|~QGLCmap
DECL|function|~QGLTemporaryContext
DECL|macro|ERROR_INVALID_PROFILE_ARB
DECL|macro|ERROR_INVALID_VERSION_ARB
DECL|macro|GL_CONTEXT_FLAGS
DECL|macro|GL_CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT
DECL|macro|GL_CONTEXT_PROFILE_MASK
DECL|macro|GL_MAJOR_VERSION
DECL|macro|GL_MINOR_VERSION
DECL|macro|GL_NUM_EXTENSIONS
DECL|macro|WGL_ACCELERATION_ARB
DECL|macro|WGL_ACCUM_ALPHA_BITS_ARB
DECL|macro|WGL_ACCUM_BITS_ARB
DECL|macro|WGL_ACCUM_BLUE_BITS_ARB
DECL|macro|WGL_ACCUM_GREEN_BITS_ARB
DECL|macro|WGL_ACCUM_RED_BITS_ARB
DECL|macro|WGL_ALPHA_BITS_ARB
DECL|macro|WGL_ALPHA_SHIFT_ARB
DECL|macro|WGL_AUX_BUFFERS_ARB
DECL|macro|WGL_BLUE_BITS_ARB
DECL|macro|WGL_BLUE_SHIFT_ARB
DECL|macro|WGL_COLOR_BITS_ARB
DECL|macro|WGL_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB
DECL|macro|WGL_CONTEXT_CORE_PROFILE_BIT_ARB
DECL|macro|WGL_CONTEXT_DEBUG_BIT_ARB
DECL|macro|WGL_CONTEXT_FLAGS_ARB
DECL|macro|WGL_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB
DECL|macro|WGL_CONTEXT_LAYER_PLANE_ARB
DECL|macro|WGL_CONTEXT_MAJOR_VERSION_ARB
DECL|macro|WGL_CONTEXT_MINOR_VERSION_ARB
DECL|macro|WGL_CONTEXT_PROFILE_MASK_ARB
DECL|macro|WGL_DEPTH_BITS_ARB
DECL|macro|WGL_DOUBLE_BUFFER_ARB
DECL|macro|WGL_DRAW_TO_BITMAP_ARB
DECL|macro|WGL_DRAW_TO_WINDOW_ARB
DECL|macro|WGL_FULL_ACCELERATION_ARB
DECL|macro|WGL_GENERIC_ACCELERATION_ARB
DECL|macro|WGL_GREEN_BITS_ARB
DECL|macro|WGL_GREEN_SHIFT_ARB
DECL|macro|WGL_NEED_PALETTE_ARB
DECL|macro|WGL_NEED_SYSTEM_PALETTE_ARB
DECL|macro|WGL_NO_ACCELERATION_ARB
DECL|macro|WGL_NUMBER_OVERLAYS_ARB
DECL|macro|WGL_NUMBER_PIXEL_FORMATS_ARB
DECL|macro|WGL_NUMBER_UNDERLAYS_ARB
DECL|macro|WGL_PIXEL_TYPE_ARB
DECL|macro|WGL_RED_BITS_ARB
DECL|macro|WGL_RED_SHIFT_ARB
DECL|macro|WGL_SAMPLES_ARB
DECL|macro|WGL_SAMPLE_BUFFERS_ARB
DECL|macro|WGL_SHARE_ACCUM_ARB
DECL|macro|WGL_SHARE_DEPTH_ARB
DECL|macro|WGL_SHARE_STENCIL_ARB
DECL|macro|WGL_STENCIL_BITS_ARB
DECL|macro|WGL_STEREO_ARB
DECL|macro|WGL_SUPPORT_GDI_ARB
DECL|macro|WGL_SUPPORT_OPENGL_ARB
DECL|macro|WGL_SWAP_COPY_ARB
DECL|macro|WGL_SWAP_EXCHANGE_ARB
DECL|macro|WGL_SWAP_LAYER_BUFFERS_ARB
DECL|macro|WGL_SWAP_METHOD_ARB
DECL|macro|WGL_SWAP_UNDEFINED_ARB
DECL|macro|WGL_TRANSPARENT_ALPHA_VALUE_ARB
DECL|macro|WGL_TRANSPARENT_ARB
DECL|macro|WGL_TRANSPARENT_BLUE_VALUE_ARB
DECL|macro|WGL_TRANSPARENT_GREEN_VALUE_ARB
DECL|macro|WGL_TRANSPARENT_INDEX_VALUE_ARB
DECL|macro|WGL_TRANSPARENT_RED_VALUE_ARB
DECL|macro|WGL_TYPE_COLORINDEX_ARB
DECL|macro|WGL_TYPE_RGBA_ARB
DECL|member|allocArray
DECL|member|colorArray
DECL|member|colorMap
DECL|member|contextArray
DECL|member|count
DECL|member|d
DECL|member|dmy_id
DECL|member|dmy_pdc
DECL|member|dmy_rc
DECL|member|maxSize
DECL|member|old_context
DECL|member|old_dc
DECL|typedef|PFNWGLCHOOSEPIXELFORMATARB
DECL|typedef|PFNWGLGETPIXELFORMATATTRIBIVARB
DECL|variable|opengl32dll
