DECL|class|QGLBufferPrivate
DECL|function|QGLBuffer
DECL|function|QGLBuffer
DECL|function|QGLBuffer
DECL|function|QGLBufferPrivate
DECL|function|allocate
DECL|function|bind
DECL|function|bufferId
DECL|function|create
DECL|function|destroy
DECL|function|freeBufferFunc
DECL|function|isCreated
DECL|function|map
DECL|function|operator =
DECL|function|read
DECL|function|release
DECL|function|release
DECL|function|setUsagePattern
DECL|function|size
DECL|function|type
DECL|function|unmap
DECL|function|usagePattern
DECL|function|write
DECL|function|~QGLBuffer
DECL|macro|GL_BUFFER_SIZE
DECL|macro|ctx
DECL|macro|ctx
DECL|macro|ctx
DECL|macro|ctx
DECL|macro|ctx
DECL|member|actualUsagePattern
DECL|member|funcs
DECL|member|guard
DECL|member|ref
DECL|member|type
DECL|member|usagePattern
