DECL|function|glActiveTexture
DECL|function|glAttachShader
DECL|function|glBindAttribLocation
DECL|function|glBindBuffer
DECL|function|glBindFramebuffer
DECL|function|glBindRenderbuffer
DECL|function|glBlendColor
DECL|function|glBlendEquation
DECL|function|glBlendEquationSeparate
DECL|function|glBlendFuncSeparate
DECL|function|glBufferData
DECL|function|glBufferSubData
DECL|function|glCheckFramebufferStatus
DECL|function|glClearDepthf
DECL|function|glCompileShader
DECL|function|glCompressedTexImage2D
DECL|function|glCompressedTexSubImage2D
DECL|function|glCreateProgram
DECL|function|glCreateShader
DECL|function|glDeleteBuffers
DECL|function|glDeleteFramebuffers
DECL|function|glDeleteProgram
DECL|function|glDeleteRenderbuffers
DECL|function|glDeleteShader
DECL|function|glDepthRangef
DECL|function|glDetachShader
DECL|function|glDisableVertexAttribArray
DECL|function|glEnableVertexAttribArray
DECL|function|glFramebufferRenderbuffer
DECL|function|glFramebufferTexture2D
DECL|function|glGenBuffers
DECL|function|glGenFramebuffers
DECL|function|glGenRenderbuffers
DECL|function|glGenerateMipmap
DECL|function|glGetActiveAttrib
DECL|function|glGetActiveUniform
DECL|function|glGetAttachedShaders
DECL|function|glGetAttribLocation
DECL|function|glGetBufferParameteriv
DECL|function|glGetFramebufferAttachmentParameteriv
DECL|function|glGetProgramInfoLog
DECL|function|glGetProgramiv
DECL|function|glGetRenderbufferParameteriv
DECL|function|glGetShaderInfoLog
DECL|function|glGetShaderPrecisionFormat
DECL|function|glGetShaderSource
DECL|function|glGetShaderiv
DECL|function|glGetUniformLocation
DECL|function|glGetUniformfv
DECL|function|glGetUniformiv
DECL|function|glGetVertexAttribPointerv
DECL|function|glGetVertexAttribfv
DECL|function|glGetVertexAttribiv
DECL|function|glIsBuffer
DECL|function|glIsFramebuffer
DECL|function|glIsProgram
DECL|function|glIsRenderbuffer
DECL|function|glIsShader
DECL|function|glLinkProgram
DECL|function|glReleaseShaderCompiler
DECL|function|glRenderbufferStorage
DECL|function|glSampleCoverage
DECL|function|glShaderBinary
DECL|function|glShaderSource
DECL|function|glStencilFuncSeparate
DECL|function|glStencilMaskSeparate
DECL|function|glStencilOpSeparate
DECL|function|glUniform1f
DECL|function|glUniform1fv
DECL|function|glUniform1i
DECL|function|glUniform1iv
DECL|function|glUniform2f
DECL|function|glUniform2fv
DECL|function|glUniform2i
DECL|function|glUniform2iv
DECL|function|glUniform3f
DECL|function|glUniform3fv
DECL|function|glUniform3i
DECL|function|glUniform3iv
DECL|function|glUniform4f
DECL|function|glUniform4fv
DECL|function|glUniform4i
DECL|function|glUniform4iv
DECL|function|glUniformMatrix2fv
DECL|function|glUniformMatrix3fv
DECL|function|glUniformMatrix4fv
DECL|function|glUseProgram
DECL|function|glValidateProgram
DECL|function|glVertexAttrib1f
DECL|function|glVertexAttrib1fv
DECL|function|glVertexAttrib2f
DECL|function|glVertexAttrib2fv
DECL|function|glVertexAttrib3f
DECL|function|glVertexAttrib3fv
DECL|function|glVertexAttrib4f
DECL|function|glVertexAttrib4fv
DECL|function|glVertexAttribPointer
DECL|macro|GL_ACTIVE_ATTRIBUTES
DECL|macro|GL_ACTIVE_ATTRIBUTE_MAX_LENGTH
DECL|macro|GL_ACTIVE_TEXTURE
DECL|macro|GL_ACTIVE_UNIFORMS
DECL|macro|GL_ACTIVE_UNIFORM_MAX_LENGTH
DECL|macro|GL_ALIASED_LINE_WIDTH_RANGE
DECL|macro|GL_ALIASED_POINT_SIZE_RANGE
DECL|macro|GL_ALPHA
DECL|macro|GL_ALPHA_BITS
DECL|macro|GL_ALWAYS
DECL|macro|GL_ARRAY_BUFFER
DECL|macro|GL_ARRAY_BUFFER_BINDING
DECL|macro|GL_ATTACHED_SHADERS
DECL|macro|GL_BACK
DECL|macro|GL_BGRA
DECL|macro|GL_BLEND
DECL|macro|GL_BLEND_COLOR
DECL|macro|GL_BLEND_DST_ALPHA
DECL|macro|GL_BLEND_DST_RGB
DECL|macro|GL_BLEND_EQUATION
DECL|macro|GL_BLEND_EQUATION_ALPHA
DECL|macro|GL_BLEND_EQUATION_RGB
DECL|macro|GL_BLEND_SRC_ALPHA
DECL|macro|GL_BLEND_SRC_RGB
DECL|macro|GL_BLUE_BITS
DECL|macro|GL_BOOL
DECL|macro|GL_BOOL_VEC2
DECL|macro|GL_BOOL_VEC3
DECL|macro|GL_BOOL_VEC4
DECL|macro|GL_BUFFER_SIZE
DECL|macro|GL_BUFFER_USAGE
DECL|macro|GL_BYTE
DECL|macro|GL_CCW
DECL|macro|GL_CLAMP_TO_EDGE
DECL|macro|GL_COLOR_ATTACHMENT0
DECL|macro|GL_COLOR_BUFFER_BIT
DECL|macro|GL_COLOR_CLEAR_VALUE
DECL|macro|GL_COLOR_WRITEMASK
DECL|macro|GL_COMPILE_STATUS
DECL|macro|GL_COMPRESSED_TEXTURE_FORMATS
DECL|macro|GL_CONSTANT_ALPHA
DECL|macro|GL_CONSTANT_COLOR
DECL|macro|GL_CULL_FACE
DECL|macro|GL_CULL_FACE_MODE
DECL|macro|GL_CURRENT_PROGRAM
DECL|macro|GL_CURRENT_VERTEX_ATTRIB
DECL|macro|GL_CW
DECL|macro|GL_DECR
DECL|macro|GL_DECR_WRAP
DECL|macro|GL_DELETE_STATUS
DECL|macro|GL_DEPTH_ATTACHMENT
DECL|macro|GL_DEPTH_BITS
DECL|macro|GL_DEPTH_BUFFER_BIT
DECL|macro|GL_DEPTH_CLEAR_VALUE
DECL|macro|GL_DEPTH_COMPONENT
DECL|macro|GL_DEPTH_COMPONENT16
DECL|macro|GL_DEPTH_FUNC
DECL|macro|GL_DEPTH_RANGE
DECL|macro|GL_DEPTH_TEST
DECL|macro|GL_DEPTH_WRITEMASK
DECL|macro|GL_DITHER
DECL|macro|GL_DONT_CARE
DECL|macro|GL_DST_ALPHA
DECL|macro|GL_DST_COLOR
DECL|macro|GL_DYNAMIC_DRAW
DECL|macro|GL_ELEMENT_ARRAY_BUFFER
DECL|macro|GL_ELEMENT_ARRAY_BUFFER_BINDING
DECL|macro|GL_EQUAL
DECL|macro|GL_EXTENSIONS
DECL|macro|GL_FALSE
DECL|macro|GL_FASTEST
DECL|macro|GL_FIXED
DECL|macro|GL_FLOAT
DECL|macro|GL_FLOAT_MAT2
DECL|macro|GL_FLOAT_MAT3
DECL|macro|GL_FLOAT_MAT4
DECL|macro|GL_FLOAT_VEC2
DECL|macro|GL_FLOAT_VEC3
DECL|macro|GL_FLOAT_VEC4
DECL|macro|GL_FRAGMENT_SHADER
DECL|macro|GL_FRAMEBUFFER
DECL|macro|GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME
DECL|macro|GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE
DECL|macro|GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE
DECL|macro|GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL
DECL|macro|GL_FRAMEBUFFER_BINDING
DECL|macro|GL_FRAMEBUFFER_COMPLETE
DECL|macro|GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT
DECL|macro|GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS
DECL|macro|GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT
DECL|macro|GL_FRAMEBUFFER_UNSUPPORTED
DECL|macro|GL_FRONT
DECL|macro|GL_FRONT_AND_BACK
DECL|macro|GL_FRONT_FACE
DECL|macro|GL_FUNC_ADD
DECL|macro|GL_FUNC_REVERSE_SUBTRACT
DECL|macro|GL_FUNC_SUBTRACT
DECL|macro|GL_GENERATE_MIPMAP_HINT
DECL|macro|GL_GEQUAL
DECL|macro|GL_GREATER
DECL|macro|GL_GREEN_BITS
DECL|macro|GL_HIGH_FLOAT
DECL|macro|GL_HIGH_INT
DECL|macro|GL_IMPLEMENTATION_COLOR_READ_FORMAT
DECL|macro|GL_IMPLEMENTATION_COLOR_READ_TYPE
DECL|macro|GL_INCR
DECL|macro|GL_INCR_WRAP
DECL|macro|GL_INFO_LOG_LENGTH
DECL|macro|GL_INT
DECL|macro|GL_INT_VEC2
DECL|macro|GL_INT_VEC3
DECL|macro|GL_INT_VEC4
DECL|macro|GL_INVALID_ENUM
DECL|macro|GL_INVALID_FRAMEBUFFER_OPERATION
DECL|macro|GL_INVALID_OPERATION
DECL|macro|GL_INVALID_VALUE
DECL|macro|GL_INVERT
DECL|macro|GL_KEEP
DECL|macro|GL_LEQUAL
DECL|macro|GL_LESS
DECL|macro|GL_LINEAR
DECL|macro|GL_LINEAR_MIPMAP_LINEAR
DECL|macro|GL_LINEAR_MIPMAP_NEAREST
DECL|macro|GL_LINES
DECL|macro|GL_LINE_LOOP
DECL|macro|GL_LINE_STRIP
DECL|macro|GL_LINE_WIDTH
DECL|macro|GL_LINK_STATUS
DECL|macro|GL_LOW_FLOAT
DECL|macro|GL_LOW_INT
DECL|macro|GL_LUMINANCE
DECL|macro|GL_LUMINANCE_ALPHA
DECL|macro|GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS
DECL|macro|GL_MAX_CUBE_MAP_TEXTURE_SIZE
DECL|macro|GL_MAX_FRAGMENT_UNIFORM_VECTORS
DECL|macro|GL_MAX_RENDERBUFFER_SIZE
DECL|macro|GL_MAX_TEXTURE_IMAGE_UNITS
DECL|macro|GL_MAX_TEXTURE_SIZE
DECL|macro|GL_MAX_VARYING_VECTORS
DECL|macro|GL_MAX_VERTEX_ATTRIBS
DECL|macro|GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS
DECL|macro|GL_MAX_VERTEX_UNIFORM_VECTORS
DECL|macro|GL_MAX_VIEWPORT_DIMS
DECL|macro|GL_MEDIUM_FLOAT
DECL|macro|GL_MEDIUM_INT
DECL|macro|GL_MIRRORED_REPEAT
DECL|macro|GL_NEAREST
DECL|macro|GL_NEAREST_MIPMAP_LINEAR
DECL|macro|GL_NEAREST_MIPMAP_NEAREST
DECL|macro|GL_NEVER
DECL|macro|GL_NICEST
DECL|macro|GL_NONE
DECL|macro|GL_NOTEQUAL
DECL|macro|GL_NO_ERROR
DECL|macro|GL_NUM_COMPRESSED_TEXTURE_FORMATS
DECL|macro|GL_NUM_SHADER_BINARY_FORMATS
DECL|macro|GL_ONE
DECL|macro|GL_ONE_MINUS_CONSTANT_ALPHA
DECL|macro|GL_ONE_MINUS_CONSTANT_COLOR
DECL|macro|GL_ONE_MINUS_DST_ALPHA
DECL|macro|GL_ONE_MINUS_DST_COLOR
DECL|macro|GL_ONE_MINUS_SRC_ALPHA
DECL|macro|GL_ONE_MINUS_SRC_COLOR
DECL|macro|GL_OUT_OF_MEMORY
DECL|macro|GL_PACK_ALIGNMENT
DECL|macro|GL_POINTS
DECL|macro|GL_POLYGON_OFFSET_FACTOR
DECL|macro|GL_POLYGON_OFFSET_FILL
DECL|macro|GL_POLYGON_OFFSET_UNITS
DECL|macro|GL_RED_BITS
DECL|macro|GL_RENDERBUFFER
DECL|macro|GL_RENDERBUFFER_ALPHA_SIZE
DECL|macro|GL_RENDERBUFFER_BINDING
DECL|macro|GL_RENDERBUFFER_BLUE_SIZE
DECL|macro|GL_RENDERBUFFER_DEPTH_SIZE
DECL|macro|GL_RENDERBUFFER_GREEN_SIZE
DECL|macro|GL_RENDERBUFFER_HEIGHT
DECL|macro|GL_RENDERBUFFER_INTERNAL_FORMAT
DECL|macro|GL_RENDERBUFFER_RED_SIZE
DECL|macro|GL_RENDERBUFFER_STENCIL_SIZE
DECL|macro|GL_RENDERBUFFER_WIDTH
DECL|macro|GL_RENDERER
DECL|macro|GL_REPEAT
DECL|macro|GL_REPLACE
DECL|macro|GL_RGB
DECL|macro|GL_RGB565
DECL|macro|GL_RGB5_A1
DECL|macro|GL_RGBA
DECL|macro|GL_RGBA4
DECL|macro|GL_SAMPLER_2D
DECL|macro|GL_SAMPLER_CUBE
DECL|macro|GL_SAMPLES
DECL|macro|GL_SAMPLE_ALPHA_TO_COVERAGE
DECL|macro|GL_SAMPLE_BUFFERS
DECL|macro|GL_SAMPLE_COVERAGE
DECL|macro|GL_SAMPLE_COVERAGE_INVERT
DECL|macro|GL_SAMPLE_COVERAGE_VALUE
DECL|macro|GL_SCISSOR_BOX
DECL|macro|GL_SCISSOR_TEST
DECL|macro|GL_SHADER_BINARY_FORMATS
DECL|macro|GL_SHADER_COMPILER
DECL|macro|GL_SHADER_SOURCE_LENGTH
DECL|macro|GL_SHADER_TYPE
DECL|macro|GL_SHADING_LANGUAGE_VERSION
DECL|macro|GL_SHORT
DECL|macro|GL_SRC_ALPHA
DECL|macro|GL_SRC_ALPHA_SATURATE
DECL|macro|GL_SRC_COLOR
DECL|macro|GL_STATIC_DRAW
DECL|macro|GL_STENCIL_ATTACHMENT
DECL|macro|GL_STENCIL_BACK_FAIL
DECL|macro|GL_STENCIL_BACK_FUNC
DECL|macro|GL_STENCIL_BACK_PASS_DEPTH_FAIL
DECL|macro|GL_STENCIL_BACK_PASS_DEPTH_PASS
DECL|macro|GL_STENCIL_BACK_REF
DECL|macro|GL_STENCIL_BACK_VALUE_MASK
DECL|macro|GL_STENCIL_BACK_WRITEMASK
DECL|macro|GL_STENCIL_BITS
DECL|macro|GL_STENCIL_BUFFER_BIT
DECL|macro|GL_STENCIL_CLEAR_VALUE
DECL|macro|GL_STENCIL_FAIL
DECL|macro|GL_STENCIL_FUNC
DECL|macro|GL_STENCIL_INDEX
DECL|macro|GL_STENCIL_INDEX8
DECL|macro|GL_STENCIL_PASS_DEPTH_FAIL
DECL|macro|GL_STENCIL_PASS_DEPTH_PASS
DECL|macro|GL_STENCIL_REF
DECL|macro|GL_STENCIL_TEST
DECL|macro|GL_STENCIL_VALUE_MASK
DECL|macro|GL_STENCIL_WRITEMASK
DECL|macro|GL_STREAM_DRAW
DECL|macro|GL_SUBPIXEL_BITS
DECL|macro|GL_TEXTURE
DECL|macro|GL_TEXTURE0
DECL|macro|GL_TEXTURE1
DECL|macro|GL_TEXTURE10
DECL|macro|GL_TEXTURE11
DECL|macro|GL_TEXTURE12
DECL|macro|GL_TEXTURE13
DECL|macro|GL_TEXTURE14
DECL|macro|GL_TEXTURE15
DECL|macro|GL_TEXTURE16
DECL|macro|GL_TEXTURE17
DECL|macro|GL_TEXTURE18
DECL|macro|GL_TEXTURE19
DECL|macro|GL_TEXTURE2
DECL|macro|GL_TEXTURE20
DECL|macro|GL_TEXTURE21
DECL|macro|GL_TEXTURE22
DECL|macro|GL_TEXTURE23
DECL|macro|GL_TEXTURE24
DECL|macro|GL_TEXTURE25
DECL|macro|GL_TEXTURE26
DECL|macro|GL_TEXTURE27
DECL|macro|GL_TEXTURE28
DECL|macro|GL_TEXTURE29
DECL|macro|GL_TEXTURE3
DECL|macro|GL_TEXTURE30
DECL|macro|GL_TEXTURE31
DECL|macro|GL_TEXTURE4
DECL|macro|GL_TEXTURE5
DECL|macro|GL_TEXTURE6
DECL|macro|GL_TEXTURE7
DECL|macro|GL_TEXTURE8
DECL|macro|GL_TEXTURE9
DECL|macro|GL_TEXTURE_2D
DECL|macro|GL_TEXTURE_BINDING_2D
DECL|macro|GL_TEXTURE_BINDING_CUBE_MAP
DECL|macro|GL_TEXTURE_CUBE_MAP
DECL|macro|GL_TEXTURE_CUBE_MAP_NEGATIVE_X
DECL|macro|GL_TEXTURE_CUBE_MAP_NEGATIVE_Y
DECL|macro|GL_TEXTURE_CUBE_MAP_NEGATIVE_Z
DECL|macro|GL_TEXTURE_CUBE_MAP_POSITIVE_X
DECL|macro|GL_TEXTURE_CUBE_MAP_POSITIVE_Y
DECL|macro|GL_TEXTURE_CUBE_MAP_POSITIVE_Z
DECL|macro|GL_TEXTURE_MAG_FILTER
DECL|macro|GL_TEXTURE_MIN_FILTER
DECL|macro|GL_TEXTURE_WRAP_S
DECL|macro|GL_TEXTURE_WRAP_T
DECL|macro|GL_TRIANGLES
DECL|macro|GL_TRIANGLE_FAN
DECL|macro|GL_TRIANGLE_STRIP
DECL|macro|GL_TRUE
DECL|macro|GL_UNPACK_ALIGNMENT
DECL|macro|GL_UNSIGNED_BYTE
DECL|macro|GL_UNSIGNED_INT
DECL|macro|GL_UNSIGNED_SHORT
DECL|macro|GL_UNSIGNED_SHORT_4_4_4_4
DECL|macro|GL_UNSIGNED_SHORT_5_5_5_1
DECL|macro|GL_UNSIGNED_SHORT_5_6_5
DECL|macro|GL_VALIDATE_STATUS
DECL|macro|GL_VENDOR
DECL|macro|GL_VERSION
DECL|macro|GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING
DECL|macro|GL_VERTEX_ATTRIB_ARRAY_ENABLED
DECL|macro|GL_VERTEX_ATTRIB_ARRAY_NORMALIZED
DECL|macro|GL_VERTEX_ATTRIB_ARRAY_POINTER
DECL|macro|GL_VERTEX_ATTRIB_ARRAY_SIZE
DECL|macro|GL_VERTEX_ATTRIB_ARRAY_STRIDE
DECL|macro|GL_VERTEX_ATTRIB_ARRAY_TYPE
DECL|macro|GL_VERTEX_SHADER
DECL|macro|GL_VIEWPORT
DECL|macro|GL_ZERO
DECL|macro|QGLFUNCTIONS_H
DECL|macro|QGLF_APIENTRY
DECL|macro|QGLF_APIENTRY
DECL|macro|QGLF_APIENTRY
DECL|macro|QGLF_APIENTRYP
DECL|macro|QGLF_APIENTRYP
DECL|macro|glActiveTexture
DECL|macro|glAttachShader
DECL|macro|glBindAttribLocation
DECL|macro|glBindBuffer
DECL|macro|glBindFramebuffer
DECL|macro|glBindRenderbuffer
DECL|macro|glBlendColor
DECL|macro|glBlendEquation
DECL|macro|glBlendEquationSeparate
DECL|macro|glBlendFuncSeparate
DECL|macro|glBufferData
DECL|macro|glBufferSubData
DECL|macro|glCheckFramebufferStatus
DECL|macro|glClearDepthf
DECL|macro|glCompileShader
DECL|macro|glCompressedTexImage2D
DECL|macro|glCompressedTexSubImage2D
DECL|macro|glCreateProgram
DECL|macro|glCreateShader
DECL|macro|glDeleteBuffers
DECL|macro|glDeleteFramebuffers
DECL|macro|glDeleteProgram
DECL|macro|glDeleteRenderbuffers
DECL|macro|glDeleteShader
DECL|macro|glDepthRangef
DECL|macro|glDetachShader
DECL|macro|glDisableVertexAttribArray
DECL|macro|glEnableVertexAttribArray
DECL|macro|glFramebufferRenderbuffer
DECL|macro|glFramebufferTexture2D
DECL|macro|glGenBuffers
DECL|macro|glGenFramebuffers
DECL|macro|glGenRenderbuffers
DECL|macro|glGenerateMipmap
DECL|macro|glGetActiveAttrib
DECL|macro|glGetActiveUniform
DECL|macro|glGetAttachedShaders
DECL|macro|glGetAttribLocation
DECL|macro|glGetBufferParameteriv
DECL|macro|glGetFramebufferAttachmentParameteriv
DECL|macro|glGetProgramInfoLog
DECL|macro|glGetProgramiv
DECL|macro|glGetRenderbufferParameteriv
DECL|macro|glGetShaderInfoLog
DECL|macro|glGetShaderPrecisionFormat
DECL|macro|glGetShaderSource
DECL|macro|glGetShaderiv
DECL|macro|glGetUniformLocation
DECL|macro|glGetUniformfv
DECL|macro|glGetUniformiv
DECL|macro|glGetVertexAttribPointerv
DECL|macro|glGetVertexAttribfv
DECL|macro|glGetVertexAttribiv
DECL|macro|glIsBuffer
DECL|macro|glIsFramebuffer
DECL|macro|glIsProgram
DECL|macro|glIsRenderbuffer
DECL|macro|glIsShader
DECL|macro|glLinkProgram
DECL|macro|glReleaseShaderCompiler
DECL|macro|glRenderbufferStorage
DECL|macro|glSampleCoverage
DECL|macro|glShaderBinary
DECL|macro|glShaderSource
DECL|macro|glStencilFuncSeparate
DECL|macro|glStencilMaskSeparate
DECL|macro|glStencilOpSeparate
DECL|macro|glUniform1f
DECL|macro|glUniform1fv
DECL|macro|glUniform1i
DECL|macro|glUniform1iv
DECL|macro|glUniform2f
DECL|macro|glUniform2fv
DECL|macro|glUniform2i
DECL|macro|glUniform2iv
DECL|macro|glUniform3f
DECL|macro|glUniform3fv
DECL|macro|glUniform3i
DECL|macro|glUniform3iv
DECL|macro|glUniform4f
DECL|macro|glUniform4fv
DECL|macro|glUniform4i
DECL|macro|glUniform4iv
DECL|macro|glUniformMatrix2fv
DECL|macro|glUniformMatrix3fv
DECL|macro|glUniformMatrix4fv
DECL|macro|glUseProgram
DECL|macro|glValidateProgram
DECL|macro|glVertexAttrib1f
DECL|macro|glVertexAttrib1fv
DECL|macro|glVertexAttrib2f
DECL|macro|glVertexAttrib2fv
DECL|macro|glVertexAttrib3f
DECL|macro|glVertexAttrib3fv
DECL|macro|glVertexAttrib4f
DECL|macro|glVertexAttrib4fv
DECL|macro|glVertexAttribPointer
DECL|struct|QGLFunctionsPrivate
DECL|typedef|qgl_GLintptr
DECL|typedef|qgl_GLsizeiptr
