DECL|function|bindToDynamicTexture
DECL|function|cleanup
DECL|function|generateDynamicTexture
DECL|function|hasOpenGLPbuffers
DECL|function|init
DECL|function|releaseFromDynamicTexture
DECL|macro|QGL_RENDER_TEXTURE
