DECL|macro|QGLPIXELBUFFER_P_H
DECL|member|accumAlphaBits
DECL|member|accumBlueBits
DECL|member|accumGreenBits
DECL|member|accumRedBits
DECL|member|alphaBits
DECL|member|alphaMask
DECL|member|associatedVisualId
DECL|member|blueBits
DECL|member|blueMask
DECL|member|colorIndexMode
DECL|member|depthBits
DECL|member|doubleBufferMode
DECL|member|drawableType
DECL|member|extendedRange
DECL|member|greenBits
DECL|member|greenMask
DECL|member|haveAccumBuffer
DECL|member|haveDepthBuffer
DECL|member|haveStencilBuffer
DECL|member|id
DECL|member|indexBits
DECL|member|level
DECL|member|maxAlpha
DECL|member|maxAuxBuffers
DECL|member|maxBlue
DECL|member|maxGreen
DECL|member|maxPbufferHeight
DECL|member|maxPbufferPixels
DECL|member|maxPbufferWidth
DECL|member|maxRed
DECL|member|minAlpha
DECL|member|minBlue
DECL|member|minGreen
DECL|member|minRed
DECL|member|multiSampleSize
DECL|member|nMultiSampleBuffers
DECL|member|optimalPbufferHeight
DECL|member|optimalPbufferWidth
DECL|member|redBits
DECL|member|redMask
DECL|member|renderType
DECL|member|rgbMode
DECL|member|screen
DECL|member|stencilBits
DECL|member|stereoMode
DECL|member|transparentAlpha
DECL|member|transparentBlue
DECL|member|transparentGreen
DECL|member|transparentIndex
DECL|member|transparentRed
DECL|member|transparentType
DECL|member|visualCaveat
DECL|member|visualSelectGroup
DECL|member|visualType
DECL|struct|GLXFBConfig
DECL|typedef|GLXPbuffer
DECL|variable|QEglContext
