DECL|function|QGLPixmapData
DECL|function|acquire
DECL|function|alphaRequested
DECL|function|areaDiff
DECL|function|beginPaint
DECL|function|bind
DECL|function|context
DECL|function|copy
DECL|function|copyBackFromRenderFbo
DECL|function|createCompatiblePixmapData
DECL|function|createPixmapForImage
DECL|function|destroyTexture
DECL|function|detachTextureFromPool
DECL|function|endPaint
DECL|function|ensureCreated
DECL|function|fill
DECL|function|fillImage
DECL|function|forceToImage
DECL|function|fromData
DECL|function|fromFile
DECL|function|fromImage
DECL|function|fromImageReader
DECL|function|glDevice
DECL|function|hasAlphaChannel
DECL|function|hibernate
DECL|function|idealFormat
DECL|function|isValid
DECL|function|isValidContext
DECL|function|maybeRoundToNextPowerOfTwo
DECL|function|metric
DECL|function|paintEngine
DECL|function|paintEngine
DECL|function|qgl_fbo_pool
DECL|function|reclaimTexture
DECL|function|release
DECL|function|resize
DECL|function|scroll
DECL|function|setPixmapData
DECL|function|size
DECL|function|texture
DECL|function|toImage
DECL|function|useFramebufferObjects
DECL|function|~QGLPixmapData
DECL|member|engine
DECL|member|fbo
DECL|struct|TextureBuffer
DECL|variable|qt_gl_pixmap_serial
