DECL|class|QGLGlobalShareWidget
DECL|function|QGLGlobalShareWidget
DECL|function|QGLWindowSurface
DECL|function|beginPaint
DECL|function|blitTexture
DECL|function|cleanup
DECL|function|context
DECL|function|context
DECL|function|deleted
DECL|function|destroy
DECL|function|drawTexture
DECL|function|endPaint
DECL|function|endPaint
DECL|function|features
DECL|function|flush
DECL|function|hijackWindow
DECL|function|initializeOffscreenTexture
DECL|function|metric
DECL|function|paintDevice
DECL|function|paintEngine
DECL|function|qt_cleanup_gl_share_widget
DECL|function|qt_destroy_gl_share_widget
DECL|function|qt_gl_hibernate_pixmaps
DECL|function|qt_gl_register_pixmap
DECL|function|qt_gl_share_context
DECL|function|qt_gl_share_widget
DECL|function|qt_gl_unregister_pixmap
DECL|function|resize
DECL|function|scroll
DECL|function|setGeometry
DECL|function|shareWidget
DECL|function|size
DECL|function|updateGeometry
DECL|function|~QGLWindowSurface
DECL|macro|GLX_SAMPLES_ARB
DECL|macro|GLX_SAMPLE_BUFFERS_ARB
DECL|member|buffers
DECL|member|cleanedUp
DECL|member|cleanedUp
DECL|member|contexts
DECL|member|ctx
DECL|member|destructive_swap_buffers
DECL|member|did_paint
DECL|member|fbo
DECL|member|firstPixmap
DECL|member|geometry_updated
DECL|member|glDevice
DECL|member|initializing
DECL|member|paintedRegion
DECL|member|pb
DECL|member|pb_tex_id
DECL|member|q_ptr
DECL|member|size
DECL|member|surfaceFormat
DECL|member|swapBehavior
DECL|member|swap_region_support
DECL|member|tex_id
DECL|member|textureSize
DECL|member|tried_fbo
DECL|member|tried_pb
DECL|member|widget
DECL|member|widgetRefCount
DECL|struct|QGLWindowSurfacePrivate
