DECL|class|Arg
DECL|class|Arg
DECL|class|Arg
DECL|class|Arg
DECL|class|Arg
DECL|class|Arg
DECL|class|Arg
DECL|class|Arg
DECL|class|Arg
DECL|class|Arg
DECL|class|ArgBase
DECL|class|CharStarContainer
DECL|class|Reversed
DECL|class|tst_QString
DECL|function|Arg
DECL|function|Arg
DECL|function|Arg
DECL|function|Arg
DECL|function|Arg
DECL|function|Arg
DECL|function|Arg
DECL|function|Arg
DECL|function|Arg
DECL|function|Arg
DECL|function|ArgBase
DECL|function|CharStarContainer
DECL|function|QCharRefDetaching
DECL|function|QCharRefMutableUnicode
DECL|function|STL
DECL|function|acc_01
DECL|function|append_bytearray_special_cases
DECL|function|append_bytearray_special_cases_data
DECL|function|append_char
DECL|function|append_char_data
DECL|function|append_charstar
DECL|function|append_charstar_data
DECL|function|append_data
DECL|function|append_impl
DECL|function|append_impl
DECL|function|append_qbytearray
DECL|function|append_qbytearray_data
DECL|function|append_qchar
DECL|function|append_qchar_data
DECL|function|append_qcharstar_int
DECL|function|append_qcharstar_int_data
DECL|function|append_qlatin1string
DECL|function|append_qlatin1string_data
DECL|function|append_qstring
DECL|function|append_qstring_data
DECL|function|append_qstringref
DECL|function|append_qstringref_data
DECL|function|append_special_cases
DECL|function|apply0
DECL|function|apply0
DECL|function|apply0
DECL|function|apply0
DECL|function|apply0
DECL|function|apply0
DECL|function|apply0
DECL|function|apply0
DECL|function|apply1
DECL|function|apply1
DECL|function|apply1
DECL|function|apply1
DECL|function|apply1
DECL|function|apply1
DECL|function|apply1
DECL|function|apply1
DECL|function|arg
DECL|function|arg_fillChar
DECL|function|arg_fillChar_data
DECL|function|arg_locale
DECL|function|assignQLatin1String
DECL|function|capacity
DECL|function|capacity_data
DECL|function|check_QDataStream
DECL|function|check_QTextIOStream
DECL|function|check_QTextStream
DECL|function|cleanup
DECL|function|compare
DECL|function|compareQLatin1Strings
DECL|function|compareRef
DECL|function|compare_data
DECL|function|constructor
DECL|function|constructorQByteArray
DECL|function|constructorQByteArray_data
DECL|function|contains
DECL|function|count
DECL|function|do_apply0
DECL|function|do_apply1
DECL|function|double_conversion
DECL|function|double_conversion_data
DECL|function|dupAndReverse
DECL|function|eightBitLiterals
DECL|function|eightBitLiterals_data
DECL|function|endsWith
DECL|function|fill
DECL|function|fromAscii
DECL|function|fromLatin1
DECL|function|fromLatin1Roundtrip
DECL|function|fromLatin1Roundtrip_data
DECL|function|fromLocal8Bit
DECL|function|fromLocal8Bit_data
DECL|function|fromQLatin1StringWithLength
DECL|function|fromRawData
DECL|function|fromStdString
DECL|function|fromUcs4
DECL|function|fromUtf16
DECL|function|fromUtf16_char16
DECL|function|fromUtf16_char16_data
DECL|function|fromUtf16_data
DECL|function|fromUtf8
DECL|function|fromUtf8_data
DECL|function|indexOf
DECL|function|indexOf2
DECL|function|indexOf2_data
DECL|function|indexOf3_data
DECL|function|indexOfInvalidRegex
DECL|function|indexOf_data
DECL|function|insert_char
DECL|function|insert_char_data
DECL|function|insert_data
DECL|function|insert_impl
DECL|function|insert_impl
DECL|function|insert_qchar
DECL|function|insert_qchar_data
DECL|function|insert_qcharstar_int
DECL|function|insert_qcharstar_int_data
DECL|function|insert_qlatin1string
DECL|function|insert_qlatin1string_data
DECL|function|insert_qstring
DECL|function|insert_qstring_data
DECL|function|insert_special_cases
DECL|function|integer_conversion
DECL|function|integer_conversion_data
DECL|function|isEmpty
DECL|function|isLatin
DECL|function|isNull
DECL|function|isRightToLeft
DECL|function|isRightToLeft_data
DECL|function|lastIndexOf
DECL|function|lastIndexOfInvalidRegex
DECL|function|lastIndexOf_data
DECL|function|latin1String
DECL|function|left
DECL|function|leftJustified
DECL|function|leftRef
DECL|function|length
DECL|function|length_data
DECL|function|literals
DECL|function|local8Bit
DECL|function|local8Bit_data
DECL|function|localeAwareCompare
DECL|function|localeAwareCompare_data
DECL|function|macTypes
DECL|function|mid
DECL|function|midRef
DECL|function|nanAndInf
DECL|function|nullFromLocal8Bit
DECL|function|nullFromUtf8
DECL|function|number
DECL|function|operator ==
DECL|function|operator ==
DECL|function|operator const char *
DECL|function|operatorGreaterWithQLatin1String
DECL|function|operator_eqeq_bytearray
DECL|function|operator_eqeq_bytearray_data
DECL|function|operator_eqeq_nullstring
DECL|function|operator_pluseq_bytearray_special_cases
DECL|function|operator_pluseq_bytearray_special_cases_data
DECL|function|operator_pluseq_char
DECL|function|operator_pluseq_char_data
DECL|function|operator_pluseq_charstar
DECL|function|operator_pluseq_charstar_data
DECL|function|operator_pluseq_data
DECL|function|operator_pluseq_impl
DECL|function|operator_pluseq_impl
DECL|function|operator_pluseq_qbytearray
DECL|function|operator_pluseq_qbytearray_data
DECL|function|operator_pluseq_qchar
DECL|function|operator_pluseq_qchar_data
DECL|function|operator_pluseq_qlatin1string
DECL|function|operator_pluseq_qlatin1string_data
DECL|function|operator_pluseq_qstring
DECL|function|operator_pluseq_qstring_data
DECL|function|operator_pluseq_qstringref
DECL|function|operator_pluseq_qstringref_data
DECL|function|operator_smaller
DECL|function|prepend_bytearray_special_cases
DECL|function|prepend_bytearray_special_cases_data
DECL|function|prepend_char
DECL|function|prepend_char_data
DECL|function|prepend_charstar
DECL|function|prepend_charstar_data
DECL|function|prepend_data
DECL|function|prepend_impl
DECL|function|prepend_impl
DECL|function|prepend_qbytearray
DECL|function|prepend_qbytearray_data
DECL|function|prepend_qchar
DECL|function|prepend_qchar_data
DECL|function|prepend_qlatin1string
DECL|function|prepend_qlatin1string_data
DECL|function|prepend_qstring
DECL|function|prepend_qstring_data
DECL|function|ref
DECL|function|remove_regexp
DECL|function|remove_regexp_data
DECL|function|remove_string
DECL|function|remove_string_data
DECL|function|remove_uint_uint
DECL|function|remove_uint_uint_data
DECL|function|repeated
DECL|function|repeatedSignature
DECL|function|repeated_data
DECL|function|replace_qchar_qchar
DECL|function|replace_qchar_qchar_data
DECL|function|replace_qchar_qstring
DECL|function|replace_qchar_qstring_data
DECL|function|replace_regexp
DECL|function|replace_regexp_data
DECL|function|replace_string
DECL|function|replace_string_data
DECL|function|replace_uint_uint
DECL|function|replace_uint_uint_data
DECL|function|replace_uint_uint_extra
DECL|function|reserve
DECL|function|resizeAfterFromRawData
DECL|function|resizeAfterReserve
DECL|function|resizeWithNegative
DECL|function|right
DECL|function|rightJustified
DECL|function|rightRef
DECL|function|section
DECL|function|section_data
DECL|function|setNum
DECL|function|setRawData
DECL|function|sign
DECL|function|simplified
DECL|function|simplified_data
DECL|function|split
DECL|function|split
DECL|function|split
DECL|function|split
DECL|function|split
DECL|function|split
DECL|function|split
DECL|function|split
DECL|function|split
DECL|function|split
DECL|function|splitRef
DECL|function|splitRef_data
DECL|function|splitRef_regexp
DECL|function|splitRef_regexp_data
DECL|function|splitRef_regularexpression
DECL|function|splitRef_regularexpression_data
DECL|function|split_data
DECL|function|split_regexp
DECL|function|split_regexp
DECL|function|split_regexp_data
DECL|function|split_regularexpression
DECL|function|split_regularexpression_data
DECL|function|sprintf
DECL|function|sprintfZU
DECL|function|startsWith
DECL|function|stringRef
DECL|function|stringRef_local8Bit
DECL|function|stringRef_local8Bit_data
DECL|function|stringRef_toLatin1Roundtrip
DECL|function|stringRef_toLatin1Roundtrip_data
DECL|function|stringRef_utf8
DECL|function|stringRef_utf8_data
DECL|function|swap
DECL|function|toCaseFolded
DECL|function|toDouble
DECL|function|toDouble_data
DECL|function|toFloat
DECL|function|toHtmlEscaped
DECL|function|toHtmlEscaped_data
DECL|function|toInt
DECL|function|toLatin1Roundtrip
DECL|function|toLatin1Roundtrip_data
DECL|function|toLong
DECL|function|toLongLong
DECL|function|toLong_data
DECL|function|toLower
DECL|function|toNum
DECL|function|toShort
DECL|function|toStdString
DECL|function|toUInt
DECL|function|toULong
DECL|function|toULongLong
DECL|function|toULong_data
DECL|function|toUShort
DECL|function|toUcs4
DECL|function|toUpper
DECL|function|toUpperLower_icu
DECL|function|tortureSprintfDouble
DECL|function|trimmed
DECL|function|truncate
DECL|function|truncateWithNegative
DECL|function|tst_QString
DECL|function|unicodeStrings
DECL|function|utf8
DECL|function|utf8_data
DECL|function|verifyZeroTermination
DECL|function|verifyZeroTermination
DECL|function|~Arg
DECL|macro|CHECK_DOUBLE
DECL|macro|CHECK_INF
DECL|macro|CHECK_NAN
DECL|macro|CHECK_NAN
DECL|macro|CREATE_REF
DECL|macro|MY_DOUBLE_EPSILON
DECL|macro|QCOMPARE
DECL|macro|QCOMPARE
DECL|macro|QSTRING_FROM_QCHARARRAY
DECL|macro|QSTRING_FROM_QCHARARRAY
DECL|macro|QTEST
DECL|macro|QTEST
DECL|macro|QT_ASCII_CAST_WARNINGS
DECL|macro|QT_NO_CAST_FROM_ASCII
DECL|macro|QT_NO_CAST_TO_ASCII
DECL|macro|Q_OS_WIN_AND_WINCE
DECL|macro|TEST_BAD
DECL|macro|TEST_BAD
DECL|macro|TEST_BAD_ALL
DECL|macro|TEST_BAD_ALL
DECL|macro|TEST_BASE
DECL|macro|TEST_BASE
DECL|macro|TEST_DOUBLE
DECL|macro|TEST_DOUBLE
DECL|macro|TEST_NEG_BASE
DECL|macro|TEST_NEG_BASE
DECL|macro|TEST_REF_ENDS_WITH
DECL|macro|TEST_REF_STARTS_WITH
DECL|macro|TEST_REF_STARTS_WITH
DECL|macro|TEST_REF_STARTS_WITH
DECL|macro|TEST_TO_INT
DECL|macro|TEST_TO_INT
DECL|macro|TEST_TO_UINT
DECL|macro|TEST_TO_UINT
DECL|member|ba
DECL|member|l1
DECL|member|pinned
DECL|member|str
DECL|member|str
DECL|member|str
DECL|member|string
DECL|member|string
DECL|struct|StringSplitWrapper
DECL|struct|StringSplitWrapper
DECL|typedef|IntList
