DECL|class|IsRegisteredDummyType
DECL|class|MetaTypeTorturer
DECL|class|RegUnreg
DECL|class|tst_QMetaType
DECL|function|Bar
DECL|function|MetaTypeTorturer
DECL|function|QTBUG11316_registerStreamBuiltin
DECL|function|RegUnreg
DECL|function|RegUnreg
DECL|function|create
DECL|function|defined
DECL|function|isRegistered
DECL|function|isRegistered_data
DECL|function|namespaces
DECL|function|normalizedTypes
DECL|function|prop
DECL|function|properties
DECL|function|qMetaTypeId
DECL|function|run
DECL|function|setProp
DECL|function|threadSafety
DECL|function|tst_QMetaType
DECL|function|typeName
DECL|function|typeName_data
DECL|function|typedefs
DECL|function|unregisterType
DECL|function|~RegUnreg
DECL|member|d
DECL|member|failureCount
DECL|member|failureCount
DECL|member|failureCount
DECL|member|i
DECL|member|propList
DECL|member|t
DECL|namespace|TestSpace
DECL|struct|Bar
DECL|struct|Foo
DECL|struct|Foo
DECL|struct|Whity
DECL|typedef|CustomString
