DECL|class|RectWidget
DECL|class|tst_QGraphicsSceneIndex
DECL|function|RectWidget
DECL|function|clear
DECL|function|common_data
DECL|function|connectedToSceneRectChanged
DECL|function|createIndex
DECL|function|customIndex
DECL|function|customIndex_data
DECL|function|initTestCase
DECL|function|items
DECL|function|movingItems
DECL|function|movingItems_data
DECL|function|overlappedItems
DECL|function|overlappedItems_data
DECL|function|paint
DECL|function|removeItems
DECL|function|scatteredItems
DECL|function|scatteredItems_data
DECL|member|brush
