DECL|class|tst_QBrush
DECL|function|badStyles
DECL|function|debug
DECL|function|fill
DECL|function|gradientStops
DECL|function|isOpaque
DECL|function|nullBrush
DECL|function|operator_eq_eq
DECL|function|operator_eq_eq_data
DECL|function|stream
DECL|function|stream_data
DECL|function|swap
DECL|function|testQConicalGradientSetters
DECL|function|testQGradientCopyConstructor
DECL|function|testQLinearGradientSetters
DECL|function|testQRadialGradientSetters
DECL|function|textures
DECL|function|tst_QBrush
