DECL|enumerator|CriticalEventPriority
DECL|enumerator|IdleProcessingDoneEventPriority
DECL|enumerator|ImportantEventPriority
DECL|enumerator|MoreImportantEventPriority
DECL|enumerator|StatusEventPriority
DECL|enum|CustomEventPriority
