DECL|class|MyClass
DECL|enumerator|High
DECL|enumerator|Low
DECL|enumerator|VeryHigh
DECL|enumerator|VeryLow
DECL|enum|Priority
DECL|function|priority
DECL|function|setPriority
DECL|member|m_priority
DECL|variable|button
DECL|variable|count
DECL|variable|myinstance
DECL|variable|object
DECL|variable|object
DECL|variable|object
