DECL|class|MyClass
DECL|class|MyClass
DECL|class|MyClass
DECL|class|Point2D
DECL|enumerator|NoOptions
DECL|enumerator|ShowAll
DECL|enumerator|ShowTabs
DECL|enumerator|SqueezeBlank
DECL|enum|Option
DECL|function|Point2D
DECL|function|Point2D
DECL|function|addLabels
DECL|function|divide
DECL|function|divide
DECL|function|divide
DECL|function|f
DECL|function|global_greeting
DECL|function|global_greeting
DECL|function|greeting
DECL|function|greeting
DECL|function|load
DECL|function|main
DECL|function|myMessageOutput
DECL|function|myMin
DECL|function|operator =
DECL|function|readConfiguration
DECL|function|x
DECL|function|y
DECL|function|~Point2D
DECL|member|data
DECL|member|x
DECL|member|y
DECL|namespace|QT_NAMESPACE
DECL|struct|Point2D
DECL|typedef|Flags
DECL|variable|a
DECL|variable|a
DECL|variable|absoluteValue
DECL|variable|boundedValue
DECL|variable|boundedValue
DECL|variable|divide
DECL|variable|i
DECL|variable|i
DECL|variable|i
DECL|variable|icon
DECL|variable|ids
DECL|variable|maxValue
DECL|variable|maxValue
DECL|variable|maxValue
DECL|variable|minValue
DECL|variable|minValue
DECL|variable|minValue
DECL|variable|myValue
DECL|variable|myValue
DECL|variable|myValue
DECL|variable|myValue
DECL|variable|myValue
DECL|variable|pixmap
DECL|variable|roundedValueA
DECL|variable|roundedValueA
DECL|variable|roundedValueB
DECL|variable|roundedValueB
DECL|variable|text
DECL|variable|value
DECL|variable|value
DECL|variable|value
DECL|variable|value
DECL|variable|valueA
DECL|variable|valueA
DECL|variable|valueB
DECL|variable|valueB
DECL|variable|w
DECL|variable|yourValue
DECL|variable|yourValue
