DECL|function|StartsWith
DECL|function|addToDictionary
DECL|function|allLowerCase
DECL|function|operator ()
DECL|member|bind
DECL|member|m_string
DECL|member|static_cast
DECL|struct|StartsWith
DECL|typedef|result_type
DECL|variable|alphaImages
DECL|variable|averageWordLength
DECL|variable|characters
DECL|variable|collage
DECL|variable|dictionary
DECL|variable|dictionary
DECL|variable|dictionary
DECL|variable|fooString
DECL|variable|future
DECL|variable|future
DECL|variable|grayscaleImages
DECL|variable|images
DECL|variable|images
DECL|variable|images
DECL|variable|lowerCaseStrings
DECL|variable|lowerCaseStrings
DECL|variable|lowerCaseStrings
DECL|variable|set
DECL|variable|strings
DECL|variable|strings
DECL|variable|strings
DECL|variable|strings
DECL|variable|strings
DECL|variable|strings
DECL|variable|strings
DECL|variable|strings
