DECL|member|FlatCap
DECL|member|MiterJoin
DECL|member|SolidLine
DECL|variable|boundingRectangle
DECL|variable|center
DECL|variable|myFont
DECL|variable|myGradient
DECL|variable|myGradient
DECL|variable|myGradient
DECL|variable|myGradient
DECL|variable|myGradient
DECL|variable|myGradient
DECL|variable|myPath
DECL|variable|myPath
DECL|variable|myPath
DECL|variable|myPath
DECL|variable|myPath
DECL|variable|myPath
DECL|variable|myPen
DECL|variable|myPen
DECL|variable|myPen
DECL|variable|myPen
DECL|variable|myPen
DECL|variable|myPen
DECL|variable|myPolygon
DECL|variable|myRectangle
DECL|variable|path
DECL|variable|startPoint
