DECL|class|GetAndEverythingShouldBePipelinedReceiver
DECL|class|GetEmptyWithPipeliningReceiver
DECL|class|GetMultipleWithPrioritiesReceiver
DECL|class|tst_QHttpNetworkConnection
DECL|function|GetAndEverythingShouldBePipelinedReceiver
DECL|function|GetEmptyWithPipeliningReceiver
DECL|function|GetMultipleWithPrioritiesReceiver
DECL|function|_connect
DECL|function|_connect_data
DECL|function|_delete
DECL|function|_delete_data
DECL|function|challenge401
DECL|function|cleanup
DECL|function|cleanupTestCase
DECL|function|compression
DECL|function|compression_data
DECL|function|finishedReply
DECL|function|finishedSlot
DECL|function|finishedSlot
DECL|function|finishedSlot
DECL|function|finishedWithError
DECL|function|get
DECL|function|get401
DECL|function|get401_data
DECL|function|getAndEverythingShouldBePipelined
DECL|function|getAndThenDeleteObject
DECL|function|getAndThenDeleteObject_data
DECL|function|getEmptyWithPipelining
DECL|function|getMultiple
DECL|function|getMultipleWithPipeliningAndMultiplePriorities
DECL|function|getMultipleWithPriorities
DECL|function|getMultiple_data
DECL|function|get_data
DECL|function|head
DECL|function|head_data
DECL|function|ignoresslerror
DECL|function|ignoresslerror_data
DECL|function|init
DECL|function|initTestCase
DECL|function|nossl
DECL|function|nossl_data
DECL|function|options
DECL|function|options_data
DECL|function|post
DECL|function|post_data
DECL|function|put
DECL|function|put_data
DECL|function|sslErrors
DECL|function|trace
DECL|function|trace_data
DECL|function|tst_QHttpNetworkConnection
DECL|member|finishedCalled
DECL|member|finishedWithErrorCalled
DECL|member|highPrioReceived
DECL|member|lowPrioReceived
DECL|member|netErrorCode
DECL|member|receivedCount
DECL|member|receivedCount
DECL|member|requestCount
DECL|member|requestCount
DECL|member|requestCount
