DECL|class|Widget
DECL|function|Widget
DECL|function|appendFunction
DECL|function|argFunction
DECL|function|arrayOperator
DECL|function|atFunction
DECL|function|boolToString
DECL|function|characterReference
DECL|function|chopFunction
DECL|function|compareFunction
DECL|function|compareSensitiveFunction
DECL|function|constCharArray
DECL|function|constCharPointer
DECL|function|containsFunction
DECL|function|countFunction
DECL|function|dataFunction
DECL|function|endsWithFunction
DECL|function|fillFunction
DECL|function|firstIndexOfFunction
DECL|function|fromRawDataFunction
DECL|function|index
DECL|function|indexOfFunction
DECL|function|insertFunction
DECL|function|isEmptyFunction
DECL|function|isNullFunction
DECL|function|lastIndexOfFunction
DECL|function|leftFunction
DECL|function|leftJustifiedFunction
DECL|function|leftRefFunction
DECL|function|main
DECL|function|midFunction
DECL|function|midRefFunction
DECL|function|modify
DECL|function|nullVsEmpty
DECL|function|numberFunction
DECL|function|plusEqualOperator
DECL|function|prependFunction
DECL|function|removeFunction
DECL|function|replaceFunction
DECL|function|reserveFunction
DECL|function|resizeFunction
DECL|function|rightFunction
DECL|function|rightJustifiedFunction
DECL|function|rightRefFunction
DECL|function|sectionFunction
DECL|function|setNumFunction
DECL|function|simplifiedFunction
DECL|function|sizeFunction
DECL|function|splitCaseSensitiveFunction
DECL|function|splitFunction
DECL|function|sprintfFunction
DECL|function|startsWithFunction
DECL|function|stringLiteral
DECL|function|toDoubleFunction
DECL|function|toFloatFunction
DECL|function|toIntFunction
DECL|function|toLongFunction
DECL|function|toLongLongFunction
DECL|function|toLowerFunction
DECL|function|toShortFunction
DECL|function|toUIntFunction
DECL|function|toULongFunction
DECL|function|toULongLongFunction
DECL|function|toUShortFunction
DECL|function|toUpperFunction
DECL|function|trimmedFunction
DECL|function|truncateFunction
