DECL|class|MyGLWidget
DECL|class|MyGLWidget
DECL|class|MyGLWidget
DECL|function|MyGLWidget
DECL|function|MyGLWidget
DECL|function|cleanup
DECL|function|initializeGL
DECL|function|initializeGL
DECL|function|initializeGL
DECL|function|initializeGL
DECL|function|main
DECL|function|paintGL
DECL|function|paintGL
DECL|function|resizeGL
DECL|function|~MyGLWidget
DECL|member|m_program
DECL|member|m_shader
DECL|member|m_texture
DECL|member|m_vao
DECL|member|m_vbo
DECL|variable|format
DECL|variable|widget
