DECL|function|main
DECL|variable|abortButton
DECL|variable|connectButton
DECL|variable|disconnectButton
DECL|variable|msgBox
DECL|variable|msgBox
DECL|variable|msgBox
DECL|variable|msgBox
DECL|variable|ret
DECL|variable|ret
