DECL|class|CustomItem
DECL|class|CustomItem
DECL|class|QGraphicsPathItem
DECL|class|SimpleItem
DECL|enumerator|Type
DECL|enumerator|Type
DECL|enumerator|Type
DECL|function|CustomItem
DECL|function|boundingRect
DECL|function|boundingRect
DECL|function|contextMenuEvent
DECL|function|dragEnterEvent
DECL|function|itemChange
DECL|function|paint
DECL|function|paint
DECL|function|setRadius
DECL|function|shape
DECL|function|type
DECL|function|type
DECL|function|type
DECL|variable|ObjectName
DECL|variable|deviceRect
DECL|variable|ellipse
DECL|variable|group
DECL|variable|item
DECL|variable|line
DECL|variable|rect
DECL|variable|rect
DECL|variable|scene
DECL|variable|xform
