DECL|class|Window
DECL|function|Window
DECL|function|clean
DECL|function|main
DECL|function|showPoppWindow
DECL|function|triggered
DECL|member|comboBox
DECL|member|echo
DECL|member|explanation
DECL|member|menu
DECL|member|pushButton
DECL|member|toolButton
