DECL|function|Ceiling
DECL|function|Floor
DECL|function|LowBits
DECL|function|Offset
DECL|function|PtrDiff
DECL|macro|CHUNK_OVERHEAD
DECL|macro|HEAP_ASSERT
DECL|macro|MALLOC_ALIGNMENT
DECL|macro|NSMALLBINS
DECL|macro|NTREEBINS
DECL|macro|USE_HYBRID_HEAP
DECL|macro|USE_HYBRID_HEAP
DECL|macro|__HEAP_HYBRID_H__
DECL|member|iBase
DECL|member|iDv
DECL|member|iDvSize
DECL|member|iSeg
DECL|member|iSize
DECL|member|iSmallBins
DECL|member|iSmallMap
DECL|member|iTop
DECL|member|iTopSize
DECL|member|iTreeBins
DECL|member|iTreeMap
DECL|member|iTrimCheck
DECL|struct|malloc_segment
DECL|struct|malloc_state
DECL|typedef|bindex_t
DECL|typedef|binmap_t
DECL|typedef|mchunkptr
DECL|typedef|msegment
DECL|typedef|mstate
DECL|typedef|tbinptr
DECL|typedef|tchunkptr
DECL|variable|T1
