DECL|function|Addr
DECL|function|Alloc
DECL|function|Alloc
DECL|function|Alloc
DECL|function|AllocLen
DECL|function|AllocLen
DECL|function|AllocNewPage
DECL|function|AllocNewSlab
DECL|function|AllocSize
DECL|function|AllocSize
DECL|function|Available
DECL|function|Available
DECL|function|Bitmap2addr
DECL|function|Bits
DECL|function|CheckBitmap
DECL|function|ChunkHandle
DECL|function|ChunkHandle
DECL|function|ChunkHeap
DECL|function|ChunkHeap
DECL|function|ChunkHeap
DECL|function|Compress
DECL|function|Compress
DECL|function|ComputeBit2idx
DECL|function|ComputeTreeIndex
DECL|function|Construct
DECL|function|ConstructLock
DECL|function|CreateThreadHeap
DECL|function|DebugFunction
DECL|function|DlFree
DECL|function|DlInfo
DECL|function|DlMalloc
DECL|function|DlRealloc
DECL|function|DoComputeTreeIndex
DECL|function|Extension_
DECL|function|Extension_
DECL|function|Find
DECL|function|FixedHeap
DECL|function|Free
DECL|function|Free
DECL|function|FreePage
DECL|function|FreeSlab
DECL|function|GetInfo
DECL|function|Init
DECL|function|Init
DECL|function|InitBins
DECL|function|InitDlMalloc
DECL|function|InitNewSlab
DECL|function|InitTop
DECL|function|InsertChunk
DECL|function|InsertLargeChunk
DECL|function|InsertSmallChunk
DECL|function|Is
DECL|function|Lock
DECL|function|Map
DECL|function|OffsetChunkHeap
DECL|function|PagedAllocate
DECL|function|PagedDecode
DECL|function|PagedEncode
DECL|function|PagedFree
DECL|function|PagedInfo
DECL|function|PagedInit
DECL|function|PagedReallocate
DECL|function|PagedSetSize
DECL|function|PagedSize
DECL|function|PagedZapSize
DECL|function|RHybridHeap
DECL|function|RHybridHeap
DECL|function|RHybridHeap
DECL|function|ReAlloc
DECL|function|ReAlloc
DECL|function|ReAllocImpl
DECL|function|ReplaceDv
DECL|function|Reset
DECL|function|Reset
DECL|function|ResetBitmap
DECL|function|Set
DECL|function|Set
DECL|function|SetCreateChunk
DECL|function|SetUseChunk
DECL|function|Setn
DECL|function|Size
DECL|function|SlabAllocate
DECL|function|SlabConfig
DECL|function|SlabEmptyInfo
DECL|function|SlabFor
DECL|function|SlabFree
DECL|function|SlabFullInfo
DECL|function|SlabInfo
DECL|function|SlabInit
DECL|function|SlabPartialInfo
DECL|function|SysAlloc
DECL|function|SysTrim
DECL|function|TChunkHeapCreateInfo
DECL|function|TmallocLarge
DECL|function|TmallocSmall
DECL|function|TreeInsert
DECL|function|TreeRemove
DECL|function|TreeWalk
DECL|function|UnlinkChunk
DECL|function|UnlinkFirstSmallChunk
DECL|function|UnlinkLargeChunk
DECL|function|UnlinkSmallChunk
DECL|function|Unlock
DECL|function|Unmap
DECL|function|operator []
DECL|function|operator delete
DECL|function|paged_codelen
DECL|function|paged_coding
DECL|macro|DELAYED_SLAB_THRESHOLD
DECL|macro|GM
DECL|macro|IMPORT_D
DECL|macro|IMPORT_D
DECL|macro|IS_FIXED_HEAP
DECL|macro|MEMORY_MONITORED
DECL|macro|SLAB_CONFIG
DECL|macro|UserTestDebugMaskBit
DECL|macro|__ALLOC_DEBUG_HEADER
DECL|macro|__ALLOC_DEBUG_HEADER
DECL|macro|__DEBUG_HDR_SIZE
DECL|macro|__DEBUG_HDR_SIZE
DECL|macro|__DEBUG_RESTORE
DECL|macro|__DEBUG_RESTORE
DECL|macro|__DEBUG_SAVE
DECL|macro|__DEBUG_SAVE
DECL|macro|__DECREMENT_COUNTERS
DECL|macro|__DECREMENT_COUNTERS
DECL|macro|__DL_BFR_CHECK
DECL|macro|__GET_AVAIL_BLOCK_SIZE
DECL|macro|__GET_AVAIL_BLOCK_SIZE
DECL|macro|__GET_DEBUG_DATA_BFR
DECL|macro|__GET_DEBUG_DATA_BFR
DECL|macro|__GET_USER_DATA_BFR
DECL|macro|__GET_USER_DATA_BFR
DECL|macro|__INCREMENT_COUNTERS
DECL|macro|__INCREMENT_COUNTERS
DECL|macro|__INIT_COUNTERS
DECL|macro|__INIT_COUNTERS
DECL|macro|__INIT_COUNTERS
DECL|macro|__PAGE_BFR_CHECK
DECL|macro|__POWER_OF_2
DECL|macro|__REMOVE_DBG_HDR
DECL|macro|__REMOVE_DBG_HDR
DECL|macro|__SET_DEBUG_DATA
DECL|macro|__SET_DEBUG_DATA
DECL|macro|__SIMULATE_ALLOC_FAIL
DECL|macro|__SIMULATE_ALLOC_FAIL
DECL|macro|__SLAB_BFR_CHECK
DECL|macro|__UPDATE_ALLOC_COUNT
DECL|macro|__UPDATE_ALLOC_COUNT
DECL|macro|__UPDATE_TOTAL_ALLOC
DECL|macro|__UPDATE_TOTAL_ALLOC
DECL|macro|__ZAP_CELL
DECL|macro|__ZAP_CELL
DECL|member|code
DECL|member|codelen
DECL|member|len
DECL|member|offset
DECL|struct|etab
DECL|variable|encode_table
DECL|variable|slab_bitcount
DECL|variable|slab_ext_frag
