DECL|function|HeaderFloating
DECL|function|PageFor
DECL|macro|CELLALIGN
DECL|macro|CHECKSLAB
DECL|macro|CHECKSLAB
DECL|macro|CHECKSLABBFR
DECL|macro|CHECKSLABBFR
DECL|macro|CHECKTREE
DECL|macro|CHECKTREE
DECL|macro|FLOATING_BIT
DECL|macro|HIBIT
DECL|macro|LOWBIT
DECL|macro|MAXSLABSIZE
DECL|macro|MAXUSEDM4BITS
DECL|macro|PAGESHIFT
DECL|macro|PAGESIZE
DECL|macro|SLABSHIFT
DECL|macro|SLABSIZE
DECL|macro|ZEROBITS
DECL|variable|KMaxSlabPayload
DECL|variable|firstpos
DECL|variable|maxuse
DECL|variable|slab
DECL|variable|slabfull
DECL|variable|slabhdr
DECL|variable|slabsperpage
