DECL|function|acceptAction
DECL|function|acceptActionGroup
DECL|function|acceptActionRef
DECL|function|acceptButtonGroup
DECL|function|acceptButtonGroups
DECL|function|acceptColor
DECL|function|acceptColorGroup
DECL|function|acceptConnection
DECL|function|acceptConnectionHint
DECL|function|acceptConnectionHints
DECL|function|acceptConnections
DECL|function|acceptCustomWidget
DECL|function|acceptCustomWidgets
DECL|function|acceptDate
DECL|function|acceptDateTime
DECL|function|acceptFont
DECL|function|acceptImage
DECL|function|acceptImages
DECL|function|acceptInclude
DECL|function|acceptIncludes
DECL|function|acceptLayout
DECL|function|acceptLayoutDefault
DECL|function|acceptLayoutFunction
DECL|function|acceptLayoutItem
DECL|function|acceptPalette
DECL|function|acceptPoint
DECL|function|acceptProperty
DECL|function|acceptRect
DECL|function|acceptSize
DECL|function|acceptSizePolicy
DECL|function|acceptSpacer
DECL|function|acceptTabStops
DECL|function|acceptTime
DECL|function|acceptUI
DECL|function|acceptWidget
DECL|function|acceptWidgetScripts
