DECL|function|QSpiAccessibleBridge
DECL|function|dBusConnection
DECL|function|enabledChanged
DECL|function|initializeConstantMappings
DECL|function|notifyAccessibilityUpdate
DECL|function|updateStatus
DECL|function|~QSpiAccessibleBridge
DECL|member|name
DECL|member|role
DECL|member|spiRole
DECL|struct|RoleMapping
DECL|variable|map
