DECL|function|DBusConnection
DECL|function|connectA11yBus
DECL|function|connection
DECL|function|dbusError
DECL|function|getAddressFromXCB
DECL|function|serviceRegistered
DECL|function|serviceUnregistered
DECL|macro|A11Y_PATH
DECL|macro|A11Y_SERVICE
