DECL|enumerator|QSPI_APP_UPDATE_ADDED
DECL|enumerator|QSPI_APP_UPDATE_REMOVED
DECL|enum|QSpiAppUpdateType
DECL|function|QSpiObjectReference
DECL|macro|Q_SPI_STRUCT_MARSHALLERS_H
DECL|member|address
DECL|member|application
DECL|member|children
DECL|member|contents
DECL|member|description
DECL|member|description
DECL|member|endOffset
DECL|member|eventName
DECL|member|hardwareCode
DECL|member|id
DECL|member|isText
DECL|member|keyBinding
DECL|member|listenerAddress
DECL|member|modifiers
DECL|member|name
DECL|member|name
DECL|member|parent
DECL|member|path
DECL|member|path
DECL|member|role
DECL|member|service
DECL|member|startOffset
DECL|member|state
DECL|member|supportedInterfaces
DECL|member|text
DECL|member|timestamp
DECL|member|type
DECL|member|type
DECL|member|v
DECL|struct|QSpiAccessibleCacheItem
DECL|struct|QSpiAction
DECL|struct|QSpiAppUpdate
DECL|struct|QSpiDeviceEvent
DECL|struct|QSpiEventListener
DECL|struct|QSpiObjectReference
DECL|struct|QSpiTextRange
DECL|typedef|QSpiAccessibleCacheArray
DECL|typedef|QSpiActionArray
DECL|typedef|QSpiAttributeSet
DECL|typedef|QSpiEventListenerArray
DECL|typedef|QSpiIntList
DECL|typedef|QSpiObjectReferenceArray
DECL|typedef|QSpiRelationArray
DECL|typedef|QSpiRelationArrayEntry
DECL|typedef|QSpiTextRangeList
DECL|typedef|QSpiUIntList
DECL|typedef|QString
