DECL|macro|QCOLORDIALOG_P_H
DECL|variable|QColorLuminancePicker
DECL|variable|QColorPicker
DECL|variable|QColorShower
DECL|variable|QDialogButtonBox
DECL|variable|QLabel
DECL|variable|QPushButton
DECL|variable|QVBoxLayout
DECL|variable|QWellArray
