DECL|function|QFileDialogArgs
DECL|function|deleteNativeDialog_sys
DECL|function|dialogResultCode_sys
DECL|function|directory_sys
DECL|function|mapFromSource
DECL|function|mapToSource
DECL|function|rootPath
DECL|function|selectFile_sys
DECL|function|selectNameFilter_sys
DECL|function|selectedFiles_sys
DECL|function|selectedNameFilter_sys
DECL|function|setDirectory_sys
DECL|function|setFilter_sys
DECL|function|setNameFilters_sys
DECL|function|setVisible_sys
DECL|macro|QFILEDIALOG_P_H
DECL|macro|UrlRole
DECL|member|caption
DECL|member|directory
DECL|member|filter
DECL|member|mode
DECL|member|options
DECL|member|parent
DECL|member|selection
DECL|struct|QFileDialogArgs
DECL|variable|QCompleter
DECL|variable|QFileDialogLineEdit
DECL|variable|QFileDialogListView
DECL|variable|QFileDialogTreeView
DECL|variable|QGridLayout
DECL|variable|QHBoxLayout
DECL|variable|Ui_QFileDialog
