DECL|function|QSidebar
DECL|function|QUrlModel
DECL|function|addUrls
DECL|function|canDrop
DECL|function|changed
DECL|function|clicked
DECL|function|dataChanged
DECL|function|dragEnterEvent
DECL|function|dropMimeData
DECL|function|event
DECL|function|flags
DECL|function|focusInEvent
DECL|function|init
DECL|function|initStyleOption
DECL|function|layoutChanged
DECL|function|mimeData
DECL|function|mimeTypes
DECL|function|removeEntry
DECL|function|selectUrl
DECL|function|setData
DECL|function|setFileSystemModel
DECL|function|setUrl
DECL|function|setUrls
DECL|function|showContextMenu
DECL|function|sizeHint
DECL|function|urls
DECL|function|~QSidebar
