DECL|macro|QXCBDRAG_H
DECL|variable|QDrag
DECL|variable|QMouseEvent
DECL|variable|QShapedPixmapWindow
DECL|variable|QWindow
DECL|variable|QXcbConnection
DECL|variable|QXcbDropData
DECL|variable|QXcbObject
DECL|variable|QXcbScreen
DECL|variable|QXcbWindow
