DECL|class|QXcbShmImage
DECL|function|QXcbShmImage
DECL|function|QXcbWindowSurface
DECL|function|beginPaint
DECL|function|destroy
DECL|function|endPaint
DECL|function|flush
DECL|function|image
DECL|function|paintDevice
DECL|function|preparePaint
DECL|function|put
DECL|function|resize
DECL|function|scroll
DECL|function|~QXcbShmImage
DECL|function|~QXcbWindowSurface
DECL|member|m_dirty
DECL|member|m_gc
DECL|member|m_gc_window
DECL|member|m_qimage
DECL|member|m_shm_info
DECL|member|m_xcb_image
