DECL|class|ClientMessageScanner
DECL|class|QDropData
DECL|function|ClientMessageScanner
DECL|function|QDropData
DECL|function|QXcbDrag
DECL|function|cancel
DECL|function|check
DECL|function|dndEnable
DECL|function|drop
DECL|function|formats_sys
DECL|function|handleDrop
DECL|function|handleEnter
DECL|function|handleLeave
DECL|function|handlePosition
DECL|function|handleStatus
DECL|function|handle_xdnd_position
DECL|function|handle_xdnd_status
DECL|function|hasFormat_sys
DECL|function|move
DECL|function|platformDropData
DECL|function|retrieveData_sys
DECL|function|startDrag
DECL|function|toDropAction
DECL|function|toXdndAction
DECL|function|xcb_window
DECL|function|xdndObtainData
DECL|function|xdndProxy
DECL|function|~QDropData
DECL|function|~QXcbDrag
DECL|macro|ATOM
DECL|macro|ATOM
DECL|macro|DEBUG
DECL|macro|DNDDEBUG
DECL|macro|DND_DEBUG
DECL|member|atom
DECL|member|drag
DECL|variable|xdnd_version
