DECL|function|QXcbIntegration
DECL|function|clipboard
DECL|function|createPixmapData
DECL|function|createPlatformBackingStore
DECL|function|createPlatformGLContext
DECL|function|createPlatformWindow
DECL|function|drag
DECL|function|fontDatabase
DECL|function|grabWindow
DECL|function|hasCapability
DECL|function|hasOpenGL
DECL|function|isVirtualDesktop
DECL|function|moveToScreen
DECL|function|nativeInterface
DECL|function|printerSupport
DECL|function|screens
DECL|function|~QXcbIntegration
