DECL|function|XInput2DeviceData
DECL|function|deviceForId
DECL|function|finalizeXInput2
DECL|function|fixed1616ToReal
DECL|function|initializeXInput2
DECL|function|valuatorNormalized
DECL|function|xi2HandleEvent
DECL|function|xi2HandleTabletEvent
DECL|function|xi2ReportTabletEvent
DECL|function|xi2Select
DECL|macro|FINGER_MAX_WIDTH_MM
DECL|member|qtTouchDevice
DECL|member|xiDeviceInfo
DECL|struct|XInput2DeviceData
