DECL|function|QXcbIntegration
DECL|function|accessibility
DECL|function|argv0BaseName
DECL|function|clipboard
DECL|function|createEventDispatcher
DECL|function|createPlatformBackingStore
DECL|function|createPlatformOffscreenSurface
DECL|function|createPlatformOpenGLContext
DECL|function|createPlatformSessionManager
DECL|function|createPlatformTheme
DECL|function|createPlatformWindow
DECL|function|drag
DECL|function|fontDatabase
DECL|function|hasCapability
DECL|function|initialize
DECL|function|inputContext
DECL|function|moveToScreen
DECL|function|nativeInterface
DECL|function|possibleKeys
DECL|function|queryKeyboardModifiers
DECL|function|runningUnderDebugger
DECL|function|services
DECL|function|styleHint
DECL|function|sync
DECL|function|themeNames
DECL|function|wmClass
DECL|function|~QXcbIntegration
DECL|variable|resourceNameVar
