DECL|class|ClientMessageScanner
DECL|class|QXcbDropData
DECL|function|ClientMessageScanner
DECL|function|QXcbDrag
DECL|function|QXcbDropData
DECL|function|cancel
DECL|function|checkEvent
DECL|function|dndEnable
DECL|function|drop
DECL|function|endDrag
DECL|function|findRealWindow
DECL|function|findTransactionByTime
DECL|function|findTransactionByWindow
DECL|function|formats_sys
DECL|function|handleDrop
DECL|function|handleEnter
DECL|function|handleFinished
DECL|function|handleLeave
DECL|function|handlePosition
DECL|function|handleSelectionRequest
DECL|function|handleStatus
DECL|function|handle_xdnd_position
DECL|function|handle_xdnd_status
DECL|function|hasFormat_sys
DECL|function|init
DECL|function|move
DECL|function|platformDropData
DECL|function|retrieveData_sys
DECL|function|send_leave
DECL|function|startDrag
DECL|function|timerEvent
DECL|function|toDropAction
DECL|function|toXdndAction
DECL|function|translateCoordinates
DECL|function|windowInteractsWithPosition
DECL|function|xcb_window
DECL|function|xdndObtainData
DECL|function|xdndProxy
DECL|function|~QXcbDrag
DECL|function|~QXcbDropData
DECL|macro|DEBUG
DECL|macro|DNDDEBUG
DECL|member|atom
DECL|member|drag
DECL|variable|xdnd_version
