DECL|function|XInput2Data
DECL|function|count_bits
DECL|function|finalizeXInput2
DECL|function|getValuatorValueIfSet
DECL|function|handleGenericEvent
DECL|function|initializeXInput2
DECL|function|isUsingXInput2
DECL|member|allTouchPoints
DECL|member|use_xinput
DECL|member|xiMaxContacts
DECL|member|xibuttonclassinfo
DECL|member|xideviceinfo
DECL|member|xinput_errorbase
DECL|member|xinput_eventbase
DECL|member|xinput_opcode
DECL|struct|XInput2Data
