DECL|function|checkEvent
DECL|function|q_xcb_call_template
DECL|macro|DISPLAY_FROM_XCB
DECL|macro|EGL_DISPLAY_FROM_XCB
DECL|macro|QXCBCONNECTION_H
DECL|macro|Q_XCB_CALL
DECL|macro|Q_XCB_CALL
DECL|macro|Q_XCB_CALL2
DECL|macro|Q_XCB_CALL2
DECL|macro|Q_XCB_NOOP
DECL|macro|Q_XCB_NOOP
DECL|macro|XCB_USE_XINPUT22
DECL|macro|explicit
DECL|macro|explicit
DECL|typedef|QXcbEventArray
DECL|typedef|WindowMapper
DECL|typedef|xcb_generic_event_t
DECL|typedef|xcb_window_t
DECL|variable|QAbstractEventDispatcher
DECL|variable|QXcbClipboard
DECL|variable|QXcbConnection
DECL|variable|QXcbDrag
DECL|variable|QXcbKeyboard
DECL|variable|QXcbNativeInterface
DECL|variable|QXcbScreen
DECL|variable|QXcbSystemTrayTracker
DECL|variable|QXcbWMSupport
DECL|variable|QXcbWindow
