DECL|function|QXcbScreen
DECL|function|cursor
DECL|function|depthOfVisual
DECL|function|format
DECL|function|grabWindow
DECL|function|handleScreenChange
DECL|function|logicalDpi
DECL|function|parseXftHintStyle
DECL|function|parseXftInt
DECL|function|parseXftRgba
DECL|function|readXResources
DECL|function|sendStartupMessage
DECL|function|topLevelAt
DECL|function|updateGeometry
DECL|function|updateRefreshRate
DECL|function|visualForId
DECL|function|windowShown
DECL|function|xResource
DECL|function|xSettings
DECL|function|~QXcbScreen
