DECL|class|QXcbXSettingsCallback
DECL|class|QXcbXSettingsPrivate
DECL|class|QXcbXSettingsPropertyValue
DECL|enumerator|XSettingsTypeColor
DECL|enumerator|XSettingsTypeInteger
DECL|enumerator|XSettingsTypeString
DECL|enum|XSettingsType
DECL|function|QXcbXSettings
DECL|function|QXcbXSettingsPrivate
DECL|function|QXcbXSettingsPropertyValue
DECL|function|addCallback
DECL|function|getSettings
DECL|function|handlePropertyNotifyEvent
DECL|function|initialized
DECL|function|populateSettings
DECL|function|registerCallbackForProperty
DECL|function|removeCallbackForHandle
DECL|function|removeCallbackForHandle
DECL|function|round_to_nearest_multiple_of_4
DECL|function|setting
DECL|function|updateValue
DECL|function|~QXcbXSettings
DECL|macro|ADJUST_BO
DECL|macro|VALIDATE_LENGTH
DECL|member|callback_links
DECL|member|func
DECL|member|handle
DECL|member|initialized
DECL|member|last_change_serial
DECL|member|screen
DECL|member|settings
DECL|member|value
DECL|member|x_settings_window
