DECL|class|ClipboardEvent
DECL|class|INCRTransaction
DECL|class|Notify
DECL|class|QXcbClipboardMime
DECL|function|ClipboardEvent
DECL|function|INCRTransaction
DECL|function|Notify
DECL|function|QXcbClipboard
DECL|function|QXcbClipboardMime
DECL|function|atomForMode
DECL|function|checkEvent
DECL|function|checkEvent
DECL|function|clipboardReadIncrementalProperty
DECL|function|clipboardReadProperty
DECL|function|formats_sys
DECL|function|getDataInFormat
DECL|function|getSelection
DECL|function|getSelectionOwner
DECL|function|handleSelectionClearRequest
DECL|function|handleSelectionRequest
DECL|function|handleXFixesSelectionRequest
DECL|function|hasFormat_sys
DECL|function|incrTransactionPeeker
DECL|function|isEmpty
DECL|function|maxSelectionIncr
DECL|function|mimeData
DECL|function|modeForAtom
DECL|function|owner
DECL|function|ownsMode
DECL|function|requestor
DECL|function|reset
DECL|function|retrieveData_sys
DECL|function|sendSelection
DECL|function|sendTargetsSelection
DECL|function|setMimeData
DECL|function|setRequestor
DECL|function|supportsMode
DECL|function|timerEvent
DECL|function|updateIncrProperty
DECL|function|waitForClipboardEvent
DECL|function|~INCRTransaction
DECL|function|~QXcbClipboard
DECL|macro|class
DECL|macro|class
DECL|member|abort_timer
DECL|member|clipboard
DECL|member|clipboard_timeout
DECL|member|conn
DECL|member|data
DECL|member|format
DECL|member|formatList
DECL|member|format_atoms
DECL|member|increment
DECL|member|m_clipboard
DECL|member|modeAtom
DECL|member|offset
DECL|member|property
DECL|member|target
DECL|member|timeout
DECL|member|type
DECL|member|win
DECL|member|window
DECL|typedef|TransactionMap
DECL|variable|transactions
