DECL|class|ClipboardEvent
DECL|class|Notify
DECL|class|QXcbClipboardMime
DECL|function|ClipboardEvent
DECL|function|Notify
DECL|function|QXcbClipboard
DECL|function|QXcbClipboardMime
DECL|function|check
DECL|function|check
DECL|function|clipboardReadIncrementalProperty
DECL|function|clipboardReadProperty
DECL|function|empty
DECL|function|formats_sys
DECL|function|getDataInFormat
DECL|function|getSelectionOwner
DECL|function|handleSelectionRequest
DECL|function|hasFormat_sys
DECL|function|maxSelectionIncr
DECL|function|mimeData
DECL|function|owner
DECL|function|requestor
DECL|function|retrieveData_sys
DECL|function|sendSelection
DECL|function|sendTargetsSelection
DECL|function|setMimeData
DECL|function|setOwner
DECL|function|setRequestor
DECL|function|supportsMode
DECL|function|waitForClipboardEvent
DECL|member|clipboard
DECL|member|clipboard_timeout
DECL|member|formatList
DECL|member|format_atoms
DECL|member|m_clipboard
DECL|member|modeAtom
DECL|member|type
DECL|member|window
