DECL|function|QXcbScreen
DECL|function|QXcbVirtualDesktop
DECL|function|addScreen
DECL|function|compositingActive
DECL|function|cursor
DECL|function|depthOfVisual
DECL|function|format
DECL|function|formatRect
DECL|function|formatSizeF
DECL|function|grabWindow
DECL|function|handleScreenChange
DECL|function|handleXFixesSelectionNotify
DECL|function|logicalDpi
DECL|function|operator <<
DECL|function|parseXftHintStyle
DECL|function|parseXftInt
DECL|function|parseXftRgba
DECL|function|pixelDensity
DECL|function|readXResources
DECL|function|screenAt
DECL|function|sendStartupMessage
DECL|function|subscribeToXFixesSelectionNotify
DECL|function|topLevelAt
DECL|function|updateGeometry
DECL|function|updateGeometry
DECL|function|updateRefreshRate
DECL|function|virtualDpi
DECL|function|visualForId
DECL|function|windowShown
DECL|function|xResource
DECL|function|xSettings
DECL|function|xSettings
DECL|function|~QXcbScreen
DECL|function|~QXcbVirtualDesktop
