DECL|function|QXcbMime
DECL|function|mimeAtomForFormat
DECL|function|mimeAtomToString
DECL|function|mimeAtomsForFormat
DECL|function|mimeConvertToFormat
DECL|function|mimeDataForAtom
DECL|function|~QXcbMime
DECL|macro|XCB_ATOM_BITMAP
DECL|macro|XCB_ATOM_PIXMAP
DECL|macro|XCB_ATOM_STRING
