DECL|class|KeyPressTransition
DECL|class|LightningStrikesTransition
DECL|function|KeyPressTransition
DECL|function|KeyPressTransition
DECL|function|LifeCycle
DECL|function|LightningStrikesTransition
DECL|function|addActivity
DECL|function|eventTest
DECL|function|eventTest
DECL|function|makeState
DECL|function|setDeathAnimation
DECL|function|start
DECL|function|~LifeCycle
DECL|member|m_key
