DECL|function|QFbCursor
DECL|function|changeCursor
DECL|function|dirtyRect
DECL|function|drawCursor
DECL|function|getCurrentRect
DECL|function|hasMouse
DECL|function|onDeviceListChanged
DECL|function|pointerEvent
DECL|function|pos
DECL|function|setCursor
DECL|function|setCursor
DECL|function|setCursor
DECL|function|setDirty
DECL|function|setPos
DECL|function|updateMouseStatus
DECL|function|~QFbCursor
