DECL|function|QFbScreen
DECL|function|addWindow
DECL|function|doRedraw
DECL|function|generateRects
DECL|function|initializeCompositor
DECL|function|lower
DECL|function|raise
DECL|function|removeWindow
DECL|function|setDirty
DECL|function|setGeometry
DECL|function|setPhysicalSize
DECL|function|topLevelAt
DECL|function|topWindow
DECL|function|~QFbScreen
