DECL|function|QFbVtHandler
DECL|function|handleInt
DECL|function|handleSignal
DECL|function|restoreKeyboard
DECL|function|suspend
DECL|function|~QFbVtHandler
DECL|macro|KBD_OFF_MODE
DECL|macro|KBD_OFF_MODE
DECL|macro|KDSKBMUTE
DECL|macro|VTH_ENABLED
