DECL|function|QFbWindow
DECL|function|lower
DECL|function|raise
DECL|function|repaint
DECL|function|setGeometry
DECL|function|setVisible
DECL|function|setWindowFlags
DECL|function|windowFlags
DECL|function|~QFbWindow
