DECL|function|QAction
DECL|function|QAction
DECL|function|QAction
DECL|function|QAction
DECL|function|QActionPrivate
DECL|function|actionGroup
DECL|function|activate
DECL|function|associatedGraphicsWidgets
DECL|function|associatedWidgets
DECL|function|autoRepeat
DECL|function|data
DECL|function|event
DECL|function|font
DECL|function|icon
DECL|function|iconText
DECL|function|isCheckable
DECL|function|isChecked
DECL|function|isEnabled
DECL|function|isIconVisibleInMenu
DECL|function|isSeparator
DECL|function|isVisible
DECL|function|menu
DECL|function|menuRole
DECL|function|parentWidget
DECL|function|priority
DECL|function|qt_strippedText
DECL|function|redoGrab
DECL|function|redoGrabAlternate
DECL|function|sendDataChanged
DECL|function|setActionGroup
DECL|function|setAutoRepeat
DECL|function|setCheckable
DECL|function|setChecked
DECL|function|setData
DECL|function|setEnabled
DECL|function|setFont
DECL|function|setIcon
DECL|function|setIconText
DECL|function|setIconVisibleInMenu
DECL|function|setMenu
DECL|function|setMenuRole
DECL|function|setPriority
DECL|function|setSeparator
DECL|function|setShortcut
DECL|function|setShortcutContext
DECL|function|setShortcutEnabled
DECL|function|setShortcuts
DECL|function|setShortcuts
DECL|function|setStatusTip
DECL|function|setText
DECL|function|setToolTip
DECL|function|setVisible
DECL|function|setWhatsThis
DECL|function|shortcut
DECL|function|shortcutContext
DECL|function|shortcuts
DECL|function|showStatusText
DECL|function|showStatusText
DECL|function|statusTip
DECL|function|text
DECL|function|toggle
DECL|function|toolTip
DECL|function|whatsThis
DECL|function|~QAction
DECL|function|~QActionPrivate
DECL|macro|QAPP_CHECK
