DECL|enumerator|QT_TABLET_NPACKETQSIZE
DECL|function|scaleCoord
DECL|function|sign
DECL|macro|QAPPLICATION_P_H
DECL|macro|QApplicationPrivateBase
DECL|member|maxPressure
DECL|member|maxTanPressure
DECL|member|maxX
DECL|member|maxY
DECL|member|maxZ
DECL|member|minPressure
DECL|member|minTanPressure
DECL|member|minX
DECL|member|minY
DECL|member|minZ
DECL|struct|QFont
DECL|struct|QTabletDeviceData
DECL|struct|QWSServerCleaner
DECL|typedef|PaletteHash
DECL|typedef|QByteArray
DECL|typedef|QMacTabletHash
DECL|typedef|QTabletDeviceDataList
DECL|variable|QByteArray
DECL|variable|QClipboard
DECL|variable|QDirectPainter
DECL|variable|QGestureManager
DECL|variable|QGraphicsScene
DECL|variable|QInputContext
DECL|variable|QObject
DECL|variable|QSocketNotifier
DECL|variable|QTouchDevice
DECL|variable|QWSManager
DECL|variable|QWidget
