DECL|class|QSessionManagerPrivate
DECL|function|FontHash
DECL|function|QApplication
DECL|function|QApplication
DECL|function|QApplication
DECL|function|QApplication
DECL|function|QApplication
DECL|function|QApplication
DECL|function|QApplication
DECL|function|QApplication
DECL|function|QApplication
DECL|function|QApplication
DECL|function|QApplicationPrivate
DECL|function|QSessionManager
DECL|function|aboutQt
DECL|function|activeModalWidget
DECL|function|activePopupWidget
DECL|function|activeWindow
DECL|function|allWidgets
DECL|function|allowsErrorInteraction
DECL|function|allowsInteraction
DECL|function|autoMaximizeThreshold
DECL|function|autoSipEnabled
DECL|function|cancel
DECL|function|cleanupMultitouch
DECL|function|closeAllWindows
DECL|function|colorSpec
DECL|function|commitData
DECL|function|compressEvent
DECL|function|construct
DECL|function|cursorFlashTime
DECL|function|desktop
DECL|function|desktopSettingsAware
DECL|function|desktopStyleKey
DECL|function|discardCommand
DECL|function|dispatchEnterLeave
DECL|function|doubleClickInterval
DECL|function|enterModal
DECL|function|event
DECL|function|exec
DECL|function|findClosestTouchPointTarget
DECL|function|focusNextPrevChild_helper
DECL|function|focusWidget
DECL|function|font
DECL|function|font
DECL|function|font
DECL|function|fontMetrics
DECL|function|giveFocusAccordingToFocusPolicy
DECL|function|globalStrut
DECL|function|handle
DECL|function|inPopupMode
DECL|function|initResources
DECL|function|initialize
DECL|function|initializeMultitouch
DECL|function|instance
DECL|function|isAlien
DECL|function|isBlockedByModal
DECL|function|isPhase2
DECL|function|isSessionRestored
DECL|function|keyboardInputDirection
DECL|function|keyboardInputInterval
DECL|function|keyboardInputLocale
DECL|function|keyboardModifiers
DECL|function|keypadNavigationEnabled
DECL|function|leaveModal
DECL|function|mouseButtons
DECL|function|navigationMode
DECL|function|notify
DECL|function|notifyLayoutDirectionChange
DECL|function|notify_helper
DECL|function|palette
DECL|function|palette
DECL|function|pickMouseReceiver
DECL|function|process_cmdline
DECL|function|qt_CoCreateGuid
DECL|function|qt_app_fonts_hash
DECL|function|qt_app_palettes_hash
DECL|function|qt_matchLibraryName
DECL|function|qt_sendSpontaneousEvent
DECL|function|qt_tryModalHelper
DECL|function|queryKeyboardModifiers
DECL|function|release
DECL|function|requestPhase2
DECL|function|restartCommand
DECL|function|restartHint
DECL|function|saveState
DECL|function|sendMouseEvent
DECL|function|sendSyntheticEnterLeave
DECL|function|sessionId
DECL|function|sessionId
DECL|function|sessionKey
DECL|function|sessionKey
DECL|function|setActiveWindow
DECL|function|setAutoMaximizeThreshold
DECL|function|setAutoSipEnabled
DECL|function|setColorSpec
DECL|function|setCursorFlashTime
DECL|function|setDesktopSettingsAware
DECL|function|setDiscardCommand
DECL|function|setDoubleClickInterval
DECL|function|setFocusWidget
DECL|function|setFont
DECL|function|setGlobalStrut
DECL|function|setKeyboardInputInterval
DECL|function|setKeypadNavigationEnabled
DECL|function|setManagerProperty
DECL|function|setManagerProperty
DECL|function|setNavigationMode
DECL|function|setPalette
DECL|function|setPalette_helper
DECL|function|setRestartCommand
DECL|function|setRestartHint
DECL|function|setStartDragDistance
DECL|function|setStartDragTime
DECL|function|setStyle
DECL|function|setStyle
DECL|function|setStyleSheet
DECL|function|setSystemFont
DECL|function|setSystemPalette
DECL|function|setWindowIcon
DECL|function|shouldSetFocus
DECL|function|startDragDistance
DECL|function|startDragTime
DECL|function|style
DECL|function|styleSheet
DECL|function|syncX
DECL|function|topLevelWidgets
DECL|function|translateRawTouchEvent
DECL|function|translateTouchCancel
DECL|function|tryModalHelper
DECL|function|type
DECL|function|updateTouchPointsForWidget
DECL|function|widgetAt
DECL|function|windowIcon
DECL|function|~QApplication
DECL|function|~QApplicationPrivate
DECL|function|~QSessionManager
DECL|macro|CoCreateGuid
DECL|member|active_window
DECL|member|animate_combo
DECL|member|animate_menu
DECL|member|animate_toolbox
DECL|member|animate_tooltip
DECL|member|animate_ui
DECL|member|app_cspec
DECL|member|app_icon
DECL|member|app_strut
DECL|member|app_style
DECL|member|autoMaximizeThreshold
DECL|member|autoSipEnabled
DECL|member|autoSipEnabled
DECL|member|discardCommand
DECL|member|fade_menu
DECL|member|fade_tooltip
DECL|member|focus_widget
DECL|member|hidden_focus_widget
DECL|member|leaveAfterRelease
DECL|member|load_testability
DECL|member|main_widget
DECL|member|modifier_buttons
DECL|member|mouse_buttons
DECL|member|navigationMode
DECL|member|obey_desktop_settings
DECL|member|oldEditFocus
DECL|member|popupWidgets
DECL|member|restartCommand
DECL|member|restartHint
DECL|member|self
DECL|member|sessionId
DECL|member|sessionKey
DECL|member|set_font
DECL|member|set_pal
DECL|member|styleOverride
DECL|member|styleSheet
DECL|member|sys_font
DECL|member|sys_pal
DECL|member|wheel_scroll_lines
DECL|member|widgetCount
DECL|variable|aargc
DECL|variable|aargv
DECL|variable|app_do_modal
DECL|variable|qt_antialiasing_threshold
DECL|variable|qt_desktopWidget
DECL|variable|qt_in_tab_key_event
DECL|variable|qt_modal_stack
DECL|variable|qt_session_manager_self
DECL|variable|qt_tab_all_widgets
DECL|variable|qt_tabletChokeMouse
