DECL|macro|QAPPLICATION_H
DECL|macro|QApplicationBase
DECL|macro|QApplicationBase
DECL|macro|qApp
DECL|macro|qApp
DECL|variable|CApaApplication
DECL|variable|QApplication
DECL|variable|QApplicationPrivate
DECL|variable|QDecoration
DECL|variable|QDesktopWidget
DECL|variable|QEventLoop
DECL|variable|QIcon
DECL|variable|QInputContext
DECL|variable|QList
DECL|variable|QLocale
DECL|variable|QPlatformNativeInterface
DECL|variable|QStyle
DECL|variable|QSymbianEvent
