DECL|class|WidgetAttributeSaver
DECL|function|QApplication
DECL|function|QApplicationPrivate
DECL|function|WidgetAttributeSaver
DECL|function|aboutQt
DECL|function|activeModalWidget
DECL|function|activePopupWidget
DECL|function|activeWindow
DECL|function|allWidgets
DECL|function|applyQIconStyleHelper
DECL|function|autoMaximizeThreshold
DECL|function|autoSipEnabled
DECL|function|cleanupMultitouch
DECL|function|clearSystemPalette
DECL|function|closeAllPopups
DECL|function|closeAllWindows
DECL|function|colorSpec
DECL|function|commitData
DECL|function|compressEvent
DECL|function|construct
DECL|function|cursorFlashTime
DECL|function|desktop
DECL|function|desktopStyleKey
DECL|function|dispatchEnterLeave
DECL|function|doubleClickInterval
DECL|function|event
DECL|function|exec
DECL|function|findClosestTouchPointTarget
DECL|function|focusNextPrevChild_helper
DECL|function|focusWidget
DECL|function|font
DECL|function|font
DECL|function|font
DECL|function|fontMetrics
DECL|function|giveFocusAccordingToFocusPolicy
DECL|function|globalStrut
DECL|function|inPopupMode
DECL|function|initResources
DECL|function|initSystemPalette
DECL|function|initialize
DECL|function|initializeMultitouch
DECL|function|instance
DECL|function|isAlien
DECL|function|isBlockedByModal
DECL|function|isSessionRestored
DECL|function|isWindowBlocked
DECL|function|keyboardInputInterval
DECL|function|keypadNavigationEnabled
DECL|function|navigationMode
DECL|function|notify
DECL|function|notifyDragStarted
DECL|function|notifyLayoutDirectionChange
DECL|function|notifyThemeChanged
DECL|function|notify_helper
DECL|function|palette
DECL|function|palette
DECL|function|pickMouseReceiver
DECL|function|process_cmdline
DECL|function|qt_app_fonts_hash
DECL|function|qt_app_palettes_hash
DECL|function|qt_sendSpontaneousEvent
DECL|function|qt_tab_all_widgets
DECL|function|qt_tryModalHelper
DECL|function|saveState
DECL|function|sendMouseEvent
DECL|function|sendSyntheticEnterLeave
DECL|function|sessionId
DECL|function|sessionKey
DECL|function|setActiveWindow
DECL|function|setAutoMaximizeThreshold
DECL|function|setAutoSipEnabled
DECL|function|setColorSpec
DECL|function|setCursorFlashTime
DECL|function|setDoubleClickInterval
DECL|function|setFocusWidget
DECL|function|setFont
DECL|function|setGlobalStrut
DECL|function|setKeyboardInputInterval
DECL|function|setKeypadNavigationEnabled
DECL|function|setNavigationMode
DECL|function|setPalette
DECL|function|setPalette_helper
DECL|function|setStartDragDistance
DECL|function|setStartDragTime
DECL|function|setStyle
DECL|function|setStyle
DECL|function|setStyleSheet
DECL|function|setSystemFont
DECL|function|setSystemPalette
DECL|function|setWindowIcon
DECL|function|shouldQuit
DECL|function|shouldSetFocus
DECL|function|startDragDistance
DECL|function|startDragTime
DECL|function|style
DECL|function|styleSheet
DECL|function|topLevelWidgets
DECL|function|translateRawTouchEvent
DECL|function|translateTouchCancel
DECL|function|translateTouchToMouse
DECL|function|tryModalHelper
DECL|function|updateTouchPointsForWidget
DECL|function|widgetAt
DECL|function|windowIcon
DECL|function|~QApplication
DECL|function|~QApplicationPrivate
DECL|function|~WidgetAttributeSaver
DECL|member|active_window
DECL|member|app_cspec
DECL|member|app_icon
DECL|member|app_strut
DECL|member|app_style
DECL|member|autoMaximizeThreshold
DECL|member|autoSipEnabled
DECL|member|autoSipEnabled
DECL|member|enabledAnimations
DECL|member|focus_widget
DECL|member|hidden_focus_widget
DECL|member|leaveAfterRelease
DECL|member|load_testability
DECL|member|m_attribute
DECL|member|m_savedValue
DECL|member|m_widget
DECL|member|main_widget
DECL|member|navigationMode
DECL|member|oldEditFocus
DECL|member|popupWidgets
DECL|member|self
DECL|member|set_font
DECL|member|set_pal
DECL|member|styleOverride
DECL|member|styleSheet
DECL|member|sys_font
DECL|member|sys_pal
DECL|member|wheel_scroll_lines
DECL|member|widgetCount
DECL|variable|qt_antialiasing_threshold
DECL|variable|qt_desktopWidget
DECL|variable|qt_in_tab_key_event
DECL|variable|qt_tabletChokeMouse
