DECL|class|FixedColumnMatrix
DECL|class|QFormLayoutPrivate
DECL|enumerator|ColumnCount
DECL|function|FixedColumnMatrix
DECL|function|QFormLayout
DECL|function|QFormLayoutItem
DECL|function|QFormLayoutPrivate
DECL|function|addItem
DECL|function|addRow
DECL|function|addRow
DECL|function|addRow
DECL|function|addRow
DECL|function|addRow
DECL|function|addRow
DECL|function|addRow
DECL|function|arrangeWidgets
DECL|function|calcSizeHints
DECL|function|clear
DECL|function|controlTypes
DECL|function|count
DECL|function|count
DECL|function|expandingDirections
DECL|function|expandingDirections
DECL|function|fieldGrowthPolicy
DECL|function|find
DECL|function|fixedAlignment
DECL|function|formAlignment
DECL|function|geometry
DECL|function|getItemPosition
DECL|function|getLayoutPosition
DECL|function|getStyle
DECL|function|getWidgetPosition
DECL|function|hasHeightForWidth
DECL|function|hasHeightForWidth
DECL|function|haveHfwCached
DECL|function|heightForWidth
DECL|function|heightForWidth
DECL|function|horizontalSpacing
DECL|function|initLayoutStruct
DECL|function|insertRow
DECL|function|insertRow
DECL|function|insertRow
DECL|function|insertRow
DECL|function|insertRow
DECL|function|insertRow
DECL|function|insertRow
DECL|function|insertRow
DECL|function|insertRows
DECL|function|invalidate
DECL|function|itemAt
DECL|function|itemAt
DECL|function|labelAlignment
DECL|function|labelForField
DECL|function|labelForField
DECL|function|layout
DECL|function|minimumHeightForWidth
DECL|function|minimumSize
DECL|function|operator ()
DECL|function|operator ()
DECL|function|operator ==
DECL|function|recalcHFW
DECL|function|removeRow
DECL|function|resetFieldGrowthPolicy
DECL|function|resetFormAlignment
DECL|function|resetLabelAlignment
DECL|function|resetRowWrapPolicy
DECL|function|rowCount
DECL|function|rowCount
DECL|function|rowWrapPolicy
DECL|function|setFieldGrowthPolicy
DECL|function|setFormAlignment
DECL|function|setGeometry
DECL|function|setGeometry
DECL|function|setHorizontalSpacing
DECL|function|setItem
DECL|function|setItem
DECL|function|setLabelAlignment
DECL|function|setLayout
DECL|function|setLayout
DECL|function|setRowWrapPolicy
DECL|function|setSpacing
DECL|function|setVerticalSpacing
DECL|function|setWidget
DECL|function|setWidget
DECL|function|setupHfwLayoutData
DECL|function|setupHorizontalLayoutData
DECL|function|setupVerticalLayoutData
DECL|function|sizeHint
DECL|function|spacing
DECL|function|spacingHelper
DECL|function|storage
DECL|function|storageIndexFromLayoutItem
DECL|function|storageIndexToPosition
DECL|function|takeAt
DECL|function|updateFormLayoutItem
DECL|function|updateSizes
DECL|function|vStretch
DECL|function|verticalSpacing
DECL|function|widget
DECL|function|~QFormLayout
DECL|function|~QFormLayoutItem
DECL|function|~QFormLayoutPrivate
DECL|member|formAlignment
DECL|member|formMaxWidth
DECL|member|fullRow
DECL|member|hSpacing
DECL|member|hfwLayouts
DECL|member|hfw_height
DECL|member|hfw_minheight
DECL|member|hfw_sh_height
DECL|member|hfw_sh_minheight
DECL|member|hfw_width
DECL|member|isHfw
DECL|member|item
DECL|member|labelAlignment
DECL|member|layoutPos
DECL|member|layoutWidth
DECL|member|layoutWidth
DECL|member|m_matrix
DECL|member|m_storage
DECL|member|m_things
DECL|member|maxLabelWidth
DECL|member|maxSize
DECL|member|minSize
DECL|member|minSize
DECL|member|min_width
DECL|member|prefSize
DECL|member|sbsHSpace
DECL|member|sh_width
DECL|member|sideBySide
DECL|member|sizeHint
DECL|member|thresh_width
DECL|member|vLayoutCount
DECL|member|vLayoutIndex
DECL|member|vLayouts
DECL|member|vSpace
DECL|member|vSpacing
DECL|struct|QFormLayoutItem
DECL|typedef|ItemMatrix
DECL|typedef|Storage
DECL|variable|DefaultFieldGrowthPolicy
DECL|variable|DefaultRowWrapPolicy
