DECL|macro|QGESTURE_H
DECL|variable|QGesture
DECL|variable|QGestureEventPrivate
DECL|variable|QPanGesturePrivate
DECL|variable|QPinchGesturePrivate
DECL|variable|QSwipeGesturePrivate
DECL|variable|QTapAndHoldGesturePrivate
DECL|variable|QTapGesturePrivate
