DECL|function|QGesture
DECL|function|QGesture
DECL|function|QGestureEvent
DECL|function|QPanGesture
DECL|function|QPinchGesture
DECL|function|QSwipeGesture
DECL|function|QTapAndHoldGesture
DECL|function|QTapGesture
DECL|function|acceleration
DECL|function|accept
DECL|function|accept
DECL|function|activeGestures
DECL|function|canceledGestures
DECL|function|centerPoint
DECL|function|changeFlags
DECL|function|delta
DECL|function|gesture
DECL|function|gestureCancelPolicy
DECL|function|gestureType
DECL|function|gestures
DECL|function|hasHotSpot
DECL|function|horizontalDirection
DECL|function|hotSpot
DECL|function|ignore
DECL|function|ignore
DECL|function|isAccepted
DECL|function|isAccepted
DECL|function|lastCenterPoint
DECL|function|lastOffset
DECL|function|lastRotationAngle
DECL|function|lastScaleFactor
DECL|function|mapToGraphicsScene
DECL|function|offset
DECL|function|position
DECL|function|position
DECL|function|rotationAngle
DECL|function|scaleFactor
DECL|function|setAcceleration
DECL|function|setAccepted
DECL|function|setAccepted
DECL|function|setCenterPoint
DECL|function|setChangeFlags
DECL|function|setGestureCancelPolicy
DECL|function|setHotSpot
DECL|function|setLastCenterPoint
DECL|function|setLastOffset
DECL|function|setLastRotationAngle
DECL|function|setLastScaleFactor
DECL|function|setOffset
DECL|function|setPosition
DECL|function|setPosition
DECL|function|setRotationAngle
DECL|function|setScaleFactor
DECL|function|setStartCenterPoint
DECL|function|setSwipeAngle
DECL|function|setTimeout
DECL|function|setTotalChangeFlags
DECL|function|setTotalRotationAngle
DECL|function|setTotalScaleFactor
DECL|function|setWidget
DECL|function|startCenterPoint
DECL|function|state
DECL|function|swipeAngle
DECL|function|timeout
DECL|function|totalChangeFlags
DECL|function|totalRotationAngle
DECL|function|totalScaleFactor
DECL|function|unsetHotSpot
DECL|function|verticalDirection
DECL|function|widget
DECL|function|~QGesture
DECL|function|~QGestureEvent
DECL|function|~QPanGesture
DECL|function|~QPinchGesture
DECL|function|~QSwipeGesture
DECL|function|~QTapAndHoldGesture
DECL|function|~QTapGesture
DECL|member|Timeout
