DECL|class|QGridBox
DECL|class|QGridLayoutPrivate
DECL|function|QGridBox
DECL|function|QGridBox
DECL|function|QGridLayout
DECL|function|QGridLayout
DECL|function|QGridLayoutPrivate
DECL|function|add
DECL|function|add
DECL|function|addData
DECL|function|addHfwData
DECL|function|addItem
DECL|function|addItem
DECL|function|addLayout
DECL|function|addLayout
DECL|function|addWidget
DECL|function|addWidget
DECL|function|alignment
DECL|function|cellRect
DECL|function|cellRect
DECL|function|checkWidget
DECL|function|colSpacing
DECL|function|colStretch
DECL|function|columnCount
DECL|function|columnMinimumWidth
DECL|function|columnStretch
DECL|function|count
DECL|function|count
DECL|function|deleteAll
DECL|function|distribute
DECL|function|distributeMultiBox
DECL|function|effectiveMargins
DECL|function|expand
DECL|function|expandingDirections
DECL|function|expandingDirections
DECL|function|expandingDirections
DECL|function|findSize
DECL|function|getItemPosition
DECL|function|getItemPosition
DECL|function|getNextPos
DECL|function|gridAt
DECL|function|hStretch
DECL|function|hasHeightForWidth
DECL|function|hasHeightForWidth
DECL|function|hasHeightForWidth
DECL|function|heightForWidth
DECL|function|heightForWidth
DECL|function|heightForWidth
DECL|function|horReversed
DECL|function|horizontalSpacing
DECL|function|initEmptyMultiBox
DECL|function|invalidate
DECL|function|isDirty
DECL|function|isEmpty
DECL|function|item
DECL|function|itemAt
DECL|function|itemAt
DECL|function|itemAtPosition
DECL|function|maximumSize
DECL|function|maximumSize
DECL|function|maximumSize
DECL|function|minimumHeightForWidth
DECL|function|minimumHeightForWidth
DECL|function|minimumSize
DECL|function|minimumSize
DECL|function|minimumSize
DECL|function|numCols
DECL|function|numRows
DECL|function|originCorner
DECL|function|recalcHFW
DECL|function|rowCount
DECL|function|rowMinimumHeight
DECL|function|rowSpacing
DECL|function|rowStretch
DECL|function|rowStretch
DECL|function|setAlignment
DECL|function|setColStretch
DECL|function|setColumnMinimumWidth
DECL|function|setColumnMinimumWidth
DECL|function|setColumnStretch
DECL|function|setDefaultPositioning
DECL|function|setDirty
DECL|function|setGeometry
DECL|function|setGeometry
DECL|function|setHorizontalSpacing
DECL|function|setNextPosAfter
DECL|function|setOriginCorner
DECL|function|setReversed
DECL|function|setRowMinimumHeight
DECL|function|setRowMinimumHeight
DECL|function|setRowStretch
DECL|function|setRowStretch
DECL|function|setSize
DECL|function|setSpacing
DECL|function|setVerticalSpacing
DECL|function|setupHfwLayoutData
DECL|function|setupLayoutData
DECL|function|setupSpacings
DECL|function|sizeHint
DECL|function|sizeHint
DECL|function|sizeHint
DECL|function|spacing
DECL|function|takeAt
DECL|function|takeAt
DECL|function|takeItem
DECL|function|toCol
DECL|function|toRow
DECL|function|vStretch
DECL|function|verReversed
DECL|function|verticalSpacing
DECL|function|~QGridBox
DECL|function|~QGridLayout
DECL|member|bottomMargin
DECL|member|cMinWidths
DECL|member|cStretch
DECL|member|cc
DECL|member|col
DECL|member|colData
DECL|member|hfwData
DECL|member|hfw_height
DECL|member|hfw_minheight
DECL|member|hfw_width
DECL|member|hint
DECL|member|horizontalSpacing
DECL|member|item_
DECL|member|leftMargin
DECL|member|maxS
DECL|member|minS
DECL|member|nextC
DECL|member|nextR
DECL|member|rMinHeights
DECL|member|rStretch
DECL|member|rightMargin
DECL|member|row
DECL|member|rowData
DECL|member|rr
DECL|member|things
DECL|member|tocol
DECL|member|topMargin
DECL|member|torow
DECL|member|verticalSpacing
DECL|struct|QGridLayoutSizeTriple
