DECL|function|QIconLoader
DECL|function|QIconLoaderEngine
DECL|function|QIconLoaderEngine
DECL|function|QIconTheme
DECL|function|actualSize
DECL|function|clone
DECL|function|directoryMatchesSize
DECL|function|directorySizeDistance
DECL|function|ensureInitialized
DECL|function|ensureLoaded
DECL|function|entryForSize
DECL|function|fallbackTheme
DECL|function|findIconHelper
DECL|function|hasIcon
DECL|function|instance
DECL|function|key
DECL|function|loadIcon
DECL|function|paint
DECL|function|pixmap
DECL|function|pixmap
DECL|function|pixmap
DECL|function|read
DECL|function|setThemeName
DECL|function|setThemeSearchPath
DECL|function|systemIconSearchPaths
DECL|function|systemThemeName
DECL|function|themeSearchPaths
DECL|function|updateSystemTheme
DECL|function|virtual_hook
DECL|function|write
DECL|function|~QIconLoaderEngine
