DECL|function|QInputContext
DECL|function|actions
DECL|function|focusWidget
DECL|function|font
DECL|function|identifierName
DECL|function|language
DECL|function|mouseHandler
DECL|function|reset
DECL|function|sendEvent
DECL|function|setFocusWidget
DECL|function|standardFormat
DECL|function|update
DECL|function|widgetDestroyed
DECL|function|~QInputContext
