DECL|function|QLayout
DECL|function|QLayout
DECL|function|QLayout
DECL|function|QLayoutPrivate
DECL|function|activate
DECL|function|activateRecursiveHelper
DECL|function|addChildLayout
DECL|function|addChildWidget
DECL|function|addWidget
DECL|function|adoptLayout
DECL|function|alignmentRect
DECL|function|childEvent
DECL|function|closestAcceptableSize
DECL|function|contentsMargins
DECL|function|contentsRect
DECL|function|controlType
DECL|function|controlTypes
DECL|function|createSpacerItem
DECL|function|createWidgetItem
DECL|function|doResize
DECL|function|expandingDirections
DECL|function|geometry
DECL|function|getContentsMargins
DECL|function|getMargin
DECL|function|indexOf
DECL|function|invalidate
DECL|function|isEmpty
DECL|function|isEnabled
DECL|function|layoutDebug
DECL|function|margin
DECL|function|maximumSize
DECL|function|menuBar
DECL|function|menuBarHeightForWidth
DECL|function|minimumSize
DECL|function|operator <<
DECL|function|operator >>
DECL|function|parentWidget
DECL|function|removeItem
DECL|function|removeWidget
DECL|function|removeWidgetRecursively
DECL|function|reparentChildWidgets
DECL|function|setAlignment
DECL|function|setAlignment
DECL|function|setContentsMargins
DECL|function|setContentsMargins
DECL|function|setControlType
DECL|function|setEnabled
DECL|function|setGeometry
DECL|function|setMargin
DECL|function|setMenuBar
DECL|function|setSizeConstraint
DECL|function|setSpacing
DECL|function|sizeConstraint
DECL|function|spacing
DECL|function|totalHeightForWidth
DECL|function|totalMaximumSize
DECL|function|totalMinimumSize
DECL|function|totalSizeHint
DECL|function|update
DECL|function|widgetEvent
DECL|function|~QLayout
DECL|macro|VALUE_OF_BITS
DECL|member|spacerItemFactoryMethod
DECL|member|widgetItemFactoryMethod
