DECL|function|QWidgetItemV2
DECL|function|changeSize
DECL|function|controlTypes
DECL|function|controlTypes
DECL|function|expandingDirections
DECL|function|expandingDirections
DECL|function|fromLayoutItemRect
DECL|function|fromLayoutItemSize
DECL|function|geometry
DECL|function|geometry
DECL|function|hasHeightForWidth
DECL|function|hasHeightForWidth
DECL|function|heightForWidth
DECL|function|heightForWidth
DECL|function|heightForWidth
DECL|function|invalidate
DECL|function|isEmpty
DECL|function|isEmpty
DECL|function|layout
DECL|function|layout
DECL|function|maximumSize
DECL|function|maximumSize
DECL|function|maximumSize
DECL|function|minimumHeightForWidth
DECL|function|minimumSize
DECL|function|minimumSize
DECL|function|minimumSize
DECL|function|operator <<
DECL|function|operator QVariant
DECL|function|setAlignment
DECL|function|setGeometry
DECL|function|setGeometry
DECL|function|sizeHint
DECL|function|sizeHint
DECL|function|sizeHint
DECL|function|spacerItem
DECL|function|spacerItem
DECL|function|toLayoutItemRect
DECL|function|toLayoutItemSize
DECL|function|updateCacheIfNecessary
DECL|function|useSizeCache
DECL|function|widget
DECL|function|widget
DECL|function|~QLayoutItem
DECL|function|~QSpacerItem
DECL|function|~QWidgetItem
DECL|function|~QWidgetItemV2
