DECL|class|QStackedLayoutPrivate
DECL|class|QtFriendlyLayoutWidget
DECL|function|QStackedLayout
DECL|function|QStackedLayout
DECL|function|QStackedLayout
DECL|function|QStackedLayoutPrivate
DECL|function|addItem
DECL|function|addWidget
DECL|function|count
DECL|function|currentIndex
DECL|function|currentWidget
DECL|function|insertWidget
DECL|function|itemAt
DECL|function|minimumSize
DECL|function|qt_wasDeleted
DECL|function|setCurrentIndex
DECL|function|setCurrentWidget
DECL|function|setGeometry
DECL|function|setStackingMode
DECL|function|sizeHint
DECL|function|stackingMode
DECL|function|takeAt
DECL|function|wasDeleted
DECL|function|widget
DECL|function|~QStackedLayout
DECL|member|index
DECL|member|list
DECL|member|stackingMode
