DECL|function|QPinchGestureRecognizer
DECL|function|QSwipeGestureRecognizer
DECL|function|QTapAndHoldGestureRecognizer
DECL|function|QTapGestureRecognizer
DECL|function|create
DECL|function|create
DECL|function|create
DECL|function|create
DECL|function|create
DECL|function|panOffset
DECL|function|recognize
DECL|function|recognize
DECL|function|recognize
DECL|function|recognize
DECL|function|recognize
DECL|function|reset
DECL|function|reset
DECL|function|reset
DECL|function|reset
DECL|function|reset
