DECL|class|QTipLabel
DECL|function|QTipLabel
DECL|function|eventFilter
DECL|function|font
DECL|function|getTipScreen
DECL|function|hideTip
DECL|function|hideTipImmediately
DECL|function|isVisible
DECL|function|mouseMoveEvent
DECL|function|paintEvent
DECL|function|palette
DECL|function|placeTip
DECL|function|resizeEvent
DECL|function|restartExpireTimer
DECL|function|reuseTip
DECL|function|setFont
DECL|function|setPalette
DECL|function|setTipRect
DECL|function|showText
DECL|function|showText
DECL|function|showText
DECL|function|styleSheetParentDestroyed
DECL|function|text
DECL|function|timerEvent
DECL|function|tipChanged
DECL|function|~QTipLabel
DECL|member|expireTimer
DECL|member|fadingOut
DECL|member|hideTimer
DECL|member|instance
DECL|member|instance
DECL|member|rect
DECL|member|styleSheetParent
DECL|member|widget
