DECL|class|QWhatsThat
DECL|class|QWhatsThisAction
DECL|class|QWhatsThisPrivate
DECL|function|QWhatsThat
DECL|function|QWhatsThisAction
DECL|function|QWhatsThisPrivate
DECL|function|actionTriggered
DECL|function|createAction
DECL|function|dropShadow
DECL|function|enterWhatsThisMode
DECL|function|eventFilter
DECL|function|hideText
DECL|function|inWhatsThisMode
DECL|function|keyPressEvent
DECL|function|leaveWhatsThisMode
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|notifyToplevels
DECL|function|paintEvent
DECL|function|say
DECL|function|showEvent
DECL|function|showText
DECL|function|~QWhatsThat
DECL|function|~QWhatsThisPrivate
DECL|member|action
DECL|member|anchor
DECL|member|background
DECL|member|doc
DECL|member|instance
DECL|member|instance
DECL|member|instance
DECL|member|instance
DECL|member|leaveOnMouseRelease
DECL|member|pressed
DECL|member|text
DECL|member|widget
DECL|variable|button_image
DECL|variable|hMargin
DECL|variable|shadowWidth
DECL|variable|vMargin
