DECL|function|backgroundBrush
DECL|function|backgroundColor
DECL|function|backgroundPixmap
DECL|function|childAt
DECL|function|erase
DECL|function|erase
DECL|function|eraseColor
DECL|function|erasePixmap
DECL|function|font
DECL|function|fontInfo
DECL|function|fontMetrics
DECL|function|foregroundColor
DECL|function|geometry
DECL|function|hasMouseTracking
DECL|function|height
DECL|function|isEnabled
DECL|function|isEnabledToTLW
DECL|function|isHidden
DECL|function|isModal
DECL|function|isTopLevel
DECL|function|isVisible
DECL|function|isVisibleToTLW
DECL|function|isWindow
DECL|function|maximumHeight
DECL|function|maximumWidth
DECL|function|minimumHeight
DECL|function|minimumWidth
DECL|function|move
DECL|function|paletteBackgroundColor
DECL|function|paletteBackgroundPixmap
DECL|function|paletteForegroundColor
DECL|function|parentWidget
DECL|function|parentWidget
DECL|function|rect
DECL|function|resize
DECL|function|setBackgroundColor
DECL|function|setBackgroundPixmap
DECL|function|setBaseSize
DECL|function|setEraseColor
DECL|function|setErasePixmap
DECL|function|setGeometry
DECL|function|setMaximumSize
DECL|function|setMinimumSize
DECL|function|setMouseTracking
DECL|function|setPaletteBackgroundColor
DECL|function|setPaletteBackgroundPixmap
DECL|function|setPaletteForegroundColor
DECL|function|setSizeIncrement
DECL|function|setSizePolicy
DECL|function|size
DECL|function|testAttribute
DECL|function|underMouse
DECL|function|update
DECL|function|updatesEnabled
DECL|function|width
DECL|function|windowFlags
DECL|function|windowType
DECL|macro|QWIDGETSIZE_MAX
DECL|macro|QWIDGET_H
DECL|variable|QAction
DECL|variable|QActionEvent
DECL|variable|QBackingStore
DECL|variable|QCloseEvent
DECL|variable|QContextMenuEvent
DECL|variable|QDragEnterEvent
DECL|variable|QDragLeaveEvent
DECL|variable|QDragMoveEvent
DECL|variable|QDropEvent
DECL|variable|QFocusEvent
DECL|variable|QGraphicsEffect
DECL|variable|QGraphicsProxyWidget
DECL|variable|QHideEvent
DECL|variable|QHoverEvent
DECL|variable|QIcon
DECL|variable|QInputContext
DECL|variable|QInputMethodEvent
DECL|variable|QKeyEvent
DECL|variable|QLocale
DECL|variable|QMouseEvent
DECL|variable|QMoveEvent
DECL|variable|QObject
DECL|variable|QPaintEvent
DECL|variable|QPlatformWindow
DECL|variable|QRasterWindowSurface
DECL|variable|QResizeEvent
DECL|variable|QShowEvent
DECL|variable|QStyle
DECL|variable|QTabletEvent
DECL|variable|QUnifiedToolbarSurface
DECL|variable|QVariant
DECL|variable|QWSRegionManager
DECL|variable|QWheelEvent
DECL|variable|QWidgetPrivate
DECL|variable|QX11Info
