DECL|function|activateWindow
DECL|function|applyCursor
DECL|function|createSysExtra
DECL|function|createTLSysExtra
DECL|function|create_sys
DECL|function|deleteSysExtra
DECL|function|deleteTLSysExtra
DECL|function|destroy
DECL|function|effectiveState
DECL|function|fixPosIncludesFrame
DECL|function|grabKeyboard
DECL|function|grabMouse
DECL|function|grabMouse
DECL|function|grabberWindow
DECL|function|hide_sys
DECL|function|keyboardGrabber
DECL|function|lower_sys
DECL|function|mapFromGlobal
DECL|function|mapToGlobal
DECL|function|metric
DECL|function|mouseGrabber
DECL|function|paintEngine
DECL|function|q_createNativeChildrenAndSetParent
DECL|function|qt_qpa_set_cursor
DECL|function|raise_sys
DECL|function|registerDropSite
DECL|function|releaseKeyboard
DECL|function|releaseMouse
DECL|function|scroll_sys
DECL|function|scroll_sys
DECL|function|setConstraints_sys
DECL|function|setCursor_sys
DECL|function|setFocus_sys
DECL|function|setGeometry_sys
DECL|function|setMask_sys
DECL|function|setModal_sys
DECL|function|setParent_sys
DECL|function|setWSGeometry
DECL|function|setWindowFilePath_sys
DECL|function|setWindowIconText_sys
DECL|function|setWindowIcon_sys
DECL|function|setWindowOpacity_sys
DECL|function|setWindowState
DECL|function|setWindowTitle_sys
DECL|function|show_sys
DECL|function|stackUnder_sys
DECL|function|stealKeyboardGrab
DECL|function|stealMouseGrab
DECL|function|unsetCursor
DECL|function|unsetCursor_sys
DECL|function|updateFrameStrut
DECL|function|updateSystemBackground
DECL|function|windowHandle
DECL|variable|keyboardGrb
DECL|variable|qt_mouseGrb
DECL|variable|qt_pressGrab
