DECL|function|QWidget
DECL|function|QWidget
DECL|function|QWidgetBackingStoreTracker
DECL|function|QWidgetPrivate
DECL|function|_q_showIfNotHidden
DECL|function|acceptDrops
DECL|function|accessibleDescription
DECL|function|accessibleName
DECL|function|actionEvent
DECL|function|actions
DECL|function|activateChildLayoutsRecursively
DECL|function|activateWindow
DECL|function|addAction
DECL|function|addActions
DECL|function|adjustFlags
DECL|function|adjustQuitOnCloseAttribute
DECL|function|adjustSize
DECL|function|adjustedSize
DECL|function|applyCursor
DECL|function|autoFillBackground
DECL|function|backgroundRole
DECL|function|backingStore
DECL|function|baseSize
DECL|function|boundingRect
DECL|function|canKeypadNavigate
DECL|function|changeEvent
DECL|function|childAt
DECL|function|childAtRecursiveHelper
DECL|function|childAt_helper
DECL|function|childrenRect
DECL|function|childrenRegion
DECL|function|cleanup
DECL|function|clearFocus
DECL|function|clearMask
DECL|function|clipRect
DECL|function|clipRegion
DECL|function|clipToEffectiveMask
DECL|function|close
DECL|function|closeEvent
DECL|function|close_helper
DECL|function|contentsMargins
DECL|function|contentsRect
DECL|function|contextMenuEvent
DECL|function|contextMenuPolicy
DECL|function|create
DECL|function|create
DECL|function|createExtra
DECL|function|createRecursively
DECL|function|createSysExtra
DECL|function|createTLExtra
DECL|function|createTLSysExtra
DECL|function|createWinId
DECL|function|createWinId
DECL|function|create_sys
DECL|function|cursor
DECL|function|deactivateWidgetCleanup
DECL|function|deleteExtra
DECL|function|deleteSysExtra
DECL|function|deleteTLSysExtra
DECL|function|destroy
DECL|function|destroy
DECL|function|devType
DECL|function|dragEnterEvent
DECL|function|dragLeaveEvent
DECL|function|dragMoveEvent
DECL|function|draw
DECL|function|drawWidget
DECL|function|dropEvent
DECL|function|effectiveState
DECL|function|effectiveWinId
DECL|function|ensurePolished
DECL|function|enterEvent
DECL|function|event
DECL|function|fillRegion
DECL|function|find
DECL|function|fixPosIncludesFrame
DECL|function|focusInEvent
DECL|function|focusNextPrevChild
DECL|function|focusOutEvent
DECL|function|focusPolicy
DECL|function|focusProxy
DECL|function|focusWidget
DECL|function|foregroundRole
DECL|function|frameGeometry
DECL|function|frameSize
DECL|function|frameStrut
DECL|function|getContentsMargins
DECL|function|getLayoutItemMargins
DECL|function|getOpaqueChildren
DECL|function|grab
DECL|function|grabGesture
DECL|function|grabKeyboard
DECL|function|grabMouse
DECL|function|grabMouse
DECL|function|grabMouseForWidget
DECL|function|grabShortcut
DECL|function|grabberWindow
DECL|function|graphicsEffect
DECL|function|graphicsProxyWidget
DECL|function|hasBackingStoreSupport
DECL|function|hasEditFocus
DECL|function|hasFocus
DECL|function|hasHeightForWidth
DECL|function|heightForWidth
DECL|function|hide
DECL|function|hideChildren
DECL|function|hideEvent
DECL|function|hide_helper
DECL|function|hide_sys
DECL|function|inTabWidget
DECL|function|inheritStyle
DECL|function|init
DECL|function|initPainter
DECL|function|inputMethodEvent
DECL|function|inputMethodHints
DECL|function|inputMethodQuery
DECL|function|insertAction
DECL|function|insertActions
DECL|function|invalidateGraphicsEffectsRecursively
DECL|function|isAboutToShow
DECL|function|isActiveWindow
DECL|function|isAncestorOf
DECL|function|isEnabledTo
DECL|function|isFullScreen
DECL|function|isMaximized
DECL|function|isMinimized
DECL|function|isOverlapped
DECL|function|isVisibleTo
DECL|function|isWindowModified
DECL|function|keyPressEvent
DECL|function|keyReleaseEvent
DECL|function|keyboardGrabber
DECL|function|layout
DECL|function|layoutDirection
DECL|function|leaveEvent
DECL|function|locale
DECL|function|lower
DECL|function|lower_sys
DECL|function|macUpdateSizeAttribute
DECL|function|mapFrom
DECL|function|mapFromGlobal
DECL|function|mapFromParent
DECL|function|mapTo
DECL|function|mapToGlobal
DECL|function|mapToParent
DECL|function|mask
DECL|function|maximumSize
DECL|function|metric
DECL|function|minimumSize
DECL|function|minimumSizeHint
DECL|function|mouseDoubleClickEvent
DECL|function|mouseGrabber
DECL|function|mouseMoveEvent
DECL|function|mousePressEvent
DECL|function|mouseReleaseEvent
DECL|function|move
DECL|function|moveEvent
DECL|function|nativeEvent
DECL|function|nativeParentWidget
DECL|function|naturalWidgetFont
DECL|function|naturalWidgetPalette
DECL|function|navigateToDirection
DECL|function|nearestGraphicsProxyWidget
DECL|function|nextInFocusChain
DECL|function|normalGeometry
DECL|function|overrideWindowFlags
DECL|function|overrideWindowState
DECL|function|paintBackground
DECL|function|paintEngine
DECL|function|paintEvent
DECL|function|paintOnScreen
DECL|function|paintSiblingsRecursive
DECL|function|palette
DECL|function|pixmap
DECL|function|pointToRect
DECL|function|pos
DECL|function|prepareToRender
DECL|function|previousInFocusChain
DECL|function|propagatePaletteChange
DECL|function|qRectIntersects
DECL|function|q_createNativeChildrenAndSetParent
DECL|function|qt_dirtyRegion
DECL|function|qt_qpa_set_cursor
DECL|function|qt_qwidget_data
DECL|function|qt_setWindowTitle_helperHelper
DECL|function|qt_widget_private
DECL|function|qt_x11_set_global_double_buffer
DECL|function|raise
DECL|function|raise_sys
DECL|function|redirected
DECL|function|registerDropSite
DECL|function|registerWidget
DECL|function|releaseKeyboard
DECL|function|releaseMouse
DECL|function|releaseMouseGrabOfWidget
DECL|function|releaseShortcut
DECL|function|removeAction
DECL|function|render
DECL|function|render
DECL|function|render
DECL|function|render_helper
DECL|function|repaint
DECL|function|repaint
DECL|function|repaint
DECL|function|repaint
DECL|function|reparentFocusWidgets
DECL|function|resize
DECL|function|resizeEvent
DECL|function|resolveFont
DECL|function|resolveLayoutDirection
DECL|function|resolveLocale
DECL|function|resolvePalette
DECL|function|restoreGeometry
DECL|function|saveGeometry
DECL|function|scroll
DECL|function|scroll
DECL|function|scrollChildren
DECL|function|scroll_sys
DECL|function|scroll_sys
DECL|function|sendComposeStatus
DECL|function|sendPaintEvent
DECL|function|sendPendingMoveAndResizeEvents
DECL|function|sendResizeEvents
DECL|function|sendWindowChangeToTextureChildrenRecursively
DECL|function|setAcceptDrops
DECL|function|setAccessibleDescription
DECL|function|setAccessibleName
DECL|function|setAttribute
DECL|function|setAttribute_internal
DECL|function|setAutoFillBackground
DECL|function|setBackgroundRole
DECL|function|setBackingStore
DECL|function|setBaseSize
DECL|function|setConstraints_sys
DECL|function|setContentsMargins
DECL|function|setContentsMargins
DECL|function|setContextMenuPolicy
DECL|function|setCursor
DECL|function|setCursor_sys
DECL|function|setDirtyOpaqueRegion
DECL|function|setDisabled
DECL|function|setDisabledStyle
DECL|function|setEditFocus
DECL|function|setEnabled
DECL|function|setEnabled_helper
DECL|function|setFixedHeight
DECL|function|setFixedSize
DECL|function|setFixedSize
DECL|function|setFixedWidth
DECL|function|setFocus
DECL|function|setFocusPolicy
DECL|function|setFocusProxy
DECL|function|setFocus_sys
DECL|function|setFont
DECL|function|setForegroundRole
DECL|function|setGeometry
DECL|function|setGeometry_sys
DECL|function|setGraphicsEffect
DECL|function|setHidden
DECL|function|setInputMethodHints
DECL|function|setLayout
DECL|function|setLayoutDirection
DECL|function|setLayoutDirection_helper
DECL|function|setLayoutItemMargins
DECL|function|setLayoutItemMargins
DECL|function|setLocale
DECL|function|setLocale_helper
DECL|function|setMask
DECL|function|setMask
DECL|function|setMask_sys
DECL|function|setMaximumHeight
DECL|function|setMaximumSize
DECL|function|setMaximumSize_helper
DECL|function|setMaximumWidth
DECL|function|setMinimumHeight
DECL|function|setMinimumSize
DECL|function|setMinimumSize_helper
DECL|function|setMinimumWidth
DECL|function|setModal_sys
DECL|function|setOpaque
DECL|function|setPalette
DECL|function|setPalette_helper
DECL|function|setParent
DECL|function|setParent
DECL|function|setParent_sys
DECL|function|setShortcutAutoRepeat
DECL|function|setShortcutEnabled
DECL|function|setSizeIncrement
DECL|function|setSizePolicy
DECL|function|setStatusTip
DECL|function|setStyle
DECL|function|setStyleSheet
DECL|function|setStyle_helper
DECL|function|setSystemClip
DECL|function|setTabOrder
DECL|function|setToolTip
DECL|function|setToolTipDuration
DECL|function|setUpdatesEnabled
DECL|function|setUpdatesEnabled_helper
DECL|function|setVisible
DECL|function|setWSGeometry
DECL|function|setWhatsThis
DECL|function|setWidgetParentHelper
DECL|function|setWinId
DECL|function|setWindowFilePath
DECL|function|setWindowFilePath_helper
DECL|function|setWindowFilePath_sys
DECL|function|setWindowFlags
DECL|function|setWindowFlags
DECL|function|setWindowIcon
DECL|function|setWindowIconText
DECL|function|setWindowIconText_helper
DECL|function|setWindowIconText_sys
DECL|function|setWindowIcon_helper
DECL|function|setWindowIcon_sys
DECL|function|setWindowModality
DECL|function|setWindowModified
DECL|function|setWindowModified_helper
DECL|function|setWindowOpacity
DECL|function|setWindowOpacity_sys
DECL|function|setWindowRole
DECL|function|setWindowState
DECL|function|setWindowTitle
DECL|function|setWindowTitle_helper
DECL|function|setWindowTitle_sys
DECL|function|shareContext
DECL|function|sharedPainter
DECL|function|show
DECL|function|showChildren
DECL|function|showEvent
DECL|function|showFullScreen
DECL|function|showMaximized
DECL|function|showMinimized
DECL|function|showNormal
DECL|function|show_helper
DECL|function|show_recursive
DECL|function|show_sys
DECL|function|sizeHint
DECL|function|sizeIncrement
DECL|function|sizePolicy
DECL|function|stackUnder
DECL|function|stackUnder_sys
DECL|function|statusTip
DECL|function|stealKeyboardGrab
DECL|function|stealMouseGrab
DECL|function|style
DECL|function|styleSheet
DECL|function|subtractOpaqueChildren
DECL|function|subtractOpaqueSiblings
DECL|function|syncBackingStore
DECL|function|syncBackingStore
DECL|function|tabletEvent
DECL|function|takeLayout
DECL|function|testAttribute_helper
DECL|function|toolTip
DECL|function|toolTipDuration
DECL|function|ungrabGesture
DECL|function|unregisterWidget
DECL|function|unregisterWidgetSubtree
DECL|function|unsetCursor
DECL|function|unsetCursor
DECL|function|unsetCursor_sys
DECL|function|unsetLayoutDirection
DECL|function|unsetLocale
DECL|function|update
DECL|function|update
DECL|function|update
DECL|function|updateFocusChild
DECL|function|updateFont
DECL|function|updateFrameStrut
DECL|function|updateGeometry
DECL|function|updateGeometry_helper
DECL|function|updateIsOpaque
DECL|function|updateIsTranslucent
DECL|function|updateMicroFocus
DECL|function|updateSystemBackground
DECL|function|updateWidgetTransform
DECL|function|visibleRegion
DECL|function|whatsThis
DECL|function|wheelEvent
DECL|function|widgetInNavigationDirection
DECL|function|winId
DECL|function|window
DECL|function|windowFilePath
DECL|function|windowHandle
DECL|function|windowIcon
DECL|function|windowIconText
DECL|function|windowModality
DECL|function|windowOpacity
DECL|function|windowRole
DECL|function|windowState
DECL|function|windowTitle
DECL|function|x
DECL|function|y
DECL|function|~QWidget
DECL|function|~QWidgetBackingStoreTracker
DECL|function|~QWidgetPrivate
DECL|macro|QT_NO_PAINT_DEBUG
DECL|member|allWidgets
DECL|member|editingWidget
DECL|member|instanceCounter
DECL|member|mapper
DECL|member|maxInstances
DECL|struct|QWidgetExceptionCleaner
DECL|variable|activeXNativeParentHandleProperty
DECL|variable|keyboardGrb
DECL|variable|mouseGrabWithCursor
DECL|variable|qt_enable_backingstore
DECL|variable|qt_mac_clearDirtyOnWidgetInsideDrawWidget
DECL|variable|qt_mouseGrb
DECL|variable|qt_pressGrab
