DECL|class|QWindowContainerPrivate
DECL|function|QWindowContainer
DECL|function|QWindowContainerPrivate
DECL|function|createWindowContainer
DECL|function|event
DECL|function|focusWindowChanged
DECL|function|~QWindowContainer
DECL|function|~QWindowContainerPrivate
DECL|member|oldFocusWindow
DECL|member|window
