DECL|class|Unaligned
DECL|class|tst_QArrayData
DECL|function|Deallocator
DECL|function|alignment
DECL|function|alignment_data
DECL|function|allocate
DECL|function|allocate_data
DECL|function|referenceCounting
DECL|function|sharedNullEmpty
DECL|function|simpleVector
DECL|function|staticData
DECL|function|typedData
DECL|function|~Deallocator
DECL|member|alignment
DECL|member|dummy
DECL|member|headers
DECL|member|objectSize
DECL|struct|Deallocator
