DECL|class|Unaligned
DECL|class|tst_QArrayData
DECL|enumerator|CopyConstructor
DECL|enumerator|DefaultConstructor
DECL|enumerator|MoveConstructor
DECL|enum|Constructor
DECL|function|CountedObject
DECL|function|CountedObject
DECL|function|Deallocator
DECL|function|DetectConstructor
DECL|function|DetectConstructor
DECL|function|DetectConstructor
DECL|function|LeakChecker
DECL|function|SharedNullVerifier
DECL|function|alignment
DECL|function|alignment_data
DECL|function|allocate
DECL|function|allocate_data
DECL|function|arrayIsFilledWith
DECL|function|arrayOps
DECL|function|const_
DECL|function|cxx11Move
DECL|function|fromRawData
DECL|function|gccBug43247
DECL|function|grow
DECL|function|literals
DECL|function|operator =
DECL|function|rValueReferences
DECL|function|referenceCounting
DECL|function|setSharable
DECL|function|setSharable_data
DECL|function|sharedNullEmpty
DECL|function|simpleVector
DECL|function|simpleVectorReserve
DECL|function|simpleVectorReserve_data
DECL|function|staticData
DECL|function|typedData
DECL|function|value
DECL|function|variadicLiterals
DECL|function|~CountedObject
DECL|function|~Deallocator
DECL|function|~LeakChecker
DECL|member|alignment
DECL|member|constructor
DECL|member|dummy
DECL|member|headers
DECL|member|id
DECL|member|liveCount
DECL|member|liveCount
DECL|member|objectSize
DECL|member|previousLiveCount
DECL|struct|CompilerHasCxx11ImplicitMoves
DECL|struct|CountedObject
DECL|struct|Deallocator
DECL|struct|DetectConstructor
DECL|struct|DetectImplicitMove
DECL|struct|LeakChecker
DECL|struct|RemoveReference
DECL|struct|RemoveReference
DECL|struct|SharedNullVerifier
DECL|typedef|Type
DECL|typedef|Type
DECL|variable|globalInit
