DECL|class|TestEventDispatcher
DECL|class|tst_BenchlibEventCounter
DECL|function|TestEventDispatcher
DECL|function|events
DECL|function|events_data
DECL|function|flush
DECL|function|hasPendingEvents
DECL|function|interrupt
DECL|function|main
DECL|function|processEvents
DECL|function|registerSocketNotifier
DECL|function|registerTimer
DECL|function|registerTimer
DECL|function|registeredTimers
DECL|function|unregisterSocketNotifier
DECL|function|unregisterTimer
DECL|function|unregisterTimers
DECL|function|wakeUp
