DECL|class|tst_QPathClipper
DECL|function|clip
DECL|function|clip2
DECL|function|clip3
DECL|function|clipTest
DECL|function|clip_data
DECL|function|initTestCase
DECL|function|loopLength
DECL|function|pathFromLine
DECL|function|pathFromRect
DECL|function|qtbug3778
DECL|function|randomPointInRect
DECL|function|samplePath1
DECL|function|samplePath10
DECL|function|samplePath13
DECL|function|samplePath14
DECL|function|samplePath2
DECL|function|samplePath3
DECL|function|samplePath4
DECL|function|samplePath5
DECL|function|samplePath6
DECL|function|samplePath7
DECL|function|samplePath8
DECL|function|samplePath9
DECL|function|strictContains
DECL|function|task204301
DECL|function|task204301_data
DECL|function|task209056
DECL|function|task251909
DECL|function|testComparePaths
DECL|function|testIntersections
DECL|function|testIntersections2
DECL|function|testIntersections3
DECL|function|testIntersections4
DECL|function|testIntersections5
DECL|function|testIntersections6
DECL|function|testIntersections7
DECL|function|testIntersections8
DECL|function|testIntersections9
DECL|function|testWingedEdge
DECL|function|tst_QPathClipper
DECL|function|zeroDerivativeCurves
DECL|function|~tst_QPathClipper
DECL|member|paths
