DECL|class|tst_QTime
DECL|function|addMSecs
DECL|function|addMSecs_data
DECL|function|addSecs
DECL|function|addSecs_data
DECL|function|cleanup
DECL|function|cleanupTestCase
DECL|function|fromString
DECL|function|fromStringFormat
DECL|function|fromStringFormat_data
DECL|function|fromString_data
DECL|function|hour
DECL|function|hour_data
DECL|function|init
DECL|function|initTestCase
DECL|function|isNull
DECL|function|isValid
DECL|function|msecsTo
DECL|function|msecsTo_data
DECL|function|operator_eq_eq
DECL|function|operator_gt
DECL|function|operator_gt_eq
DECL|function|operator_lt
DECL|function|operator_lt_eq
DECL|function|operator_not_eq
DECL|function|secsTo
DECL|function|secsTo_data
DECL|function|setHMS
DECL|function|setHMS_data
DECL|function|toString
DECL|function|toStringLocale
DECL|function|toString_data
DECL|function|toString_format
DECL|function|toString_format_data
DECL|function|tst_QTime
DECL|function|~tst_QTime
