DECL|function|q_configFromQPlatformWindowFormat
DECL|function|q_createConfigAttributesFromFormat
DECL|function|q_hasEglExtension
DECL|function|q_reduceConfigAttributes
DECL|function|q_windowFormatFromConfig
