DECL|function|QEGLPlatformContext
DECL|function|QEGLSurface
DECL|function|doneCurrent
DECL|function|eglContext
DECL|function|format
DECL|function|getProcAddress
DECL|function|makeCurrent
DECL|function|swapBuffers
DECL|function|~QEGLPlatformContext
