DECL|class|tst_rcc
DECL|function|binary
DECL|function|binary_data
DECL|function|cleanupTestCase
DECL|function|createRccBinaryData
DECL|function|doCompare
DECL|function|findExpectedFile
DECL|function|initTestCase
DECL|function|rcc
DECL|function|rcc_data
DECL|function|readExpectedFiles
DECL|function|readLinesFromFile
DECL|member|m_rcc
DECL|typedef|QStringMap
