DECL|class|QFtpCommand
DECL|class|QFtpDTP
DECL|class|QFtpPI
DECL|class|QFtpPrivate
DECL|enumerator|AbortStarted
DECL|enumerator|Begin
DECL|enumerator|CsClosed
DECL|enumerator|CsConnected
DECL|enumerator|CsConnectionRefused
DECL|enumerator|CsHostFound
DECL|enumerator|CsHostNotFound
DECL|enumerator|Failure
DECL|enumerator|Idle
DECL|enumerator|None
DECL|enumerator|Success
DECL|enumerator|WaitForAbortToFinish
DECL|enumerator|Waiting
DECL|enum|AbortState
DECL|enum|ConnectState
DECL|enum|State
DECL|function|QFtp
DECL|function|QFtp
DECL|function|QFtpCommand
DECL|function|QFtpCommand
DECL|function|QFtpDTP
DECL|function|QFtpPI
DECL|function|QFtpPrivate
DECL|function|_q_fixupDateTime
DECL|function|_q_parseDosDir
DECL|function|_q_parseUnixDir
DECL|function|_q_piConnectState
DECL|function|_q_piError
DECL|function|_q_piFinished
DECL|function|_q_piFtpReply
DECL|function|_q_startNextCommand
DECL|function|abort
DECL|function|abort
DECL|function|abortConnection
DECL|function|addCommand
DECL|function|bytesAvailable
DECL|function|bytesAvailable
DECL|function|cd
DECL|function|clearData
DECL|function|clearError
DECL|function|clearPendingCommands
DECL|function|clearPendingCommands
DECL|function|close
DECL|function|connectToHost
DECL|function|connectToHost
DECL|function|connectToHost
DECL|function|connected
DECL|function|connectionClosed
DECL|function|currentCommand
DECL|function|currentCommand
DECL|function|currentDevice
DECL|function|currentId
DECL|function|dataReadyRead
DECL|function|delayedCloseFinished
DECL|function|dtpConnectState
DECL|function|error
DECL|function|error
DECL|function|errorMessage
DECL|function|errorString
DECL|function|get
DECL|function|hasError
DECL|function|hasPendingCommands
DECL|function|hostFound
DECL|function|list
DECL|function|login
DECL|function|mkdir
DECL|function|parseDir
DECL|function|processReply
DECL|function|put
DECL|function|put
DECL|function|rawCommand
DECL|function|read
DECL|function|read
DECL|function|readAll
DECL|function|readAll
DECL|function|readyRead
DECL|function|remove
DECL|function|rename
DECL|function|rmdir
DECL|function|sendCommand
DECL|function|sendCommands
DECL|function|setBytesTotal
DECL|function|setData
DECL|function|setDevice
DECL|function|setProxy
DECL|function|setTransferMode
DECL|function|setupListener
DECL|function|setupSocket
DECL|function|socketBytesWritten
DECL|function|socketConnected
DECL|function|socketConnectionClosed
DECL|function|socketError
DECL|function|socketReadyRead
DECL|function|startNextCmd
DECL|function|state
DECL|function|state
DECL|function|waitForConnection
DECL|function|writeData
DECL|function|~QFtp
DECL|function|~QFtpCommand
DECL|function|~QFtpPrivate
DECL|member|abortState
DECL|member|ba
DECL|member|ba
DECL|member|bytesDone
DECL|member|bytesFromSocket
DECL|member|bytesFromSocket
DECL|member|bytesTotal
DECL|member|callWriteData
DECL|member|close_waitForStateChange
DECL|member|command
DECL|member|commandSocket
DECL|member|currentCmd
DECL|member|data
DECL|member|data
DECL|member|dev
DECL|member|dev
DECL|member|dtp
DECL|member|err
DECL|member|error
DECL|member|errorString
DECL|member|host
DECL|member|id
DECL|member|idCounter
DECL|member|idCounter
DECL|member|is_ba
DECL|member|is_ba
DECL|member|listener
DECL|member|pending
DECL|member|pendingCommands
DECL|member|pi
DECL|member|pi
DECL|member|port
DECL|member|proxyHost
DECL|member|proxyPort
DECL|member|rawCmds
DECL|member|rawCommand
DECL|member|replyCode
DECL|member|replyText
DECL|member|socket
DECL|member|state
DECL|member|state
DECL|member|transferConnectionExtended
DECL|member|transferMode
DECL|member|waitForDtpToClose
DECL|member|waitForDtpToConnect
