DECL|macro|QHTTPTHREADDELEGATE_H
DECL|variable|QAuthenticator
DECL|variable|QEventLoop
DECL|variable|QHttpNetworkReply
DECL|variable|QNetworkAccessCache
DECL|variable|QNetworkAccessCachedHttpConnection
