DECL|function|QHttpNetworkReply
DECL|function|QHttpNetworkReplyPrivate
DECL|function|authenticationMethod
DECL|function|bytesAvailable
DECL|function|bytesAvailable
DECL|function|bytesAvailableNextBlock
DECL|function|clear
DECL|function|clearHttpLayerInformation
DECL|function|connection
DECL|function|contentLength
DECL|function|eraseData
DECL|function|errorString
DECL|function|expectContent
DECL|function|findChallenge
DECL|function|getChunkSize
DECL|function|header
DECL|function|headerField
DECL|function|ignoreSslErrors
DECL|function|ignoreSslErrors
DECL|function|isChunked
DECL|function|isCompressed
DECL|function|isConnectionCloseEnabled
DECL|function|isFinished
DECL|function|isPipeliningUsed
DECL|function|majorVersion
DECL|function|minorVersion
DECL|function|parseHeader
DECL|function|parseHeader
DECL|function|parseStatus
DECL|function|readAll
DECL|function|readAny
DECL|function|readAnyAvailable
DECL|function|readBody
DECL|function|readBodyFast
DECL|function|readBodyVeryFast
DECL|function|readHeader
DECL|function|readReplyBodyChunked
DECL|function|readReplyBodyRaw
DECL|function|readStatus
DECL|function|reasonPhrase
DECL|function|removeAutoDecompressHeader
DECL|function|request
DECL|function|setContentLength
DECL|function|setDownstreamLimited
DECL|function|setErrorString
DECL|function|setHeaderField
DECL|function|setRequest
DECL|function|setSslConfiguration
DECL|function|setStatusCode
DECL|function|setUrl
DECL|function|setUserProvidedDownloadBuffer
DECL|function|shouldEmitSignals
DECL|function|sslConfiguration
DECL|function|statusCode
DECL|function|supportsUserProvidedDownloadBuffer
DECL|function|uncompressBodyData
DECL|function|url
DECL|function|userProvidedDownloadBuffer
DECL|function|~QHttpNetworkReply
DECL|function|~QHttpNetworkReplyPrivate
