DECL|function|QNetworkReply
DECL|function|QNetworkReply
DECL|function|QNetworkReplyPrivate
DECL|function|attribute
DECL|function|close
DECL|function|error
DECL|function|hasRawHeader
DECL|function|header
DECL|function|ignoreSslErrors
DECL|function|ignoreSslErrors
DECL|function|ignoreSslErrorsImplementation
DECL|function|isFinished
DECL|function|isRunning
DECL|function|isSequential
DECL|function|manager
DECL|function|operation
DECL|function|rawHeader
DECL|function|rawHeaderList
DECL|function|rawHeaderPairs
DECL|function|readBufferSize
DECL|function|request
DECL|function|setAttribute
DECL|function|setError
DECL|function|setFinished
DECL|function|setHeader
DECL|function|setOperation
DECL|function|setRawHeader
DECL|function|setReadBufferSize
DECL|function|setRequest
DECL|function|setSslConfiguration
DECL|function|setSslConfigurationImplementation
DECL|function|setUrl
DECL|function|sslConfiguration
DECL|function|sslConfigurationImplementation
DECL|function|url
DECL|function|writeData
DECL|function|~QNetworkReply
