DECL|enumerator|ExpiryTime
DECL|enum|ExpiryTimeEnum
DECL|function|CacheableObject
DECL|function|Node
DECL|function|QNetworkAccessCache
DECL|function|addEntry
DECL|function|clear
DECL|function|emitEntryReady
DECL|function|hasEntry
DECL|function|linkEntry
DECL|function|releaseEntry
DECL|function|removeEntry
DECL|function|requestEntry
DECL|function|requestEntryNow
DECL|function|setExpires
DECL|function|setShareable
DECL|function|timerEvent
DECL|function|unlinkEntry
DECL|function|updateTimer
DECL|function|~CacheableObject
DECL|function|~QNetworkAccessCache
DECL|member|key
DECL|member|member
DECL|member|newer
DECL|member|object
DECL|member|object
DECL|member|older
DECL|member|receiverQueue
DECL|member|timestamp
DECL|member|useCount
DECL|struct|Node
DECL|struct|Receiver
