DECL|enumerator|CacheMagic
DECL|enumerator|CurrentCacheVersion
DECL|function|QNetworkDiskCache
DECL|function|cacheDirectory
DECL|function|cacheFileName
DECL|function|cacheSize
DECL|function|canCompress
DECL|function|clear
DECL|function|data
DECL|function|expire
DECL|function|fileMetaData
DECL|function|insert
DECL|function|maximumCacheSize
DECL|function|metaData
DECL|function|prepare
DECL|function|prepareLayout
DECL|function|read
DECL|function|remove
DECL|function|removeFile
DECL|function|setCacheDirectory
DECL|function|setMaximumCacheSize
DECL|function|storeItem
DECL|function|tmpCacheFileName
DECL|function|uniqueFileName
DECL|function|updateMetaData
DECL|function|writeCompressedData
DECL|function|writeHeader
DECL|function|~QNetworkDiskCache
DECL|macro|CACHE_POSTFIX
DECL|macro|CACHE_VERSION
DECL|macro|DATA_DIR
DECL|macro|MAX_COMPRESSION_SIZE
DECL|macro|PREPARED_SLASH
